### ISSUE TITLE
Atlas error recording

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1003]
# Background

The long run mode in which Atlas will run is that it is provisioned by a Gateway that pays for infrastructure access on behalf of the user. A critical part of making this work well is that the Gateway Operator is able to monitor the performance the end user is experiencing in Atlas. It just so happens that this kind of monitoring would be extremely useful to us at this time, when we are effectively running the only Gateway. There are a variety of failures one can easily observe by trying to use Atlas, and there is no automated way of delivering an up to date view what kinds of failures are occurring across the user base at any given time. One prominent example is the extremely delayed loading of image assets

![Screenshot 2021-07-17 at 22 59 00](https://user-images.githubusercontent.com/437292/126049235-e6560ebf-cf5c-49cf-b62d-d626556ff3ff.png)

Being to monitor error events in particular would provide very useful live feedback to the storage & distribution lead in the DAO, and Jsgenesis staff.

# Proposal

1. Introduce basic error event monitoring reporting from Atlas about failures in the storage system. These should be capture-able in any sort of standardized event tracking system, which further would make it very practical to analyze, export, filter and visualize this data. We should not build our system, but rather allow Atlas to report to some sort of generic interface. If we can't make it generic, then we should just pick the standard used by some dominant solution. The primary errors we are interested in are storage asset loading which fails. It should cover all asset types (avatars, channel cover photos, previews, video media), on any screen, and it should include metadata about what provider failed (identified by worker id), for what asset. Another error we should track is playback failure that results from incompatible encoding, since we need a deeper understanding of how severe that problem is, and this requires more metadata bout the host as well.
2. Deploy an actual live dashboard on our website which both working group participants and Jsgensis staff can use to keep up to date on what is going wrong.

**Comment by kdembler** [comment]
Broken into separate milestone
