### ISSUE TITLE
Test out failure during upload

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1014]
Community member reported Atlas acting strangely when there was a connection problem during upload. We should test this scenario out and make any necessary changes if confirmed. Original message:

> I would like to suggest that the developers provide for the fact that the user may have communication interruptions and ensure that the download can continue after the interruption. What is happening now is like: I am uploading a large video. There is a connection break, but judging by the progress bar, the video continues to load. It reaches 100%. And hangs on it. It may take 5-10 minutes and nothing will happen. If you update it, the studio will ask you to reconnect.

**Comment by bedeho** [comment]
I also tried uploading today, lots of irregularities in the UX that are hard to describe in a reproducible way, beyond the infra possibly not performing well, so I think we may need to prioritize `My Uploads`.

**Comment by kdembler** [comment]
After creating the issue I've tested it out and was able to fully reproduce what was described, however the cause was strictly infra-related. Unless you mean some other issues than the one described above, I'm not sure how we will be able to alleviate that
