### ISSUE TITLE
Why does Atlas take so long to load?

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#105]
By load, I mean from time you try to resolve URL in your browser until it shows anything at all of our UI.

This could be an issue that only has to do with our deployment, but even then it would perhaps we worth improving, and if its due to some problem higher up in the infrastructure or app, then this certainly should be addressed at some point.

**Comment by kdembler** [comment]
It seems the initial render takes quite some time to finish (1-2s). We should be able to trim that down at least a bit, let's figure out where that comes from

**Comment by kdembler** [comment]
This has been mostly taken care of, closing for now
