### ISSUE TITLE
Graceful landing page video playback

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#106]
Right now, the playback of the cover video begins the moment the clip has been loaded, there are two problems with this.

1. The transition from loading to showing the cover photo appears instant, or at least very fast, can this be slowed down and have a fadein if it does not.
2. The user is unable to perceive the actual cover if they have fast connection, so it just jumps straight into the video directly while the entire scene is still loading, often when lots of preview videos have not yet been rendered. Overall it means that there is just a lot happening simultaneously, which slightly disorients the user on what is happening. We could instead let the cover sit for a moment after, even if the video is available, and then gracefully transition into playing the video at a later time so that this happens a little bit later than the entire scene getting rendered to begin with.

**Comment by kdembler** [comment]
`1.` It appears instant, because there isn't any transition at the moment. The cover image URL is hardcoded so that it's completely handled by the browser. Until we remove that hardcode, I think we should only do point `2.` here

**Comment by kdembler** [comment]
Done
