### ISSUE TITLE
Video player freezes for a split second when scrubbing/seeking on mobile

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1107]
It seems that when you change time on seek bar, the video frame freezes for a second but you still hear the video sound. 
This bug probably refers only to IOS, but it's worth testing also on android devices. You can find a video that shows the problem here: https://github.com/Joystream/atlas/pull/1104#pullrequestreview-722033989
Related to #1091

**Comment by dmtrjsg** [comment]
Re-tested and seems not to be overly jarring, the delay was not noticeable
