### ISSUE TITLE
Existing upload flow issues

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1108]
### Problem

With the current implementation of Atlas there exists one flaw which gives user a false understanding of the progress of uploading an asset. This spawns some confusion and undesired scenarios in the app. The core of the problem is that currently in Atlas we assume that `finished file upload = finished upload flow`, which isn't necessarily true. That's because even though the file was successfully uploaded to the storage provider, there is still some time period before the provider accepts the upload on-chain and query node processes that event. This opens up 2 scenarios in which the app may give users false understanding:

#### 1. Playing video right after upload
Let's assume that user published a new video and is currently waiting for the video file to finish uploading. At some point it does and the user gets information that the upload was successful and is finished. However, because it will take a moment for the asset to be accepted and reflected by the query node, if user tries to play the video in the Viewer experience, it will fail because the file is missing.

#### 2. Refreshing right after upload
Because of the reasons above, right after the upload is finished, query node will still report the asset as `PENDING` - not finished. When Atlas loads, it asks the query node for all unfinished uploads and presents them to the user as failed and waiting for upload resume. If the user refreshed right after the upload finished, Atlas will ask query node and get information that this asset has failed, even though it's just waiting for processing. This can give the user impression that something didn't work properly. If the user waits a couple seconds and refresh again, the asset will disappear from the missing list.

### Solution
The solution here is to fix the wrong assumption we had and be smarter about status of the upload. Firstly, we need another approach to deciding whether the upload is finished - it cannot rely solely on the file upload success, but also on the status reported by the query node. Secondly, we must have a mechanism to do a second check on uploads we assume as failed, to alleviate scenario #2. For that, when starting an upload we can save the liaison to the local storage and later send a HEAD request to that liaison to check whether the upload for that file was finished. In general, we should also improve the UI to better reflect the status of the upload.

**Comment by bedeho** [comment]
Excellent summary!

What should be done on the viewer side if someone lands on a video which is in this status? are we doing something for this?

**Comment by kdembler** [comment]
Yes, I think we agreed that @KubaMikolajczyk will add a player variant for this scenario

**Comment by KubaMikolajczyk** [comment]
UI/UX solutions to that problem will be defined and captured in issues below:
https://github.com/Joystream/atlas/issues/1063
https://github.com/Joystream/atlas/issues/1189
