### ISSUE TITLE
Video Content Pages implementation feedback

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1131]
Some visual issues I've noticed so far: (preview accessible at https://deploy-preview-1130--atlas-dev.netlify.app)

- [x] Language select is too tall:
<img width="353" alt="Screenshot 2021-08-09 at 12 54 11" src="https://user-images.githubusercontent.com/12646744/128696196-8cea944f-8f60-4b35-8b44-d5268441835b.png">
<img width="303" alt="Screenshot 2021-08-09 at 12 54 21" src="https://user-images.githubusercontent.com/12646744/128696217-cd6050bf-c6b6-49af-b839-3bfe46e7b5d9.png">

- [x] "Channels in your language" isn't properly aligned (text + select):
<img width="505" alt="Screenshot 2021-08-09 at 12 54 24" src="https://user-images.githubusercontent.com/12646744/128696292-922b7ef9-f9f1-4f9c-8ca5-d373bc487343.png">
<img width="967" alt="Screenshot 2021-08-09 at 12 54 29" src="https://user-images.githubusercontent.com/12646744/128696300-c7e5d457-3091-4fb8-9259-4a6112439744.png">

- [x] I don't think all the empty area next to channel preview should be clickable. Probably only the avatar and the title? Not sure, @KubaMikolajczyk your feedback would be appreciated here. (click anywhere in this area will trigger navigation)
<img width="1205" alt="Screenshot 2021-08-09 at 12 59 27" src="https://user-images.githubusercontent.com/12646744/128696558-8c92605d-74f1-44bc-9029-dbaf60ea65f0.png">

- [x] Seems the follower count isn't fetched properly for channels:

https://user-images.githubusercontent.com/12646744/128696691-3ebf066d-dec3-4104-a8b1-64f576161bd2.mov

- [x] Videos in the ranked carousel on mobile seem to have very restricted area for title+meta:
<img width="400" alt="IMG_5420E307823E-1" src="https://user-images.githubusercontent.com/12646744/128697148-647567a8-d8fa-4215-8a06-9c2770799400.jpeg">

- [x] When doing an initial page load, the "Official Joystream updates" section flashes on top of the screen only to be replaced by "Popular on Joystream". Where does this come from?

https://user-images.githubusercontent.com/12646744/128697497-bb20b194-cfe6-4749-8da9-d04400ce1ab9.mov

- [x] The carousel interaction when the last page is non-full is a bit misleading to me. Take a look at this scenario, the last (4th page) has only one item. When you get to the end and go back, looking at the indicator at the bottom, it seems like you've moved two pages of content back. If you press again, it seems like you're on the first page but even then you can press once more to reveal the first item. This will likely need some feedback from @KubaMikolajczyk as well. Maybe when at the end of the content, the "back button" should make the previous page to be fully shown and not always move by a fixed amount of items?

https://user-images.githubusercontent.com/12646744/128698082-413787e5-53b4-4eef-90d3-c1975b436300.mov

- [x] Mobile carousel shows only one item, the design specified a behaviour in which a part of the next item is also visible to show the user the content is scrollable. If it's complex, we can tackle that as part of post-sprint responsiveness update:
<img width="400" alt="IMG_C31F4B2ACE88-1" src="https://user-images.githubusercontent.com/12646744/128698417-0b359323-56e1-4b92-8518-90e85469aa34.jpeg">

**Comment by kdembler** [comment]
Additional points:

- [ ] Spacing of the title section for infinite grid is wrong. According to the design, there should be:
- 20px between header and divider
- 48px between diver and content<br><img width="647" alt="Screenshot 2021-08-13 at 11 42 01" src="https://user-images.githubusercontent.com/12646744/129338273-4d29ef7e-5774-4fa8-a7a0-1922b865264d.png">
- [ ] Spacing between content sections needs to be cleaned up. Design specifies constant 128px margin between each section. Implementation is very varying. We should make sure each `<section>` in app takes the correct amount of space (for example the carousel controls don't have the necessary vertical padding in the app), and then define a constant margin between them. This needs to be done for all the views
- [ ] "Official Joystream updates" shouldn't have "See all" button
- [ ] We're lacking "Discover new channels" section in `Home`
- [ ] "Official Joystream updates" and "Top 10 this week" in `Home` are in wrong order
- [ ] "New" icon in CTA is wrongly colored:<br><img width="145" alt="Screenshot 2021-08-13 at 12 01 25" src="https://user-images.githubusercontent.com/12646744/129340649-631e0a82-f31e-4415-acee-15775fa32b34.png">
- [ ] Browse channels icon in CTA has a wrong color
- [ ] We should remove the old `Videos` view
- [ ] `Top 10 Channels` header should be `Top 10 channels`
- [ ] `Discover channels` header should be `Discover new channels`
- [ ] CTA text doesn't have proper typography styles, it should use `h5` variant of `Text`

**Comment by drillprop** [comment]
> Additional points:
> 
> * [ ]  Spacing of the title section for infinite grid is wrong. According to the design, there should be:
> * 20px between header and divider
> * 48px between diver and content<img alt="Screenshot 2021-08-13 at 11 42 01" width="647" src="https://user-images.githubusercontent.com/12646744/129338273-4d29ef7e-5774-4fa8-a7a0-1922b865264d.png">
> * [ ]  Spacing between content sections needs to be cleaned up. Design specifies constant 128px margin between each section. Implementation is very varying. We should make sure each `<section>` in app takes the correct amount of space (for example the carousel controls don't have the necessary vertical padding in the app), and then define a constant margin between them. This needs to be done for all the views

https://github.com/Joystream/atlas/issues/1166

> * [ ]  "Official Joystream updates" shouldn't have "See all" button
> * [ ]  We're lacking "Discover new channels" section in `Home`
> * [ ]  `Top 10 Channels` header should be `Top 10 channels`
> * [ ]  `Discover channels` header should be `Discover new channels`
> * [ ]  "Official Joystream updates" and "Top 10 this week" in `Home` are in wrong order
> * [ ]  We should remove the old `Videos` view

https://github.com/Joystream/atlas/issues/1168

> * [ ]  "New" icon in CTA is wrongly colored:<img alt="Screenshot 2021-08-13 at 12 01 25" width="145" src="https://user-images.githubusercontent.com/12646744/129340649-631e0a82-f31e-4415-acee-15775fa32b34.png">
> * [ ]  Browse channels icon in CTA has a wrong color
> * [ ]  CTA text doesn't have proper typography styles, it should use `h5` variant of `Text`

https://github.com/Joystream/atlas/issues/1167
