### ISSUE TITLE
Discover page design

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1132]
The scope of this issue is to review, update and finalize the designs of the **Discover** page, formerly created by @KubaMikolajczyk, based on the feedback from Bedeho in #874 and the research done by @KubaMikolajczyk.

This includes:
- Creating a video category tile component and its variants,
- Proposing a logic for sorting video categories on the Discover page,
- Proposing new information to be displayed in each category.

**Comment by toiletgranny** [comment]
> **⚠️ This is part 1/2 of the update regarding the Discover & Category page designs. Once you're done with reviewing this, make sure to check out [part 2](https://github.com/Joystream/atlas/issues/1133) as well!**

@bedeho Here's the prototype to check out the new iteration for this page, and a video update to learn all about it.

- [Figma prototype](https://www.figma.com/proto/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?page-id=9147%3A79&node-id=12734%3A346828&viewport=357%2C48%2C0.35&scaling=min-zoom&starting-point-node-id=12734%3A346828)
- [Video update](https://play.joystream.org/video/5902) _(I apologize for the extreme noise in the background! Next time I'll use an external microphone.)_

Please, let me know if you have any questions, ideas, or other things you'd like to discuss. Once this is approved, I can proceed with RWD and preparations for the developer handoff. :)

**Comment by bedeho** [comment]
# Feedback

1. I think we can totally go for human curation, likely will be better quality and easier to execute on technically.
2. I think the presentation of each category is now much more effective in allow people to quickly glance over and identify what major categories exist and which are worth engaging with. The bigger size and bigger font helps a great deal. I am not sure the icons + colors do much heavy lifting here, but they look nice at any rate. However, I think the choice to use video shots, as well as the other rectangles, I think does not work very well. This imagery is highly complex and non-standardized across categories, it only serves to make it harder to distinguish what the theme of each category effectively. I think we need a consistent visual language here, which works in the same diretion as the consistency of the titles and icons. I think this still applies to the featured categories, but its less severe here, as there are so few of them and everything is so large. I don't see the content being displayed helping in any real way to allow the user to identify promising categories, it just adds time to processing.
3. I think it would be better if the featured categories overview would not require scrolling. The name of the game is speed and clarity to identify what is interesting, and having to navigate through works in the opposite direction, in particular when we will have such a small set of featured categories (3?).

**Comment by toiletgranny** [comment]
@bedeho Thanks for your feedback! Here's a prototype to check out a new iteration, and — again — a video update to learn all about it.

- [Video update](https://play.joystream.org/video/5957) (I'd recommend starting with this)
- [Figma prototype](https://www.figma.com/proto/UdBMxrLspjcf6IVYYJS8YP/Page-Discover-and-Video-category?node-id=1%3A9808&viewport=376%2C48%2C0.11&scaling=min-zoom&starting-point-node-id=1%3A10593) (Use left and right arrows to navigate between all the screens you saw me showcasing in the video update)

**Comment by bedeho** [comment]
# Feedback

Phenomenal work, and perfect video, telling a story about what you tried and why makes it 10x easier to understand what problems you are trying to solve and why.

Overall I think that really the name of the game here is making this entire scene as easy to process quickly as possible, and for that reason I think that some of the new variations introduced here perhaps don't support that goal sufficiently well
- The featured section that requires interaction, or perhaps the expiry of lon lasting timers, takes too much work or time, respectively. It looks great, but unfortunately I think there is a risk of engagement being very low.
- The greyed out imagery, while better than before, still makes the scene very busy, and you are ultimately left trying to process the names, not the images.

For this reason, I think its best to go with
- No pictures on category cards: perhaps there is some room to adjust the presentation with this in mind, but I think they looked pretty effective also as you suggested them.
- Featured categories just makes each card big, no interaction required: https://www.figma.com/proto/56eC3mJS9VbaVAfA5d9y0V/%5BPage%5D-Discover-%26-Video-category?node-id=240%3A17063&viewport=376%2C48%2C0.24&scaling=min-zoom&starting-point-node-id=202%3A1634

**Comment by kdembler** [comment]
#### My 2 cents:

I really like _something_ representing the category card, I think they may look a bit dull without anything other than icon and text? IMO 👇 looks really nice and my visual focus is on titles and icons, I actually noticed that images are there only after hovering over one of the tiles.

<img width="1342" alt="Screenshot 2021-08-18 at 13 33 15" src="https://user-images.githubusercontent.com/12646744/129891056-340c3ee2-5d5b-4c28-ac51-3bb0fb0e651a.png">

Regarding featured categories, was wondering about the layout of those. My guess is that the number of those will change but I guess we could just use regular grid when there's even number and elevate one on top if there's odd number of them.

**Comment by bedeho** [comment]
> I really like something representing the category card, I think they may look a bit dull without anything other than icon and text?

Ok, my conviction is not this strong, lets go with that and see then :)

**Comment by toiletgranny** [comment]
@bedeho Thanks for the feedback. I'll try to briefly mention my way of arriving at final recommendations in future video updates, if that's helpful to you. :) I'm also really glad to hear you decided to give the imagery on category cards a try. 🎉 I know Miłosz and Kuba also agree that having images (especially when they're muted by default) doesn't really affect the overall readability, but can help greatly in quickly distinguishing category cards from each other.

@kdembler, thanks for stepping in. I think you're correct in regards to the grid layout of the featured categories section. I'll try to come up with a bulletproof logic (based on CSS grid) to make sure increasing/decreasing the number of featured categories won't harm the layout.

**Comment by toiletgranny** [comment]
We met with @kdembler and @eldiegod earlier today to discuss implementation. Designs, prototype, and the documentation for the Discover page can be found here — https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Page-Discover-and-Video-category?node-id=1%3A26288
