### ISSUE TITLE
Hide empty categories when browsing

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#115]
Most categories will start out empty, currently this makes the browsing tab much less functional, so I think we need to hide categories here that have less than some lower bound number of videos, e.g. 0.

**Comment by kdembler** [comment]
To implement this, it'd make most sense to add some kind of filtering on the query node side. Otherwise, we'd have to fetch videos for each category just to tell whether there are _any_

**Comment by bedeho** [comment]
I assumed this sort of reverse lookup was already possible, will create a query node issue as well then.
