### ISSUE TITLE
"Up next" offering to play the same video that was finished

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#1164]
Two example videos (from the same channel):
https://play.joystream.org/video/5566
https://play.joystream.org/video/5746

![image](https://user-images.githubusercontent.com/50830161/129344667-233bacef-2a17-4685-942f-d7fba5e35280.png)

As shown in the image, these videos both queue the `up next` video to be the same video that is already playing. Once the countdown finishes, they do not load another video.

**Comment by kdembler** [comment]
Thanks for the report, I've seen this as well but wasn't able to find link for reproduction later!
