### ISSUE TITLE
Failed scrubbing

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1178]
If you are playing back the video, and if part of the video has not yet been loaded and you scrub to this part of the video, the playback does not continue even when that part of the video has been loaded, this is quite annoying when you are trying to get to a particularly part of the video, and you end up having to press play again.

**Update**
Browser: Firefox 90.0.2 (64 bit)

**Comment by kdembler** [comment]
I haven't seen that behaviour, it always continues the playback for me. Is this something you are aware of @drillprop?

**Comment by drillprop** [comment]
wasn't aware at all, but managed to reproduce this. It seems that it's happening only on firefox. Scrubbing unfortunately is really buggy right now and needs some refactoring. I will try to find a solution to resolve this issue
