### ISSUE TITLE
Update video view design aspect ratio

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#118]
The video view (one with the video player) in the current design assumes an uncommon video ratio, causing the implemented screen to look unattractive with a more realistic aspect ratio:

<img width="1774" alt="Screenshot 2020-09-07 at 12 33 56 PM" src="https://user-images.githubusercontent.com/12646744/92378661-6f711080-f106-11ea-800e-bc5cd1fea144.png">

The design should probably be updated to match a 16:9 video aspect ratio and better accommodate different screen sizes

Created off of #57

**Comment by dmtrjsg** [comment]
Will be tackled in a Theatre mode (dedicated) + some comments next to it.
