### ISSUE TITLE
Playing video right after upload

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1189]
This issue is related to first scenario from : https://github.com/Joystream/atlas/issues/1108

>  ### Playing video right after upload

> Let's assume that user published a new video and is currently waiting for the video file to finish uploading. At some point it does and the user gets information that the upload was successful and is finished. However, because it will take a moment for the asset to be accepted and reflected by the query node, if user tries to play the video in the Viewer experience, it will fail because the file is missing.

This issue is meant to deal with improving the UI to better deal with the problem described above - probably designing a special state for video player would be the best solution for this problem.

**Comment by bedeho** [comment]
# Feedback

Not sure if I was supposed to give feedback here in this issue, but didn't find anywhere else.

- Looks great, but I prefer the bigger variation!
- Do we have some state like this for when videos are in the `My Videos` tab also? I think that is needed. This variation was for a the video page itself.

**Comment by KubaMikolajczyk** [comment]
The bigger variation it is then!
For my videos video tile when its being upoloaded we have a tile like this on the prototype below. (Please use "r" key to refresh the prototype whenever you like) - prototype link: [LINK](https://www.figma.com/proto/mMGcjK0usOHzKXAwcBdwiv/[-10]-Upload-flow-improvements?page-id=3%3A202&node-id=53%3A14419&viewport=300%2C48%2C0.03&scaling=min-zoom&starting-point-node-id=53%3A13741&show-proto-sidebar=1)

**Comment by KubaMikolajczyk** [comment]
Upload flow video update
https://www.loom.com/share/e748fd67207f4f5fb7ca8005a4d32f69

**Comment by kdembler** [comment]
Designed & implemented
