### ISSUE TITLE
Spice up the README

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#12]
Why don't we add a pretty App preview shot to spice up the README, will evoke interest for newcomers.

**Comment by kdembler** [comment]
We could also add a link to deployed version and add some info in general. Current README wasn't changed since extraction from the monorepo, possibly could use some information about what Atlas/Joystream, some links to docs, etc.

**Comment by bedeho** [comment]
Bumping this issue again.

Could make the README slightly more appealing to new devs arriving, for example by having some nice glossy high resolution product screenshots and relevant badges. Here are some aspirational examples.
- https://github.com/webtorrent/webtorrent-desktop
- https://github.com/atom/atom

**Comment by kdembler** [comment]
Worked on in #557
