### ISSUE TITLE
Discrepancies on the popular page

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1219]
There appear to be a significant number of discrepancies  between the design (right) and the implementation (left)?

![Screenshot 2021-08-21 at 07 13 38](https://user-images.githubusercontent.com/437292/130311484-de3dda99-e382-4957-a39b-736ca527a612.png)

1. Featured videos are actually smaller than the non-featured videos, this seems wrong, and the design does not look that way.
2. The degree of horizontal overlap between the number and the video.
3. The total vertical space between the two video sections, top 10 and popular. It was already problematically large in the design, now it just appears to be a huge loss of critical space. I think even the design should be adjusted here, its just so wasteful without any counterbalancing payoff.
4. The vertical offset of the page title `Popular on Joystream`.
5. Scroller (already mentioned in another issue).

**Comment by bedeho** [comment]
It actually appears there is a similar set of issues on the channels page


![Screenshot 2021-08-21 at 07 34 40](https://user-images.githubusercontent.com/437292/130311702-e10933c4-e1a1-400d-969c-605d9320b583.png)

**Comment by kdembler** [comment]
1. That's not entirely true, as it depends on the breakpoint. Take a look at this design:<br><img width="849" alt="Screenshot 2021-08-24 at 12 01 39" src="https://user-images.githubusercontent.com/12646744/130597820-85288517-0b00-4371-8099-c90f6bcf6b52.png"> We will be adjusting those a bit though
2. I think it's almost the same? Also breakpoints differences, like above
3. Agreed, we'll clean this up
4. True
5. Fixed already (not deployed yet)
