### ISSUE TITLE
Skeleton loaders are wrongly placed on VideoHero

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1221]
Take a look at the video, placeholders are a little bit off. We should move them down.

https://user-images.githubusercontent.com/51168865/130319487-3da4e951-8c36-4bfb-800c-b175ca751ef0.mov

**Comment by kdembler** [comment]
Good catch. Also, I'm not sure if we actually the two loaders at the bottom? It doesn't seem there's any content that they represent, there are only buttons under the title

**Comment by kdembler** [comment]
Good catch. Also, I'm not sure if we actually the two loaders at the bottom? It doesn't seem there's any content that they represent, there are only buttons under the title. ping @KubaMikolajczyk

**Comment by KubaMikolajczyk** [comment]
Yes I agree with the above 👆
