### ISSUE TITLE
Introduce user session recording

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1228]
Requirements from designers:

🔴 Must-haves:
1. Access to user session recordings for both Viewer and Publisher experiences,
2. Filtering user session recordings by demographics and technical data (localization, browser, etc).

🟢 Nice-to-haves:
1. Filtering user session recordings by events, such as clicking on a specific button, or an input field (specified as a CSS class or a custom selector),
2. Heat maps, Click maps, Scroll maps,
3. Saving sets of user session recording fitlers to be used later (these are called “Segments” in FullStory),
4. Options for gathering feedback from users (example: https://www.hotjar.com/tour/#incoming-feedback),
5. User behavior (like heat map) on control and test while A/B testing.

**Comment by rafalpawlow** [comment]
All solutions below have must-haves, nice-to-haves are listed for each of them

**VWO**
https://vwo.com/insights/

* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Saving sets of user session recording filters to be used later (these are called “Segments” in FullStory),
* Options for gathering feedback from users

**Hotjar**
https://www.hotjar.com/
* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Saving sets of user session recording filters to be used later (these are called “Segments” in FullStory),
* Options for gathering feedback from users
* Filtering user session recordings by events, such as clicking on a specific button, or an input field (specified as a CSS class or a custom selector),


**Uxtweak**
https://www.uxtweak.com/
* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Options for gathering feedback from users
* Filtering user session recordings by events, such as clicking on a specific button, or an input field (specified as a CSS class or a custom selector),

**inspectlet**
https://www.inspectlet.com/
* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Options for gathering feedback from users

**Mouseflow**
https://mouseflow.com/

* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Saving sets of user session recording filters to be used later (these are called “Segments” in FullStory),
* Options for gathering feedback from users

**Matomo**
https://matomo.org/

* User behavior (like heat map) on control and test while A/B testing
* Heat maps, Click maps, Scroll maps,
* Saving sets of user session recording filters to be used later (these are called “Segments” in FullStory),
