### ISSUE TITLE
Error when making changes to `VideoPlayer.tsx`

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1234]
Every time we update code in `VideoPlayer.tsx` we are getting: 
![image](https://user-images.githubusercontent.com/51168865/130456376-d02181fc-07bf-46ba-85e3-278517122e12.png)
and on every change, we need to refresh the site to see our changes. It could be really annoying.

At first, I thought that, fixing circular dependencies will resolve this issue, but I was wrong.
To fix that we probably need to revisit and check how we initialize `videojs` instance.

**Comment by rafalpawlow** [comment]
@dmtrjsg Why did we close this issue?

**Comment by drillprop** [comment]
Reopened. The problem still exists, unfortunately

**Comment by dmtrjsg** [comment]
@rafalpawlow not sure rn, perhaps as a fluid bug during the grooming session on the 24th.. just to be reopened today 😇

**Comment by drillprop** [comment]
This is probably caused by `playerInstance.dispose()` that we're calling in `useEffect` cleanup function of `useVideojsPlayer` hook. Dispose is removing the video element which results in crashing the app.
