### ISSUE TITLE
Video content pages implementation review

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1236]
After video content pages implementation review some issues were spotted: 
1. Play and sound buttons are 39 px H - in designs we use 48 px for wide screens and on smaller screens 40px
1. When we load the page the buttons in video hero are hidden - they only appear when video is playing - we could just disable them and enable when video loads it would be much smoother
1. I love how the carousel with big numbers works on desktop great job <3
1. Carousel with official joystream updates cut the last video on desktop which shouldnt happen if we want to scroll by sections (because if we scroll by section we will skip the last video which is cut in half - it will just scroll past it to the next one in queue)
1. We display empty channels and those with a low count of videos on them - is there any easy workaround that we could use if we decided not to implement video count?
1. In sections where we have channels filtered by language - can we check if we have any channel in the language and if we dont then do not display an option to choose that language from the list? Only show it when we really have channels to display - as currently it can be really misleading :) 
1. In layout below 1415 when we switch to displaying 3 video tiles in a row in all video content sections like followed channels, popular on joystream etc - could we display 3 rows instead of 2 to show more content?
1. In layout below 1091 when we switch to 2 video in a row - could we display 4 rows in above sections instead of 2 to show more content? / also in this width displaying 2 rows of videos fo channels in channel sections like discover new channel would be good
1. When we switch to one video in a row view on really small widths like on mobile we currently display 2 videos in vertical rows in sections like followed channels or popular on joystream - could we display 6 like in designs to show more content before pushing show more button
1. On those mobile widths can we show 3 videos vertically for each channel in sections like discover new channels like in designs
1. I think that video still have the title , channel name, upload and views scaled proportionally to the width of the tile and not using 2 fixed sizes like advised in designs - it creates this issue that if the tile is really big the text content is really big competing in visual hierarchy with section titles / on the other hand if the tiles are really small the titles become too small - is this missed in implementation or decided not to use that approach?
1. I love cta cards - looks awesome - could we change the size of the typo on them on smaller screen widths not to make them span their text to two lines and be more consistent in visual hierarchy with section titles which are getting smaller on smaller screen widths?

**Comment by kdembler** [comment]
I took a liberty of editing your issue to add numbers so I can address points separately :)

`1.` Sizing of buttons across screen sizes is something we should discuss during our sync tomorrow. For now we'll change the size to 48px. (https://github.com/Joystream/atlas/issues/1243)

`2.` Also https://github.com/Joystream/atlas/issues/1243

`4.` Tracked here: #1212 

`5.` I'm not really sure what we could do about those

`6.` That's possible but a bit complex to achieve, I think costs>benefits here

`7. - 10.` Yes, very good points, I was aware we don't have this yet, we should definitely improve (https://github.com/Joystream/atlas/issues/1245)

`11.` That was missed (https://github.com/Joystream/atlas/issues/1246)

`12.` Sure, https://github.com/Joystream/atlas/issues/1247

**Comment by KubaMikolajczyk** [comment]
Great job!
 1, 2, 4 ,11, 12 were implemented and everything looks good there :) 
 Spotted issues 5 & 6 are not going to be tackled - maybe we can think about dealing with them in future.
 Issues 7- 10 are yet to be implemented.
