### ISSUE TITLE
Viewer channel implementation review

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1237]
During implementation review of viewer channel page few issues were spotted:
- When I load a channel by clicking its name from any section on video content pages it loads only 6 videos - I have to refresh to see that the channel has more ?? bug?
- When I follow channel and then unfollow it the dialog displayed says: "Would you consider staying? 0 Keep following for more fresh content! " - I bet user won't get what this 0 means - also iI believe we decided to change the way we display information here to : title : Do you want to unfollow? desc: Unfollowing [nameofchannel] will no longer show new content from this channel on your following page. It can be found here https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=11921%3A424903
- If I expand the search and then unclick out of it it will stay expanded instead of collapsing
- If I search I have to type whole word for example "Micro" to find everything that has this word in the name - wdyt about searching for parts of words as well couse micromanagement wouldnt be found this way - if I have video called "newly married" by typing "new" it would display the video 
- In layout below 1024px the search bar and sorting bar is not spaced from the spacer and tab bar - it looks a bit dense there
- In layout below 654 we display only 4 videos in vertical row - maybe it would be a good idea to make it at least 6 to allow user to have some more content on one page
- In the same mobile layout - the pagination has no spacing, displays only one page at a time, and is really dense even if there is still space to display 3 pages at least 
- Pagination component should take advantage of available space to display the largest number of page number buttons that can fit on the screen so on the smallest screen we support 320px we can still fit a version with two icon buttons  - you can find examples here https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=110%3A18271 - please note that because of it all secondary icon buttons (also destructive and warning) disabled state was changed from 50% opacity to 25%.
- On mobile if I search for a keyword "sort by" function dissapears - and whole layout jumps a bit - maybe we could leave the "sort by" function visible if we dont hide it when opening search bar
- Unfollow Dialog is displayed in a really high position both on desktop and mobile - it would be much better to display it centered in the middle of the screens like in designs 
- If we open the dropdown sort by the blue outline styling is an on click effect - so when it opens it immidiatelly dissapears and outline becomes white again - we could leave it blue as long as it is open - use it for focused state like in designs to indicate that this is the current action  (also the blue outline stays on the select when we unclick it - could then turn white as it comes back to default state)

**Comment by kdembler** [comment]
> When I load a channel by clicking its name from any section on video content pages it loads only 6 videos - I have to refresh to see that the channel has more ?? bug?

Has been fixed since

> When I follow channel and then unfollow it the dialog displayed says...

That 0 shouldn't be there but yeah, let's clean this up in general: #1293 

> If I expand the search and then unclick out of it it will stay expanded instead of collapsing

#1295 

> If I search I have to type whole word for example "Micro" to find everything that has this word in the name - wdyt about searching for parts of words as well couse micromanagement wouldnt be found this way - if I have video called "newly married" by typing "new" it would display the video

This is out of our hands, that's how our querying backend does search now and we likely won't change that in the near future

> In layout below 1024px the search bar and sorting bar is not spaced from the spacer and tab bar - it looks a bit dense there

This should be already fixed

> In layout below 654 we display only 4 videos in vertical row - maybe it would be a good idea to make it at least 6 to allow user to have some more content on one page

We currently have task in progress, we'll include this there: #1245 

> In the same mobile layout - the pagination has no spacing, displays only one page at a time, and is really dense even if there is still space to display 3 pages at least

This should be already fixed

> Pagination component should take advantage of available space to display the largest number of page number buttons that can fit on the screen so on the smallest screen we support 320px we can still fit a version with two icon buttons - you can find examples here https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=110%3A18271 - please note that because of it all secondary icon buttons (also destructive and warning) disabled state was changed from 50% opacity to 25%.

https://github.com/Joystream/atlas/issues/1300 and https://github.com/Joystream/atlas/issues/1299


> On mobile if I search for a keyword "sort by" function dissapears - and whole layout jumps a bit - maybe we could leave the "sort by" function visible if we dont hide it when opening search bar

I think we should likely hide it because we cannot apply sorting to search results atm. We will make the layout not jump though - https://github.com/Joystream/atlas/issues/1298

> Unfollow Dialog is displayed in a really high position both on desktop and mobile - it would be much better to display it centered in the middle of the screens like in designs

https://github.com/Joystream/atlas/issues/1297

> If we open the dropdown sort by the blue outline styling is an on click effect - so when it opens it immidiatelly dissapears and outline becomes white again - we could leave it blue as long as it is open - use it for focused state like in designs to indicate that this is the current action (also the blue outline stays on the select when we unclick it - could then turn white as it comes back to default state)

Sounds good - https://github.com/Joystream/atlas/issues/1296
