### ISSUE TITLE
Introduce within channel search

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#125]
Searching free text for currently selected tab.

Probably should be done after https://github.com/Joystream/atlas/issues/124, and depends on this new feature in Hydra https://github.com/Joystream/hydra/issues/127.

**Comment by kdembler** [comment]
@bedeho Could you expand on that a bit? I don't really understand what this issue is about

**Comment by kdembler** [comment]
Let's create a new issue for this once we do viewer refresh
