### ISSUE TITLE
Vidoe listing on channel broken

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1256]
This seems totally broken, the set of visible videos, including pagination, changes as you resize the viewport. As always, I am on FireFox.

**Comment by kdembler** [comment]
Can you explain a bit more, possibly with some example? I'm not really sure what the problem is

**Comment by kdembler** [comment]
Nevermind, managed to reproduce. Seems the problem happens when you enter the channel view linked from some other view. Sometimes only some of the videos will show up and if you refersh, more will appear

**Comment by bedeho** [comment]
Yes sorry, I should have perhaps described that part also. I guess I just assumed it was a universal problem, not depending on what path you took, really weird.
