### ISSUE TITLE
Update step component in MultiFileSelect

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1271]
![image](https://user-images.githubusercontent.com/51168865/131311185-f85b5242-1267-49ac-8f8a-a6fd378c97e7.png)

We should also check the Figma prototype. There are a lot of changes there, make sure that everything is included(animations, file titles, border bottom, etc)

**Comment by KubaMikolajczyk** [comment]
Great job with the animation! Looks snapy!

How about this little jump when selecting a video 👇 first when selected we can see whole file name and the loader is a little bit smaller than the check icon that's coming after it - we should make them both the same size to avoid the jump - and secondly the icon button with the bin appearing on the right side of that file step and visibly cutting the file name - we could just reserve a space for the button on the right side and truncate the file name as soon as it appears in the file step :) wdyt?

https://user-images.githubusercontent.com/31144205/133477078-54254ca8-c31b-42e7-b879-4dbff9a10b37.mov
