### ISSUE TITLE
Add right-click menu on video previews

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#129]
A very common interaction in the browser will be to open video playback in a new tab, currently it's missing, and it makes discovery quite cumbersome, as you cannot use the natural queuing function of the browser tabs. Both the image and the title should open a menu, and also the channel avatar, allowing you to open the channel in another tab.

For the Electron version this will not be available, but we can deal with that later. There is a watchlist feature designed which could partially serve this end, but its not clear whether how well that would work either.

**Comment by kdembler** [comment]
This is something that would be automatically fixed by #36, closing in favour of that
