### ISSUE TITLE
Introduce client-side watchlist

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#130]
# Design

## Screens

Can be found on board, this is the primary screen for when its open and being inspected

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=1009%3A4777

But changes are also required to the video preview.

## Transitions

We are missing major transitions, described here: https://github.com/Joystream/atlas/issues/131

# Business Logic

- Should reuse whatever client-side state abstraction which is introduced in the personalization release: https://github.com/Joystream/atlas/issues/30.
- An item is automatically removed from watchlist when its played until the end.
- Ability to add videos to the watchlist from playback.

**Comment by kdembler** [comment]
May be blocked atm due to changes in design
