### ISSUE TITLE
Watchlist design enhancements

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#131]
The current watchlist design

- has no transition for when videos are added to the watchlist
- has no transition for when videos are removed from the watchlist
- does not indicate the size of the watchlist when its closed
- there should be an icon or something on the playback screen to add a video to the watchlist which currently is not, if it is on the watch list, we need some transition which opens the watchlist and scrolls to the location of the video and some how emphasizes it.

**Comment by KubaMikolajczyk** [comment]
This relates to old watchlist design which was never implemented - it will be redesigned in the future. This issue is no longer relevant.
