### ISSUE TITLE
Search sprint scope

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1320]
## Intro:
Since the search experience is inextricably linked to the top navigation bar (because it holds the search box, from which the searching experience starts) my suggestion would be to include changes to the top bar component in this sprint, as well.

![CleanShot 2021-09-02 at 12 07 35@2x](https://user-images.githubusercontent.com/35307309/131825611-a0e26ae5-5122-43d3-9765-352ebde27ddb.png)

## Related issues & other resources:
- https://github.com/Joystream/atlas/issues/874
- https://github.com/Joystream/atlas/issues/23
- https://github.com/Joystream/atlas/issues/44
- https://github.com/Joystream/atlas/issues/9
- https://github.com/Joystream/atlas/issues/194
- https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=7797%3A1384

## Scope:
1. _(1 day)_ Research and compare search experience on other most popular video platforms,
2. _(~~4~~ 6 days, including reviews & developer handoff)_ Redesign the top navigation bar along with the search input field featuring the following functionalities:
   - Local search history/autocomplete,
   - Clear,
   - Close
3. _(~~2~~ 3 days, including reviews & developer handoff)_ Design a bottom navigation bar, specifically for mobile devices, placed at the bottom of the viewport (example below), 
![CleanShot 2021-09-02 at 14 16 1](https://user-images.githubusercontent.com/35307309/131842095-cef4faf7-2f2c-45a5-970b-b956a9016b3c.png)

4. _(~~5~~ 6 days, including reviews & developer handoff)_
Redesign the search results page featuring the following functionalities:
   - Separating search results by their type (videos/channels),
   - Filtering search results in a similar (or even exactly the same) fashion as the "All videos" section on the recently designed Video category page,
   - Error, loading & empty states.

**In total: 16 days**

### Other notes

After syncing with @kdembler I've found out that due to technical reasons:
- We can not offer an autocomplete based on other users' search phrases,
- Due to the above, in case of no results for a specific search, we cannot offer results for similar searches,
- At the same time, we can offer an autocomplete with a list of specific results matching the search phrase,
- The only search we can support as of now is an exact search, meaning that eg. if you search for "joy", the video with "enjoy" in its title would not get picked up in search results,
- The only way search results can be sorted as of now is by "best match".

**Comment by kdembler** [comment]
Looks good from my perspective! Have one question though: what do we need bottom navigation bar for? All the current navigation is done via a hamburger-icon-expanded sidebar anyway. What would go into that bottom navbar?

**Comment by toiletgranny** [comment]
Great question, @kdembler, I should have probably explained this earlier. 

The main reason is ergonomics. We do have the hamburger menu, which I imagine would still remain as our main navigation on mobile devices. But because of its placement, it's very difficult to reach with your thumb while using your phone single-handed.

Having that bottom navigation bar, displayed up until a certain breakpoint, with links to **main** Atlas views, **including search**, would offer a more convenient experience. Most popular social media platforms provide the bottom navigation bar in their mobile web apps (not to be confused with native mobile apps): YouTube and Twitter are some of my favorite examples. 

Another reason would be offering Atlas as a PWA on mobile devices in the future. Having that bottom navigation bar implemented would make the PWA experience so much closer to the native mobile app experience.

**Comment by bedeho** [comment]
Thanks @toiletgranny , excellent summary.
