### ISSUE TITLE
Add video count to channel preview

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#133]
The original design had total view count across all videos, like this

![Screenshot 2020-12-09 at 16 36 42](https://user-images.githubusercontent.com/437292/101650965-d28f7d80-3a3c-11eb-8c65-1831adc7e060.png)

but this is less useful now where its mostly about just directing people to channels where there is any content at all. In the future we can change this if it makes sense, also based on more information about how trustworthy our final follower/view count infra actually will be.

**Comment by kdembler** [comment]
Just a note, this is currently blocked as there is no way to query total channel views

**Comment by kdembler** [comment]
~This likely requires some support from the query node side to supply the number of videos as a channel field.~

~We can mock it for the time being though. This will require adding a new field to the schema (at `api/schemas/extendedQueryNode.graphql`), including it in the queries, running codegen and then returning that field from the mocked resolver and displaying its value~

After all, we can use a simple query to get videos count of a channel, something like this:
```graphql
query GetChannelVideosCount ($channelId: ID!) {
  videosConnection(first:0, where: { channelId_eq: $channelId }) {
    totalCount
  }
}
```
