### ISSUE TITLE
Storybook controls not working properly for lots of components

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1333]
If you take a look at some storybook components, lots of controls are disabled or not working properly. For instance, this is from Snackbar: 
![image](https://user-images.githubusercontent.com/51168865/132311441-637d2656-dad9-47a4-9a0c-bd96ab94ca4a.png)
Also, we are getting lots of console warnings about deprecated properties 
![image](https://user-images.githubusercontent.com/51168865/132312028-0988da7d-6912-49d4-b493-e32eee302c28.png)
This is the effect of updating the storybook(the API changed a bit) which happened together with the vite migration.

We should go through all of these storybook components, update them, and make sure that everything works as before.

**Comment by drillprop** [comment]
The problem is more complex than I initially thought. With our current setup inferring args don't work because storybook uses `react-docgen-typescript` under the hood to get those and this library doesn't work with vite.
Found https://www.npmjs.com/package/react-docgen-typescript-vite-plugin but it also doesn't work well, for some reason it wrongly infers args, every arg is basically an object, which is wrong. 
We could declare args explicitly for every story, but it will require writing a lot of code, and other than that it is highly possible that in the future we will at some point forget updating stories when updating components. So, this is not a great option too. 

We need to find a solution to bring back inferring args. Maybe there is some library out there that could be working for us, or we could just wait for the next major storybook update, which hopefully fixes that

**Comment by dmtrjsg** [comment]
⚠️ Blocked by libraries we use..

**Comment by dmtrjsg** [comment]
We are waiting for the relerase on the vendor side.

**Comment by eldiegod** [comment]
close this? @kdembler

**Comment by kdembler** [comment]
I think we could repurpose this issue to go through existing components and make sure the stories work properly. I think we may have some where we unnecessarily define the props manually.
