### ISSUE TITLE
Ideas for community-managed featured content in Atlas

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1425]
## The goal

The goal of this issue is to describe possible solutions for letting the Joystream community manage some featured content inside Atlas. This includes the existing video hero, but also features yet to be implemented, like the featured videos for video category. Managing all of that curated content by the dev team isn't really feasible for a long term and it's a great place for community contribution, we just need to enable it.

### Static hosted JSON files

This is the approach we use today for the main page video hero. We have a Jsgenesis-owned bucket storage where we keep a single JSON file that describes the video hero - it provides the ID of the main video, title to be displayed in the hero and also a URL for the cut video file to be played in background. We could leverage the same approach for other data, like featured videos for a specific category. There could be a single/multiple JSON file(s) describing the list of videos, in the same manner as we do with the video hero. Community members could be given access to update those files and Atlas would display the updated data. The issue with this approach is the access control. Because of the authentication of the bucket storage, it's not easy to gain/revoke access for community members. Access is done via a secret key that needs to be generated by the server's admin (Mokhtar). So the easiest approach would be to generate one secret for the community, but then this secret is valid forever until someone manually revokes it. So if there was a single role in the community responsible for this, whenever the person fulfilling this role changes, we should revoke&generate new key to ensure only one person has access. This is cumbersome because we need to ask Mokhtar.

#### Advantages
- Easy to build

#### Disadvantages 
- Problematic access control

### Gateway-like featured content server

Another way we could go about this is to build a very basic version of a gateway node that would keep info about featured content inside its database. Along with some simple authentication mechanism, the featured content could be updated via an API and the access control could be fine-tuned to the project needs. Atlas would then query this data via GraphQL, like it does with all the other data sources (query node & Orion). However, assuming some featured videos would also need to have a custom short cut of the video, we still need some kind of storage to let the community upload those files, as doing file hosting as part of this server wouldn't be really feasible.

#### Advantages
- We take the first iterative step in building the gateway node
- We use the same approach to fetch the data as with the other data sources
- We're closer to the final solution (not as temporary as static JSON files)
- Could use account-based access control

#### Disadvantages
- Needs to be built (although I think we could reuse some parts of Orion so not a giant effort, I estimate something like 1-2 days)
- We still need some kind of storage for the video files so it only solves the metadata part of the problem

### Summary

I think both alternatives make sense and I'd be really happy to start building the gateway node. However, the problematic part is that we still need to host the video files and it wouldn't be straightforward to make this part of the content network atm. Mixed approach would work as well (metadata in gateway, files in static storage) although access control is still a problem. So likely the first approach makes most sense at the moment.

**Comment by bedeho** [comment]
Thanks for the overview, really helpful.

- I think that the access control model can be really simple:
  - we control what credentials (password, key,..) have access at any given time,
  - we chose to give a single trusted community member X access
  - community, as represented by an changing set of curators, asks X to make updates when needed.
- I think storing assets on the gateway, or some bucket controlled by X, either one works fine, I don't see a downside. The assets would in any case never be stored on the platform storage system, that seems wrong for how things work in production.

**Comment by kdembler** [comment]
Another idea came to my head. Maybe instead of using the current storage, we would create some Github repo that community would be given access to. Then Atlas could query files directly from that repo. One issue that can be experienced in this scenario is poor performance of downloading files from Github. We would need to test out caching inside the app. We can cache the JSON files for sure, it may be harder for the media files, but it may not be that bad. This solution kinda takes care of the access control issue, in a sense that we can easily control who has write access to the repo. Downside is that all contributors would need to have Github accounts.

**Comment by bedeho** [comment]
- It would be great to do something which is a bit more aligned with the future, in particular that this alternative does not save that much time or complexity.
- Are you sure large media files work well on Github, in the sense that its easy to put on there and download at decent speed?
- Believe it or not, a lot of people find using Git+Github very confusing, and do not have accounts to begin with, so we are still back in the case where some key people will be responsible for the publishing none the less here.

**Comment by kdembler** [comment]
> Are you sure large media files work well on Github, in the sense that its easy to put on there and download at decent speed?

I'm entirely unsure, I expressed that in my last comment.

Github may be confusing, true, but unfortunately I think all of the available short-term solutions will be.

I think the only solution aligned with the future is the gateway node with some simple account system. Is that what you're suggesting? Generally, if you're fine with this, I'd be happy to go with this. Basically we build very simple backend capable of storing those JSONs describing the featured content. Additionally we have some bucket storage for hosting the media files themselves. Community would be given logins/password for the backend and most likely interact with it via some HTTP client. If we wanted to, we could also create some very simple frontend.

**Comment by kdembler** [comment]
Discussion continued in https://github.com/Joystream/atlas/issues/1486
