### ISSUE TITLE
Fix mobile version of video player

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#144]
There are quite a few discrepancies, not least of which being the size of the title, viewport margin and the way the playback controls work, 

![Screenshot 2020-12-10 at 11 33 43](https://user-images.githubusercontent.com/437292/101760802-a4ad4600-3adb-11eb-9b82-093ea251dd95.png)

while this is the design

![Screenshot 2020-12-10 at 11 34 05](https://user-images.githubusercontent.com/437292/101760828-b0007180-3adb-11eb-84f2-70077882b1e1.png)

look at designs here, 

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=1086%3A4948

but note that there are genuine things we do not want from the design just yet like the three "purple" buttons, the chromecast control and the settings control.

**Comment by kdembler** [comment]
Please note that I'm not sure how easy those video player controls changes will be. We're using a video player library, and while so far we've been able to style it the way we wanted to, that may not always be the case. It's worth looking into, but may be non-trivial

**Comment by kdembler** [comment]
We should first try and see how feasible this is. If it's going to take >4h then we shouldn't pursue it at the time.

Take a look at `src/shared/components/VideoPlayer/VideoPlayer.style.tsx` - this contains styles to override the default video player look. It should be possible to add media queries there to make mobile style more in line with the design (doesn't have to be perfect)
