### ISSUE TITLE
Let's change the meta theme color to black? 

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1444]
## Context

Since the release of the new Safari on iPhones, iPads, and Macs, more attention is put on the `theme-color` meta tag, which can now affect the browser's presence. 

![image](https://user-images.githubusercontent.com/35307309/135466996-99e5e72e-ea37-4af3-8c6b-2ca307b236e0.png)

## Proposal
Because of the above, it becomes more apparent that we might consider updating our theme color, defined under the `<head>` tag, so that it matches Atlas body background-color: black `#000`. Currently, it's set to Joystream's primary brand color: blue.

`<meta name="theme-color" content="#4038FF">` -> `<meta name="theme-color" content="#000">`

| | Before | After (Preview) |
| -- | -- | -- |
| Desktop | <img width="1526" alt="Zrzut ekranu 2021-09-30 o 14 56 34" src="https://user-images.githubusercontent.com/35307309/135463257-5aba72f7-4381-4fff-9682-bfc21db0f8da.png"> | <img width="1526" alt="Zrzut ekranu 2021-09-30 o 15 02 48" src="https://user-images.githubusercontent.com/35307309/135463275-f16ba8be-b005-448a-82bd-78bc0434fb10.png"> |
| Mobile | ![IMG_4867](https://user-images.githubusercontent.com/35307309/135463568-b8e1f023-b7a1-45fc-94ef-4d24807bd48b.PNG) | ![IMG_4866](https://user-images.githubusercontent.com/35307309/135463595-0fe2b316-9026-4256-ae09-6e0ffe0dc7b5.PNG)

## Reasoning

The new implementation of the `<meta>` tag in Safari aims to _blur_ the boundary between the website and the browser's UI. In this context, having a strong blue color set as our theme color does the opposite, as it's making the boundary between the website and the browser's UI more noticeable, than ever. I would even say it's distracting when casually browsing Atlas on iOS Safari.

As the main background color of our app is a pure black color, it makes sense to have it set as our theme, so that the browser's UI feels like a natural "extension" of the app.

_Please note that this change should not affect how the app is rendered in other browsers, eg. Chrome._

**Comment by kdembler** [comment]
I'm not entirely sure the goal of this feature (new only in Safari, has been supported by Android browsers for some time) is to actually blur the boundary between the website and browser. My understanding is that this feature lets you make your page stand out in a way, offer further customization of the experience. There's a lot of pages that use their primary color as theme color, checkout out those examples:
- https://www.tripadvisor.com
- https://css-tricks.com
- https://www.swyx.io
- https://kentcdodds.com

I'm not saying we shouldn't change the color to black, just that maybe it's not an easy decision.

**Comment by kdembler** [comment]
Gave it some more thought, maybe we could tone down the primary color a bit to still give a sense of brand without too much visual disruption? `blue-700` looks nice to me

**Comment by KubaMikolajczyk** [comment]
Maybe we could try using some other shade of our neutrals palette? It will still look aesthetically pleasing, it will be brand-aligned and we would get rid of this really prominent blue outline which is being a real eye-catcher on the original variant. Wdyt?

**Comment by kdembler** [comment]
I don't think neutral color will be brand-aligned here, blue is what gives it the Joystream-feel for me. You think the darker shades of blue still don't work?

**Comment by toiletgranny** [comment]
> I'm not entirely sure the goal of this feature [...] is to actually blur the boundary between the website and browser. [...] 
There's a lot of pages that use their primary color as theme color

@kdembler Of course, there are many ways the theme color in the `<meta>` tag can be used. Having watched Apple's ["Design for Safari 15" WWDC keynote video](https://developer.apple.com/videos/play/wwdc2021/10029/), I'm fairly confident the primary use case they had in mind was actually blending the browser with the page, like in these examples: [Vimeo](https://vimeo.com), [Spotify](https://spotify.com), [Frame.io](https://frame.io), [Tidal](https://tidal.com), [Netflix](https://netflix.com), or [Fubiz](http://fubiz.net), [Forbes](https://forbes.com), [Engadget](https://engadget.com).

My concern with the blue (or its shades) is that the browser's UI might not be the best _canvas_ for manifesting the brand personality. At least not everywhere. In our case:
- sticking with the primary blue color at the top results in an over-prominent and eye-catching top header, which reduces the prominence of primary actions (buttons) used within in the app,
- using darker shades of blue, as suggested by @kdembler, might come down to a personal preference. To me, it looks a bit repulsive, especially given that we're not really using darker shades of the primary blue as backgrounds anywhere within the app.

I like @KubaMikolajczyk's idea about using darker shades from the neutral palette. Ultimately, my recommendation would be as follows:
- `black`,
- `neutral-800`,
- `neutral-900`,
- `neutral-700`.

**Comment by kdembler** [comment]
It seems the meta color is used both ways, I could provide many more examples with contrasting colors as well. If black is your recommendation though, I won't argue, so we'll just update it :)
