### ISSUE TITLE
Missing feedback on reupload

### ISSUE THREAD

**Issue by rafalpawlow** [Joystream/atlas#1460]
@KubaMikolajczyk  When you interrupt the upload of a large file and try to do a reupload, there is no feedback that something is happening. After a long while the file starts uploading. I think we need some loader or some indicator that file waiting for upload.

https://user-images.githubusercontent.com/13706246/136208147-e52df16f-9f8f-46a9-a60d-370c2eb5ffbb.mov

**Comment by drillprop** [comment]
This is my proposition on how we could tackle this. No additional design is required.

https://user-images.githubusercontent.com/51168865/136209840-ac93fd17-cb11-489c-9acf-0d419ce5a90d.mov

**Comment by kdembler** [comment]
Very good point, I agree! For context, while waiting we're calculating hash of the file the user chosen to make sure it's the same file as the one chosen when doing initial upload. If it matches, we start uploading, if not, we tell the user that we have the wrong file. So I think what @drillprop suggested here works well
