### ISSUE TITLE
Delegating one designer to work solely on the design system

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1482]
# Intro
Below is a proposal for a change in the design team composition, allowing for one designer to be exclusively responsible for the Atlas design system.

### TL;DR
We have a lot of cleaning up to do with our components library and the design system as a whole. The design and tech debt in this is starting to slow us down (both designers and engineers). We imagine having one designer focused solely on this so that the others can proceed clear-minded with ongoing sprints and so that developers have one go-to person with design system-related questions and requests. We can start right away.

# What?
First things first, let’s make sure we all understand what a design system is. In a nutshell, a design system could be a collection of:
- a library of reusable UI components,
- a style guide (or a set of design tokens)
- documentation and guidelines on common product-specific UX/UI patterns,
- UX copy writing guidelines,
- etc.

The goal of this proposal is to have one member of the Atlas design team focused solely on the Atlas design system. The scope of work for such a person would include (not limited to):
- Refactoring currently implemented components, based on design & tech team requests, or their own initiative,
- Creating new components, based on design team requests,
- Supervising and discussing the implementation of new components with the tech team,
- Writing down consistent documentation for already existing and newly created components,
- Supervising and discussing the implementation of design tokens in Atlas.
- And more.

Because of my prior work experience, the field of expertise, and interests, together with Klaudiusz, Kuba, and Nina we agreed that I might be the best fit for this role. That’s why it’s me writing this.

# Why?
So far, contributions to the Atlas design system were made by whoever was the designer/developer with a need or an idea of adding or changing something about the Atlas design system.

While it did work okay at the beginning, in a team of 2 designers, as the product was becoming more complex and the team was becoming bigger, the lack of clearly defined rules has slowly started to lead us into duplication of efforts and lack of clarity in our daily work, slowing us all down.

More specific examples of the things mentioned above include lack of documentation and usage guidelines for UI components, duplicated UI components, legacy UI components not updated due to the lack of time, components implementation not matching the designs, and more.

We expect these struggles to only get deeper with each passing day, as the project evolves and no action is taken.

Large and mature in-house product design departments, eg. at Netflix, or Spotify, handle this by having dedicated teams of designers, engineers, project managers, product managers, etc. working on in-house design systems alone. Some of our largest clients at Netguru treat their design systems as standalone products.

While at Joystream/Atlas we might not be in a position to have an entire design system team yet, having a dedicated designer might be a good starting point. (Hopefully, this could be followed by a dedicated developer focused on the design system in the future.)

We hope that such a team composition could free up the rest of the designers (Kuba, Nina, potentially someone else in the future) from the burden of keeping the design system up to date or discussing legacy components with developers, allowing them to shift their focus back on ongoing sprints (eg. NFT) and creating room for rapid and creative exploration.

On the other side of things, developers could have a go-to person for everything concerning our design system, not worrying about their questions/requests affecting the progress of ongoing sprints.

As per the design system itself, it is expected that once led by a single person, it’s going to become more consistent, clear, and intuitive to use with time, which could also translate to fast and easy customization for people forking Atlas.

# How?
This is an optional read. Below is a rough plan of how I could start working in the new role:
1. First, a clear and intuitive design system contribution process might need to be established, so that tech and design teams know how to ask for help or request a change in the design system.
2. Knowing there’s a lot of UI components requiring are immediate attention, these need to be gathered on a list and prioritized.
3. Before the actual refactoring can happen, a process of creating, implementing, and documenting design system changes needs to be written down as well, so that we don’t end up repeating the same mistakes.
4. Next, we need to be mindful of new additions that will surely need to be made with NFT sprints. New components will need to be consulted with product designers, added, and documented in our system.

# What are the implications?
Giving this plan a go means there’s one less designer working directly on NFT and any other future sprint. However, it’s important to note that:
- This does not necessarily translate to the proportionally decreased velocity of the design team. At the end of the day, we’re all heading towards the same goals, with the design system being a tool allowing us to get there faster.
- The design system designer will still contribute to ongoing sprints indirectly, by working on design system changes implied by ongoing sprints.

# Summary
In terms of what we need from you, at the very least, we would hope to get your approval for this. We would love to get to know your thoughts on this in case you have any questions or doubts so that we can discuss this further.

**Comment by kdembler** [comment]
@toiletgranny I think we can close this issue now?

**Comment by toiletgranny** [comment]
Yes, of coursr! Closing now! :)
