### ISSUE TITLE
Make the channel edit view stretch full width when creating first channel

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1485]
Seems like there is a margin on the left hand side when trying to create your first channel during onboarding, where the consumer side menu would normally be.

![Screenshot 2021-10-13 at 17 21 41](https://user-images.githubusercontent.com/437292/137163679-d6853266-c6e4-4e58-a94a-3e01c3856a7b.png)

**Comment by kdembler** [comment]
We should be able to improve that by making the view stretch the full width - one issue is that we need to make sure there are no layout shifts happening here. After the user actually creates the channel, the sidenav will appear but it shouldn't shrink the content - it may be visually unpleasing. What we could is make sure we first navigate the user to my videos and only then trigger the sidnav. May require some testing to make sure there aren't any visual issues
