### ISSUE TITLE
Process for community to manage featured content in Atlas

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1486]
### Goal

The goal for this issue is to describe (figure out?) a process to let the Joystream community manage featured content in Atlas autonomously, without the need of JSG involvement. This is supposed to simulate what in the future will likely be featured content managed by gateway operator.

### Status quo

Currently the only piece of content in Atlas that is managed by the community is the video hero displayed on top of the home page*. You can find more info about how this works [here](https://github.com/Joystream/atlas/blob/master/docs/video-hero.md). As part of this process you could distinct three roles that take part in it:
1. _Content curators_ - members of the community responsible for preparing suggestions of new featured content. Those members periodically prepare new ideas for video hero
2. _Reviewer_ - once content curators prepare new video hero ideas, they send those to JSG for review and approval
3. _Content admin_ - once approved, the new video hero info needs to be sent to someone who has write access to the server that holds this data to make the change go live. Currently that's me (@kdembler)

This process doesn't work great long-term though. As part of new changes we're introducing to Atlas, we'd like to include some new types of featured content. We'd like the community to be able to manage this content directly, without a need to ask someone from JSG to update files on a remote server.

_* Actually there is also a set of "featured videos" but this is managed directly via blockchain so let's ignore this part for the moment. If this new process plays out well, we will likely move the current global featured videos to be managed with this process as well._

### A way forward

To improve this, I'd like to propose the following changes to the current process:
1. Drop requirement of review by JSG for some kinds of content. I think video hero changes should still get approval first but community should be autonomous to change other types of featured content.
2. Move the _content admin_ role from JSG hands to some trusted community member(s). They would receive all the necessary technical instructions/keys and would be able to autonomously update the featured content.
3. Improve the way we persist data about featured content. Instead of hosting static JSON files which can be error-prone, this functionality will be offered by Orion instead. This way _content admins_ can use GraphQL request to update featured content info. However, static hosting would still be required for media files.

#### Updating video hero
1. _Content curators_ prepare ideas for new video hero. That includes picking videos to be featured but also preparing short cuts of videos to be featured on the front page. They can use an arbitrary internal process to achieve this
2.  _Content curators_ send the suggestion for new video hero to the designated _reviewer_ (this will likely be a JSG member)
3. Once approved, _content curators_ send the video hero info (video id, title, prepared video file) to _content admin_ to make the updates go live.
4. _Content admin_ uses their access to upload prepared video file to static hosting operated by JSG. Then they use their Orion access to send a GraphQL request to update the video hero.
5. The change is live in Atlas right away.

#### Updating featured videos for a video category
1. _Content curators_ prepare list of featured videos for a video category. This list may include some current entries but should be complete (i.e. not a change set, but a full list of new videos that should be featured). For the most prominent featured videos, _content curators_ also prepare cut video files for display in a video-hero-like section.
2. Since this content type doesn't require review, _content curators_ send the necessary information (list of video IDs + prepared video files for few of those videos) directly to the _content admin_.
3. _Content admin_ uploads necessary files to the static hosting and runs an Orion request to update the featured content.
4. The change is live in Atlas right away.

### Summary
I think this new process should give community more autonomy in updating the featured content while making sure it's not too cumbersome for any side of the process.

I'd love to hear some feedback/suggestions on how to improve this!

**Comment by bwhm** [comment]
I think this is a reasonable approach, and don't see any big issues making it happen pretty quickly.

- The `content admin` would probably be the `curator lead`? 

As long as there are clear instructions on how to do this, I think they'd do just fine :)

**Comment by toiletgranny** [comment]
> Content curators prepare ideas for new video hero. That includes picking videos to be featured but also preparing short cuts of videos to be featured on the front page.

From a designer's perspective, I'm especially interested in knowing how the preparation of these short cuts could work, from a technical point of view. 
- Would there be an option to provide start and end timestamps of the video, so that the original video file can be later played within that timeframe? 
- Or does that mean having content curators ​manually trimming down a video file, in a video editing software, and saving it as a new video file?

**Comment by kdembler** [comment]
That'd be second option for now, they would need to manually trim down the video

**Comment by kdembler** [comment]
Documented in `docs` now - https://github.com/Joystream/atlas/blob/master/docs/community/featured-content.md
