### ISSUE TITLE
NFT Video Page Design

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1498]
### Info:

"Video NFT" is a part of the NFT experience MVP scope.
This particular issue is a communication container for the whole "VIdeo NFT" experience.
"Video NFT" refers to NFT experience on Video player page.

### Features that must be included in MVP scope:

Display NFT status for a video for content viewer
- [x] #1934
- [x] #1935
- [x] #1936
- [x] #1937
- [x] #1938
- [x] #1939
- [x] #1940
- [x] #1941
- [x] #1942
- [x] #1949

TBC @Lenorette @toiletgranny  it seems to me we'd need to include Publisher:Buy Now, Publisher:Change price for NFTs to this epic or is it handled elsewhere?

**Comment by Lenorette** [comment]
Video update 
https://www.loom.com/share/92d2d7e47a244cf2822dc2feefabd936?sharedAppSource=team_library

**Comment by bedeho** [comment]
# Feedback

- First off, this was so exciting, my favourite NFT video yet, seeing it come together in the primary consumption experience, and not just in a marketplace like context.
- It would be great if you could provide Figma links as well when you post these.
- Be aware that not only do we not currently support comments, but we also dont support like/dislike. We can possibly try to look into adding this, but it would risk bloating scope and delaying, so perhaps we can add that all in another sprint and release? If we do this, we need some variation where this is not present.
- Its not clear to me whether we can support sharing right now, I think @kdembler should weigh in.
- I assume history is closed by default? just want to confirm.
- Widget in general looks great, all state variations looks very sharp from what I could see.
- I believe that as a matter of priority, Atlas is video consumption experienced on the viewer side, not an NFT marketplace. This means that most people on this screen are trying to engage with the content, the community, the creator and the people. The NFT asset is there to enhance this experience, and the actual transactional activity will only rarely be relevant. I believe this design violates this in two ways
  - it emphasises the detailed state and actions assocaied with the NFT more than showing adjacent content to the user. I think here we should be looking to separate the most basic NFT information, i.e. there is an NFT owned by X at last price Y, from all the other assocaited information and actions. Then rare user who want to engage with the NFT details can choose to reveal that on demand.

  - it does not give sufficient prominence to the owner of the NFT in the overall scene, as distinct from all the other NFT details. As stated in the brief, within communities, the primary value of an NFT for the owner is visibility which signals something in a given community. Right now, the owner will get ignored almost all of the time. I think, like the prior point emphasises, try to find a way to lift out the ownership and put it in a really prominent visual location, but without compromising the consumption objectives of the normal viewer. Some of the other NFT preview variations you have done show some ways of doing this I think.
- I am still missing some reply to my inquiry about whether owners should be able to set some kind of metadata or message associated with their message, which can be presented or be part of decorating the viwer experience. I think I asked @KubaMikolajczyk about this, he said he would explore, but not sure what the outcome was, and implications for this page.
- Are we still planning to have a dedicated NFT page? I am not sure its needed, just wondering to make sure I am synched on the full context.
- I see we have introduced non-cinema mode here, that is super interesting, and I think we do indeed need it. But have you thought about how to manage the size and aspect ratio of the video container, depending on the aspect ratio and resolution of the underlying video media?
- I hope we can have a solid animation on transition cinema <-> normal.

**Comment by kdembler** [comment]
Great video Nina, really like the updated video page!

First off to answer @bedeho question about sharing: we could support that, but I'm not sure whether we should. Adding buttons to direct you to new twitter/facebook post with a link to the video shouldn't really be an issue, however those posts would be really poorly looking. I think we should postpone this until we can get better social previews (https://github.com/Joystream/atlas/issues/416). If we do wait, then the feature will have a proper wow effect once we release

Also some other general points from my side:
- When providing mock prices, I think we should use something more realistic in terms of amount of JOY. Assuming JOY token is not divisible, I guess we can assume that the granularity will be pretty high, i.e. price for one token will likely be expressed in cents so prices for NFTs could likely reach thousands or potentially even millions of JOYs, it'd be good to take that into account
- I'm not sure if this is the right issue to put this comment on (if not, please direct me to the right place 🙏): I'm not sure whether we should put such granular timers on tiles for videos that have NFT auction ending soon. Current designs display very accurate time left, including seconds left. My fear is that if a lot of previews like this are shown in the grid, all the changes in timers may create unwanted visual clutter, users may get distracted from content by timers constantly changing. Maybe instead we could show a less accurate time, like for example "~2 hrs" or something alike?

**Comment by Lenorette** [comment]
>It would be great if you could provide Figma links as well when you post these.

I'm soooo soryy... I forgot to do that...
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/%5BPage%5D-Video?node-id=954%3A40327

> Be aware that not only do we not currently support comments, but we also dont support like/dislike. We can possibly try to look into adding this, but it would risk bloating scope and delaying, so perhaps we can add that all in another sprint and release? If we do this, we need some variation where this is not present.

Sure I remember that we do not support any of those but I think we really should focus on them in near future if possible. I'll delete that for now. 

> I assume history is closed by default? just want to confirm.

Yes, I think it should be hidden/closed by default.  

> I believe that as a matter of priority, Atlas is video consumption experienced on the viewer side, not an NFT marketplace. This means that most people on this screen are trying to engage with the content, the community, the creator and the people. The NFT asset is there to enhance this experience, and the actual transactional activity will only rarely be relevant. I believe this design violates this in two ways

Thanks for that, I'll try to explore it more!

>I am still missing some reply to my inquiry about whether owners should be able to set some kind of metadata or message associated with their message, which can be presented or be part of decorating the viwer experience. I think I asked @KubaMikolajczyk about this, he said he would explore, but not sure what the outcome was, and implications for this page.

Thanks for bringing that up, I wasn't aware of it. We talked about it today a little and we think that maybe it would be better to include that in post MVP phase for NFTs. We see some possible dangers with something like that and we think it would require more exporation. Some users could buy NFT to just write down some offensive stuff or disturbing things which creator may not want to see. There ofcourse could be some special process for them to add text where Creator would have to confirm to it at the end but we think it's not super necessary for our MVP and it could just prolong design process without bringing too much value now. - But please let me know what do you think about it

>Are we still planning to have a dedicated NFT page? I am not sure its needed, just wondering to make sure I am synched on the full context.

I think that we don't need it now. If in future users would like to see more NFT related info or something then we could think about creating separate page. But for now I think we are good with displaying NFT details only on video page

> I see we have introduced non-cinema mode here, that is super interesting, and I think we do indeed need it. But have you thought about how to manage the size and aspect ratio of the video container, depending on the aspect ratio and resolution of the underlying video media?

Not yet, as usual, screens for different resolutions will be prepared when we will agree on the content of the page.

Share button
> I think we should postpone this until we can get better social previews (#416). If we do wait, then the feature will have a proper wow effect once we release

Yeah, I think we could wait with it, but just don't let it be forgotten :D 

>I'm not sure if this is the right issue to put this comment on (if not, please direct me to the right place 🙏): I'm not sure whether we should put such granular timers on tiles for videos that have NFT auction ending soon. Current designs display very accurate time left, including seconds left. My fear is that if a lot of previews like this are shown in the grid, all the changes in timers may create unwanted visual clutter, users may get distracted from content by timers constantly changing. Maybe instead we could show a less accurate time, like for example "~2 hrs" or something alike?

I think it all depends on how accurate we want to be with displaying the time of the auction. Imo the most accurate is the best one, users will know exactly how much time left they have without a need to go into a Video Page and check the details. 
Visually I think it wouldn't bother me that much but ofc it is something best seen live. But check this out https://rarible.com/?statuses[]=AUCTION here is how it's displayed on Rarible - just scroll down till Explore section. All NFTs have timer counting down, I think it's not that horrible.
But please let me know what do you think and if you still see it as a danger I'll try to find some better solution for that.

**Comment by bedeho** [comment]
All makes sense, thank you!

**Comment by Lenorette** [comment]
Hey @bedeho

I've explored more the positioning of NFT widget and layout of information in it, according to your previous comment. I also gather feedback from the team about it, and we all think that it would be better not to hide NFT informations and actions. We think it's gonna be more valuable to show them, we gonna have better chance that users will try to engage with NFTs - if we gonna hide those information most of users will not even try to expand it to see what's hidden there. I think we should go with that design for the beginning to highlight NFT existence, and try to engage users to interact with it. If in future users will feedback on it that they are not really interested in NFTs and we should not push it, I think then we could rethink then. 
I've changed a little information structure in the widget, so now Owner is more highlighted.

Maybe it's only my opinion but when I scroll the prototype I don't mind seeing this widget at the top of "similar content" on the right side of the screen, I don't think it's interrupting my "video watching" experience, I also don't think that this widget takes to much space. But this is only my personal opinion :D 

Also here are links to "prototype" you can just see individual screens and get better feeling
Version we prefer https://www.figma.com/proto/sMydmZJlzhK91FTIPOd7D2/%5BPage%5D-Video?page-id=787%3A29126&node-id=954%3A40327&viewport=300%2C48%2C0.44&scaling=min-zoom&starting-point-node-id=989%3A42174&show-proto-sidebar=1
Explorations https://www.figma.com/proto/sMydmZJlzhK91FTIPOd7D2/%5BPage%5D-Video?page-id=787%3A29126&node-id=1025%3A47632&viewport=300%2C48%2C0.44&scaling=min-zoom&starting-point-node-id=1025%3A47632&show-proto-sidebar=1

If you really don't feel that, I also tried to place this widget below video description - this is more aligned with what you mentioned before, that we are a video platform with additional possibility to by NFTs. 
You can check it here https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/%5BPage%5D-Video?node-id=1054%3A53999

So as always let me know what do you think about it and which version do you prefer :)

**Comment by bedeho** [comment]
1) I appreciate the careful consideration and exploration, thank you.
2) This is hard to judge up-front, I def. see the value on higlighting NFT interaction - in particular when its one of our unique features compared to YT, and also our recommendation system is likely to be pretty subpar for a substantial period of time, both because the tech is not there - and because our pool of content is small, so the cost of crowding out this space is not so high. In the end, I am a bit concerned still, but I think we should go with your recommendation here, given your careful consideration.

**Comment by Lenorette** [comment]
Link to final designs in Figma
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1%3A688

**Comment by Lenorette** [comment]
Here's final video walkthrough in loom
https://www.loom.com/share/6217a943951e4f6eb46401c57c457c22?sharedAppSource=team_library
