### ISSUE TITLE
Tracking Issue: Issuing NFT

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1499]
Add content later here from @KubaMikolajczyk

**Comment by bedeho** [comment]
# Note

- Great review of other platforms, love that, but let us not get too constrained by it either unless there is a good reason. There is lots of experimentation going on around how to use NFTs, well beyond what those simple marketplaces offer, and we are in a very specific context which we should also take into account.

- I am just terribly sorry for not having the documentation ready in the handbook, I am making this a top priority. The fact that you did this much useful work only based on the user stories is quite impressive.

- I think I would have done a better job here giving feedback on the core design here if I knew what level of detail to consider. The Figma link was not shared, so that also made me a bit suspicious that you wanted me to only address high level issues. At any rate, I addressed some more specific details as well.

# Feedback

- I think it makes sense to remove "play in joystream" action from the dropdown, it follows a consistent pattern. I am actually not sure we even need to put secondary actions in the dropdown, but downside seems limited.

- There is in principle no requirement to wait for a video's assets to get uploaded successfully to issue an NFT for that video.

- The steps involved after sending the transaction to publish a video is the same for every blockchain operation, including issuing NFTs.

- I think we should def. expose whitelists for auctions. I think analogy for this feature is how an artist will want to curate who actually gets to own their art, in order to create exclusivity which does not only depend on access to money, but also social status. This is an important dimension of how sales are done in the art world, not everyone is invited to everything, even if they could afford it. You could also imagine a creator for example rewarding people in their community by having access to a future auction. 

- Royalties are part of the system, the docs are just incomplete, I will prioritise completing them asap.

- Minimal bid step is a bit more esoteric, but most real world auctions have this, you cannot bid 1 cent more than the last person in any real world auction. We could try to no make it a prominent choice, for example making it automatically 5% of the starting price, and then allowing the person to override if they want?

- Buy Now price during an auction I think also serves a useful function in some cases. Certainly in open auctions, there should be a way to guarantee that you get the item, as there is no ending time which would otherwise guarantee it. But even for English auctions it can be a useful way to ensure that, in some cases, get a higher price if you know there are a handful of buyer who are extremely interested in getting the item, but perhaps do not have that big of a budget. This feature could help lock in the buy now price from them because they cannot risk loosing to someone with deeper pockets, but without this feature they would perhaps not even bother, because they know they could easily loose.

- I totally agree with the idea of moving the NFT issuance experince out of the same publishing screen for creating the video, it got too crowded and required lots of scrollingin a small space. However, I wonder whether we should not instead just make it a second step of the process itself, as I presume a very large fraction of videos will ahve NFTs. With the current approach, you will have to first make a transaction, with all the delays that incurs, then go back and fire off a second flow. It would be great if this could all be done in separate steps before publishing even. It would certainly be fine to not do it if it bloats the scope, but in the future that sounds better.

- NFT metadata mutability: so far, I am not actually seeing any NFT specific metadata in what you are showing, the metadata you reference is the video metadata, and this will always remain mutable, with or without an NFT. We could change this, but I am not sure. If we had explicit metadata just for the NFT, we could still allow that to also be changed after issuance, for example so long as the NFT was owned by the channel owner.

- Reservation price and starting price, i.e. the minimum valid price of a bid, is really the same thing, is it not? our system only has the latter.

- Keep in mind that issuing an NFT is not the same as picking whether what kind of auction there should be. An NFT can be issued in an idle state, where there is no scheduled auction or anythign else, and the NFT is owned by the channel owner. There are also other states you can pick, like offer to send to sell to some specific other person at a given price and a instant buy now mode. This will become more clear when I have the docs ready. It also means that if we are going to do the designs in a roughly forward compatibel way, we need more than a single dimmed out COMING SOON button.

- Issuing experience:
  - I think this experience really would benefit from being a full screen emersive experience, possibly broken up in multiple steps. Right now, the small scrollable space where things will cahgne substantailly based on what you select as the type is a bit rough. In general I feel that unless one is dealing with dynamic user provided content of unpredictable size, avoiding scrolling as pattern is highly desirable in almost all cases.
  - Recall from above, issuing an NFT does not require starting an auction, per say.
  - The top section showing the information about the video appears to me to not really do anything useful for the publisher in this context, and its taking the most valuable space. If we actually had distinct NFT metadata which gave a different presentation format for the NFT, then that could make more sense, but when its just presenting the same data the puplisher has already. As I mentioned, all of the video metadat is still mutable even after the NFT is issued, but even if it was not, I would have elected to show the final preview on the last screen during a confirmation step, rather than up front when the user is trying to make a bunch of key decisions.
  - By virtue of the above, removing he warning should be fine.


- NFT metadata: I was expecting you guys to perhaps suggest some interesting ideas here that would be making NFTs in our specific context more useful. For example, if you recall when you did the first few concept designs a few months back, the owner could specify a message associated with the NFT, and this could be displayed in the video experience. To me, that seems potentially interesting and easy enough that it would be wortht trying. Recall that many NFTs have these sorts of features extending well beyond the bare bones image NFTs that have become very well known. The most prominent example is probably the original Cryptokitties NFTs which allowed for breeding. But even beyond this, there could be room for more mundane metadata that would be helpful for allowing the NFT to be shared and consumed. So for example, having the option of a sort of preview or trailer video for the full video could be very useful as the primary artefact that is shared outside of the platform, as sharing the full video which could be quite long, and so there would be no succinct way to get an impression about what it was about. For image NFTs this problem does not exist, but for videos it might. The trailer could also be just be the creator talking about the primary video and epxlaining how, why, when it was made, etc. Anyway, these are just ideas. Wanted to draw your attention to this sort opportunitiy as well. Of course we could sidestep all of this for a later design sprint also, but want to hear your thoughts.

- Could it make sense to have a standalone sort of public page for each NFT, as distinct from the consumption experience? Remember that the video page has lots of things on it, in particular in the future, including suggestions for other videos, comment fields, social token stuff, etc. So could it be advisable to have a dedicated NFT page for each video which is solely dedicated to giving a public page where you can see everything about the NFT, including hte history, bids, auction status, etc. This sort of page could also allow us to avoid cluttering the player page too badly, and instead only show some key points about the NFT on the video page.

- I think it would be useful to see, on the My Videos page, what videos have or have not issued NFTs, even without hovering. For example if you uploaded a bunch of videos without NFTs over time, and then you are trying to recall which ones those are, then it would be useful to not have to go and hover over all of the videos one by one to see the state of the secondary action button.

**Comment by bedeho** [comment]
Follow up question: _should_ video metadata, including the primary video asset and cover photo, be mutable if there is a live NFT on the video? currently it is, butperhaps it should not? we can change this!

**Comment by KubaMikolajczyk** [comment]
Thank you for such detailed feedback!

So sorry for not leaving the link to the Figma file (It's mainly because the frames I presented here are still on the exploration page), but here they are if you want to take a look at them -> [Link to figma](https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=452%3A28416)

### My responses to feedback:

> I think it makes sense to remove "play in joystream" action from the dropdown, it follows a consistent pattern. I am actually not sure we even need to put secondary actions in the dropdown, but the downside seems limited.

We can keep the secondary actions in the context menu then discoverability of those actions will be higher and keeping up to 5 links there should not be bad for our UX. 

> There is in principle no requirement to wait for a video's assets to get uploaded successfully to issue an NFT for that video.

Noted. In that case, we have this covered.

> The steps involved after sending the transaction to publish a video is the same for every blockchain operation, including issuing NFTs.

That's great! So we can reuse the same modal steps we used before!

> I think we should def. expose whitelists for auctions. I think analogy for this feature is how an artist will want to curate who actually gets to own their art, in order to create exclusivity which does not only depend on access to money, but also social status. This is an important dimension of how sales are done in the art world, not everyone is invited to everything, even if they could afford it. You could also imagine a creator for example rewarding people in their community by having access to a future auction.

Alright! Should this whitelisting be done by entering the wallet addresses of those people who are allowed to buy? Or do you have in mind another value that we can use to whitelist them? (email? member name?)

> Royalties are part of the system, the docs are just incomplete, I will prioritise completing them asap.

Sure!

> Minimal bid step is a bit more esoteric, but most real world auctions have this, you cannot bid 1 cent more than the last person in any real world auction. We could try to no make it a prominent choice, for example making it automatically 5% of the starting price, and then allowing the person to override if they want?

Yes, I agree with the word "esoteric" here 😅 And I can see that this concept can also be pretty abstract for the user - even if we create a field to set it and by default, it would be 5% of the starting price then:
1. Shouldn't it be optional?
2. Should the user be able to choose the percent incrementation / fixed incrementation (eg. each bid step must be 2 JOY larger than the one before)
3. Or maybe we should use only incrementation by a fixed amount instead of using percentages?

>Buy Now price during an auction I think also serves a useful function in some cases. Certainly in open auctions, there should be a way to guarantee that you get the item, as there is no ending time which would otherwise guarantee it. But even for English auctions it can be a useful way to ensure that, in some cases, get a higher price if you know there are a handful of buyer who are extremely interested in getting the item, but perhaps do not have that big of a budget. This feature could help lock in the buy now price from them because they cannot risk loosing to someone with deeper pockets, but without this feature they would perhaps not even bother, because they know they could easily loose.

So the way you see it would be handling this like on more traditional marketplace like Ebay 
[Link to Ebay screenshot in Figma](https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=492%3A43241) 
So we would not have two separate modes one for auction and one for selling for fixed price but rather connect them both and allow user to choose which one to enable - only auction , auction + buy now , or only buy now.
Tell me wdyt?

>I totally agree with the idea of moving the NFT issuance experince out of the same publishing screen for creating the video, it got too crowded and required lots of scrollingin a small space. However, I wonder whether we should not instead just make it a second step of the process itself, as I presume a very large fraction of videos will ahve NFTs. With the current approach, you will have to first make a transaction, with all the delays that incurs, then go back and fire off a second flow. It would be great if this could all be done in separate steps before publishing even. It would certainly be fine to not do it if it bloats the scope, but in the future that sounds better.

I would have to explore possibilities here and discover how we could do this - maybe we could move this NFT issuance experience to a "video workspace" type container and make it as a second optional step of video creation process & as a separate flow that an NFT owner can enter from other place in the platform. Im on it!

>NFT metadata mutability: so far, I am not actually seeing any NFT specific metadata in what you are showing, the metadata you reference is the video metadata, and this will always remain mutable, with or without an NFT. We could change this, but I am not sure. If we had explicit metadata just for the NFT, we could still allow that to also be changed after issuance, for example so long as the NFT was owned by the channel owner.

I'm rising this topic as this can get really dangerous - NFT as a non-fungible tokens can be owned by someone else than the creator of this particular NFT (obviously :D ) and in this scenario if someone just bought an NFT asset which then can be easily edited and changed to represent something totally different by the creator then it can lead us to creators removing or completely changing the content of a token and therefore impacting its value. I imagine that as a user if I buy 20 min video called: "I love cats" with a cute cat on thumbnail - I want it to remain what I bought and any changes made after my purchase would be unwanted.

>Reservation price and starting price, i.e. the minimum valid price of a bid, is really the same thing, is it not? our system only has the latter.

Reserve price would be a price which is a minimum bid that get accepted eg. I sell my nft for 2 JOY on an auction and reserve price is 10JOY - someone could bid 8 JOY and if the auction ends at that point and noone bids over 10 JOY (or equal) then the auction ends without winner. So its a really different thing than starting price which in this example is 2 JOY. It's a pattern that we can meet on some of traditional marketplaces like ebay etc.

>Keep in mind that issuing an NFT is not the same as picking whether what kind of auction there should be. An NFT can be issued in an idle state, where there is no scheduled auction or anythign else, and the NFT is owned by the channel owner. There are also other states you can pick, like offer to send to sell to some specific other person at a given price and a instant buy now mode. This will become more clear when I have the docs ready. It also means that if we are going to do the designs in a roughly forward compatibel way, we need more than a single dimmed out COMING SOON button.

Sure I will study the NFT docs that you provided and come up here with a different solution to that. So user will be able to issue an NFT without putting it on market or issue and then transfer. Noted!

>Issuing experience:
I think this experience really would benefit from being a full screen emersive experience, possibly broken up in multiple steps. Right now, the small scrollable space where things will cahgne substantailly based on what you select as the type is a bit rough. In general I feel that unless one is dealing with dynamic user provided content of unpredictable size, avoiding scrolling as pattern is highly desirable in almost all cases.
Recall from above, issuing an NFT does not require starting an auction, per say.
The top section showing the information about the video appears to me to not really do anything useful for the publisher in this context, and its taking the most valuable space. If we actually had distinct NFT metadata which gave a different presentation format for the NFT, then that could make more sense, but when its just presenting the same data the puplisher has already. As I mentioned, all of the video metadat is still mutable even after the NFT is issued, but even if it was not, I would have elected to show the final preview on the last screen during a confirmation step, rather than up front when the user is trying to make a bunch of key decisions.
By virtue of the above, removing he warning should be fine.

Yes Im leaning towards changing to full screen mode in "video workspace" alike container to present this experience better. I'm still not sure if video should be mutable by creator after making it as an NFT but yes I agree it could be presented as a last step in the flow!

> NFT metadata: I was expecting you guys to perhaps suggest some interesting ideas here that would be making NFTs in our specific context more useful. For example, if you recall when you did the first few concept designs a few months back, the owner could specify a message associated with the NFT, and this could be displayed in the video experience. To me, that seems potentially interesting and easy enough that it would be wortht trying. Recall that many NFTs have these sorts of features extending well beyond the bare bones image NFTs that have become very well known. The most prominent example is probably the original Cryptokitties NFTs which allowed for breeding. But even beyond this, there could be room for more mundane metadata that would be helpful for allowing the NFT to be shared and consumed. So for example, having the option of a sort of preview or trailer video for the full video could be very useful as the primary artefact that is shared outside of the platform, as sharing the full video which could be quite long, and so there would be no succinct way to get an impression about what it was about. For image NFTs this problem does not exist, but for videos it might. The trailer could also be just be the creator talking about the primary video and epxlaining how, why, when it was made, etc. Anyway, these are just ideas. Wanted to draw your attention to this sort opportunitiy as well. Of course we could sidestep all of this for a later design sprint also, but want to hear your thoughts.

Oh I'm all in! I would love to create those little bits that would make NFTs in our specific context more "sexy" :) Just currently I'm trying to catch the bare MVP for this feature and I thought about tackling those additional features in post MVP sprint. Please let me know what you think :) 

>Could it make sense to have a standalone sort of public page for each NFT, as distinct from the consumption experience? Remember that the video page has lots of things on it, in particular in the future, including suggestions for other videos, comment fields, social token stuff, etc. So could it be advisable to have a dedicated NFT page for each video which is solely dedicated to giving a public page where you can see everything about the NFT, including hte history, bids, auction status, etc. This sort of page could also allow us to avoid cluttering the player page too badly, and instead only show some key points about the NFT on the video page.

Yes I agree that this concept would be worth exploring as we risk overloading the player page with NFT features - maybe we could show only some features at video page and then offer a more expanded view for those who want to dive deeper into particular NFT. We didn't explore this approach yet but I will surely put it on my list :) 

>I think it would be useful to see, on the My Videos page, what videos have or have not issued NFTs, even without hovering. For example if you uploaded a bunch of videos without NFTs over time, and then you are trying to recall which ones those are, then it would be useful to not have to go and hover over all of the videos one by one to see the state of the secondary action button.

Great catch! Nina is currently working on indicators for video tiles to solve this problem :)

**Comment by KubaMikolajczyk** [comment]
> Follow up question: _should_ video metadata, including the primary video asset and cover photo, be mutable if there is a live NFT on the video? currently it is, butperhaps it should not? we can change this!

As I responded above - I believe that video should become immutable after its issued as an NFT, because otherwise we risk putting collectors in many uncomfortable scenarios when data is changed after the purchase. Wdyt?

**Comment by toiletgranny** [comment]
@bedeho:
> Follow up question: should video metadata, including the primary video asset and cover photo, be mutable if there is a live NFT on the video? currently it is, butperhaps it should not? we can change this!

@KubaMikolajczyk asked us to weigh in on this, so here's my take. While I strongly believe that the video asset itself should be locked once the video is published (regardless of whether there's an NFT on it or not), I can see both the risks and benefits of having all other data about the video remaining editable.

From https://github.com/Joystream/atlas/issues/1329, @bedeho:
> Critically, owning a video, in the sense described herein, is not a claim on the intellectual property, revenue or any other rivalrous property of using the actual content itself.

With my understanding of the above, the content creator, remaining an owner of the intellectual property, might come to expect to be able to change the video's title or its thumbnail. This could be critical eg. in the context of monetization (of course, if it's ever possible), as content creators on YouTube nowadays tend to experiment with different videos' titles and thumbnails to see what's performing better (this is explained better [in this video](https://www.youtube.com/watch?v=S2xHZPH5Sng)).

On the other spectrum, as far as I know, currently, there's no concept of editing NFT's details on — at least — the most popular marketplaces. As a collector, I might be surprised to see a thumbnail or a title change in a video I _own_. I might consider the change having a negative impact on the perceived value of a good. This would inevitably lead to conflicts.

So perhaps a hybrid model is worth considering? At least at the beginning? Some rough ideas, thought-starters, sorted from the most absurd to the least terrible:
- We could try having changes to the video's details (excluding the video file) requiring explicit consent from an NFT owner. 
- We could try giving NFT creators an option to reserve a right to edit the video's details at any point in time, with this reservation being later prominently displayed on the NFT page.
- Or maybe we should just draw a line between the video's metadata and the NFT's metadata, and treat those separately? The first could remain under an exclusive video's creator control, as this focuses on how the asset is displayed as a video, on a video-sharing platform. The latter, being about the NFT for a video, can only be set up once and shall remain intact.

**Comment by kdembler** [comment]
> On the other spectrum, as far as I know, currently, there's no concept of editing NFT's details on — at least — the most popular marketplaces

If you do a deeper dive on ERC721, Ethereum's NFT standard, most NFTs actually are mutable - the NFT itself declares an URL under which you can fetch metadata for it - title, description, image, anything else. You can design some solutions that make this locked, for example using IPFS, but _a lot_ of projects just use a regular backend service hosted by the NFT issuer and gives them (issuer) ability to completely change details of owned NFTs. This design is certainly non-ideal.

To answer the general question, I'd vote for making the video immutable after the NFT has been issued. I agree with what you described @toiletgranny, regarding experiments that content creators will try with the title+thumbnail (I knew that the link was pointing to that Veritasium video before clicking :D), but those can be run before issuing the NFT, right? So content creator can do all sorts of changes but once they issue an NFT it's set in stone. What you buy is what you get, you're not at creator's mercy to not change the video thumbnail to dickbutt.

> We could try having changes to the video's details (excluding the video file) requiring explicit consent from an NFT owner

This sounds like an interesting option longer term although I think it could introduce too many complexities at this point, like  how exactly this approval works, how it's coordinated etc.

**Comment by bedeho** [comment]
Phenomenal points @toiletgranny @kdembler I think the simplest thing is best here actually, both for product and core tech: if an NFT exist for a video, no part of the video can be altered. Added this issue for it to be fixed in the blockchain

https://github.com/Joystream/joystream/issues/2786

**Comment by bedeho** [comment]
> Alright! Should this whitelisting be done by entering the wallet addresses of those people who are allowed to buy? Or do you have in mind another value that we can use to whitelist them? (email? member name?)

Whitelisting is of members, so allowing the user to specify the member by handle is probably the most convenient during the issuing flow.

> Shouldn't it be optional?

It can be optional for the user to provide, but the underlying blockchain requires some specific value which Atlas has to provide, so one approach would be to just send %5 of the price under the hood.

> Should the user be able to choose the percent incrementation / fixed incrementation (eg. each bid step must be 2 JOY larger than the one before)

The bid step is a fixed number of JOY, it cannot be a percentage of the last bid, so this is not possible.

> Or maybe we should use only incrementation by a fixed amount instead of using percentages?

I am not 100% I understand what you mean, but this sounds like what I am suggesting. So suppose the user sets price to 100 JOY, then the increment would automatically be set to 5 JOY, perhaps even hidden from the user.

There is one problem here though, and this is that the user is not required to set a price, the reservation - or starting price, could be 0, in which case the bid step would be 0 JOY, which would mean it basically does not work. So we may need to set some minimal magic number if the user has no reservation price.

> So the way you see it would be handling this like on more traditional marketplace like Ebay
Link to Ebay screenshot in Figma So we would not have two separate modes one for auction and one for selling for fixed price but rather connect them both and allow user to choose which one to enable - only auction , auction + buy now , or only buy now.

I am afraid I did not understand this question.

> I'm rising this topic as this can get really dangerous - NFT as a non-fungible tokens can be owned by someone else than the creator of this particular NFT 

NFT metadata, which we currently do not have, does not _have to be_ mutable after issuance. We can allow the creator to set it once, and that could be the end of the story. There could still be a case for having such metadata, but that has to be evaluated directly on its own merits.

> Reserve price would be a price which is a minimum bid that get accepted eg. I sell my nft for 2 JOY on an auction and reserve price is 10JOY - someone could bid 8 JOY and if the auction ends at that point and noone bids over 10 JOY (or equal) then the auction ends without winner. So its a really different thing than starting price which in this example is 2 JOY. 

I am afraid I did not understand this point.

**Comment by bedeho** [comment]
# Note

This is feedback for this design iteration

https://github.com/Joystream/atlas/issues/1495#issuecomment-954877797

- Loved the intro, with the teaser and then the personal part <3.
- I think it would be good if the design issue and the feedback issue could be one issue, like we are doing for the member account work here: https://github.com/Joystream/atlas/issues/1496#issuecomment-953756970. Right now things are getting split across this thread and the standalone design thread above, which is much harder to then follow along with later.

# Feedback

## Missing `offer`

 You are missing "offer": which is an offer for a specific other member to receive, possibly for payment, this NFT, described here https://joystream.gitbook.io/joystream-handbook/subsystems/video-nfts#offer-nft. If this is out of scope currently, then perhaps we should do the "COMING SOON" disabled state thing you did in a prior iteration for the other ways of putting an NFT on the market?

## Does an open auction have a duration? if not, should it?:

It does not, and I don't think it should. Open auctions exists precisely for those situations where the owner is interested in selling the asset, but they do not have sufficient information about how much interest there is at different prices, so it is in effect a learning process of public price discovery. It is very hard to know up front for how long you want to learn. In some cases perhaps you know that you def. would not want to learn for more than a given period of time, but the benefit of ruling this out is very limited, and the added complexity is therefore not worth it.

## Starting price

I think we can just call this the reservation price, as that is a bit more accurate.

## Missing Tooltip

The starting price does not have a tooltip.

## Preview

The Large image preview on the left hand side takes about 50% of the total visual space, but it really does not add any value to the user. They have already seen a preview of the image for thumbnail purposes, so there is no need to display it for that reason at least. This scene is already quite overloaded, as I mention in _Alternative Approach_ below,.

## Whitelist Interaction

I do not think whitelist interaction really works: It does not in any way actually confirm to the user that valid members have been specified, and even if some members have been specified, the absence of any sort of dual confirmation - perhaps by showing avatar and raw member id, makes it susceptible to mistakes/typos. A more explicit type picker, the kind you discarded, would be more useful. Keep in mind, whitelists are unlikely to be _huge_, both for technical reasons, and because they are precisely meant for exclusive scenarios.

## Immutability Warning

The huge warning about immutability is too invasive and will make an already nervous user uncomfortable. For most people, they will figure this out at some later point, without much harm. Also check my alternative approach section below, as it may allow other more graceful ways of communicating, since there will be more space to work with.

## Progress Indicator

- The drawer based progress indicator, which you showed as an alternative, both overloads this visual form for two very distinct forms of interaction and information, so I don't think we should go for it.
- I am not sure if its really worth having a progress indicator with only two steps, also, having it at the bottom as these thin low contrast bars seems like it will not get much attention anyway.

## Alternative approach

I think the version we have now is fine, but I see some problems that I want to highlight, and suggest an approach which may be better.

Our flow for uploading a video is already quite dense, in the sense that we are requiring a user to make a decision about a substantial number of parameters in a single scene in one go. I think we get away with it because the concept of publishing to a video platform is already quite familiar to people, hence they don't need to learn hardly any new concepts. I think when it comes to issuing an NFT, that no longer really applies. This is a totally new behaviour where there is more at stake - literally financially, and there are lots of different - but similar, concepts (open auction, english, buy now, fixed price, royalties ...) people have to understand to make a decision. Going for this same approach of requiring the user to make many related and unfamiliar decisions in a single step seems too optimistic to me. We are having to rely on

- lots of very small text explainer tooltips explaining very complex and nuanced concepts
- the user making a decision about what to make a decision about (see more): it's quite arbitrary to say that the user has to choose to learn about royalties, but be presented with the concept of a starting price.
- the user having to scroll to see all options in a very small space

if we were to choose to make things more involved, for example allowing the issuer to set user defined metadata, or other more complex rights for the future owner, or show fiat equivalent prices, this would only be compounded and crowded.

So I think there is a tradeoff here. You can go for this approach, which perhaps allows less interactions fro a user who already knows everything. Alternatively you could go for a more unpacked step-by-step approach, focusing on exposing one major economic decision at a time, which would be better for a first time or new user. See below for an example of how the flows could work in this approach.

In the end, I am not actually sure what we should do, not only is there a user focused tradeoff, but there is also an execution tradeoff on our end. Doing further iterations take our time, and I can't tell for sure how significant the difference is in the end for users. I would like to get your input on whether you think this alternative has any merit, and whether it's worth spending more time on now.

![nft_issuance_flows](https://user-images.githubusercontent.com/437292/139701990-1571ce7a-bfa9-4b33-94fb-b0a3a7849996.png)

**Comment by KubaMikolajczyk** [comment]
# Note response

Thank you for your feedback!
I'm glad you liked the intro! 
I renamed this issue to Tracking Issue: Issuing NFT so we can treat it as a container for our feedback loop related to this topic - I thought we were supposed to move our conversation to newly created design issues and have both design and feedback there as it is in case of the issue you mentioned: https://github.com/Joystream/atlas/issues/1496#issuecomment-953756970

# Feedback response

> Making an offer: You are missing "offer": which is an offer for a specific other member to receive, possibly for payment, this NFT, described here https://joystream.gitbook.io/joystream-handbook/subsystems/video-nfts#offer-nft. If this is out of scope currently, then perhaps we should do the "COMING SOON" disabled state thing you did in a prior iteration for the other ways of putting an NFT on the market?

I actually left the offer out of this experience on purpose as this feature didn't seem like a part of the listing experience - but rather an action taken on already existing NFT - but after your feedback I see now how this should be included here as well

> Does an open auction have a duration? if not, should it?: It does not, and I don't think it should. Open auctions exists precisely for those situations where the owner is interested in selling the asset, but they do not have sufficient information about how much interest there is at different prices, so it is in effect a learning process of public price discovery. It is very hard to know up front for how long you want to learn. In some cases perhaps you know that you def. would not want to learn for more than a given period of time, but the benefit of ruling this out is very limited, and the added complexity is therefore not worth it.

Alright, I will remove time duration from an open auction - one question though - in case of fixed price - do you think this should be treated similar to an open auction with no time duration? 

> Starting price: I think we can just call this the reservation price, as that is a bit more accurate.

I'm worried that this can create confusion for users already familiar with patterns on platforms like opensea where starting price and reserve price are two separate concepts - take a look at image below
![image](https://user-images.githubusercontent.com/31144205/139844930-7fca4549-5a6b-4973-b952-c2e46b28126f.png)
On rarible for instance starting price is called minimum bid
![image](https://user-images.githubusercontent.com/31144205/139845080-4858ef77-442f-47f2-bfd7-31415ca72554.png)
Wdyt? Maybe minimum bid approach would suit us better?

> The starting price does not have a tooltip.

Yes - and it can be worth adding it there!

>Whitelist Interaction : I do not think whitelist interaction really works: It does not in any way actually confirm to the user that valid members have been specified, and even if some members have been specified, the absence of any sort of dual confirmation - perhaps by showing avatar and raw member id, makes it susceptible to mistakes/typos. A more explicit type picker, the kind you discarded, would be more useful. Keep in mind, whitelists are unlikely to be huge, both for technical reasons, and because they are precisely meant for exclusive scenarios.

I hear you - I will reiterate this with your feedback in mind!

> Preview / Immutability warning / Alternative approach 

Thank you for those ideas! I can clearly see that UX wise we have a field to improve this experience and maybe this unpacked step-by-step approach would fit better in our scenario and it definitely deserves to be explored further. I like the idea of using part of the screen for explaining those complicated concepts - we have to keep in mind though that this will have a trade-off as more experienced users might find this concept annoying after going through step experience for the 100th time. I will come up though with a possible solution for that and try to marry those 2 concepts into one.

**Comment by bedeho** [comment]
> I actually left the offer out of this experience on purpose as this feature didn't seem like a part of the listing experience - but rather an action taken on already existing NFT - but after your feedback I see now how this should be included here as well

It does not have to be, but it can! It means in some cases people would have to do two separate steps, but I also think this particular flow is by far the least relevant one, so you would remove some clutter in many other cases. Its up to us to decide what is best for the product now.

> do you think this should be treated similar to an open auction with no time duration?

It is, in the blockchain, treated the same way.

> I'm worried that this can create confusion for users already familiar with patterns on platforms like opensea where starting price and reserve price are two separate concepts - take a look at image below

So what is actually the difference then? What is starting price in the first picture?

**Comment by KubaMikolajczyk** [comment]
New update with alt approach:
https://www.loom.com/share/063bbec065fe4da0a30e867e8d51e8f1

Also if anyone want to scout figma: https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=781:45041

And walk through prototype from video with me:
https://www.figma.com/proto/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?page-id=796:46662&node-id=796:46745&viewport=396,48,0.18&scaling=min-zoom&starting-point-node-id=796:46745&show-proto-sidebar=1

**Comment by bedeho** [comment]
# Feedback

- This amazing work, I literally was laughing at how sweet the experience felt, but then in the end I had to shed a tear that you did not recommend it 😢 . I literally could not think of anything that could be better in the not-recommended approach, so I really think both approaches are as strong as they can be as is.
- I am not sure what the user testing will entail, but it would seem that almost by assumption, it will be very biased towards the non-recommended approach, as everyone will be a new user in that test. Not clear how you would solve that.
- Do you have any idea how products generally approach this question of designing for new vs. power users? This must be a common topic in product design.

**Comment by KubaMikolajczyk** [comment]
Hi Bedeho thank you for you feedback and I'm sorry for such late response to this msg.

I'm really glad that you like the "wizard" approach. I already had a meeting with a UX expert from Netguru and I have a pretty strong understanding of how we can test those two different approaches. We will have to first define what differentiates those two types of users in our specific case: power user vs newbie (and I'm going to do that with the team on Monday), then I will prepare a survey that all user testing applicants will fill and then we will perform quality tests with (i hope) 20 users recruited on discord. After that, I hope we will have a better understanding of what works and what doesn't, but I will share a more detailed plan with you next week.
