### ISSUE TITLE
Feature request: Playlists perhaps needed sooner

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1500]
People have started working around the absence of playlists for original Joystream specific content, so perhaps we should execute on this sooner. Just a product management note for the future.

https://play.joystream.org/video/6935

![Screenshot 2021-10-18 at 10 54 44](https://user-images.githubusercontent.com/437292/137700024-da826cca-2b54-4d58-a1b3-afe5ce235bf4.png)

**Comment by dmtrjsg** [comment]
#1648  < Epic raised
