### ISSUE TITLE
Playback speed

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1503]
### Context
I often want to do this, in particular to see reviews, e.g. of know-your-council. Not urgent, just giving my feedback.

### Scope
* [ ] Control playback speed 
* [ ] Speed setting stored in local storage and applies to next video in playback [applies to all settings]

### Designs
* Link to[ Figma user story](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2127%3A135540)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202474130431850) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@dmtrjsg Does it make sense to have this issue moved under the "Subtitles" epic, since we agreed to include it in the scope, on the "since-we-are-here-kind-of-basis"?

**Comment by toiletgranny** [comment]
@dmtrjsg Designs for the playback speed controls have been transferred over to the Video page Figma file by @TCzechowski when working on #1503. 

The flow for changing playback speed [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2127%3A135540).
