### ISSUE TITLE
NFT purchase view Design

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#1506]
### Info
"Transaction view" is a part of the NFT experience MVP scope.
This particular issue is a communication container for the whole "Transaction view" experience.

**Comment by TCzechowski** [comment]
Update:
https://www.loom.com/share/fc821090c9c64463b97cd8ec9d53d037

Figma File:
https://www.figma.com/file/yVS7nkKjUtCeBcjUDqBbCF/Transaction?node-id=415%3A22858

**Comment by bedeho** [comment]
# Feedback

Thank you for the video, it was great, short and sweet! The abstraction you picked to hide the context for launching the flow was very helpful ;)

- Placing a bid here only pertains to an auction, either English or Open, not Fixed price (buy now) ? this is not totally clear to me. But even if its just for an auction, you need to distinguish these cases quite clearly, as bidding in an Open auction involves your bid being locked in for up to a given amount of blocks, even if the owner does not accept it, before you can withdraw the bid. In an English auction, you cannot withdraw at all, and the whole auction will end at some point in time. Lastly, if there is a buy now condition associated, this should really be a single action button to possibly fulfill, and the user should be discouraged from entering an amount that exceeds the buy now if it is defined. So all in all, the UX needs to be quite a bit more tuned to the details of what kind of context in which the bidding is taking place.
- I am curious, you are going for a large view, but not 100% full screen, what was this? Do we think any user will for example want to go back to `New` or `Start publishing` from this screen? That does not seem likely to me, in which case simply going full size of browser viewport seems even cleaner.
- Keep in mind that video NFTs are all 1-of-1, so there is no notion of more than one other person collecting a given NFT, like you have shown for `Collectors`. This is a key design decision made at the core layer of the system, and changing it will require substantial effort, so we cannot accommodate any change on this at this point in this design sprint. I asked for input from designers if they thought this was a show stopper, but noone said anything so far.
- It would be great to see the identity of who has made the currently active bid, not only to make you aware that you may be outbidding yourself, but also to entice competitive bidding where people are wanting to out-compete someone else they may recognize from the same community or subculture. This is all good as it supports the creator in the end!
- What do you show if there is no current bid? or what do you show if the auction does not have an end date? this sort of connects with my point about bidding UX needed to be different for different kinds of auctions.
- The `service fee` should really just be `transaction fee`, as there is no additional cost to bidding except paying for your transaction.
- Part of the motivation for buying an NFT could be that you are supporting a creator, which would happen explicitly if there is a royalty associated. So it would be great to show the royalty which would occur, if any, and also clarify how much would go to each party in the event your bid wins
  - platform (burned)
  - creator royalty
  - owner
- Love the holograhic effect! how did you do that?

**Comment by TCzechowski** [comment]
Thanks for the feedback Bedeho!

**There's the link to new update:**
https://www.loom.com/share/f0ccfae87467418cacc36c3fb9846fb7

**Figma link:**
https://www.figma.com/file/yVS7nkKjUtCeBcjUDqBbCF/Transaction?node-id=638%3A33011

### Feedback response

> Placing a bid here only pertains to an auction, either English or Open, not Fixed price (buy now) ? this is not totally clear to me. But even if its just for an auction, you need to distinguish these cases quite clearly, as bidding in an Open auction involves your bid being locked in for up to a given amount of blocks, even if the owner does not accept it, before you can withdraw the bid. In an English auction, you cannot withdraw at all, and the whole auction will end at some point in time. Lastly, if there is a buy now condition associated, this should really be a single action button to possibly fulfill, and the user should be discouraged from entering an amount that exceeds the buy now if it is defined. So all in all, the UX needs to be quite a bit more tuned to the details of what kind of context in which the bidding is taking place.

Yes, you are right. My thought here was to discuss the initial idea / layout structure etc. and prepare the rest of auction types after that, but now that I think of it, it wasn't a good approach. Fixed that in the new video and prepared versions for all auction types :)

> I am curious, you are going for a large view, but not 100% full screen, what was this? Do we think any user will for example want to go back to New or Start publishing from this screen? That does not seem likely to me, in which case simply going full size of browser viewport seems even cleaner.

Good point, fixed in the new version.

> Keep in mind that video NFTs are all 1-of-1, so there is no notion of more than one other person collecting a given NFT, like you have shown for Collectors. This is a key design decision made at the core layer of the system, and changing it will require substantial effort, so we cannot accommodate any change on this at this point in this design sprint. I asked for input from designers if they thought this was a show stopper, but noone said anything so far.

Thank you for that insight! The whole NFT concept wasn't that clear for me yet at that time. We still want to maintain that feeling of "joining the community" though, so we've changed the "Collectors" label to "Community", which won't display collectors of that particular NFT anymore but will display creator's followers.

> It would be great to see the identity of who has made the currently active bid, not only to make you aware that you may be outbidding yourself, but also to entice competitive bidding where people are wanting to out-compete someone else they may recognize from the same community or subculture. This is all good as it supports the creator in the end!

Great idea, implemented in the current iteration!

> What do you show if there is no current bid? or what do you show if the auction does not have an end date? this sort of connects with my point about bidding UX needed to be different for different kinds of auctions.

New iteration has it covered. You can check it out in the video / Figma :)

> The service fee should really just be transaction fee, as there is no additional cost to bidding except paying for your transaction.

Fixed

> Part of the motivation for buying an NFT could be that you are supporting a creator, which would happen explicitly if there is a royalty associated. So it would be great to show the royalty which would occur, if any, and also clarify how much would go to each party in the event your bid wins
platform (burned)
creator royalty
owner

Done in the current iteration :)

> Love the holograhic effect! how did you do that?

You just simply message animation wizard called Adam, and he'll do his magic! :) Glad you liked it!

**Comment by kdembler** [comment]
Bringing here a point I've brought up in the Rocketchat:

I think showing the topbar at all times is useful to the user - we keep Joystream branding visible at all times and also give the user quick glance at their currently logged in membership, I guess sidenav is indeed not that useful (possibly we should also hide for the video workspace?)

**Comment by bedeho** [comment]
> I think showing the topbar at all times is useful to the user - we keep Joystream branding visible at all times and also give the user quick glance at their currently logged in membership, I guess sidenav is indeed not that useful (possibly we should also hide for the video workspace?)

I agree that the top bar is more useful than the sidebar, but I am not sure its really useful to have the top bar, including search, publishing visible, I would guess the conversion into those would be near 0, as it's just not very natural. I see a case for the branding being kept, but I think even that has limited significance. The singular focus of the experience shown here is quite compelling to me, with or without the brand. Arguably, this logic could probably then apply to other parts of the product where we have not been careful about this, but the principle still stands I think.

If you have high conviction on this, what is a good way to resolve?

**Comment by TCzechowski** [comment]
> I think showing the topbar at all times is useful to the user - we keep Joystream branding visible at all times and also give the user quick glance at their currently logged in membership, I guess sidenav is indeed not that useful (possibly we should also hide for the video workspace?)

I understand your point, and I would agree with that if it was a screen where the user spends a lot of time. Taking into account that it's a quick "one step" kind of process, I don't think that the user will spend much time there, and I personally think introducing extra noise on the screen just for this use case is not worth it.

I will bounce that idea off other designers tomorrow, though, and I'll let you know what they think :)

**Comment by bedeho** [comment]
# Feedback

- Love the transitions, really makes it easy to understand and follow the changes.
- **Variations:** All the different variations look great and work consistently and efficiently, and it seems you have covered everything.
- **Collectors:** First, I think this will actually be quite confusing, as it's not clear what this means in the experience. Second, we cannot actually execute on this, as the information about who follows whom is not stored in one central place right now, its all client side, where each person knows who they follow. Third, even if it was centralised into some place, it's not at all clear it should be _public_, so that anyone can know who everyone follows. This has serious privacy implications which can be quite serious, for example imagine someone follow lots of creators that our of step with the majority social sentiment in their society, e.g. someone follows lots of christian religious content who lives in North Korea, or someone who follows lots of non-hetrosexually themed content while living in Iran. This could have quite serious implications, so I doubt this can ever be public.
- **Missing Buy Now in Bidding:** I understand the idea here, but I think we have to help the user make good financial decisions by preventing them from inserting a bid which is above a possibly set buy now price. This would be a user error, as you say they get to make the choice up front before this flow begins, however, we should still prevent it. Could one solution be to just prevent the user from providing input values for the value that exceed the buy now value?
- **X hours:** X comes from the chain, like all other values, and it's different for each auction.
- **Royalties:** This was a super nice presentation, but _royalites_ is actually the name reserved only for what the creator possibly may get, so kind we find some other universal name across the three, e.g. **Value Split**.
- **Ends in:** Just curious, but could it be useful to display some sort of progress bar or something that indicates how much of the total initial time is left, so as to indicate to the user how long this opportunity has been available? Just a thought, may not be important at all.
- **Preview images:** Great if we could have more realistic and diverse preview images in the Figma, as I find it's a more realistic context in which to judge the solution. Some times it can become more clear that a particular design has an visual hierarchy which either is too strong or to weak compared to realistic images places near by,

**Comment by kdembler** [comment]
Keeping topbar in the view isn't introducing additional noise, it's just keeping the one we already have :P We could introduce some backdrop that would "gray out" the content of the topbar so it wouldn't be in users focus. However, my feeling on this isn't that strong, so if you agree we should hide it, then let's do that

**Comment by TCzechowski** [comment]
> Collectors: First, I think this will actually be quite confusing, as it's not clear what this means in the experience. Second, we cannot actually execute on this, as the information about who follows whom is not stored in one central place right now, its all client side, where each person knows who they follow. Third, even if it was centralised into some place, it's not at all clear it should be public, so that anyone can know who everyone follows. This has serious privacy implications which can be quite serious, for example imagine someone follow lots of creators that our of step with the majority social sentiment in their society, e.g. someone follows lots of christian religious content who lives in North Korea, or someone who follows lots of non-hetrosexually themed content while living in Iran. This could have quite serious implications, so I doubt this can ever be public.

@bedeho I might have explained it wrong. Apologies. We didn’t actually want to display creators FOLLOWERS, but “Supporters” that have bought NFT from the Creator. If they buy the NFT, then it would be displayed on their profile so that information would be pretty much public anyway, right? Maybe we should switch the label to “Supporters” instead of “Community”? What do you think?

> Missing Buy Now in Bidding: I understand the idea here, but I think we have to help the user make good financial decisions by preventing them from inserting a bid which is above a possibly set buy now price. This would be a user error, as you say they get to make the choice up front before this flow begins, however, we should still prevent it. Could one solution be to just prevent the user from providing input values for the value that exceed the buy now value?

So maybe we can include a subtle text displaying the Buy Now price, and when the user tries to place a bid higher than the Buy Now option then we could display an alert and ask the user if they want to switch to Buy Now mode? Like on the screenshot below? 

**Default:**

![image](https://user-images.githubusercontent.com/22870059/142259516-69bfcf5d-d7e6-4177-a2d7-cbf51dcdf544.png)

**After setting the amount that is higher than the Buy now option:**

![image](https://user-images.githubusercontent.com/22870059/142259713-afe948bd-4a50-4022-a821-ea806de75471.png)

**Comment by bedeho** [comment]
> @bedeho I might have explained it wrong. Apologies. We didn’t actually want to display creators FOLLOWERS, but “Supporters” that have bought NFT from the Creator. If they buy the NFT, then it would be displayed on their profile so that information would be pretty much public anyway, right? Maybe we should switch the label to “Supporters” instead of “Community”? What do you think?

Ah ok, got it, still think it will need some minimal explanation, perhaps a tooltip?

> So maybe we can include a subtle text displaying the Buy Now price, and when the user tries to place a bid higher than the Buy Now option then we could display an alert and ask the user if they want to switch to Buy Now mode? Like on the screenshot below?

I think this is better yes. Could we do even better by avoiding requiring the user to read all the details and then chose an action, perhaps just automatically setting the value to the buy now, if it is ever exceeded, and then just display a shorter message, without a switch action, which just says "Bids cannot exceed buy now price". This also would not need to be in red, as a scary error, more like a point of information?

**Comment by TCzechowski** [comment]
> if it is ever exceeded, and then just display a shorter message, without a switch action, which just says "Bids cannot exceed buy now price". This also would not need to be in red, as a scary error, more like a point of information?

Is there any specific reason why it cannot exceed the buy now price? I know it sounds kinda counter-intuitive, but maybe there are going to be scenarios where a huge fan and wants to support the creator and thinks "The buy now price is too low, they deserve more!" and bids higher. It probably wouldn't happen often, but I wanted to put that out there. What do you think? 

Also, I must have missed this part in my previous reply:
> Preview images: Great if we could have more realistic and diverse preview images in the Figma, as I find it's a more realistic context in which to judge the solution. Some times it can become more clear that a particular design has an visual hierarchy which either is too strong or to weak compared to realistic images places near by,

I am not sure that I understand what we are talking about here. What do you mean by **Preview Images**?

**Comment by bedeho** [comment]
> Is there any specific reason why it cannot exceed the buy now price? I know it sounds kinda counter-intuitive, but maybe there are going to be scenarios where a huge fan and wants to support the creator and thinks "The buy now price is too low, they deserve more!" and bids higher. It probably wouldn't happen often, but I wanted to put that out there. What do you think?

I never thought of that, but the blockchain itself actually prevents it, so you cannot even overpay if you wanted to, so what I am talking about is here to make sure the user has an accurate understanding of what they can do, so they are not surprised by the amounts they end up seeing when all things are said and done.

> I am not sure that I understand what we are talking about here. What do you mean by Preview Images?

I literally just mean the images you use as standins on Figma for whatever actual images users would use. Using diverse and more realistic photos, perhaps @Lenorette can show you what she does already.

**Comment by TCzechowski** [comment]
> I never thought of that, but the blockchain itself actually prevents it, so you cannot even overpay if you wanted to, so what I am talking about is here to make sure the user has an accurate understanding of what they can do, so they are not surprised by the amounts they end up seeing when all things are said and done.

And what exactly should happen when someone bids for the same amount as Buy Now price? or 1 tJOY less? Should the auction become frozen and wait until the end?

**Comment by bedeho** [comment]
> And what exactly should happen when someone bids for the same amount as Buy Now price? or 1 tJOY less? Should the auction become frozen and wait until the end?

If they bid one less, then that would be the new highest bid, if they bid exacty But Now price, or more, they will be charged Buy Now price, regardless, and become owner.

**Comment by TCzechowski** [comment]
> If they bid one less, then that would be the new highest bid, if they bid exacty But Now price, or more, they will be charged Buy Now price, regardless, and become owner.

Got it, we've also changed some things:
- Switched from writing "tJOY" everywhere to using tJOY icons.
- Moved the tJOY indicator inside amount input to the left side (as an icon) and moved the dollar converter from below the input to inside the input, as it caused some usability issues explained in the video.

I think we are pretty much done here, please check it out and let me know if can mark it as done :)

Figma link:
https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=985%3A96675

Loom:
https://www.loom.com/share/cf019a4f240c420bae41fa769390b91a

**Comment by bedeho** [comment]
**Perfect**
