### ISSUE TITLE
Mobile version: "Dots button" not visible till hover

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1521]
**Issue:**
On mobile devices there is no mouse hover effect, as result we can see three dots for each video only when touch on scroll: [http://joxi.ru/RmzGZ7ZUjaJ1K2](http://joxi.ru/RmzGZ7ZUjaJ1K2)

**Browser:**
All mobile browsers. 
Tested on iPhone 11 Pro, iOS 15.0.2, Safari browser.

**Suggestion:**
Always show this button for mobile version

**Comment by kdembler** [comment]
100% agree, should work this way from the beginning
