### ISSUE TITLE
Mobile version: Search button require second click to see keyboard

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1524]
When we click on "search button" on mobile, we should click on input one more time to start typing (to see keyboard): [https://play.joystream.org/video/7060 ](https://play.joystream.org/video/7060 )

**URL:**
[https://play.joystream.org/search](https://play.joystream.org/search)

**Brovser:**
All mobile browsers. 
For test I using iPhone 11 Pro, iOS 15.0.2, Safari browser.

**Suggestion:**
Automatically focus input field.

**Comment by kdembler** [comment]
Agreed, we're currently completely reworking the search experience and this will be tackled as part of this. (I actually made a comment regarding exactly this an hour ago :D https://github.com/Joystream/atlas/pull/1513#issuecomment-953674279). So given that new search experience will be released soon I'm gonna close this issue, but good catch :)
