### ISSUE TITLE
Mobile version: Fix search popup

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1525]
When I open search it is possible to scroll page in the bottom of popup: [https://play.joystream.org/video/7061](https://play.joystream.org/video/7061)

**Browser:**
All mobile browsers

**Suggestion:**
Add "overflow: hidden;" for body tag

**Comment by kdembler** [comment]
Like mentioned in #1524, this will also be tackled as part of the search improvements sprint, so closing here
