### ISSUE TITLE
Feature request: Automatically update search results on typing

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1526]
Automatically update search on typing (after 3 symbols) for desktop and mobile. 
For now user should click Enter to view search results.

**Comment by kdembler** [comment]
Like replied in last two issues (see #1524), this is being reworked. You can see current work in progress version here: https://search-flow--atlas-dev.netlify.app/ I welcome you to leave feedback for that :) For time being, closing this issue
