### ISSUE TITLE
Short Video in Atlas 10-30 sec

### ISSUE THREAD

**Issue by fomoiks** [Joystream/atlas#1528]
How do you like to make an idea in the Atlas for a section for short video 10-30 seconds like in YouTube and Instanrams? this can be done in a separate place like on YouTube. I think this will bring more people to the Atlas. this is also a popular format

**Comment by kdembler** [comment]
Hey, thanks for your suggestion. The idea is really interesting and I think this could very well be integrated into Atlas at some point, however it likely won't be a priority in the nearest future.

**Comment by bedeho** [comment]
> How do you like to make an idea in the Atlas for a section for short video 10-30 seconds like in YouTube and Instanrams? this can be done in a separate place like on YouTube. I think this will bring more people to the Atlas. this is also a popular format

If you mean something like YouTube Shorts, then I really think this only makes sense once you have a mature mobile product, which we do not, and we would have to make very substantial investments on the user editing side. So I think something like this actually would make most sense to have third party developers start building once we have pushed our basic infrastructure, tech and incentives further along.

If you mean something else, then please elaborate :)

**Comment by fomoiks** [comment]
> > How do you like to make an idea in the Atlas for a section for short video 10-30 seconds like in YouTube and Instanrams? this can be done in a separate place like on YouTube. I think this will bring more people to the Atlas. this is also a popular format
> 
> If you mean something like YouTube Shorts, then I really think this only makes sense once you have a mature mobile product, which we do not, and we would have to make very substantial investments on the user editing side. So I think something like this actually would make most sense to have third party developers start building once we have pushed our basic infrastructure, tech and incentives further along.
> 
> If you mean something else, then please elaborate :)

yes, i mean video like Youtube Shorts )

**Comment by bedeho** [comment]
Covered by https://github.com/Joystream/atlas/issues/5946.
