### ISSUE TITLE
Bad right-click interaction with video previews

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1529]
A very frequent interaction with video previews is to right-click in order to start playback in a new tab, unfortunately, our current hover effect disappears when initaiting this, which is very un-intuitive, as it feels as if you are disengaging with the content when right clicking. It also creates the akward effect that after you have clicked on the opening-in-a-new-tab menu option, then the hover effect reappears again.

It seems like simply keeping the hover effect on is more natural harmonic to the user.

**Comment by kdembler** [comment]
Firefox kinda breaking this here: (first I use Firefox, then switch to Chrome):

https://user-images.githubusercontent.com/12646744/139412602-0e41303a-c50f-45ac-a103-2bf3fb07f7bd.mov

**Comment by bedeho** [comment]
Ah I see, nice catch, there is no fix for Firefox here?

**Comment by kdembler** [comment]
I'm not saying that, we need to investigate, this was just a quick test

**Comment by toiletgranny** [comment]
While I haven't been working on this component yet, I assume that preserving the hover effect upon right-click indeed _was_ an initial intention of the designer behind this.

@kdembler let me know how I can help you with that. :)
