### ISSUE TITLE
Design & Tech Sync Weekly Meeting Log

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1539]
# 03.11.2021
Wednesday, November 3rd, 2021.

# Participants
- Klaudiusz,
- Kuba,
- Nina,
- Tomek,
- Adam

# Agenda:
1. Discuss Adam's proposal for [the new typography system](https://www.figma.com/proto/Of1sEePR7umP2KRX4VJb6P/Foundation-%26-Design-Tokens-Playground?page-id=338%3A125743&node-id=338%3A125798&viewport=338%2C48%2C0.03&scaling=min-zoom&starting-point-node-id=338%3A125798) in the Atlas Design System,
2. Discuss [unified component documentation ideas](https://www.figma.com/file/ItowByw08Sf0UPxQvIERxf/Design-System-Documentation?node-id=0%3A1),
3. Discuss adopting an analytics tool in Atlas,
4. Discuss Figma file structure.

# Todo
1. Adam is going to share the typography presentation with the design team and gather their feedback by Thursday at the latest.
2. Tomek is going to gather feedback regarding the current Figma file structure from the Atlas tech team, to get a better understanding of the exact pain points.
3. Klaudiusz is going to refresh his memory on where things are in terms of adopting an analytics tool, conclusions to be discussed next week.

**Comment by toiletgranny** [comment]
# 17.11.2021
Wednesday, November 17th, 2021.

# Participants
- @kdembler
- @KubaMikolajczyk
- @Lenorette
- @TCzechowski
- @toiletgranny
- @dmtrjsg 

# Agenda:
1. Review todo's from last week,
2. Discuss conditional large number formatting for NFT prices,
   - What about inputs?
   - https://www.statisticalconsultants.co.nz/blog/how-the-world-separates-its-digits.html
3. Check the status of the analytics tools implementation & available options research,
4. Check the status of design tokens implementation,
   - Check the status of the automated icons export,
5. What is the Time block?
6. **Discuss Figma structure (@TCzechowski)**

# Notes & Todo
1. **Review todo's from last week**
All done.
2. **Discuss conditional large number formatting for NFT prices**
   - Klaudiusz confirms that different formatting for large number separators based on the user's location _is possible_, thus this is the direction we'll take. For Figma designs, we'll use spaces. 🚨 Adam to make a note of that in the [Atlas Figma Guidelines for Designers document](https://github.com/Joystream/atlas/blob/master/docs/design/figma-guidelines-for-designers.md).
   - Not knowing precisely how large numbers we should account for, in terms of NFT prices, in designs, we decided to:
      -  Abbreviate large prices in all app views, except for transaction confirmation views (eg. placing a bid, making an offer, buying now, etc.) that @TCzechowski is currently working on.
      - Large prices should be abbreviated based on the following examples table:
         Value | Abbreviated value
          -- | --
          150 tJOY | 150 tJOY
          1500 tJOY | 1.5K tJOY
          1500000 tJOY | 1.5M tJOY
          1500000000 tJOY | 1.5B tJOY
          1500000000000 tJOY | 1.5T tJOY
          1500000000000000 tJOY | 1 500T tJOY
     - Whenever a price is abbreviated, hovering over it should trigger a tooltip showing the full price.
 3. **Check the status of the analytics tools implementation & available options research**
     - @dmtrjsg reviewed some of the available options and came up with a comparison table: https://miro.com/app/board/o9J_ljXQMLY=/
     - 🚨 @dmtrjsg to share a survey with the Atlas team to gather and analyze preferences around the "analytics" tools in general,
     - As of now, HotJar and LiveSession.io are being currently tested. 🚨 The design team to agree on whether we prefer having individual accounts on these platforms or a group one. Once the decision is made, @toiletgranny to share email addresses with @dmtrjsg.
4. **What is the Time block?**
   - 🚨 @KubaMikolajczyk & @TCzechowski to discuss this with @kdembler async, on RocketChat.
5. **Discuss Figma structure (@TCzechowski)**
   - Not discussed, 🚨 decided to move into another meeting.

**Comment by toiletgranny** [comment]
# 24.11.2021
Wednesday, November 24th, 2021.

# Participants
- @kdembler
- @KubaMikolajczyk
- @Lenorette
- @TCzechowski
- @toiletgranny
- @dmtrjsg

# Agenda:
1. Review todo's from last week,
2. **Discuss Figma structure (@TCzechowski)**,
3. Date & time formats — which should we be using in Atlas? Can this also be user-specific, depending on the locale?

# Notes & Todo
1. **Review todo's from last week**
      - For new tools & services used in Atlas, by default we'll go with a shared, group account approach. We'll be using individual accounts whenever there's no seat pricing, and when it's convenient/needed.
      - In terms of how and when plan on reviewing user session recordings, we'll discuss this next week on Wed.
      - **What is a "Time block"?**
           - After bringing everyone together in understanding how the "time block" term referred to blockchain blocks that are produced every 6 seconds (on average), we agreed that the whole concept (including how it's communicated to end-users through UI, eg. in timed auctions) needs to be discussed in a group, ideally with Bedeho. 🚨 Thus we'll circle back to it during Monday's weekly meeting.
2. **Discuss Figma structure (@TCzechowski)**
     - @TCzechowski presented his ideas for approaching Figma structure adjustments,
     - @dmtrjsg expressed the importance of having easily accessible user stories in Figma, connected to Epics, and documented for developers. He also suggested his ideas for a new Figma structure.
     - 🚨 Adam and Tomasz to sync and come up with a new proposition by Friday, backed up by visuals, based on ideas exchanged during the discussion. This is will be later discussed with @dmtrjsg.
3. **Date & time formats — which should we be using in Atlas? Can this also be user-specific, depending on the locale?**
   - Not discussed, 🚨 decided to move into another meeting.

**Comment by toiletgranny** [comment]
# 01.12.2021
Wednesday, December 1st, 2021.

# Participants
- @kdembler
- @KubaMikolajczyk
- @Lenorette
- @TCzechowski
- @toiletgranny
- @dmtrjsg

# Agenda:
1. Review todo's from last week,
2. Date & time formats — which should we be using in Atlas? Can this also be user-specific, depending on the locale?
3. Developers reassigning design GitHub issues (@KubaMikolajczyk),
4. **Finalize discussing Figma structure (@TCzechowski)**,

# Notes & Todo:

1. **Review todo's from last week:**
    - **🚨 @TCzechowski to initialize the discussion regarding "Time Blocks" in the NFT MVP epic GitHub issue.**
2. **Date & time formats:**
     - We decided to go with one date & time format for now, as the app is available in English only.
     - The exact format is yet to be specified, but we'll most likely use a European one, eg. `11 Nov 2021`, or `11 November 2021`.
     - Since we decided to stick to one format of date & time, we decided it makes sense to change our recent decision regarding numbers formatting and use one format as well. 
     - **🚨  All of the above to be thoroughly documented in a markdown document by @toiletgranny.**
3. **Developers reassigning design GitHub issues (@KubaMikolajczyk):** 
     - No action required.
4. **Finalize discussing Figma structure (@TCzechowski):**
    - 🎉 We have a consensus. **🚨 @TCzechowski to document this in a markdown document.**

**Comment by toiletgranny** [comment]
# 08.12.2021
Wednesday, December 8th, 2021.

# Participants
- @kdembler
- @Lenorette
- @TCzechowski
- @toiletgranny
- @dmtrjsg

# Agenda:
1. Review todo's from last week,
2. Review & discuss @dmtrjsg's "Delivery Cadence" Miro board,
3. Discuss @dmtrjsg's concerns around the updated Sign up flow.

# Notes & Todo:
1. **Review todo's from last week:**
   - **🚨 @TCzechowski to initialize the discussion regarding "Time Blocks" in the NFT MVP epic GitHub issue.**
   - **🚨 @toiletgranny to document decisions and create design guidelines for large numbers & date formatting,**
2. **Review & discuss @dmtrjsg's "Delivery Cadence" Miro board:**
   - We went through selected parts of the document, with Dmitry offering an in-depth explanation of his intentions and expectations.
   - We agreed for the design team to discuss & review the "User Testing and Validation Cadence" part internally, and form suggestions for changes and adjustments to the process. The outcome will be discussed during next week's meeting.
3. **Discuss @dmtrjsg's concerns around the updated Sign up flow.**
   - We discussed the confusion around the "Sign up" vs "Sign in" in UI, as well as the whole situation behind users connecting their Polkadot accounts with Joystream memberships.
   - We arrived at a conclusion that current designs need to be updated to address the above.

**Comment by dmtrjsg** [comment]
Transferred to Notion: https://www.notion.so/joystream/5df344a0addf4b8e872f7f781806f8ca?v=51ff0abeb7c6430abc6207d861098657
