### ISSUE TITLE
Remove shared components folder

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#1541]
Involves reorganizing the components into a possibly new folder structure / renaming / cleanup

**Comment by kdembler** [comment]
I think we could also use this occasion to introduce standarized way of component structure. I'd like to propose the following rules:
1) Each component should have it's own directory, named `ComponentName`, regardless of number of files it requires.
2) Each directory should have `index.ts` inside it allowing importing directly from the directory
3) Each directory should contain `ComponentName.tsx` file that contains the main component
4) Styles for the component should be in file named `ComponentName.styles.ts` (note the pluralization of style**s**, I think it will be good to clean this up)
5) Similarly, stories for the component should be in `ComponentName.stories.tsx`.

A lot of component will already follow the above, but some will require a bit of cleanup
