### ISSUE TITLE
Channel searching is not working

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1554]
So, it seems searching for channels doesn't work as it should be. At first, I thought that the problem lies in the query node and its limitations, but did some testing, and something definitely don't work correctly.
Here's proof
Playground: 
![image](https://user-images.githubusercontent.com/51168865/140486393-b75944a3-63e8-4d52-b23f-1b57e7052483.png)
Our app: 
![image](https://user-images.githubusercontent.com/51168865/140486444-adfac49b-3a21-4ba3-bb00-ae00b1b4f996.png)

**Comment by rafalpawlow** [comment]
I think we will not be able to fix this until this issue will be resolved https://github.com/Joystream/joystream/issues/2800

**Comment by kdembler** [comment]
Yeah I think this may be the case. If you add `whereVideo: {}` to the query, channels are no longer returned properly :/

**Comment by kdembler** [comment]
Although @wyrdrender, one fix I think we could make is to not send `whereVideo` at all when there are no filters selected? I guess most of the time users won't be filtering

**Comment by kdembler** [comment]
After some discussion with @wyrdrender we agreed that this is currently blocked by https://github.com/Joystream/joystream/issues/2800 and we won't be able to provide any fix on Atlas side

**Comment by kdembler** [comment]
Closing this as we're moving away from `search` query as part of #2882
