### ISSUE TITLE
Document TransactionModal component

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1561]
First off, sorry for not using the issue template yet, I will add those in the coming week!

So currently in the implementation we have a component that's called `TransactionModal` - this is the component that we display to the user when there is a blockchain transaction ongoing:
<img width="471" alt="Screenshot 2021-11-06 at 12 58 14" src="https://user-images.githubusercontent.com/12646744/140608763-2431361b-23cc-4e74-901d-4ae55296a694.png">

However, the design information about this component is scattered across different files and it isn't really documented in the components library so it's hard to understand what the final version is supposed to look like. Current locations in the design:
- First iteration - https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=9066%3A227107
- Usage in upload flow improvements - https://www.figma.com/file/mMGcjK0usOHzKXAwcBdwiv/%5B%2310%5D-Upload-flow-improvements?node-id=51%3A8561

It'd be great to have documentation for this component in a single place!

**Comment by toiletgranny** [comment]
@kdembler Designs and docs for this component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5207%3A204082). Let me know if this is what you were looking for or if there's anything missing. On the Figma side, the goal is to start using this component in our designs moving forward.

![image](https://user-images.githubusercontent.com/35307309/151798326-08e88e28-6203-434f-8d93-4442fdcd07bb.png)

**Comment by kdembler** [comment]
Fantastic, thanks for cleaning this up!
