### ISSUE TITLE
No empty state for Channels tab in search results

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1576]
<img width="1392" alt="Screenshot 2021-11-09 at 17 17 15" src="https://user-images.githubusercontent.com/12646744/140962384-c5334e54-4859-4710-b597-26f9fcb728e3.png">

**Comment by wyrdrender** [comment]
I'm not able to reproduce it
![Zrzut ekranu 2021-11-10 o 11 13 43](https://user-images.githubusercontent.com/13706246/141094441-9979818e-2905-4156-ac49-627eba878981.png)
