### ISSUE TITLE
Logged out user error

### ISSUE THREAD

**Issue by rafalpawlow** [Joystream/atlas#1586]
When user is not logged in and tries go to `/studio/videos` a meaningless error appear
<img width="1680" alt="Zrzut ekranu 2021-11-12 o 12 52 31" src="https://user-images.githubusercontent.com/13706246/141462972-c63217fd-0e4f-469a-a143-f8f3de9577a8.png">

Maybe instead of this we could show user some information that she/he should log in or automatically redirect her/him to `/studio`
@kdembler WDYT?

**Comment by kdembler** [comment]
From what I can tell, what you suggest is already happening. If I log out or use browser without the extension and go to the `studio/videos`, I get redirected to Studio login page. Could you double check that an error is happening and if yes, could you provide steps to reproduce?

**Comment by rafalpawlow** [comment]
@kdembler Take a look

https://user-images.githubusercontent.com/13706246/141765125-38a31878-7d9e-4290-a609-d5f675197ea0.mov

**Comment by kdembler** [comment]
Yep you're totally right, not sure how I missed that previously
