### ISSUE TITLE
Update the "Top navigation" design component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1588]
Based on information gathered from @Lenorette, as part of the NFT MVP scope of work.

**Comment by toiletgranny** [comment]
The new Top navigation component can be found here: 
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135755

**Comment by toiletgranny** [comment]
<img  style="text-align: center" width="584" alt="member_dropdown" src="https://user-images.githubusercontent.com/35307309/143443254-ab77f2dd-a621-4663-b68d-51b14ee256af.png">

@bedeho As we'd like to finalize the new Member dropdown component, as part of work for NFTs, I wanted to clarify a few things on what and how (and where?) can we communicate to users in regards to their **tJOY** balance, for now, on the testnet.

What I know so far, thanks to your answers to @Lenorette questions [in this issue](https://github.com/Joystream/atlas/issues/1496), is that the only way for members to get tJOY would be to "get some initial small amount from Jsgenesis", "earn by participating in the community", and "receive from other users in the community directly".

If we can agree that all of the above information is important to me, as a member of the platform on the testnet, to know, my questions are:
1. What would be the most convenient way for us to explain all of that? 
   - Should it be a simple in-app modal with a few lines of text, that opens up upon clicking on the "Learn about tJOY" link highlighted on the screenshot above (1)? That 
   - ⭐  Or should we link to some external resource, such as a markdown document hosted in our repo, or a GitBook article, or a page on Joystream.org? I believe this approach might be more convenient for end-users as this way I get a sharable link that I can reference eg. during a conversation with someone else on Discord. I also think this could be easier for us to adjust and maintain later on, eg. if we find out that something might require a different or more detailed explanation.
2. Who could I ask for preparing some content for this?

I would appreciate your perspective on the above.

CC @dmtrjsg

---------

_The design above originated from @Lenoratte's initial design explorations on the member dropdown that you might have seen on [her previous video updates](https://www.loom.com/share/6ecd2f95a67e49ca8d63fe11134cedb6)._

<img width="584" alt="member_dropdown_original" src="https://user-images.githubusercontent.com/35307309/143444078-7947e78e-c66a-4411-a4f7-f5beaa3a0d1e.png">

**Comment by bedeho** [comment]
Hi, excellent questions

- Lets use an external link, that way we don't need to have the design team get looped in as we change things about what opportunities are available.
- I think @dmtrjsg can coordinate this with @robertneckelius , who heads up marketing, as I think he is creating content around this at the moment already.

PS: Don't know what the screenshot with the blurred avatar is, but looks juicy as hell :drooling_face:

**Comment by toiletgranny** [comment]
**⚠️ No action required**
_I've mistakenly started the above discussion in the wrong GitHub issue, but now let's just keep it here. My above questions and answers below are connected to this issue: https://github.com/Joystream/atlas/issues/1645_

----

Ok, cool! @dmtrjsg, @robertneckelius let me know if I can provide any other details, guys! :)

PS: @bedeho  Glad that you liked it! 🔥 It's just the [new member dropdown](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3201%3A111989) that can be opened up from the top navigation, by clicking on your avatar while signed in. You've seen it previously in Nina's video updates regarding NFT; it's just here we applied some finishing touches and visual adjustments during making a proper component out of it.

**Comment by kdembler** [comment]
I don't have anything valuable to add to the discussion taking place here but I just love this member dropdown, god damn 🔥

**Comment by kdembler** [comment]
Let's only include the topnav work here, without anything related to the member dropdown (no double avatars, etc)
