### ISSUE TITLE
Customer Analytics and Feedback Tools Discovery

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1590]
**Context:** 

Atlas product reached the point in its evolution where analysis of product usage and capturing regular feedback from users is required to enable the team to effectively work on subsequent product releases. The immediate need for capturing and analyzing user sessions was brought up by Netguru team last week as part of the overarching initiative to validate the usability of new features developed. Since most of the user sessions capturing tools in the market offer additional features, such as and not limited to surveys, NPS, polls, and event funnels, the broader topic of overall product analytics and user feedback can be addressed here in order to define a holistic toolset for enabling feedback-focussed user interactions and product analytics.

Quite often the solutions in the market span both analytics and workflow features, hence these two topics are combined, for the benefit of including such vendors.

Capabilities covered here with respect to Atlas project analytics and user feedback are considered equally important and relevant for other user-facing products (Pioneer), unless specifically stated otherwise. 

**Requirements:**

The overall capabilities that Joystream cross-functional team is seeking to obtain are product usage analytics and customer feedback.

_**Analytics**_

**Individual user sessions recording and review** - Ability to record and analyze single user sessions individually as well as a sample out a number of sessions to review that have the same params (e.g. review the full recording of an individual user session and watch a few sessions out of all that match a set of params like duration, region, has interacted with a particular feature)*

**Aggregate users behavior and trends - Funnels tracking** - Ability to view statistics of user events funnel and drop rates at an aggregated level (e.g. view % of users that leave the app after stage 2 of content publishing workflow; where do users go after landing on page X)

**Aggregate users behavior and trends - Custom events tracking** - Ability to view usage statistics of a custom event (e.g. view  % and count of users who clicked on Feature X, % and count of users that choose Y in the drop-down  on page Z)

_**User Feedback/ Product Ops**_

**Surveys** - ability to distribute and analyze surveys with different types of questions supported (binary, open short, open detailed, multiple select)

**Feature request** - ability to collect feature requests from users, mark up, group, and analyze

**Provide general feedback** - ability to collect general feedback from users, group and analyze

**Report bug** - the ability for users to report a bug effectively (capture details, tag before sending

**Upvote feature from backlog/roadmap** - ability to view the roadmap/ backlog of features and upvote subset of features and provide more feedback if applicable

**Recruiting users for detailed research** - Ability to recruit platform users for moderated usability tests and discovery interviews. Some sort of pre-screening and marking up the emerging panel of users with 

*All user data must be possible to filter by user attributes, such as traffic_source, geography, user agent browser, and tech, features used, pages visited, and any other custom parameters provided by the user during onboarding. A mandatory list of attributes is to be defined at a later stage and will depend on the capabilities of the potential tools "hired" to provide the capabilities listed here. 

**Non-functional Reqs:**

- Implementation of tools must not introduce custom code that will not be relevant for the other companies. If that is a necessity, the way how tools are implemented must minimize subsequent efforts on removing such code from Joystream instance when forking for their own purposes

- Tools should integrate with the current product and community mgt tools to the maximum extent possible (Github, TeamGantt, RocketChat, Discord)

**Approach to selection**

- Create a list of capabilities and prioritize the list in terms of importance
- Source/ create a list of potential software tools
- Create a mapping of sought for team capabilities with features of tools researched
- Consider integrations of new tools with existing comms and project mgt tools employed: Github, Rocket, TeamGantt
- Consider UX of tools in the analysis
- Consider Pricing of tools analysis

_The decision will be based on the combination of capabilities covered, ux, integration and pricing considerations._

TBC: scoring model can be developed in case decision making requires a more systematic and objective view on the matter

**Current list of potential tools under review**

User analytics:

_Session based>_
[FullStory](https://www.fullstory.com/)
[SmartLook](https://www.smartlook.com/)
[HotJar](https://www.hotjar.com/)

_Event based>_
[Amplitude](https://amplitude.com/)
[MixPanel](https://mixpanel.com/)

_User Workflows>:_
[HotJar](https://www.hotjar.com/)
[UserSnap](https://usersnap.com/)
[ProductBoard](https://www.productboard.com/)

**Comment by dmtrjsg** [comment]
Just found smth that might be a great candidate for the session recs if not the winner. https://livesession.io/ > there's a video run-through of all the features covered but in essense its a **very targeted app that focuses only on user session recordings**, and does it well, while not crossing with analytics or workflow tools, so fits in perfectly with reasonable pricing and good UX. 

WIP review of the tools is here: https://miro.com/app/board/o9J_ljXQMLY=/

**Comment by kdembler** [comment]
@dmtrjsg We can close right?
