### ISSUE TITLE
Olympia Faucet - Atlas

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1596]
# Background

The membership creation faucet which powers Atlas does not work any longer, as it relied upon certain runtime features that are no longer present, specifically `addScreenedMember`. We need some way to allow this sort of faucet to work both for Atlas and now for Pioneer, as each has onboarding flows that allows for automated membership creation.

# Proposal

The Olympia runtime has a membership system which has the concept of invitations, where a each member can create new derivative memberships which have a default quantity of funds in their controller account that is subject to an invitation lock. This approach is more aligned with how onboarding will work in the future, as it has a lock which dramatically diminishes the incentive to attack the faucet, since the funds can only be used to pay for normal transaction fees, not capture . When we transition to a runtime which will have non-zero fees, this will be important, as we can no longer create memberships which have 0 default balance. For this reason I suggest we use this feature to power an updated version of our faucet, found in the private repo 

https://github.com/Joystream/membership-faucet

We can def. make this repo public also. All invitations could be made from a dedicated invitation member which has an invitation quota which can be easily updated by the membership working group lead, or by SUDO I believe.

**Comment by jodator** [comment]
Thank you for the example. The solution described here is quite clever and should be fairly easy to setup. I'll try to prepare a solution for the Olympia.

**Comment by jodator** [comment]
@bedeho I've updated the existing faucet to use a dedicated member to invite new. We should be able to test in with Pioneer onboarding process locally to verify the workflow.

Few things to notice. In order to invite members we must check two things:

1.  The membership working group budget – needed for the invitation lock
2.  The number of invites for member – to be checked

**Comment by jodator** [comment]
The PR is ready. The faucet uses a designated member to invite new members.

@bedeho & @dmtrjsg This cause one nuance:

![](https://user-images.githubusercontent.com/247363/143604280-1b2b853f-7ca8-4ad4-af25-ece269c5e526.png)

This member will be visible in the Pioneer app as it is returned by the query node. Also, all of the onboarded uses will be seen as invited by this special member.

Without changing the runtime for onboarding purposes I see that we could:

*   whitelist such member on the Pioneer side (kinda tricky but might be doable)
*   handle such invitations on the query-node with a different `entry` type (this entry could be "ONBOARDED" or something like this). Probably a similar effort as changing Pioneer.

**Comment by bedeho** [comment]
Great job! I am not actually sure I understand what problem you are trying to solve, are you trying to avoid surfacing this member in Pioneer? I don't think that is a real problem.

**Comment by jodator** [comment]
> Great job! I am not actually sure I understand what problem you are trying to solve, are you trying to avoid surfacing this member in Pioneer? I don't think that is a real problem.

Yes – I was worried that this Member will be always visible. If that's not an issue, that's even better as it's less work and maintenance.

**Comment by dmtrjsg** [comment]
@mnaamani to help define (create issues) to handle the implications of this issue in other repos.

**Comment by mnaamani** [comment]
Implementation was fixed by @jodator and merged into https://github.com/Joystream/membership-faucet/tree/olympia
It is published as docker image `joystream/faucet:olympia` and I have tested on playgrounds successfully through pioneer but need to confirm it was tested by Atlas.

**Comment by kdembler** [comment]
Closing since this has been implemented and integrated since
