### ISSUE TITLE
LiveSession snippet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1599]
Hi,
--
Dmitry Meltsov (dmitry@jsgenesis.com) shared your email with us so you can install LiveSession on . Please see the instructions below:
Add this code to your HEAD website section.
<script type="text/javascript"> !function(w, d, t, u) { if (w.__ls) return; var f = w.__ls = function() { f.push ? f.push.apply(f, arguments) : f.store.push(arguments)}; if (!w.__ls) w.__ls = f; f.store = []; f.v = "1.0"; var ls = d.createElement(t); ls.async = true; ls.src = u; var s = d.getElementsByTagName(t)[0]; s.parentNode.insertBefore(ls, s); }(window, document, 'script', ('https:' == window.location.protocol ? 'https://' : 'http://') + 'cdn.livesession.io/track.js'); __ls("init", "029d5963.01f6daca"); __ls("newPageView") </script>
You can find installation guides for popular platforms (including WordPress and Google Tag Manager) here: https://livesession.io/help/get-started/
Please reply to this email if you have any questions.
Thanks,
LiveSession Team

**Comment by kdembler** [comment]
I will generate this myself once we set up a new account 👍

**Comment by dmtrjsg** [comment]
Seems like we'd need to re-install on all subdomains. Generated a new ID for Atlas: 
029d5963.a21f20e4

Over to you @kdembler  :)

**Comment by dmtrjsg** [comment]
@kdembler  sorry pal, one last update here, as we need to point Atlas snippet to .org website ID.

To-do> update the website id to "029d5963.08106298"
