### ISSUE TITLE
VideoWorkspace new tab bug

### ISSUE THREAD

**Issue by rafalpawlow** [Joystream/atlas#1622]
**Describe the bug**

When you try to add new tab in video workspace, it's in edit mode and there is no way to add video file.

**To Reproduce**

1. go to studio
2. click "Upload video"
3. click "+" button on tabs bar

**Expected behavior**

Clicking "+" button should open new tab with possibility of adding a video file.

**Screenshots**

![Zrzut ekranu 2021-11-22 o 14 16 17](https://user-images.githubusercontent.com/13706246/142868333-46046ea9-f673-4597-a6ca-36793b7cf0c7.png)

**Device (please complete the following information):**

- OS: macOS Monterey
- Browser Chrome 96

**Comment by drillprop** [comment]
Cannot reproduce on dev. Read https://github.com/Joystream/atlas/pull/1652#issuecomment-982781661
