### ISSUE TITLE
Test Issuing NFT Experiences : Regular form vs Wizard

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1626]
# Concept

_We want to test two different experiences for a new flow of Issuing an NFT. Our initial assumptions are that each experience may be more appealing to a different group of users._ 

# Assumptions:

#### Regular form:
_A simple form on the right, NFT card visualization on the left._
Pros: Faster for power users, easy when done over and over again
Cons: Harder to explain more difficult concepts for a new user, must rely on tooltips & documentation
Better for: Power users

#### Wizard form:
_Big explainer field on the left, step by step options on the right_
Pros: A better explanation for a total beginner of complex NFT related concepts
Cons: Might get tiring when done over and over
Better for: Beginners

# What do we want to test?

- Is this option of issuing NFT easy to discover?
- Is the user aware that the video will become immutable after issuing?
- Is one experience easier to navigate than the other?
- Is it faster to complete one experience vs the other?
- Does the user understand unique NFT concepts better after completing one experience than the other?
- Understand possible user pain points.

# How will we test this:

Using maze unmoderated sessions:

**TEST LINKS**
Issue NFT "Regular form" - [link here](https://app.maze.co/maze-preview/mazes/63131457)
Issue NFT "Wizard" - [link here](https://app.maze.co/maze-preview/mazes/62765709)

During moderated sessions on lookback.

**Comment by KubaMikolajczyk** [comment]
# Test results


**Tested users:**
- 51

**Is this option of issuing NFT easy to discover?** 
- It's not the first thing user sees when using video workspace, but it's discoverable and no issues were reported by the users regarding the concept of issuing NFT being a switchable part of video adding flow.

**Is the user aware that the video will become immutable after issuing?**
- Yes. 64% of the users answered correctly. (Will you be able to edit your video later, after issuing it as an NFT? - No)

**Is one experience easier to navigate than the other?**
- Yes. Most of the users preferred the "Wizard" (26) experience over the "Single-step form" (13). And in later comments, many of them stated that wizard experience is:  "easier for me to use and understand", "took less time to adapt". So we can easily assume that the Wizard experience will be easier to navigate for both new and regular users.

Is it faster to complete one experience vs the other?
- Yes and no. "Single-step form" was completed on average 8.4 s, and the "wizard" in 4.2s - we can't assume much based on this as we had to show users both experiances in the same order. So while completing a single-step form they were also learning the interface. 

Does the user understand unique NFT concepts better after completing one experience than the other?
- Yes and no. We can't answer that as we asked our users our questions after showing them both of experiences - but shows us that it can take more than one prototype for a user to get familiar with those complicated concepts.

# Thoughts from users

## **After testing "Single-step" prototype:**
 
![image](https://user-images.githubusercontent.com/31144205/143892177-7eb52d96-561b-4e77-b646-075a430619c8.png)

- One user suggested moving toggles next to labels as they are hard to discover on the right
![image](https://user-images.githubusercontent.com/31144205/143891789-4ba7b816-c9f1-41e5-aa91-777c136788fc.png)

- Multiple users suggested it was intuitive and clear, pretty easy and understandable
![image](https://user-images.githubusercontent.com/31144205/143891855-a125ada9-b6e5-45e1-976d-52e1444d4e0f.png)
![image](https://user-images.githubusercontent.com/31144205/143891876-9159a2a7-3f5c-49cd-b36a-0cb5eb411e0f.png)
![image](https://user-images.githubusercontent.com/31144205/143891896-c3a9cc55-7b1b-40c5-9776-6196fcbfb074.png)
![image](https://user-images.githubusercontent.com/31144205/143892057-acd7e7b4-dae3-4ecf-9ea4-f23e19b29dd1.png)

## **After testing the "Wizard" prototype:**

![image](https://user-images.githubusercontent.com/31144205/143892275-d739cea4-1e24-4e66-a472-5eb1cfde3942.png)

- Many users stated that they like the "single step form" design better but they understand that it will be better for a new user
![image](https://user-images.githubusercontent.com/31144205/143892647-6da7691f-192d-4e9a-85e4-51f4a4b79f08.png)
![image](https://user-images.githubusercontent.com/31144205/143892697-0d21fe2e-0fc0-4aca-b98e-751e65de5968.png)
- One user suggested adding joy to $ conversion
![image](https://user-images.githubusercontent.com/31144205/143892915-21320419-e701-4c3a-8ffc-7cf1b1e4ec4d.png)

## **Which experience you preferred?**
![image](https://user-images.githubusercontent.com/31144205/143893003-680b7ea0-aaec-415a-95cc-a85b9f78c35c.png)

- One user suggested a user should be able to choose advanced or beginner version 
![image](https://user-images.githubusercontent.com/31144205/143893242-552cc493-99c5-4057-ba51-ffb7960a1bf0.png)

- Many user sugested that wizard approach was easier, and more readable
![image](https://user-images.githubusercontent.com/31144205/143893835-ac6a9466-c700-4d4e-a879-df8dc9c87352.png)
![image](https://user-images.githubusercontent.com/31144205/143893857-0eb6b6da-d889-48e5-a7f7-00a000e21f82.png)
![image](https://user-images.githubusercontent.com/31144205/143894203-7c60b1fc-e4d4-49cb-bc9a-c81177c45ef4.png)
![image](https://user-images.githubusercontent.com/31144205/143894245-4238d316-9119-45bf-aec2-87340963b7e8.png)



- But there were also many voices rooting for single step approach
![image](https://user-images.githubusercontent.com/31144205/143893934-1395e20d-ddab-487d-95ef-9591549efd60.png)
![image](https://user-images.githubusercontent.com/31144205/143894068-d6887912-8b49-4768-aa89-dfd8a5c57efa.png)
![image](https://user-images.githubusercontent.com/31144205/143894117-7631a35d-ca6d-42bd-a2d7-b5e0b8f1d6ec.png)
![image](https://user-images.githubusercontent.com/31144205/143894164-52ecd4b6-f083-49d1-88d8-19cebb14a0f1.png)
![image](https://user-images.githubusercontent.com/31144205/143894300-d2c288ac-c39a-4de7-ab76-318839929311.png)
![image](https://user-images.githubusercontent.com/31144205/143894332-b0569e62-e6e3-4535-9f9f-d1af738e74df.png)

# Conclusion
Based on our findings two times as much users lean more towards the "Wizard" approach (66%) and while many users stated that single step form approach would be easier and quicker for them, more users describes wizard approach as more approachable and more readable. 

I would recommend going with wizard experience for now and test its performance carefully in the future. For now it will be a safer choice, preffered by majority of testers.

**Comment by bedeho** [comment]
Excellent writeup, I am happy to go with this :)
