### ISSUE TITLE
Create information component

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1628]
### Description

A unified information component is needed - a hoverable element triggering tooltip.

### How urgent this is?

Not a blocker, but still worth considering

**Comment by toiletgranny** [comment]
@kdembler I think the `design-system` label should be added automatically to all issues created with the issue template I provided you with. Is there anything that changed when you uploaded that issue template?

**Comment by kdembler** [comment]
@toiletgranny I didn't change anything in the template, the issue is that the template assumed a label called `design-system` but in our repo it was called `design system` (with a space). I changed the label name yesterday so it should be properly applied going forward

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/150374703-8b9a5bb8-f7a8-424e-8256-f54643af56a5.png)

Designs and the documentation for this component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4819%3A169964).

For the implementation of this component, it's critical to support keyboard & touch-screen devices usage. All the details can be found in the documentation.
