### ISSUE TITLE
Create a new member/channel dropdown to allow for having memberships in the viewing experience

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1645]
### Description

Based on information gathered from @Lenorette, as part of the NFT MVP scope of work.

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
The new Member dropdown component, along with a full documentation designers & engineers, can be found over here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3201%3A111989

Please note, that the new Member dropdown requires having implemented other recently changed/introduced components:
- https://github.com/Joystream/atlas/issues/1649
- https://github.com/Joystream/atlas/issues/1656
- https://github.com/Joystream/atlas/issues/1589

**Comment by toiletgranny** [comment]
**⚠️ Attention**
_I've mistakenly started a discussion regarding this component in the wrong GitHub issue. Discussion relevant to this component can be found over here: https://github.com/Joystream/atlas/issues/1588_

**Comment by kdembler** [comment]
I LOVE IT

**Comment by kdembler** [comment]
Displaying number of tJOYs will be handled in #1762

We will do member switch animation in #1763
