### ISSUE TITLE
Avatar component adjustments

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1649]
### Description

When an avatar with a black image is placed against a pure black background, the visual boundaries of this component get blurred. 

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
@Lenorette has added a 1px semitransparent outline to all variants of the Avatar component.
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=104%3A76

**Comment by kdembler** [comment]
As part of this issue, let's also cleanup the Avatar variants in the implementation
