### ISSUE TITLE
Unify sign in flow 

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1653]
Unify sign-in experience for both experiences publisher and viewer

Please note, that the new Sign in flow requires having implemented other recently changed/introduced components:

- https://github.com/Joystream/atlas/issues/1645
- https://github.com/Joystream/atlas/issues/1588
- https://github.com/Joystream/atlas-resources/issues/2#issuecomment-979026239

**Comment by Lenorette** [comment]
Hey, here's the final video walkthrough for unified Sign-up flow.
Let me know if all is good 

https://www.loom.com/share/5790cec2a44049478acb2e099c278c7f?sharedAppSource=team_library

Figma file
https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up?node-id=105%3A202

**Comment by bedeho** [comment]
Great work, thanks for the video, left one minor question/comment.

**Comment by kdembler** [comment]
Hey, a bit late on the feedback but I have some points to raise:
1. I'm a bit concerned about removal of the `Welcome to Joystream Studio` screen. What should happen if the user navigates to Studio (for example with `Joystream Studio` button in sidenav) and is logged out? Should we just show [this screen](https://www.figma.com/file/dKOFSvTQAQ23mJQEj73yRA/Sign-up?node-id=302%3A36163) right away? I think this may be a bit "rough"? Is the user expecting that they need to log in right away without any prior message?

2. The Polkadot stepper includes a close button. What is supposed to happen when I click it? What about being in Studio and doing an initial login?

3. After the very initial designs for this flow were done, we discovered that some users had issues with the Polkadot extension - maybe by mistake they denied the application access to the extension and were left blocked. To solve this problem we've added a small button in the Polkadot extension screen to give users some instructions on how to proceed in that case. I think now that we're refreshing those screens we should include this in the design so we stay in sync. This is what we have currently (obviously needs to be slightly updated) (the modal opens after clicking the button at the bottom):
<img width="512" alt="Screenshot 2021-12-03 at 09 48 06" src="https://user-images.githubusercontent.com/12646744/144573449-9f45ca60-4d1a-457a-8fe8-2f666dec70c1.png">
<img width="554" alt="Screenshot 2021-12-03 at 09 48 09" src="https://user-images.githubusercontent.com/12646744/144573416-bc56e780-dd24-45a3-997b-20adc6998f3d.png">

4. I'm also curious about the screen where you choose the Polkadot account. The design uses those circle-y images to represent the accounts. What's the goal here? Are we supposed to use those same static images for all the accounts or the goal here was for those to be somehow generated for each separate account? We currently use something else in the implementation but would want to sync up.
<img width="361" alt="Screenshot 2021-12-03 at 09 55 59" src="https://user-images.githubusercontent.com/12646744/144577327-9d1114ed-624f-45d5-a824-b592d3541c26.png">

**Comment by Lenorette** [comment]
Hey @kdembler thanks for the feedback

> 1. I'm a bit concerned about removal of the Welcome to Joystream Studio screen. What should happen if the user navigates to Studio (for example with Joystream Studio button in sidenav) and is logged out? Should we just show this screen right away? I think this may be a bit "rough"? Is the user expecting that they need to log in right away without any prior message?

Removing  `Welcome to Joystream Studio` screen was a decision made with @bedeho . I think we could just change button in side nav to “Sign up button” we have in top navigation (also then we will have everything cohesive) - with some additional text like: "After Signing up you will be able to create channels, own NFTs" ect.
wdyt?

>2. The Polkadot stepper includes a close button. What is supposed to happen when I click it? What about being in Studio and doing an initial login?

Ok so I think (and I've already updated designs) that we should display PolkaDot dialog box just above the page on which Sign up was call (ofc with a dark overlay), so when users closes PolkaDot box he'll stay on the same page he was looking at. 

>3. I think now that we're refreshing those screens we should include this in the design so we stay in sync. This is what we have currently (obviously needs to be slightly updated) (the modal opens after clicking the button at the bottom):

Thanks for letting me know about it I'll update it this in our designs.

>4. I'm also curious about the screen where you choose the Polkadot account. The design uses those circle-y images to represent the accounts. What's the goal here? Are we supposed to use those same static images for all the accounts or the goal here was for those to be somehow generated for each separate account? We currently use something else in the implementation but would want to sync up.

Those random circle avatar are taken form PolkaDot itself (they create one unique avatar for each account). I didn't acctually changed it in any way for NFTs, this was previously designed that way. And we think it's a pretty nice thing to have, for sure it will be easier for users to select specific account they want from PolkaDot. 
Is there any reason why we don't have it implemented? And will you be willing to make it happen? :D

**Comment by bedeho** [comment]
> Removing Welcome to Joystream Studio screen was a decision made with @bedeho . I think we could just change button in side nav to “Sign up button” we have in top navigation (also then we will have everything cohesive) - with some additional text like: "After Signing up you will be able to create channels, own NFTs" ect.
wdyt?

I guess the screen, or at least _a screen_, make sense in one flow but not in another. So I still don't see a need for it while clicking the initial login button from the consumer side, but if you are just hitting the studio section directly, then something else does make sense. Is this kind of distinction practical on a technical level @kdembler ?

**Comment by kdembler** [comment]
1. I agree with what @bedeho proposed here, my suggestion would be to have _a screen_ when you first go to Studio, even if to just get a very brief introduction. Not a problem on a technical level.
2. I was mostly concerned with this close button in the above case, if you went to studio for the first time and you would get a modal with a close button, user would be left out with an empty screen? If we go with my suggestion from point 1, then I think we're good here 👌 
3. Yeah this was done ages ago, will be great to have this in the design, thanks!
4. Okay so the case here is that we don't have access to those images that the extension generates, we only get the address string. It's possible this wasn't properly communicated when we were doing the first implementation. However, did a quick check and it seems there's a library for generating those so we will introduce them.

**Comment by Lenorette** [comment]
Ok, so I've added "Studio welcome screen" which will only be display when:
a) user goes directly to Studio without being signed up first in viewer
b) user already signed up in viewer and goes to Studio for the very first time.

you can check it here https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up?node-id=513%3A18756

**Comment by kdembler** [comment]
I think we may need to slightly update the screen - it uses the old Joystream Studio logo with a badge, we're using just `studio` logo now and it will be already displayed in the topbar (see https://github.com/Joystream/atlas/issues/856). Also, you've mentioned that this would also be shown to the user that has signed in already but hasn't visited studio yet. Should we still use the `Sign up` primary button in that case?

**Comment by Lenorette** [comment]
OMG I've missed the logo, will update is quickly!!!
As for second  (b)) scenario I hoped that you'll also check screen below 😂 
heres the direct link to that screen https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up?node-id=513%3A18757
We've changed label inside the button :)

**Comment by kdembler** [comment]
> As for second (b)) scenario I hoped that you'll also check screen below 😂

Ah crap I completely missed that, thanks for pointing this out 🙇‍♂️ 

--- 

One last question regarding the logo inside the screen. In our current implementation we show the topbar above this screen, like so:
<img width="1407" alt="Screenshot 2021-12-06 at 13 39 00" src="https://user-images.githubusercontent.com/12646744/144847561-51a4fee0-6a99-4c3c-9181-55670da697a3.png">
 
Your design suggest the topbar shouldn't be visible here at all but I'd opt to keep it (doesn't cause layout changes when we later introduce it, we could also show the logged in user avatar). WDYT?
