### ISSUE TITLE
Membership profile page designs

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1657]
### Features that must be included in MVP scope:

- [x] Display all NFT’s I issued / created 
#1751  #1808 
- [x] Display all NFT’s I own as a member 
#1752  
- [x] Trigger starting an open auction 
#1753  
- [x] Cancel an open auction 
#1754  
- [x]  Bid on an open auction 
#1756  
- [x] Control public presence (name, desc, avatar) in atlas 
#1803 #1804 #1805 #1755  
- [x] Copy link from NFT tile 
#1807 
- [x] Change price from NFT tile 
#1806

- [x] #1809

Please note, that this  flow requires having implemented other recently changed/introduced components:
- https://github.com/Joystream/atlas/issues/1553
- https://github.com/Joystream/atlas/issues/1662

**Comment by Lenorette** [comment]
Link to final designs in Figma
https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?node-id=0%3A1

Final video walkthrough 
https://www.loom.com/share/4800e34d2622408faac52857a98682b2?sharedAppSource=team_library

**Comment by dmtrjsg** [comment]
Dev is covered in Epics: 

#1750 and #1802
