### ISSUE TITLE
Update "Option card" components

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1676]
### Description

Based on information gathered from @KubaMikolajczyk, as part of the NFT MVP scope of work.

### Figma link

https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=796%3A48187

### How urgent this is?

This will block me soon

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/146954693-7572cc7a-b52f-4962-b2b2-e1a6f7906b73.png)

The updated "Option card" component, along with a full documentation can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4118%3A144975

While the full list of changes can be found in the "Changelog" part of the documentation in Figma, the key changes are:
- Adding an icon variant to be used in the issuing NFT flows,
- Bringing Figma component and its implementation counterpart closer together, eg. by adding "disabled" or "error" states which were missing in Figma and present in the implementation, but also taking this opportunity to adjust the styling of the above states.

---

![image](https://user-images.githubusercontent.com/35307309/146955329-f645988a-8194-4255-b72a-d563ca10a6db.png)

Supporting the standalone "Option card", there's now a new "Option card group" component combining two other components that were previously used in Figma: "Option row horizontal" & "Option row vertical".

This component and its documentation can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4118%3A155697

---

If this is helpful, here's the original component design in Figma, which served as a base for the current implementation: https://www.figma.com/file/yaw2k1Fw5sezLoYLLRU10v/Web-Components-(PX-Grotesk)?node-id=750%3A90472

**Comment by kdembler** [comment]
Dev AC:

- [x] Add any missing variants
- [x] Make sure implementation follows all the colors/states from Figma
