### ISSUE TITLE
Create a "NFT card" component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1678]
### Description

Based on information gathered from @KubaMikolajczyk and @TCzechowski, as part of the NFT MVP scope of work:
- https://www.figma.com/file/uY98FOmQPgozpNOtAiklBg/Issuing-NFT?node-id=1063%3A67422
- https://www.figma.com/file/yVS7nkKjUtCeBcjUDqBbCF/Transaction?node-id=660%3A33264

### How urgent this is?

This will block me soon

**Comment by toiletgranny** [comment]
The NFT card component can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3807%3A139770

https://user-images.githubusercontent.com/35307309/145983905-20786b94-cf2d-4686-b7b4-429f989b670a.mp4

Please note, that this component can be implemented with or without a 3D effect upon hovering. In case the tech team decides to proceed with the extra fun, I'd highly recommend for the developer assigned to this to sync with me before tackling this.

**Comment by TCzechowski** [comment]
Changed the status because we need additional variant for mobile.

**Comment by toiletgranny** [comment]
Component updated, now it comes with two breakpoints: `XXS` and `SM`. For other information please refer to my last comment above.

**Comment by kdembler** [comment]
As part of this task, let's skip the 3D interaction and holographic effect
