### ISSUE TITLE
Prepare final screens for NFT issuing 

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1684]
## Description
Final screens for the issuing experience should include:
- Choosing to list for sale or not
- Choosing the type of listing
- Summary of NFT listing

## Figma link
https://www.figma.com/file/NdNx5jV2R2IDeMflnWPMD7/Issuing-NFT-(Master)?node-id=105%3A202

**Comment by kdembler** [comment]
Btw, I'm hoping the design will also provide the desired behaviour of video workspace when you are in the middle of the NFT issuance and you switch the tab to another video, etc.

**Comment by KubaMikolajczyk** [comment]
# Overview
Final screens for NFT Issuing can be found on the video workspace page under NFT workspace.

# Figma links
https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=916%3A21173
