### ISSUE TITLE
The Category Picker Completely covers the screen on mobile

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#172]
On mobile the `CategoryPicker` on the production version of the app will end up covering the whole screen, completely obfuscating videos.

![image](https://user-images.githubusercontent.com/29527327/102233094-293f0080-3ef0-11eb-93c6-b10cf9fa12ce.png)

The design does not cover this case, since the screen showed uses a low number of categories.

**Comment by bedeho** [comment]
The current UI design is actually not that functional either, a better solution is needed, horizontal scroll?

![Screenshot 2020-12-15 at 16 32 36](https://user-images.githubusercontent.com/437292/102235970-37425080-3ef3-11eb-9786-bf4f73501596.png)

**Comment by KubaMikolajczyk** [comment]
This pattern is getting a complete rework in the redesign of discover page.
Discover page : [Discover page link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9775%3A4626)
also https://github.com/Joystream/atlas/issues/874
Should we close this? @kdembler

**Comment by kdembler** [comment]
Yes sir
