### ISSUE TITLE
Create mobile size component for Polkadot dialog window.

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1724]
We need to prepare small version design for Polkadot dialog box.
https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up?node-id=502%3A54724

**Comment by toiletgranny** [comment]
Note: we need to update the Stepper component inside as well so that it's scrollable horizontally.

**Comment by dmtrjsg** [comment]
Superceded by Talisman
