### ISSUE TITLE
Component: Notifications Centre

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1741]
AC:

- [ ] Just the list of items with checkboxes, without the floating action bar and managing checkboxes

[Link to Figma >](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications-(Copy)?node-id=901%3A94454)

<img width="687" alt="Screenshot 2022-01-20 at 12 08 15" src="https://user-images.githubusercontent.com/93924525/150336069-e0469166-bc8d-4c33-ab6d-b05dde9ac0f6.png">

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1741?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
