### ISSUE TITLE
Auction Winner Settling the Auction

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1742]
## Context

This issue encapsulates design and development of settling the auction by the winner. 

After auction is won, the user has to _actively_ settle the auction for the ownership transfer to be recorded on the chain. This transaction of ownership transfer has a fee applying to it, paid by the winner.  In fact this can be done by any agent, but we are restricting it to the winner in the UI. 

🎥  [Video walkthrough](https://www.loom.com/share/4cc368aad7ab4f498c2271a6831d8ac3)

## AC
- [ ] Notification event - auction won - snack bar deep-linking to auction settlement page
- [ ] Auction settled confirmation snackbar
- [ ] Handling the transaction
- [ ] Animation Confetti on the winner's view

## Designs

🎨 [ LInk to Figma ](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=1237%3A23354)

**Comment by TCzechowski** [comment]
Hello @bedeho!  Continuing our discussion from [Rocketchat](https://chat.jsgenesis.com/channel/atlas-design?msg=3CsWJnSpAQbvN6L5x), we came up with some additional questions: 

1. How does the settlement process exactly look like?
2. Is settling the bid time restricted?
3. If yes, who sets the duration/deadline? If the platform sets it, how long would that duration be?
4. If not, how do we prevent potential situations where person won the auction, but didn’t settle it and the auction became frozen for, potentially, ever?
5. I assume that since “settling the bid” is a blockchain transaction, the user would need to pay the transaction fee for doing that. Is that correct?

cc: @dmtrjsg @toiletgranny @Lenorette @KubaMikolajczyk

**Comment by bedeho** [comment]
> How does the settlement process exactly look like?

So I assume we are here talking about an English auction, as for open auctions the owner has to actually accept the bid for it to be the winner - this would instantly update ownership.

During English auctions, anyone can submit valid bids, one greater than the other, and when the finalization period has passed, the last valid bid (i.e. the largest value bid), will have won the auction. However, winning the auction at this time expiry does not update the ownership by itself, which also means that the payment for the old owner, or the royalty or the platform fee, is not made. Someone has to make a call to the extrinsic `claim_won_english_auction`, for this to happen. Now, _anyone_ can actually do this, not only the new winner. So the channel owner, or a DAO participant, or the new owner or just a random member can do this sort of settlement.

> Is settling the bid time restricted?
> If yes, who sets the duration/deadline? If the platform sets it, how long would that duration be?
No.

> If not, how do we prevent potential situations where person won the auction, but didn’t settle it and the auction became frozen for, potentially, ever?

There is no real incentive to do this, but there is no way to prevent this currently. A wide variety of agents have an incentive, and an ability, to settle the auction.

> I assume that since “settling the bid” is a blockchain transaction, the user would need to pay the transaction fee for doing that. Is that correct?

Yes.

**Comment by TCzechowski** [comment]
Thank you for the answers, @bedeho! 

> Now, anyone can actually do this, not only the new winner. So the channel owner, or a DAO participant, or the new owner or just a random member can do this sort of settlement.

I'm a bit confused on how this process would look like. As I imagine it now, it would look like this:

1. The highest bid wins the auction when it's duration ends
2. Then, **_the owner of this bid_** has to go to the settlement page (which will be accessible only for that bidder)
3. Then, they have to confirm the settlement and make a blockchain transaction
4. Then, the ownership of that NFT is transferred to them.

But my thought process involves only the bidder, and you are saying that anyone can do this. Would that settlement page be accessible for everyone then? And anyone can settle the auction for this bidder?

**Comment by bedeho** [comment]
> Then, the owner of this bid has to go to the settlement page (which will be accessible only for that bidder)

Firstly, I am only talking about the properties of the _system_ not about the Atlas UI, so I am not thinking in terms doing something on page X or Y.

Second, _anyone_ can settle the bid, not only the winning bidder. As I said

_Now, anyone can actually do this, not only the new winner. So the channel owner, or a DAO participant, or the new owner or just a random member can do this sort of settlement._

> But my thought process involves only the bidder, and you are saying that anyone can do this. Would that settlement page be accessible for everyone then? And anyone can settle the auction for this bidder?

Again, I am not talking about what you can do in Atlas, but the system. In Atlas, we can choose to present the relevant actions to the actors for whom we think it's most relevant. I think that, at least for now, it's certainly sufficient to only make Atlas present this settlement opportunity for the winning bidder, that will likely cover all practical cases in the near to medium term.

**Comment by TCzechowski** [comment]
HI @bedeho!
I've recorded a video where I go through the prototype that I quickly prepared to show you how I imagine the settlement process and to clarify if I've missed something.

Did I miss anything? Is something more complex than that? Or did I miss any additional costs that we should inform the user about? Let me know!

https://www.loom.com/share/4cc368aad7ab4f498c2271a6831d8ac3

**Comment by bedeho** [comment]
`Perfect`

**Comment by dmtrjsg** [comment]
<img width="939" alt="Screenshot 2022-01-26 at 10 52 43" src="https://user-images.githubusercontent.com/93924525/151150944-05d00ed7-f1ba-4eee-9e04-78988f8ac8d4.png">

On this screen I wonder if it is clear enough that the bid was placed - a toaster confirmation message applies?

**Comment by bedeho** [comment]
> On this screen I wonder if it is clear enough that the bid was placed - a toaster confirmation message applies?

That seems quite orthogonal to the scope of this issue, this is just about how to settling auctions, which has nothing to do with any sort of feedback on the event that you just placed a bid, the bid would be placed possibly long in advance of auction settlement. Perhaps I am misunderstanding.

**Comment by dmtrjsg** [comment]
Correct, I was just making sure we are supporting the placement of bid with appropriate visual cues on the ui side.  We've confirmed this during the call, and implementation is addressed in a different gh issue.

**Comment by dmtrjsg** [comment]
Just reviewing this again and thinking we need to inform the bidder about the settlement fee in the placing bid flow.. @TCzechowski  shall we update [the respective designs](https://github.com/Joystream/atlas/issues/1859) with  "Auction winners need to claim the ownership transfer with setting the auction results. This is a _separate transaction_ and incurs a fee of ** {{JOY}} ?

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1742?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow

**Comment by dmtrjsg** [comment]
#1742
