### ISSUE TITLE
Component for notifications widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1743]
<img width="637" alt="Screenshot 2022-01-20 at 12 07 32" src="https://user-images.githubusercontent.com/93924525/150335919-695607bb-3aef-48da-b47b-fcebeae789da.png">

[Link to Figma >](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications-(Copy)?node-id=901%3A94457)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1743?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
