### ISSUE TITLE
Update the "Pill" component with new variants & add a "Pill group" component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1760]
### Description

Based on consultation with @kdembler and @wyrdrender, in the light of upcoming changes & refactor of the "Video tile" component, we decided to expand and use the "Pill" component for displaying eg. a time duration of the video, or its status in Studio (Draft, Unlisted). This requires the "Pill" component to be expanded and enhanced with new variants.

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=909%3A98162

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
The updated "Pill" component can be found over here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=909%3A98162

The original "Pill" component had no variants, but because we've been already using it in other places (eg. in the "Tab" component) it's important to note that the original version of this component is now of size: small, styling: default, and layout: text.

**Comment by kdembler** [comment]
To do:
- Update the component
- Introduce to the Storybook
- Make sure Pill is a proper component, with its own styles, independent of Badge
