### ISSUE TITLE
Add a new variant of the "Channel card" component + update the component to use color design tokens inside

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1767]
### Description

I need a version of channel card without a button
Maybe a smaller size of the card could be also created

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A25135

### How urgent this is?

This will block me soon

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/146952910-49001069-af9a-498c-b840-496203bc6d75.png)

The component is ready to be reviewed & implemented under this link: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4094%3A144630
