### ISSUE TITLE
Icon on reconnect file button shouldn't have stroke and should have different color 

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1772]
**Describe the bug**

as the title says. 

**To Reproduce**

1. Go to studio, and upload video
2. Refresh when uploading to interrupt uploading
3. Go to my uploads
4. Click on the upload bar
5. You should see a button with the wrongly colored icon

**Expected behavior**

The icon should be black
Design: https://www.figma.com/file/eyXP72Qq5oPMbxZhJrh4Wd/%5BPage%5D-My-uploads-(Publisher)?node-id=430%3A4831

**Screenshots**

![image](https://user-images.githubusercontent.com/51168865/145228208-2629ae3f-d5db-4be7-90de-ae295c6f8e39.png)

**Device (please complete the following information):**

- OS: [e.g. macOS Monterey]
- Browser [e.g. Chrome]

**Comment by kdembler** [comment]
Will be done as part of https://github.com/Joystream/atlas/issues/3130
