### ISSUE TITLE
Create an "Avatar group" component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1778]
### Description

The goal of this task is to create an Avatar group component, stacking multiple avatars together, with a predefined spacing between single avatars.

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
The read-to-be-implemented component can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3742%3A136245

**Comment by kdembler** [comment]
Looks good!
