### ISSUE TITLE
Create an "NFT tile details" component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1792]

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/146148321-45702ca0-637c-4101-81e3-ebefa058807a.png)

Designs for this component can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3630%3A138983

I highly recommend catching up on Tandem with the assigned developer(s) _before_ the implementation of NFT & Video tile components begins.

---

Related components:
- https://github.com/Joystream/atlas/issues/1790
- https://github.com/Joystream/atlas/issues/1793
- https://github.com/Joystream/atlas/issues/1553
- https://github.com/Joystream/atlas/issues/1792
- https://github.com/Joystream/atlas/issues/1791

**Comment by kdembler** [comment]
Will be tackled as part of #1791
