### ISSUE TITLE
Refactor & update the "Video tile details" component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1793]

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/146149297-2f71c193-b9c6-4df1-ab8f-18f244522951.png)

Designs for this component can be found here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3630%3A112904

I highly recommend catching up on Tandem with the assigned developer(s) _before_ the implementation of NFT & Video tile components begins.

---

Related components:
- https://github.com/Joystream/atlas/issues/1790
- https://github.com/Joystream/atlas/issues/1793
- https://github.com/Joystream/atlas/issues/1553
- https://github.com/Joystream/atlas/issues/1792
- https://github.com/Joystream/atlas/issues/1791

**Comment by kdembler** [comment]
This will be tackled as part of #1553
