### ISSUE TITLE
WIP: Creator Tokens design brief 

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1799]
WIP.

**TODO**

* [ ] Documentation
* [ ] Video recording of concepts for design team
* [ ] User stories

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1201959124126446) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
superceded by https://github.com/Joystream/atlas/issues/2400
