### ISSUE TITLE
Disabled buttons looks bad

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#181]
<img width="498" alt="Screenshot 2020-12-21 at 16 09 49" src="https://user-images.githubusercontent.com/12646744/102791254-06589480-43a7-11eb-8ef0-a73b5875ee39.png">

I guess they may be too bright - they look unattractive

**Comment by ghhrmnzdh** [comment]
Add `loading` state for buttons or it's too distracting? This design also matches the `placeholder` that is being used accross the project. Also the text and icons should darken a little bit, for example `colors.gray[200]` is a good choice.

**Preview**:

![loading-state-button](https://user-images.githubusercontent.com/35824204/103434554-55f55680-4c18-11eb-9dbe-63ef59f185ef.gif)

**Comment by bedeho** [comment]
Lol @kdembler I already had an issue for it, but very encouraging that our judgements are converging ;)

https://github.com/Joystream/atlas/issues/185

**Comment by bedeho** [comment]
> Add `loading` state for buttons or it's too distracting? This design also matches the `placeholder` that is being used accross the project. Also the text and icons should darken a little bit, for example `colors.gray[200]` is a good choice.
> 
> **Preview**:
> 
> ![loading-state-button](https://user-images.githubusercontent.com/35824204/103434554-55f55680-4c18-11eb-9dbe-63ef59f185ef.gif)

I think the issue here is that what type of loading animation is used is not going to work universally in all contexts, which is not actually that surprising. We will get the designer to look at this and create a new guideline.

**Comment by kdembler** [comment]
I think the immediate hotfix will be just darkening the background and/or text a bit to find something that feels visually good

**Comment by kdembler** [comment]
Fixed via #191 for now. There are no other places in the app that actually use disabled buttons, so I guess once designers decide to use them, they'll add designs for them as well. Closing for now
