### ISSUE TITLE
Support staggered rollout 

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1821]
# Background
Is described here https://github.com/Joystream/joystream/issues/2948.

# Proposal
It's not actually clear what the launch state will be, and whether one can have any meaningful Atlas experience right from genesis. For example, while storage system is frozen, will there be distributors who are teed up to work from block 0 with content? Needs to be revisted, in the meantime this issue is a placeholder.

## Scope

- [ ] Design (and implement) placeholder screen for Atlas App to be shown, while the network is beeing rolled out. Service outage sort of screen impacting all modules.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202196251276767) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Based on the rollout described in the linked issue, seems like using Atlas would make sense only once the full rollout is done (content directory extrinsics come last). Taking this into account, I guess all we would need from Atlas is some kind of "Chain is booting up" view that would be displayed during rollout?

**Comment by bedeho** [comment]
Yep, which we already have some solution for, so I'm just going to close this. Also, I am going to reduce complexity of the roleout as well.
