### ISSUE TITLE
Create NFT widget component

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1822]
Link to final design in Figma
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1242%3A109695

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1822?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
