### ISSUE TITLE
Non-public channels visible in "Newsest channels" section

### ISSUE THREAD

**Issue by Lezek123** [Joystream/atlas#184]
After adding a channel with `isPublic` set to `false` I can still see it in the "Newset channels" section and by visiting the channel page (`https://play.joystream.org/channel/CHANNEL_ID`).

When using Hydra playground (https://hydra.joystream.org/graphql) I can see this channel beeing returned by `channels` query, but  it has `isPublic` correctly set to `false`

**Comment by kdembler** [comment]
Fixed now
