### ISSUE TITLE
[USERSNAP] Account created with wallet 5FC..Ejoy

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1840]
## Scope

- [ ] Add validation that membership is already created before user is allowed to sign

## Context
**Taken at**: https://play.joystream.org/studio/membership/new
**Fields**:
- Expected Result: Account created with wallet 5FC..Ejoy
- Houston, we have a problem.: Only New Accounts Can be Used for Screened Members

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8ca2e45b-0b4b-426e-9c57-07c3893eee27-annotated_97c3d648-0d72-43cf-af4b-a2449c075c2b.png?etag=f026f7d611384bb5bdb676ec09078f74)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8ca2e45b-0b4b-426e-9c57-07c3893eee27-annotated_97c3d648-0d72-43cf-af4b-a2449c075c2b.png?etag=f026f7d611384bb5bdb676ec09078f74)*

**Browser**: Chrome 96 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 506x905
**[Open #5 in Usersnap](https://app.usersnap.com/l/feedback/e7a9dce1-7a2f-4af7-b340-9a009f58a0a7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
<img width="1398" alt="Screenshot 2021-12-29 at 12 20 52" src="https://user-images.githubusercontent.com/93924525/147662206-aa147d79-1df6-4a14-8e33-a2d2c5b3ae93.png">

**Comment by dmtrjsg** [comment]
<img width="929" alt="Screenshot 2021-12-29 at 12 26 01" src="https://user-images.githubusercontent.com/93924525/147662176-2c0b64c6-cd7f-4925-8dba-5a8216b7f038.png">

**Comment by kdembler** [comment]
https://github.com/Joystream/atlas/issues/3172 should take care of this
