### ISSUE TITLE
Create animation templates for Joystream product demo videos

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1844]
The output for this task is going to be an Adobe After Effects file used as a boilerplate for all future short product demo videos for social media. This is to ensure consistency between consecutive videos, and also between product videos from 2 different teams: Atlas & Pioneer.

Ideally, the file contains:
1. Animated Joystream logos,
2. Animated & customizable titles,
3. Animated Joystream background patterns,
4. Cursor images & animations,
5. Start & ending screens templates,
6. (optionally) App screens framing & animation examples.

**Comment by toiletgranny** [comment]
The After Effects file with Joystream animation templates is ready for me and @MattAugustynowicz to review, discuss, and finalize. Our next meeting is currently planned for Tue, Jan 25. Depending on the feedback, I'd account for 8 more hours of work here at most.

https://github.com/Joystream/design/tree/master/social-media/product-animations/_template

**Comment by toiletgranny** [comment]
Based on our call, together with @MattAugustynowicz we agreed to update the animation templates with 3D screen visualizations and a couple of transition presets (patterns, shapes, and movement).

The updated After Effects file [can be found here](https://github.com/Joystream/design/tree/master/social-media/product-animations/_template), and a demo composition render below. Please note that the below animation has been created solely to showcase some of the animation templates and presets provided in the AE file.

https://user-images.githubusercontent.com/35307309/151978083-9a0cba8a-0bae-478f-8252-2474e55a3a2d.mp4

**Comment by bedeho** [comment]
Looks promising!
