### ISSUE TITLE
Loading of home page controls update

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#185]
Seems like the default loading state does not look that great, and actually greates a bad temporary high contrast which is disurptive

![Screenshot 2020-12-28 at 20 16 27](https://user-images.githubusercontent.com/437292/103238055-d3377780-4949-11eb-9892-3272dfc679b3.png)

It will probably work better to not show any button during loading, and instead fade in the button itself just as with the background itself. Not 100% sure that will work either, but worth trying. If that also looks funky then a designer must look at it, so just premptively tagging it with design label for now.

**Comment by kdembler** [comment]
Related to #181

**Comment by kdembler** [comment]
Reopening that - even once we fix the disabled button look, I still think it will be a good idea to show buttons only once the video is loaded
