### ISSUE TITLE
Channel NFT Tab Search

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1854]
**Context**
Search on NFTs tab

**AC**

- [ ] Search Box appears on "magnifying glass" icon click
- [ ] Mechanics of search exactly the same as on play.joystream.org right now with exact match from title returning non-zero results
- [ ] Zero results page taken from Videos

⚠️ Search is not added to any Figma files.

**Comment by dmtrjsg** [comment]
@Lenorette can you pls include Search into the figma files.

**Comment by Lenorette** [comment]
Done here https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=581%3A30133

**Comment by kdembler** [comment]
@Lenorette there are couple open question left from me that design doesn't answer atm:
1. Does it work the same for videos?
2. What happens if I start searching for NFTs and switch to Videos tab?
3. What happens if I start searching and switch to Information tab?
4. How does search works and looks on mobile?

It'd be great if you could include this

**Comment by Lenorette** [comment]
>1. Does it work the same for videos?

Yes, exactly the same. https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=626%3A32402

>2. What happens if I start searching for NFTs and switch to Videos tab?

Search should be canceled and we should display all videos from newly selected tab. Search filed should change back to Icon only. When Search expanded again it could remember last search word.

>3. What happens if I start searching and switch to Information tab?

You should open up Information tab and search should be canceled/cleared, in Information tab Search icon should not appear at all.

>4.How does search works and looks on mobile?

https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=626%3A40606
When user click on Search text field on mobile, automatically native keyboard should appear and user should start typing. With pressing return/go/enter on keyboard search should start. User can quickly cancel search by clicking on X icon inside search field. 
When user switch to a different tab, same as on desktop search should be canceled and we should display all videos.

let me know if it's enough and if all is good now ;)

**Comment by kdembler** [comment]
Thanks so much for including those. One last thing, could we also include your answers for 2. and 3. in Figma so it's clear without looking for additional info?

**Comment by Lenorette** [comment]
Done, added that to Figma

**Comment by kdembler** [comment]
Thanks! All good from my perspective now, moving back to dev pipeline 👍
