### ISSUE TITLE
Owners Avatars on NFT videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1857]
**Context**
Displaying NFT issuing channel and owners avatars on the NFT card in list view

**AC**

- [ ] NFT owners avatars displayed on NFT card
- [ ]  Conditions
<img width="287" alt="Screenshot 2022-01-04 at 16 06 42" src="https://user-images.githubusercontent.com/93924525/148088205-2e631363-1d1a-4892-920b-7653b8409ecd.png">

**Design**

[Link to Figma](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=515%3A41506)

**Comment by kdembler** [comment]
Will be handled by #1791
