### ISSUE TITLE
NFT Purchase Layout with States and Validation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1859]
**Context**

Place the Bid View
<img width="842" alt="Screenshot 2022-01-04 at 17 31 08" src="https://user-images.githubusercontent.com/93924525/148099714-2e6551ca-1eb4-4fb6-ba74-906bbd956dbf.png">

**AC**
Different states of the screen
- [ ] English Auction no bids placed ⚠️  _Transaction fee_ instead of gas fee ⚠️ 
- [ ] Only the number of blocks left
- [ ] Open Auction [(no timer)](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=965%3A93201) 
- [ ] Insufficient [Funds  ](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=1022%3A102687)
- [ ] Amount entered is less than [minimum bid](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=1022%3A104907)
- [ ] Amount entered is [more than Buy now price ](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=1024%3A112415)
- [ ] Responsive [link to Figma page](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=993%3A96351)

**OOC:**
- [ ] Displaying an hour:minute timer
- [ ] English Auction Timer view [with < 1 minute to go](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=965%3A90622)

**Designs**

[Link to Figma >](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=964%3A134035)

**Comment by dmtrjsg** [comment]
@TCzechowski  added a few figma bubbles for quick updates, but overall feature is ready for dev so keeping in "ready for dev" pipeline for planning tomorrow while assigned to you. 

<img width="186" alt="Screenshot 2022-01-04 at 17 56 21" src="https://user-images.githubusercontent.com/93924525/148102720-b0d3887b-12c4-4604-a6c0-34b449769e37.png">

**Comment by dmtrjsg** [comment]
Fixed price sales (we only show "buy now price") and change the header from "Place bid" to "Purchase NFT" @TCzechowski  ⚠️  pls confirm if that was intended, or it is captured in the designs elsewhere?

**Comment by TCzechowski** [comment]
> Fixed price sales (we only show "buy now price") and change the header from "Place bid" to "Purchase NFT" @TCzechowski ⚠️ pls confirm if that was intended, or it is captured in the designs elsewhere?

It depends. When user enters this screen by clicking "Buy now" button instead of "Place bid", then they will see this screen:
https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-Purchase-view?node-id=1024%3A113877
