### ISSUE TITLE
Context menu component should use ListItem component as its items

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#1863]
Currently, we have some custom styled component inside Context Menu: 
![image](https://user-images.githubusercontent.com/51168865/148199666-becdb63b-9dbb-41d2-8a9b-251571967321.png)

We should make use of the recently added ListItem instead.

**Comment by toiletgranny** [comment]
Please note that there's also a change in the background color that needs to happen. Designs for this component, along with a changelog outlining what exactly has changed (November 23, 2021) [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3158%3A103636).
