### ISSUE TITLE
More than 5 members owning NFTs

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1866]
- [x] Up to 5 users shown as individual avatars, if more, then the last avatar is a circe with "+X" denoting additional members who own NFTs ⚠️  [TBC Figma Link](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=515%3A35953)

**Comment by Lenorette** [comment]
Designs for this are here https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=581%3A27950

**Comment by kdembler** [comment]
Looks good to me, closing since we will tackle this as part of the task we already have
