### ISSUE TITLE
Design a symbol for the JOY token

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1868]

**Comment by toiletgranny** [comment]
The goal of this task is to design a universal and easily scalable symbol of the JOY token, which is going to replace [the placeholder one we've been using so far in the designs](https://www.figma.com/file/2tlBY1JQtRMoyjmjJQ9jam/Icons?node-id=663%3A2191).

The expected outcome of the task would be:
1. A new icon design, preferably created natively for multiple common UI icon sizes (eg. 16x16, 24x24, 32x32, 48x48), [available in this Figma file](https://www.figma.com/file/2tlBY1JQtRMoyjmjJQ9jam/Icons?node-id=663%3A2191), as a replacement of the current contents of the "JOY token" Figma component.
2. A set of PNG, JPG & SVG exports with the new icon, uploaded to the [Design repository](https://github.com/Joystream/design).

While designing the icon it is recommended to consider selecting a Unicode equivalent of it to be used as a replacement of the "JOY" code or the graphical symbol. Perhaps [this conversation](https://ethresear.ch/t/proposal-change-ether-currency-symbol-from-to/120) might serve as an inspiration for this process.
