### ISSUE TITLE
Atlas Team Synchronization Document

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#188]
# Purpose

The set of people working on the Atlas product is changing substantially, and will likely continue to increase in the near future. This document is intended to synchronise the current and future contributors to Atlas around the current state of the product, and how we should move forward in 2021.

# Joystream

## Project

Joystream is an open source blockchain project for a new kind of video platform protocol. The distinguishing property of this protocol versus traditional platforms is the focus on enabling user ownership and operation. The best guide to the background analysis for the initiative is the [Joystream Manifesto](https://www.joystream.org/manifesto).

## Status

The project started in late 2018, and has since then been built and developed by a distributed team of developers, designers and community builders. The system is not yet live, and has so far gone through a number of test networks with increasing technical, product, economic and social complexity. Our current test network is the [Babylon Network](https://www.joystream.org/babylon). The main network launch of the system is currently expected some time in late 2021.

# Jsgenesis

Jsgenesis is a Norway based corporate entity tasked with the temporary mission of building the technology and community of the Joystream project. The role of the entity is as a temporary catalyst to get the system live, not as a permanent or even post-launch steward of the success of the system. The core premise of the project is that the community will be equipped to finalise and exercise all resource allocation and policy decisions required through the blockchain based governance system.

# Atlas Overview

## Product

The Joystream project has a large suite of different open source technology products, and (Atlas)[https://play.joystream.org/] is the first, and currently only, content consumption and publication product. It is a web application, of which there is only a single instance on https://play.joystream.org/, and it is powered by the infrastructure on the current Babylon network. It serves user goals very familiar the public consumer YouTube service. This can be contrasted with other user facing products, such as (Pioneer)[https://play.joystream.org/], which serves user goals associated with governance and operational activities.

## Status

The very first public release of Atlas was made with the launch of the Babylon, and it is still very early in the product life of the product. A very small subset of the planned, and even fully designed, features are present in the current public product. As a result the product has very limited, if any, usage outside of the core Joystream community at this time. This is likely to remain the case for some time, as the main priority will be to build out the basic product offering in such a consumer product, and also develop it in lock step with the continuously evolving blockchain (storage, bandwidth, query, telemetry, monetisation, etc.) infrastructure.

# Atlas Team

## Members :technologist:

1. Klaudiusz Dembler (Technical Lead): Works at Jsgenesis.
2. Francesco Bacetti (Front-End Engineer): Works at Jsgenesis, **leaves 1st February 2021.**
3. Bedeho Mender (PM): Works at Jsgenesis.
4. Wiktor Półtorak (Design Lead): Works at Netguru agency.
5. Milosz Klimek (Design Mentor): Works at Netguru agency.
6. Bartosz Dryl (Front-End Engineer): Works at Elpassion agency.
7. Mikołaj Jędrzejewski (Front-End Engineer): Works at Elpassion agency.

A few things are worth noting.

- The initial design of the consumer side of Atlas was not made by Wiktor and Milosz, they did however design the publisher side from scratch.
- We expect the Atlas team to keep growing in the early part of 2021 on the front-end engineering side.
- The design team has a few major contributions they will continue to do in Q1, but at some point they will need to pause their effort because the backlog of implementation work accumulated will have grown so large. It is however unclear when that would be. We have some thoughts about possibly doing a separate mobile and/or TV app, in which case that could be a subsequent area of work for this part of the team.

## Collaboration Patterns :handshake:

The collaboration has currently been organised as follows

- (1-3) have daily 0930AM (CET) internal stand-ups as part of rest of Jsgenesis team.
- (1-3) have weekly (mostly Monday morning) 1-2 hour team meetings about problems and priorities.
- 1,2 have ad-hoc calls on Zoom and discussion on Github and RocketChat.
- (3-5) have 1-3 weekly 15m-1h calls for discussion and review.
- 3 does asynchronous reviews of UI/UX designs from 4,5.

## Key Resources :books:

- Atlas Figma: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas
- Github Page of Joystream: https://github.com/Joystream
- Github Page of Atlas: https://github.com/Joystream/atlas
- Github Page of Hydra: https://github.com/Joystream/hydra
- Joystream Community Telegram Channel: https://t.me/joinchat/CNyeUxHD9H56m3e_44hXIA
- Jsgenesis RocketChat.
- Netguru Slack Channel.

# Atlas Planning & Execution Cycle :bulb:

In 2020 the planning cycle typically has worked something like this

1. Bedeho reviews project-wide priorities and constraints, and identifies the highest ROI focus area for next Atlas release. A release plan draft is prepared to this end, which includes considerations about required inputs from designers, infrastructure, etc.
2. Atlas team provides feedback on plan.
3. Designers & Bedeho produce UX/UI designs.
4. Front-End team plan total work scope required, addressing estimates on total time requirements for completion, an internal division of labour, required help from other non-Atlas team members of Jsgenesis, for example related to hosting, infrastructure, content, etc.
5. Bedeho provides feedback on product UI and provides input on changes in scope as a result of lessons learned during execution, and the Atlas engineering team continuously monitors progress and reassigns tasks based on workload balance and comparative advantage.
6. When Atlas work is part of a broader network release, the changes are tested internally by a Jsgenesis + Community Quality Assurance team.

At any time during this process there may be identification of bugs and also contributions from outsiders, these are tracked on Github and triaged in or out of the current release.

# Current Focus Areas :eyes:

1. We are working on introducing so called _personalization_ in the ongoing release https://github.com/Joystream/atlas/issues/30.
2. The biggest part of the publisher experience has just been designed to completion: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/?node-id=3119%3A0
3. We are about to start work fixing various imperfections and problems in the current design of the viewer experience that have been identified since the first design iteration. Some of the issue can be seen here: https://github.com/Joystream/atlas/issues?q=is%3Aissue+is%3Aopen+label%3Adesign
4. The Figma project is being reorganised and cleaned up so that it will be easier to use, because now it is quite badly out of synch with the actual app in various ways, and also not well organised or complete.

# Atlas Q1/Q2++ 2021 :rocket:

Here is the relevant information for what work is in scope for Q1/Q2 of Atlas team, and also how that work will be conducted.

## Future Atlas Priorities :scale:

Priorities are ordered roughly by expected completion time, however there is substantial uncertainty

1. Onboard `Bartosz` & `Mikołaj`.
2. Fix outstanding viewer side design debt.
3. Complete Figma reorganisation.
4. Release Atlas with personalisation.
5. Release Atlas powered by new smart contract content directory. More information on this later.
6. Release Atlas with publisher experience.
7. Release Atlas with additional content types in viewer and publisher side (playlists & episodic).
8. Release Atlas with v2.0 storage and bandwidth infrastructure. More information on this later.
9. Release Atlas with gateway system. More information on this later.
10. Release Atlas with monetization(advertising). More information on this later.
11. Release v1.0 of Joystreamjs library based on refactoring infrastructure facing code in Atlas.

#### Onboarding Milestones:

1. Get familiar with [dev resources](https://github.com/Joystream/atlas/tree/master/docs). Let Klaudiusz know how comfortable you are with the technologies/tools mentioned. Read up on anything that's unclear
2. Take a tour of Atlas: https://github.com/Joystream/atlas/issues/195
3. Start working on some of the basic issues from the project: https://github.com/orgs/Joystream/projects/37

During onboarding Bartosz and Mikołaj should collaborate closely with Klaudiusz and reach out if anything's unclear or questions arise.

## New Collaboration Pattern :mega:

Given the ongoing changes to team composition and focus areas, we have to remain flexible, but I suggest the following as a starting point.

1. We use RocketChannel for all work communication - `atlas` and `atlas-dev` channels.
2. A separate Atlas Front-End engineering daily standup, e.g. at 09:50am CET, between team members Klaudiusz, Francesco, Bartosz, Mikolaj, with Bedeho included if needed, led by Klaudiusz.
3. Only Klaudiusz, Francesco, Bedeho are part of Jsgenesis daily standup at 0930am, because this call is already quite large and focused on many other areas.
4. A Monday morning release meeting, with flexible start time, with Klaudiusz, Francesco, Bartosz, Mikolaj, and Bedeho, to track overall progress on the current release.
5. Bedeho, Wiktor and Milosz continue their ad-hoc weekly meetings as before.

All work done by engineers should correspond to some issue on Github, and this issue should have estimates.

## Any questions or problems?

Talk to Bedeho.

**Comment by kdembler** [comment]
Great doc, should be mighty useful going forward into 2021 :tada:

Some small things I wanted to bring up:

1. `Release v1.0 of Joystreamjs library based on refactoring infrastructure facing code in Atlas`. I wanted to clarify what's the status on that. Does that mean that `joysteam.js` won't be pursued outside of Atlas and all the infra-code should be handcrafted inside Atlas? Not sure if my question is clear, we can discuss that during 1-1.
2. Francesco suggested that the weekly release meeting can be just Bedeho-Klaudiusz to sync up on team progress. Considering that Atlas shall have a daily standup to discuss all the stuff internally anyway, I think that may be a good idea. I can aggregate the status and pass on any questions/concerns. I'm willing to try it out this way.
