### ISSUE TITLE
Update Navigation item components

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#1880]
### Description

Changes connected to https://github.com/Joystream/atlas/issues/1710

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/148533701-506dd83b-9dda-40fd-a90d-c6ae0f6b0774.png)


Designs and documentation for this component can be found here:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4322%3A172581

**Comment by kdembler** [comment]
This will be handled as part of #1710
