### ISSUE TITLE
Update top navigation to include the notifications button

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#1888]
### Description

https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=839%3A96757

Top Navigation:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135755

Button:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A6243

Badge:
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4284%3A141647

Icon:
https://www.figma.com/file/2tlBY1JQtRMoyjmjJQ9jam/Icons?node-id=304%3A2547

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135755

### How urgent this is?

This will block me soon

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/149151776-11fab011-a998-4ed4-9768-11d59a48d147.png)

Changes in the Top navigation component are ready to be reviewed. [Designs and documentation can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3173%3A135755).

@kdembler Perhaps it's a good moment to point out that we updated the "Search", "Zoom in" & "Zoom out" action icons to improve their legibility. Additionally, there's a new action icon we added: the lightning bolt representing notifications. The name of the icon is "Notifications". New icons & updates to the existing ones are ready to be fetched from our [Figma API -> Storybook](https://www.figma.com/file/1uxugLps6oooI38PGmdrn9/Figma-API-Storybook) Figma file.
