### ISSUE TITLE
Video loading playback with wrong dimensions

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#189]
The loading state should show a loader for the playback canvas which corresponds to what it will actually be when playback is ready, this should be possible, because the dimensions of the media are known from the metadata.

As a side note, because this information cannot be trusted, some sanity check should be conducted to make sure they are roughly rational, and if the numbers mismatch with the media, once available to the player, then the real values should be taken from the player as now.

**Comment by kdembler** [comment]
Which `loading state` do you refer to here? You mean when the full view is in the "placeholder" state with everything greyed out?

**Comment by bedeho** [comment]
Yes this is what I mean by loading state.

**Comment by kdembler** [comment]
Well then it's not really true that we know dimensions of the media from the metadata, because full placeholders is what's displayed when we're still fetching metadata

**Comment by bedeho** [comment]
Damn, you are right :(
