### ISSUE TITLE
Remove usag of `gap` with Flexbox

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#1899]

**Comment by eldiegod** [comment]
Flex gap seems to be pretty well supported nowadays I think we should be fine using it unless I'm missing something here

**Comment by traumschule** [comment]
> Flex gap seems to be pretty well supported nowadays I think we should be fine using it unless I'm missing something here

At least in updated browsers.

> CSS Gap is a feature of the CSS Grid spec and Flexbox. Currently Firefox is the only major browser that supports gap on flex items. Update: As of April 25, 2021, CSS Gap for Flexbox is supported in all major browsers! [source](https://coryrylan.com/blog/css-gap-space-with-flexbox)

**Comment by kdembler** [comment]
It's not that well supported, Safari added support in April 2021 which is less than a year ago, I want to support browsers 1.5y behind for now
