### ISSUE TITLE
Idea: Frontend possible dependency issue detected

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1905]
The failure of a third-party content provider could bring an overall breakdown of your website.
If you have to use a third-party content, ensure that you chose an asynchronous integration and that you have a fallback in case of problem.

**This resource represents a SPOF for this page:**
[fonts.googleapis.com/css2?family=IBM+Plex+Sans:w[...]500;600;700&display=swap](https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@600;700&family=Inter:wght@400;500;600;700&display=swap)

**Comment by kdembler** [comment]
Could you expand on how this is a single point of failure? If the font fails to load, the website will use certain fallbacks:
```
font-family: IBM Plex Sans, -apple-system, BlinkMacSystemFont, Avenir Next, Avenir, Segoe UI, Helvetica Neue, Helvetica, Ubuntu, Roboto, Noto, Arial, sans-serif
```
