### ISSUE TITLE
Idea: Reduce graphql response time 

### ISSUE THREAD

**Issue by VlodkoMr** [Joystream/atlas#1907]
Try to optimise graphql response time, it can speed up page load and provide better user experience.
Requests: http://joxi.ru/l2Z9kwkUlVREQm (waiting more than 1.00 second for response).

Possible solution: cache results or just some parts of the code.

**Comment by kdembler** [comment]
Unfortunately this is something that is out of our control at the moment. We've already made significant improvements over the last few months, currently Hydra (framework for indexing and querying the blockchain state) is the bottleneck. With Giza release coming soon we're using a newer version of Hydra which should improve the performance. This should improve over time. This is already mentioned here https://github.com/Joystream/joystream/issues/2818 so closing this ticket as I don't think there's anything Atlas-specific to do here. Let me know if you disagree
