### ISSUE TITLE
Drop support for multiple tabs in VideoWorkspace

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1913]
**Context**
Supporting multi tab setting for NFT issuing (inherited from studio)

**Design links**

The video tabs component was removed and replaced by the local component video workspace toolbar - which can be found here : https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1341%3A133231

All of the screens were adjusted to support new component. It's worth noticing how it behaves on small screens: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=969%3A17422

⚠️  🆕  Component:

- [ ] https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5096%3A145926

**Comment by dmtrjsg** [comment]
Question raised with Bedeho.

**Comment by KubaMikolajczyk** [comment]
# Video tab feature - user sessions review

Link to sessions: [Click here to watch sessions](https://app.livesession.io/app/08106298/sessions?filters=((must:session.start_url.:((string:((operator:contains):(values:((0:%2Fstudio%2Fvideo-workspace))))))::url))&pagination=((3:creation_timestamp_desc:10))&dateRange=((last_30_days:21-12-2021:20-01-2022))) (x8 speed recommended)

Keeping the video tab feature (which allows users to create and manage multiple video upload processes) would be hard and time-costly if it comes to supporting issuing NFT in multiple tabs simultaneously.

# Session user notes

1. user bde28b02, Uploaded: 1️⃣
clicks the close icon button on the left on the card instead of the close button on the right to close the document  

2. User d1a14831, Uploaded: 2️⃣  +
Uploadsmany videos one by one and do not use tab features at all  

3. User cd4d2f6d, Uploaded: 1️⃣
Uploads one video and do not use it  

4. User e3fac527, Uploaded: 2️⃣. +
Does not use it - although on the recording we can see that two tabs are open - the first one is just a draft and the user does not interact with tabs throughout the session

5. User cd4d2f6d, Uploaded: 1️⃣
Uploads one video and does not use video tabs  

6. User 20eb8cea, Uploaded: 2️⃣ +
Uploads multiple videos does not use the video tab feature

7. User 20eb8cea, Uploaded: 2️⃣ +
Uploads multiple videos does not use video tabs  

8. User d71136a8, Uploaded: 🛑
Used video tab to close panel  

9. User d71136a8, Uploaded: 1️⃣
Uploaded one video does not use the video tabs  

10. User 26c84d19, Uploaded: 1️⃣
Uploads video and does not use video tabs  

11. User 26c84d19, Uploaded: 2️⃣ +
Uploads several videos and does not use the video tab

 12. User 02092199, Uploaded: 🛑
Did not complete because didn’t recognize the video title field is mandatory  

13. User 27ffd6d0, Uploaded: 1️⃣
Uploaded one video that did not use the video tabs  

14. User c891cef9, Uploaded: 2️⃣ +
Uploads several videos and does not use the video tab bar

15. User a30ef20f, Uploaded: 2️⃣. +
Has initial problems with recognizing video title field as mandatory - then uploads one video does not use the video tabs, then uploads another video and does not use video tab, uses big upload new video are to upload a new video  

16. User 02092199, Uploaded: 2️⃣  +
Uploads several videos does not use video tabs  

17. User d71136a8, Uploaded: 2️⃣  +
Has 7 tabs open, one by one fills text content of those videos, looks like this user is reuploading own content from another platform to Joystream, then when uploading one by one user does not use the tabs to do this but rather draft section where her clicks on each draft to upload it  

18. User 20eb8cea, Uploaded: 2️⃣. +
Uploads several videos, does not use the video tabs  

19. User da3513b9, Uploaded: 1️⃣
Uses tab to quickly close the video workspace  

20. User 3569de3d, Uploaded: 1️⃣
Uploads a video does not use the video tabs  

21. User da3513b9, Uploaded: 1️⃣
Uploads one video does not use the video tabs  

22. User d2800330, Uploaded: 2️⃣ +
Uploads several videos does not use the video tabs. Uses big area upload video to upload a new video.  

23. User bad713d4, Uploaded: 2️⃣ +
Uses a video tab bar just to check what it does. Uploads several videos and uses a big area to do it, does not use video tab bar for multiple video uploading.

# Observations & Summary

For 35 recorded sessions, 21 (60%) of them ended in successful upload of video. (13 was browsing through but not uploading, 1 was abandoned during the process)  

Out of 21 sessions where users uploaded a video 9 (42%) of them uploaded just one, while 12 (58%) users uploaded more than one video during that particular session.

  Out of 21 sessions where users uploaded a video only 1 (4%) user used the video tabs feature for purpose of video uploading, 2(9%) of them opened a new draft and closed it after getting familiar with this feature, in 3(15%) user sessions user used video tab bar to close the video workspace, 16(76%) of users didn’t use the video tabs at all.  
  
  Users usually upload one video, wait on my videos page ,watch how it’s uploading and then click the big upload new video area to upload another one
  
  Overall - the observed usability of this component is low therefore I see no contradictions for removing it and maybe revisiting this pattern in the future.

**Comment by KubaMikolajczyk** [comment]
# Deprecate video tabs 

If we decide to deprecate this feature certain work has to be done on the design side.
- [x] Redesign the video tab bar component and rethink the usage of space 
- [ ] (optionally) Test video workspace closing 
- [x] Replace all old video tab bar components to new ones

Estimated time 1,5 - 3 days (depends if we test)

**Comment by KubaMikolajczyk** [comment]
# Overview
The decision to deprecate video tabs was based on user session recordings and complexity of development to maintain this pattern while supporting NFT issuing in multiple tabs. 

# Figma links
The video tabs component was removed and replaced by the local component video workspace toolbar - which can be found here : https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1341%3A133231

All of the screens were adjusted to support new component. It's worth noticing how it behaves on small screens: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=969%3A17422

**Comment by toiletgranny** [comment]
Update, based on today's design & tech sync meeting, the recommendation from @kdembler is to make this component global, due to the fact it's also being used in the designs for the NFT purchase view. The new component is now called "Drawer header", and is a temporary solution until we tackle the overlay system holistically (modals, windows, side sheets, popovers, etc.).

The designs for this component [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5096%3A145926).

![image](https://user-images.githubusercontent.com/35307309/151181352-a8898704-9e9f-4188-b5c7-071007586b36.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1913?planning-poker) with ZenHub @drillprop @rafalpawlow @eldiegod @lcoenengithub
