### ISSUE TITLE
Nft Issue Flow: Form fields for all progress steps

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1915]
**Context**

Issuing NFTs. This ticket is to accommodate for all form fields with validations used in Issue NFT flow except whitelisting.

**AC**
- [ ] Form fields for issuing NFTs

- [ ] [Listing Type page](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=980%3A19132)
- [ ] Auction Settings - [Royalties](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=988%3A27970)
- [ ] Auction Settings - [Minimum Bid](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=988%3A30356)
- [ ] Auction Settings - [Fixed Price](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=995%3A27365)
- [ ] English Auction - [Set Duration](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=996%3A28264)
- [ ] [Transaction Confirmation Page ](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=988%3A24905)
- [ ] Tooltips for all settings as [described here](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=988%3A22912)

** ⛔ Out of scope**
- [ ] Whitelisting
- [ ] Royalties validation (https://github.com/Joystream/atlas/issues/1950)
- [ ] Date/duration validation (https://github.com/Joystream/atlas/issues/1919)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1915?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
