### ISSUE TITLE
Handle date-related validation in NFT issuing

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1919]
**AC:**

- [ ] Handle validation of dates in past/future
- [ ] Handle summary screen when the start date is in the past - https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1251%3A93666
- [ ] Write unit tests for DatePicker component to test validation

**Comment by dmtrjsg** [comment]
Do external benchmarking on this 
Let's flesh out point 2 in design
Check with Runtime what it expects

**Comment by kdembler** [comment]
Sounds good, this was a solution I had in mind as well. In terms of runtime inputs, when creating an English auction, 2 parameters are expected:

- `starts_at: Option<BlockNumber>` - this is optional and I'm unsure how to interpret that, sent a question in the chat.
- `auction_duration: BlockNumber`

So it seems we should be fine with this approach. However, from my quick look at the runtime it also seems like there are no restrictions around the start date being in the past. So it's possible that the current approach from the design would fully work. @dmtrjsg

**Comment by KubaMikolajczyk** [comment]
# Overview
On Wed tech & design call, we agreed to adapt a pattern similar to other benchmarked marketplaces.

# Figma
It's done now - below are flows presenting new scenarios:
- [As a publisher I want to set an auction duration for an NFT that I’m issuing](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=996%3A28264)
- [As a publisher I want to select a specific date as a starting date and expiration date](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1212%3A93693)
- [As an publisher I try to select a past date for auction duration of NFT that I’m issuing ](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1080%3A87373)
- [As an publisher I try to select a date, but wait too long on listing summary page and the time passes](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1251%3A93953)

**Comment by kdembler** [comment]
@dmtrjsg I think this is to be closed?

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1919?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow @lcoenengithub
