### ISSUE TITLE
Issue NFT with Whitelisting of selected members

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#1921]
**Context**

NFT can be offered to a controlled / selected group of Joystream members. For this, Publisher needs to look up the members by member ID and add to the list on Step 2 and review on Step 3.

**AC:**
- [ ] On Step 2, the list is editable, on Step 3 the list is not editable
- [ ] Margins are slightly different on both pages @KubaMikolajczyk is that intentional ❓ 

**Designs**

Link to user stories in Figma:
 [Add user to whitelist](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1000%3A29308)
[Remove user from whitelist](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1003%3A32597)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1921?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
