### ISSUE TITLE
Atlas UI, UX and Figma project design debt

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#194]
# Purpose

Document the full set of issues that needs review from product designers at this time.

# Note

In this summary, the same part of the product may be addressed in multiple respects in different places, hence any solution must bring together a solution that simultaneously covers all concerns.

# Goal

The goal of this issue is to

1. fix certain problems of our current design of Atlas.
2. for our design resources to reflect a fully specified design, e.g. in terms of responsiveness, input treatment, animations, the current best understanding of either what is, or will be, in the Atlas product.

# Problems

## 1. Underspecified Product

The original design of Atlas itself was that is was not a full product design when it came to key screens, but rather just showed some examples of how the component library could be put to use.

The main screens are now as described in personalisation release:
https://github.com/Joystream/atlas/issues/30

## 2. Underspecified Responsiveness

The original design of Atlas itself underspecification of how the layout, images, videos and other assets should behave at different viewport dimensions.

### Video Grids

The design that appears to show a fixed size content preview for all viewport sizes, whether its when listing search results, viewing a channel, video suggestions under player, browsing or other screens. It is not clear from this what is supposed to happen for a bigger viewport, and for smaller viewports - like tablet and mobile, the content has the same dimensions.

The application has been built with a policy of

1. always filling the entire screen width.
2. adjusting size of previews based on width of viewport, to optimise for view-ability (this is done on both Youtube and Netflix). Specifically the policy keeps element margins fixed, always retains the aspect ratio of elements and adjusts their width according to a set of breakpoints that map how many elements should be visible horizontally as a function of viewport width. Try application to see it in action.

This has worked reasonably well, but the design in Figma does not reflect this. The approach must be reviwed, and the Figma must be updated.

### Home Screen Header

By "header" we mean the area starting under the search bar and ending at the first row of videos. The original design shows a single snapshot of home-screen header, just with two different images (illustration or skyline). It was not explained at all what should happen when viewport is adjusted, in terms of how background image should be scaled and whether the height of the header. After this, we got a specialised design for this header that was aimed introducing a featured content title and playing background video
https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/?node-id=2374%3A45800

However this also did not address responsiveness.

The header design in the app is separate from the main design, moreover, the application has a responsiveness policy which is both

1. missing from Figma
2. needs to be reviewed by a designer. We implemented a policy where the % amount of masking of the height of the cover photo is increased at certain breakpoints as the width of the viewport increases, and then a special approach for the mobile screen when everything becomes especially tight. One effect of the reset of the masking % is that it creates an unpredictable masking of the background imagery, but the upside is that it keeps the first row of videos within view even for quite wide screens. Here we need help both to review whether the policy is the best approach, and if so, what actual break points to use.
3. there is no explicit policy on how the appearance of the background image, although its quite clear that some constraints would improve the appearance, such as making sure it has some kind of built in gradient effect that works well with the UI gradient.

### Channel Header

The header section has the exact same set of problems and issues as the home screen header.

### Channel Grid Element

Here the issue is simply that, unlike video grids above, channels in grids, such as search results or carousels, are not subject to the same resizing policy as videos are in the current app. This has mostly been an oversight so far, but this must be subject to the same review and harmonisation in Figma as above.

### Series & Playlist Grid Elements

Same issue as for Channels, but these are not even part of the app yet, but same analysis and Figma update required.

### Player

There is no description of how to do this, and it appears to assume that all videos have aspect ratio of 16:9, which is not the case. We have some kind of policy here at the moment, but it does not manage the height ideally at the current moment, e.g. see here

https://github.com/Joystream/atlas/issues/91

and it also has the converse problem of not using the full height well, as even when it could allow a wider video width within the available height, while preserving the aspect ratio.

Currently, the playback mode is effectively like "cinema mode" on Youtube, so the playback area fills the full width of the screen. The policy used by YouTube seems to work quite well, as it also will deal with how to manage different aspect ratios, however it must be captured in our Figma, other parts of the design must be harmonised to work with this. For example the controls need to also be designed to suit the different sizes.

### Category List

https://github.com/Joystream/atlas/issues/172

## 3. User Input Robustness

The original design of Atlas itself did not take seriously being robust to user provided inputs of heterogeneous quality, such as images and avatars, or names and strings that were of arbitrary long.

- We need an explicitly described policy for dealing with length of user input strings, such as titles for videos, channels, descriptions, etc. Currently the app does random things to deal with it, but the design must explicitly capture it in some way, such as clipping, wrapping, etc.
- https://github.com/Joystream/atlas/issues/45

## 4. Miscellaneous Flaws

The original design of Atlas itself had mix of other problems & flaws:

- The hover animation provided for content units, such as videos and channels and series, is not compatible with the carousel button. No thought was made to how these should interact (e.g. https://github.com/Joystream/atlas/issues/42). An easy way to solve this is to just drop the buttons altogether, and use a partly visible next content item as a clickable/swipe-able button itself, but without any hover effect. There is also no prescription about how to treat the horizontal gradient gradient caused by the carousel when hovering (https://github.com/Joystream/atlas/issues/42#issuecomment-737298827)
- Its not clear what to do about the carousel if its not full, is that ok? what happens when a carousel goes empty while the viewer is watching, e.g. by closing out videos in the "Continue Watching" row. Some transition is required here.
- When on mobile, only a single carousel item is observed, requiring a lot of clicking: https://github.com/Joystream/atlas/issues/54
- Missing watchlist issues: https://github.com/Joystream/atlas/issues/131
- Missing progress indicator in carousel: https://github.com/Joystream/atlas/issues/62
- Keyboard controls need to be described at least a few places, such as exit out fo search overlay, control of player.
- Missing failed playback state: https://github.com/Joystream/atlas/issues/40
- Policy for dealing with empty search results in subcategories https://github.com/Joystream/atlas/issues/44
- https://github.com/Joystream/atlas/issues/9
- https://github.com/Joystream/atlas/issues/143

## 5. New Constraints

Since the initial design, the product itself has evolved on a path some what distinct from the initial design, and new design requirements have emerged that were not part of the original design.

- Original design has < > navigation in the top menu as a result of us hoping the same singular design could be used both in and outside browser, where the latter does not have browser based Band & Forward buttons, however, we have later concluded that this duality is not possible, so we are only focused on a pure browser experience.
- Channels you follow in menu https://github.com/Joystream/atlas/issues/30
- https://github.com/Joystream/atlas/issues/77
- https://github.com/Joystream/atlas/issues/62
- https://github.com/Joystream/atlas/issues/52
- https://github.com/Joystream/atlas/issues/178

## 6. Figma Project

Figma project itself was not organised in a way there was a manageable way to grow the set of features, and also provided integrated and contextual explanations of related information, such as animations, responsiveness and keyboard controls.

- There are lots of screens and visual elements that are not part of current or future versions of the product
  - Livestreaming indication on channel avatars
  - Drop the screens that have the illustration
- There are some screens or elements that are likely part of future releases, but not the one currently in production. Not sure what to do about this, see next section
  - login/logout button
  - registration and signup flows
- Update and harmonise all animations, and write one coherent animation guide document. Keep in mind that
there are animations in the app that are not in the design, such as the fadein of content previews or home header section, etc.
- Remove out entire page having to do with website integration: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/?node-id=2590%3A36640

### Questions about Figma & App synchronisation

1. How to we record and organise two different variations of some part of Atlas that reflect two levels of maturity, so they do not apply simultaneously? So an example could be (a) the channel screen as it currently is, and (b) the channel screen when we introduce playlists and series. We need a way to keep both variations, at least for some time, and there will always be an ever changing set of such disparities, as there is always some delay from the design to the implementation phase.
2. For the long term, should we aspire to keep Figma and the app in synch, or is this not a policy worth adopting?

**Comment by KubaMikolajczyk** [comment]
Most of issues here were closed. This issue's purpose was to provide designers with knowledge about design debt. Currently work is done in separate issues and we are all up to date so this issue can be closed.
