### ISSUE TITLE
Display minimized player after scrolling down

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#1941]
When user scrolls down below Video Player, we would display smaller, "minimized player" in left-bottom corner.

###Figma
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1242%3A113066

**Comment by bedeho** [comment]
Oh damn, this actually looked really cool 🤯 !

**Comment by dmtrjsg** [comment]
Agreed 
1. to use play again in the end of the video for hte minimised component
2. to show mini version on the right hand side

Designs: 

Flow: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=7260-310724&t=X7M8ez0mvy7apXaa-0
Component: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1244-87427&t=vH6oLXVKe3rY2QrZ-0
