### ISSUE TITLE
Notifications Maze Test #1

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#1945]
# Overview
The overall test was conducted to test the usability / discoverability of certain interface elements.

[Maze link](https://app.maze.co/projects/69870903/mazes/69870962/results)

# Participants
There were only 13 participants in total, which is too little for unmoderated test to provide reasonable results. We’ve sent emails to our user database from Usersnap and also on Discord, but it’s still much less than when we posted the link on Twitter (around 50 replies).

-----
#### Completion rate:
🟩  Direct success: **84.6%**
🟧  Indirect success: **0%**
🟥  Give up: **15.4%**

#### 📝  Summary:
- One tester did not notice “mark all as read” buttons neither in the widget, nor in the notifications page, and went straight to selecting notifications one by one. Then, after they’ve noticed the floating component, they’ve selected all notifications and marked them as read (which wasn’t a part in this mission, but somehow they’ve managed to do that in the prototype).
- One tester did not click the “mark all as read” button in the widget, but they opened the notifications page and clicked it there.
- Most of the testers did not have any problems with that mission.

#### 💡 Recommendations:
- No recommendations at this point, but I’d suggest to check after the implementation if the situation from first point in the summary happens more often (when we have the data from more users)
-----
#### Completion rate:
🟩  Direct success: **30.8%**
🟧  Indirect success: **46.2%**
🟥  Give up: **23.1%**

#### 📝 Summary:
- 1 person didn’t notice the “mark all as read” button on the notifications page.
- The reason why the indirect success rate is high is that the testers misunderstood the task and did the same thing as in the first mission. But then after realising they completed the task without any troubles.

#### 💡 Recommendations:
- No recommendations at this moment, except for me to write clearer task descriptions ;)
-----
#### Completion rate:
🟩  Direct success: **75%**
🟧  Indirect success: **8.3%**
🟥  Give up: **16.7%**

#### 📝 Summary:
- 1 tester (give up) opened notifications widget, marked ALL notifications as read and gave up. But that might be because they didn’t understand the task (They wrote that they are using Google Translate for this test and don’t understand task descriptions)
- 1 tester (give up) opened up notifications page and started clicking everywhere, breaking the prototype.

#### 💡 Recommendations:
- No recommendations at this moment.
-----
## Mission 4: Please take a look at the notifications below and click the notification that you think needs your attention the most.

I don’t know what was the issue, but Maze didn’t record all of the clicks. It tells that 7 users have clicked, but displays only 3 clicks.

#### 📝 Summary:
- It was not clear for the users which notification requires their action. 2 of them selected “Someone purchased your NFT” notification (buy now), 1 selected “You won the auction” notification.

#### 💡 Recommendations:
- We agreed on the meeting to go live with the current version of these screens, but I was wondering if we can get a “quick win” kind of thing there. I thought of a possible solution to add an icon with a tooltip for those most important notifications to drive user’s attention to them. When they user hover on it, they see more “generic” explanation, something along the lines of “You are going to lose this auction if you don’t react here” or “You have to accept that bid if you want to end the auction”. This way we don’t add much dev effort to implement this, but we also are not leaving that completely ignored. Thoughts, @dmitry, @klaudiusz (already discussed it with the design team so I’m not mentioning them here)?
![image.png](https://images.zenhubusercontent.com/61a0ab8bb8aa3136d7af1b10/184d4b97-6547-47cf-974c-09b4784dbc64)

**Comment by dmtrjsg** [comment]
@TCzechowski thank you for running the analysis

As discussed before let's go ahead with the simple notifications as per the current designs. And I am raising a follow up improvement to iterate on the single notification component (card).

Potential improvements:
1. Analyse all notifications and split into information and action required.
2. Consider iconography and colour coding to emphasise important parts
3. Consider adding CTAs to the notifications to increase readability when skim reading
4. Consider bringing notifications in the notiff centre closer with the action notifications snack bar component - it seems we have all of the ingredients there and I don't see why not re-use same pattern effectively.

Closing this task. The follow up ticket is [linked here. ](https://github.com/Joystream/atlas/issues/1946)
