### ISSUE TITLE
Notifications Improvements

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1946]
⚠️ DM: view all comments before scoping

Potential improvements for notifications epic: #1497 

To-do

1. Analyse all notifications and split into information only / action required.
2. Consider iconography and colour coding to emphasise important parts
3. Consider adding CTAs to the notifications to increase readability when skim reading
4. Consider bringing notifications in the notiff centre closer with the action notifications snack bar component - it seems we have all of the ingredients there and I don't see why not re-use same pattern effectively.

Based on Comments for Notifications:

Add types
Add icons per type
Add Filter by type and read/unread

__

ℹ️  Some work has been done on this already:

- #2087 

https://www.loom.com/share/d0867111546b42368cb82e04b96ebeb6

<img width="1107" alt="Screenshot 2022-03-15 at 12 37 04" src="https://user-images.githubusercontent.com/93924525/158379215-469c491f-df8d-40a7-85cb-d0ec8833d3ef.png">

**Comment by dmtrjsg** [comment]
Based on Comments for Notifications:

Add types
Add icons per type
Add Filter by type and read/unread

**Comment by dmtrjsg** [comment]
Layout (too much white space on the right)
Upd Bold handle vs Bold action  (see how its done for History)

<img width="875" alt="Screenshot 2022-04-27 at 12 06 48" src="https://user-images.githubusercontent.com/93924525/165506782-5d90eb2f-1921-4832-970c-4f3c967f9c57.png">

**Comment by toiletgranny** [comment]
Parking one more thing from @kdembler 
> hey guys, I’m implementing last two NFT notifications we’ve discussed: **Auction you have participated in has ended; Your auction has been settled**.
>
>Both of those create a problem in the context of our existing notification tile. The design assumes that all the notification will have some kind of actor, other member or yourself. However, for both of those new notifications, there isn’t really any actor. For the first one, we could present the winner if we wanted but I think this information isn’t really relevant to the user. For the second one, there isn’t anyone we can point to. I was thinking about just skipping the member name and displaying only notification text, for example: “Auction you participated in has ended” but we still have an avatar on the left that needs to present something. Do you guys have any idea for a short-term fix?
