### ISSUE TITLE
Onboarding tour

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#195]
1. Clone the repo
2. Run Atlas locally both in mocking (`yarn dev`) and production mode (`yarn dev:prod`)
3. Make some code changes, run linting `yarn lint` (our ESLint is integrated with Prettier)
4. Create your repo fork, open a test PR
5. Explore contents of `src/views`. Take a look at the rendered screens and see how the data is fetched using `Apollo Client`
6. Take a look at `src/mocking` (make sure to be in mocking dev mode) - this is where all the client-side mocking is done.
7. Change the mocking videos resolver to return something else (e.g. just one video) (`src/mocking/server/index.ts` may be a good place to start)
8. Browse some of the queries we use in `src/api/queries`
9. Take a peek at what's exported from `src/shared/theme/index.ts`. All the sizing, colors and typography are imported from here

**Comment by dmtrjsg** [comment]
This issue is outdated, at some point Readme.txt work by @kdembler will take care of this. #12
