### ISSUE TITLE
Cinematic View

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1959]
## Scope
- [ ] allow to enter cinematic view from player control and adjust video view
- [ ] persist the preference in `personalData` store

## Designs

🎨  [Link to Figma ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1350%3A94657)

## Comments

The idea iss not to hide NFT widget (with auction details) but just move it below video in cinematic mode, so when user scroll down he'll have NFT widget available and rest of recommended content.

**Comment by Lenorette** [comment]
Hey @dmtrjsg I've already had designs for cinematic view, but they were in [Design](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1211%3A96534) and [RWD](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1242%3A113099) pages in figma.

Also the idea was not to hide NFT widget (with auction details) but just move it below video in cinematic mode, so when user scroll down he'll have NFT widget available and rest of recommended content.  

Here I've made them also as user story, let me know if all is ok. 
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1350%3A94657

**Comment by dmtrjsg** [comment]
@Lenorette looks great!  Thanks for the update!

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1959?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
