### ISSUE TITLE
Video Page: Layout changes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1960]
**AC:**

- [ ] Update the description/license/title section
- [ ] Include CTAs at the bottom at the bottom of the page
- [ ] Placeholders for recommendations (#1961)

![Screenshot 2022-01-20 at 11.47.40.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/1bb3b32d-7682-4fbd-9a1c-2266cb03cf8a)

[Link to Figma >](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1288%3A146214)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/1960?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
