### ISSUE TITLE
Video NFT: Component - LInks to discovery categories

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#1962]
![Screenshot 2022-01-20 at 11.51.12.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/9190682d-c7f1-4ebc-8ffe-857efbe8c5e1)

:warning: Figma link TBC @Lenorette  pls share the link

**Comment by Lenorette** [comment]
Ok, so each one of those elements should move to different place of course:
- Popular on Joystream - https://play.joystream.org/popular
old figma file https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=9105%3A233873
- New & Noteworthy - https://play.joystream.org/new
old figma file https://www.figma.com/file/Vk2Z4QOiVa5bB6q3cBIG5J/Joystream-Atlas?node-id=9105%3A235186
- Discover videos - https://play.joystream.org/discover 
https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=1%3A26625
