### ISSUE TITLE
Idea: Generalise wallet/signer

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#1971]
# Background

Currently we only support Polkadotjs, but to me that seems like a relatively low-effort and semi-abandoned project, not-withstanding being the most popular Dapp signer in the Polkadot space. Perhaps more importantly, it only exists as a browser based extension, so it means our web app cannot be used from mobile, which is actually a very big problem, as it not only blocks all the interesting web3 stuff for consumers, but also possibly basic signup to accounts for basic personalization, if that is going to be powered by the same web3 authentication vs. password+email.

# Proposal

Do some research into how we can generalize support for other wallets or signers. It does seem like WalletConnect works with Polkadot, and  there is a vibrant wallet ecosystem, but I am not sure what the best way is to support them all in a way which is economical. There is also the question of trying to support wallets that unlock interoperability, which will be very valuable when Joystream is a parachain/thread.

_Edit: Here is an example of what happens if the app does not have multiwallet awareness https://twitter.com/bitfalls/status/1522227993229283328_

**Comment by kdembler** [comment]
YES! I was thinking about the exact same thing yesterday, thanks for putting this into writing. Are you sure about WalletConnect support for Polkadot? I did some research and haven't found anything, it seems both [WalletConnect is lackign support](https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/issues/21) and there are also no wallets that would support Polkadot and WalletConnect, we're still so early :((

But fully agreed on the need to support multiple ways of authentication and abstract this somehow. I think we could even build something similar to https://github.com/Web3Modal/web3modal, but just for Polkadot ecosystem. To start off, for use with Pioneer and Atlas, but this could very well become a popular library. We just need to actually find some usable wallets though. From my understanding at this point, it is exclusively `polkadot{.js}` with Talisman having extension in the alpha.

**Comment by bedeho** [comment]
> Are you sure about WalletConnect support for Polkadot

Says so on their website, they also advertise mulit-chain support, and there are issues about Polkadot support on their Github, but did not look in detail beyond this.

https://github.com/WalletConnect-Labs/walletconnect-v2-monorepo/projects/2#card-51217936

>  I think we could even build something similar to https://github.com/Web3Modal/web3modal

Oh awesome idea, we could probably get W3F grant support for that also, if needed, not sure how much effort it requires.

**Comment by kdembler** [comment]
> Oh awesome idea, we could probably get W3F grant support for that also, if needed, not sure how much effort it requires.

For real, sounds totally doable. I think the effort wouldn't be really that big, in Ethereum world, the extension is usually a full provider, it proxies all the API calls etc, here we would just create an abstraction for account management so I'm optimistic.

**Comment by bedeho** [comment]
For mobile I am seeing these two being quite popular in the Substrate space

- https://novawallet.io/
- https://mathwallet.org/en-us/

**Comment by kdembler** [comment]
Run a quick test of both:
- novawallet has only mobile app and doesn't support any dapp integration AFAICT
- mathwallet offers two separate apps:
  - browser extension, similar to the one we use currently - it does the job but I'd say it's not a big improvement over the current one
  - mobile wallet app that includes dapp browser, I managed to create a channel through it but it's quite buggy and the app crashed when I wanted to upload a video

All in all, I think those are quite in early stages as well, but if some users want to use them, they are free to, it works

**Comment by traumschule** [comment]
The [ledger research](https://github.com/Joystream/community-repo/tree/master/contributions/research/ledger-for-joystream#5-research-without-any-testing-required-if-any-other-hardware-wallet-manufacturer-supports-polkadotsubstrate-and-by-extension-joystream) mentions [cobo](https://cobo.com/wallet) (app) and [safepal](https://shop.safepal.io/products/safepal-hardware-wallet-s1-bitcoin-wallet) (hardware wallet) as DOT compatible.

**Comment by bedeho** [comment]
Adding another to the list: https://twitter.com/subwalletapp

**Comment by bedeho** [comment]
Adding another one to the list: https://twitter.com/FearlessWallet

**Comment by kdembler** [comment]
Just to share an update, I have an early access to the Talisman extension now, will try to do some MVP integration in the coming week. They have also built something similar to web3 modal that will let user pick which wallet to use, that will be included in the integration

**Comment by bedeho** [comment]
Is this one any good?

https://substrate.io/substrate-connect/

**Comment by kdembler** [comment]
Oh that's interesting, surprised we haven't run into that before. It seems this actually is a bit different, as it runs a light-client node in the browser, instead of connecting to a specific RPC endpoint, definitely worth exploring!

**Comment by mochet** [comment]
So I do a lot of research which I've finally developed a proper system (a database) for storing/retrieving and managing these. I come across lots and lots of random projects and wallets. 

This issue, combined with:
* https://github.com/Joystream/marketing/issues/202
* https://github.com/Joystream/marketing/issues/203

Are something I will address at significant scale. My database is going to contain 100+ wallets quite soon and I'll be trying to get the community involved in testing them and categorizing them.
I should be able to deliver an extensive list of those that work within the Polkadot Ecosystem at some point.

**Comment by bedeho** [comment]
> So I do a lot of research...

This is all useful stuff, but largely seems out of place for this issue?

**Comment by mochet** [comment]
> > So I do a lot of research...
> 
> This is all useful stuff, but largely seems out of place for this issue?

I saw examples of other wallets being shared here, so if I come across very promising ones I'll share them. Particularly those that can actually sign Polkadot transactions within the brower or through a smartphone app that Joystream's UI would surface (because some seem like they can hold DOT tokens and not sign transactions)

**Comment by dmtrjsg** [comment]
@mochet is the spreadsheet you are referring to here ready to be shared? Especially interested in your take on most popular wallets and ones that can work on mobile. Now that we've paved the way with Talisman and Subwallet, would be good to see if we need to extend the list further for better coverage.

**Comment by bedeho** [comment]
Done.
