### ISSUE TITLE
Snackbar improvements

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2005]
### Description

As discussed on our call, I would like the action button to be moved below the snackbar description.
![image](https://user-images.githubusercontent.com/22870059/151244994-4dacc717-6133-4cae-8c9a-3201a8741be6.png)

Thank you!

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4606%3A140876

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
Done! Designs and docs [can be found over here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=4606%3A140876).

![image](https://user-images.githubusercontent.com/35307309/151386495-088de0ce-8b67-4b07-8ee2-2f1b3493a188.png)

**Comment by drillprop** [comment]
Fixed in #2009
