### ISSUE TITLE
Fix video hero title display

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2013]
Our video hero has some issues that cause problems with display of title:
1. The implementation doesn't follow the design in terms of number of columns used for title section
2. Implementation has incorrect limit of 2 lines of text for the title. This should only apply to the video hero in "category" variant.

Figma: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=489%3A88635

For reference:
<img width="1056" alt="Screenshot 2022-01-27 at 14 56 58" src="https://user-images.githubusercontent.com/12646744/151372984-e208f18e-0a9c-4d98-996e-4252c4905786.png">

**Comment by rafalpawlow** [comment]
@kdembler Are you sure about 2nd point? As far as I can see, category video hero has 2 lines limit and a regular one does not have this limit.
![Zrzut ekranu 2022-02-2 o 19 29 10](https://user-images.githubusercontent.com/13706246/152215470-35809f06-4d06-47b0-8f1a-d1389d0bb68c.png)
