### ISSUE TITLE
Simplified transaction modal in snackbar

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#2025]
## Context
New, simplified designs for "transaction dialog/modal", most of it is now placed in snack bar notifications.

## Designs
🎨  [Figma Link ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1445%3A88618)

## Scope

**✅  Acceptance Criteria:**
Update transaction modal flow in signing all transactions inside the app for
- [ ] NFT auction use cases: that require update of blockchain (issue as NFT, Put on auction, make a bid, accept auction bid,  transact (buy now), settle auction)
- [ ] Studio use cases: publish/ update video

**⛔  Out of scope:**

- [ ] Transaction modals on creating new membership (that happen outside of the regular views)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2025?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow

**Comment by dmtrjsg** [comment]
Looks like an old issue.. is there anything worth carving out and raising as a separate issue or just closing it, @toiletgranny ?

**Comment by toiletgranny** [comment]
I believe it can be closed, @dmtrjsg.
