### ISSUE TITLE
Fix text wrapping in the number of views in the Video tile component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2030]
There should be a non-breaking space between the number of views and the word "views" in the Video tile component. Currently, there's not. Can we have it? 🙏 

![image](https://user-images.githubusercontent.com/35307309/151567079-511d3963-cdf0-4a1d-890d-31b142876ea7.png)

**Comment by kdembler** [comment]
Thanks for creating an issue, this slipped my mind!
