### ISSUE TITLE
Rework and lay out clear foundation for section components in Atlas (Section Components UX)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2031]
### Description

 As we've found out with @kdembler while working on https://github.com/Joystream/atlas/issues/1595, the current state of designs and the implementation of section components in Atlas not only does not match but is also in desperate need of updating and cleaning up on both sides.

 As sections are such a vital element of each Atlas viewer experience page, we want to unpack the current state of all related components, find out what are the current needs for their usage and how we can address all of them through a new, simple and intuitive system of "lego blocks".

 We believe that having clear guidelines and foundations for the above will unlock a faster design & implementation process in the future, fewer questions and doubts along the way, and easy, straightforward customization of potential forks of Atlas in the future.

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=110%3A1118

### How urgent this is?

Not a blocker, but still worth considering

## Scope
- [ ] Review sections components as per description
- [ ] Review this comment and take a view on incorporating [this observation](https://github.com/Joystream/atlas/issues/1226) here

**Comment by toiletgranny** [comment]
Note to self: leave a Figma designs link

**Comment by dmtrjsg** [comment]
Adding a link to description, which seems relevant to this issue: 
- https://github.com/Joystream/atlas/issues/1226

**Comment by toiletgranny** [comment]
The task can be now reviewed and  implemented based on designs, docs, and changelog which [can be found in Figma:
- [Section header component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=11419%3A264823&t=2dft7MafWPz3V72s-4),
- [Section footer component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=11422%3A212457&t=2dft7MafWPz3V72s-4),
- [Section content component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=11422%3A217988&t=2dft7MafWPz3V72s-4),
- [Section component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=11419%3A246478&t=2dft7MafWPz3V72s-4),

![image](https://user-images.githubusercontent.com/35307309/216837026-ba5b6270-2fa3-4fec-9dd4-8d0bf546a444.png)

Please note that the above work is missing a new component for the [Channel preview](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A27094&t=2dft7MafWPz3V72s-4), which was planned to be included in the scope of this ticket initially. We agreed with @KubaMikolajczyk that he'll pick this up at a later stage once he gets a chance to work on a page that uses this component.
