### ISSUE TITLE
Playlist - Content viewer: Lo-fi mockups

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2035]
Provide Figma walkthrough on lo-fi mockups covering the playlists feature.

**Comment by dmtrjsg** [comment]
Video:
https://www.loom.com/share/bd33024894e5460faa9c01b3ef23136c

Figma:
[https://www.figma.com/file/Ww4DdpJZTdIX6qysnTtcuS/Playlists:-Viewer?node-id=639:82982](https://www.figma.com/file/Ww4DdpJZTdIX6qysnTtcuS/Playlists%3A-Viewer?node-id=639%3A82982)
