### ISSUE TITLE
Create an icon for issuing an NFT

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2049]
### Description

The goal of this task is to create a new icon for indicating the process of issuing an NFT, so that it can be later replaced with the currently used icon (a trolley icon made for minting an NFT).

![image](https://user-images.githubusercontent.com/35307309/151977369-0ad9445b-efd2-419e-9e45-089e42a694ef.png)

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3630%3A116415

### How urgent this is?

Not a blocker, but still worth considering

**Comment by TCzechowski** [comment]
Left: After
Right: Before

![image](https://user-images.githubusercontent.com/22870059/152945412-cf45a1e4-b9e5-4a00-a855-c403045e968f.png)

**Comment by dmtrjsg** [comment]
Retrospectively: maybe we can test this very quickly as in ABC with a quick discord post. Like with emoji :one: :two: or :repeat: if smth else seems to be more intuitive for creating an NFT from the publishers' perspective. wdyt? @toiletgranny @TCzechowski

**Comment by TCzechowski** [comment]
The "baby trolley" icon won with 5 votes on discord (vs 3 votes for shopping cart), and most of us also preferred the trolley on our meeting, so we will use the "Baby trolley" icon for minting NFT.

This task will be done together with #2247.
