### ISSUE TITLE
Idea: Kill switch

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2052]
**Is your feature request related to a problem? Please describe.**

Right now, the content moderation on-chain is not yet very mature socially and tooling wise, and Orion yet has no server side-screening for the operator, at the same time we allow publishing content freely, and this content can easily end up getting automatically surfaced in various areas of Atlas. This is not ideal w.r.t. the risk of abusive or inappropriate content being published.

**Describe the solution you'd like**

At least as a stopgap remedy right now, allow a trusted set of actors - who collectively will have reasonably high availability, to unilaterally be able to stop Atlas from working, in the sense that is serves any pages. As this kill switch feature has relatively low negative impact when abused, we should start out with the simplest possible solution which does not require authentication, logging or alerts. Some sort of confirmation interaction or something would be useful to prevent fat-finger mistakes.

**Comment by kdembler** [comment]
One quick idea that would be easy to implement:

In Vercel we add environment variable that enables some kind of maintenance mode. If a build is triggered with it, the App will render a maintenance screen, something like this:
<img width="400" alt="Screenshot 2022-01-26 at 13 06 42" src="https://user-images.githubusercontent.com/12646744/151991326-794ba5a7-ae15-4d1e-9491-8728f57523de.png">

**Steps required to kill Atlas:**
1. Change env variable in Vercel
2. Re-run build
3. Wait for it to finish (~3min)

**Who would be able to do this:**
Anyone who has necessary permissions in Vercel. At the moment that's Martin, Mokhtar and me.

--- 

What do you think, would that work? I think anything outside of Vercel and build process will be quite more complex to implement

**Comment by bedeho** [comment]
> Anyone who has necessary permissions in Vercel. At the moment that's Martin, Mokhtar and me.

This sounds like a level of access where someone can mess up stuff quite a lot, is that not right? Is there some way to contain that so we can open it up to a much greater number of people?

**Comment by kdembler** [comment]
Ah, I didn't understand that you meant this many people as "trusted set of actors". In that case, it gets tricky. You've mentioned that the initial solution shouldn't require authentication, so we are fine with random people being able to stop Atlas?

**Comment by bedeho** [comment]
Not random, say people we trust wont abuse it, but we cant risk their opsec and other issues is robust enough that they have the ability to do whatever they want.

**Comment by kdembler** [comment]
Ofc, people we trust won't abuse it but if we say there's no authentication, then anyone on the internet would have access to this kill switch, not just people we trust, right?

**Comment by dmtrjsg** [comment]
covered in 
- https://github.com/Joystream/atlas/issues/3001
