### ISSUE TITLE
Rework form components in Atlas (inputs, selects, textareas etc.)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2056]
### Description

The current set of form components in Atlas, while addressing basic needs, suffers from inconsistencies between designs and implementation, lack of technical documentation, or guidelines on the usage.

As a result, as the Atlas design & engineering team grows, inconsistencies (eg. select components used for sorting) in the form components usage start to emerge, each one taking time and effort on making, discussing, and maintaining. As the new app views are created, these issues are expected to get deeper and thus more difficult to address later on.

As with #2053, revisiting, updating, and documenting form components creates an opportunity to bring in more **accessibility**, clarity, consistency, and ease of use to our design system, increase the speed of design iterations, and cut down the implementation time (while improving the accuracy) in the future.

The proposed scope of this task is to review, adjust, update and document the following components:
1. Text fields/Inputs,
2. Textareas,
3. Selects (https://github.com/Joystream/atlas/pull/1988), 
4. Checkboxes, Radio buttons, Switches,
5. How forms are validated globally,

### How urgent this is?

Not a blocker, but still worth considering

**Comment by toiletgranny** [comment]
I'm super thrilled to be finally passing this issue over to you, @kdembler! Of course, this is only the beginning of the implementation journey for this, I realize. I'm sure that despite having talked it through multiple times together, there still will be questions and ideas during the process (and I'm already looking forward to the ones we'll decide to turn into actionable items!). 

But despite it all, I believe this is still an important milestone for something we have all been willing to do for quite some time now. Sleeker, more consistent, and more accessible forms are coming to Atlas and I can't wait to see how it plays out in the wild! Thank you @KubaMikolajczyk and @TCzechowski for all your help with this! 

Ok, enough bull*hit. Let's get down to business. 😆  The outcome of this task is (open for discussion!):
1. A series of component changes. Some are more light-weighted (like checkboxes, or switches), and some are a bit heavier (like inputs or selects). I created a separate GitHub issue for each new or changed component that was affected by this. I linked them as blockers to this one, but I'm also listing them all out below.
   - [(Re)create the Form field component](https://github.com/joystream/atlas/issues/2715)
    - [Update the Checkbox component](https://github.com/joystream/atlas/issues/2711)
    - [Update the Input (formerly: Text field) component](https://github.com/joystream/atlas/issues/2707)
    - [Update the Option card component](https://github.com/joystream/atlas/issues/2713)
    - [Update the Radio button component](https://github.com/joystream/atlas/issues/2710)
    - [Update the Select component](https://github.com/joystream/atlas/issues/2708)
    - [Update the Switch component](https://github.com/joystream/atlas/issues/2712)
    - [Update the Textarea component](https://github.com/joystream/atlas/issues/2709)

2. A whole lot of new design & engineering documentation, and — more importantly — content & usage guidelines. Each component comes with its own piece of reading, but now there's also a whole separate frame in Figma talking solely about a high-level approach to the form design in Atlas. This includes subjects such as different kinds of form validation, prepopulating form fields whenever possible, providing guidance on prerequisites for successful field validation, smart defaults, etc. All of that can be found here [[LINK TO FIGMA]](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7505%3A150243), and I'd encourage every developer working on updates for form components to familiarize themselves with this and get a better perspective on the anticipated usage of their work later on in the wild. Naturally, we'll be adding more here in the future, but it's a decent starting point, I think.
![image](https://user-images.githubusercontent.com/35307309/168825431-9cc65508-d008-45b8-a5de-87acab357275.png)

Looking forward to hearing your thoughts on this once this goes into development. 

cc @dmtrjsg

**Comment by dmtrjsg** [comment]
@toiletgranny thank you for turning around this tremendous piece of work! 💪

**Comment by kdembler** [comment]
@dmtrjsg @toiletgranny Since we have this broken down into specific tickets and already in progress, should we close this umbrella issue?
