### ISSUE TITLE
Review - unified sign in flow

### ISSUE THREAD

**Issue by Lenorette** [Joystream/atlas#2067]
### Logic (@toiletgranny)

1. **[(0:00 – 1:39)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Polkadot account with JS membership not picked up instantly after being added in the extension**
   - **AS IS:** When I click on the "Sign in" button add then a Polkadot account with a JS membership associated with it in the extension, nothing happens in the app. I neec to close our internal Polkadot modal and click on the "Sign in" button again to have access to my membership.
   - **TO BE:** Ideally, our internal Polkadot modal is closed instantly, and the membership is available in the app the moment I add it to the Polkadot extension.
2. **[(1:40 – 2:10)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) The "Sign in" button not working when I remove/hide my Polkadot accounts in the extension**
   - **AS IS:** When I remove/hide _all_ my Polkadot accounts with a JS membership associated with them, the avatar in the Top navigation goes back to the "Sign in" button (cool!), but it doesn't do anything.
   - **TO BE:** The "Sign in" button brings up our internal Polkadot modal.
3. **[(2:10 – 2:52)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Membership dropdown remains open even after I remove/hide all of my Polkadot accounts**
   - **AS IS:** When I open up the Membership dropdown, having one or more Polkadot accounts with JS membership associated with them, and then remove/hide these accounts in the extension, the dropdown remains open but is empty.
   - **TO BE:**  Ideally, the membership dropdown either closes the moment I add/remove (hide/unhide) Polkadot accounts with JS membership associated with them in the extension, or it closes when there are no more active Polkadot accounts with JS memberships.
4. **[(2:52 – 3:23)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Membership dropdown preserving its state upon closing and reopening**
   - **AS IS:** When I open up the Membership dropdown and go into "Switch member" and close it, upon reopening I'm landing on that "Switch member" state.
   - **TO BE:**  Ideally, I always land on the initial, default state of the Membership dropdown each time I open it.
 5. **[(3:23 – 4:06)](https://www.loom.com/share/f3a6c18670b44e1bb967d269323640b7) Switching between viewer/studio is not consistent if I have memberships with channels and without them**
    - **AS IS:** When I go into Studio while browsing with a Membership without a channel, I'm landing on the channel creation page — fantastic. But then, if I switch my membership to a one with a channel, I land on my channel editing page, instead of on the initial Studio view, which is currently "My videos".
    - **TO BE:**  Ideally, in this case, the app redirects me to the "My videos" page.

### Visual differences (@Lenorette)

Divider should not appear there when there is no more content below. It should only appear when member has some channels.
<img src="https://images.zenhubusercontent.com/619f51dafb271d01d95753ed/ef1955e3-bde0-4739-8c60-ee27d6c7e677" width="700">

When I hover over the avatar I can see hover state, it should not appear there.
Or if we want to leave it there when I click on the avatar, Membership edit page should open up with Avatar input active.
<img src="https://images.zenhubusercontent.com/619f51dafb271d01d95753ed/f77b7e08-d593-404a-85c0-872d04320cbd" width="700">

Distance between snackbar and bottom of the page is way to big, it should be 16px.
<img src="https://images.zenhubusercontent.com/619f51dafb271d01d95753ed/56ccb924-2b02-44e9-aa45-48dee29810ac" width="700">

On hover, maybe it would be better to change copy to: "Copy Polkadot address"
<img src="https://images.zenhubusercontent.com/619f51dafb271d01d95753ed/3bf7e9c3-7041-4e6f-a5b3-4cff48b8bd69" width="400">

**Comment by kdembler** [comment]
Great points! @drillprop can you jump on those right away?

**Comment by toiletgranny** [comment]
@kdembler I just added a few comments from my side. I also recorded a Loom video in case that's easier for you to recreate the steps.

**Comment by kdembler** [comment]
Very thorough review Adam. Addressing those points:

1. This is really an edge case, I think the number of users who go through this flow of having an account with a membership hidden and enabling it will be super low. I'm happy to do create an issue for this but let's not block the release
2. Very similar to point above, I would say not a blocker as well
3. Same as above but even lower priority
4. Agreed, let's fix this before the release
5. I think there are some other implications here. There is a general rule - when you switch membership/channel, you stay on the same view as you were before. So if I go to channel edit and switch the membership, we want to stay in the same view, right? I don't think this specific case is worth introducing an additional rule for. WDYT?

**Comment by toiletgranny** [comment]
1. Just to add a little bit of context here: at this point I didn't try to break anything on purpose just yet (as I did with the other things), it's just something I would intuitively do if I had a clean set up and an already existing Polkadot account with JS membership. So I would simply advise reconsidering if it's indeed an edge case. Also, on the "hiding/unhiding", it's the very same operation as simply adding/importing or removing Polkadot accounts from the extension, I believe. I used this approach in the video only because it was quicker and didn't require me to provide the mnemonic seed required for importing an account.
2. This seemed like an easy fix to me, but sure! 
3. Of course.
4. Great!
5. `So if I go to channel edit and switch the membership, we want to stay in the same view, right?` In the viewer — yes, absolutely. But Studio? I'm not so sure. That's certainly not what I come to expect from using eg. YouTube Studio with multiple channels. Over there, switching the channel always brings me back to the first view. See the video below. You know me and that I'm also not a fan of creating exceptions or introducing unnecessary rules; I'd just go ahead and say that my recommendation would be to change that general rule altogether. WDYT?
https://user-images.githubusercontent.com/35307309/152531269-c69198de-09c0-4526-b15d-2c4fe40547c4.mp4

**Comment by kdembler** [comment]
`1.` I get your point but I would say that importing an account that already has a membership as part of this flow is an edge case. If user has a membership, I guess it's like 99% chance they already have it in their extension. We do a lot of account management as app testers but usually users just have a single account that stays there or just create a fresh account.

`5.` Hmm, all right. I guess we can navigate to my videos when you switch member/channel. @drillprop

**Comment by drillprop** [comment]
@toiletgranny 
2. I'm referring to the issue which you described between 1:56 to 2:10 of your video. I did some testing and please let me know if I'm wrong. if you actually forget/remove the account(not hide - this is important) everything works well. Also when you add the account, the new account should show up in the dialog correctly. I would consider using this `visibility button` as some really rare edge case. Nevertheless, I'll try to fix this, just want to clarify this.

**Comment by drillprop** [comment]
Closing in favor of #2070
