### ISSUE TITLE
Sort categories based on the number of videos in the Discover page

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2080]
An idea that was missed when documenting [final designs](https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=1%3A26590) for the [Discover page](https://play.joystream.org/discover) was that Video category tiles ought to be sorted based on the number of videos in categories. 

For this reason, the goal of this task is to have this sorting applied in the implementation.

**Comment by dmtrjsg** [comment]
@toiletgranny from my perspective it would be better to show a counter of videos but keep the order intact so that users don't need to "hunt" for it on the page and favourite categories are easier to find.

**Comment by toiletgranny** [comment]
@dmtrjsg That's a fair point, but it doesn't solve the problem of having potentially unpopular categories listed at the top, which doesn't contribute to increasing content discoverability.

How about rearranging categories based on their video count _right now?_ As a one-time operation? This way, Science & Technology (1365) would be first, People & Blogs (878) would be second, while Nonprofits & Activism (48) would be... last (that's sad). https://play.joystream.org/discover

It may be worth revisiting and doing the excercise again, a few months after hitting the mainnet, as I imagine the currently uploaded content might not reflect what will end up being uploaded on the platform when it gains more popularity.
