### ISSUE TITLE
[USERSNAP] Catching an error during video uploading

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2084]
**Taken at**: https://play.joystream.org/studio/uploads
**Fields**:
- Expected Result: Catching an error during video uploading
- Houston, we have a problem.: Cant upload video

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/78e25f28-ad68-4e05-ba06-8c17c1f92ed7-annotated_eafe7020-1fbb-4e58-8bfe-f2892e1654e9.png?etag=f4c046152d03ef3c1bababa1a1f28a43)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/78e25f28-ad68-4e05-ba06-8c17c1f92ed7-annotated_eafe7020-1fbb-4e58-8bfe-f2892e1654e9.png?etag=f4c046152d03ef3c1bababa1a1f28a43)*

**Browser**: Chrome 89 (macOS Mojave)
**Screen size**: 1280x1024
**Browser size**: 1680x560
**Labels**: Bug
**[Open #10 in Usersnap](https://app.usersnap.com/l/feedback/8337249c-78e7-422f-aa85-b4374662d443?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Raised this to capture storage provider switch.

**Comment by kdembler** [comment]
This was caused by issues on the storage providers side, AFAICT everything on Atlas side worked properly so I would close this @dmtrjsg

**Comment by dmtrjsg** [comment]
Sure thing, I noticed it got reported in Usersnap before we started discussing it in RC. Closing, thankyou!
