### ISSUE TITLE
Prepare Issue NFT quick prototype for Marketing Tweet/ Short Video

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2090]
## Context

@mrexpat  (Robert) is working on the marketing materials supporting NFTs release. He needs  a quick 10 second video covering the Issue NFT flow (latest version).  We need to avoid having a real youtube channel to avoid any potential claims on copyright in the future.

## To-do

1. Take [this as a starting point](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=405%3A5330). Update the channel name, member name and anything that points to SChism to an imaginary/ mock names and imagery.
2. Create a FIgma clickable prototype (happy path) for the most recent NFT issue flow
3. Send the prototype link to robert@jsgenesis.com

**Comment by KubaMikolajczyk** [comment]
Loom prototype overview: https://www.loom.com/share/8dcfe24ee9f24d59a89fe060f878511d?sharedAppSource=team_library
Link to prototype: https://www.figma.com/proto/xm6vBdSnQDroc57rGfGtPM/Video-workspace?page-id=1600%3A94337&node-id=1601%3A104231&viewport=365%2C48%2C0.52&scaling=min-zoom&starting-point-node-id=1601%3A104231
