### ISSUE TITLE
Verified status of channels

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2091]
Pretty simple filler idea, should have rather limited product design implication, and can be implemented as metaprotocol where curators can set & unset this status.

**Comment by kdembler** [comment]
Lovely 😍

**Comment by dmtrjsg** [comment]
@bedeho would a proposal mechanism be used for it or a simpler CLI record for a user with the curator role? Is this already defined for runtime?

**Comment by bedeho** [comment]
This would not be a proposal, its something any curator could do, and yes, doing it through the CLI is totally fine. This will require doing some metaprotocol work, because the concept of being verified is meta. I'm sure @zeeshanakram3 could do this whole thing in like 10s ;)

**Comment by dmtrjsg** [comment]
superceded by 
-  https://github.com/Joystream/atlas/issues/3840
