### ISSUE TITLE
Improve mobile video experience

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#210]
Right now when you use the mobile version of the app, you cannot pause or play video on tap. You have to touch a small play/pause button on a video. 

I think the desired result would be to mimic how it's done on youtube: 
1. User taps on the screen first time - overlay with pause icon will show up(it should be visible for at least 2-3 seconds).
2. User taps on the screen a second time - if the overlay with pause icon is still visible video pauses, overlay with a play icon will show up. 
3. User taps the third time - video unpauses, overlay disappear.

**Comment by kdembler** [comment]
Also:
- scrolling the video is pretty hard, you cannot actually press and hold the progress marker
- it's impossible to change the volume - you can only tap the icon to mute
