### ISSUE TITLE
Create logic for converting tJOYs to $

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2105]
We will need to know price of tJOY expressed in $, for example to display NFT prices, like here: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1350%3A99607

We can get this info from the status server, which currently exposes only a single endpoint available at `https://status.joystream.org/status`. It returns a JSON with a `price` field. Separate endpoint for just price is being added but for now let's use `/status`.

**Comment by eldiegod** [comment]
What do we need to do here @kdembler ?

**Comment by kdembler** [comment]
To start with, we can run a request to `https://status.joystream.org/status`, this returns a big JSON with `price` field. We could have some provider/manager that fetches this on startup and this could later be used to convert tJOYs to dollars. The JSON is quite heavy unfortunately, will see if we could add some dedicated price endpoitn

**Comment by eldiegod** [comment]
Probably should run the fetch on an interval basis as this could change rapidly no?

Dedicated endpoint would be ideal

**Comment by kdembler** [comment]
I'm not so sure about rapid changes, at least as long as we're on testnet. There is no market to trade `tJOYs`, the value is dependent on the USD backing by jsgenesis, which I think changes infrequently, basically when withdrawals are done or the backing is replenished. On mainnet we will probably need separate source of that data anyway. If we manage to get sepearate endpoint, some interval fetch would be ideal, for now I think we can just fetch once to not burden the network too much

**Comment by eldiegod** [comment]
I think @lcoenengithub is working on this no? we should update assignee here

**Comment by kdembler** [comment]
You are correct
