### ISSUE TITLE
Moderated usability test — Comments & reactions

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2119]
# What do we want to test
1. Validate (or invalidate) that the amount and/or form of communication in the UI around comments being stored on the blockchain is enough for participants to be able to add comments without disturbance.
   - We need this to be verified with both web3 experienced participants as well as users that are totally new to this world to see how their reactions might differ.
2. Validate (or invalidate) the same thing ☝️ but for reactions underneath comments.
   - Validate (or invalidate) that participants understand how reactions can be added or revoked, including a scenario in which a particular reaction is already present under a comment, but participants are asked to add it from the reactions popover menu.
3. Validate (or invalidate) that participants understand how many levels of threads they can create when replying to comments.
4. Gather insights on their preferences regarding having a limited vs an unlimited set of reactions under comments,
5. Capture participants' thoughts on how often do they see themselves using reactions for comments in the currently presented form.

# How do we want to test it
Using moderated usability tests followed by informal discussion and a few focus group-style questions.

# How will we measure the results
- For 1-3: By measuring the success rate of specific tasks and noting down all their thoughts and pain points along the way,
- For 4: By showing alternative options for reactions (limited vs unlimited) and asking about (a) which one do participants see themselves using more often, but also (b) which one is easier for them to at-a-glance see how do people feel about certain comments.
- For 5: By asking about participants' subjective anticipated frequency of usage of commenting and comments reaction features in Atlas, in comparison to their current frequency of usage of similar features in other social media platforms they're active on.

# Example questions
- Using the prototype, can I ask you to add a new comment? Can I ask you to reply to this comment?
- Did you notice this piece of information about comments being stored on the blockchain? How did that make you feel?
- Based on what you've seen so far, how often would you see yourself commenting videos on Joystream compared to how often you comment videos on YouTube right now: less often, the same, or more often? Why?
   - OR: Imagine YouTube introduces reactions to comments in the same way you just saw it in this prototype. How would that affect how often you react to other people's comments: less often, the same, or more often? Why?

# Test details
Time: Thursday-Friday, 17-18 Feb 2022

@dmtrjsg

**Comment by dmtrjsg** [comment]
Amazing, thank you for preparing this @toiletgranny  based on all comments from today, perhaps worth throwing in these extra points: 
- the best way to show users (multiple) own comments after posting and otherwise
- explore single/ vs multiple thread levels situation (let's discuss tomorrow if its worth restricting to X levels based on real estate)

May help us to shoot a  quick-fire Maze asking users "if you only had 5 emojis to pick, which would you chose? Same question for 10 and 25? (numbers are arbitrary)

**Comment by toiletgranny** [comment]
# Summary

## About the test
1. Testing scenarios, tasks, questions, Figma prototype, and video recordings [can be found in Notion](https://www.notion.so/Comments-reactions-b5559e48e20f4ec6b876b412a770b599).
2. Notes from individual sessions (courtesy of @KubaMikolajczyk) [can be found here](https://www.notion.so/76c35eae4b3c4039aa9966709f78a400?v=4dfb57ffeb034be1bd1118f8caa54d75&p=b5559e48e20f4ec6b876b412a770b599).
3. We conducted moderated usability tests with 4 participants:
   1. A person who ✅ **is** familiar with the platform but has 🚫 **little to no understanding** of the concepts behind web3,
   2.  A person who 🚫 **is not** familiar with the platform and has 🚫 **little to no understanding** of the concepts behind web3,
   3. A person who ✅ **is** familiar with the platform and has a ✅ **very good understanding** of the concepts behind web3,
   4. A person who 🚫 **is not** familiar with the platform but has a ✅ **very good understanding** of the concepts behind web3.


## Testers to be paid
:bulb: Testers to be paid out [are now also listed in Notion](https://www.notion.so/76c35eae4b3c4039aa9966709f78a400?v=26b794a11a0f4797bf81d4baf90ecea8) with a quick option to change their status and mark them as "Paid out".
1. 13mfkDMnUQe3ZAr7LJRjKSvNmy6Cco2ocVFgCaz4MSu5s2BM
2. 5HMoR3CWHAtS52SjpTFNR5u7nJbYTKaGcBDeNJ431RYDzNAW
3. 5CaDmoBUtV2ebxiFY3YVaK1k2k8bo9wcxGVTjKPhBSxXLuoH

## Key findings
1. **Deleting/editing comments:** Half of the participants said that the lack of editing or deleting options in comments would increase their hesitation about leaving comments on Joystream.
   - While no task nor question in the test scenario revolved around concepts of editing or deleting comments, this topic has emerged naturally during the course of the conversation in 2 out of 4 sessions.
   - Concerns around deleting/editing appeared always after posting a first comment or two.
   - 3 participants said they would not expect to be able to edit/delete comments once they realized comments are stored on the chain, however, they would be still instinctively looking for such options in the UI.
2. **Posting a comment:** 3 out of 4 participants did not expect comments nor reactions to be stored on-chain. [[21:34-22:53]](https://drive.google.com/file/d/1q8XFBNmBMarjIOfeWaJJuV4yxB4G7_ux/view)
   - One participant (claiming to be rather unfamiliar with web3 concepts) found it unnecessary while another one (web3 expert) said **it's exciting and saw it as an advantage.**
   - After posting a comment, for one participant (unfamiliar with web3 concepts) it still came as a surprise that reactions are also being stored on-chain. For others, it felt rather natural once they realized that comments are.
   - The only participant who seemed to be totally unsurprised about the fact was the one that was both familiar with web3 as well as had his own channel on Joystream.
3. **Reactions:** 🎉 None of the participants had issues with figuring out how the reaction system works:
   - While the rather unfamiliar with web3 part of participants did not expect the reactions to be stored on-chain (worth noting: that was _after_ posting comments and discovering that they're stored on the blockchain), the ones who consider themselves web3 experts found nothing surprising about that and said that the heads up was unnecessary at that moment.
   - One participant, unfamiliar with web3, said she finds it unnecessary for reactions to be stored on-chain.
   - Half of the participants agreed that they would see themselves being more encouraged towards reacting under comments if the number of reactions was unlimited (as opposed to having preselected reactions).
   - At the same time, all participants agreed that it's easier to at-a-glance see the breakdown of reactions with the preselected reactions option.
4. **Replies & threads:** 🎉 None of the participants had issues with finding out how to reply to someone else's comment.
    - All participants found it intuitive that a reply to a comment in the main thread is displayed at the bottom of other replies to that same comment.
    - However, half of the participants did not expect to see their reply to another reply to land on the same thread level, rather they anticipated a new sub-thread is going to be created. [[32:33-33:00]](https://drive.google.com/file/d/1q8XFBNmBMarjIOfeWaJJuV4yxB4G7_ux/view)
5. **Sorting:** Half of the participants initially had minor problems understanding how comments are sorted and where this can be changed.
   - At first, some said it appears to be random, but after a short while they assumed it was based on how many reactions a comment had received.
   - Once discovered sorting by "Most popular", all participants instinctively assumed that this is being driven purely by the number of reactions a comment received. No participant mentioned anything about certain reactions being potentially used to downvote a comment.
   - Once the participants found the sorting dropdown in the prototype, they had no trouble using and understanding how it works.
   - When asked where would they expect their comment to appear after posting, 3 participants said at the top, while one assumed it would most likely go all the way to the bottom of the page.
6. **Summary:** Based on the prototype:
   - 1 participant said he would see himself commenting on videos in Atlas more often than on YouTube or other social media platforms (purely because of the fact the comments are stored on the blockchain). 3 said it would be the same. None said it would be less often.
   - 1 participant said she would see herself leaving reactions under comments on YouTube more often if they were to adopt the limited reactions system showcased in the prototype. 2 said it would be the same. None said it would be less often. One participant refused to answer.

## Recommendations
@dmtrjsg 
1. Restrict the communication in the UI around comments & reactions being stored on the blockchain to display a one-time-only popover appearing upon the user's first interaction with likes/dislikes, comments, or comments reactions (whichever comes first).
2. Include comments deletion in the scope of the current epic.
   - As a future step, address comments editing and all its implications.
3. By default, have the user's posted comments always positioned on top, with the comments being posted as replies being the only ones visible in the threads without clicking on "Show X replies". Have this functionality being an option that can be disabled in the sorting dropdown.
4. Reconsider the positioning of the sorting dropdown to make it more visible.
5. Conduct a follow-up Maze test on comments reactions in order to:
   - mitigate the risk of moderated test results being affected by the way two alternative options were presented in the Figma prototype,
   - gather quantitative data on the community's preferences on the limited vs unlimited comments reactions,
   - and to help us pick the final set of reactions to be used for the commenting system (if we proceed with the preselected option).

**Comment by dmtrjsg** [comment]
Agreed to:
1. Show same modal once with copy covering comments, reactions.
2. Deleting and editing comments with keeping track record is a part of this epic
3. Agreed to keep own comments on top independent from sorting options
4. Maybe try "Sort by.." label. I don't recall what we agreed on, but pls feel free to consider alternatives in the happy pass rec
5. 🚀 👾👾👾

**Comment by toiletgranny** [comment]
# Summary of the follow-up Maze test

## About the test
1. We conducted an unmoderated Maze test/survey. At first, participants were tasked to add a reaction to comment twice:
   - In the first prototype, there was a limited set of reactions to choose from,
   - In the second prototype, there was an unlimited set of reactions to choose from.
2. There was no screener conducted this time, everyone was welcome to take part.
3. We had 15 responses in total.
4. Full test results [can be found in Maze](https://app.maze.co/projects/76778380/mazes/76867047/results/).

## Testers to be paid
_Sorted by the response date (earliest at the top), invalid wallet addresses are filtered out._
1. 5GuMJVvcq4Vfwt1gXFQGq9pafeRn29eya2s9e9EZJCd2PMRn
2. 5FWjkKfRMLMUxR76beCjBgWgh9fGRiUd1NSupHisjxaAcGyc
3. 5CaDmoBUtV2ebxiFY3YVaK1k2k8bo9wcxGVTjKPhBSxXLuoH
4. 5DrGQQ8ZJoZpCDJKKf8cW6y6AAi5rekN2mUNCDtAL1xvhMi3
5. 5Ew4nS5PMCYhoww3MzM23NXs8BevsanRQ8zdLkbSyijKvNX5
6. 5EkQqSa9yzSf4MbYiVocuNuSaspeMf3Nmt4TAoUHD4ANJqz4
7. 5EFYsQoRdXZnpNN6RLouysEgewjpYjjUicowuv8EQbiWSHUW
8. 5Enf3akTGyZ7Nsu7usJ5LoVuWExHvEbVBDB8jiGXHk6fSimU
9. 5CPP6tXt9BkBwHpoYEod4p9a31uiLf9w27Xh2Mmek8TwvG2K
10. 5HMoR3CWHAtS52SjpTFNR5u7nJbYTKaGcBDeNJ431RYDzNAW

## Key findings
1. **Question: Which option gives you a better understanding of the reactions behind each comment?**
![image](https://user-images.githubusercontent.com/35307309/155987622-d58a158d-8f2a-4318-a78b-7f2a819e01c4.png)
   - Option A with preselected emojis — **80%**,
   - Option B with an unlimited emojis selection — **20%**.
11. **Question: Which option would you use more often when reacting to comments?**
![image](https://user-images.githubusercontent.com/35307309/155987646-017030ae-aaaa-4878-88c4-01a4634b7720.png)
   - Option A with preselected emojis — **71%**,
   - Option B with an unlimited emojis selection — **29%**.
12. **Question: If you were to pick 5 emojis to be used as comments reactions, which one would you choose? Answer with emojis.**
   - ❤️ = 10,
   - 👍 = 10,
   - 👎,😂 = 4,
   - ✅,😡,👌,👏,🎉,🤮 = 2.
13. **Question: If you were to pick one set of reactions, which one would be the most encouraging for you to use?**
![image](https://user-images.githubusercontent.com/35307309/155987016-99a34f44-6fe5-4df7-a3c3-dedcd8730632.png)
   - Option B — **46%** _(Joystream initial set of reactions: amusement, love, laugh, shock, anger)_,
   - Option C — **23%** _(Parrot emotional framework: love, joy, surprise, anger, sadness, fear)_,
   - Option D — **23%** _(Facebook reactions: like, love, ~~care~~, haha, wow, sadness, anger)_,
   - Option A  — **8%** _(Plutchik emotional framework: anger, surprise, disgust, enjoyment, fear, and sadness)_
14. **Question: Open mic, feel free to write whatever you want!**
   - "I usually like to have some presets emojis cause it's faster to react but if I would be able to customize it/have access to all when needed could be nice :)"
   - "Is it overkill? Maybe like and dislike will be enouth to start?"
   - "I definitely feel option B, with the full selection of emojis is what most people look for when using emojis. The more options, the better, in my opinion. I love the idea of adding hearts and different reactions to the videos themself. "
   - "very happy to add such features, I had a discussion in peeoner to add them, so much better for the platform and new users"
   - "A very cool idea to be able to put any emoji from a large set, but only a few dominant ones are displayed! So you can better understand the relationship to the content."
   - "Having to select any emoji you want is cool, but for me I prefer a pre-selected set of emojis are they as it is easier to use. Also, having to sign the transaction on chain everytime you react is quite a hassle at first, although, eventually you get use to it.".


## Recommendations
@dmtrjsg 
Based on the results above, I recommend proceeding with a custom, limited set of reactions, in the following order:
1. 👍 amusement, 
2. ❤️ love, 
3. 😂 laugh,
4. 🤯 shock,
5. 😡 anger.

**Comment by dmtrjsg** [comment]
payment requested with @bwhm
