### ISSUE TITLE
Button component improvements

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2123]
**Changelog:**

• Removed "white" button type
• Added "Secondary" text button type for variants: Text, Text + left icon, Text + right icon. It will replace removed "white" button type. No visual differences, just different name of the type.
• Added "Tertiary" text button type for variants: Text, Text + left icon, Text + right icon.

**Figma link:**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=216%3A6243

**Comment by kdembler** [comment]
Tackled in #2463
