### ISSUE TITLE
Video thumbnail improvements to support Playlists.

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2125]
**Changelog:**

• Added new "Type" property
• Added new "Playlist" type to support playlists with this component.

**Figma link:**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=3629%3A119374

*Important:
New playlist thumbnail has different hover animation.

**Comment by kdembler** [comment]
@TCzechowski I think yesterday during sync you guys mentioned there is some additional transition of the `X videos` overlay on hover? Is that a thing or maybe I misunderstood?

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2125?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
