### ISSUE TITLE
New "Playlist tile" component

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2126]
Created new "Playlist tile" component. All of the info can be found in the Figma link below :)

**Figma link:**
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5663%3A174913

**Comment by kdembler** [comment]
Do these tiles look somehow differently for publishers or do we only use the existing variant?

**Comment by TCzechowski** [comment]
@kdembler We're going to use something else on the publisher side (list view), so we don't use these anywhere on the publisher side :)

**Comment by kdembler** [comment]
All right, thanks for the clarification, looks good then 👍

**Comment by TCzechowski** [comment]
Small update @kdembler:
We are not using the "Playlist tile" component on the publisher side, but we **are** using Video thumbnail with it's type set to "Playlist" (new thing, https://github.com/Joystream/atlas/issues/2125)

**Comment by kdembler** [comment]
All right, I have some concerns about that one though, will mention during our sycn

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2126?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow
