### ISSUE TITLE
Update file select component to support changes in Playlist: Channel owner

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2127]
File select, dropzone, and file step components got an update to support the new usage of dropzone in the playlist workspace.
All three components are now documented in a new documentation style and ready to be implemented.

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5664%3A176055
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5664%3A175508
https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-Components?node-id=5664%3A174961

It's highly recommended to first have an intro call with a designer before starting to implement the changes.

**Comment by kdembler** [comment]
Some feedback here: Currently the dropzone component defines only 2 properties, `Type` (Empty or Thumbnail) and `State`. However, it seems there's quite some more possible adjustments to this component. For example, like mentioned in the docs below, copy for specific step or whether the button is primary. I think we should define all possible variants on component-level, so we don't do manual overrides for specific usages. So I would expect to see variants for empty state for both thumbnail and video, and separate variant for playlists.

**Comment by KubaMikolajczyk** [comment]
> Some feedback here: Currently the dropzone component defines only 2 properties, `Type` (Empty or Thumbnail) and `State`. However, it seems there's quite some more possible adjustments to this component. For example, like mentioned in the docs below, copy for specific step or whether the button is primary. I think we should define all possible variants on component-level, so we don't do manual overrides for specific usages. So I would expect to see variants for empty state for both thumbnail and video, and separate variant for playlists.

OK I will make all variants into components 👌

**Comment by KubaMikolajczyk** [comment]
Hey it looks like I shouldn't have to do all of the components as separate instances in Figma - as the only difference occurs in case of empty states for all usages across the app - so I listed all empty states copy here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=5664%3A175508
Do you think it can resolve this issue?

**Comment by kdembler** [comment]
Well this component needs prop to control what's displayed inside it. For example, the button variant inside changes, so this needs to be controlled somehow. But let's not drag it, we will just do this ourselves in the implementation

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2127?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
