### ISSUE TITLE
Fix the grid on the My videos page

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2134]
**AC:**

- [ ] Update my videos grid to use 24px gap on MD breakpoint

---

With the recent design updates to the My videos page, a couple of errors have sneaked into the way the grid is applied in Figma, which — unfortunately — made their way to the implemented version of the page as well.

The goal of this task is to go over the Figma designs for the My videos page and verify:
1. If proper grip settings are used on different breakpoints (things like a gap of 16px and a gap of 24px, etc.),
2. If the correct size of the Video tile components is used on different breakpoints,
3. If all Figma frames are properly laid out and are indeed filling out their containers.

Once design fixes are applied, this task is expected to be carried over to the tech team with a detailed description of what exactly has been adjusted.

**Comment by KubaMikolajczyk** [comment]
The grid was fixed - please note that videos grid changes on breakpoint MD (1024px) from 16px (vertically and horizontally) to 24px (vertically and horizontally).
Link to my videos RWD screens: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=214%3A13275
