### ISSUE TITLE
[USERSNAP] video preview on timeline

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2142]
**Sender**: r10v4@outlook.com
**Taken at**: https://play.joystream.org/video/7988
**Fields**:
- Welches Feature würden Sie sich wünschen?: video preview on timeline
- Welches Problem würde das für Sie lösen?: to pick the right scene of the video on the timeline
(like in youtube)

**Browser**: Chrome 96 (Windows 10)
**Screen size**: 1397x786
**Labels**: new feature
**[Open #6 in Usersnap](https://app.usersnap.com/l/feedback/4b52d584-3109-4988-80d3-acbea203ee73?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

⚠️  server side dependency

**Comment by dmtrjsg** [comment]
@kdembler  same as #1646 ?

**Comment by kdembler** [comment]
Yep!

**Comment by dmtrjsg** [comment]
Closing as duplicate
