### ISSUE TITLE
[USERSNAP] Right click menu should have "Save video as" option. It shows only "save audio as" option.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2143]
**Taken at**: https://play.joystream.org/video/14464
**Fields**:
- Expected Result: Right click menu should have &#34;Save video as&#34; option. It shows only &#34;save audio as&#34; option.
- Houston, we have a problem.: Video is not visible.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8285ae18-05c9-4c2d-b7cf-ff2c0ab748cf-annotated_5b3b519e-4d57-4d4b-aacd-3026f8083914.png?etag=d257b3245d90115eea0bd570789bde18)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8285ae18-05c9-4c2d-b7cf-ff2c0ab748cf-annotated_5b3b519e-4d57-4d4b-aacd-3026f8083914.png?etag=d257b3245d90115eea0bd570789bde18)*

**Browser**: Chrome 97 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x937
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/00f7b80c-aed3-4ef1-9814-bf8675221c11_screen_recording_0241f657-89e9-4c43-b5eb-29638da23fcb.webm?etag=3eaace97bfd06d4a47690abd9899cccf)**
**[Open #9 in Usersnap](https://app.usersnap.com/l/feedback/860cc638-8327-4aab-8451-fc4f17c5b0c3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
❓  Do we have an idea of "save audio as" is? (I cannot clarify as this was an anonymous report) @kdembler

**Comment by kdembler** [comment]
I think they are referring to the menu they get from the browser when right-clicking, that's outside of our control. However, they mention that the video is missing from playback, not sure what that's about

**Comment by dmtrjsg** [comment]
Thanks for your replies. There isn't anything we can do to get back to the guy and also _No console  messages were recorded._ so closing
