### ISSUE TITLE
[USERSNAP] It should start uploading again. However I get the below response: Failed to upload asset: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2144]
**Taken at**: https://play.joystream.org/studio/uploads
**Fields**:
- Expected Result: It should start uploading again. However I get the below response:
Failed to upload asset: Cannot read properties of null (reading &#39;name&#39;)
- Houston, we have a problem.: studio/uploads retry button returns an error

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d2aa5daf-3fe6-47b8-9cb0-959f1bafdd41-annotated_75fab5ee-2477-46ab-8178-27bc0db9d82b.png?etag=634aa0a30a560314773330d833bde13f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d2aa5daf-3fe6-47b8-9cb0-959f1bafdd41-annotated_75fab5ee-2477-46ab-8178-27bc0db9d82b.png?etag=634aa0a30a560314773330d833bde13f)*

**Browser**: Chrome 97 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 625x664
**Labels**: Bug
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/3b8ae0dd-dc86-4225-b921-3a3976cc7140_screen_recording_bdf24c15-4c83-4749-851a-4e5c02fd2046.webm?etag=5a92f905f9a22f23a50c52ca8c51b53f)**
**[Open #7 in Usersnap](https://app.usersnap.com/l/feedback/1b58a82c-aa01-440a-9ce0-0f81a13594de?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by kdembler** [comment]
This should be fixed already
