### ISSUE TITLE
Beautiful 404 page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2147]
## Context 

Create a 404 as we had a blank page served before

## Designs: 

[Link to Figma](https://www.figma.com/file/KiWym2ELAfUrCqMmDddmfu/404-page?node-id=105%3A202)

## Scope
- [ ] Create a beautiful page available for random urls
- [ ] Include separately in each layout (viewer, studio, etc.)
- [ ] Ignore the Joystream logo at the top since this will be already in the topnav
- [ ] The button should navigate to respective layout homepage (for example "My videos" when in Studio)

## ⛔  Out of scope
- review existing pages for video/channel/playlist unavailable

**Comment by TCzechowski** [comment]
**Figma link:**
https://www.figma.com/file/KiWym2ELAfUrCqMmDddmfu/404-page?node-id=328%3A1815

No user stories as this is pretty much self explainatory :)
