### ISSUE TITLE
Design Changes to Publisher Experience

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#215]
# Terminology

In this issue we use the term _content_ to refer to both videos and channels, and _media assets_ to refer to both video and image files which will be stored in the Joystream native storage infrastructure.

# Problems

The following problems have occurred due exclusively to mistakes on my part.

1. It was assumed that it is possible to initiate media asset uploads without having to sign anything. To clarify, by initiating, I am referring to actually starting to put data on a remote host.
2. We are not dealing with the possibility of interrupted or failed uploads. Not designing for this could more expensive tech/design debt later.
3. We are not dealing with the fact that uploading a assets requires a possibly lengthy (0-10s) client side computation of a hash fingerprint prior to upload can be initiated. The user will in the current design be able to issue transaction before this is done.
4. It is assumed that when content is updated on-chain, then the effect is immediately visible on the consumer side. This is not correct. Because of the issue in 1, new content should not be visible for consumers before all media assets are fully uploaded. In the current design the video is shown available for playback in the videos page with immediate effect, and the publisher also does not understand this delay, which has unpredictable length, and may think that once the transaction succeeds, the content should be available in search results and under his/her channel. A note: When it comes to editing media assets we do not follow this policy, frankly because its too complex to get right, hence if a user edits two or more assets at once, the changes will be immediately visible in the order they become uploaded, which can lead to temporary mismatching assets visible to some users.
5. Most transactions will have two independent sources of delay before the intended effect will be visible in user facing applications: getting the blockchain to accept the transaction, or not, and getting the API powered by the blockchain to reflect the new state of the blockchain. The latter process may itself take a variable number of seconds, and will occur after the signer has disappeared. This means that when you edit your channel title for example, in the current design, it will not be immediately updated in Atlas, either for the publisher or consumer, and you will see the old title for some unpredictable length of time. This is not ideal, but it may be an acceptable circumstances, at least for some time.
6. The cover/avatar editor, which allows you to control placement and size is a bit underspecified. Its not clear how _exactly_ it will work. What are the limits to the placement, how far can you zoom in or out, and how does this interact with the relative dimensions of the image vs. the image area. For example the twitter profile image editor prevents any edge of the image from moving to the inside of the image area, which seems very useful to avoid very bad placements where the image is almost outside the canvas entirely.

# Caveat

A complicating factor in designing Pioneer has been keeping in mind that the storage system is being redesigned, and trying to anticipate what it will look like is not easy in all respects, however, the described problems are genuine because we anticipate they reflect deep constraints that are _likely_ to be in place for the long term. That said, it is entirely certain that even after addressing the problems described, further changes will be required in the future as that system becomes ready.

# Storage System & Content Directory

Here I attempt to describe the storage system and content directory as they should be assumed to behave for the purposes of the publishing experience in Atlas.

### Publishing

This applies both to creating videos or channels.

1. Regardless of how many assets you need to upload, and how much metadata you want to publish, this will be possible in a single blockchain transaction. In order to make this transaction, a hash digest must be computed for each media asset to be uploaded, and the time it takes to compute this digest is roughly proportional to the size of the asset. So a very large video will take longer than a small image for example. In an absolute sense I think we can assume that most normal cases will take anywhere from 0 to 10s. Obviously the metadata also has to be ready prior to making the transaction as well, as it is supposed to combine everything. The fee associated with this transaction will be determinable up front, before issuing it. Hence only a single interaction with the signer extension app is required.
2. Doing this transaction may or may not itself work, and if it does, one will have to retry.
3. When the transaction is successful, the actual upload of the assets can commence.
4. As each upload completes, the relevant storage host that accepts the upload will make a separate transaction on the blockchain signaling this. As each of these confirmations are issued, Atlas will eventually learn about them, but the delay is not entirely predictable. If the API/query node is working properly, it could possibly add an extra 2-3s to the existing delay associated with getting a transaction confirmed, but it could be slower. Importantly, the consumer side of Atlas should follow the policy of entirely omitting any content, be it a channel where any of the assets have not yet been confirmed to be completely uploaded, the publisher side could however choose to show content published under your channels which are not yet completed, or potentially permanently interrupted from a prior session.
5. One of the uploads may fail, either because the user loses their internet connection, or because the host accepting the upload has some kind of problem. At that point it is possible to retry connecting to the same host at any time and re-upload the same content _from scratch_. However, if the problem is on the other end, you may experience never being able to connect, or never being able to complete, multiple times in a row, in which case, you likely will need to re-initiate a fresh upload with someone else, and that will require a new transaction+signing. In this case, see _editing_ section to learn about that.

Notice that one has to publish the metadata (1) _before_ the upload begins (3), which is the reverse of the current flow in the app.

### Editing

The user may want to edit some subset of metadata or subset of media assets for a video or channel. Alternatively, as in 5 in the _publishing_ section, an upload of media assets may have failed so consistently with the given host, hence it has become required to reinitiate the upload with someone else.

This action, like above, is done in a single transaction, with computable up front fees, and a single signing interaction. After the transaction is sent, one or more asset uploads begin, while these uploads are in transit, the old assets will still be visible to consumers and publishers alike under the current design. If more than one asset is being updated, the content will appear with possibly an inconsistent set of assets applied, because the assets will not complete uploading all at once.

**Comment by bedeho** [comment]
# Addendum

In the interest of simplifying Atlas publishing, we will not support URL based assets of any kind, video or images, only uploads to the native Joystream infrastructure.

**Comment by kdembler** [comment]
All of those seem to be resolved by now
