### ISSUE TITLE
The problem with viewing videos with non-standard aspect ratio

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/atlas#2155]
The problem is noticeable when watching a video with a non-standard aspect ratio In full-screen mode, in the example - vertical video. 

1. Go to [atlas](https://play.joystream.org/video/15127)
2. Click Exit cinematic mode if active
3. Click Fullscreen
4. As a result, the video takes up the entire width of the screen, but the player controls disappear

Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by kdembler** [comment]
Thanks for reporting, I see we missed some things when updating the player page, will fix soon!
