### ISSUE TITLE
Idea: Timestamp reference in comments that allow navigating to precise playback location

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2177]
Basically stuff that appears like this on YT and works like a link

![Screenshot 2022-02-22 at 20 26 58](https://user-images.githubusercontent.com/437292/155204467-403467f3-95ec-47f6-8f2c-112b4412e932.png)

**Comment by dmtrjsg** [comment]
this will be covered by #2936 and taken to this sprint
