### ISSUE TITLE
UI for when an auction will start in the future - NFT Widget

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#2180]
### Description

Fairly self-explanatory we need a UI state for the NFT widget to show that an auction exists but has not yet started.

### Figma link

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1242%3A109695

### How urgent this is?

This is blocking me now

**Comment by kdembler** [comment]
I think the same goes for NftTile?

**Comment by toiletgranny** [comment]
This has been addressed in https://github.com/Joystream/atlas/issues/2182, see examples below. Please note, that this also requires changes to the NFT tile component.

![image](https://user-images.githubusercontent.com/35307309/157064535-5cbb9fb1-4ab5-4544-af2e-a5e901a396fa.png)
![image](https://user-images.githubusercontent.com/35307309/157064643-a3b83123-beec-4f65-8816-97d5d97e1541.png)
