### ISSUE TITLE
Fetch NFTS owned by a member on the members page

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#2181]
Fetch NFTS owned by a member on the member page with:

- Filters
- Sorting
- ~~Infinite grid scrolling~~ Normal pagination

https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?node-id=923%3A136058

**Comment by eldiegod** [comment]
@toiletgranny should this page have an infinite grid or pagination?

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2181?planning-poker) with ZenHub @drillprop @eldiegod @lcoenengithub @rafalpawlow

**Comment by drillprop** [comment]
@eldiegod just FYI I edited your post. I talked to Adam and he said that we should implement regular pagination, not infinite scrolling.  It seems that the design is currently wrong.

**Comment by eldiegod** [comment]
@drillprop nice, thanks for the update 👍
