### ISSUE TITLE
NFT design changes

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2182]
In this issue I will try to summarize new agreements around NFT auctions and how they operate. Based on https://github.com/Joystream/joystream/issues/3285

### Updated rules for **open** NFT auctions:

- Single auction can have multiple bids, but only a single bid per member. Members are free to replace their bids, either increasing or decreasing the price.

- There is no validation applied to bids, other than making sure they are bigger than the minimum price. This means that the concept of **minimal bid step does no longer exist in an open auction**. You also don't have to place a bid that is higher than 
the currently top one

- NFT owner is free to pick the winning bid from the list of all of them, doesn't have to be the highest one

- Withdrawals of bids are never automatic. If you place a bid on an open auction, you will have to manually withdraw it, the only exception is if you are picked as the winner. So it may be possible that you have a bid left to withdraw, even though the auction has already ended, and the NFT is no longer for sale. Since we allow single bid per member, you will usually have only a single bid to withdraw, although I think the following edge-case is possible (to be confirmed):
1. You place a bid on running auction, let's call it Auction A
2. Someone else is picked as a winner of Auction A
3. New owner of the NFT places it on an auction again, let's call it Auction B
4. You place a bid on Auction B
5. You have two bids available for withdrawal, from auctions A and B

---

### For **English** auctions the same old rules apply:
- Bids cannot be cancelled and if at least a single bid has been placed, the auction cannot be cancelled
- There is only a single active bid, the highest one, and the previous bids get automatically withdrawn when outbid
- New bid always has to be higher than the (current bid + minimal bid step)
- When the timer expires, the highest bid wins

---

@toiletgranny @dmtrjsg Given those, we will need to review the designs and make sure they reflect these behaviors (they don't) and schedule any necessary updates

**Comment by dmtrjsg** [comment]
Members are free to replace their bids, either increasing or decreasing the price. -> before they got outbid? Or independent, meaning they can keep bidding but the treatment of their bid on the system level is different? (is the current auction price for bidders here not visible?)

You have two bids available for withdrawal, from auctions A and B -> if that is the case, we'd probably need a place to list your bids.. separate tab in the notification for auction-related notiffs could be a step into this direction.

**Comment by kdembler** [comment]
> Members are free to replace their bids, either increasing or decreasing the price. -> before they got outbid? Or independent, meaning they can keep bidding but the treatment of their bid on the system level is different? (is the current auction price for bidders here not visible?)

Sorry but I don't fully understand your question. You will be able to modify your bid, independently of other bids, so being outbid doesn't have any effect on this ability.

> You have two bids available for withdrawal, from auctions A and B -> if that is the case, we'd probably need a place to list your bids.. separate tab in the notification for auction-related notiffs could be a step into this direction.

Still needs to be confirmed, we're discussing the runtime treatment

**Comment by toiletgranny** [comment]
> Still needs to be confirmed, we're discussing the runtime treatment

Regarding two bids being available for withdrawal, @kdembler, do we have any updates on that? I've been playing with Rarible today and the way they approach this is that they treat auctions independently from the current NFT owner. If I place a bid on an auction which is then settled (and I'm not a winner), my bid is still out there available for the new owner to be accepted if they want. If the new owner puts this NFT on a new open auction, my previous bid remains valid (if it matches the new criteria).

**Comment by kdembler** [comment]
I think what we agreed on is that you have to withdraw your bid from the previous auction before you can place a new one

**Comment by toiletgranny** [comment]
Ok, so just to make sure, does it mean that if I don't withdraw my bid and a new auction begins (let's say it's an open auction initiated by a new owner, who won the previous open or English auction), my bid _can be_ selected as a winning one in that new auction?

**Comment by kdembler** [comment]
No, our plan was to not make this bid acceptable. So it's not valid anymore and you need to withdraw it if you want to place a new one

**Comment by toiletgranny** [comment]
## NFT widget component

![image](https://user-images.githubusercontent.com/35307309/157045623-bbf9e15a-369d-4f96-8713-15ef01cd1967.png)


Updated designs and docs for the NFT widget component, along with a breakdown of all changes in designs, [can be found in Figma](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A112135). Please note, that:
- This component update addresses the following GitHub issues:
   - https://github.com/Joystream/atlas/issues/2196,
   - https://github.com/Joystream/atlas/issues/2195,
   - https://github.com/Joystream/atlas/issues/2180,
- Along with changes and adjustments to the NFT widget, minor changes in the [NFT owner](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A123336)  and the [NFT info item](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A123284) components need to be implemented as well.
- Because of the above changes, user stories for [accepting a bid (as an NFT owner)](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1247%3A100057) and[ withdrawing a bid (as a content viewer)](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1247%3A107861) has been updated in Figma.

**Comment by toiletgranny** [comment]
## NFT tile

![image](https://user-images.githubusercontent.com/35307309/157059509-d2d10426-3edc-4a45-88b2-b1ce9f3e37e1.png)

Updated designs and docs for the NFT tile component, along with a breakdown of all changes in designs, [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3630%3A139541). Please note, that this component update addresses the following GitHub issues:
- https://github.com/Joystream/atlas/issues/2195,
- https://github.com/Joystream/atlas/issues/2180.

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2182?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
