### ISSUE TITLE
Idea: Show constitution

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#2192]
This doesn't seem to have been discussed or mentioned on this repo at all, it has been suggested via this issue: https://github.com/Joystream/atlas/issues/2191

TLDR: `Atlas` should show the constitution, or maybe the particular area of it dealing with content and moderation policies.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202539691060621) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Thank you for raising. This could potentially be handled via these two tickets. tbc

- https://github.com/Joystream/atlas/issues/2032
- https://github.com/Joystream/atlas/issues/2120

**Comment by bedeho** [comment]
I disagree, Atlas is about content only, and it is a consumer interface, the constitution will be a very complex document describing all sorts of policies.

**Comment by dmtrjsg** [comment]
@bedeho While I do not have a strong view on this, just to clarify, would it not make sense to even include a link to it in the footer of the side nav? Would constitution or relevant parts from it be cited in Terms of Service or Content Policy which are already added there?

<img width="394" alt="Screenshot 2022-07-22 at 15 35 36" src="https://user-images.githubusercontent.com/93924525/180462389-005d886b-54b6-4252-a2ad-795d606969ce.png">

**Comment by bedeho** [comment]
> While I do not have a strong view on this, just to clarify, would it not make sense to even include a link to it in the footer of the side nav? Would constitution or relevant parts from it be cited in Terms of Service or Content Policy which are already added there?

the only thing I see that could make sense would be some backlink to the project itself, because I assume more and more people will just directly land in some instance of Atlas, not even hosted by Jsgenesis, and getting some sort of contextual way to find out or find out about Joystream makes sense, the consitution is multiple layers out of context, and may have very limited relevance to the actual Atlas app.

**Comment by dmtrjsg** [comment]
The link to Joystream would be from the logo / Atlas re-branding. With "powered by Joystream" badge.  Tagging @toiletgranny  so we pick it up in the relevant ticket or add here if the decision will be taken to go in a diff direction.

**Comment by toiletgranny** [comment]
Hey @dmtrjsg, thanks for tagging! I'm afraid it's unclear to me exactly how I can help at this point, though.

1. > The link to Joystream would be from the logo / Atlas re-branding.

    Which logo? Atlas? Do you mean linking to Joystream.org by clicking on the Atlas logo? 
    
2.  >  With "powered by Joystream" badge.
     
     The word _badge_ implies adding something visual somewhere, but I'm afraid I can't remember we talked about this before. Apologies if it's my memory, but could I ask you to elaborate on this idea or point to an issue where it's described? 😅 

I'm happy to discuss this over tomorrow's tech/design sync call if you prefer! :)
