### ISSUE TITLE
Expired English auction state for NFT components

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2195]
### Description

While developing some of the NFT components we've noticed that they're missing states for an English auction that has expired. What I mean by that is:
- the auction has finished - it's past its end block and new bids are not accepted
- at the same time, the auction hasn't been settled yet.

The following components are affected:
1. `NftTile` doesn't seem to have any variant for that case
2. `NftWidget` (displayed on Video page) has a state for when you (as a buyer) have won and the auction is awaiting settlement. However, it's not specified what should be presented in this case to:
a) NFT owner
b) random user not participating in the auction

One additional case to handle is when the auction has expired but there were no bids made to it. In that case, the auction needs to be cancelled by the owner.

### How urgent this is?

It's blocking me right now

**Comment by toiletgranny** [comment]
This has been addressed in https://github.com/Joystream/atlas/issues/2182, see examples below.

![image](https://user-images.githubusercontent.com/35307309/157063574-3073b09c-f849-4ced-861b-dc95c8c5722f.png)
![image](https://user-images.githubusercontent.com/35307309/157064210-9f2e5517-04f5-4ac0-8e95-2ca90d19e616.png)
![image](https://user-images.githubusercontent.com/35307309/157063620-416bb6e4-804e-4025-aa37-36ae55e78490.png)
