### ISSUE TITLE
NFT Widget doesn't mention current auction winner

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2196]
### Description

The NFT Widget component shows the NFT auction status, including the current top bid. However, it doesn't show the current auction winner, i.e. who has made the current top bid. If I'm participating in the auction it would be useful to see at a glance whether I'm currently the winner, without analyzing the NFT's history.

### Figma link

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1242%3A109726

### How urgent this is?

This will block me soon

**Comment by toiletgranny** [comment]
This has been addressed in https://github.com/Joystream/atlas/issues/2182, see the preview below.

![image](https://user-images.githubusercontent.com/35307309/157063142-bb8eb7ff-3367-47b7-91e3-a5d6ed6e1c4b.png)
