### ISSUE TITLE
Global Search Box improvements

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2207]
We've moved Global search box component from Web components to local Search results page, and updated few things in the process.

**Changelog can be seen on Figma:**
https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=2%3A10973

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2207?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
