### ISSUE TITLE
Comments Design: Video workspace — LoFi mockups

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2210]
### User stories

1. As a channel owner, I want to enable or disable the comments section for my videos, separately.

**Comment by toiletgranny** [comment]
@dmtrjsg my recommendations for the experience of enabling/disabling the comments section in the video settings are ready to be reviewed! Find out all about it here:

1. [Loom video update](https://www.loom.com/share/d0867111546b42368cb82e04b96ebeb6) (0:00 – 5:35),
2. [Figma prototype](https://www.figma.com/proto/EzJmuVoYrIEuUZ8VhqEBdH/Video-page%3A-Reactions-%26-Comments?page-id=2146%3A307565&node-id=2146%3A313334&viewport=402%2C48%2C0.21&scaling=min-zoom&starting-point-node-id=2146%3A313334&show-proto-sidebar=1)

The key open question is whether we agree to keep the comments section visibility setting remaining under the control of the video author even after an NFT for this video has been issued and transferred to another member? My recommendation is: yes, because of the reasoning I provided in the video update.

cc @kdembler

**Comment by kdembler** [comment]
I agree that this should modifiable after NFT is minted

**Comment by dmtrjsg** [comment]
@toiletgranny  Thanks for detailed consideration on the disable comments feature, agreed with everything you've said!

➕  One suggestion is to present the "Disabled comments" situation for viewers with a line of copy "Comments are disabled by the owner." (instead of simply hiding)

**Comment by toiletgranny** [comment]
Thanks, @dmtrjsg! Of course, this will be included in the designs for the Video page.

**Comment by TCzechowski** [comment]
I've added enabling/disabling comments in video settings, but it is just adding a small section in currently existing flow in Figma. We do have existing user stories for uploading a new video, editing an existing one, and editing minted video, and all of those will have the comments section included, so it didn't make sense to me to create a separate User story (flow in Figma) for that section.

Designs:
[New video - Expanded (+ new video)](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)
[Editing minted video](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)

![image](https://user-images.githubusercontent.com/22870059/159491594-9049de6b-b9a4-40c0-875b-da05bc1a3c53.png)
