### ISSUE TITLE
New way of handling transaction with minimised snack bar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2225]
## Context

Reactions due to frequency require a more subtle way to show signing transaction toaster

## Scope

Update the way how toaster notification looks and works
- [x]  update card design
- [ ] only show at the point of triggering reaction, once signed we _don't show progress/success_ 
- [ ] Show toaster it again if transaction fails
- [ ] Write logic for handling the transaction in the background. Pay attention to the fact that the transaction handling cannot be longer done by a hook called by the view, because the view can be quit when the transaction is processing.

**Out of scope ⛔ :**
- [ ] In case of multiple transactions triggered, the toaster will show compound (aggregate counter of transactions pending signing) ⚠️ covered in comments designs which are WIP
- [ ] Skip Retry button in failed snackbar

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2225?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow

**Comment by toiletgranny** [comment]
To whoever is going to be the developer picking this up: keep in mind, that it's technically possible for me, as a content viewer, to like or dislike multiple videos (operating within the same browser tab), and then sign the transactions in Polkadot separately. Should that be the case, here are designs for how it's been agreed to handle this in the Snackbar component.

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2572%3A456346
