### ISSUE TITLE
Component for likes/ dislikes and ratio bar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2226]
### Context
Dev epic for Reactions on video page.
🔧  Design epic: 
- #1985 

### Scope

- [ ] Component for like/ dislike
1. default
2. liked
3. disliked
4. Processing state (when the transaction is ongoing)
5. Loading state (when we don't have the data yet)

- [ ] [likes-to-dislikes ratio bar](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2093%3A135314) Let's use a simple transition between the loading/processing state - we can fade out the ratio bar and fade in the animated bar and vice versa, instead of fully animating the bar
- [ ] Show a information popover when the user reacts for the first time (local storage persistent) - https://www.figma.com/file/EzJmuVoYrIEuUZ8VhqEBdH/Video-page%3A-Reactions-%26-Comments?node-id=2029%3A472760

### Designs

[Link to Figma user story ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2093%3A135229)
[Link to Figma component](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A114186)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2226?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
