### ISSUE TITLE
Animation once reaction is added

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2228]
### Context

Animation for adding reaction as part of the #1876 epic

### Scope

- [ ] Animation once reaction added

### Designs

[Link to Figma](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A114186)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2228?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow

**Comment by kdembler** [comment]
Done in #2411
