### ISSUE TITLE
Integrate video reactions

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2229]
### Context

Handling transaction for reactions. Depends on all components to be in place before doing it.

### Scope
- [ ] Handle transaction execution for leaving reaction on a video page

### Design
[Figma ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2093%3A135230)

✋ 📖  link to be added perhaps with some help from @kdembler

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2229?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
