### ISSUE TITLE
CO: Playlist List Page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2232]
### Context

User story for Channel Owner wrt Playlist creation and mgt

### Scope

- [ ] Create a layout for `My playlists` view (including tabs)
- [ ] Create `PlaylistRow` component (include mobile variant with actions without hover)
- [ ] Create the list view (can be scrollable horizontally on mobile)

### Out of scope

- [ ] Drafts tab, or anything else related to drafts

### Design

[Link to figma](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=966%3A16231)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2232?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
