### ISSUE TITLE
CO: Custom Thumb user story

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2237]
### Context

User story for Channel Owner wrt Playlist creation and mgt

### Scope
- [ ] Custom Thumbnail for Playlist

### Designs

[Link to Figma](https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=970%3A16745)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2237?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
