### ISSUE TITLE
Loading State of the Reactions progress

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2244]
**Context**

![Screenshot 2022-03-08 at 14.40.25.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/aedd0fb0-3bcd-4366-b89e-8fdbb0cd0c73)

**Scope**

We need to call this "in progress state"
And think about the loading state (when page loads and we don't have the data just yet)

**Comment by toiletgranny** [comment]
![image](https://user-images.githubusercontent.com/35307309/157454747-f14a2472-395b-46b1-a953-12a67a5f82f6.png)

Designs and docs for the updated Reaction stepper component [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A114186).
