### ISSUE TITLE
CW: Playlist Details View Components

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2252]
### Context

Playlists content viewer side

### Scope

- [ ] Playlist details card

Thumbnail image
Meta
Description
Channel Owner + Follow
Copy playlist link

- [ ] List of videos on the right
+ Infinite scroll

- [ ] Handle empty state (no videos) [Figma > ](https://www.figma.com/file/f6pcaMR7bryFmszfrzTqJM/Playlist-details-page?node-id=336%3A2174)

Out of scope ⛔ 
- [ ] Numerated list (e.g. drop numbers)

### Designs

🎨  [Link to Figma > ]([Link to Figma>](https://www.figma.com/file/f6pcaMR7bryFmszfrzTqJM/Playlist-details-page?node-id=927%3A51669)

Preview: 

<img width="817" alt="Screenshot 2022-03-09 at 16 43 39" src="https://user-images.githubusercontent.com/93924525/157488815-eafc4319-b3e8-4d5d-9eaa-b533bc83aa06.png">

Preview Empty List State:

<img width="862" alt="Screenshot 2022-03-09 at 17 15 20" src="https://user-images.githubusercontent.com/93924525/157495082-e9379701-5ed4-4751-8242-43017aad76be.png">

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2252?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
