### ISSUE TITLE
CW: Playlist Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2253]
### Context

Playlists content viewer side

⚠️  When user enters the Video page by clicking Playlist tile or from Playlist details page, we display Playlist content component on the right side.

### Scope

- [ ] Playlist widget

> Playlist title
> Channel owner name
> Ordinal number of video playing 
> List of other videos  
> Collapsible state tbc

- [ ] Copy link as all cases are covered here #2251 

Out of scope:
- [ ] Videos play in a defined order (e.g if video 3 plays, video 4 is next)

### Designs

[Figma> ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=1987%3A128637)

Preview:
<img width="843" alt="Screenshot 2022-03-09 at 16 56 36" src="https://user-images.githubusercontent.com/93924525/157491387-66c935ba-7946-4f79-94e9-1b10d52e468a.png">

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2253?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
