### ISSUE TITLE
CW: Featured in Playlist

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2254]
### Context

Playlists content viewer side

⚠️  When user directly opens a video that is part of a playlist (not from playlist details page), then the “Featured in playlists” section is displayed.

### Scope

- [ ] Featured in playlist

> Playlist title
> Channel owner name
> Ordinal number of video playing 
> List of other videos  
> Collapsible state tbc

Out of scope ⛔ 
- [ ] Copy link as all cases are covered here #2251 

### Designs

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2254?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
