### ISSUE TITLE
CW: Playlists section in "All" tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2256]
### Context

Playlists content viewer side

### Scope

- [ ] Add "All" tab in channel viewer view

### Design

[Figma link][(https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=5%3A25483)](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=983%3A69004)

Preview:

<img width="586" alt="Screenshot 2022-03-15 at 13 48 10" src="https://user-images.githubusercontent.com/93924525/158391843-6fef569b-9176-42dc-b0f0-0b811655adc0.png">

**Comment by dmtrjsg** [comment]
@TCzechowski pls add a link form Figma here once ready ;)

**Comment by TCzechowski** [comment]
@dmtrjsg done

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2256?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
