### ISSUE TITLE
CW: Search results with PL

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2257]
### Context

Playlists content viewer side

### Scope

- [ ] Playlists section on SR page (all)
- [ ] See more playlists (shows if there's more matches)
- [ ] Playlists tab
- [ ] Playlists section in search drop down? [Figma](https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=2%3A10973)

### Design
[Link to Figma> ](https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=5%3A75397)

<img width="788" alt="Screenshot 2022-03-09 at 17 24 22" src="https://user-images.githubusercontent.com/93924525/157496735-a41b49e4-56fe-4e04-9182-2a4de6bb8d31.png">

**Comment by dmtrjsg** [comment]
- [ ] No playlists section in search drop down? (⚠️ tbc) @TCzechowski @kdembler  pls remind me if we agreed not to include it..

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2257?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow

**Comment by TCzechowski** [comment]
> * [ ]  No playlists section in search drop down? (⚠️ tbc) @TCzechowski @kdembler  pls remind me if we agreed not to include it..

We do have it here:
https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=2%3A10973

**Comment by bedeho** [comment]
Superseded by https://github.com/Joystream/atlas/issues/5919
