### ISSUE TITLE
Research subtitles: adding

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2258]
# Overview
Feature of adding subtitles to videos need to be researched.

**Comment by KubaMikolajczyk** [comment]
# Desk research
In order to find out more information on the topic of adding subtitles to videos, I decided to first try it on my own. As I have never done it before I could test firsthand the whole process and learn from it. 
The whole process is commented on and captured here in user stories: https://www.figma.com/file/9ahrOSqPdyGfZmpKrtUpFn/Subtitles%3A-Publisher?node-id=708%3A313

### Findings
- I got stuck in the process twice: the first time when looking for adding subtitles function in the first step of the upload video modal and then later on when trying to create an .srt file that would get accepted.
- Youtube does not inform users about how to create an .srt file, or which software should be used to do it successfully
- Youtube allows users to add only one subtitle file while uploading a video but only a file for selected video language
- More languages can be added after uploading on a separate page called subtitles
- Youtube has also auto subtitling and manual subtitling feature - I couldn't auto subtitle any video that would be subtitled correctly 100% so I had to correct them manually anyway
- The whole experience is an unpleasant experience

### Srt file
File which is a standard for subtitling for many years already. It's a simple text file with no formatting in UTF-8, which is following the file structure shown in the picture below.
![image](https://user-images.githubusercontent.com/31144205/157651842-3c4e2ee8-9898-4576-a723-a9bd6ab8f680.png)
To make one can be a painful process. I couldn't succeed on TextEdit to make a file that would get accepted. I succeeded while creating a simple file in Atom IDE. That's why many people use external tools to get help with subtitles editing/creation. Tools such as:
- Subtitle Edit - existing long time on market
- Premiere Pro - has an option to add captions
- Movavi Video Edit
(and a long list of others, there is a lot of small software to do this job)

⚠️ In our UX & UI - We should consider how to care for a user who is brand new to subtitling/captioning and tries to make this kind of file for the first time.

### Subtitles vs Captions
Subtitles are just a translation to another language, and Captions is subtitling as well but with audio descriptions of events in the video for people with hearing impairment. Some video applications like Netflix will allow users to choose whether they want to play just English subtitles or English + captions.

But on youtube there is no clear difference between the two of them - it depends on a person creating subtitles if he/she wants to add captions as well to their subtitles (both of them are contained inside one .srt file). 

Maybe in our case, there is no need to ask the user if the file that he/she wants to upload is just subtitles or captions. And just treat them both the same way - but we will need then to add "Subtitles/CC" naming for that function in the video player to follow that logic @toiletgranny 

More in #2259 👉

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk  Nicely done! ⭐
