### ISSUE TITLE
First user interview subtitles : adding

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2259]
# Overview
Initial user interviews have to be conducted before the first explorations/mockups to get an initial idea of users' expectations and experiences.

**Comment by KubaMikolajczyk** [comment]
#### Test overview
# Subtitles: Adding, 09 Mar 22 
- Introduction interviews with users to find out their problems and expectations towards adding subtitles to videos on video platforms. To do this I invited users to test the youtube experience of adding subtitles and learn by observing their reactions.
- num of users: 3️⃣

# Testers to be paid:
5E9ZTTBh4p7vvrkJczqtYVMggimVhW3KJ83SdtBPy3TenANs
5CaDmoBUtV2ebxiFY3YVaK1k2k8bo9wcxGVTjKPhBSxXLuoH
5CAZtGnnkLGadGiieMp6M6ng631gw5F48oiLuif8xGARrjXk

# Test summary
- None of the testers ever added subtitles on youtube 
- One tester adds subtitles to her videos in premiere pro
- All of them had a basic understanding of what .srt file is and claim that would google how to make it if they had to do it
- All 3 testers expected being able to add subtitles at first step of adding new video modal, and were very confused that they didn't find it there
- All 3 testers went to show more section in add new video dialog and expected subtitles feature to be there 
- 2 out of 3 testers claimed that they would either resign or google for help once they got stucked in the process of enabling add subtitles function
- 1 out of 3 testers were able to find a way to add subtitles in more languages to their videos
- All testers claim the feature to add subtitles for more language is too hidden and expected it to be in the same place where they added the first subtitle

# Findings
- Testers had a lot of struggles with the youtube flow of adding subtitles to videos. 
- To address their bad experience we should avoid splitting this experience by adding subtitles to multiple steps and making unclear dependencies between fields. 
- Also adding more subtitles in other languages function should be in the same place in UI as adding the first subtitle, that's where users expect it to be located.
- .SRT file is a standard format for subtitles and people know about it - but youtube does not help anyhow or guide how to create it - there is room for improvement here to help new users get more familiar with creating subtitle files.

**Comment by dmtrjsg** [comment]
Payments requested. @KubaMikolajczyk if we are to use these particular respondents in our later design explorations/ validation, worthwhile to make a not about their participation here [Notion page](https://www.notion.so/4ecaa0a1b1c14135aafaade99bf23caa?v=6882a2bf17d14fa090ad31acbaf13964). 

PS: Loved this approach of testing on existing competitor flow with a view to incorporate the learned pitfalls to our very own designs 💪  Way to go!  @toiletgranny @TCzechowski let's try and adopt this approach for all our future designs where relevant.

**Comment by toiletgranny** [comment]
> Loved this approach of testing on existing competitor flow with a view to incorporate the learned pitfalls to our very own designs 💪 Way to go! @toiletgranny @TCzechowski let's try and adopt this approach for all our future designs where relevant.

Of course, @dmtrjsg, that's why we recommended Kuba to try out this approach.
