### ISSUE TITLE
Divide minting and listing experiences in Video workspace

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2266]
**AC:**

- [x] Update the visuals of the royalties input field
- [x] Use chain constants for royalties validation

---

# Overview
Due to new discoveries made during the implementation of NFT Issuance - New adjustments have to be done to the video workspace. 

# Tasks
- Re-design part of interface responsible for issuing NFT in video workspace
- Remove royalties screen from designs
- Remove royalties screen from user stories
- Correct all user stories accordingly to the new limitations
- Update video tile context menus with new actions
- Update all RWD
- Remove not for sale NFT listing
- Re-Design smooth experience for listing NFT on auction 
- Design onboarding(explanation) experience for a user minting NFT for the first time & showing how to list it after its done

**Comment by KubaMikolajczyk** [comment]
Video update summing up all work here: https://www.loom.com/share/0d2dee18c2324f1880113642913e8f6e
Link to changelog video workspace: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1378%3A93428
Link to changelog my videos: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=784%3A26954

**Comment by kdembler** [comment]
Looks good to me, @dmtrjsg want to review as well or should we move to Ready for dev?
