### ISSUE TITLE
Update playlist:channel owner with new changes

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2267]
# Overview
After review of playlist: channel owner some decisions were made
- Remove "more" button from playlist workspace 
- Drop concept of playlists drafts

Video workspace
- Add empty state for playlists while in video workspace 

Those decisions have to be implemented in final designs, RWD, and corrected user stories.

## Scope

- [x] #2486
- [x] #2487
- [x] #2488

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk pls do this point "Add empty state for playlists while in video workspace" as part of the ticket number (e.g. add link to figma to this ticket) >  #2168

**Comment by KubaMikolajczyk** [comment]
Done:
- More btn removed from designs, flows & rwd
- Same for draft system removed
- Warning added for user closing an unpublished playlist : https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=1064%3A33444
- Empty state for no playlist in video workspace flow created: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2509%3A162914
