### ISSUE TITLE
Add support for corner radii design tokens

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2273]
The goal of this task is to add support for radii design tokens. A JSON file for the new set of design tokens [can be found here](https://github.com/Joystream/atlas-resources/blob/main/design_tokens/radii.token.json), with mirror documentation in Figma [available here](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=878%3A9140).

![image](https://user-images.githubusercontent.com/35307309/157697031-1e5b719c-4900-41e6-b5d7-b669939e5601.png)

**Comment by kdembler** [comment]
TIL radii is plural of radius, I would totally say radiuses 😅
