### ISSUE TITLE
Ideas: Start playback before loading other thumbnails, detect user location, offer download link

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2282]
*atlas test March 2022*

Thanks to `youtube-dl` I do not watch yt online very often but noticed some new features recently:
- Comments are loaded not before the user scrolls down to see them. Maybe somethings similar is possible for suggested videos/thumbs.
- For popular videos flow is interrupted with 1 minute ad. Although it is out of the hands of the current atlas team but up to gateways i hope Joystream never does that.
- Since yt is a centralized platform so CDN features are easier than with decentralized buckets. Would it make sense to have the user select a location on first use or infer it (client-side)? Like
```
axios.get('https://freegeoip.net/json/')
  .then(({ data }) => {
    // select nearest bucket family based on `data.country_code` here
  })
  .catch(e => {
    // use sensible default and/or show decent notification to select location (like yt did for language a while back)
  });
```

- With the current atlas for me `more from <user>` and video details are loaded and shown before the actual video thumbnail and playback starts. Javascript enables to react to loading of certain elements with (pseudo code):
```
<CurrentVideoThumb onLoad={startPlaybackAndShowOther} onError={tryOtherBucketOrShowErrorDetails} />
```
(or something like [this](https://crate.io/blog/geolocation-101-get-users-location))

- When selecting replay for the currently watched and loaded video the video is loaded again instead being played from buffer / cache?
- keyboard shortcuts for `r` (replay), `n` (next), or `s` (stop) after playback
- option switch to toggle auto-play-next like on yt, possible user setting
- not all users may be familiar with licenses (for example what is [CC0](https://creativecommons.org/choose/zero/)). show tooltip with explanation or have it link to a separate route for details what a user is allowed to do with it.

[context](https://discord.com/channels/811216481340751934/859752198166282280/950743117613641768):
- maybe just a design decision to show empty placceholders instead of the grey blinking? just personal taste to reduce distractions
- if it possible (without big effort) to prioritize which elements are loaded first, priority could be the selected video and to load others once playback started (did not check if thumbnails take much time or if it is the QN request)
- the option select a bucket somehow would be a PRO feature (either per video / session or maybe an ordered list in settings to change priority persistently) if atlas does not account for distance / latency already
- yes download link would be rad!

Feel free to create separate issues for mentioned features at your discretion.

**Comment by kdembler** [comment]
This list seems a bit out of date at this point. We're gonna close this for now, let's try to break this down into individual issues with `idea` labels

**Comment by traumschule** [comment]
Still got this tab open and want to create follow-up issues for some mentioned ideas.
