### ISSUE TITLE
Video player UI design tokens update

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2283]
**Player control:** 

- [x] Changed icon and text colour from “Core/Neutral/50/Default” to “Text/strong”
- [x] Changed hover state background from “Core/Neutral/700/Lighten” to “Background/Strong/Alpha”
- [x] Changed “Pressed” state background from “Core/Neutral/800/Lighten” to “Background/Default/Alpha
- [x] Changed “Focus” state border from “Core/Neutral/700/Lighten” to “Border/Muted/Alpha”
- [x] Changed “Disabled” state to “Text/Default/Strong”

**Player tooltip:**

- [x] Changed text colour from “Core/Neutral/50/Default” to “Text/Strong”
- [x] Changed background colour from “Core/Neutral/500/Darken” to “Background/Default/Overlay”

**Player volume control**

- [x] Changed “Default” state to text/strong
- [x] Changed “Hover/Active” fill from “Core/Neutral/700/Lighten” to Background/Default/Strong/Alpha”
- [x] Changed “Hover/Active” icon colour to “Text/Strong”
- [x] Focus & Disabled: Changed icon colour to “Text/Strong”

**Player UI controls:** 

- [x] Changed all icons colour to Text/Strong

**Settings header:**

- [ ] Changed text colour to Text/Default
- [ ] Changed icon colour to Text/Strong
- [ ] Changed divider colour to Divider/Bottom

**Setting group list item:**

- Default: 

- [ ] Changed label text colour to Text/Strong
- [ ] Changed value colour to Text/Default

- Hover/Pressed:

- [ ] Changed background colour to Background/Default/Strong/Alpha,
- [ ] Value + Label colours to Text/Strong

Disabled:

- [ ] Changed color to Text/Default/Strong

**Settings list item:**

Default: 

- [ ] Changed text colour to Text/Default and Text/Strong 
- [ ] Changed chevron colour to Text/Strong 
- [ ] Changed value colour to Text/Default

**Hover/Pressed:** 

- [ ] Changed label colour to Text/Strong 
- [ ] Changed background colour to Background/Default/Strong/Alpha

Disabled: 

- [ ] Changed text colour to Text/Strong

**Comment by TCzechowski** [comment]
Forgot I already created that issue 🤦‍♂️  Please ignore and close this 😅

**Comment by kdembler** [comment]
Thanks for the detailed changelog!

**Comment by kdembler** [comment]
@dmtrjsg Why was this closed?

**Comment by dmtrjsg** [comment]
@kdembler based on [prev comment](https://github.com/Joystream/atlas/issues/2283#issuecomment-1066457723) ☝️

**Comment by kdembler** [comment]
But I think we actually closed the other issue, this one has estimate already
