### ISSUE TITLE
Comments: Notifications

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2284]
### Content

Based on discussion and agreements from https://github.com/Joystream/atlas/issues/2087

Channel owner notifications on comments

### Scope

- [ ] CO gets notified about replies to my comments
- [ ] CO gets notified about new comments under my videos

### Out of scope
- Interaction with notifications

**Comment by TCzechowski** [comment]
Added 2 notifications.

Figma file:
https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=1083%3A55010

**Comment by kdembler** [comment]
Looks good 👍

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2284?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
