### ISSUE TITLE
Comments: Enable / Disable Comments

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2286]
Based on discussion and agreements from https://github.com/Joystream/atlas/issues/2210

---

### User stories
1. As a channel owner, I want to enable or disable the comments section for my videos, separately.

**AC**
- [ ] Enable/ disable comments switch added to studio for video upload and editing. [Figma Link](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)
- [ ] Enable/ disable comments for minted video. [Figma>](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)
- [ ] Disabling the comments section does not allow for posting new comments under this video and hides any existing comments.

- [ ] Viewer side when comments were disabled > https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411%3A219280

**Comment by TCzechowski** [comment]
I've added enabling/disabling comments in video settings, but it is just adding a small section in currently existing flow in Figma. We do have existing user stories for uploading a new video, editing an existing one, and editing minted video, and all of those will have the comments section included, so it didn't make sense to me to create a separate User story (flow in Figma) for that section.

Designs:
[New video - Expanded (+ new video)](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)
[Editing minted video](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753)

![image](https://user-images.githubusercontent.com/22870059/159491594-9049de6b-b9a4-40c0-875b-da05bc1a3c53.png)

**Comment by dmtrjsg** [comment]
Can we just change Don't allow comments -> Disable comments @TCzechowski

**Comment by TCzechowski** [comment]
@dmtrjsg sure, done

**Comment by dmtrjsg** [comment]
Guys, could not find the link to the viewer side of the equation. I think we wanted to show smth like comments was disabled by channel owner? can you pls help find it

@toiletgranny @TCzechowski

**Comment by toiletgranny** [comment]
There you go, @dmtrjsg: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411%3A219273

@TCzechowski When you have a moment, can I ask you to include the above link somewhere in the user story for disabling the comments section in the Video workspace? 🙏

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2286?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
