### ISSUE TITLE
Block Edits for Video for Minted NFT

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2297]
**AC:**
- [ ] Disable all fields video edit fields as per design
- [ ] Separate VideoForm component into smaller component for input section (split to be figured out)

Block edits in video workspace when NFT is minted for the video

[Originating from this design ticket>](https://github.com/Joystream/atlas/issues/2168)

Figma: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2174%3A75868

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2297?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
