### ISSUE TITLE
Update publisher video tile to support Auction + buy now scenario

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2301]
![image](https://user-images.githubusercontent.com/31144205/158603927-98a772ef-d922-4a42-876a-646621f9202b.png)
- Publisher video tile should support scenario where there is an auction + buy now and display two separate pills with icons
- Wording in pill with time when there is less than a minute left is changed to "< 1 min"
All changes visible here in video tile docs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3630%3A116415

**Comment by kdembler** [comment]
Really like the change to `< 1 min` but aren't all those pills a little bit obtrusive on the thumbnail? Feels like covering a substantial portion of it and thumbnails are super important for conversion

**Comment by dmtrjsg** [comment]
Thinking we may want to do the pills with "<1hr" indication. This needs to be refreshed.

**Comment by dmtrjsg** [comment]
That was since deprecated. closing.
