### ISSUE TITLE
Explore Auction step page adjustments

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2308]
## Context 

A recent discussion on rocketchat brought to our attention a new perspective on both English and open types of auctions.
After a brief Thursday meeting, we decided to prepare explorations of two solutions to the discovered problem.

## Scope

Details are in Loom walkthrough on all changes [Link > ](https://www.loom.com/share/a1af69f07cd24011a1903e3b93b12de8)

AC:
- [ ] Auction type selector updated to Open and Timed
- [ ] Timed auction has extra field for date range - Ending Date
- [ ] specific day/ shortcuts date pickers 
- [ ] Display starting date on auction confirmation page (last step before setting live)
- [ ] Update tJOY text fields (auction&buy now) to look the same as they do in purchase view (tJOY icon on the left, USD price in the pill on the right)

## Design

Changelog link: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace

**Comment by KubaMikolajczyk** [comment]
🎥 I prepared two prototypes with two different solutions and walked through them in this video update: https://www.loom.com/share/033a4ffbba644e4595da756306dfba71

#### If you want you can also go through them yourself 👇
Prototype 1️⃣  : https://www.figma.com/proto/xm6vBdSnQDroc57rGfGtPM/Video-workspace?page-id=1600%3A94337&node-id=2462%3A158541&viewport=490%2C48%2C0.63&scaling=scale-down&starting-point-node-id=2462%3A158541
Prototype 2️⃣ : https://www.figma.com/proto/xm6vBdSnQDroc57rGfGtPM/Video-workspace?page-id=1600%3A94337&node-id=2464%3A160975&viewport=490%2C48%2C0.63&scaling=scale-down&starting-point-node-id=2464%3A160975

**Comment by dmtrjsg** [comment]
Thanks for putting this together, after comparing side to side I'm certainly in favour of the second option, 2️⃣ 👍 .

**Comment by KubaMikolajczyk** [comment]
The majority both on rocket chat & here voted for solution 2️⃣ 
Action item: Implement feedback from Adam to designs and update designs respectively.

**Comment by KubaMikolajczyk** [comment]
All designs/ flows & RWD updated with new changes.
Video update 3 min: https://www.loom.com/share/a1af69f07cd24011a1903e3b93b12de8
Link to changelog: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1378%3A93428

**Comment by kdembler** [comment]
Looks good 👍
