### ISSUE TITLE
Update the Dialog (Modal) component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2312]
**AC:**

- [ ] Make sure positioning, sizing, margins, and overflows are implemented correctly
- [ ] Update animation if needed
- [ ] Add corner radii to dialog

The goal of this task is to 
1. Update the Dialog component based on the designs, docs, and changelog which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6261%3A134667). Please note that this component utilizes a new set of design tokens for corner radii. A separate GitHub issue for that can be found here: https://github.com/Joystream/atlas/issues/2273. 
![image](https://user-images.githubusercontent.com/35307309/158852664-cece098e-dfd4-4a49-ad97-26aa72a41b4d.png)

2. Update the "Modal" component's implementation based on new documentation in Figma. A reminder that so far, there was no explicit design documentation for the behavior of _modal content_ in Atlas therefore I sense that support from @kdembler might be needed in translating the design docs into actionable tickets for engineers. The docs in Figma attempt to capture and document the current usage of modals in Atlas while taking the opportunity to propose new solutions and improvements. 
![image](https://user-images.githubusercontent.com/35307309/158853011-1bd3a724-1b13-4483-bc99-bd7d28e30ed8.png)
![image](https://user-images.githubusercontent.com/35307309/158854402-d0bb10af-0efd-4bdf-976c-48f48d7befcf.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2312?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
