### ISSUE TITLE
Introduce an Alert dialog component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2313]
**AC:**

- [ ] Create new Alert/Confirmation dialog component that uses the existing dialog
- [ ] Use this new component inside `useConfirmationDialog` hook

The goal of this task is to introduce an Alert dialog component based on the designs and docs which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6261%3A134667). Please note, that the Alert dialog component is just an encapsulation of the Dialog component with predefined properties, contents and usage guidelines on top of it.

![image](https://user-images.githubusercontent.com/35307309/158855703-8be8dc53-a92f-4ea8-afba-a1584b77c58c.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2313?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
