### ISSUE TITLE
Update the Video info section on the Video page to support showing/shrinking long descriptions

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2315]
Based on https://github.com/joystream/atlas/issues/2086#issuecomment-1041464659, the goal of this task is to update the Video info section of the Video page to support hiding overly long video descriptions by default, and to introduce a few other minor stylistic improvements using this opportunity.

Designs, docs, and the changelog [can be found in Figma](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2528%3A332970).

![image](https://user-images.githubusercontent.com/35307309/158861058-bffbd6bd-93d1-414c-8832-d16402d5afe6.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2315?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
