### ISSUE TITLE
Update the NFT widget component to add loading state for timers and support more scenarios for displaying auction dates

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#2329]
We need to implement a loading state for the timers in the Nft Widget as the current block data is sometimes loaded after the nft data arrives.

https://user-images.githubusercontent.com/51168865/159445554-372618cb-c7fc-48b9-bbed-d2e5fbe4ef0a.mov

**Comment by eldiegod** [comment]
cc @toiletgranny @kdembler

**Comment by toiletgranny** [comment]
Would you guys mind jumping on a quick Tandem call to help me understand which data is available at which point? Perhaps we could try to come up with a solution on the spot and have.

**Comment by toiletgranny** [comment]
The outcome of this task, as agreed in #2333, is to:

### NFT info item
Update the NFT info item component based on the designs, docs, and changelog [which can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A123284).

![image](https://user-images.githubusercontent.com/35307309/159918816-7f134447-f56c-4e75-85c5-c8af3d690d41.png)

### NFT widget
And then update the NFT widget component based on the designs, docs, and changelog [which can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A112135).

![image](https://user-images.githubusercontent.com/35307309/159919191-a15a3189-d995-4f3e-9006-6fcabf3a6bec.png)
