### ISSUE TITLE
 Update the NFT tile component to add loading state for timers and support more scenarios for displaying auction dates

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2345]
As agreed in https://github.com/Joystream/atlas/issues/2333, the goal of this task is to update the NFT tile component based on the designs, docs, and changelog [which can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3630%3A139541).

![image](https://user-images.githubusercontent.com/35307309/159952227-999a6efd-6168-40a4-bff7-0cd6fc6e1570.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2345?planning-poker) with ZenHub @drillprop @rafalpawlow
