### ISSUE TITLE
Channel Payouts: High Fidelity Mockups (HiFi), Documentation & Handover

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2365]
This phase includes activities such as:
- creating Figma mockups from scratch, this time ensuring a proper design work hygiene (through naming layers, setting up constraints, ditching all unnecessary local components, etc.),
- creating/updating global components and their documentation,
- creating designs, documentation, and prototypes for all user stories,
- creating designs for responsiveness,
- identifying and designing for empty states, error states, and edge cases,
- applying visual finishing touches,
- etc.

The expected outcome is:
- a final video walkthrough of the Figma file and a prototype for engineers,
- links to Figma designs and prototypes,
- separate GitHub issues created for changing or introducing new global components.

**Comment by TCzechowski** [comment]
Final Video Walkthrough:
https://www.loom.com/share/2297c250d7f3488fbfe7780f0a504de1

Figma:
https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/Channel-payouts-Hi-Fi?node-id=1498%3A15095

**Comment by dmtrjsg** [comment]
We'd need to cover 2 more cases:

- Channel payouts blocked by Proposal
- Minimum/ Maximum Cashout limits imposed by same proposals have to be adhered to (at the point of Claiming Rewards)

Here's the respective ticket in Pioneer: 
- https://github.com/Joystream/pioneer/issues/3073

**Comment by toiletgranny** [comment]
@dmtrjsg I'm afraid I'm going to need some more details to tackle this, as I'm not sure where to look for them in the Pioneer GitHub issue you linked. Would it make sense to arrange a separate meeting to discuss this?

**Comment by toiletgranny** [comment]
@bedeho We just jumped off a quick sync with @dmtrjsg in regards to the above. There are a few clarifying questions we would appreciate if you could take a look at.

![image](https://user-images.githubusercontent.com/35307309/173825620-b8af5a3b-05d9-4972-afe8-fba313d4954d.png)
(screen from the Pioneer)

### "Channel payouts blocked By Proposal"
- What do we mean by the "channel payout"? My assumption is that it's what we're referring to in Atlas as a "reward from the council", but I want to double-check because it sounds like it could also be withdrawing funds from the channel account into a member account.
- If my above assumption is correct, what would that mean for me, as a channel owner, to deal with a blocked payout? Let me explain. First, a reminder that we agreed to make it possible not to claim the entire council reward [(a Figma screen to illustrate that view)](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/Channel-payouts-Hi-Fi?node-id=1603%3A28562) And so, in that context, if I have unclaimed JOY tokens from a previous payout, and a new one comes in as blocked, am I, as a channel owner, still able to claim JOY tokens from the previous payout?
- What would be the reason for the council to block a payout? How often would we expect that to happen? For how long would that payout be locked? Please, feel free to disregard these questions if you don't believe there's any value in explaining them to me at the moment. 

### "Minimum/ Maximum Cashout limits"
Knowing both fields are optional in Pioneer, how often would we expect the council to actually set min/max cashout limits? For what reason? Knowing this would help prepare a better experience on the Atlas side.

**Comment by bedeho** [comment]
> What do we mean by the "channel payout"? My assumption is that it's what we're referring to in Atlas as a "reward from the council", but I want to double-check because it sounds like it could also be withdrawing funds from the channel account into a member account.

No, only the former. 

> am I, as a channel owner, still able to claim JOY tokens from the previous payout?

No, you are blocked, everyone is blocked until such payouts become unblocked. This blocking feature is basically a sort of dead-man switch where the council can just stop everything going on, in case they suspect something has gone wrong.

> What would be the reason for the council to block a payout? How often would we expect that to happen? For how long would that payout be locked? Please, feel free to disregard these questions if you don't believe there's any value in explaining them to me at the moment.

I guess the prior answer sort of covers is. We hope it happens very rarely, but once it happens, it seems like it could easily take days to resolve in a realistic a scenario if something has gone terribly wrong.

> Knowing both fields are optional in Pioneer, how often would we expect the council to actually set min/max cashout limits? 

This is just very hard to say anything concrete about :/

# Note on optionality

Be aware that _every field_ in this proposal should be optional, this because it is a sort of all-in-one proposal which carries control inputs which impacts payouts in general. Design-wise, this means more things needs to be optional. @thesan Should be able to help you pin down what fields or combinations of fields should have an on-off control by looking at the proposal signature.
