### ISSUE TITLE
[USERSNAP] -- Field form validation for video upload

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2375]
@dmtrjsg commented on [Tue Mar 29 2022](https://github.com/Joystream/pioneer/issues/2725)

**Sender**: admin@mlcrip.net
**Taken at**: https://play.joystream.org/studio/video-workspace
**Fields**:
- Expected Result: -- both ff and chrome --
- Houston, we have a problem.: upload button does not work ?

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7ec572af-e782-469a-9acb-e6a7dd2af3fe-annotated_d4f2e3b1-3649-4386-84ed-59ea38a828cf.png?etag=ee1ce65b831623d019347b380f6a343c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/7ec572af-e782-469a-9acb-e6a7dd2af3fe-annotated_d4f2e3b1-3649-4386-84ed-59ea38a828cf.png?etag=ee1ce65b831623d019347b380f6a343c)*

**Browser**: Chrome 99 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x722
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/e1be9ea3-16dd-484b-8ffb-95b567d6e973_screen_recording_d9ed7f01-c615-4da0-956a-81191549005b.webm?etag=fe30120ac22902da5aff18ee1bb667c1-2)**
**[Open #14 in Usersnap](https://app.usersnap.com/l/feedback/5dcb6652-cbc0-4c1c-bba7-5059db0ddc95?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by kdembler** [comment]
This isn't a bug, maybe a UX one. The user in the recording didn't provide the video title, that's why the button was disabled. I think this is a great example of why we need to rethink our approach to form validation - user is lost, not knowing which field is missing. IMO, ideal behaviour in that case would be enabled Submit button that focuses any input if missing and shows an error message.

cc @toiletgranny

**Comment by dmtrjsg** [comment]
100% and same question I raised in the related bug. https://github.com/Joystream/atlas/issues/2376

**Comment by kdembler** [comment]
I think we could potentially close this one and make a note in https://github.com/Joystream/atlas/issues/2056 that this should be included in the scope

**Comment by traumschule** [comment]
> user is lost, not knowing which field is missing. IMO, ideal behaviour in that case would be enabled Submit button that focuses any input if missing and shows an error message.

Probably similar to what you meant: The form could include `{ error_message }` somewhere which then can be defined by form validation handler, or open a modal via callback to be more obvious.

Would this be the kind of issue you would be willing to assign to the community in the spirit of https://github.com/Joystream/joystream/issues/3473?

**Comment by toiletgranny** [comment]
Addressed in https://github.com/Joystream/atlas/issues/2692#issuecomment-1135740582 and will be addressed in https://github.com/Joystream/atlas/issues/2738
