### ISSUE TITLE
[USERSNAP] I have been unable to sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2387]
@dmtrjsg commented on [Tue Mar 29 2022](https://github.com/Joystream/pioneer/issues/2718)

**Sender**: tomli2025ac@gmail.com
**Taken at**: https://play.joystream.org/studio/videos
**Fields**:
- Expected Result: I have been unable to sign in
- Houston, we have a problem.: I can&#39;t sign in

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b8041183-8276-4806-8421-36d4b9129d98-annotated_c021239b-d7b5-4c7d-9c65-30e2376650d7.png?etag=4dcc54ebf937014b35f8138e2ab6d724)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b8041183-8276-4806-8421-36d4b9129d98-annotated_c021239b-d7b5-4c7d-9c65-30e2376650d7.png?etag=4dcc54ebf937014b35f8138e2ab6d724)*

**Browser**: Edge (Chromium) 99 (Windows 10)
**Screen size**: 1440x900
**Browser size**: 1440x781
**[Open #12 in Usersnap](https://app.usersnap.com/l/feedback/0fca6036-aa66-4fac-8e8d-474877128666?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@kdembler hey buddy, is this Edge support or smth else?

**Comment by kdembler** [comment]
It should work, not really sure what this is about
