### ISSUE TITLE
Creator Tokens Design Brief

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2400]
# Purpose

Allow creators to align their most passionate community members around the future creative activities of the creator and the community, by pooling the resources of the community and sharing the upside. This is particularly impactful for creators with an ambitious plan for growing the scope and scale of their activities before they have garnered a big audience. By sharing the upside, the community members become natural evangelists and collaborators on making the creator as successful as possible in the future. Lastly, it also creates a sort of scouting market where third parties with a keen eye for talent and projects will start searching for promising and undervalued creators, and providing them financial, operational and marketing support.

# System

## Terminology

A specific creator token is herein denoted by $CRT, as distinct from the Joystream native token $JOY.

## Overview

As the technical description of the system constraints are quite dense, this section attempts to provide a higher level overview to make it easier to establish a small mental model to build upon.

- Owner of a channel can issue a $CRT, if one does not already exist.
- $CRT is owned _as an account holder_, not as a member, curator or channel. So even if your channel issued a $CRT, as a member who owns that channel, you don't own such tokens by virtue of owning the channel, it's by virtue of the accounts you have.
- A given account can hold an unlimited different types of $CRT simultaneously.
- It starts out in one of three major modes
  - Idle: nothing special going o
  - Sale: a certain quantity of tokens can be purchased by the public at stated terms, for $JOY. When a sale is done, one goes back to Idle automatically.
  - AMM: it is possible to buy $CRT from the blockchain, at a dynamic price determined by the blockchain, or alternatively sell your $CRT as a holder back to the blockchain. Creator can take us back to Idle mode if they are willing to buy back all $JOY from the AMM.
- Tokens allocated during initial issuance, or during sale, may be subject to a vesting schedule specified by the issuer, read more here: https://github.com/Joystream/joystream/issues/3382#issuecomment-1087544037
- While a $CRT has been issued, all $JOY revenue arriving to the channel account of the creator, whether from NFT sales, NFT royalties or council payouts, cannot be withdrawn by the channel owner, instead, a so called _revenue split_ must be triggered.
- Regardless of the mode above, the creator can trigger a _revenue split_ , which takes a certain amount `A` of $JOY which exists in the channel account (creator picks `A`, does not need to be everything), and allocates a certain predefined (at time of  issuance) percentage `S` to the token holders and `100 - S` to the channel owner. Any $CRT holder can claim their share of `A*(100-S)/100` by locking up their $CRT for a certain period of time. $JOY is distributed pro-rata during such a split, and any unclaimed $JOY is simply returned to the channel account. During this locking time, $CRT locked cannot be transferred to anyone else.
- Regardless of the mode above, the creator can claim a certain number of new $CRT per period of time, sort of like a "living wage", but only if this was decided during the initial token issuance.
- The issuer can choose to issue issue the token with limits about who can receive it. This limit applies both during buying during sale, buying from AMM or just a normal transfer between two token holders. The issuer can later only increase the number of possible recipients, never reduce.
- When tokens that are bought during a sale, or tokens the creator assigns to themselves during issuance, can be subject to a certain limits about when they can be transferred, this is called vesting. But be aware that they can be used to receive $JOY as part of revenue splits.

### Owning $CRT

The most substantial technical fact that must be noticed by the designers is that: you do not own $CRT _as a member_, you own it as _an account holder_, just like $JOY. That is, you can hold creator tokens just by having a raw Joystream account, without having a membership, and even if you had one or more memberships, there is no principle associated between the two. This applies both for the creator who issues the tokens, and for the general audience. The creator does not own the tokens _in their channel_ or _in their creator membership_, its just lives in one of their accounts.

This does conflict a little bit with how asset ownership works in Atlas now, which focuses on a member who owns NFTs. It also would for example make it difficult to do things like displaying flaire symbol besides the profile of a member in the context of a channel to signal them holding the token, for example in the comment field, which could be an interesting feature at some point down the road. The simplest workaround, which I have already cleared as being "low cost", is to just make ownership of $CRT at the membership level, not accounts, but we need clarity as soon as possible.

### AMM always on?

In the current scheme, the AMM is not always on, this means there is no on-chain price indicator, which will make it harder to have always-on indication of what each $CRT is worth. Now, in the future, the $CRTs may be trading on other venues, e.g. on DEXs via interoperability, however, that will be a very complex integration to pull off product wise, it may be very valuable to have an integrated pricing mechanism for the foreseeable future.

The outstanding question for making this work is how this AMM economically interacts with any ongoing Sale. Do you pause the AMM? do they run in parallel, does that entirely make sense? TBD. but more product constraints could help.

## Initial Requirements

`This can still be changed if good opportunities are identified which are not too hard to implement`.

https://github.com/Joystream/joystream/issues/2362#issue-867837174

Importantly, as work begins, these requirements may begin to become more and more stale, so we must try to reconcile where we are once a full implementation has been completed. In fact, it is already the case that there are certain permissions which have been introduced which may prevent a channel owner from doing certain things at certain times, as a result of the actions of content curators, however, we will ignore this for the time being, as it is largely tangential to the core business domain.

# User Stories

This scope is .... shall we say ... not small.
Big prize to whomever can cut this down :champagne: :champagne: :champagne:.

## Channel Owner

- I would like to issue a $CRT.

## $CRT Issuer

- (X) I would like to see the state of my $CRT, e.g.
  - list of holders:
  - list of allowed holders, if transferability policy is permissioned.
  - token distribution across holders (pie chart?)
  - price: only possible if there i a live AMM.
  - price chart?: only possible if there is a live AMM.
  - current major state
  - history state events: splits, sales, AMMs, return to idle.
- I would like to see the history of all $CRT transfers.
- I would like to trigger a sale of an idle $CRT.
- I would like to trigger return to idle state for a sale which has ended.
- I would like to trigger a revenue split.
- I would like to end a terminated revenue split.
- I would like to add a new recipient to the list of acceptable holders, if $CRT is permissioned.
- I would like to know when a revenue split has timed out.
- I would like to know when a sale has timed out.
- I would like to get notified when someone buys or sells to the AMM.
- I would like to get notified when someone buys during an ongoing sale.

## Viewer

- I would like to see whether a given channel as a $CRT, with some basic facts, basically like $CRT issuer above (X).
- I would like to see whether a video I am watching is from a channel which has $CRT.
- I would like to purchase tokens from the AMM for a $CRT.
- I would like to purchase tokens from the Sale for a $CRT.
- I would like to get notified if anyone I follow has issued a token or initiated a sale.
- I would like to see a list of ongoing sales.
- I would like to see a list of newest issued $CRT.

## $CRT Holder

- I would like to see my portfolio of $CRT holdings, across all creators.
- I would like to transfer $CRT to a beneficiary.
- I would like to participate in an ongoing revenue split.
- I would like to sell $CRT to an AMM.
- I would like to unlock my tokens from a concluded revenue split.
- I would like to know when there is an ongoing revenue split or sale for a $CRT I hold.
- I would like to know when I have locked tokens for a revenue split which has concluded.
- I would like to be notified when a revenue split is initiated for a $CRT I hold.
- I would like to be notified when a revenue split is concluded for a $CRT I hold.
- I would like to be notified when an AMM is initiated for a $CRT I hold.

# Resources

- Similar
  - https://rally.io/
  - https://tryroll.com/
  - https://www.deso.org/
- Inspo: https://twitter.com/trends_vc/status/1401947070462763012
- Understanding bonding curves
  - https://www.youtube.com/watch?v=bBpa9395b4Q
  - https://www.youtube.com/watch?v=14hH0dKktvc

**Comment by dmtrjsg** [comment]
Design is covered by #2402
