### ISSUE TITLE
Creator Tokens — Owner & Issuer: Design

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2405]
## Context

Design epic covering CRT owner & issuer side of Creator Tokens.

### Channel Owner

- I would like to issue a $CRT. 
- Base denomination is hard coded at [18 symbols](https://github.com/Joystream/atlas/issues/2503#issuecomment-1101191201)

### $CRT Issuer

- (X) I would like to see the state of my $CRT, e.g.
  - list of holders:
  - list of allowed holders, if transferability policy is permissioned.
  - token distribution across holders (pie chart?)
  - price: only possible if there i a live AMM.
  - price chart?: only possible if there is a live AMM.
  - current major state
  - history state events: splits, sales, AMMs, return to idle.
- I would like to see the history of all $CRT transfers.
- I would like to trigger a sale of an idle $CRT.
- I would like to trigger return to idle state for a sale which has ended.
- I would like to trigger a revenue split.
- I would like to end a terminated revenue split.
- I would like to add a new recipient to the list of acceptable holders, if $CRT is permissioned.
- I would like to know when a revenue split has timed out.
- I would like to know when a revenue sale has timed out.
- I would like to get notified when someone buys or sells to the AMM.
- I would like to get notified when someone buys during an ongoing sale.

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk adding this reference here wrt base units supply : https://github.com/Joystream/atlas/issues/2503#issuecomment-1101191201
