### ISSUE TITLE
Creator Tokens — Owner & Issuer: High Fidelity Mockups (HiFi), Documentation & Handover

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2410]
This phase includes activities such as:
- creating Figma mockups from scratch, this time ensuring a proper design work hygiene (through naming layers, setting up constraints, ditching all unnecessary local components, etc.),
- creating/updating global components and their documentation,
- creating designs, documentation, and prototypes for all user stories,
- creating designs for responsiveness,
- identifying and designing for empty states, error states, and edge cases,
- applying visual finishing touches,
- etc.

The expected outcome is:
- a final video walkthrough of the Figma file and a prototype for engineers,
- links to Figma designs and prototypes,
- separate GitHub issues created for changing or introducing new global components.

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk the copy edits are added to t[his page: ](https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=3936%3A297666)

**Comment by KubaMikolajczyk** [comment]
FInal overview for CRT Creator | Creating CRT, Editing CRT page, Dashboard
🎥 Loom: https://www.loom.com/share/78c2304cfaad4b6895ba28f0829d2a5c
📄 Figma: https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=278%3A69650

**Comment by bedeho** [comment]
Awesome work, just staggering how well documented and clear this is, I hope the engineers will enjoy building this. I don't really have anything to add, except
- `allowlist` => `whitelist`
- be aware that when the runtime starts enforcing some limits on what the vesting schedule and other things can be, then this may undermine the "default" options you are presenting, like risky, safe, etc. What do you do if some or multiple of them are not valid depending on what runtime has as limit? This is obviously a broader topic, as these limits are still being pinned down, and there will be separate limits pertaining to issuing, starting sales, starting AMM, etc. Just keep it in mind.
- we may already have covered this, but how do we allow users to get on the whiteliest if they currently are not? is there just some link that can be specified that the creator can control, so sending them to a Discord or Form or something?

**Comment by KubaMikolajczyk** [comment]
@bedeho Thank you I'm glad you liked it :)
- As per allowlist and whitelist - I tried to propose this change after discussion with Adam about the meaning behind the "whitelist" term and reading this article: https://www.linkedin.com/pulse/allowlist-blocklist-better-terms-everyone-lets-use-them-rob-black/
The naming is up to you here let me know if you would rather keep it as whitelist 100%?
- Yes we will have to look more carefully into it when we will know those limits - for now those timeframes for preset options should be treated as placeholders
- We only explored an option for a Viewer/Buyer persona to click on a button on the viewer side to know more about how to get on whitelist - now on the creator side we will have to give creator an option to edit those information. I will be working on whitelisting (or allowlisting :3) from today so this is the next thing coming

**Comment by bedeho** [comment]
> The naming is up to you here let me know if you would rather keep it as whitelist 100%?

I may be missing what this article is saying, but I would bet any amount of money on the fact that a greater share of people will correctly understand what a whitelist is vs. an allow list in our context, it wont even be close. So if that is the point, then I have to disagree.
