### ISSUE TITLE
Post-mainnet idea: UI modules managed by users

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#2414]
The Atlas UI can only show so much information at once before it becomes untenable. There is an entire world of browser extensions and other customizations that sit on top of the YouTube UI and cater to certian varieties of users.
What would be really cool at some stage is a sort of marketplace or system where user can easily access and load such "extensions".

Example: https://chrome.google.com/webstore/detail/tubebuddy/mhkhmbddkmdggbhaaaodilponhnccicb

**Comment by dmtrjsg** [comment]
@mochet I am not sure if it is up to us to build it, but thanks for the idea.
