### ISSUE TITLE
Handle whitelisted auctions for viewers

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2419]
If the NFT is on an auction that has a whitelist and the viewer is not included in that whitelist, we need to disable placing a bid/buying and show an appropriate message. Design coming soon

_Actually,_ this needs to be handled outside of NFT widget as well, for example the "Place bid" option should not show up in the NFT/Video tile.

**Comment by toiletgranny** [comment]
Designs and docs for this [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2077%3A112135), in the “Whitelisted sale” section of the documentation.

![image](https://user-images.githubusercontent.com/35307309/161743623-b74d040c-c8db-4c8e-a0d6-dbcc52baa405.png)
