### ISSUE TITLE
Reply to comments

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2443]
Reply to comments [link](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2213%3A140576)

- [ ] Thread
- [ ] All replies are always sorted by their publication date, starting with the newest ones.

Out of scope:
- [ ] ~Subthread~

covered in https://github.com/Joystream/atlas/issues/2522

**Comment by toiletgranny** [comment]
>  All replies are always sorted by their publication date, starting with the newest ones.

@dmtrjsg There might have been a misunderstanding about the above. My recommendation was to have replies sorted chronologically, starting with the oldest ones on top. I had a typo in the user story description in Figma, which I already fixed. Hope you're ok with this sorting method.
