### ISSUE TITLE
Comments section

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2449]
Design: https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2555%3A452099

**AC:**

- [ ] Loading state
  - [ ] Sorting disabled 
  - [ ] 4 comments in loading state
- [ ] Comments section disabled state (https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2411%3A219280)
- [ ] Data fetching (we can do mocked data if QN not available yet)
- [ ] Display all top-level comments by default
- [ ] Handle guest user https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2431%3A214814

**Out of scope:**
- Sorting (#2442)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2449?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
