### ISSUE TITLE
Review and update Button component

### ISSUE THREAD

**Issue by rafalpawlow** [Joystream/atlas#2463]
**Scope:**
- Include changes from #2123
- Make sure `textOnly` and `iconOnly` variants are needed, probably we can get rid of them and "compute" those values
- Rethink component props and API, see what variants make sense. Best to discuss with the dev team before doing the work
- Figure out what's the situation with `IconButton`, do we need it or use regular button with `iconOnly`
- Make sure all the variants look the same as in Figma
- Clean up storybook stories

---

### Description

We have mismatches between design and implementation, especially in the teritary variant. Please make sure storybook works well for all variants, especially for `textOnly` variant.

### Figma link

https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A6243

### How urgent this is?

Not a blocker, but still worth considering

**Comment by eldiegod** [comment]
> Make sure textOnly and iconOnly variants are needed, probably we can get rid of them and "compute" those values

what does "compute" mean here?

for the record we should remove `IconButton` I marked it as deprecated as `IconButton` is a separate implementation from our buttons and makes it so we have to maintain 2 components everytime we add features to button
