### ISSUE TITLE
Channel Payouts: Testing v2

### ISSUE THREAD

**Issue by TCzechowski** [Joystream/atlas#2464]

**Comment by TCzechowski** [comment]
@dmtrjsg @toiletgranny @KubaMikolajczyk 
**Test card:**
https://www.notion.so/joystream/Creator-payouts-v2-a75df836d43a425ab2f76022b2b79e6c

**Comment by TCzechowski** [comment]
We've already discussed the outcome of the tests so I probably won't write a whole report here, but key findings / recommendations / etc.

1. Just now -> Specific timestamp
2. Payout total -> We def. need more clear label, or — at worst — a tooltip.
3. "Welcome to Payments" -> A blank screen is too much. A modal instead?
4. Iterate on empty states of widgets to give the user more context


## **Users to be paid out:**
5CAZtGnnkLGadGiieMp6M6ng631gw5F48oiLuif8xGARrjXk
5HVxLAskxQZiQMJwfMWDGQfK4beevP17zjYm8PAaA7GTZqdW
5E9ZTTBh4p7vvrkJczqtYVMggimVhW3KJ83SdtBPy3TenANs
5CfjBwVfBxrGxNF6PWt9Fh5A6KicPMptbR3AQ9MUUFkzsMSm

CC @dmtrjsg

**Comment by dmtrjsg** [comment]
Requested $30 TJoys with @bwhm 

to the aforementioned wallets
