### ISSUE TITLE
Reintroduce NFT collectors in channel view

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2479]
We've hidden NFT collectors inside the channel view because the data for it wasn't available. This can be done now (see https://github.com/Joystream/joystream/pull/3563). Let's bring it back and integrate with real data

**Comment by dmtrjsg** [comment]
<img width="612" alt="Screenshot 2022-04-21 at 11 47 18" src="https://user-images.githubusercontent.com/93924525/164442356-de4e17db-8563-4612-9fd0-27e29f74669c.png">
