### ISSUE TITLE
Atlas Problems Tracking

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#25]
This issue is meant to be the central source to gather all problems and observation coming up while building Atlas. 

I suggest we keep each comment / problem in its own comment to keep this issue more organised.

**Comment by kdembler** [comment]
@Gamaranto I believe the thing you've mentioned here is already fixed, right?

**Comment by fcescob** [comment]
Correct 

> @Gamaranto I believe the thing you've mentioned here is already fixed, right?

**Comment by kdembler** [comment]
Okay, closing this then as the problem was taken care of, for next ones let's open separate issues
