### ISSUE TITLE
Separate Atlas brand

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2512]
# Background
Currently, the product is

* using logo and brand identity indistinguishable from the project.
* is hosted on a subdomain of the joystream project: play.joystream.org

but at the same time we refer to it as _Atlas_ both internally, on the website and in announcements, social media, newsletters and other communication. This leads to people being a bit confused about what it is, whether it is itself Joystream, and
this lack of distinction has some costs.

1. It becomes less clear that it is intended to be _one_ among many products that people can build on the platform.
1. Confusion in general just lowers clarity of marketing, word of mouth and buyin to the future.
1. Creators will be less clear about who exactly they are giving their content to and who can use it, and under what constraints. Are the terms and conditions with the DAO or Jsgenesis?

As it stands, its clear that there is ample room for Jsgenesis to keep making a very wide range of improvements in the Atlas product post launch, stuff like 

* Orion v2
* Youtube-synch
* Shared data layer
* Creator token?
* Creator analytics
* Fiat onboarding

, etc. Some of these things may go live before mainnet, but executing and iterating on them well will clearly go beyond that milestone. This means these costs (1-3) are going to increase, because this implies that the time horizon for Jsgensis being involved in developing Atlas is clearly expanding, and it may end up becoming an important first application for creators to get involved for a longer period of time than I initially imagined. 

# Proposal
Here is a very humble low effort set of changes we can make to put us on a better path in terms of addressing these costs:

* Put app on separate top level domain, independent from Joystream.
* Give separate logo.
* Consider a name change if it makes sense?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202547954768625) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Oof, that's a big one, although we will need to do this sooner or later. It certainly is confusing that we brand Atlas as "Joystream" in the app, I've raised this before. I'm not sure if those changes are not too drastic for the time being though. 

When you say "Consider a name change if it makes sense?" do you think about name of the app (Atlas) or the name of the app hosted by Jsgenesis (seems to be Joystream atm)? I'm afraid that if we pick some distinct name for Jsgenesis-hosted Atlas, we basically start branding ourselves as a gateway operator and I feel it may be a bit early for that and may create more confusion. Maybe for now we just embrace the "Player" aspect more and say there is "Joystream Player" and "Joystream Studio"? Will need to think some more, sharing early thoughts for now. Curious what others think ;)

**Comment by bedeho** [comment]
> When you say "Consider a name change if it makes sense?" do you think about name of the app (Atlas) or the name of the app hosted by Jsgenesis (seems to be Joystream atm)? I'm afraid that if we pick some distinct name for Jsgenesis-hosted Atlas, we basically start branding ourselves as a gateway operator and I feel it may be a bit early for that and may create more confusion. 

I was actually thinking this, yes ;)

`Joystream Player` sort of exactly gives this feel that _this is the official thing Joystream is supposed to be_, and it just doesnt allow people to let their imagination run free about what this system can become. Also, its a horrible brand :P

I also think that perhaps what we can do is to keep the name of the codebase/assets/standards/repo etc.  `Atlas`, but then we make the first steps to actually distinguish this from an actual customized _deployment_ of this codebase on a particular infrastructure - and that is what we give a new name, call it `fooapp`. So `fooapp` is the customized deployment of `Atlas` that Jsgenesis operates. We don't use `Atlas` in any communication going forward, as only really developers and communtiy people need to understand it as a distinct thing, sort of like Hydra vs. QN.

**Comment by kdembler** [comment]
Gave this some more thought and I agree we probably should do this, maybe sooner than later. However, I think we need to be careful to make sure users understand what this new product is and how it is connected to Joystream. For example, if someone stumbles just upon `fooapp`, do they understand that this is running on Joystream? Also, if we embrace `fooapp` being something jsgenesis operates, do we still ask the community to update the featured content for example? Makes sense when there is "official player" for Joystream, once it's "jsgenesis player" it's a bit different. Also, how much effort do you think we should spend on branding this? Do we just come up with something that works as temporary thing or do we actually spend resources to create proper brand/find good name/make sure it's future-proof?

**Comment by traumschule** [comment]
i think fooapp is a bad name :)

> we basically start branding ourselves as a gateway operator

That seems consequent. What are incentives to invest money for developing a separate app? If it's not a bounty there needs to be a revenue model.

> These are open source products, they are not sold to generate revenue for Jsgenesis or anyone else, they are meant for everyone to use. So they don't get any ROI from them directly. Of course, these apps are the main way people interact with the Joystream system, so indirectly of course it impacts ROI in that sense.

In [that](https://discord.com/channels/811216481340751934/866593771645960223/966331324845658172) sense Joystream invested (their own + funder's money) into that `play` product (with codename `atlas`) without financial incentive. How would anyone (a future gateway provider) compete? Some answers here: https://play.joystream.org/video/20545

![valueflows](https://user-images.githubusercontent.com/31551045/167604778-29ee90ef-1f98-4320-a8dc-bc1b5739143d.png)

i could go ahead and create my own faster `jsbrowser` app for mobile and desktop without reliance on cloudflare and show ads, add a subscription model, premium features, market user behavior and profiles ..

![gateways-flows](https://user-images.githubusercontent.com/31551045/167604796-ea1116bb-72a6-4c01-bfcc-c86a11d2f92c.png)

It is likely that some of Joystream investors / backers speculate on these income streams and already are developing their proprietary products. However it is very valuable for the Joystream brand to provide the community owned `atlas` and it will always stand out as something unique (just like the book).

BTW please never break channel / video links again (like with the non-migration of some assets from sumer to giza).

**Comment by bedeho** [comment]
> That seems consequent. What are incentives to invest money for developing a separate app? If it's not a bounty there needs to be a revenue model.

This is a fair point, but lets try to have a separate issue about this
https://github.com/Joystream/joystream/issues/3738

**Comment by dmtrjsg** [comment]
Estimation ticket is raised: https://github.com/Joystream/atlas/issues/2959
