### ISSUE TITLE
Allow curator to use Atlas as owner

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2515]
# Background
As a continuation of https://github.com/Joystream/atlas/issues/2514

Some channels are owned by curator groups, and curators are able to act as owners of those channels when they are part of those group. Currently it is not possible for such curators to do this in Atlas. Curators also have a set of permissions associated with operating channels on behalf of the group, and these permissions are managed by a special actor called the _curator lead_.

## Runtime
Here is the runtime implementation work

* permissions: https://github.com/Joystream/joystream/issues/3436

# Proposal
Allow curators to use Atlas to operate channels within the permissions they face at any given time, as well as understanding clearly what those permissions are.

Note: this goal is not very urgent, but it would be much more urgent than the channel collaborator featuere enhancement.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202534423562897) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
We would benefit from merging both in one for easier prioritisation for now. Closing 2515 and adding  additional Acceptance criteria to 2514.
