### ISSUE TITLE
Comments: Reply to reply 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2522]
## Context
-  #2443 

This ticket is to add functionality of reply to reply + @ member + notifications

[Design> ](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?node-id=2356%3A392932&t=Sp4tNqkhPmHBC0fK-1)

**Comment by attemka** [comment]
@attemka to check the orion nesting rules
