### ISSUE TITLE
Goodwill warning banner

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2529]
## Context

From time to time, there will be some sort of reason a deployed Pioneer instance is not working properly. I know we are planning some developer related features to allow for diagnostics around this, but also having some consumer facing banner or something warning that "right now things aint working that well, being worked on", can help buy some goodwill when we run into trouble. It can be a manual thing that can be triggered on infrastructure side, and ideally it would not require rebuilding the app. Would require some very light design work.

Same issue in Pioneer https://github.com/Joystream/pioneer/issues/2879

## Scope

@design
- [ ] design overlay to be shown on all pages  (see context for details)

@dev
- [ ] Enabled/disabled wo rebuilding the app

**Comment by dmtrjsg** [comment]
@kdembler can you weigh in on this one?

**Comment by kdembler** [comment]
@bedeho We already have maintenance mode, although you need to go to Vercel and rebuild the app to enable it. Is "Enabled/disabled wo rebuilding the app" really that important?

**Comment by bedeho** [comment]
I think the most important part is just having some sort of communication, not that you don't need to rebuild.

**Comment by kdembler** [comment]
Right so we actually had more discussion around this topic as part of #3001 and we will make it work so that you can actually trigger this "maintenance mode" without rebuild and just by supplying a _magic password_ in the correct field in the app. So I think we can actually close this as a duplicate

**Comment by kdembler** [comment]
It's done
