### ISSUE TITLE
English Auction Bugs and Change Requests

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2534]
- Add Settle Auction for Host to the overflow menu on NFT tiles
- Add Settle Auction Screen for Auction Host (seller) @TCzechowski  to add visuals

**Comment by TCzechowski** [comment]
**Figma file:**
https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1237%3A23354

@dmtrjsg It occured to me that we also need a separate snackbar notification after user settles the auction. Already included it in the Figma file.

![image](https://user-images.githubusercontent.com/22870059/165112976-964b1439-f0a5-471f-b3ec-7ca2e7ac096d.png)
