### ISSUE TITLE
Accessing my profile from publisher experience

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2571]
# Overview
When testing NFT issuing I spotted the fact that one is able to access my profile only from the viewer part of the experience. It's probably because of the fact that when my profile was being designed it was desired to keep viewer and publisher experiences separate. It's worth considering including my profile link also on the publisher side of the experience to allow users to check their NFTs easily after uploading without a need to go to the viewer experience first.

#### Viewer
![image](https://user-images.githubusercontent.com/31144205/165551964-8bcc2ad3-c8b1-40f2-a5c6-02d391901d2f.png)

#### Publisher
![image](https://user-images.githubusercontent.com/31144205/165552043-df18abb5-cfc1-4179-937c-ee65b9ba0afd.png)

**Comment by kdembler** [comment]
Done in the new member dropdown
