### ISSUE TITLE
SIMPLE Image safety

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2581]
## Context
- https://github.com/Joystream/joystream/issues/3685

## Scope
- [ ] Add a "report" or similar sort of button which does not do anything on-chain, but simply allows user to send a ping.
- [ ] Allow app host to maintain a separate resource blacklist (URLs & data objects), which ideally can be updated by operator without taking app offline.

**Comment by dmtrjsg** [comment]
Already captured here: 
- https://github.com/Joystream/atlas/issues/3037
- https://github.com/Joystream/atlas/issues/3002

Closing as duplicate, while transferred this AC to the pointed issues:

"separate resource blacklist (URLs & data objects)"
