### ISSUE TITLE
Work with Joystream address format

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2585]
Update to work with this https://github.com/Joystream/joystream/issues/181

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202441988732827) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
@bedeho could you shed more light on what supporting this would actually mean? I think ultimately this would be up to wallet developers to support this format? Is there anything Atlas should do with regards to that?

**Comment by bedeho** [comment]
This is only relevant if we are currently either displaying, or accepting as input, an accounts inside the product. I can't actually think of any place off the top of my head. For such cases, using proper addresses means that the automated checksum validation protects users from making errors without noticing while inputting an address into a field, and having the network identifier as part of the address means that when you copy the address from inside Atlas to some third party app or something, it can verify that you are indeed talking about the same chain as this app may be requiring.

**Comment by kdembler** [comment]
We're only displaying account address, I think in 2 places - member profile (you can copy the address) and member creation (you need to pick account to connect with). So the input validation is out of scope. 

> having the network identifier as part of the address means that when you copy the address from inside Atlas to some third party app or something, it can verify that you are indeed talking about the same chain as this app may be requiring.

We get the address from the extension though. Should we modify the account address that we get from the extension to display it in a different format?
