### ISSUE TITLE
Introduce thousands separators (space) in input fields

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2595]
The idea captured in the spreadsheet
> Since it's quite likely that we'll be operating on very large numbers in NFT prices (at least at the beginning), shouldn't we consider introducing thousand separators (spaces) in input fields? Currently, it's very difficult to keep track of how many 0s you are entering.

![CleanShot 2022-04-29 at 16 30 48](https://user-images.githubusercontent.com/35307309/165965397-2750e564-4ae1-463b-8739-eb5b5e172422.png)

**Comment by eldiegod** [comment]
Tried different solutions in here but they all presented some problems as there is no native way to format the output of an input without altering it in some way.

Attempted to format the value of the input directly and parse it after change events back into a number but different problems appeared like when a user has it's caret after a formatting space and they try to delete digits, the event registers like they are trying to delete the space but the space is just formatting so we would have to handle change events ourselves which seems like a lot of logic.

Other option would be to render an overlay on top of the Input that shows the formatted value without altering it in the input directly but the main problems I saw is we would not be able to show a caret as the number spacing would differ with the input and also text selection would have the same problem

**Comment by dmtrjsg** [comment]
In the light of denomination being changed in favour of smaller numbers and JOY fractions, this becomes less of a priority if not worth not doing. Closing before becomes more pertinent.
