### ISSUE TITLE
Update the copy in the membership update success snackbar component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2598]
The idea captured in the spreadsheet
> Not related to the test task, but I think it's worth mentioning. When I changed my membership avatar, I got a snackbar notification with lorem ipsum as a copy. ~~Perhaps it's worth to review copy of the whole platform, not just NFT's itself.~~ (Done)

![CleanShot 2022-04-29 at 16 42 44](https://user-images.githubusercontent.com/35307309/165967514-ebb9b1e4-4bc4-4417-8939-99ba3528703d.png)

---
 
If I may suggest a copy right away, keeping in mind the other recent NFT-related copy changes, I'd suggest to ditch the body copy altogether and updating the header to say "Profile updated successfully". CC @dmtrjsg @kdembler @TCzechowski

**Comment by kdembler** [comment]
Will be addressed in #2584
