### ISSUE TITLE
Fiat denomination of prices

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2607]
# Background
In particular when setting prices $JOY/$CRT prices, it would be very useful if the user could see the Fiat/$USD equivalent of that value. Also when viewing such a price which has bearing on an imminent action, then it could also be useful. 

# Proposal
For certain key areas of the app when crypto prices are being presented or specified, show some secondary visual indication of value in fiat terms.

## $JOY

The complication here is that the product should be able to run in two mode, with or without a $JOY/fiat price feed. When there is no external $JOY/fiat price feed, the design should just omit this information, as it does today. Having a design which is flexible enough to work in both modes, without too much complication, would be the objective. The design also has to work in case the price feed becomes unavailable for any random reason.

Another factor here is that one should not show historical transactions of crypto with _current_ $JOY/fiat price. We could go as far as trying to show historical prices if we believe we will have historical exchange rates, **but I don't believe that is worth the effort at this point**.

The tech side of this should be rather elementary, not very unusual assumptions should be made about the format of the price feed, and consulting some standard price feed APIs, seems advisable. Ideally the app should not be bundled to work with a hard coded price feed, but it would be fine to just get started. 

## $CRT

**Seriously consider not doing $CRT as first try here, just added it for sharing my thoughts.**

This is slightly more complicated. Here there first off has to be some exchange rate for $JOY itself, but then, there also has to be some $JOY/$CRT price as well that can be used. This will be the case if there is an active AMM, or if there was a last sale. But if we use a last sale price, this is kind of risky. First off, it can just have been a very long time ago, and so not indicative one way or the other. Second, you can do a very small sale - even to yourself if the token is permissioned, and thus get any random price you want. This problem may be so bad we should just ignore this entirely, or we should wait for a future where we can expect to have direct price feeds even for $CRT tokens in bigger third party trading venues which are more liquid. 

# Related
Should probably be done in concert with this : https://github.com/Joystream/atlas/issues/2277

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202230296346139) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
>  When there is no external $JOY/fiat price feed, the design should just omit this information, as it does today.

That is not entirely true, as part of Rhodes we display fiat prices for NFTs for example:
![Screenshot 2022-05-11 at 09 01 03](https://user-images.githubusercontent.com/12646744/167788608-73a38a4f-a8ee-4a3a-970c-7cb9bbec6f85.jpg)

**Comment by bedeho** [comment]
Well where is this rate coming from? clearly from the tJOY price API? so it does not apply to the case I am talking about?

**Comment by kdembler** [comment]
Yes, that's the tJOY price, but I don't think what you said is true, since the product already displays the conversion using the token price. It's tJOY now but after mainnet would be JOY price or the designs would need to be updated. Or maybe I misunderstood somehow

**Comment by bedeho** [comment]
1. If we are alrady displaying thing with fiat prices, that is great! not sure if this is being done in all relevant places, but its a great start. There is also the question of doing this when inputs are being specified, so user sees fiat equivalent.
2. I was simply saying that, it may be that _there is no price feed_ at some point in time in the future, for whatever reason, the product should still work in that case and just not show the fiat price.

**Comment by kdembler** [comment]
As we're coming back to this with the recent Carthage prioritisation, here's some more specific items we should tackle in Atlas:
1. Make sure we handle no fiat conversion price gracefully:
- Inputs that display price conversion will show `null` if price is not available
- Take a closer look at the NFT widget. While it works without the price and its loading is handled, we could improve it. For example, when showing the top bid, if the price is not available, the bidder handle won't be shown.<br><img width="400" src="https://user-images.githubusercontent.com/12646744/172365116-4913e75c-2d04-4362-892a-4525038b9b64.jpg" /><img width="400" src="https://user-images.githubusercontent.com/12646744/172365124-09fc3fb8-90d3-417a-8715-bd27beb0857a.jpg" />

2. Consider showing fiat price in additional places:
- User balance
- Last NFT price (in NFT widget)

Overall I think we handle all of this quite nicely already so the scope of work will be minimal (could be even excluded from the Carthage scope if we wanted to restrict it)

**Comment by bedeho** [comment]
In my ongoing crusade to reduce scope I'm this to `urgent-post-mainnet` for the simple reason that _on launch_ there won't be any price feed, and given how quickly we likely could ship this (<1 week), we should not devote any design, implementation and testing bandwidth to it as part of `Carthage`
