### ISSUE TITLE
Block durations and milestones using dates & clock time

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2613]
# Background

In various places the user has to either read about a block duration or a particular block in the future, or has to specify this in an input form. This ends up being very difficult for many users (e.g. @mrexpat on bounty module), as the blocknumbers are gigantic, and have an unclear relationship with actual real clock/date time.

# Proposal

Allow users to get a date/clock variation for block durations or events, based on human readable notions of time. The main complication is explaining to users that when somehing is specified in clock time, the actual specification is blocks, which has a stochastic clock time.

**Comment by kdembler** [comment]
We already kind of do this for NFTs:
![Screenshot 2022-05-05 at 16 04 22](https://user-images.githubusercontent.com/12646744/166940721-f1304276-e8c3-44dd-a0aa-32613ffa7298.jpg)

Do you have any specific improvement over this in mind?

**Comment by mrexpat** [comment]
awesome @kdembler

**Comment by bedeho** [comment]
No, this was a general point @kdembler , I hope we are consistently doing this, looks excellent.

**Comment by kdembler** [comment]
Should we close this then?

**Comment by bedeho** [comment]
Sure thing.

**Comment by dmtrjsg** [comment]
https://github.com/Joystream/pioneer/issues/2213 < This was long raised for Bounties; now extended with Acceptance Criteria to update inputs to be clock time first (and translate to blocks rather than the opposite)
