### ISSUE TITLE
Balance updates on subscriptions

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2620]
rn requires page refresh to show correct numbers, and before refresh seemingly shows balances from other membership
 
[ ROW 27](https://docs.google.com/spreadsheets/d/1pWTx_BQTSAdDjEOJd5M7VxSy7qKhKjwbCdxqjU5MOjU/edit#gid=234738953)

<img width="804" alt="Screenshot 2022-05-05 at 18 02 33" src="https://user-images.githubusercontent.com/93924525/166975356-1438ede1-afe2-49c4-bb27-bbf4a4c1956e.png">

**Comment by dmtrjsg** [comment]
@toiletgranny will kindly 😎 confirm if this happens with single account as well.

**Comment by toiletgranny** [comment]
@dmtrjsg I can confirm that's not an issue when using a single account. 

Sorry for the delay; I tested this right after our meeting and [put down the note in the spreadsheet](https://docs.google.com/spreadsheets/d/1pWTx_BQTSAdDjEOJd5M7VxSy7qKhKjwbCdxqjU5MOjU/edit?disco=AAAAZBDYG1I).
