### ISSUE TITLE
Creator Tokens — Viewer: Research & Discovery

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#2656]
This phase can include activities such as debriefing, desk research, competitor analysis, booking and conducting discovery in-depth interviews, or performing moderated usability tests on existing competitors' products.

The expected outcome is a brief report on key findings & conclusions, a link to Figma moodboards, screenshots from the competitor analysis, etc.

**Comment by KubaMikolajczyk** [comment]
# Context

The important question about being a viewer of a creator token is how a viewer becomes a token owner. With that in mind below you can find some key findings & conclusions from my desk research of viewer experience from platforms with creator tokens & some major crowdfunding platforms as we spotted similarities between selling a token and fundraising your project on a crowdfunding platform.

# Key findings

### Creator tokens platforms
1️⃣  Most prominently displayed information about coins seem to be the price, circulating coins supply and the locked value inside those tokens.
2️⃣  All of those platforms use benefits as a main focus right after the price and volume
3️⃣  Although Rally seems to be the most popular and has the best user experience among all others, there is clearly an unused potential for letting the creator to tell their own story.

### Crowdfunding platforms
1️⃣  Common pattern across most of the popular platforms to divide the main layout into a main board where user can share their story with text, images & videos in one page scrolling experience + an additional panel on the right side with some additional information
2️⃣  Video + buy now action as a primary element when opening the page
3️⃣  There is a noticeable freedom given to the campaign owners when it comes to the form of their campaign presentation.

🟢  After exploring those platforms I can't get rid of the feeling that existing creator coin marketplaces do not let the user to present their projects with enough level of detail. I think getting inspiration from crowdfunding platforms in that matter can be beneficial both for the coin creators and the viewers. Lastly apart from some important information like price, coin supply or locked value I can see a huge value in using a benefit language when communicating the value of a coin for the user. 

### Below in-depth exploration are tldr. Read only to gain a deeper context in the findings.

# Creator token platforms

# 1️⃣  Rally
https://rally.io/

### Discovering coins
On rally platform viewer can discover coins by their discover coins page. Apart from the featured artists there is a prominent table of coins which allow viewer to dive into some coin details from this view
![image](https://user-images.githubusercontent.com/31144205/167851814-587b8d96-51f3-4ea4-ba5a-95bd99068686.png)
This page also gives some explanation about why one should consider buying into a coin & some success stories of big creators.
![image](https://user-images.githubusercontent.com/31144205/167852039-89d86cbf-853a-418c-b0a8-b7869c5cd876.png)
When user previews a coin a page with additional information & a current price is shown. As a viewer we land on a coin overview page which is a page combining all descriptions & msging from the creator. Below you can see coin uses & benefits section which can be set up by the token creator.
![image](https://user-images.githubusercontent.com/31144205/167852710-6239b811-be36-401b-b069-ff383f2dbfc2.png)
If users scrolls a little bit further we can see some packages offered by the creator which allows viewers to gain a deeper understanding of what this particular creator can do for them
![image](https://user-images.githubusercontent.com/31144205/167853167-742e9096-158e-400c-92e5-b186e9e10513.png)
last comes the description of the project with some social links
![image](https://user-images.githubusercontent.com/31144205/167853238-436f2c64-1f04-4862-9403-cb746d85d2d2.png)
If we switch to the activity tab more technical information are presented like a history of price or recent transactions
![image](https://user-images.githubusercontent.com/31144205/167853586-f206821f-6934-450a-85ad-cf4160255f49.png)
with additional information about weekly rewards (something like our creator payouts) which is visible to the public 
![image](https://user-images.githubusercontent.com/31144205/167853824-de364500-0b93-4627-bed1-ff49434e76f7.png)

### Buying coins
If I'm a signed & logged in member of this platform two additional tabs appear - one being my wallet and showing me my ownership if it comes to this particular creator
![image](https://user-images.githubusercontent.com/31144205/167854560-cdd557f4-d017-4591-a963-b5b606f0e4e5.png)
Also my rewards a separate page showing my rewards from owning this coin
![image](https://user-images.githubusercontent.com/31144205/167854703-53667037-b374-4afd-bb40-0625107aa172.png)
If I try to buy the coin the modal appears asking for a payment method
![image](https://user-images.githubusercontent.com/31144205/167854841-f9137551-e068-4177-b1a3-73ba86aa9d9f.png)
After choosing the credit card I can select an amount I want to buy
![image](https://user-images.githubusercontent.com/31144205/167855297-d8856f61-809e-474f-af6f-ad57c095dd96.png)
I stop at this checkout experience when the payment details are required
![image](https://user-images.githubusercontent.com/31144205/167855897-62013248-c423-4d04-b444-b374f8a89175.png)

# 2️⃣ Bitclout

On bitclout you have to be signed in & logged to see the creator token list.
![image](https://user-images.githubusercontent.com/31144205/167856651-2b07a93e-1038-4614-8455-b87f3962042b.png)
The word thing here is that it seems like they're creating coins for creators who haven't join them yet as per this msg of hovering elonmusk coin
![image](https://user-images.githubusercontent.com/31144205/167856901-f7e7bf7f-493d-4c06-b72b-f3223d4e76f2.png)
If viewer clicks on a coin a kind of feed opens like on twitter. Also some important information is here about the token itself.
![image](https://user-images.githubusercontent.com/31144205/167857046-cb7b078b-a81e-4424-86ad-8cb203d35f25.png)
Navigating with tabs if we click on creator coin we can see all holders of this coin
![image](https://user-images.githubusercontent.com/31144205/167857370-e9357301-ee93-4e0a-b446-39ba94f8cfb3.png)

If user chooses to buy the coin it can be done with a primary button buy. WHen clicked the page changes to this checkout experience.
![image](https://user-images.githubusercontent.com/31144205/167857918-28e60d98-dcb8-417e-831e-281f64b15128.png)
Unfortunatelly I cannot see any more of this experience because I am presented with error msg prompting me to buy the platform's coin first. What is worth noting is an additional option in form of checkbox to follow the creator while purchasing the coin.
![image](https://user-images.githubusercontent.com/31144205/167858212-5bfac68d-400b-4ced-9b6f-77c14592db70.png)

# 3️⃣ FYOOZ

This platform marketplace has chips filters on the top to sort for creator categories.
![image](https://user-images.githubusercontent.com/31144205/167864805-fd5ed8b4-9729-4012-b13a-6af6225077ef.png)
A big prominent image of the creator is used as a main media to present the coin - when hovered some additional info is revealed
![image](https://user-images.githubusercontent.com/31144205/167865923-71814748-3a46-437e-b998-d59e47102b54.png)
After going to a token page we can see right away a big token avatar with a buy action and some facts about coin along with additional benefits below
![image](https://user-images.githubusercontent.com/31144205/167866126-dd9445a8-dfa0-4fcd-b8cc-0fa6b40012ce.png)
After scrolling we can see additional section with some about content and social media links
![image](https://user-images.githubusercontent.com/31144205/167866295-ec0d53f7-3976-43c7-b21b-46dbb10c966d.png)
When we click on a card in about section additional dialog appears
![image](https://user-images.githubusercontent.com/31144205/167866468-e26d1e07-54e7-40d6-bbfe-62edef00a80d.png)
If user try to purchase the token the dialog below is presented
![image](https://user-images.githubusercontent.com/31144205/167866635-e73c8720-736d-4abf-8a61-a75b2103b93d.png)
which later on moves you to an external tool for exchanging tokens called uniswap
![image](https://user-images.githubusercontent.com/31144205/167866816-063f9fea-8d2a-4661-8c7a-bfd4c10941ad.png)

# Crowdfunding platforms

# 1️⃣ Kickstarter

Every Kickstarter campaign is about funding some project. After user opens the page of a single project first thing that is the most prominent are Into video and a button to support the project. 
![image](https://user-images.githubusercontent.com/31144205/167870699-62d78d82-f826-4c1e-bc95-6673d82e33a2.png)
If user scrolls a bit we can see few tabs and the one which is currently open is the overview tab called campaign under that the main layout of the page is divided into 3 parts - from the left really small navigation, main presentation part of the project, and lastly the right panel with other important information. Each of the panels is individually scrolled
![image](https://user-images.githubusercontent.com/31144205/167871612-c9e89693-1db6-4c1a-a068-d5b3fe616c1d.png)
The main part of the layout can be freely adjusted by the user and its a mix of images, videos, headings & text - combined into one page scrolling experience.

On the right side we can see a more information about the author and then helpful panels showing steps of support and benefits that come with it.
![image](https://user-images.githubusercontent.com/31144205/167872841-34bf72e6-eda7-4596-acee-820bce0d1662.png)

# 2️⃣ Indiegogo

Just like the Kickstarter above IndieGoGo follows a similar pattern with the video intro and support button being the primary elements when opening the page.
![image](https://user-images.githubusercontent.com/31144205/167873445-da39a558-1b52-43b2-b36e-3d49d512d4e8.png)
Here also the main part of the layout is the one page experience where user can freely put text, images & videos. While the right panel shows different levels of support for the campaign. The only difference is that those two scroll together here which after a short scrolling leave user with some blank space on the right.
![image](https://user-images.githubusercontent.com/31144205/167874202-dd78fe12-5a4a-48f7-96ba-56a977725630.png)

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk excellent work 🤩 key findings nicely inform our next steps so thank you for putting it all together. Excited about the mockups review next week!

**Comment by dmtrjsg** [comment]
my 5p:

**Discovery**
Discovery mvp can be represented as a section in discover channels.  We will address it properly together with NFT marketplace.

**Channel page**
From my pov kickstarter can inform our channel page, but (without green field free flow formatting, but rather a well designed structured page blocks, with one of them being joystream video thumbnail) 

**Checkout and CRT Holder Views**
Rally's checkout experience and token holder experience are quite compatible with what we have already, so good to see we were on track with the industry standard with our early ideas.  

**Overall**
In terms of overall info presentation, less clutter is better, so alternatives to market leaders are clearly loosing out. mho rally has all the right buildings blocks but assembled in slightly suboptimal way.  e.g. transaction history [ :wink: ]  is above weekly rewards, which is arguably what you want to know most to buy for gains. Also rally layout seems a little too sparse in some places.

Overall I think your key findings very well inform next steps, but let me know if you’d benefit from discussing very early thoughts.
