### ISSUE TITLE
[USERSNAP] I have to actually press "Place bid" button to get the negative feedback that its below minimum bid amount. Should be shown earlier.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2665]
## Scope
- [ ] Place bid input gets validated
- [ ] Make sure the "change price" input for NFT owner is also validated on blur 

_____

**Sender**: None
**Taken at**: https://play.joystream.org/video/26684
**Fields**:
- Expected Result: I have to actually press &#34;Place bid&#34; button to get the negative feedback that its below minimum bid amount. Should be shown earlier.
- Houston, we have a problem.: Minimum bid amount verification too late

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1be3c233-7d1b-4556-af85-e1c168ee4a06-annotated_641fc865-9ad6-46c9-988c-a342cbb00ff2.png?etag=3226ae7513e0e2be03cb5f5b6d615c3c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1be3c233-7d1b-4556-af85-e1c168ee4a06-annotated_641fc865-9ad6-46c9-988c-a342cbb00ff2.png?etag=3226ae7513e0e2be03cb5f5b6d615c3c)*

**Browser**: Firefox 100 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1752x1154
**[Open #19 in Usersnap](https://app.usersnap.com/l/feedback/7320acfc-0acd-4548-a455-7f3abc2a52b0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by toiletgranny** [comment]
That's fair. Frankly, I, too, would expect this input to be validated on blur since that's our approach during the listing flow. Can we make sure the change price input is also validated on blur if we go with this? 🙏

**Comment by dmtrjsg** [comment]
Discussed this with Klaudiusz, and in-line with the global pattern on validating on submit, this would get cancelled.
