### ISSUE TITLE
Make it easier to find / switch member profiles

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2671]
- do not reload the app when changing URL to another member (https://play.joystream.org/member/member?tab=Activity)
- list profiles that created NFT, Videos, Channels more prominently
- add members / channel owners to search results
- dropdown on profile page to select another member

**Comment by kdembler** [comment]
> do not reload the app when changing URL to another member ([play.joystream.org/member/member?tab=Activity](https://play.joystream.org/member/member?tab=Activity))

Could you expand on this point a bit? I don't fully understand

**Comment by traumschule** [comment]
when you changed the url to another member the app reloads completely instead just changing the route. looks fixed now. :+1:

**Comment by kdembler** [comment]
We haven't done any fixes for this :P You mean changing the URL manually in the browser URL input?

**Comment by traumschule** [comment]
yes, then it's up to cloudflare maybe.

**Comment by kdembler** [comment]
No, it certainly doesn't have anything to do with Cloudflare. To my knowledge, it's actually not possible to (manually) change the URL without reloading the app, that seems to be the browser behaviour and cannot be controlled by the application.

**Comment by traumschule** [comment]
[react-router](https://reactrouter.com/docs/en/v6/hooks/use-location) [can help with that](https://stackoverflow.com/questions/45373742/detect-route-change-with-react-router) using [history](https://github.com/remix-run/history/blob/dev/docs/api-reference.md#historylistenlistener-listener) listener

**Comment by kdembler** [comment]
This allows you to interact with the browser's history API, but that will only include changes made programatically, using the same history API. This can't detect manual change of the URL in the browser bar, as browser will always fetch a new document when you navigate to a different URL yourself

**Comment by traumschule** [comment]
Well, if you are sure about that. Thought i'd been using it for a while in react apps already.

**Comment by kdembler** [comment]
I'm not 100% sure, but I haven't seen anything like this implemented ever. If you can point me to an app that can support something like this, I'd love to take a look

**Comment by traumschule** [comment]
Maybe it's as you said then and some browsers like ff and chrome are just more clever.

**Comment by dmtrjsg** [comment]
Created:
- https://github.com/Joystream/atlas/issues/2947

Profiles that created NFT, Videos, Channels more prominently  
- https://github.com/Joystream/atlas/issues/2904
- https://github.com/Joystream/atlas/issues/2905

Switch member:
- https://github.com/Joystream/atlas/issues/2946
