### ISSUE TITLE
It takes too long to be able to place a bid

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2672]
Auctions can get quite hectic and user wants to load NFT page and place a bid fast. Currently the `Place bid` button is not visible for a long time which can also confuse new users.

**Comment by kdembler** [comment]
I'm assuming you mean the delay when you open the video page directly from a link (fresh app load). There's a reason behind it though, I certainly wouldn't call it a bug. The thing is that we need to have connection with Joystream node to get the current block. Auctions can start in the future and if that's the case, you cannot place a bid on them yet. So until we know what the current block is, we cannot tell whether it's already possible to place a bid on a given auction. The button becomes visible once the app knows whether the auction is active.

**Comment by dmtrjsg** [comment]
Closing for now as will not be actionable. Improvement of this ticket will be in response time and connectivity status ux.
