### ISSUE TITLE
Creator Tokens — $CRT Holder: Testing

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2690]
This phase can include activities such as conducting moderated/unmoderated usability tests on prototypes from the LoFi phase, doing surveys, or other types of user research.

The expected outcome is a brief summary of key findings, a list of recommendations, and a list of test participants to be paid out (if applicable). Learn more from [Approaching testing in Atlas](https://grizzled-corleggy-af8.notion.site/Approaching-testing-in-Atlas-115a1c0480144c8682dc9b63c99473c4) Notion article (WIP).

Depending on the results, the next step is either proceeding to the next phase of the design process or going back to the LoFi phase and repeating the tests if needed.

**Comment by KubaMikolajczyk** [comment]
This experience will be tested together with other experiences after finishing all hi fi work for CRTs
