### ISSUE TITLE
Rework video form title input and validation

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2692]
The title input on video form really blends in with the background and may be easily missed by the user. When you also take into account that validation on this page doesn't let you see any error (the submit button is disabled), the experience can be really confusing. This has been reported by a number of different users (both jsgenesis and community), we should really make some quick fix there to improve this flow

**Comment by toiletgranny** [comment]
@kdembler Below, you'll find my list of recommendations on how we can mitigate this issue ad hoc, before we do the overhaul of the entire video upload form based on the recent forms design changes in the design system.

1. Update the Title input (formerly: Title area) component based on the designs, docs, and changelog, which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7666%3A157393). The key changes which aim on solving the problem are increasing the brightness of the placeholder text and introducing the Error styling variant, which should be used to direct the user's attention towards this field (if left blank upon form submit attempt).
2. Change the Title input component placeholder to "Enter video title" (not on the component level, only in the video upload form).
3. Prepopulate the video title with the uploaded video file name while using the following parsing rules:
   - Drop the file extension from the end of a string if matching any of the following: `.webm|.mpg|.mp2|.mpeg|.mpe|.mpv|.ogg|.mp4|.m4p|.m4v|.avi|.wmv|.mov|.qt|.flv|.swf|.avchd|.mkv`,
   - Replace all underscores with spaces,
   - Capitalize the first character of a string.
4. Make sure the above-mentioned parsing only takes place once: when fetching the video file name.
4. Change the validation strategy to allow submitting the video upload form before filling it out accordingly to the requirements. For validation errors, let's use the copy we already have in the code, while keeping in mind that the copy might change after we're done implementing everything in https://github.com/Joystream/atlas/issues/2056.

> **Changelog (from Figma)**
> - Renamed the component from “Title area” to “Title input”,
> - Updated text colors to use color design tokens,
> - Updated transition animations to use animation design tokens,
> - Rearranged and renamed component properties,
> - Added Styling property with Error variants (for selected States),
> - Updated the validation requirement info styling to use a different format: “Min 5 chars • Max 60 chars”, instead of “Min 5 Chars | Max 60 Chars”,
> - Updated the on-hover tooltip contents guidelines to be always the same (“Click to edit”).

![image](https://user-images.githubusercontent.com/35307309/169842115-3edb66e8-20c9-48b5-b6ca-f41d680aca01.png)

**Comment by kdembler** [comment]
Thanks a bunch, we will implement those suggestions right away 👍
