### ISSUE TITLE
ESC closes dialogue windows and overlays

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2700]
**Sender**: None
**Taken at**: https://play.joystream.org/video/26684
**Fields**:
- Which feature are you missing?: Exit place bid overlay with ESC
- What problem would that solve for you?: I wanted to exit this place bid overlay using keyboard ESC key, rather than navigating to the small X, but its not supported.

**Browser**: Firefox 100 (macOS Catalina)
**Screen size**: 5120x1440
**[Open #14 in Usersnap](https://app.usersnap.com/l/feedback/45d51be5-a0c0-4449-8151-a0086a2b5b7a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by kdembler** [comment]
Worth considering for regular dialogs as well. Let's ask Adam for input but worth doing IMO

**Comment by drillprop** [comment]
After a short call with Adam, we decided to add support for all the dialogs and drawers. One important thing - we should warn the user with a dialog about losing data in drawers where there are many inputs - VideoForm, NftForm when he presses escape or closes the drawer with the X button. We don't do this right now at all.

**Comment by dmtrjsg** [comment]
Looks like we have a chance for a quick turnaround for the confirmation modal designs later today as we were looking for small fillers with  @toiletgranny, so a good candidate :)
