### ISSUE TITLE
[FEATURE REQUEST] Keep player visible while scrolling description

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2701]
**Sender**: dev@joystreamstats.live
**Taken at**: https://play.joystream.org/video/26217
**Fields**:
- Which feature are you missing?: Keep player visible while scrolling description
- What problem would that solve for you?: The video scrolls away. Some news site automatically switch to picture mode in the buttom right. That be fancy.

**Browser**: Chrome 99 (Linux)
**Screen size**: 1920x1080
**[Open #13 in Usersnap](https://app.usersnap.com/l/feedback/83058c6e-09d4-4f16-97b4-5e2c3bc31574?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@kdembler  did we have this already designed by Nina?

**Comment by kdembler** [comment]
Yes, see https://github.com/Joystream/atlas/issues/1941

**Comment by dmtrjsg** [comment]
@kdembler thanks a mil. Closing this one. Original issue moved out of icebox to be released with comments and reactions.
