### ISSUE TITLE
[FEATURE REQUEST] Show new videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2702]
**Sender**: dev@joystreamstats.live
**Taken at**: https://play.joystream.org/new
**Fields**:
- Which feature are you missing?: Show new videos
- What problem would that solve for you?: [new](https://play.joystream.org/new) displays `promising channels`. I would like to see a grid of 6 x 3 lines latest video uploads with `more` button to be routed to `/new/videos` with endless scrolling.

**Browser**: Firefox 98 (Linux)
**Screen size**: 1920x1080
**[Open #12 in Usersnap](https://app.usersnap.com/l/feedback/bb9e657c-0543-48ef-9b35-dae3d76b07d5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by drillprop** [comment]
Hmm, I think we added this recently.  We have the `Recently uploaded` section. 
![image](https://user-images.githubusercontent.com/51168865/168762288-7a15730b-ea85-4ca2-af85-c3a3f42a3d47.png)

**Comment by kdembler** [comment]
Yes, can confirm it's done
