### ISSUE TITLE
Update the Input (formerly: Text field) component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2707]
**AC:**

- [ ] Create reusable style blocks that will replace `InputBase` component
- [ ] Implement updates to the `Input` component

**OOC:**

- [ ] Formatting of numbers inside an input, captured in #2595

---

The goal of this task is to update the Input (formerly: Text field) component based on the designs, docs, and changelog, which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7058%3A174881). 

> **Changelog (from Figma)**
> - Renamed the component from “Text field” to “Input”,
> - Updated the overall styling, along with the internal layers structure,
> - Rearranged and renamed component properties,
> - Added Prefix & Suffix variants,
> - Added Styling property with Error variants (for selected States),
> - **(Breaking change!)** Changed the type of icons used in the component from Controls (24px) to Action (16px),
> - Changed the Action variant to include a Button component of a specific type,
> - Added the ability to nest custom components both at the beginning and at the end of the component,
> - Added processing variant,
> - Added Medium size variant (with the original being now called “Large”),
> - Dropped Label and Caption variants (these are now handled by the Form field component),
> - Added documentation along with content/usage guidelines.

⚠️ Please note that the change in the type and size of icons used inside will make the Input component not backward compatible with the earlier usage in that regard. Therefore, my suggestion for the developer taking care of this task would be to reach out to me once the component is implemented and reviewed, schedule a 30-minutes session together, and walk through the app to catch and note down all of the icons that will require updating.

![image](https://user-images.githubusercontent.com/35307309/168804172-f4951984-8e17-498b-9637-4e5aa8de5b7f.png)

---

**⚠️ Absurd number of variants warning!** 
Due to the nature of the component and the characteristics of Figma, as a design tool, the number of variants of this component is very large. As a developer inspecting the designs, you might want to consider duplicating the Figma file over to your Drafts space and playing with the component yourself. [Learn more (2:15 min).](https://youtu.be/66sWUyenQcw)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2707?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
