### ISSUE TITLE
Update the Select component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2708]
**AC:**

- [ ] Extract `List` component from the `ContextMenu`. This would be just a styled list of `ListItem` components. It needs to support passing arbitrary props to both the container and items, so it can be used with `downshift` inside the `Select`. It should have a `size` prop. Then the `ContextMenu` is just a `List` wrapped in `Popover`
- [ ] Update the `Select` component with all the changes from Figma. We use new `List` component inside to have matching styles.

**OOC:**

- [ ] Support for selecting multiple values

---

The goal of this task is to update the Select component based on the designs, docs, and changelog, which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7080%3A141520). 

> **Changelog (from Figma)**
> - Updated the overall styling, along with the internal layers structure,
> - Rearranged and renamed component properties,
> - Added Styling property with Error variants (for selected States),
> - **(Breaking change!)** Changed the type of icons used in the component from Controls (24px) to Action (16px),
> - Added an inline label variant,
> - Dropped the Small size variant,
> - Dropped Label and Caption variants (these are now handled by the Form field component),
> - Proposed the use of Context menu for rendering the list of options, along with guidelines on keyboard navigation,
> - Added guidelines for multi-select usage,
> - Added documentation along with content/usage guidelines.

⚠️ Please note that [similarly to the Input component](https://github.com/Joystream/atlas/issues/2707), the change in the type and size of icons used inside will make the Select component not backward compatible with the earlier usage in that regard. Therefore, my suggestion for the developer taking care of this task would be to reach out to me once the component is implemented and reviewed, schedule a 30-minutes session together, and walk through the app to catch and note down all of the icons that will require updating.

![image](https://user-images.githubusercontent.com/35307309/168806375-07c22a98-0587-45b4-9ee1-d289044b8e3c.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2708?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
