### ISSUE TITLE
(Re)create the Form field component

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2715]
- [ ] Make all the updates to the `FormField` component
- [ ] Go through the app and move all the `helperText`s from inputs to `FormField`

---

The goal of this task is to create the Form field component based on the designs and docs, which [can be found in Figma](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=7056%3A167547). 

> **Changelog (from Figma)**
> _There's no Changelog because this component did not exist previously in the components library in Figma._

![image](https://user-images.githubusercontent.com/35307309/168819288-776b3c95-f6e4-40c3-8f3e-8dd2174898e2.png)

**Comment by kdembler** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Atlas-600edbb8799cc700103bc2d7/issues/Joystream/atlas/2715?planning-poker) with ZenHub @drillprop @eldiegod @rafalpawlow
