### ISSUE TITLE
[USERSNAP]"Manifest fails to load because of Cloudflare"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2736]
**Sender**: dev@joystreamstats.live
**Taken at**: https://play.joystream.org/nfts
**Fields**:
- Expected Result: manifest.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.

Content begins
```
&lt;!DOCTYPE html&gt;
&lt;!--[if lt IE 7]&gt; &lt;html class=&#34;no-js ie6 oldie&#34; lang=&#34;en-US&#34;&gt; &lt;![endif]--&gt;
&lt;!--[if IE 7]&gt;    &lt;html class=&#34;no-js ie7 oldie&#34; lang=&#34;en-US&#34;&gt; &lt;![endif]--&gt;
&lt;!--[if IE 8]&gt;    &lt;html class=&#34;no-js ie8 oldie&#34; lang=&#34;en-US&#34;&gt; &lt;![endif]--&gt;
&lt;!--[if gt IE 8]&gt;&lt;!--&gt; &lt;html class=&#34;no-js&#34; lang=&#34;en-US&#34;&gt; &lt;!--&lt;![endif]--&gt;
&lt;head&gt;


&lt;title&gt;Please Wait... | Cloudflare&lt;/title&gt;
```
- Houston, we have a problem.: Manifest fails to lead becaues of Cloudflare

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f959c8c9-6114-40a0-8faf-a10b64c5036a-annotated_19a82c24-71b5-47a8-948a-b1f29dd850b8.png?etag=e84df2f37069d512f8e52085b23432d6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f959c8c9-6114-40a0-8faf-a10b64c5036a-annotated_19a82c24-71b5-47a8-948a-b1f29dd850b8.png?etag=e84df2f37069d512f8e52085b23432d6)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1058x1081
**[Open #20 in Usersnap](https://app.usersnap.com/l/feedback/76903657-9c20-4383-9491-5e4e10e2574f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
@dmtrjsg looks like form title goes to the wrong field.
title i set was "Manifest fails to lead becaues of Cloudflare"

**Comment by dmtrjsg** [comment]
Cannot replicate this, so closing for now
