### ISSUE TITLE
Outdated link in design docs

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#2737]
https://github.com/Joystream/atlas/tree/master/docs/design
> Atlas design docs
> As of December 2021, all kinds of docs related to Atlas design have been moved and are being maintained in Notion:
> https://grizzled-corleggy-af8.notion.site/Design-Space-487ed84966fa495a8c037935639ca681

**Comment by toiletgranny** [comment]
Hi! Sorry about that, here's the correct link: https://joystream.notion.site/Design-Space-487ed84966fa495a8c037935639ca681

@drillprop, can I ask you to update it?

**Comment by drillprop** [comment]
@traumschule thanks for pointing this out. Fixed in #2739
