### ISSUE TITLE
Introduce geolocation awareness in distributor selection

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2748]
# Background

Currently, Atlas selects distributors randomly, more or less. This means that latency of fetching data, like videos and images, will possibly be quite high, because distributors may be very far away geographically/connectivity-wise from the relevant user.  Fixing this is a relatively cheap undertaking on the application side, and it can substantially improve the UX of Atlas, which he strategic value. It also can help the distributor working group get more realistic load patterns that can help them understand how to manage and maintain the infrastructure under more realistic circumstances than today, where the load is presumably uniform.

# Proposal

Add basic features in Atlas for this kind of selection. I don't think it is advisable to have any sort of user interaction in selecting this at any level, as its never something the user will want to be involved in. Hence there should not be any need for design work here.

**Comment by traumschule** [comment]
- https://github.com/Joystream/atlas/issues/2553
- https://github.com/Joystream/atlas/issues/2282
- https://github.com/Joystream/atlas/issues/2672

**Comment by bedeho** [comment]
Wow, seems you were miles ahead of me here @traumschule ;) guess those issues should be reviewed at the same time.

**Comment by kdembler** [comment]
Dropping the link here: https://github.com/Joystream/joystream/blob/giza_staging/distributor-node/docs/node/index.md#distributionbucketfamilymetadata
