### ISSUE TITLE
Perpetual followed channels loading

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2749]
When I open the sidebar, I see the following

![Screenshot 2022-05-26 at 10 40 24](https://user-images.githubusercontent.com/437292/170452115-2767902b-91f1-4073-94fd-ef30238c5b6f.png)

Even if I refresh, this keeps being the same.

Could this be because my local storage is referencing creators who did not make it past some migration/network upgrade?
If not, what is going on?

**Comment by kdembler** [comment]
> Could this be because my local storage is referencing creators who did not make it past some migration/network upgrade?

Yep, that would be my guess. We had this handled actually, seems it broke along the way

**Comment by bedeho** [comment]
> Yep, that would be my guess. We had this handled actually, seems it broke along the way

Ok, should I do anything, like clear my browser history, or will a fix be done?

**Comment by kdembler** [comment]
We will fix it next sprint
