### ISSUE TITLE
Create publishing sidenav

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#275]
#### Description

We will need a separate navigation sidenav for the publishing part of Atlas.

#### Requirements

- `PublishingSidenav` added to `src/components` (with items defined inside the component)
  - same done for `ViewerSidenav`
- New sidenav integrated
  - Should be displayed instead of the regular one when the path starts with `/studio`

**Comment by 0xVolodya** [comment]
Hi, can I try to do this?

**Comment by kdembler** [comment]
Hey @nadalfederer, thanks for your interest in this. I'd be happy if you worked on this, however, I think this may be slightly blocked by one other task currently in progress - #276. I think it'd make most sense to work on this once the other is finished.
