### ISSUE TITLE
Question: Fetching video assets

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#2756]
# Background

We are looking into improving Atlas display latency, this is part of me getting up to speed and having a place to discuss related improvements to this topic of fetching assets.

# Question

When Atlas needs to render a bunch of videos in a scene, say in search results, or on a channel page or whatever, and there are tons of assets it needs to fetch, specifically cover photos and channel avatars how does it currently select whom to grab these from?

1. Does it fetch everything from one random distributor?
2. Does it fetch each asset from different distributors?
3. Is each asset fetched in a standalone query?

**Comment by kdembler** [comment]
> Does it fetch everything from one random distributor?

> Does it fetch each asset from different distributors?

We're determining a distributor to use for every file separately. Like I've mentioned, currently the process is semi-random, that means we don't use any metric to pick the operator, but we also want this pick to be mostly repeatable, so on next visit to the app, the same URL is used for the asset, otherwise you cannot use what you already have in the browser cache. You may want to take a look at my comment: https://github.com/Joystream/atlas/issues/2553#issuecomment-1123580088.

> Is each asset fetched in a standalone query?

I'm not really sure what you mean here. The overall process is that at the app startup we fetch the list of all distributors and bags they serve, create some local lookup object and when we want to access this asset, we will see which distributors serve this bag and pick one of them.

**Comment by bedeho** [comment]
> We're determining a distributor to use for every file separately.

So hypothetically, lets say if there are `N` assets to be displayed, this _could_ result in `N` distinct distributor hosts being used, one unique per asset? Assuming this is the case, then if one further assumes that the browser would do lots of fancy magic when needing to fetch `N` assets from one host, rather than `N` distinct hosts, then the size of `N` could contribute significantly to the total time it takes to fetch all assets.

So my question is, is there such magic, or any other factor that should lead us to suspect that having a large number of distinct hosts will increase expected time until last asset is fetched?

**Comment by bedeho** [comment]
One thing that makes me think it really should be a big difference is stuff like

- having to check `N` SSL certs.
- limits on #of connections in the browser somehow blocking how much you can request in parallel, however this seems like a complex [topic](https://blog.bluetriangle.com/blocking-web-performance-villain)

**Comment by kdembler** [comment]
> So hypothetically, lets say if there are N assets to be displayed, this could result in N distinct distributor hosts being used, one unique per asset?

Correct.

> So my question is, is there such magic, or any other factor that should lead us to suspect that having a large number of distinct hosts will increase expected time until last asset is fetched?

There may be some magic but I don't think we would benefit from it either way. If our distributors were using HTTP/2, we could benefit from multiplexing multiple requests over a single TCP connection, but all operators I've checked were using HTTP/1.1.

> having to check N SSL certs.

That probably has some impact indeed but without HTTP/2, just using a single distributor would be still a partial solution.

> limits on #of connections in the browser somehow blocking how much you can request in parallel, however this seems like a complex [topic](https://blog.bluetriangle.com/blocking-web-performance-villain)

So limits are actually per host, so having to fetch all the assets from a single host without HTTP/2 would actually decrease performance, as far as my understanding goes.

---

There's probably quite a few things we could improve in this area, we just never focused on this at all. Also my question is, are there any indications that request prioritization/number of providers are any significant contributors to the asset fetching issues we're seeing? I think those may be very small improvements, making sense at larger scale. At this point it seems like we really need to focus on infra (and picking the closest distributors) to see the biggest impact. Let me know if you disagree

**Comment by bedeho** [comment]
> but all operators I've checked were using HTTP/1.1.

Ok, so we should change this then? Like in Argus, and probably even Colossus?

> indications that request prioritization/number of providers are any significant contributors to the asset fetching issues we're seeing

Absolutely not, really, the problem should be analyzed and broken down, for different pages, so we can see how much each component is contributing, before we do anything drastic indeed.

Could this be a community task? or could this be outsourced to some service?

**Comment by kdembler** [comment]
> Ok, so we should change this then? Like in Argus, and probably even Colossus?

Definitely, this should improve the performance quite a bit. Although I'm not sure if this will actually be Argus/Colossus and not just the proxy setup, like nginx or caddy.

> Absolutely not, really, the problem should be analyzed and broken down, for different pages, so we can see how much each component is contributing, before we do anything drastic indeed.

> Could this be a community task? or could this be outsourced to some service

Yeah I think someone with technical experience from community could take a stab at it, understanding what causes the issues will help us prioritize the fixes

**Comment by bedeho** [comment]
I did a quick check on YT, it seem 100% of cover photos come through a single DNS endpoint at least `https://i.ytimg.com`, which presumably means the SSL stuff only happens once, and perhaps even that browser fetches all assets over one connection in parallel. E.g. this is an URL 

`https://i.ytimg.com/vi/oRG2jlQWCsY/hq720.jpg?sqp=-oaymwEcCOgCEMoBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&rs=AOn4CLC5aImc0EDvmgrSnIx_gHajlr5hhQ`

Interestingly, all avatars are fetched from a different single domain `https://yt3.ggpht.com`, and this is an example URL

`https://yt3.ggpht.com/ytc/AKedOLR-igJVdq-kp4V3qJMozd7ysi9bDN0BaDsIidyeJw=s68-c-k-c0x00ffffff-no-rj`

What is interesting to think about is: how could we unlock this in our system? Since the distributor fundamentally are oriented around _bags_, meaning they are tasked with distributing all assets for a single channel, its not obvious how you could instruct them to do something like "hold all assets of type x from all bags", for example. It would be entirely feasible to accommodate more flexible stuff like that, but its also not sure its _needed_. But at the end of the day, at some level, if we are going to unlock any efficiency from being able to get `N` assets from a single host, then hosts have to be tasked with distributing those assets.
