### ISSUE TITLE
NFT view loading blinking

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2759]
Reported by `Ömer_ÖzdemirTR#5183` on Discord:

> Tryed several times. even with 35mbps internet connection, while Loading pages on atlas the loading  animation seems blinking and seems irritating to the eye. maybe it can be more smooth.

https://user-images.githubusercontent.com/12646744/170714151-a57da832-f1d3-40e4-9b00-607574508aeb.mp4

On the recording there is my NFT which is the first so there actually shouldn't be any loading after that last item

**Comment by eldiegod** [comment]
Can't reproduce, are you able to?

**Comment by kdembler** [comment]
Wasn't able to reproduce as well but I think more than one person have reported this so worth investigating somehow
