### ISSUE TITLE
[USERSNAP] Loading NFT pages is Blinking

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2767]
@dmtrjsg commented on [Fri May 27 2022](https://github.com/Joystream/pioneer/issues/3116)

**Taken at**: https://play.joystream.org/nfts
**Fields**:
- Houston, we have a problem.: Loading NFT pages is Blinking
- Comment: When open NFT page and go to second pages, while page is loading nft images, loading animation seem blinking and irritating to the eye. it should be more smooth.
- Feedback: Ömer_ÖzdemirTR#5183

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/254d602d-45dd-40f1-b587-293a78b8d66e-annotated_e6ec9947-7851-4141-8660-3262caba2063.png?etag=ee23327006af999a73f93dd803b4062a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/254d602d-45dd-40f1-b587-293a78b8d66e-annotated_e6ec9947-7851-4141-8660-3262caba2063.png?etag=ee23327006af999a73f93dd803b4062a)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x722
**[Open #263 in Usersnap](https://app.usersnap.com/l/feedback/ba3096a2-67d7-4bc6-9dd5-8665222bf4f8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by kdembler** [comment]
Duplicate of https://github.com/Joystream/atlas/issues/2759
