### ISSUE TITLE
Link overlapping with the description on small screens

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2780]
![Screenshot 2022-06-02 at 11 36 28](https://user-images.githubusercontent.com/12646744/171601741-2f80730a-0d72-4800-ae5a-11f9362040fe.jpg)

Seen here: https://play.joystream.org/video/26800

Only happens on screens below 520px for this specific case although I guess it depends on the exact link.

**Comment by kdembler** [comment]
It's actually not only links, text can do the same and on bigger screens:
![Screenshot 2022-06-02 at 15 44 28](https://user-images.githubusercontent.com/12646744/171643505-be1c4267-12e8-41d9-8c80-d649c8669ecb.jpg)

**Comment by kdembler** [comment]
Additionally,

> Also, still on iOS, Safari, when I click the "Show more" button, and then "Show less", the video description is gone entirely.

**Comment by eldiegod** [comment]
> Additionally,
> 
> > Also, still on iOS, Safari, when I click the "Show more" button, and then "Show less", the video description is gone entirely.

hmm I'm not able to repro this on IOS, is there a video?

**Comment by toiletgranny** [comment]
@eldiegod Have you tried this video? https://atlas-git-reactions-joystream.vercel.app/video/5 I'm on iPhone 12 Pro, iOS 15.5, Safari.

**Comment by toiletgranny** [comment]
Also, it was only today in the morning when I discovered (**As is**) the video title is `var(--typography-desktop-h600)` on desktops.  **To be:** `var(--typography-desktop-h500)`. Can we include this little tweak in the scope of this task?

**Comment by eldiegod** [comment]
> @eldiegod Have you tried this video? https://atlas-git-reactions-joystream.vercel.app/video/5 I'm on iPhone 12 Pro, iOS 15.5, Safari.

Yes I can reproduce on that one and happens in other browsers too
