### ISSUE TITLE
Reaction stepper fixes

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#2792]
> As is: There's a min-width: 155px set on the Reaction stepper component.
> To be: There should be no min-width, as it makes the nested buttons misaligned horizontally. I'm curious: why was this property set over there in the first place? I'm worried it might have been solving some other CSS issue I'm not aware of.

> 🚨 As is: The Reaction stepper component doesn’t update after leaving a reaction and having the transaction processed successfully. When I refresh the page, the Reaction stepper component displays correct values.
To be: The Reaction stepper should be refreshed the moment the transaction has finished processing

**Comment by toiletgranny** [comment]
@kdembler I have three more minor CSS tweaks we came up with just today, in the morning. Could we include them in the scope of this task, @kdembler? 🙏 
1. **As is:** The color of the 1px border underneath the color Reaction stepper component is set to `var(--color-core-neutral-700)`.
**To be:** `var(--color-border-muted)`.
2. **As is:** Width of the border underneath the color Reaction stepper component matches the width of the parent container.
**To be:** Up until the MD breakpoint, the bottom border should outgrow the surrounding container by `16px` (or better yet: the outer margin we have right now on mobile screens, if we keep it as a CSS variable) on both sides. Please, [have a closer look here.](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2555%3A435487)
