### ISSUE TITLE
Implement the sign in publishing view layout

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#280]
#### Description

Implement the initial Studio view, according to the design https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=3119%3A0

#### Requirements

- Matches the design and its flows (without the integration logic)
- Scales on mobile devices properly

**Comment by 0xVolodya** [comment]
Can I try to do this? or it is blocked

**Comment by kdembler** [comment]
Thanks for your interest in this @nadalfederer. Unfortunately, this one will be pretty complex and will require some internal communication both with the rest of the team and the designers so I'd rather have someone from the Jsgenesis team to work on this one.

I do appreciate your contributions and eagerness to help though! I think today we should merge the PR that was blocking the #275 and maybe you can work on that then? I can ping you once we're ready to proceed if you're interested
