### ISSUE TITLE
Atlas fees support in components

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2815]
**AC:**

- [ ] Update the contents of reaction onboarding popover
- [ ] Update the info and tooltip in comment input
- [ ] Add fee support to Dialog component

## Context
Fees will be non-zero, covering both size of extrinsic parameters, and also computational costs.

Any input field which includes text that goes into the chain, such as the body or title of a blog post, ends up being stored on-chain, and this impacts the total transaction fee that must be paid. It would be useful to have a clear UX around communication how what the user is providing as inputs is impacting the final fee.

## Scope
* [ ] Introduce non-zero fees denominated in JOY Mainnet Currency for all modals: 

- Add fees info to Comments
- Add fees info to Reactions info modal shown first time to users (it will be a param)
- Add fees to the footer of all modals
NFT minting / buying / bidding
Video Posting / editing/ deleting
Updating Membership
Channel Creation / Editing

@toiletgranny  will update the list pointing to the Figma designs

### Out of scope

[we ignore everything that is added below this line in this ticket]

:information_source:  These features may impact design decision for fees, hence makes sense to address holistically:

* [JOYs denomination](https://github.com/Joystream/joystream/issues/3389)
* [Flexible Currency](https://github.com/Joystream/pioneer/issues/3004) 
* [Fiat denomination of prices](https://github.com/Joystream/atlas/issues/2607)

* [ ] https://github.com/Joystream/atlas/issues/2277
* [x] #2834
* [x] #2837
* [x] #2838

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202413103666730) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Working note: mentione fees in the reactions popover.

**Comment by toiletgranny** [comment]
@dmtrjsg @bedeho, here's the video update covering (hopefully) all there's to discuss regarding how & when can we display fees in Atlas: https://www.loom.com/share/701bde25f9874b07a9da86024523a44a

[Here's the Figma prototype](https://www.figma.com/proto/ZJP3EfviLTInY997SXL0mD/Fees-in-Atlas?page-id=802%3A5523&node-id=1101%3A17326&viewport=-874%2C164%2C0.41&scaling=min-zoom&starting-point-node-id=1101%3A17326), in case you want to follow along with me. Just use left and right arrows to navigate through the screens I'm covering in the video update.

cc @kdembler

**Comment by kdembler** [comment]
Thanks for the update Adam.

@bedeho do you have any rough idea of how big the fees may be on mainnet? Even some estimation of order of magnitude may be useful to reason about this.

I would really opt to not display fee information for those very simple interactions like leaving a reaction under the video. At the end, wallet should show fee estimation to the user anyway

**Comment by toiletgranny** [comment]
> I would really opt to not display fee information for those very simple interactions

I agree, but only assuming fees for those won't be significant.

> At the end, wallet should show fee estimation to the user anyway

Of course, that would prob solve everything, but — just to be sure — I'm not misremembering things about Polkadot.js **not** showing fees in the extension, right? And that there's nothing we can do about it (changing what's displayed in the Polkadot.js signer)?

**Comment by toiletgranny** [comment]
Also, one more thing struck me just today in the morning: **Can we tell how long it's going to take for us to calculate the fee?** And then convert it to JOY/tJOY?

My recommendations from yesterday's video update are based on the assumption it's either really quick or almost instant. But if it's more likely to take 2, 5, or 10 seconds, then we're running into the issue of having to indicate that the fee calculation is being fetched in the UI. This is not ideal, for multiple reasons and might call for a different approach to displaying fees in the UI altogether. But, before we open up this discussion, let's check if it's even worth our time. 

So yeah, how is it regarding the time needed for calculating fees? Can we tell at this point?

**Comment by kdembler** [comment]
> Of course, that would prob solve everything, but — just to be sure — I'm not misremembering things about Polkadot.js not showing fees in the extension, right? And that there's nothing we can do about it (changing what's displayed in the Polkadot.js signer)?

Yep, correct. Although Talisman will display them though:

https://user-images.githubusercontent.com/12646744/173802277-8771da78-9e90-49e0-8873-02bcd9d5ca71.mov

As you can see, for now the fee is undefined but that should change once Talisman adds support for our chain.

> So yeah, how is it regarding the time needed for calculating fees? Can we tell at this point?

I'm not sure yet actually, but my guess would be it should be less than 2 seconds most of the time, but we certainly need _some_ design treatment for that (although I would aim for something simple to start with)

**Comment by bedeho** [comment]
> @bedeho do you have any rough idea of how big the fees may be on mainnet? Even some estimation of order of magnitude may be useful to reason about this.

My hope is that we can try to keep this very low for all the metaprotocol stuff, because that just involves reading the database to authenticate a remark, so it should be very very cheap, comparable to all major low fee chains, fractions of cents. For othet transactions, is harder to say, but they would obviously be more expensive. There is also the issue of how big blocks will be, which impacts how expensive even metaprotocol messages will be, as they have some size to them.

**Comment by toiletgranny** [comment]
@kdembler The changes from the agreed scope are now ready to be implemented in the shape & form we discussed together with @dmtrjsg on the Wed's meeting (meaning the optimistic scenario).

Here's the list:
- Designs, docs, and changelog for **comments & reactions** [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2140%3A135509),
- Designs, docs, and changelog for the **Action bar component** (a footer we display in _NFT minting / buying / bidding_, _Video Posting / editing/ deleting_, _Updating Membership_, _Channel Creation / Editing_) [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8477%3A161454),
   - Please note that the fee information should be now displayed in all instances of the Action bar component, which includes flows such as the NFT listing (currently, the implementation disregards the designs and omits this information in the Action bar component), or the NFT purchase view.
   
   
cc @dmtrjsg

**Comment by dmtrjsg** [comment]
@toiletgranny  🙈 sorry for being late to the party with the below: 

1️⃣  **Comments:**

Overall I would opt in for showing actual fee in JOY and tooltip icon next to it (rather than line of text insinuating same info). On tooltip click, we serve a popup encapsulating this copy:

"We store all records, including assets metadata, comments and reactions on blockchain, transaction fees apply to cover for the computational costs of adding such records to the block and processing it. Tap or click on the transaction fee to view full accurate precise representation of transaction fees." (hover is not mobile-friendly)

So when number is clicked you see:

"Transaction Fee of 1 JOY and 123556646 BDH* applies
($USD 0.00006)
*1 JOY = 1000000 BDH".


2️⃣  **Reactions**

I think we only include info about reactions fees to the initial screen (once) and not bother on showing tooltip for reaction hover as this makes it less engaging to use and fees will be without variation for all transactions and very insignificant. 

3️⃣  **Footer of modals:**

- Similarly to comments section above, I would just put all text explainers to a tooltip and only show the actual fee 
- Liking the <0.01 JOY approach 🙌  
- The fees label -> Transaction fee: (rather than just fee)
- Do we need to repeat transaction fees on both modal footer AND confirmation screen list ? There are no inputs at this stage so no fees variation, so thinking we show on all modal steps apart from last one?

Lastly:
- Would be good to see numbers component and fees updated tooltips on the same figma page, so that we can "copy-paste" this to Pioneer and ensure same approach, if that's not too much to ask 😇

**Comment by toiletgranny** [comment]
A note about things we agreed on during today's Atlas Design Weekly meeting: 
- update the copy in all tooltips and popovers mentioning fees,
- use the Number component for displaying fees,
- display the fee in the Comment input component directly, right next to the Button (instead of hiding it in the tooltip),
- put the fee information inside the tooltip in the Action bar component.

---

And so, @kdembler one more time, here's the list of changes:

- Designs, docs, and changelog for **comments & reactions** [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2140%3A135509),
- Designs, docs, and changelog for the **Action bar component** (a footer we display in _NFT minting / buying / bidding_, _Video Posting / editing/ deleting_, _Updating Membership_, _Channel Creation / Editing_) [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8477%3A161454),
   - I mentioned this change [in this PR](https://github.com/Joystream/atlas/pull/2857#issuecomment-1160498065), as you requested Klaudiusz.   
   
cc @dmtrjsg

**Comment by toiletgranny** [comment]
Too fast. Klaudiusz brought my attention to the fact that there are more flows involving fees in the app. Moving this into the backlog again so that I can review this one more time.

**Comment by toiletgranny** [comment]
Ok, guys, hopefully this third time will be a charm. @kdembler, again, here's the complete list of changes, including the new items I added just now:

- Designs, docs, and changelog for **comments & reactions** [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2140%3A135509),
- Designs, docs, and changelog for the **Action bar component** (a footer we display in _NFT minting / buying / bidding_, _Video Posting / editing/ deleting_, _Updating Membership_, _Channel Creation / Editing_) [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8477%3A161454),
   - I mentioned this change [in this PR](https://github.com/Joystream/atlas/pull/2857#issuecomment-1160498065), as you requested Klaudiusz.   
- **🆕 NEW** Designs, docs, and changelog for the **Dialog footer component** [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8638%3A171330). Once this is implemented, we can proceed with the following changes:
   - Add the fee info to the delete video alert dialog, designs for which [can be found here](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3171%3A168073),
   - Add the fee info to the remove NFT from sale alert dialog, designs for which [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5076%3A261284),
   - Add the fee info to the remove change NFT price dialiog, designs for which [can be found here](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=4924%3A266241).
