### ISSUE TITLE
[feature request] Weak Stream

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2818]
@dmtrjsg commented on [Mon May 16 2022](https://github.com/Joystream/pioneer/issues/3066)

**Taken at**: https://play.joystream.org/embedded/video/25422
**Fields**:
- Which feature are you missing?: Weak Stream
- What problem would that solve for you?: Although my internet connection is fine, the videos are cut off a lot. It loses its fluency and is distracting.
- Share your Github or Discord so we can get in touch: Erenn#5176

**Browser**: Chrome 101 (Windows 10)
**Screen size**: 1920x1080
**[Open #6 in Usersnap](https://app.usersnap.com/l/feedback/933c23a6-1476-47fb-9bbc-135035776a1c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Moved to Atlas project.

**Comment by kdembler** [comment]
This can only be distributor performance issue, should be improved by fixes in #2748 and others

**Comment by traumschule** [comment]
Not performance related but bitrate, analysed in #2760.

**Comment by kdembler** [comment]
I don't agree. The video in question uses about 1.5MB/s. It's not unreasonably big (ofc could be better) but with a good (relative, accounting for distance, etc) distributors performance, it shouldn't really be an issue.

**Comment by traumschule** [comment]
Ok, let me close the loop then and inform DP that this is a new target.

**Comment by dmtrjsg** [comment]
@traumschule what is DP in this context, pls kindly clarify :)

**Comment by traumschule** [comment]
sry js jargon, meant our distribution (bandwidth) providers. [channel](https://discord.com/channels/811216481340751934/933726271832227911/983693375599444049)
