### ISSUE TITLE
Bloat fees required for channel and video creation.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2826]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202410590420293) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
Keep in mind that all this means is that when paying for the transaction fee, `Atlas` must add an extra margin to it to cover such fees, and the values of such fees can be read from the chain state directly.
