### ISSUE TITLE
We need thumbnails to show up when sharing on Social Media

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2828]
@Delranchorecipes commented on [Wed Jun 08 2022](https://github.com/Joystream/pioneer/issues/3202)

When I try to share Joystream video links the thumbnails don’t show up. They only show half the time on facebook and 0% of the time on other social platforms where I share them.  Pinterest, google search, reddit, etc.

**Comment by dmtrjsg** [comment]
@kdembler was that not already covered, or did we only do Twitter?

Worth raising separate issues for each individual SM?

**Comment by kdembler** [comment]
Facebook should work, each link I test with works fine.

Pinterest needs its own issues since they require some specific markup just for their site.

Google search and reddit should be handled now, I added them

**Comment by dmtrjsg** [comment]
Closing as per above. Pinterest is not worth the effort as we agreed today with Klaudiusz.
