### ISSUE TITLE
Show error message if the balance is insufficient for buy now

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2872]
## Scope
- [ ] Implement insufficient funds form field validation, as soon as input is added

## Design
 Pattern is here> [According to the designs left by Tomek](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1022%3A102687)

## Context

@dmtrjsg commented on [Sat Jun 11 2022](https://github.com/Joystream/pioneer/issues/3223)

**Taken at**: https://play.joystream.org/video/26860
**Fields**:
- Which feature are you missing?: Tell me I don&#39;t have enough funds
- What problem would that solve for you?: When I open the Buy now/bid screen for an NFT, the Buy button is disabled, but its not explained why.
- Share your Github or Discord so we can get in touch: bedeho

**Browser**: Firefox 100 (macOS Catalina)
**Screen size**: 5120x1440
**[Open #18 in Usersnap](https://app.usersnap.com/l/feedback/3f7af61a-1c42-4027-a34f-238ca536c669?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@kdembler @toiletgranny 👀

**Comment by toiletgranny** [comment]
[According to the designs left by Tomek](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1022%3A102687), I can see the "Insufficient funds" message should be displayed at all times if the bid/buy now price input is populated. 

@kdembler Knowing that the bid/buy now price input field is prepopulated, can we trigger the first validation upon entering the NFT purchase view, so that we can actually display the "Insufficient funds" message? Also, once all of the most recent form component changes are fully implemented, I think we could easily unlock the "Place bid" button.

**Comment by kdembler** [comment]
Well there's no input field in the buy now mode, that's why there's no validation there currently, this also wasn't captured in the designs.

But yeah, simple fix on our end

**Comment by KubaMikolajczyk** [comment]
If input fields are in the form and one fails validation, we should display the error msg in the form field component. However, if there are no input fields and the user fails validation for a different reason we can use the snackbar component which according to design documentation should be used in such cases.

📄 Link to NFT Purchase figma changelog : https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1566%3A812637&t=4g9KBQ5ZWV8FUZf8-4
📄 Link to web components alert documentation where we have rules for such cases: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6292%3A134170&t=SCdWqjqTo1pLHFnI-4

**Comment by dmtrjsg** [comment]
Display this toaster on each click on the button: 

<img width="532" alt="Screenshot 2023-01-30 at 14 43 44" src="https://user-images.githubusercontent.com/93924525/215508576-adf12803-a583-421c-8077-9370d89a969f.png">

[LInk>](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=2615%3A27295&t=PKzxuumW3Pw0G4Zk-1)

**Comment by dmtrjsg** [comment]
Testing on Dev blocked by: 
- https://github.com/Joystream/atlas/issues/3729

**Comment by dmtrjsg** [comment]
Tested, works well for all cases 👍 

One thing Toaster notification needs to disappear after 4 seconds- > will add this separately as an enhancement
- https://github.com/Joystream/atlas/issues/3737
