### ISSUE TITLE
Input caret color is barely visible on some backgrounds

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#2914]
![image](https://user-images.githubusercontent.com/51168865/175539828-1759587d-946b-4a54-94b2-5afb8cad9ebd.png)

Maybe we should reconsider changing the input background to a solid one? We could also change the caret color to a different one.

**Comment by dmtrjsg** [comment]
One for @toiletgranny.

**Comment by iamnamananand996** [comment]
![Screenshot 2023-01-28 172524](https://user-images.githubusercontent.com/31537362/215265134-7b68bd01-dafe-4e44-913c-211880c75aa3.png)


adding carat color as **#fff** (white) will solve this problem, as we don't have light and dark modes right now, if we have that 
then, we should consider, 

- **#fff** for default mode 
- **var(--color-background-primary)** for light mode.

please assign this issue on me, I can make this changes.

**Comment by KubaMikolajczyk** [comment]
I experimented with it and it looks like a quick fix would be to change caret-color to color/text/default/strong token and it would be my recommendation. 
I changed it in the designs here: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A115828&t=KYHkyAiFIcOZJIkf-4

**Comment by dmtrjsg** [comment]
cc @iamnamananand996 @chrlschwb @attemka

**Comment by iamnamananand996** [comment]
okay, what I can understand from figma design is to have caret-color: **#F4F6F8**, Please confirm Is that correct ?,
then, I will make this change.
cc - @KubaMikolajczyk
