### ISSUE TITLE
Reduce number of skeleton loaders in replies

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#2932]
I've noticed, that even though we know in advance how many replies particular comment has, we still showing more skeleton loaders than the replies. This causes a slight layout shift. For example:
1. Comment has 2 replies(
2. User clicks `show 2 replies`
3. User sees 4 skeleton loaders
4. What's the point of seeing 4 skeleton loaders here? We already know, how many replies the comment has. There should be only two skeleton loaders below the comment. 

https://user-images.githubusercontent.com/51168865/176388660-4dd6c1be-0288-4131-9ca9-df97e09b27ea.mov

**Comment by dmtrjsg** [comment]
Awaiting approval from @toiletgranny

**Comment by toiletgranny** [comment]
Sounds like a no brainer to me, let's do it! ❤️

I didn't know we have the number of replies upfront. Also, we were supposed to display just one skeleton loader for fetching replies, [as per designs](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2282%3A163661), but I guess I must have missed that when reviewing the implementation.
