### ISSUE TITLE
Switch Member

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2946]
## Scope

![Screenshot 2022-06-30 at 16.57.54.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/6701df8d-9cfb-40c5-9f78-6337d29d17cd)

## AC

- [ ] Select membership added to channel and viewer drop downs

## Design
[Link to designs](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3201%3A111989)

**Comment by kdembler** [comment]
This is already implemented, unless I misunderstand @dmtrjsg
