### ISSUE TITLE
Test New Wallet Implementation on Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2948]
## Context

Talisman wallet / signer is now implemented and released to production

Designs: https://github.com/Joystream/atlas/issues/2817
PR: https://github.com/Joystream/atlas/pull/2901

## Scope

- Perform QA of the released feature with multiple accounts and wallets [polkadot.js, talisman, subwallet], with/ and without previously created accounts. 

Specific scenarios covered here:
- https://github.com/Joystream/atlas/issues/2070

**Comment by dmtrjsg** [comment]
+ Specifically these scenarios:
- https://github.com/Joystream/atlas/issues/2070

**Comment by ivanturlakov** [comment]
Hi @dmtrjsg! Does this need to be tested on prod, or do we have a staging for this?

**Comment by dmtrjsg** [comment]
@ivanturlakov thank you for clarifying, its already on prod so better to do it right there 👍

**Comment by ivanturlakov** [comment]
Tested on prod

macOS Monterey 12.4
Chrome 103.0.5060.114, (x86_64)

Scenarios #2070

1. Polkadot account with JS membership not picked up instantly after being added in the extension - !

https://user-images.githubusercontent.com/46903215/177971967-e30f0379-b640-4c8d-b437-42e763373dea.mov


https://user-images.githubusercontent.com/46903215/177972354-0e8e05d1-a0b2-4234-a477-3147d55e5440.mov


2. The "Sign in" button not working when I remove/hide my Polkadot accounts in the extension - Fixed
3. Membership dropdown remains open even after I remove/hide all of my Polkadot accounts - !

https://user-images.githubusercontent.com/46903215/177973665-1c5ae44f-4700-407e-97df-1a46f9fd4433.mov



Talisman new acc:
- Error when creating a member 
<img width="1440" alt="429_error" src="https://user-images.githubusercontent.com/46903215/177974231-aadf59fa-6d0b-452b-a8d4-75fe872d7b99.png">


SubWallet new acc:
- Error when creating a member
<img width="1440" alt="429_error_sub" src="https://user-images.githubusercontent.com/46903215/177974281-76b9e826-a3cd-4d53-9208-2447ddc747a6.png">

**Comment by dmtrjsg** [comment]
@kdembler @toiletgranny 👀 smth for us to discuss on Monday

**Comment by dmtrjsg** [comment]
Discussed and arrived to conclusion that all of these are not likely to occur outside of testing, and if they do there is no damage for the ux.

Re last one @ivanturlakov, the 429 issue is a safety mechanism to prevent users from abusing the faucet. The account gets unlocked after cooldown period. 

One to fix tho:
Adding toaster notification on signing in existing wallet "Welcome back"..  https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=1281%3A32654

**Comment by ivanturlakov** [comment]
> Re last one, the 429 issue is a safety mechanism to prevent users from abusing the faucet. The account gets unlocked after cooldown period.

It looks fair for Talisman, as I created the first account, then tried to create another, and get a 429 error. But for SubWallet I cant create even one. Not sure how long cooldown period is(5 days for now), tried to create a new acc and still get 429 error(Talisman & SubWallet).


In this case, I disabled Polkadot & Talisman extensions, only SubWallet is active.
<img width="494" alt="Снимок экрана 2022-07-13 в 13 58 16" src="https://user-images.githubusercontent.com/46903215/178721280-ceaa4080-6865-48c1-9c01-c7870a785626.png">

**Comment by dmtrjsg** [comment]
@ivanturlakov that may stem from the fact that we are using Talisman lib and they have not included Subwallet just yet.. @kdembler  is best to confirm.. but if that is the case, we can look into adding a line of explanation that subwallet-js will be supported once added to Talisman native library Smth like "Coming soon"?

**Comment by kdembler** [comment]
@ivanturlakov The cooldown is based on IP address, not wallet address, that's likely why even the first attempt for SubWallet fails for you - you got your quota filled by creating a membership for your Talisman account.

@dmtrjsg That's not related
