### ISSUE TITLE
Sometimes thumbnails don't load on chrome

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#2957]
A couple of people reported that sometimes thumbnails don't load. It seems that it's happening only on chrome, and most often on incognito mode(?).  Unfortunately, I don't know the exact steps to reproduce, but it's worth checking what's wrong. 
This is a console output when this is happening: 
![image](https://user-images.githubusercontent.com/51168865/177108424-42e6cca0-ba4a-4955-bd82-3ddadd398b6b.png)

I think investigating `assets.manager.tsx` is a good place to start.

**Comment by dmtrjsg** [comment]
could not reproduce, will keep in the backlog for the time being

**Comment by kdembler** [comment]
Closing until we have more details to reproduce
