### ISSUE TITLE
Design Spike: calculate impact on existing assets and calculate effort to change for Atlas mainnet launch re-branding

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2959]
## Context
This

* https://github.com/Joystream/atlas/issues/2512

## Scope
* [ ] Collect all assets that would potentially require branding change 
> (as links to figma, provided as comment to this ticket)
* [ ] Calculate effort to update from the design pov
*  [ ] Populate design links and description to this issue- https://github.com/joystream/atlas/issues/3021

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202547849278728) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Ok, @dmtrjsg, @bedeho, @mrexpat, @kdembler, here's the video update on how I see our options at the moment. https://www.loom.com/share/0e26109a10c2432695c1e7bfe2a56f7d


TL;DW, given the circumstances, my recommendations are as follows:
1. **Name:** Let's stick with Atlas as a name for `play.joystream.org`,
2. **Domain:** Depending on the budget, we can either try acquiring `atlas.watch` for $2,000, or — if we need to be more price conscious at this point — we can keep looking for ideas for a combined domain name, such as `atlasapp.com` (this one is, sadly, very much taken)
3. **Logo:** I recommend version B — [link](https://www.figma.com/proto/ySdq2CbxHPMNs9IpJNXBIJ/Atlas-Brand?page-id=2%3A22566&node-id=2%3A84078&viewport=322%2C372%2C0.29&scaling=min-zoom&starting-point-node-id=2%3A84078&show-proto-sidebar=1) (other versions can be previewed from the left-hand sidebar in Figma).

**Comment by bedeho** [comment]
Love it!
- Happy to stick with `Atlas`
- Also agree with your logo choice.
- Thanks for doing the background work on the domain! It may be worth spending a bit here, so perhaps @dmtrjsg could take the lead and speak with the various alternative owners? I think we should try to even speak with .com and .app to start off as well.

**Comment by mrexpat** [comment]
When approaching domain owners its best to approach them from the "small 1man band" perspective versus "serious start up with $13m in funding", as they'll adjust the price accordingly. Best to make them a decent offer, not an insulting one, but not come off as a well funded buyer.

**Comment by toiletgranny** [comment]
@dmtrjsg To move this issue into the Design Review column, as a short summary, having both name and the logo already approved, all that is left to do is:

- Exploring and discussing together that capital "A" alternative version you asked for (~60 min),
- Updating components & flows (~60 min):
   - [Adding Atlas logo as a component here](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=716%3A70391),
   - [Updating the top navigation component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3173%3A135755),
   - [Updating the Side navigation component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=4322%3A173750),
   - [Updating the Sign in flow](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in?node-id=0%3A1),
   - [Updating the logo in the embedded variant of the Video player component](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2090%3A120662).
- Syncing with an engineer to go through the code, find, and replace all instances of the previous name (~30 min).

My understanding is that we'll tackle all points in https://github.com/Joystream/atlas/issues/3021.

**Comment by dmtrjsg** [comment]
Thank you for this Adam!
