### ISSUE TITLE
Lo-fi for Joystream.org Landing Page for Mainnet launch

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2961]
## Context
* https://github.com/Joystream/marketing/issues/259

:info: This issue will get migrated to Marketing repo. Raising in Atlas while waiting for access rights and Zenhub integration with marketing

## Scope

- [ ] Low-fi mockups with structure and components variations to be able to cook a version for adding fidelity and reviewing with users.

Preview:
![Screenshot 2022-07-04 at 13.53.32.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/8fa8bd96-2d79-4e55-a398-e5452aa9eff9)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202548029534675) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
The low-fi mockups for the Joystream.org homepage, which we've been discussing over the last two weeks, can be found here: https://www.figma.com/file/3uoobZkRhFF4yibFjCWa2D/Joystream-%7C-Website?node-id=5523%3A129022
