### ISSUE TITLE
[USERSNAP] Loading....

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2966]
## Scope

- [ ] Display component that App waits for user action in the Extension (sign)

## Context
__________
dmtrjsg made a clone from related Pioneer issue [Sat Apr 30 2022](https://github.com/Joystream/pioneer/issues/2948)

## Scope
* [ ] Create design pattern (modal?) for handling extension response pending states
* 
* 
* 

![](https://user-images.githubusercontent.com/93924525/177380777-9d4e9001-4601-40cd-ad42-b3ace42bf954.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202555745652802) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
I don't understand

**Comment by dmtrjsg** [comment]
We have a prompt on atlas to handle this @bedeho 

Examples below is on placing bid and for adding comment:

<img width="531" alt="Screenshot 2022-07-19 at 12 17 39" src="https://user-images.githubusercontent.com/93924525/179737827-56c6d743-780c-4806-8ea4-a3874ab1dcc8.png">

<img width="424" alt="Screenshot 2022-07-19 at 12 18 45" src="https://user-images.githubusercontent.com/93924525/179738040-d7532044-9556-442c-a867-ca59a9c57935.png">
