### ISSUE TITLE
New name for Atlas

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#2971]
# Background
As part of https://github.com/Joystream/atlas/issues/2959, we've agreed to create a new name & logo for Atlas, for reasons described by @bedeho in https://github.com/Joystream/atlas/issues/2512.

# Scope

**The goal of this task is to, just like with the [base unit name issue](https://github.com/Joystream/joystream/issues/3389), use the creative powers of the Jsgenesis team and collect new Atlas name ideas internally.** 👀 This is so that we can later pick the top X ideas and do final voting with the entire Joystream community on Discord. All ideas are welcome at the moment, there are no specific constraints. 🚀 Let's see what we got, first.

### Inspiration
As an inspiration, below is a random collection of already existing names used in the Joystream project.

- **Project name:** Joystream,
- **Current consumer-facing app name:** Atlas
- **Governance app name:** Pioneer
- **Token asset name:** JOY
- **Base unit name:** HAPI
- **Past releases names:** Carthage, Rhodes, Olympia, Giza, Sumer, Antioch, Babylon, Alexandria, Nicaea, Constantinopole, Rome, Acropolis, Athens, Sparta.
- **Other _decentralized_ video sharing platforms/projects:** LBRY/Odysee, LivePeer, Dlive, Verasity, BitChute, D.Tube, Theta.tv, Chainflix

**Comment by drillprop** [comment]
Actually, I kinda like just... `Atlas`. Maybe I got used to it. 
The downside of this name is the fact, that it will be hard to associate a video platform with the titan from Greek mythology 😄

**Comment by toiletgranny** [comment]
I can't say I don't like this name, either, frankly speaking. And since there are no other ideas, let's see what we can do with the Atlas name. 

Of course, a dozen other products and services already go under this name, but, as per my quick desk research, I don't think we should be concerned about any of the ones in the tech industry ([1](https://atlasapp.com/), [2](https://atlas.app/en), [3](https://www.atlas.net/)). (cc @mrexpat)

The main challenge I can see is the domain name. All the popular choices are already in use, such as:
- atlas.com (for sale),
- atlas.video (for sale),
- atlas.app,
- atlas.io,
- atlasapp.com,
- playatlas.com,
- atlas.net,
- atlasplay.com (could be for sale),
- atlas.org (could be for sale).

According to name.com, ".JOY domains are pending release", which means we could try getting **atlas.joy**. But I couldn't find any information on when the registration begins exactly, nor do I have knowledge of whether registering a .joy domain comes with any risks. 

Since domain names are not my main field of professional expertise, @kdembler do you see any other opportunities for us to go forward with the Atlas name while having a decent and memorable domain name?

**Comment by kdembler** [comment]
I'm not really a domain expert, but I don't see any additional opportunities. I think personally I would go with a different name than Atlas since this is already the software's name, but I don't have any good suggestions.

**Comment by dmtrjsg** [comment]
Maybe we can post this question to the community on Discord? I don't have a strong candidate, and already got used to Atlas 😇

**Comment by drillprop** [comment]
@dmtrjsg I thought we already asked?
@kdembler made a good point about the name Atlas, completely forgot about it. Maybe we could figure something with the word `joy`  as a suffix or preffix.
