### ISSUE TITLE
Spike: how help video creators migrate their videos manually?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2980]
## Context

Assist Youtube channel owners to migrate their content manually before automation is available through youtube sync service. 

This ticket is aimed on figuring out what can we get away with relying on Front end mostly or entirely: Crawler/ API to fetch assets meta and pre-populate forms/ file impex/ other way?

- Compare youtube video structure with our own video. See how we could populate our video form with youtube data?
- What are the API endpoints that would be used to get that data?
- What permissions do we need from the API?

https://developers.google.com/youtube/v3/docs/channels

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202570034961603) by [Unito](https://www.unito.io)

**Comment by rafalpawlow** [comment]
## How can we help video creators migrate their videos?
We could make it possible by creating drafts from fetched results from Youtube API.
I believe we could create a modal in which the user provides the api key, name or id of the channel, based on which we can create a list of drafts.

## Compare youtube video structure with our own video. See how we could populate our video form with youtube data?
* Youtube data structure contains everything we need to create draft: `title`, `description`, `category`, `language`, age restriction

## What are the API endpoints that would be used to get that data?
* https://www.googleapis.com/youtube/v3/search
* https://www.googleapis.com/youtube/v3/videos

## What permissions do we need from the API?
* user will have to create api key in Google API Console

## Problems and inconveniences
* we will have to translate youtube category id to ours
* we will not able to transfer license, user will have to do manually
* not sure what to do with assets, theoretically we could take at least thumbnail from YT API
