### ISSUE TITLE
Atlas Video Sorting (Newest to Oldest) Bug?

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/atlas#2986]
**Describe the bug**

I think there is bug when you sort My Videos from Newest to Oldest or vice versa.
Similar with Youtube, I expect it to sort videos from newest uploaded to oldest uploaded one or vice versa
However, it seems the 'Newest/ Oldest' function sorts videos based on editing date not uploading date.

**To Reproduce**

1. Go to Joystream Atlas 'My Videos'
2. Click 'Newest'
3. Choose one old video, edit description or any details and save it.
4. Navigate back to list of videos.
5. Check order of that edited video.

**Expected behavior**

You will see that the old edited video suddenly becomes the newest video in your list

**Screenshots**

Before editing an old video: https://drive.google.com/file/d/1CqMnOB1If_nR7aVDd0Txt4Vatf-YLHTn/view?usp=drivesdk

After editing an old video: https://drive.google.com/file/d/1O-CC_kfvhEsJE6zzdAaENCp46HN6RijK/view?usp=drivesdk

**Device (please complete the following information):**

- I use Windows

**Additional context**

N/A

**Comment by drillprop** [comment]
@Songoku1691 thanks for creating this issue and pointing this out. This is a bug in the query node, which is already fixed, but not deployed yet. 
All the videos should be displayed in the right order on the next major release.

**Comment by Songoku1691** [comment]
Thanks for information Sir
