### ISSUE TITLE
Personalisation v2

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#30]
# Personalisation in Atlas: v2

## Background

The current version of Atlas being built is an identical experience for all users in that it is not impacted by user state in any way. This is of course very limiting, and this issue attempts to describe a design that may allow us to make the first steps in the direction of personalisation. The design is still based on the base established here

https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=730%3A5283

## Deployment

It is as of yet unclear how this will be deployed, but most likely this will not require altering the runtime in any way, but may require some new temporary Jsgenesis hosted infrastructure. This will have to be determined later.

### Client-Side Only User State

We will not have any server side hosting of user state, hence it will all live in local storage. This has the implication that clearing the browser history, or going to a private session, or going to a new browser, or a new device, all implies that prior user state will not be transferred over. It is not clear what long term approach to take. An implication of using local storage is also that there are no accounts and corresponding signup, login and logout flows.

#### Adding Follower Count

Orion needs to be extended to not only hold content view counts, but also hold representations about follower relationships, so who followed what channel when.

All queries and mutations are through a GraphQL API still.

#### Event Data Model

Currently we have a state based data model for content view counts, so we only represent the cumulative view count for each content item. We now want to transition from state to event based model, so that we maintain much richer information that facilitates much richer queries and Sybil prevention.

#### Actor Identification and Authentication

The lack of any events has meant that we did not represent any form of actor in the data model, however, now it makes sense to introduce this in some way, but we can do something trivial like using the remote host. This is not stable in any meaningful way, but it may have value for simple debugging and analytics purposes for now. In the future we will probably add some incrementally more sophisticated identification and authentication scheme on top of this.

#### Hosting

There will still only be a single hosted Orion instance operated by Jsgenesis for this release.

### Content Directory

We need help from Leszek on these points:

1. Introduce curator updatable information about the current hero section featured video.
2. Introduce a separate channel category type, similar to video categories, and associated each channel with such a category.
3. Introduce featured channels.

### Query Node

We need help from Metin or Arsen on these points:

1. Needs to be updated to support channel categories.
2. Needs to be updated to support hero section featured video.
3. Needs to be updated to support featured channels.

### CLI

We need help from Leszek on these points:

1. Needs to be updated to support channel categories.
2. Needs to be updated to support hero section featured video.
3. Needs to be updated to support featured channels.

### Migration

None. Channel owners will need to bind their channel to a category, but no migration is required due to content directory schemas.

### Home Screen

The home screen, also referred to as the "landing page" internally, has the followings structure, going section by section from top to bottom.

1. **Featured Content:** Same as today.
2. **Continue Watching [carousel]:** If the user has started, but not completed, watching at least one video, then the continued watching section should include this video in the carousel. If there is no such video, the section is omitted. No _See All_.
3. One of the following (No _See All_):
-  **From Channels I Follow [infinite scroll]:** All videos available across all channels the user follows published no more than Y days ago, if at least some number X, otherwise skipped.
- **Recent Videos [infinite scroll]:** All videos available across all channels, listed in reverse chronological order.

### Videos

Exactly the same as the current "Browse" screen for the Babylon release, except

- title is "Videos"
- a carousel, titled "Featured", between the title and the category selector, which contains a set of featured videos. These videos are not from a single category, which is part of the reason why this carousel lives above the category selector. We can play with allowing these videos to be larger than the videos in the infinite scrollers also. When scrolling, these videos are, like the page title, only visible when at the very top of the page, unlike the category selector.
- introduce an "All" meta category which is selected by default.
- videos are ordered by most recently created first.

### Channels

Exactly the same as current "Browse" screen for the Babylon release, except

- title is "Channels"
- a carousel, equivalent to the featured videos carousel, except for channels.
- introduce an "All" meta category which is selected by default.
- channel are ordered by most recently created first.

#### Presentation

- UI for all states: https://github.com/Joystream/atlas/issues/17
- UX
  - Remains stable during scrolling of the main page
  - Entirely hide when on playback mode, only allow opening when hamburger menu is clicked, but have flow over, like on the design

#### Structure

- Home
- Videos
- Channels
- In-lined list of channels you follow, as below:

![Screenshot 2020-10-10 at 11 54 39](https://user-images.githubusercontent.com/437292/95663969-f5d4a400-0b43-11eb-8179-780a3d418e1a.png)

#### Old Top Menu & Search bar

- Drop the icons, but don't introduce the <> buttons that were primary added for Electron variation
- center search bar, as in the original design.
- make search bar escapable, as in the original design, w.r.t this => https://github.com/Joystream/atlas/issues/23
- show search history, as in the original design, using local state.
- up to date transitions for search bar entry, search and exit.

### Miscellaneous

- https://github.com/Joystream/atlas/issues/18
- https://github.com/Joystream/atlas/issues/133
- https://github.com/Joystream/atlas/issues/138 

## Milestones

**Please suggest rough outline of who does what in what order.**

**Comment by kdembler** [comment]
Looks good and looks fun. I think it may actually be more work than the initial one, but that's fine with me. Some questions I have:

1. Just to clarify, we want to remove what we currently have on the landing page and replace with what's in the issue? So remove the newest videos, newest channels, etc.
2. Regarding the menu you've said `Entirely hide when on playback mode, only allow opening when hamburger menu is clicked, but have flow over, like on the design`. I'm not entirely sure I understand. The hamburger button appears as part of the menu itself so not sure how it can be "entirely hidden".
3. Also regarding the menu, should `Videos` and `Channels` be "major" entires in the menu or part of the `Browse` section as seen here:<br><img width="359" alt="Screenshot 2020-12-14 at 12 08 35" src="https://user-images.githubusercontent.com/12646744/102074454-1d2a4480-3e05-11eb-9b3d-0996fb5a99e7.png">
4. You've said `make search bar escapable` - does that mean the entire search view should function as on overlay? That is, when viewing search results you can close them to reveal what you've been previously looking at? We can explore that way but there are some other problems associated with it. For example, how does the navigation work w.r.t. the URLs. When you open the search overlay, does the URL just stay the same or change to the search URL. There may be other hidden issues like that. I'd actually postpone that work for now, we can do recent searches with how the search view currently works as well.
5. ~More of a note than a question, the logic for `From Channels I Follow/Recent Videos` infinite scroller will get complicated and will require 2-3 network requests just to know what to show.~ Combing back to it, this shouldn't be that complex 

Added later:
6. How should we communicate the required changes in Content Directory/Query Node/CLI? Who should be creating issues for those and who should communicate with associated people/teams?
7. Where should the `In-lined list of channels you follow` be displayed? I don't think it's included in any of the designs?

**Comment by kdembler** [comment]
Also, how should we communicate the required changes in Content Directory/Query Node/CLI? Who should be creating issues for those and who should communicate with associated people/teams?

**Comment by kdembler** [comment]
One more, where should the `In-lined list of channels you follow` be displayed? I don't think it's included in any of the designs?

**Comment by kdembler** [comment]
Tracking issues that should contain all points raised here:
- #159 
- #155
- #157
- #166
- #167

**Comment by bedeho** [comment]
1. Yes.
2. Sloppy wording, really just meant this: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=1009%3A1927
3. Yes, we only have major entries, no minor like in that preview.
4. No, the URL is unaffected by simply engaging search, its not important to _link_ to an open search view any more than an open menu drawer, in particular because the actual recent searches will be different for each user. I guess it _could_ be of value to link to executing a search, but I dont think that is urgent at this point. So we could just go with no allaround. You will have to fill me in on what other issues you are concerned about then.
5. ok.
6. yes,make issues, very good idea in order to get full scope more clearly.
7. Indeed, design will be done.

**Comment by kdembler** [comment]
All done :)
