### ISSUE TITLE
Operator specific content reporting (BE)

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3002]
**Scope:**
- Add a GraphQL mutation in Orion to allow to add reports for malicious videos
- Orion saves that somewhere in the database
- There's a query that allows you to get all the reports (maybe some simple filtering)
- Add throttling based on IP address to limit abuse (for example 1 report/1 IP/1 minute)
- Database record should be something like this:
```json
{
  "reporter_ip": "127.0.0.1",
   "video_id": "123",
   "rationale": "I don't like the man's voice",
   "created_at": "2020-01-01T01:01:01Z"
}
``` 

---

# Background
Different Atlas instances will want to exercise different policies about what to screen, moreover, the Atlas instane may not want to rely on the timeliness of the DAO curators to enforce curation, even if policies did match for a given piece of content. For this reason, it would be useful for each instance to be able to accept incoming reports from users of their app directly. The actual enforcement of app level screening is presumed to be feasible by some other app level blacklist.

# Proposal
Add a sort of "report" button to each piece of content, which can serve as away to capture any complaint about content, being DMCA or just anything else. Should launch a form in the application where use can manually enter a message, and then this message is sent to some backend API which is supposed to capture this in some database or something. The API and database should be external to this core feature, and for Jsgensis Atlas we can just do something simple list AirTable or something.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202622762244683) by [Unito](https://www.unito.io)

**Comment by bedeho** [comment]
I'm not sure I agree that this really should have been bundled with Orion? Couldn't we just ahve allowed the person to use whatever old endpoint they wanted to capture this into their bespoke data/analytics solution, rather than adding extra work on our end and being very opinionated about how data is stored?

**Comment by kdembler** [comment]
> Couldn't we just ahve allowed the person to use whatever old endpoint they wanted to capture this into their bespoke data/analytics solution, rather than adding extra work on our end and being very opinionated about how data is stored?

Sorry I don't understand, what do you see as an alternative? What is "extra work" on our end? If not Orion, something else would need to capture this data. Also I don't fully understand how we're very opinionated about data, we need to pick _some_ schema for the time being right? I'm also not sure what "whatever old endpoint" you are referring to.
