### ISSUE TITLE
Sending transaction is not working on production build

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3005]
To reproduce:
1. run yarn atlas:build
2. go to `atlas/packages/atlas/dist` and run `npx serve`
3. If you leave a like to a video you'll get `No joystream instance` in the console
4. Similar thing will happen when you try to do something else like upload a video or update a channel. 
You'll experience the same in our vercel deployments - https://atlas-cukdlawf5-joystream.vercel.app/ 

Probably worker related bug: 
![image](https://user-images.githubusercontent.com/51168865/179707939-6b553f25-52ee-4fba-88c9-354c25684fba.png)

**Comment by rafalpawlow** [comment]
This issue may be related https://github.com/vitejs/vite/issues/4646
