### ISSUE TITLE
Idea: Improve Show More, Show Less Button of Video Description Details

### ISSUE THREAD

**Issue by Songoku1691** [Joystream/atlas#3006]
**Is your feature request related to a problem? Please describe.**

Yes, when you check video description of Atlas and click 'Show More/ Show Less' paragraph spaces are gone. So the video description becomes 1 continuous line.

**Describe the solution you'd like**

I hope paragraph spacing remains even after you click 'Show More/ Show Less' 

**Additional context**

Please check this video illustrating the issue:
https://play.joystream.org/video/27086

**Comment by kdembler** [comment]
Already fixed
