### ISSUE TITLE
Placeholder screen for Channel Payouts module

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3012]
## Context

New homepage for joystream.org will feature payments module screenshots, while the feature is planned to get delivered only after mainnet. To avoid the discrepancy between the homepage and atlas features, the proposition is to add a placeholder screen for the Payments module to inform users.

## Scope
- [ ] Add payouts module to top nav 
> suggest to consider the "coming soon" treatment in the top nav as well, not the same but similar to how that is done on Pioneer for upcoming modules
- [ ] Add a placeholder page for payouts module, featuring some key screens designs and copy informing users that while payments and withdrawals are available from your channel balance, the payments dashboard it is currently worked on and coming soon

**Comment by toiletgranny** [comment]
Hey, @dmtrjsg, let me know if the below will do. 

![image](https://user-images.githubusercontent.com/35307309/182875330-cc01019f-2458-4767-b877-0cb41d35d66d.png)

If this is ok then @kdembler, the RWD screens can be found in [this Figma file](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1917%3A30454), and all illustrations are already placed in the [Figma API -> Storybook](https://www.figma.com/file/1uxugLps6oooI38PGmdrn9/Figma-API--%3E-Storybook?node-id=1007%3A310) file.

**Comment by dmtrjsg** [comment]
@toiletgranny  @kdembler 

Suggest a tweak on the copy.

"Payments Dashboard is coming soon. Stay tuned." for H1. 

"Payments module will give you an overview and analytics of all proceedings to your channel balance, earned from selling NFTs,  earning royalties, investment to your creator tokens by your audience and incentive rewards granted by joystream DAO council. Withdrawals to your personal account can be handled here." for H2

**Comment by toiletgranny** [comment]
I tried to use simpler language, keeping in mind our non-native English users in mind, which makes me a bit worried about words such as "module" and "proceedings" and the overall technical complexity. But if both of you guys find this body copy more appropriate, I'll change it immediately! :)

Also, do you think we could keep it shorter for the main header, perhaps dropping the "Stay tuned" part? The reason is that, in general, we don't really use full sentences, and therefore, dots in the headings of Atlas.

**Comment by kdembler** [comment]
I really like the simplicity of copy @toiletgranny already used, easy to read

Maybe we also do a similar placeholder screen for creator tokens for the users to stay tuned?
