### ISSUE TITLE
Modular Atlas

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3020]
# Background

Atlas has, or is getting, a mix of features which may not be fully relevant to all deployments, e.g.

- YouTube partner program: only really relevant for Jsgenesis instance just now, but perhap some others will want to run one if they somehow coordinate on not duplicating.
- NFT features
- Upcoming creator token features
- Fiat onboarding features

A given instance may not want to put all of these into production at the same time.

# Proposal

Allow for for Atlas operator to disable certain logical subsets of features. This should be kept simple for now, and pausing could easily just be at the UI layer, no in the guts of the product. Such a feature would possibly be quite important if we are going to take seriously the idea of having multiple operators in the near term.

**Comment by bedeho** [comment]
Similar idea here: https://github.com/Joystream/atlas/issues/2306

**Comment by dmtrjsg** [comment]
@bedeho 

Leaning towards making these provisions for the future features, but perhaps not the ones that we've built already.

❓ is why someone would not want to just fork the app and do it themselves for NFTs or Creator tokens that are so much part of the web3 world anyways.

**Comment by bedeho** [comment]
>  is why someone would not want to just fork the app and do it themselves for NFTs or Creator tokens that are so much part of the web3 world anyways.

Are you asking why would someone want to remove these features? I could certainly see that they could, if they are differentiation based on content vertical or have some other focus, and it has already been requested, so seems plausible to me. But anyway, the core here is not even about NFTs or creator tokens. In general, being able to have _some_ control over what features are part of the deployed app will be needed, the questoin is only which specific features should we try to modularise away, and this depends on cost and complexity of doing so vs. prospective value. For example, the fiat onboarding seems like a nobrainer, because not everyone wanting to run an app will be willing or able to establish a commercial relationship with our fiat onboarding provider.

**Comment by dmtrjsg** [comment]
Yep, discussed exactly that with @kdembler and for all of the non-NFT features we agreed to take on this approach subject to reasonable effort. I will relay to you if we are not going to modularise the upcoming features. NFTs seem to be a little to expensive to refactor at this time around. 

@bedeho Since this proposal is fully acknowledged and triaged, closing the issue as completed. NFT refactoring would probably be coupled with other features (like more flexibility on content dir etc.)

Would you suggest to "modularise" the Payments module as well?

**Comment by bedeho** [comment]
> Would you suggest to "modularise" the Payments module as well?

No I don't think that is important enough to just do outright.
