### ISSUE TITLE
Disabling comments not working for NFT 

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3025]
Once the transaction is done, we're getting an error: 
![image](https://user-images.githubusercontent.com/51168865/180944711-cb120973-f8f3-4f71-bbd2-d437b6ad54cd.png)

**Comment by kdembler** [comment]
We probably include nft issuance options again even though the NFT already exists and it fails

**Comment by rafalpawlow** [comment]
I'm closing it regarding to https://github.com/Joystream/atlas/issues/3032
