### ISSUE TITLE
Update VideoForm to not allow any editing after NFT is minted

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3032]
As part of Carthage release, all video edits are disabled after an NFT for that video is minted. We should update designs and implementation of the video workspace to accommodate that.

**Comment by toiletgranny** [comment]
Hoping for this to be an intermediate state, I added a temporary variant of the video workspace based on the above description, without updating user stories for playlists and subtitles. The design [can be found here](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=308%3A5753).

Inspecting the designs, please note:
1. The updated copy about video settings immutability in the Banner component,
2. The updated order of displaying video settings,
3. The lack of a primary "Publish changes" button at the bottom of the video workspace; just the "Close" secondary Button component instead.

@kdembler over to you!
