### ISSUE TITLE
Operator Specific content reporting (Form)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3036]
**Scope:**

- [ ] Add channel reports to Orion (exactly the same as video reports)
- [ ] Make "rationale" field required in Orion (both for videos and channels)
- [ ] Add video reporting to Atlas (https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5886%3A294312, skip "Retry" in snackbar)
- [ ] Add channel reporting to Atlas (https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1504%3A124858)
- [ ] Create component for the report form that can be used in both cases above
- [ ] Integrate with Orion

---

Front end/ Design to support this ticket :

https://github.com/Joystream/atlas/issues/3002

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202676097388424) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Ok, @dmtrjsg, @kdembler, just to help me understand the scope better:

1. In his proposal in #3002, @bedeho mentions adding "a sort of 'report' button to each piece of content". First off, I just wanted to confirm it's only videos we want users to be able to report at this point. No other type of content. **If this is true, please carry on to the second point and disregard what's below.**
     - Unless we're thinking of having a general, floating (?), kind of a "Report" button, similar to the "Feedback" one from Usersnap, I'm afraid we would need to make a list of all types of _reportable_ content, so that I can start thinking of where should we put that "report" button/link for each content type, separately. Which, as it now occurs to me, is not a trivial amount of work. Anyway, my best guess is that we want to allow users to report:
             - Videos,
             - Comments,
             - Playlists,
             - Channels,
             - Members,
             - Assets, such as avatars and cover photos (?).
2. I remember we talked about it briefly on Monday, but I just wanted to check if nothing has changed since then in that regard, namely: we still have no specific needs for things we need to ask the user about in a report, other than the rationale, which is mentioned in #3002? Are we open to go an extra mile (or rather a few extra feet) to explore what other things we could be potentially asking reports for? Such as a category for the report?

**Comment by bedeho** [comment]
> I just wanted to confirm it's only videos we want users to be able to report at this point.

No I think it has to be channels as well. Like say someone has a really problematic channel cover photo, I think the operator would want to aleast have this sort of alert crowd sourced by the audience through the repoting system. I don't know that we need to make this super granular, like distinguishing the channel cover photo vs avatar, more like just "report channel" for everything.

> - Videos,

Yes.

> Comments,

No, this is not easy for operator to control, and the video owner can more directly moderate, and has a reason to, also with more context.

> Playlists,

I would skip this also, not clear that its really needed as distinct from the videos.

> Channels,

Yes.

> Members,

Seems less important, perhaps in the future?

> Assets, such as avatars and cover photos (?).

No.

**Comment by kdembler** [comment]
Regarding the second point, I would just use a rationale for now, I don't expect the volume to be too big to handle without filtering for now and also that's what we did for our backend implementation. Although if you strongly think that we should add it, I'm fine with it too

**Comment by dmtrjsg** [comment]
Initially I was pushing for category, but classification is arbitrary and I'm with Klaudiusz on rationale would be sufficient for the starting version.

**Comment by toiletgranny** [comment]
@dmtrjsg, I read your comment right after finishing my video update! 😅 Well, let's see if I manage to change your minds about categories. The 9 min video update can be found here — https://www.loom.com/share/85f247bb9b224cc9817a703331baedbd

Figma prototype link is here — https://www.figma.com/proto/q7mCoVOG80kXsR8BzZWk4T/Operator-specific-content-reporting-(Form)?page-id=802%3A5357&node-id=1201%3A166661&viewport=545%2C450%2C0.33&scaling=scale-down&starting-point-node-id=1201%3A166661&show-proto-sidebar=1

cc @kdembler @bedeho

**Comment by kdembler** [comment]
Thanks for the update Adam. I think we're still gonna skip category for now but it's good to have the design reference for later ;)

**Comment by toiletgranny** [comment]
@dmtrjsg this task wasn't ready for devs, I'll move the issue to the Design Review column once it is

**Comment by dmtrjsg** [comment]
Ah forgive my itchy finger @toiletgranny

**Comment by toiletgranny** [comment]
@kdembler Alright, changes are ready to be reviewed and implemented! Designs, docs and the changelog for Video & Channel pages can be found under below links:
- [Video page](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5886%3A325024),
- [Channel page](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1510%3A129633).

**Comment by kdembler** [comment]
Lovely, thanks!
