### ISSUE TITLE
Lots of requests are sent on homepage

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3048]
If you check the network tab you'll notice that we are asking about `videoByUniqueInput` ~20 times. This doesn't happen on `play.joystream.org`

The issue was probably introduced in https://github.com/Joystream/atlas/pull/3003

**Comment by rafalpawlow** [comment]
The problem is that we need `fullVideo` for nft context menu in video tile. I think easiest way to resolve this is to include `nft` object to `basicVideo`. WDYT @kdembler ?

**Comment by kdembler** [comment]
> I think easiest way to resolve this is to include nft object to `basicVideo`

I would really prefer to not do this if possible.

This wasn't an issue previously, what has changed? Was this introduced by your PR with changes to the context menu? What data specifically do we need now that wasn't needed before?

**Comment by rafalpawlow** [comment]
@kdembler Yes, this was introduced by my PR with context menu changes. Previously we didn't need any NFT data in viewer video tile, but since we add nft actions to it, we need to fetch whole NFT object.
