### ISSUE TITLE
Claim Channel Payment Flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3053]
## Context
Originating Epic

* https://github.com/Joystream/atlas/issues/2401

## Design
Link to Figma > [LINK](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1547%3A19340)

## Scope
* [ ] Claim CTA
* [ ] Modal to review fees
* [ ] Confirmation modal

## Out of scope
* [x] Insufficient Joy to cover tx fees/ null claim / claim more than balance (these do not apply based on max amount claimable at all times)

https://github.com/Joystream/atlas/issues/3086

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202701542805374) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Update to amount claimable = max claimable amount and not modifiable

**Comment by KubaMikolajczyk** [comment]
Required changes done ✅
- Changed modal for claiming the reward to be always equal to max reward ( removed input for entering a custom value)
- Removed scenarios for Insufficient Joy to cover tx fees/ null claim / claim more than balance (these do not apply based on max amount claimable at all times)
[Link](https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=1547%3A19340)
