### ISSUE TITLE
Chromium: None of the distributors provided the asset

### ISSUE THREAD

**Issue by singulart** [Joystream/atlas#3061]
- [ ] Prepare debug version of Atlas with bunch of console.logs to figure out where the issue is
- [ ] Deploy this version to temp branch, send link to isonar and ask for logs
- [ ] Fix the problem

---

Steps to reproduce:

1. Using latest version of Chromium from https://download-chromium.appspot.com/
2. Try to open Atlas video and play it: https://play.joystream.org/video/27246
3. Observe the error in Console: "None of the distributors provided the asset"

Expected result: I should be able to play the video

**Comment by kdembler** [comment]
Does this happen for you every time?

**Comment by singulart** [comment]
> Does this happen for you every time?

Yes, every time

**Comment by rafalpawlow** [comment]
@singulart Can I ask you to check this video and tell me if you are able to play it? https://file-examples.com/storage/fe2c60820462fe6819b9429/2017/04/file_example_MP4_1280_10MG.mp4

**Comment by singulart** [comment]
> @singulart Can I ask you to check this video and tell me if you are able to play it? https://file-examples.com/storage/fe2c60820462fe6819b9429/2017/04/file_example_MP4_1280_10MG.mp4

The link doesn't work.. File not found

**Comment by rafalpawlow** [comment]
@singulart Sorry It must have expired somehow. Can you try one of the links from this site? https://file-examples.com/index.php/sample-video-files/sample-mp4-files/

**Comment by singulart** [comment]
> @singulart Sorry It must have expired somehow. Can you try one of the links from this site? https://file-examples.com/index.php/sample-video-files/sample-mp4-files/

Shall I click these links under Chromium?

**Comment by rafalpawlow** [comment]
@singulart Exactly. For me these mp4 doesn't work in chromium (same as joystream videos) and I wonder if it is not some kind of bug in chromium

**Comment by singulart** [comment]
![Uploading Screenshot 2022-08-19 at 15.47.41.png…]()

**Comment by singulart** [comment]
<img width="785" alt="Screenshot 2022-06-22 at 13 42 29" src="https://user-images.githubusercontent.com/7863785/185621875-3d409e39-510f-4985-a289-2632ab6d2e4f.png">

**Comment by singulart** [comment]
<img width="1499" alt="Screenshot 2022-08-19 at 15 47 41" src="https://user-images.githubusercontent.com/7863785/185621928-c6ae476d-6e18-41d7-b8f8-5d858ee339dc.png">

**Comment by singulart** [comment]
Request to this file hangs.

**Comment by rafalpawlow** [comment]
This looks like a bug in chromium and not joystream. I'm afraid there is nothing we can do on our side.
