### ISSUE TITLE
NFT purchase improvements (price + fee)

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3070]
**Scope:**

- [ ] Include price breakdown in Buy now flow ("you will pay" and "transacion fee")
- [ ] Show loading state for "You will pay" when the fee is being fetched
- [ ] Ensure fee loads properly for both buy now and place bid
- [ ] Ensure price + fee is properly validated

---

I think there is a little discrepancy between what we show in the `Place bid` view and what we show in the `Buy now` view. 
Yes - there is a fee in the action bar, but I think we should be more clear about how much the user needs to actually pay
Place bid view:
![image](https://user-images.githubusercontent.com/51168865/182785867-f5a97d54-74c6-42c4-b6bf-154dab832cb3.png)
Buy now view
![image](https://user-images.githubusercontent.com/51168865/182785707-12d648cd-9246-4c69-9ec7-b72daa9827ef.png)

**Comment by toiletgranny** [comment]
We added a Price breakdown variant which comes with skeleton loaders for the "You will pay" and "Transaction fee" information. https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1036%3A102837
