### ISSUE TITLE
Add more meaningful errors in the transaction dialog

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3078]
Similar to https://github.com/Joystream/atlas/issues/1861

Since we're moving to Carthage and we add support to fees we could update the transaction dialog to handle errors better.

* [ ] Find out what error codes we need to add.  
* [ ] Add them to `TransactionModal.constants` and add proper description

**Comment by kdembler** [comment]
I think these are the ones we should handle:
1. Not enough funds to cover tx fees (if the in-app validation failed). Keep in mind, that there are different types of fees (basic blockchain fee, different state bloat bonds, data object per size fee) and failing specific fee may result in different type of error.
2. Mismatch in expected fee value and actual blockchain value (for state bloat bonds). Same as above, error code may be different for each fee
3. Potentially errors when you try to withdraw/send too much funds. For example I have 100 JOYs in my channel account and I try to withdraw 150

Nothing else comes to my mind, anyone else has any different ideas?
