### ISSUE TITLE
How to scale ChannelPreview across screen sizes

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#308]
We're currently lacking a policy to scale `ChannelPreview` across different screen sizes. All the channel previews have a fixed width, which means when previews are displayed in the grid, distance between them will vary across different screen sizes which doesn't produce the best visual experience. We should figure out how we can scale them in a responsive fashion

**Comment by KubaMikolajczyk** [comment]
@kdembler this screen will change a lot and we dropped the channel card in its previous form.
New browse channels: [Browse channels link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8295%3A316)
Should we close this?

**Comment by kdembler** [comment]
If channel card will only use a fixed width across screen sizes, then sure

**Comment by KubaMikolajczyk** [comment]
A channel card will be respecting grid which will be implemented in the future - the example is here:
https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=11578%3A505297
Currently we use this component only in this type of top 10 carousel.
