### ISSUE TITLE
Payouts: Loading states for Balance history and Sources of Payments widgets

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3080]
dmtrjsg commented on [Thu Aug 04 2022](https://github.com/Joystream/marketing/issues/274)

## Context
* https://github.com/Joystream/atlas/issues/2401

## Scope
Loading states for 

* https://github.com/Joystream/atlas/issues/3057
* https://github.com/Joystream/atlas/issues/3058
* https://github.com/Joystream/atlas/issues/3056

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202736524010795) by [Unito](https://www.unito.io)

**Comment by KubaMikolajczyk** [comment]
All loading states for widgets provided ✅
Designs: https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?node-id=2007%3A28623
