### ISSUE TITLE
No tooltip with the exact value of my balance

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3083]
**As is:** Hovering over my account balance doesn't bring up a tooltip with a full number.
**To be:** It should bring up a tooltip with a full number, just like in [the Number component.](https://atlas-storybook-git-dev-joystream.vercel.app/?path=/story/other-numberformat--regular)

![CleanShot 2022-08-05 at 11 40 29](https://user-images.githubusercontent.com/35307309/183050435-35f92ecc-fae2-467b-9572-5225a110c9a5.png)

**Comment by drillprop** [comment]
Already fixed but it's not deployed yet
![image](https://user-images.githubusercontent.com/51168865/183052370-da310881-b4e6-4b00-983c-1e2f237606b6.png)
Try:
https://atlas-git-dev-joystream.vercel.app/
