### ISSUE TITLE
Incorrect NFT purchase view implementation + lack of support for the insufficient funds case scenario

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3084]
The implementation of the NFT purchase view in the Buy now mode doesn't match [the designs](https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1024%3A114229). However, the designs aren't that good either, as they don't provide any guidelines on handling the insufficient funds case scenario properly.

The goal of this task would be to revisit the NFT purchase view designs, address the insufficient funds case, and then create a detailed list of implementation issues to be passed over to engineers.

![play joystream org_video_27232](https://user-images.githubusercontent.com/35307309/183050909-210bcdfc-82e5-4daf-b05f-dac888a8e730.png)

cc @kdembler @dmtrjsg

**Comment by kdembler** [comment]
@toiletgranny You may want to take a look at Carthage implementation of this, as we've done some improvements here: https://atlas-git-carthage-joystream.vercel.app/

**Comment by kdembler** [comment]
Will be handled in https://github.com/Joystream/atlas/issues/3070
