### ISSUE TITLE
Update MemberDropdown to allow easy switching between member and channel

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3085]
https://user-images.githubusercontent.com/12646744/183072941-29404e33-4d35-484a-8816-c648fb6aef4a.mp4

https://www.figma.com/proto/1U8dkMKYlHAMTFH6FXTWFe/Channel-accounts?page-id=1237%3A15962&node-id=1237%3A15969&viewport=888%2C502%2C0.24&scaling=min-zoom&starting-point-node-id=1237%3A15969

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202736673685254) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
addressed in #2556
