### ISSUE TITLE
Testing that 100% locked funds from faucet can be used for starting as creator

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3089]
@dmtrjsg commented on [Fri Aug 05 2022](https://github.com/Joystream/atlas/issues/3090)

## Scope
Verify that even just using invitation funds, that are 100% locked (except for fees), we can do things like creating a channel and uploading assets and so on, because those actions include value payments above and beyond fees, for example bloat bonds and storage fees. 

Very that fresh members with funds obtained exclusively from faucet:

* [ ] Can create channel
* [ ] Can upload video
* [ ] Can edit video
* [ ] Can mint NFT
* [ ] Can put out on auction and settle auction
* [ ] Can withdraw to own account from channel account

⛔ 
- [ ] Cannot Bid on NFT
- [ ] Cannot Buy now NFTs

⚠️ Playground to test on: ~https://54.242.207.183.nip.io/network/config.json~
https://atlas-next.joystream.org/network/config.json

Atlas instance: https://atlas-next.joystream.org/http-rpc

Env variables:

VITE_NEXT_ORION_URL=https://atlas-next.joystream.org/orion/graphql
VITE_NEXT_QUERY_NODE_SUBSCRIPTION_URL=wss://atlas-next.joystream.org/query-node/server/graphql
VITE_NEXT_NODE_URL=wss://atlas-next.joystream.org/ws-rpc
VITE_NEXT_FAUCET_URL=https://atlas-next.joystream.org/member-faucet/register

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202727727437469) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
Will be done in https://github.com/Joystream/atlas/issues/3178 and https://github.com/Joystream/atlas/issues/3179
