### ISSUE TITLE
Introduce NFT proceedings go to channel balance as part of the flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3093]
- [ ] Update copy in the “Heads up!” Banner component, displayed under NFT options section, in the Video workspace (https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3223%3A161358),
- [ ] Update description of the Form field component for NFT royalties (https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3223%3A161045),
- [ ] Add a Banner component to the 3rd step of the NFT workspace (https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2393%3A82183),
- [ ] Add a confirmation dialog for minting NFT for a video (https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=3692%3A140829).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202736679778647) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
Alright, @kdembler, all changes are ready to be reviewed and implemented based on the designs, documentation, and changelog, which you can find here: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1945%3A109809
