### ISSUE TITLE
Idea: Improvements to reduce friction of blockchain interactions

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3098]
Couple ideas on how to make users life easier when it comes to signing/waiting for transactions:
1. Build optional signature-less experience, where users authenticate with a backend in regular web2 way and the backend manages private keys for them, so users don't need to install any extension
2. Make the UX of waiting for transaction processing less obtrusive - we could use the new minimized transaction snackbar (that we use for comments) for other types of actions and don't block the full app when the transactions are processing. Also, possibly including instant optimistic results
3. Don't wait for block finalization and just rely on block inclusion - this way the total processing time would be significantly lower

**Comment by mochet** [comment]
I would also suggest this: https://github.com/Joystream/pioneer/issues/3442
Basically ensuring that any transaction initiated is stored in a local storage log regardless of success/fail.

If this is possible I imagine it would help users understand what happened to their transaction. When it comes to things like NFT auctions and some actions with mainnet $JOY I could imagine the risks at stake will be far more significant than our current users have had and even slightly risking accidentally sending a transaction again may be a very expensive mistake.

**Comment by bedeho** [comment]
Superceeded by 
- https://github.com/Joystream/atlas/issues/3684
- https://github.com/Joystream/atlas/issues/1820
