### ISSUE TITLE
Update flows for adding subtitles

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3101]
Since we did some improvements to adding subtitles in the implementation on the fly, the designs needs to be updated. 

- [ ] We decided to remove Mark/Unmark as a closed captions option in the context menu
- [ ]  In the Combobox a user will be able to choose closed captions from the list 👇🏻 
![image](https://user-images.githubusercontent.com/51168865/183913427-b4969f82-25dd-4342-8020-5668a88a098c.png)
- [ ] Once a language is added in the form, this language should be disabled in the Combobox list with short information "Added" on the left
![image](https://user-images.githubusercontent.com/51168865/183913926-786f0cb1-0bfb-414f-8969-16f84dd9cd34.png)

**Comment by KubaMikolajczyk** [comment]
Done ✅
All of the changes are now reflected in the designs which can be found here:
Subtitles flows: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2653%3A124752
Changelog: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1378%3A93428

**Comment by dmtrjsg** [comment]
Looking good, two small questions: 

@KubaMikolajczyk pls add the case for zero matches for keybord input to the field. 
@kdembler pls advise on adding subtitles to minted NFTs.

**Comment by kdembler** [comment]
Once NFT is minted, it's not possible to add/remove subtitles
