### ISSUE TITLE
Placeholder screen for CRT module

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3117]

**Comment by KubaMikolajczyk** [comment]
Proposition for CRT placeholder is done based on placeholder page for my payments ✅
https://www.figma.com/file/VzPBMpUnGjGOHMSW2ZHbGY/Creator-tokens?node-id=2615%3A201416

**Comment by dmtrjsg** [comment]
Just a small copy update for H2:

From this: 
<img width="678" alt="Screenshot 2022-09-15 at 10 31 47" src="https://user-images.githubusercontent.com/93924525/190331048-b8a74f91-60ad-41de-b8d7-6d77e41d80b2.png">


To this: With Creator Tokens, channel owners are able to mint their own personalised tokens and let their audience buy and hold a share in the channel.
