### ISSUE TITLE
Video player enters a play/pause toggle infinite loop

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#314]
When dragging the progress bar around a couple of times letting it go then repeating and then triple-clicking on the progress bar the video player enters a play/pause toggle infinite loop.

Notes:
Could only repro so far if the video was playing and not paused.
Making the player fullscreen also triggered the bug in some cases.
Looks like some specific videos are more prone to it

Video link reference:
https://www.loom.com/share/9bf8d30b01b54a95af38d6a874e19969

**Comment by drillprop** [comment]
Not 100% sure but I started experiencing this bug after merging this PR https://github.com/Joystream/atlas/pull/208. So it may be worth investigating these changes. For me, it seems that happens more frequently on high CPU usage.
