### ISSUE TITLE
YT LP Rewards Section

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3147]
## Context
- https://github.com/joystream/atlas/issues/2973

## Scope

- [ ] Tier selector
- [ ] Display rewards panels based on Tiers

## OOS
 - Get started in 3 steps section

## Design

[LInk to Figma> ](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1604%3A85511)

<img width="588" alt="Screenshot 2022-08-18 at 20 36 18" src="https://user-images.githubusercontent.com/93924525/185479661-87772a7b-4ca0-4ab6-9e16-3b862ef482c7.png">

**Comment by drillprop** [comment]
FYI this section, which could be interpreted as part of this "reward section" 👇🏻 
 ![image](https://user-images.githubusercontent.com/51168865/189093598-c4f92256-2b67-4f5e-b12d-d3ecd64006cb.png)

Will be done in #3149
