### ISSUE TITLE
'unsupported file type selected' popup

### ISSUE THREAD

**Issue by ninja-fire** [Joystream/atlas#3175]
**Describe the bug**

the 'unsupported file type selected' popup still pops even after a good file type has been uploaded. this pop up appears each time you make a new action on the page: 
-uploading thumbnail
-validate video and broadcast transaction
-...

**To Reproduce**

1. upload a wrong file type
2. Click on 'reselect file'
3. upload the right file type
4. 'unsupported file type selected' pop up appears again

**Expected behavior**

the 'unsupported file type selected' should stop poping after uploading the right file type

**Screenshots**

![image](https://user-images.githubusercontent.com/44232936/186750045-05a4105f-6ff3-4b05-9672-82f0a238945f.png)

**Device (please complete the following information):**

- OS: macOS Monterey v12.5.1
- Browser google chrome Version 104.0.5112.101

**Additional context**

**Comment by dmtrjsg** [comment]
Sorted in here:
- https://github.com/Joystream/atlas/issues/2910
