### ISSUE TITLE
Test Invitation Lock coverage of Misc fees Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3178]
@dmtrjsg commented on [Fri Aug 26 2022](https://github.com/Joystream/pioneer/issues/3579)

## Context

2nd round of QA, Env details are in the Epic pls see pioneer/3577>
- https://github.com/Joystream/pioneer/issues/3577

Testing Invitation Lock Fees Coverage

## Scope

1️⃣ Ensure that 100% Invitation lock funds received from Faucet can only cover the following transactions:

###  ✅  Transactions Supported Atlas
- **Standard transaction fees**
- **Bloat bonds**
    - Channel bloat bond (`content::create_channel`)
    - Video bloat bond (`content::create_video`)
    - Storage data objects bloat bond (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
- **Storage data size fee** (`content::create_channel`, `content::update_chanel`, `content::create_video`, `content::update_video`)
    
2️⃣  Ensure that 100% Invitation lock funds received from Faucet can NOT cover the following transactions:

### ⛔ Not supported Atlas
- **Nft auction bids** (`content::make_english_auction_bid`, `content::make_open_auction_bid`)
- **Nft payments** (`content::buy_nft`, `content::accept_incoming_offer`)
- **Channel swap payment** (`content::accept_channel_transfer`)
     -  **Transfers** (`balances::transfer`, `balances::transfer_keep_alive()`, `balances::transfer_all()`)

## Env

Use `Atlas Next` environment to test with. Once you launch Atlas from `carthage` branch, open AdminModal with Ctrl+Shift+D and pick the correct env from a dropdown:

<img width="528" alt="CleanShot 2022-08-31 at 18 14 51@2x" src="https://user-images.githubusercontent.com/12646744/187728022-1b0c0646-8a38-4da8-94af-8e81a7b1975c.png">

**Comment by ivanturlakov** [comment]
### Transactions Supported Atlas

✅ Standard transactions - Like/Comment/Follow
Successful transaction: Withdraw, MemberRemarked, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xb941cd8da4cd21732050f5c9af52a604c841f8a21734b0542cf8630fafc52fd5
extrinsic hash: 0x599d873babbad8e143276172a9e20be23a20018e800635262c77365555bba748
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xb941cd8da4cd21732050f5c9af52a604c841f8a21734b0542cf8630fafc52fd5

✅ Create channel
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, DynamicBagCreated, Withdraw, Deposit, NewAccount, Endowed, ChannelCreated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x26ca451d10652628a38ac5ba72eecd620a4c76ed3f4d1fae823ba3e0284d411e
extrinsic hash: 0x423999cffdda283b24d67906bd8fa977a31a0485a4846cdbfec840e8801f1178
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x26ca451d10652628a38ac5ba72eecd620a4c76ed3f4d1fae823ba3e0284d411e

✅ Create video
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, DataObjectsUploaded, Withdraw, Deposit, VideoCreated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xbd98fd17b566099468381ee9d0d98c434f3acce4d1536546650d627dd68dcf5c
extrinsic hash: 0xe1b21cf8408d59ccce577865040036ed0303fcb9adae0a0e99ce2ac069ca3450
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xbd98fd17b566099468381ee9d0d98c434f3acce4d1536546650d627dd68dcf5c

✅ Update channel
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, Transfer, DataObjectsUpdated, ChannelUpdated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x0bf80efcbac254bf85623ca6a509cd160110409562741f7c62bb68dec8e6af1a
extrinsic hash: 0x3363e891dc5259e77388f5eafd942cae97e7348d388219b989003a57c4d4d6e3
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x0bf80efcbac254bf85623ca6a509cd160110409562741f7c62bb68dec8e6af1a

✅ Update video
Successful transaction: Withdraw, Withdraw, Deposit, Withdraw, VoucherChanged, VoucherChanged, Transfer, DataObjectsUpdated, VideoUpdated, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0xc6b56fcb69a9386b5a65204670252734f947f6ffc297cf4144d31b19c496b741
extrinsic hash: 0xdb18827ca143a9535c77e2771a6af1051d161c515c74ba4177c1bb8975687874
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0xc6b56fcb69a9386b5a65204670252734f947f6ffc297cf4144d31b19c496b741

✅ Delete video
Successful transaction: Withdraw, VoucherChanged, VoucherChanged, Transfer, Transfer, DataObjectsDeleted, Transfer, VideoDeleted, ExtrinsicSuccess
on network: wss://atlas-next.joystream.org/ws-rpc
in block: 0x9422f6f021304e86477e146f0d43027ccb626d2ff213c2c1c8f8c445f5f6d8ad
extrinsic hash: 0x08af265f85febfd1079981dfd9276fe0abc90dd7b5f1a8fee9f9fd24ee319ff5
more details at: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x9422f6f021304e86477e146f0d43027ccb626d2ff213c2c1c8f8c445f5f6d8ad

### Not supported Atlas

A user account with 30 tJOY(Invitation lock)
<img width="1406" alt="Снимок экрана 2022-09-06 в 14 43 37" src="https://user-images.githubusercontent.com/46903215/188859037-c79e87e3-980e-44c9-acda-7742a8faae26.png">
<img width="301" alt="Снимок экрана 2022-09-06 в 14 42 53" src="https://user-images.githubusercontent.com/46903215/188859072-5210bcce-e7af-4467-8d94-44f62c124711.png">

🚫 Nft auction bids
<img width="553" alt="Снимок экрана 2022-09-06 в 14 48 24" src="https://user-images.githubusercontent.com/46903215/188859788-94eade7d-45d3-42db-9bed-15050e27ca31.png">
<img width="657" alt="Снимок экрана 2022-09-06 в 15 19 45" src="https://user-images.githubusercontent.com/46903215/188859859-84f67dc5-116a-412e-8a37-54fcdc30a02e.png">

🚫 Nft payments
<img width="553" alt="Снимок экрана 2022-09-06 в 14 50 04" src="https://user-images.githubusercontent.com/46903215/188860001-9468e67a-4c74-4cb1-9625-590ef4b7bc0a.png">
<img width="657" alt="Снимок экрана 2022-09-06 в 15 19 45" src="https://user-images.githubusercontent.com/46903215/188860773-1ac7b0f9-a40b-4ac5-b457-7e929cc308ce.png">

🚫 Channel swap payment
<img width="657" alt="Снимок экрана 2022-09-06 в 15 19 45" src="https://user-images.githubusercontent.com/46903215/188860773-1ac7b0f9-a40b-4ac5-b457-7e929cc308ce.png">

🚫 Transfers
<img width="494" alt="Снимок экрана 2022-09-06 в 14 45 41" src="https://user-images.githubusercontent.com/46903215/188860804-9a6a9bfd-1498-4600-b479-b57b83e095db.png">
<img width="692" alt="Снимок экрана 2022-09-06 в 14 46 47" src="https://user-images.githubusercontent.com/46903215/188860915-e4b8181f-ab72-4a6a-a620-6f327c1afd33.png">
