### ISSUE TITLE
Idea: Opinionated wallet selection

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3180]
# Background

Right now we present a new user, who does not have a wallet, with a neutral list of wallets to install, of which we will support 3, possibly more in the future.

# Proposal

This does not really serve he product, a user does not have information or apatite to learn about distinctions, so we should just tell them to install a specific wallet which is known to be compatible with their browser.

**Comment by dmtrjsg** [comment]
Afaik we pre-agreed to recommend Talisman with a simple label "Recommended" and put it on top of the list.
