### ISSUE TITLE
YPP: Capture category information

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3183]
When a new creator signs up for YPP, and auto-synch works, what category should be used for those videos? We will allow infra to [capture such information upon signup](https://github.com/Joystream/youtube-synch/issues/38), but Atlas must provide it in some way? Seems it will have to ask the creator to select among one of the categories the app has been configured to supports?

**Comment by dmtrjsg** [comment]
Firstly Atlas category structure should be cross checked with YT category structure. Thesis is that when it was set up we loosely replicated YT, so need to check for the diff of the trees to be able to solve for it.

**Comment by dmtrjsg** [comment]
Agreed to compare YT channel categories with Video Categories for Atlas. NB:  video categories quite likely to inherit categories from Channel tbc. 

@zeeshanakram3

**Comment by dmtrjsg** [comment]
Based on this issue:
- https://github.com/Joystream/youtube-synch/issues/42

Decision was to:
`YT sync scraps the YT category, and lets creator select a single category. Inform users that this will be propagated to all videos, but can be changed manually. What they select is default display category for the video category.`

Based on this, closing the issue as there will not be any mapping from YT to Atlas Display categories in the first release.
