### ISSUE TITLE
Uploading avatars + Avatar component changes PR review

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3203]
1. **As is:** Hovering over an avatar in the `AvatarGroup` component triggers a hover state of the Avatar component itself.
   **To be:** The Avatar component should be in its _unclickable_ state in this component, [just like in this version of this component](https://dev--atlas-storybook.netlify.app/?path=/story/other-avatargroup--default).
2. **As is:** When the `editable` property is set to `false`, hovering over the Avatar component still causes the border color to change (it's very subtle, but it's there if you look closely).
   **To be:** No styling property should change upon hovering over the Avatar component, if its `editable` property is set to `false`.
3. **As is:** In the "Create membership" step of the Sign in dialog, the blur effect is applied directly to the selected avatar image in the background, causing unpleasant border bleeding around the edges of the container.
**To be:** The blur effect should be applied as a `backdrop-filter`, on a div that sits _on top_ of the avatar image, just like in the "Member dropdown" component.

**Comment by kdembler** [comment]
@toiletgranny 

Regarding 
> As is: When the editable property is set to false, hovering over the Avatar component still causes the border color to change (it's very subtle, but it's there if you look closely).
To be: No styling property should change upon hovering over the Avatar component, if its editable property is set to false.

Are you 100% sure? Looking at the current documentation for this component, it seems that what you are describing should be the effect of `clickable` property set to false, not `editable`?

**Comment by toiletgranny** [comment]
Yes, sorry, I meant the `clickable` property.
