### ISSUE TITLE
Subtitles PR review

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3207]
1. **As is:** During video upload, when selecting a file called "name.srt", in the UI it's labeled as "name.vtt".
**To be:** At this point it's still a `.srt` file, and it's best to refer to it as such, otherwise we might confuse users and trick them into thinking that perhaps a different file got picked up off their hard drive (my story).
2. ~What's with the list of languages? Where did we get it from? Why can't I upload polish subtitles? :D What other languages might we be missing? @dmtrjsg~
3. **As is:** There is no shadow underneath the "Context menu" component acting as a dropdown menu for our "Combobox" component.
**To be:** There should be a shadow since it's a copy of the "Context menu" component.
4. ~**As is:** Having selected a language but not providing a file for it, and then proceeding with the video upload and transaction signing, etc., upon reopening this video in the edit mode, I could still see the language I selected.
**To be:** It's not a biggie, but since I ended up uploading a video without subtitles, would it make more sense to simply drop my language selection if it doesn't carry any additional information with it? (cc @KubaMikolajczyk)~
5. **As is:** In the Viewer experience, when opening up settings of a video that with no subtitles, I can still see "Subtitles" as a section in the settings menu. I can click on it to go inside and see that "Off" is the only option.
**To be:** If there are no subtitles provided for a video, just like the "CC" icon, the "Subtitles" section in the video settings menu should not be displayed at all.

### Open ended
6. ~**As is:** As a publisher, I can only download a subtitles file that I have just selected to be uploaded. When I save video changes and get back to it a day after, I won't be able to download the subtitles, as the option is not available anymore.
**To be:** According to the designs, the exact opposite was supposed to be true. I'm assuming, however, that the difference in the implementation is rooted in technical constraints we were unaware of at the time of designing this. If this is true, I think it begs the question, what's the use of the "Download file" option whatsoever now? I can see none, frankly speaking. If what I say is true and you guys (@kdembler, @KubaMikolajczyk, @dmtrjsg) agree with me, then I'd opt for a minor design tweak in which we git rid of the "Download file" option altogether, and repurpose the tree dots menu to a trash icon button component, making it easier for the user to delete a language. Wdyt?~
7. ~**As is:** When I upload a subtitle file and then save video changes, the name of the original subtitles file is replaced with `subs.vtt` in the Subtitle box component.
 **To be:** According to the designs, we ought to preserve the original file's name. It is my understanding, however, that — again — due to technical constraints we were unaware of at the time of approving the designs, we ended up displaying `subs.vtt` instead. If that's the case and there's no way for us to bring back the original subtitles name, then I think it begs the question, what's the use of displaying `subs.vtt`? To me, as a video author, it brings no value. I don't understand what it is. If you guys (@kdembler, @KubaMikolajczyk, @dmtrjsg) are with me, I will opt to drop this altogether and have the subtitles file name displayed only when uploading new ones.~

**Comment by kdembler** [comment]
2 - The current list of languages have been prepared ages ago, when doing the first Studio iteration I think. I'm fine with expanding it, we would just need to find a list that makes sense.

4 - I think we shouldn't really allow the user to "publish" subtitles without a file. In that case I would either:
a) Force the user to delete subtitles language without file attached
b) Just filter it out during publishing

6 - This isn't really a technical constraint, it just wasn't in scope yet. There is a PR in review that adds this option to already published subtitles.

7 - Yeah, we already agreed that this will not be displayed for published subtitles, it just wasn't implemented yet.

@toiletgranny I mentioned both 6 and 7 as things that are currently in the works 😄
