### ISSUE TITLE
Discussion: Category filtering details in `Carthage`

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3212]
There are a few unresolved loose ends w.r.t. how category filtering should be done in Carthage

1. Only on `Discovery` screen, or outside as well.
2. Playback filtering, e.g. user punching in raw video ID.
3. NFT filtering on  `NFT` screen & home screen: this is difficult due to lack of relationship filtering in QN.

My POV:

- I think 1 was a yes?
- I think 2 & 3 have to have same value (yes/no), or things get weird for the user really easily.
- I think its worth adding redundant filed on NFTs as workaround, so filtering works. Is conceivable that other uses want to do this as well, not just Atlas, when we go to this multi-Atlas scenario.

**Comment by kdembler** [comment]
My POV:
1. I don't fully understand what you mean by that point but here's my look on this topic:
- Operator defines set of _display categories_ `Y`. Those are categories visible in `Discover`. For each of those they specify:
  - Display name
  - Icon
  - Color
  - Image (this and all above is used by `Discover` screen)
  - Set of QN category IDs that this _display category_ supports. This set is different for each display category but can overlap. So _display category_ contains multiple QN categories and single QN category can belong to multiple _display categories_ inside a single app.
- Based on display categories, set of QN categories supported by the app can be derived:
```ts
const displayCategories = [/* ... */];
const allQnCategories = [];
for (const displayCategory of displayCategories) allQnCategories.push(...displayCategory.qnCategories);
const uniqueQnCategories = uniq(allQnCategories);
```

- Only videos belonging to one of `uniqueQnCategories` will be displayed in the app. That includes all of viewer screens, discovery, search and Studio experience
- When publishing a new video, creator would pick one of `uniqueQnCategories` to assign to their content

2 & 3: Agreed the answer should be the same and I think it should be yes. Let's add redundant field for NFTs and then we have same treatment. If the user hits up video outside of defined categories, that would be filtered by QN and the result in app would be as if the video didn't exist. We could tweak the messaging that the video is not found and that it may just be ignored by this specific gateway.

**Comment by bedeho** [comment]
1. This is exactly what I meant ;)
2 & 3: 100%,  made issue for a better messaging screen here: https://github.com/Joystream/atlas/issues/3213 . There is a risk people will end up hitting this message for various reasons, so lets treat it in a more careful way.

Question: was any of this actually for Carthage? I thin it was not first, then it was in some random Slack message, but I keep confusing myself, it would be great if it was <3

**Comment by kdembler** [comment]
This originally wasn't meant for Carthage but I think we can squeeze it in. These are design implications that come to my mind:
- In video view, we currently display single category the video belongs to, that's QN category. We also display icon next to it, using in-app mapping. After those changes we can go to ways about it:
  - We either display only a name of QN category video belongs to (there won't be app icon associated with it anymore)
  - We display a list of _display categories_ this video belongs to <- this would be my recommendation<img width="683" alt="CleanShot 2022-09-05 at 15 26 30@2x" src="https://user-images.githubusercontent.com/12646744/188460417-bf9e6a23-b060-4a9c-b5fa-a987ee53507b.png">

- I think we can get away without any changes in both `Discover` and specific category screen. However, AFAIK, curators still have tasks about updating featured videos for category views. What do we do with that? Do we keep them doing this? Do we get rid of featured stuff? I wouldn't get rid of it, but at the same time it feels weird to have DAO do stuff for us, now that we're branding our instance as independent gateway. Any thoughts?

**Comment by kdembler** [comment]
Closing since we reached conclusion and implemented this
