### ISSUE TITLE
Validate user has enough funds for tx

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3222]
**AC:**

- [ ] Every time we would send a transaction, validate that the user has enough funds for transaction

---

Currently if the user doesn't have enough funds to pay for transaction fee, we will still let them initialize the tx and they will end up with a failed transaction and "not enough funds" message. We should check whether user has enough funds before we let them sign a transaction and display a message in the UI. What this needs to take into account, is the fact that different types of funds can be paid for different types of fees. So even though the free balance of a user may be 0, they can still send a trasaction using locked funds

Designs for minimized transactions already done:
> :warning: I wasn't able to test whether error snackbar components have been implemented to handle insufficient funds to cover transaction fees. kdembler I'm afraid you'll need to verify this yourself. It's the third bullet point [in this changelog](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=5739%3A263821).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202987390279959) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@kdembler Assuming validation happens so fast, it doesn't make sense to flash loaders for a split of a second, my understanding is that the only design treatment this issue needs is some form of letting the user know about their funds being insufficient to cover transaction fees. 

If this is correct, please let me know if this toast message makes sense. 

![image](https://user-images.githubusercontent.com/35307309/193825483-2691ca65-fd38-4714-b64d-ec71adc1b2b2.png)

**Comment by toiletgranny** [comment]
Note to self:
- The goal was to entertain the user for the time the fee is calculated in the background,
- One solution we discussed briefly with @kdembler is to change the button to something that indicates loading.

**Comment by toiletgranny** [comment]
@kdembler Here's the solution, just like we discussed it. It requires changing two components:
- [The Dialog component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9274%3A172494),
- [The Action bar component](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9724%3A174396).
