### ISSUE TITLE
Incorrect display of likes and dislikes for the video(carthage local)

### ISSUE THREAD

**Issue by ivanturlakov** [Joystream/atlas#3223]
The problem was noticed when running Atlas locally from the carthage branch

Before - 0:0
Thumbs Up
After - 1:1
<img width="152" alt="Снимок экрана 2022-09-07 в 13 04 14" src="https://user-images.githubusercontent.com/46903215/188853484-cdbc7b11-fac3-4cef-99b6-31aa2956ef38.png">

Before - 0:0
Thumbs Down
After - 0:0
<img width="144" alt="Снимок экрана 2022-09-07 в 13 06 55" src="https://user-images.githubusercontent.com/46903215/188853779-671ab2a2-1a6e-47e3-8d12-8d2838fd1fd7.png">

**Comment by kdembler** [comment]
Thanks for the report @ivanturlakov! We fixed it in https://github.com/Joystream/atlas/pull/3247
