### ISSUE TITLE
Change tooltip for Joy token icon

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3226]
We shouldn't mention anything relating to future exchange listing. Let's find a different copy for this tooltip or get rid of it

<img width="261" alt="CleanShot 2022-09-08 at 10 26 10@2x" src="https://user-images.githubusercontent.com/12646744/189073840-0eedd394-e5c9-490f-95db-69c6df9d82db.png">

**Comment by toiletgranny** [comment]
Keeping in mind that the main goal of the tooltip was to simply explain what the icon stands for, I'd vote for replacing the tooltip copy with this: _JOY token is a native crypto asset of Joystream blockchain. It is used for platform governance, purchasing NFTs, trading creator tokens, and covering blockchain processing fees._

If this sounds good to you @kdembler and @dmtrjsg, I believe this issue can be moved straight into Ready for Dev.

**Comment by kdembler** [comment]
Sounds good!
