### ISSUE TITLE
Bad visibility of Joystream logo in embedded player

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3231]
<img width="612" alt="CleanShot 2022-09-09 at 09 58 22@2x" src="https://user-images.githubusercontent.com/12646744/189301740-2930e148-c9db-478d-8390-1b221522ecd5.png">

For some bright video covers, the logo in the bottom right may not be very visible, maybe it's worth adding very subtle shadow at the bottom to alleviate?

**Comment by toiletgranny** [comment]
@kdembler Seems like it's something that got overlooked during implementation, as the designs have shadows for all elements displayed in the player component. Please note this includes not only the logo, but also the video title and the channel name at the top.

https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=2611%3A232846

**Comment by kdembler** [comment]
Just to make sure, do you mean the `Video player background` layer?

**Comment by toiletgranny** [comment]
No no, @kdembler, I meant all layers on top of it. Here's a video:

https://user-images.githubusercontent.com/35307309/190999589-12ae55c8-c394-4c28-a67d-dd949a916dd2.mp4
