### ISSUE TITLE
Idea: Better upload handling

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3240]
# Background
Right now, for a mix of technical and social reasons, storage providers are failing to absorb uploads reliably. There are discussions ongoing about how to address this, but its not clear exactly when they will conclude and materialize. 

# Proposal
1. **Smarter clients side logic:** I hate to make the client thicker, but perhaps this one intervention won't be too bad. Perhaps, before the upload begins, the app can try to simultaneously connect to all the storage providers assigned to the given bag where the dataobjects are landing, i.e. the bag for their channel, and try to quickly establish which one is most responsive, and which one has decent speed. Not sure if it would even be possible to do like a trial upload of some rubbish payload just to check how they are working? In fact, perhaps such a trial endpoint sort of could be of utility anyway, e.g. for lead/operator to test how well uploads are working. Would be constrained do a very small payload.
1. **Error reporting:** I assume currently this is not being reported, but being able to send the alert to gateway operator and to some second endpoint, e.g. like lead, could be useful for better analytics powering debugging and performance monitoring.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202987173366088) by [Unito](https://www.unito.io)

**Comment by kdembler** [comment]
1. I wouldn't go with try-all approach, I think we should use the same as we do for distributors, so pick the operator closest to you geographically. We already have all the setup, just a matter of enabling the same logic to operators. If you pick one closest to you and the speed it still poor, then that's an issue to be solved with the operator.
2. We do some kind of reporting already. We have the Sentry.io monitoring that logs all the errors that happen on the client side. I think what gets there should be mostly enough to get a good picture, it's just a matter of aggregating this data and looking through it.

**Comment by bedeho** [comment]
> I wouldn't go with try-all approach

What is the cost though, specifically. Replication factor is like 5 now, seems like both the tech & performance side of doing that investigation is small, and sounds like sort of reuable code that other apps may want in the future, even if Atlas does not.

> We do some kind of reporting already.

1. Is the use of sentry some how built into Atlas, or could one use any random kind service on the other end without having to rip out some sort of sentry library?
2. I assume if you use sentry, you have to pay for that as an Atlas operator, at least with any non-trivial scale?
3. What about being able to relay automatically from sentry, at least serious errors, without manual intervention from operator?

**Comment by kdembler** [comment]
> What is the cost though, specifically. Replication factor is like 5 now, seems like both the tech & performance side of doing that investigation is small, and sounds like sort of reuable code that other apps may want in the future, even if Atlas does not.

Just to make sure, you are talking about making changes to Colossus so it offers this kind of a test endpoint that can be used to measure speed? I just don't think it's app's job to ensure the storage network works properly, it should be on WG and it should just work. To make things clear, depending on how this new functionality exactly functions, while it could allow us to measure performance, it wouldn't guarantee that an actual upload would succeed since there still could be scenarios for failure not captured by this test.

> Is the use of sentry some how built into Atlas, or could one use any random kind service on the other end without having to rip out some sort of sentry library?

It is built in, in a sense that we use Sentry library. However, we only use the library in a single file where we define the logger so swapping to a different library/provider would be fairly trivial.

> I assume if you use sentry, you have to pay for that as an Atlas operator, at least with any non-trivial scale?

Correct

> What about being able to relay automatically from sentry, at least serious errors, without manual intervention from operator?

Sentry offers an option to do some automatic reporting via email or other means, based on specific conditions, we would just need to set it up.

**Comment by bedeho** [comment]
> Just to make sure, you are talking about making changes to Colossus so it offers this kind of a test endpoint that can be used to measure speed? 

Yes.

> I just don't think it's app's job to ensure the storage network works properly, it should be on WG and it should just work.

I agree this sort of heavy probing should not be part of default functioning of the app, however reporting errors upon observed failures should. The question is: would it not be worth it as a stop gap? this boils down the cost side. So I am just asking from a pragmatic point of view.

> Correct

Ok, I'm making an issue to decouple this at some point in the future:

**Comment by kdembler** [comment]
> however reporting errors upon observed failures should

Fully agreed.

> The question is: would it not be worth it as a stop gap? this boils down the cost side. So I am just asking from a pragmatic point of view.

Right. So while it's not super complex, it may not be that easy to do on our side. The uploading code is quite old at this point (we've made only slight adjustment since first Sumer release) and I think to make this work properly we would need to do a slight refactor. While this adds up the cost, I think this could allow us to make further improvements to uploads easier in the future. Assuming Colossus work is done, I would say doing this properly in Atlas would be like 2-3 days of dev work, which I think is a fair cost.

**Comment by bedeho** [comment]
>  I would say doing this properly in Atlas would be like 2-3 days of dev work, which I think is a fair cost.

Great, I can prepare an issue, but in attempting to do so, it just raised a perhaps obvious question I should have asked sooner: do we actually have any reason to believe, currently, that any substantial % of upload failures occur _after the download is initiated_? Because, lets say this never happened, and 100% of all upload failures have to do with just being unable to establish the connection or something, then perhaps this endpoint is sort of pointless, and the whole story is just: can you connect.

**Comment by kdembler** [comment]
In cases I have investigated, 100% failures occurred after the full file was uploaded, in the finalization step.

**Comment by bedeho** [comment]
Do you think all of the failures could just be the same problem? is there any reason to suspect otherwise currently?

**Comment by kdembler** [comment]
No, I've seen at least 3 distinct error messages:
1. Incorrect bucket ID - this was related to misconfigured worker ID and should be alleviated with this PR: https://github.com/Joystream/joystream/pull/4283
2. Incorrect file size - no idea what this was about, I've only seen it in one node and other nodes accepted the same asset just fine.
3. Failed to send extrinsic - like above, have seen it only once and no clue what it's about

**Comment by kdembler** [comment]
@bedeho I did a quick look at Colossus code and I think I figured out reasons for errors above:
2. https://github.com/Joystream/joystream/issues/4293
3. https://github.com/Joystream/joystream/issues/4292

Please assign priority to those as you fit

**Comment by bedeho** [comment]
Will do a call with storage+distributor leads post-carthage so we can just talk about some of these things, then schedule some of these to get done before mainnet, great work :)
