### ISSUE TITLE
Use selected wallet name in minimized transaction snackbar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3248]
**Scope:**

- [ ] Go through the app to ensure we don't use hardcoded "Polkadot" wallet name anywhere and always use selected wallet name.
- [ ] These places are affected for sure:
  - [ ] Minimized transaction snackbar (`packages/atlas/src/providers/transactions/transactions.manager.tsx`)
  - [ ] There are other transactions waiting for signature (`packages/atlas/src/providers/transactions/transactions.hooks.ts`)

**Sender**: None
**Taken at**: https://play.joystream.org/video/27611
**Fields**:
- Expected Result: - The &#34;Continue in Polkadot&#34; spinner dialog: the spinner in bottom right is specifically talking about Polkadot signer extension, but we support multiple wallets now, I am using Talisman. All referenes to &#34;Polkadot (signer)&#34; in the app should be purged.
- When trying to like a video, the Talisman signer popped up, asking me to connect an account, but after that there was no prompt for password or anything, the liking spinner and &#34;Continue in Polkadot&#34; dialog was just going forever.
- Houston, we have a problem.: Two problems when trying to like a video

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9724f76a-5cf8-4643-ad5c-9ebd9432a9bd-annotated_c61c5915-b19e-4062-81ea-911e02f13965.png?etag=358cbec7a7537a26fdb7cee3001b0e89)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9724f76a-5cf8-4643-ad5c-9ebd9432a9bd-annotated_c61c5915-b19e-4062-81ea-911e02f13965.png?etag=358cbec7a7537a26fdb7cee3001b0e89)*

**Browser**: Firefox 104 (macOS Catalina)
**Screen size**: 5120x1440
**Browser size**: 1752x1146
**[Open #23 in Usersnap](https://app.usersnap.com/l/feedback/2056c2e0-45e5-4b27-bec1-8c3420f975ea?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bedeho** [comment]
I opened Talisman later, it seemed to be in some old "approve mode" or something which was not shown last time, this may be the cause, so may be a bad Talisman UX issue causing the hanging,but copy issue still remains.

**Comment by kdembler** [comment]
We removed most references when doing multi-wallet support but missed that and one more place, thanks for reporting 👍
