### ISSUE TITLE
Substrate vs Joystream address format UX upd

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3256]
## Scope

- [ ] Update the designs of the Transfer Modal as per [this comment](https://github.com/Joystream/atlas/issues/3256#issuecomment-1268447352)
- [ ] Update the validation to accept both Substrate generic and Joystream Specific addresses.
- [ ] Convert the address to Joystream format before sending an extrinsic

## Context
> Polkadot wallet address vs Joystream wallet address
Designs for the Transfer dialog have been created around the assumption that JOY tokens can be transferred from one Polkadot wallet to another; therefore, it's the Polkadot wallet address that's an identifier of a destination account. [(link)](https://www.figma.com/file/uHzbhNX9dP4QtZbIapvZI6/Transfer-dialog?node-id=1013%3A5720) In the implementation, to my surprise, the "Polkadot wallet address" has been swapped with "Joystream wallet address".

Now, "Joystream wallet address" is a concept to which I, as an Atlas user, haven't been properly introduced to yet, meaning (a) I don't know what's my Joystream wallet address or (b) where to find it.

Unless changing "Polkadot wallet address" to "Joystream wallet address" isn't trivial (no one talked to me about it) and is necessary for the Transfer dialog to work, I believe we must create an issue to think about onboarding Atlas users with the concept of Joystream wallet addresses, it's relation with Polkadot wallet addresses and how does transfering funds work in general. And for that to happen, I'd need to be onboarded with that knowledge myself, too.

@dmtrjsg @kdembler If you guys agree with the above, I'd appreciate pointing me to further reading on the subject, if it's available (I tried looking it up in our Handbook, but I haven't found anything), or arranging a meeting where I can have someone explain this to me.

**Comment by toiletgranny** [comment]
@kdembler Having talked to you about this and having read a few articles on the subject, my recommendation is as follows:

1. In the Transfer dialog, in the Destination account text field, let's bring back the "Polkadot wallet address" placeholder, as it's more technically accurate.
   - The current "Joystream wallet address" placeholder implies that only Polkadot wallet addresses in the Joystream format are accepted by the form, which is not the case.
2. In the Transfer dialog, in the Destination account text field, let's add a tooltip briefly explaining multiple wallet address formats. **Designs, docs, and documentation [can be found here.](https://www.figma.com/file/uHzbhNX9dP4QtZbIapvZI6/Transfer-dialog?node-id=703%3A5383)**

![image](https://user-images.githubusercontent.com/35307309/194072821-b2b368a6-ef26-4f5b-a68c-30ebc072ff7c.png)

cc @dmtrjsg

**Comment by dmtrjsg** [comment]
Agree with the design implementation.

⚠️  Just to add that both formats should be accepted in the destination account. Lets update the validation on prefix, but remove the char length from the validation.
