### ISSUE TITLE
Improve language selects

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3257]
## Context

Review and extend the list of supported languages

## Scope

- [x] Update the languages list in the app
- [ ] Replace language select in VideoForm with Combobox
- [ ] Implement the new list separator
- [ ] Introduce separation into "Popular" and "All" languages

Out of scope: ⛔ 
- [ ] 🆕  ~Update the language select component for uploading subtitles to support multiple languages.~ not required 

🔗 Spreadsheet [LINK > ](https://docs.google.com/spreadsheets/d/1DS8nyJWLQpXWKrX9q697VHj2snV4rUwTVkWN3PlKEOE/edit?usp=sharing)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202987367684496) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
## Recommendation

Use a de-duped superset of Youtube Creator Support Languages + EU languages + Top 50 Content Websites +  top 10 APAC + top 3 African (adjusted for internet penetration) + Hebrew. This way we would not get any bad publicity of exclusion and cover all of the bases. 

Top 10 languages can be arranged in alphabetical order in the top section called "Most popular", and Other languages can be an alphabetical list underneath.

Finalised deduplicated list to be created after confirmation of the above proposal with the team

@kdembler @toiletgranny @bedeho 

## Research

1️⃣ Intro: [76% of internet users speak 10 languages](https://www.statista.com/statistics/262946/share-of-the-most-common-languages-on-the-internet/)

2️⃣ [Top 50 Languages for Content Websites](https://en.wikipedia.org/wiki/Languages_used_on_the_Internet)

3️⃣    List of languages for Creatprs Support on YT (Proxy for Indication on which are most popular as spoken by native and non-native speakers)

Arabic
Bengali
Chinese (simplified)
Chinese (traditional)
English
French
German
Italian
Indonesian
Japanese
Korean
Polish
Portuguese
Russian
Spanish
Thai
Turkish
Vietnamese
Urdu
________

I'd say a superset of YT support + top 50 Content may be a safe bet +


2️⃣ **EU languages:**

Bulgarian, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, German, Greek, Hungarian, Irish, Italian, Latvian, Lithuanian, Maltese, Polish, Portuguese, Romanian, Slovak, Slovenian, Spanish and Swedish.

3️⃣ **Latin American Languages**
Spanish. Portuguese cover vast majority. 

Native languages for reference[ can be found here](http://www.native-languages.org/most-latin.htm#:~:text=Among%20all%20languages%2C%20the%20top,Italian%20(with%202%20million.)) but chances to have creators making content in such languages is low.

4️⃣ *Asia Pacific Region*

<img width="478" alt="Screenshot 2022-09-16 at 19 45 03" src="https://user-images.githubusercontent.com/93924525/190678548-589194b2-12fa-4e7e-91a7-16a7d9639cae.png">

Chinese 
Indonesian
Japanese
Bengali
Punjabi
Filipino
Thai
Tamil
Vietnamese
Malay
Lao

5️⃣ *Africa* 

Hausa (Nigeria) – 34 million
Yoruba (Nigeria) – 28 million
Swahili (Kenya, Tanzania, Uganda) – 26 million
Amharic (Ethiopia) – 25 million
Fula (west & central Africa) – 24 million
Oromo (Ethiopia, Kenya) – 24 million
Igbo (Nigeria) – 24 million
Malagasy (Madagarscar) – 18 million
Somali (Somalia) – 15 million
Chichewa (Malawi) – 12 million
Akan (Ghana) – 11 million
Zulu (South Africa) – 10 million

6️⃣  Other Languages

Hebrew
Welsh

ℹ️ YT:  Languages supported on Youtube.

List of languages supported for creating videos on YT (seems to be exhaustive, including Latin which is an archaic language, Charokee - tribe language, American Sign Language - which cannot be used for subtitles but can be used for videos for obvious reasons, Catalan - which is region specific and not country-specific, Russian Latin - which can be used for subtitles only, and Volapük- constructed synthetic language). Safe bet, but 

⚠️ ❓ if there are some nagative implications of going this way other than lots of scrolling in the drop down.. not sure, but it does look excessive to me on a common sense level.

NB: Subtitles language selection is not allowed on YT, but inherited from Video Language

Abkhazian
Afar
Afrikaans
Akkadian
Albanian
⚠️ American Sign Language
Amharic
Arabic
Aramaic
Armenian
Assamese
Aymara
Azerbaijani
Bambara
Bangla
Bashkir
Basque
Belarusian
Bhojpuri
Bislama
Bodo
Bosnian
Breton
Bulgarian
Burmese
Cantonese
Cantonese (Hong Kong)
⚠️ Catalan
⚠️ Cherokee
Chinese
Chinese (China)
Chinese (Hong Kong)
Chinese (Simplified)
Chinese (Singapore)
Chinese (Taiwan)
Chinese (Traditional)
Choctaw
Coptic
Corsican
Cree
Croatian
Czech
Danish
Dogri
Dutch
Dutch (Belgium)
Dutch (Netherlands)
Dzongkha
English
English (Canada)
English (India)
English (Ireland)
English (United Kingdom)
English (United States)
Esperanto
Estonian
Faroese
Fijian
Filipino
Finnish
French
French (Belgium)
French (Canada)
French (France)
French (Switzerland)
Fulah
Galician
Georgian
German
German (Austria)
German (Germany)
German (Switzerland)
Greek
Guarani
Gujarati
Haitian Creole
Hakka Chinese
Hakka Chinese (Taiwan)
Haryanvi
Hausa
Hawaiian
Hebrew
Hindi
Hindi (Latin)
Hiri Motu
Hungarian
Icelandic
Igbo
Indonesian
Interlingua
Interlingue
Inuktitut
Inupiaq
Irish
Italian
Japanese
Javanese
Kalaallisut
Kannada
Kashmiri
Kazakh
Khmer
Kinyarwanda
Klingon
Konkani
Korean
Kurdish
Kyrgyz
Ladino
Lao
Latin
Latvian
Lingala
Lithuanian
Luxembourgish
Macedonian
Maithili
Malagasy
Malay
Malayalam
Maltese
Manipuri
Māori
Marathi
Masai
Min Nan Chinese
Min Nan Chinese (Taiwan)
Mixe
Mizo
Mongolian
Mongolian (Mongolian)
Nauru
Navajo
Nepali
Norwegian
Occitan
Odia
Oromo
Papiamento
Pashto
Persian
Persian (Afghanistan)
Persian (Iran)
Polish
Portuguese
Portuguese (Brazil)
Portuguese (Portugal)
Punjabi
Quechua
Romanian
Romanian (Moldova)
Romansh
Rundi
Russian
⚠️ Russian (Latin)
Samoan
Sango
Sanskrit
Santali
Sardinian
Scottish Gaelic
Serbian
Serbian (Cyrillic)
Serbian (Latin)
Serbo-Croatian
Sherdukpen
Shona
Sicilian
Sindhi
Sinhala
Slovak
Slovenian
Somali
Southern Sotho
Spanish
Spanish (Latin America)
Spanish (Mexico)
Spanish (Spain)
Spanish (United States)
Sundanese
Swahili
Swati
Swedish
Tagalog
Tajik
Tamil
Tatar
Telugu
Thai
Tibetan
Tigrinya
Tok Pisin
Tongan
Tsonga
Tswana
Turkish
Turkmen
Twi
Ukrainian
Urdu
Uyghur
Uzbek
Venda
Vietnamese
⚠️ Volapük
Võro
Welsh
Western Frisian
Wolof
Xhosa
Yiddish
Yoruba
Zulu

**Comment by kdembler** [comment]
Just FYI, Query Node currently uses [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for language codes, so if we want to avoid changes there, the languages we pick should be represented in ISO 639-1, you can find the list on wikipedia

**Comment by dmtrjsg** [comment]
Ready for dev: https://docs.google.com/spreadsheets/d/1DS8nyJWLQpXWKrX9q697VHj2snV4rUwTVkWN3PlKEOE/edit#gid=0

**Comment by bedeho** [comment]
Seems this has been settled, I'm not needed.

**Comment by dmtrjsg** [comment]
@toiletgranny we need to slightly modify the drop down selector for languages to allow for horisontal delimiter between popular languages and the rest of the languages since it has a "popular' section.

**Comment by toiletgranny** [comment]
@dmtrjsg Done! 

1. I added a new component, a List divider, designs and documentation for which [can be found here](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9696%3A171951),
2. I updated the designs and user stories for adding subtitles, which [can be found here](https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1945%3A109809).

> **Note**
> Since we're using the Combo box component for selecting languages, which allows typing to search, please note my recommendation is to hide dividers for when the list of languages is filtered out by the user's input.

![image](https://user-images.githubusercontent.com/35307309/193799856-7548bdff-69a5-45e8-ada6-c1a8f71df53a.png)

**Comment by dmtrjsg** [comment]
Love it 😍

**Comment by dmtrjsg** [comment]
@drillprop will this also apply to selecting the language of subtitles?

**Comment by drillprop** [comment]
> @drillprop will this also apply to selecting the language of subtitles?

Yeah, we can add this. I mean - I don't see any obstacles to adding this as well in the subtitles select element.

**Comment by dmtrjsg** [comment]
Great, will add this to the acceptance criteria 👌
