### ISSUE TITLE
Jsgenesis Atlas instance

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3273]
# Background

We have done the technical and design work to make the Atlas _codebase_ customizable when deployed as a running instance, as described here: https://github.com/Joystream/atlas/issues/2512

There is however one major outstanding question: _what about the instance that Jsgenesis operates?_

The specific questions are
1. **what should be the instance name and logo mark?**
2. **what should be the domain at which it is served?**
3. **what sort of content and category space should be used?**

Right now, it is just called _Atlas_, which is the same name as the primary codebase, it has a logo mark pretty similar to the Joystream mark, it is most recently planned to be served from `www.atlasplay.io` and it has no explicit content focus and a corresponding very generic set of content categories

- Pets
- Music
- Nonprofits
- Travel
- Entertainment
- Comedy
- Autos
- Science
- People
- Education
- Gaming
- Film
- News
- Howto
- Sports

# Proposal

## Premise

The reason Jsgenesis should operate a gateway at all boils down to a timing issue: right now, the technical and operational team is very well organised and informed, and the DAO will just be getting started. By running it's own gateway, three strategically valuable goals can be supported

a. it becomes easier to focus on building in a way that serves third party gateways that will be launching later.
b. it becomes easier to rollout and test totally new features with being exposed to the uncertainty around the precise timeline at which new and well organised gateways will operate.
c. it becomes easier to much earlier attract the initial set of creators and consumers, which itself is valuable to do **early** because
  - c.1. it assist in prioritising further development on Atlas on the basis of real user input.
  - c.2. it generates realistic load/abuse on key infrastructure like faucet, YPP, Orion, QN, storage and distributors.
  - c.3. it generates more awareness of the project in the crypto space overall

The first two are achieved regardless of the exact brand used, at least to a significant extent, but I believe the last one is very sensitive to the

## Case Study: `Mirror`

![Screenshot 2022-09-22 at 00 08 32](https://user-images.githubusercontent.com/437292/191619250-986b26c4-cd80-4da4-8ca3-81f839336d95.png)

[Mirror](http://www.mirro.xyz) billed itself as "Medium on the Blockchain", so to speak, where the content and author index lived on Ethereum and assets lived on Areweave, and it differentiated itself from Medium most clearly through the bundling of innovative NFT tools around monetising and fundraising written works. They very quickly, either by user demand or deliberately, became very focused on building out a curated pool of authors from the Web3 space, which they built through something they called the "$WRITE Race", which was a combined token incentivised writing and status competition. They have been very successful at establishing themselves as the de-facto writing platform in Web3 itself, and publishing there is now considered a positive signal of authenticity and status, and while they still have a way to go branch into the mainstream that Medium is able to serve, it seems quite clear that they have done very well by focusing on the Web3 authorship space as a beachhead.

## Thesis

The best way to achieve goals c.{1,2,3} is to focus on the creator on a vertical where we have the greatest tailwinds: **blockchain**. If we during the next year can serve the video creator community in our space anywhere close to how well Mirror has, it will have been a great step forward for the project in a multitude of ways, and an excellent foundation upon which future growth can be built.

## Specifics

The way specifically execute on this focus based thesis is firstly to adopt a creator acquisition strategy which is aligned with this focus, but also to have a distinct set of categories used to only surface content related to this focus. The name itself, like `Mirror`, need not be very narrow or descriptive, it just needs a decent presence online. A name is just a name, and e.g. `YouTube` & `TikTok` are ridiculous names all the way up until the moment they aren't.

- **Name:** Gleev.
- **Domain:** gleev.xyz (available 20 NOK)
- **Categories:**
  - Investing
  - Podcasts
  - Conferences
  - Reviews
  - Tutorials
  - News
  - Memes
  - Interviews
  - Analysis
  - Predictions
  - Trading

## Rationale

There are two categories of reasons why this thesis is an effective approach for reaching our goals

1. Focusing on a vertical rather than being generic:
   - It's easier to capture new creators when you can reference others they may know as already being onboarded.
   - It's easier for creators to effectively refer their peers.
   - It's easier for new creators to understand why the offering is particularly relevant to them and their audience.
   - It's easier to focus communication, marketing, tutorials and campaigns around a more homogenous pool of users, as they have a more uniform set of references, expectations, requirements and understanding.
   - It's easier to build a pool of content that starts to become interesting to the consumer side.
2. Focusing on blockchain specifically:
   - Both the creator and consumer side is already more aligned aspirational.
   - Many creators are already subject to serious publishing and monetization constraints around their content.
   - Both the creator and consumer side already has, in relative terms, a greater understanding of a large number of the UX concepts that are new to a more general audience (wallets, transactions, assets, fees, etc.), and is also much more patient with the immaturity of the tech and products.
    - Both the creator and consumer side is disproportionately on desktop, which is where we are strongest right now, compared ot general content audience.
   - Automatically generates awareness precisely in the community where we would like to generate more awareness (c3).
   - Like `Mirror`, publishing and using a web3 native platform for content can become sign of authenticity, further encouraging adoption and use.

## Implications

- **Website:** Right now, the website has a few key CTAs saying `Claim your channel`, talking directly to creators, primarily because the whole site speaks very directly to creators, not because we were expecting that creators were going to land on the main project website as part of the natural signup flow, they were not. It may however be more prudent now to clarify things by either replacing this CTA, or having it send you to a section or new page which shows an overview of apps/gateways which you can get onto. This should also explain how these are different apps built on one platform. The Jsgenesis app would merely be one of these.
- **Curation problem:** Its unclear how fast this becomes an issue, but at some point someone may end up publishing something under a gateway which does not actually fall under the topic scope of that gateway, e.g. uploading a cooking video under the trading category of the Jsgenesis gateway. This is a curation problem that can be solved both at public and gateway layer, but I suspect the public resolution of such mistakes is needed as well - so everyone automatically benefits from the error correction. Thus some extra message would be needed where a category owner can evict a video.
- **YPP:** YPP running on the Jsgenesis gateway will need to explain that the content has to fall into one of the appropriate categories, and we indeed already have an open question relating to exactly this, namely which content category videos from youtube should be replicated into by default.

**Comment by dmtrjsg** [comment]
1. **Targeting:** Focussing on the single vertical is certainly beneficial, blockchain/web3 seems a natural one with growing audience, so fully support that. Name - pretty good and snappy. Has some emotive link to it, great pick.
2. **Multiple gateways and CTA upd** I like the idea of having an intermediate page featuring all gateways, but this would probably mean re-jigging some of the main project landing page. 
3. **Curation** The design for this is pretty much done, all we need is to add a specific category to the reporting. I wonder if curation of all gateways would fall on DAO Content Curators Workers? Or would this be part of Gateways  WG responsibility, which would in effect need some sort of sub-groups to split the responsibilities. Maybe I'm missing smth
4. YPP - ackd. 

Happy to create the issues for design and we can start as early as next week 🚀

**Comment by toiletgranny** [comment]
1. `Gleev` ❤️ 

1. Narrowing down our initial target audience will make a lot of things easier for us, super excited for this! I think it might be a good opportunity for us to come up with a specific [user persona](https://www.nngroup.com/articles/persona/) to support future design conversations. I'll do some reading around that in my free time.

2. > **Website:** [...] It may however be more prudent now to clarify things by either replacing this CTA, or having it send you to a section or new page which shows an overview of apps/gateways which you can get onto. This should also explain how these are different apps built on one platform. The Jsgenesis app would merely be one of these.
   
   Is my understanding correct that it would be the goal for later, once there actually are more gateways other than ours? Or do you envision a list/grid view with just our gateway listed for now and perhaps some copy along the lines of "there's more to come, check back soon, this is where we'll be listing them"? 
   
3. > **YPP:** YPP running on the Jsgenesis gateway will need to explain that the content has to fall into one of the appropriate categories, and we indeed already have an open question relating to exactly this, namely which content category videos from youtube should be replicated into by default.

   Excuse my question if it's already been discussed at some point in the past, but is mapping YouTube categories to Joystream ones, and then assigning video categories based on that mapping not an option for us?


4. > **Curation problem:** [...] Thus some extra message would be needed where a category owner can evict a video.

   Oh, did not know that would be possible. Has it been decided what happens with the video once its _evicted_? E.g. does it become uncategorized? Regardless, would it make sense to perhaps shift the efforts towards preventing this from becoming an issue (as much as it's possible), rather than developing solutions for mitigating this? Haven't been doing any reading around that, so I'm probably missing a lot of technical complexity behind it, but what I've seen YouTube doing for quite some time now is what seems to be relying less and less on user-specified video categories and, instead, more on them analyzing the video's metadata (title, desc, tags, perhaps even the video contents itself too?) to determine the subject. This allows for much finer and more sophisticated video categorization, which also translates to more effective video recommendations. 


---

Also, to address the three specific questions you mentioned:
1. **what should be the instance name and logo mark?**
    I, too, like the name `Gleev`. Also liked `Vijoy` and `Joycast`.
2. **what should be the domain at which it is served?**
   It is now clear to me how the `.xyx` domain extension has become a web3 thing, but if it's not a huge financial issue, I'd also consider registering other domain extensions, such as `.app`, `.io`, or `.net` if available.
3. **what sort of content and category space should be used?**
   I believe that starting without a specific content focus is the best way to go, and might be the most effective way to support the goal C.

**Comment by dmtrjsg** [comment]
@toiletgranny 
>Is my understanding correct that it would be the goal for later,

Thought so initially as well but after deliberation arrived to understanding that we can have a copy/ concept of multiple gateways more prominent and the list of apps can be pretty humble, designed in the way where Atlas can be the only one without much harm/ empty space.

>Mapping YouTube categories to Joystream ones, and then assigning video categories based on that mapping

Zeeshan started looking into it, and we'll have a better view on the category trees mapping and take a view on that after.  After a quick review I figured that YT has channel categories and videos inherit them.. but this issue will shed more light on it:
- https://github.com/Joystream/atlas/issues/3183#issuecomment-1252162132

> but if it's not a huge financial issue, I'd also consider registering other domain extensions, such as .app, .io, or .net if available.

This is actually a good idea!

**Comment by kdembler** [comment]
1. Name sounds pretty cool, I also get the point of narrowing down the target audience and see benefits of it but I think we also have to be clear about some downsides related to that:
a) I think some of our most active creators using the platform today would fall outside of the Gleev categories. I think about Eclipsing Binary, SatoriD and couple others. It would suck if the app they've been using for a couple of months and have started to build some community in, suddenly will reject their content.
b) You will probably say that as a remedy for above, community will launch new Gateways and some of them will be able to capture content from those people. True, but I'm not sure if that's best for our project's growth. The size of our userbase atm is very small already. If we force the community to split between different apps right away, I'm afraid we won't get critical mass to achieve success.
c) I guess that for some time, until real players looking for profit come and try to build their gateways, our own will be the highest quality and should be "showcased" when new users are looking into the platform to ensure best conversion rates.<br><br>To sum up, I'm not sure what is the best way to proceed forward. I see why verticalised is better for a couple of reasons but I think that we need solutions for problems above. Maybe we do Gleev and another very generic instance that doesn't get that much love but also just shows everything there is on the platform? I don't know...

2. Re curation:
> This is a curation problem that can be solved both at public and gateway layer, but I suspect the public resolution of such mistakes is needed as well - so everyone automatically benefits from the error correction. Thus some extra message would be needed where a category owner can evict a video.

a) How exactly do we solve this on public layer? I think the only thing that can be done by the DAO is to mark the video as censored? 
b) What about featured content on Gleev? Current Atlas instance gets featuring updates from DAO curator workers, I don't think that works once we market ourselves as something separate from Joystream? They currently update:
- Home video hero
- Featured videos for each category (visible in Discover and in specific category pages) (worth considering how valuable that really is)

**Comment by bedeho** [comment]
> I think some of our most active creators using the platform today would fall outside of the Gleev categories. I think about Eclipsing Binary, SatoriD and couple others. It would suck if the app they've been using for a couple of months and have started to build some community in, suddenly will reject their content.

I feel like those guys are sort of blockchain adjacent at the very least, they are actively exploring the space and talking about related topics. I am sure they could reasonably feel at home in one of the broader categories, perhaps not with all of their content though. But I do think we have to limit how much strategic emphasis to put on that handful of actors.

> I guess that for some time, until real players looking for profit come and try to build their gateways, our own will be the highest quality and should be "showcased" when new users are looking into the platform to ensure the best conversion rates.

The implication of this is that you think we should be conservative about showcasing other apps on Joystream org? not sure I understand where you are going with that point. If so, then I think we certainly need to be sensitive to where we send people indeed, so for example if a site goes down or something, clearly, we should not be linking to it, but I am not sure how restrictive we should be, I guess this will sort of be clear when we have more concrete examples to look at.

> another very generic instance that doesn't get that much love but also just shows everything there is on the platform? I don't know...

Yeah that could work actually (Vinteo ??? :D), I guess I would just be a bit concerned about the overhead of operating two? **what do you think, sounds interesting**.

> How exactly do we solve this on public layer? I think the only thing that can be done by the DAO is to mark the video as censored?

No it means that whomever owns a category, which would be the remember creating it, is allowed to basically disassociated any video which claimed to be in that category, so this would require a new metaprotocol message, and it would leave the video without a category assignment. At this point, the video owner could update the category to something else, or just leave it.

> What about featured content on Gleev? Current Atlas instance gets featuring updates from DAO curator workers, I don't think that works once we market ourselves as something separate from Joystream? They currently update:

I guess I messed up here, I thought 100% was controlled by operator. I thought we had removed all of that? or perhaps this is also what you mean, you are just asking who in Jsgenesis should do this work going forward?

**Comment by kdembler** [comment]
> I feel like those guys are sort of blockchain adjacent at the very least, they are actively exploring the space and talking about related topics. I am sure they could reasonably feel at home in one of the broader categories, perhaps not with all of their content though. But I do think we have to limit how much strategic emphasis to put on that handful of actors.

Fair enough

> The implication of this is that you think we should be conservative about showcasing other apps on Joystream org? not sure I understand where you are going with that point. If so, then I think we certainly need to be sensitive to where we send people indeed, so for example if a site goes down or something, clearly, we should not be linking to it, but I am not sure how restrictive we should be, I guess this will sort of be clear when we have more concrete examples to look at.

`I think we certainly need to be sensitive to where we send people indeed` 👈 basically that. But agreed, I guess we can clear this out along the way.

> Yeah that could work actually (Vinteo ??? :D), I guess I would just be a bit concerned about the overhead of operating two? what do you think, sounds interesting.

I don't really think there's any overhead, outside of featuring videos as I mentioned in my other point. Any bugfixing etc would still happen for Gleev anyway

> No it means that whomever owns a category, which would be the remember creating it, is allowed to basically disassociated any video which claimed to be in that category, so this would require a new metaprotocol message, and it would leave the video without a category assignment. At this point, the video owner could update the category to something else, or just leave it.

Hmm I wouldn't go that way. It is not clear that the category creator holds any control over it, I think this would cause more category segregation as each operator would probably want to control all of the categories displayed in their app. As an operator, you wouldn't want to rely on some random person controlling one of categories in your app, so every operator would most likely create all the categories themselves, kind of breaking the idea of shared category pool.

> I guess I messed up here, I thought 100% was controlled by operator. I thought we had removed all of that? or perhaps this is also what you mean, you are just asking who in Jsgenesis should do this work going forward?

It is indeed controlled by the operator, that is all the featuring happens in Orion. It's just that currently all of that is still done by curators, they just interact with Orion instead of the chain. So we can do this independently from the DAO, but like you said, somebody will just need to do it.

**Comment by bedeho** [comment]
> I don't really think there's any overhead, outside of featuring videos as I mentioned in my other point. Any bug fixing etc would still happen for Gleev anyway

There is also the DMCA, YPP, and possibly some infra monitoring effort, but fair enough. I guess my next question is then: we only have so many people to actually do the creator acquisition work, to work with them, capture feedback, handholding and [all the unscalable stuff which is key to success](http://paulgraham.com/ds.html). If we have to choose how to split resources between Glee and Vinteo, I would put 100% on the former in terms of these specific activities. Disagree? If not, do we just leave Vinteo to sort of have to rely on 100% organic growth without any deliberate care? Is that bad? is it a free option to catch interested folks that don't fall into the Gleev product and where community gateways don't exist yet?

> so every operator would most likely create all the categories themselves, kind of breaking the idea of a shared category pool.

exactly :D, so that's my point, should we be breaking or facilitating this idea? I think the latter, after all this shared compilation of a public content pool is extremely powerful. 

I have not published it yet, but I have a very simple proposal that allows decorating publishing channels and content with the app within which it was published, this allows attribution of contributions to the creator and content pool to the originating app. This allows chain to make sure to give applications a share of the value that a creator generates into the future. In this world, an app basically has an interest in other apps distributing their content, rather than hiding it, and having accurate metadata associated with your categories and content supports this goal.

> As an operator, you wouldn't want to rely on some random person controlling one of the categories in your app

Well it would not be random, but ultimately I think it is very valuable for applications to be able to use inflow of content acquired by other credible gateways. I am not saying you _have to_, and you can certainly avoid it - as you describe, but I am saying that it's important to facilitate the option that you could. This just again boils down to the core question: is it valuable to have a public pool of content and creators that apps have incentives to both use and contribute to in a scaleable way? I believe yes.

> but like you said, somebody will just need to do it.

Indeed, ok, so yes, not sure who, I will be involved in working with creators, probably @dmtrjsg  also, so perhaps we can split the bill between us.

**Comment by kdembler** [comment]
> If we have to choose how to split resources between Glee and Vinteo, I would put 100% on the former in terms of these specific activities

Agreed

> do we just leave Vinteo to sort of have to rely on 100% organic growth without any deliberate care? Is that bad? is it a free option to catch interested folks that don't fall into the Gleev product and where community gateways don't exist yet?

I think that's completely fine. If the DAO/Gateway working group want to give it some love, then sure, but I think it should be lowest effort from us - just make it available.

> This just again boils down to the core question: is it valuable to have a public pool of content and creators that apps have incentives to both use and contribute to in a scaleable way? I believe yes.

I'm not sure if I'm understanding correctly, but if by that you mean that categories should be shared as much between gateways as possible, then I agree. To make this work well I think we shouldn't introduce this concept of category ownership.

**Comment by bedeho** [comment]
> To make this work well I think we shouldn't introduce this concept of category ownership.

How then to make sure categories are actually respected? if there is an owner, the owner will take responsibility and curate w.r.t. meaning people expect, at least if the arrangement works, if not, every gateway will have to either manually review everything before syndicating, or risk giving their users a bad experience. Like say if I start publishing white noise videos to all categories, just spamming, now every gateway for every piece of content has to detect, and block client side. 

I am happy to not do anything out of the gate, just see how it evolves, may be a non-issue for a long time.

**Comment by kdembler** [comment]
Hmm yeah I see your point but I think we also need to consider gateway operators being uncomfortable with using categories that give external actors privilege to mess with videos published under the gateway. Perhaps some 3rd solution we don't see at the moment. Like you said, maybe best to ignore for now

**Comment by dmtrjsg** [comment]
Perhaps I am a little late to the party, as we seem to have achieved an agreement on Gleev (Crypto vertical) vs Vineto (everything else), but having thought about this more here are my considerations:

1. While the Apps are a storefront for the blockchain capabilities, we are also pursuing the purpose of enabling creator-driven marketing.
2. The product should benefit creators, that can effective sell their NFTs and CRTs to the audience without friction, and I have a hunch that non-crypto creators may have a much bigger audience that can cross-pollinate different channels and creators without changing the vertical. There is a benefit in aggregating when thinking about this context.
3. Deliberately restricting the target audience or splitting across multiple apps will be a detriment for this objective, even though operationally (read: content curation) and ux wise (read: navigation inn the lack of proper back end and poor on site search experience) its more beneficial to have more narrow focus. 

I feel like we may be able to do best of both, focus our marketing efforts on Crypto Community and still allow for other content to grow organically.

Challenge of maintaining of quality/ more targeted content can be achieved with promoting Crypto category in-app.  We could go as far as having a Top Menu Item for “Featured Crypto Content” with a mix of Channels/ Videos/ NFTs / Tokens. 

Q: Is there a technical limitation that prevents us from having 2 levels of categories in Gleev to accommodate for subcategories that you suggested in the original ticket?

If we could go with the multi-level category structure  like this:
Crypto>
Interviews
Analytics
Investing
DAO
..
Pets>
dogs
cats
lizards
..
I can see how we could further down the line enable us to promote a better way to promote the Crypto lvl1 category in Popular/ Home/ and Discover modules. Which In my view would serve both purposes for us to focus on lvl1 category promotion while supporting some content specification for the benefits of easier navigability.

cc
@kdembler @bedeho

**Comment by bedeho** [comment]
# Points of Agreement

I agree with your basic observation here, to summarize: _the user acquisition activities can have a content focus while the product itself does not._ Here are some additional points in favor

- If one reviews the `Rationale` section above, it is indeed clear that many of these hold to some extent, or even same extent in many cases, if we focus on web3 in terms of user acquisition only. 
- `Mirror` itself does not do anything to restrict or influence what sort of content is published. 
- We would not need to have two apps, which I still believe will have extra overhead. This is a real issue because we may see adoption from creator segments we did not anticipate, and if Vinteo is at that point less prioritized, then we could be loosing out.

# Points of Disagreement

> I have a hunch that non-crypto creators may have a much bigger existing audience with much more compelling content when we speak NFTs trading volumes.

I don't think how compelling the content is in a general sense is close to the first-order factor when it comes to the the success prospects with NFT/CRT tools. Yes, _someone_ ha to find the content and the creator compelling, that is a requirement, but beyond this, I believe the ability to comprehend and deal with Web3 concepts (fees, wallets, signing, addresses, staking, confirmations, NFTs, tokens, ....) is a much greater factor. 

> Deliberately restricting the target audience or splitting across multiple apps will be a detriment for this objective, even though operationally (read: content curation) and ux wise (read: navigation inn the lack of proper back end and poor on site search experience) its more beneficial to have more narrow focus.

I presume you are saying it's more useful for the same app to have two creators, from distinct verticals, in the same app, rather than in two distinct apps.

I believe this has very little value under most reasonable partitionings of the content space, because in all cases only a minuscule portion of the overall creator pool will be onboarded in the near term, and hence the chance that a consumer will benefit from the greater liquidity by happening to have two distinct vertical tastes catered to is extremely small.

# Conclusion

I see some unique benefits of not only having a narrow user acquisition focus, but also content selection, specifically

1. **More sticky consumer experience:** By a strict filtering on content, target consumers will find a greater density of relevant content in all areas of the application, and they will recognizes the entire product as more relevant to them both now and in the future. It will increase the chance they come back and check up on the product or refer it to friends. This will assist in growing a more focused consumer base, which subsequently helps address one of the biggest pain points for new creators: reaching aligned users. This is particularly challenging for newcomers. I have tried to describe this matching problem as being a big opportunity in unbundling YouTube in [this recent community call](https://play.joystream.org/video/27410?time=673).
2. **Better server-side discovery:** The effect described in the prior point will be strengthen even further when discovery actually has a server-side. Trying to do sensible search and recommendations, based on dynamic user consumption data, over very diverse content, and also just more content, will be much harder to do well.
3. **Crowding out:** By putting effort into a generalized content product, it is at much greater risk of crowding out third party efforts to try to do the same or focus on alternative verticals, because less organised smaller initiatives will see themselves to a greater extent in direct competition with Jsgenesis. More implicitly it may just make it less clear that the point is a vision with a diverse set of products ontop, rather than one monolithic youtube clone. **For this reason I  think we should not do Vinteo at the same time, despite my earlier buyin. I'd rather have us detect organic creator pull, and convey this as an opportunity for the community as first pass. Also, this pull won't come homogenously across all verticals, it will be focused, and we will get the benefit of observing this focus.**
- **Optionality:** If we started with a narrow user base in Gleev, expanding in light of new evidence later has very limited transition costs. Forgive the hubristic analogy, but if Facebook can start as a lookup directory restricted to a handfull of US colleges, and eventually transition to everyone over 13 across the globe, without some sort of brand conflict, then likely Gleev could gracefully expand as well. This means by starting narrow, we get to explore the hypothetical benefits I describe in 1,2,3. Conversely, if we just start in the other end, we just never get to test this at all, and the long term unique upside in that alternative path seems very low.

At this point we have discussed this quite a lot, which I think is very useful, it certainly helps me sharpen my thinking. But I also think its time to just conclude, move forward, and learn what happens when.

I suggest, as a remedy, we add some point in the Gleev onboarding flow where we clarify the verticalised focus, as I described above, and we give some very prominent CTA if the person trying to join feels they do not fall in scope, and then alternatively just capture them in some form or something, and tracking analytics of how often someone signals this, even if they don't complete the form.

---

# Category Levels Question

> Q: Is there a technical limitation that prevents us from having 2 levels of categories in Gleev to accommodate for subcategories that you suggested in the original ticket?

This is mostly a design challenge, Atlas does not work like that currently, and depending on how its implemented in Atlas technically it need not be more than that. Specifically, if we allow display categories, which are purely client side, to have nested organization, but leave public categories to be linear, then nothing would have to be done at the metaprotocol level. This would have the added benefit of not leaking all sorts of very Atlas level assumptions into the standard, such as the whether that there can be exactly 1, 2 or arbitrary levels of depth in the category tree.

**Comment by dmtrjsg** [comment]
Thank you @bedeho for providing a detailed feedback. The `crowding out` point is actually something I have not fully considered at the time of writing, and taken from this perspective, it makes sense to only focus on a single vertical, without the ambition to accommodate for residual categories in a less-curated Vinteo.

I see your point on the Web3 "obstacles" for generic audience, being overweighting the benefits from broad content discovery, especially in the absence of proper backend support for content discovery at the time of launch. 

Re categories, noted 👍  in the light of Gleev App with strict content vertical focus, that would be something we can address later.

**Comment by mochet** [comment]
I think a podcast/audio app is essential, but I imagine its probably not doable right now, but should be a priority after launch IMHO

> -   `Mirror` itself does not do anything to restrict or influence what sort of content is published.

This is not entirely true, they had a competition system for quite a while for users to actually get access as an author so they did very much influence the quality of their initial userbase.

> because in all cases only a minuscule portion of the overall creator pool will be onboarded in the near term

I think this highlights one critical requirement for most gateways to fulfill in the early days (and perhaps requires governance, it will certainly require tooling to be developed) which is to create highly regular competitions for content (of whichever variety a gateway is intending to focus on).
I think rewarding creators before they even think about channel payouts/NFTs/creator tokens is the best way to achieve traction when attracting a pool of valuable creators.

Note that rewarding creators via competitions would involve 2 methods:
- Immediate financial incentives
	- instead of waiting for weeks/months for the other incentive methods to matter
- Prominent social placement (or free advertising) of their content for some period of time
	- essential to community building and developing a sense of belonging for creators
- Perhaps also some form of "award" being tied to the channels profile, signalling they have won competition(s)

If the competitions are organized well then they can focus on content categories which are distinct--and there is no reason there cannot be simultaneous competitions being run.

Competitions do require some way for a user to signal that the video is valuable which could be:
- Views
- Subscriptions
- Comments
- Likes
- Off-chain signals (via Discord bot or something)
- For sybil resistance: only considering signals from users who match some criteria

It could even mirror the early onboarding experience of Mirror by restricting publishing access using a voting system.

I have put a lot of thought into competitions already and how important they will be and developed some partial methodology where they can be launched, measured and reported. If this went through DAO governance it could easily become a way of measuring a gateway's "performance" which is distinct and highly valuable.

If competitions are measurable and repeatable, then it makes it very trivial once they have matured enough to change their focus area and build the community.

An interesting example: https://docs.writingmonks.com/guides/predict-performance

**Comment by bedeho** [comment]
I think your reply here @mochet , while interesting, is not really on topic, and your observations will just get lost when this issue of Atlas instances is shipped. I think you should find a better place for these ideas.
