### ISSUE TITLE
Having created a channel on my phone, I can't see it on desktop

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3284]
**As is:** Having created a channel on my phone, after heading back to Atlas on a desktop I can't find any trace of it in the Member dropdown component, nor when accessing Studio. Even after refreshing the page. Note, that I've been signed into my JS membership on both devices through the entire course of creating a channel on another device.
**To be:** Having created a channel on one device, ideally, upon refreshing Atlas on another device, I can see my channel in the Member dropdown component and I can access Studio with it.

**Phone:**
iPhone 12 Pro, iOS 16.0, Safari inside of the Polkawallet app.

https://user-images.githubusercontent.com/35307309/193005747-e9fa4bdc-dd07-4956-9e23-fa8aef9fcfda.MP4

**Dekstop:**
Chrome 105.0.5195.125 (Official Build) (arm64), Polkadot.js browser wallet

https://user-images.githubusercontent.com/35307309/193006142-c31edde7-d5c0-4d9b-8a7e-d29541645ec9.mp4

**Comment by WRadoslaw** [comment]
Couldn't reproduce this, closing it for now.
