### ISSUE TITLE
Incorrect implementation of the Dialog footer component (Fee)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3286]
Dialog footer's component implementation is off compared to the designs [(link)](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=8638%3A170301) when it comes to the fee is displayed with two buttons.

Design | Implementation
---|---
![image](https://user-images.githubusercontent.com/35307309/193013129-aca666b8-ab41-45fc-8e71-3d82fb4f760f.png) | ![CleanShot 2022-09-29 at 12 49 07](https://user-images.githubusercontent.com/35307309/193012438-0003c6d7-08f6-4ce4-9a4c-1ee3a6bad6a6.png)

**Comment by dmtrjsg** [comment]
@toiletgranny hey we've all looked at it and kind agreed that it looks better above the buttons 😅 😇 .. Hope you don't mind if we keep it as is .. :)
