### ISSUE TITLE
Figma backup

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3314]
This task aims to set up an automated backup of all Figma files stored in [the Atlas team](https://www.figma.com/files/team/988759271589293564/Atlas?fuid=730334878476004289), as requested by @bedeho.

Ideally:
1. The end solution is 100% autonomous,
2. Backup is done every 24 hours, at night, somewhere between midnight and 3 am,
3. All files stored in the Atlas team are backed up,
4. Backups are stored for 30 days.

cc @dmtrjsg

**Comment by dmtrjsg** [comment]
@toiletgranny  I understand thats a set up inside Figma itself? ..could you do the same for Pioneer pls?

**Comment by rafalpawlow** [comment]
@dmtrjsg Actually not, It will be a service that will download backups via figma API. Klaudiusz asked me to take care of this. It will be configurable so there will be no problem using it for Pioneer.

**Comment by toiletgranny** [comment]
Just like @rafalpawlow said. My goal was to create a separate ticket for Pioneer once we first try it out in Atlas.

**Comment by dmtrjsg** [comment]
ahh thanks for the clarification @rafalpawlow, wasn't aware of this, sounds good 👍 

thanks @toiletgranny 🙏
