### ISSUE TITLE
Gleev Logo and Assets upd

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3320]
**Scope:**

- [ ] Update the logos
- [ ] Update the favicons
- [ ] Also, let's make sure to change the name of the "Popular on Joystream" section on the homepage to "Popular on Gleev".
- [ ] Update the maintenance view (@dmtrjsg to provide updated copy)

---

dmtrjsg commented on [Tue Sep 27 2022](https://github.com/Joystream/marketing/issues/293)

## Context
In-line with the concept of multiple gateways we need to update the logo of Atlas to Gleev a

* #289
Depends on:

* https://github.com/Joystream/atlas/issues/3276

Out of scope ⛔ 

* logo for Vinteo

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203133500663216) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@kdembler, let's do this!

1. The new logo can be found and exported from the [Foundation figma file](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=716%3A70391).
2. Pages and components to be updated, based on the scope outlined in changelogs (to which I'm pasting links below) are:
   - [Side navigation](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9779%3A174960),
   - [Top navigation](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9151%3A168457),
   - [Member dropdown](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9258%3A167766),
   - [Video page](https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=6396%3A297910),
   - [Channel page](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414)
   - [Sign in flows & the Welcome to Studio screen](https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-in-flows?node-id=2013%3A33819).
3. This time I created a set of dedicated favicons for each platform, all of which can be found and exported from [this page in the Foundation file.](https://www.figma.com/file/Cc3VDoK6qglJ617ChA2EMr/Foundation?node-id=1575%3A25754)
4. Also, let's make sure to change the name of the "Popular on Joystream" section on the homepage to "Popular on Gleev".

cc @dmtrjsg @bedeho

**Comment by dmtrjsg** [comment]
@toiletgranny imho we also need to update this maintenance mode screen to be Gleev branded:


<img width="628" alt="Screenshot 2022-10-18 at 14 29 34" src="https://user-images.githubusercontent.com/93924525/196406876-de7d01ba-abe8-4f3e-ab3c-20ec31f8b66e.png">

Here the concept is that once we are on Mainnet, the app will not be available for some days while the network is rolling out.. It may take a week or more. I think the fact that its t_he network update being rolled out_ hence the app is not operational, may be worth reflecting as well.

On the copy side we may benefit from a slight shift of the focus from "We will be right back!" to "We will be up and running soon" as this is more broad. 

cc @bedeho

**Comment by toiletgranny** [comment]
Totally on board with the copy change suggestion, but not entirely sure now about the logo change. Specifically: should it be the Gleev logo or the Atlas logo?

The reason I'm asking is that just yesterday I was informed by our engineers that I've prematurely removed Atlas-branded product screenshots and Atlas logos from Figma, because — which is something that came to me as a surprise — we will be still using those alongside Gleev branding now; not in place of it. cc @kdembler 

So in light of the above, I thought I might double-check if it's indeed the Gleev logo we should be using here?

**Comment by dmtrjsg** [comment]
@toiletgranny Since screen informs users that Gleev app which is presumably referenced in the upstream journey (e.g. marketing website) is not available, I'd say in this case let's use Gleev Logo 👍

**Comment by kdembler** [comment]
We've discussed this topic with @bedeho today. The conclusion was this: Gleev will be jsgenesis-managed gateway but we will still have the "default" or "stock" Atlas codebase that will act as a basis for Gleev. We want that default Atlas to work out of the box with its own "Atlas" branding. So the unfortunate consequence is that whenever we prepare an asset (like a product screenshot), we should have separate versions for Atlas and Gleev. @toiletgranny I don't think we need to maintain separate component libraries, we can just replace the logo on the fly where needed

**Comment by toiletgranny** [comment]
Ok, thanks for clarifying that!

**Comment by toiletgranny** [comment]
Alright, @kdembler, hope this will do. Hope the copy is okay, @dmtrjsg.

https://www.figma.com/file/xBXWBZMqM0JAydQZ7ZaZ6D/Maintenance-page?node-id=101%3A17142
