### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3326]
The current README was built when Atlas was thought of as a sort of canonical example app, and it does a great job at that. Its main audience is people who aspire to contribute to this codebase itself. Moving forward, Atlas going to be more explicitly a white-label software product, which is customizable, and where developers arriving at the repo will be looking to understand the power of this customization and production deployment, and how to get started trying this. The goal of having people contribute to Atlas itself is obviously still present, but it is subservient to the new primary goal.

**Comment by dmtrjsg** [comment]
Hey @bedeho do you have an example of the readme file you are having in mind? In the light of the operators guide we were unsure if a simple reference to the guide would suffice or extra formatting/ info is required to be added.

**Comment by bedeho** [comment]
No problem, will just close then.
