### ISSUE TITLE
Gleev Adaptation for Mainnet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3334]
## Context

This is a tracker issue to encapsulate all work carried out wrt Gleev rebranding, spanning Marketing website, YPP and Atlas onboarding experience

## Scope
- #3276 
- #3320 
- #3319  
- #3321 

Out of scope:
- #3322

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203142926083287) by [Unito](https://www.unito.io)

**Comment by toiletgranny** [comment]
@dmtrjsg I believe the scope of this epic is now fully addressed design-wise.
