### ISSUE TITLE
Landing page and onboarding journey variation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3344]
## Context
- https://github.com/Joystream/joystream/issues/4376

Specifically last point: 
".. to accommodate this [Launching gleev post-mainnet] is to make sure we have a reasonable variation of our mainnet landing page that works while we are launching, rolling out through the relevant stages, and before Gleev is up and running."

## Scope

* [ ] Create a variation of the marketing website which would announce soon to be released Gleev as a new brand name
In this variation: Explain that  [TBC]

Joystream Blockchain is on Mainnet already, but Gleev will not include any of the videos uploaded to date 
Joystream will be launching Geleev, own-managed version of Atlas codebase, which focusses on Web3 content

Atlas is the name of the codebase, which will remain as an open source project, available to be forked

:question: Does mainnet launch mean that all testnet content will be part of mainnet?
* [ ] Add appropriate messaging on viewers side 
* [ ] Add appropriate messaging to the studio onboarding journey

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1203179145269276) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@bedeho ❓ Does mainnet launch mean that all testnet content will be part of mainnet?

**Comment by bedeho** [comment]
> Does mainnet launch mean that all testnet content will be part of mainnet?

no, on mainnet there will be 0 content migration, let alone content that falls within narrower scope of Gleev vs. old Atlas.

**Comment by dmtrjsg** [comment]
Ignore this issue
