### ISSUE TITLE
Idea: Introduce a changelog

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3358]
# Dependency

https://github.com/Joystream/atlas/issues/3327

# Background

It would be a big benefit publish a changelog for releases, have a long running release file, and have a low-effort process to make it very easy to maintain such a log. It just took @dmtrjsg a very long time to compile an overview of all of the changes that are being introduced in `Carthage`, and it would have been very difficult to do this sort of retro investigation unless they are very close to the development process. The log can be generated [automatically or manually](https://www.freecodecamp.org/news/a-beginners-guide-to-git-what-is-a-changelog-and-how-to-generate-it/), but in the latter case its important that its done continuously.

**Comment by kdembler** [comment]
Will be done in #3327
