### ISSUE TITLE
Opening NFT history in NFT widget crashes app

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3362]
**Sender**: mail@eclipsingbinary.net
**Taken at**: https://play.joystream.org/video/26717
**Fields**:
- Expected Result: Clicking on view history on an NFT should reveal the history of transactions on that NFT
- Houston, we have a problem.: unable to view bid history on an NFT

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/40714ca1-b6f6-407f-bc4b-4d995c7d0d7b-annotated_3836ecf6-f5ab-4718-9e38-e0c49b0619b1.png?etag=e944c0205948b481deb4b66fa6dc5ce7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/40714ca1-b6f6-407f-bc4b-4d995c7d0d7b-annotated_3836ecf6-f5ab-4718-9e38-e0c49b0619b1.png?etag=e944c0205948b481deb4b66fa6dc5ce7)*

**Browser**: Chrome 106 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x937
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/18a1ce87-fe74-4df9-967c-7fd14d3bc6a2_screen_recording_f05ae354-f77c-4a7f-845b-d8fd1f411b66.webm?etag=2198ff03233110d8fe2e96f4288eb759-2)**
**[Open #25 in Usersnap](https://app.usersnap.com/l/feedback/680c95a8-94da-4840-bc0c-2ad906123457?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by drillprop** [comment]
Doesn't happen on `carthage` branch, I'm pretty sure that's already fixed. I think we can close this.
