### ISSUE TITLE
Carthage Atlas testing

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3365]
## Context
This ticket will encapsulate the set of scenarios required for testing Atlas before Carthage branch is deployed to prod

## Scope
Execute the set of the following test scenarios and raise bugs as separate issues linking to this originating testing issue in comments:

### Creating membership 
1. Captcha works
2. Avatar can be cropped and updated
3. Faucet error messaging explains the reason why creating second membership right after first one is prohibited
4. Joy added to membership account under Invitation Lock and its displayed correctly
5. Joy cannot be transferred 
6. Edit member assets

### Creating channel
1. Studio welcome screen is updated with new designs
2. Channel created and wallet assigned to it
3. Joystream addresses for wallet and membership are visible in the top nav component and have joystream format
4. Edit channel assets
5. Transfer to Channel account from non-member account
6. Withdraw from channel account to member account

### Upload video
1. Upload video
2. During video upload switch off network so upload interrupted. Re-upload again via edit button on error message.
3. Upload Subtitles in Both SRT and WebVtt formats, one with close captions CC
4. Download subtitles, check if correct format is downloaded
5. Edit video assets

##  NFT
1. Mint NFT
2. Try upd video assets
3. Sell on auction
4. Sell via buy now
5. Sell on whitelisted
6. Check which balance proceedings come to
7. Withdraw proceedings to personal acc
8. Transfer to external polkadot acc (generic substrate address, not joystream).

## Comments And reactions
1. Add / edit / delete comment
2. React / unreact

## Video Playback settings
1. Check autoplay
2. Check subtitles
3. Check playback speed

## Test Locks
1. Invitation lock displayed correctly and covers tx fees but cannot be transferred
2. ~Vesting lock displayed correctly and does not cover any fees and cannot be transferred~

**Comment by drillprop** [comment]
## Create membership ##
As a user:
-  I can create a membership with the Polkadot extension ✅ 
-  I can create a membership with the Talisman extension ✅ 
-  I need to verify the captcha during membership creation, and the captcha works as it should  ✅
-  I can choose only unique membership handle and the input validation works correctly ✅ 
- I can update the avatar, change it and remove it ✅ 
- I receive messages explaining the reason why creating second membership right after the first one is prohibited ✅ (I add a small improvement here: https://github.com/Joystream/atlas/pull/3370)
- I receive the correct invitation lock and it's displayed correctly ✅

**Comment by drillprop** [comment]
## Editing membership, transferring a membership balance, displaying membership balance ## 
As a user: 
- I can update the membership about field ✅ 
- I can update the membership handle ✅ 
- I can update the membership avatar ✅ 
- I can delete the membership avatar ✅ 
- I cannot transfer the locked balance ✅ 
- I see the correct transferrable balance ✅ 
- I see the correct invitation lock ✅ 
- I see the correct invitation lock after doing a transaction when I don't have a transferrable balance ❌ (Created PR to fix this https://github.com/Joystream/atlas/pull/3371)
- I see the correct balance after doing the transaction when I have a transferrable balance ✅ 
- I can transfer some of my transferrable balance to another account and the balance is displayed correctly ✅  
- I can transfer all of my transferrable balance to another account and the balance is displayed correctly ✅

**Comment by drillprop** [comment]
## Channel creation and editing ##
As a user:
- I see the correct welcome screen when I go to the studio. I can go back to the atlas and open the channel form ✅ 
- I want to create a channel ✅ 
- I want to create channel and validation works correctly ❌  Fix here https://github.com/Joystream/atlas/pull/3372
- I want to upload avatar and cover during channel creation ✅ 
- I can edit channel fields(except avatar/cover) ✅ 
- I can edit an avatar ✅ 
- I can edit a channel cover(generally works, but there are few cases that it doesn't) ❌  Created issue https://github.com/Joystream/atlas/issues/3373
 - I can transfer tokens to my channel rewardAccount and the balance is displayed correctly ✅ 
 - I can withdraw tokens from channel ❌  it is possible, but there is a small bug.  Issue https://github.com/Joystream/atlas/issues/3374
 -  `Joystream addresses for wallet and membership are visible in the top nav component and have joystream format` ❓ - @dmtrjsg I don't know what you mean here.

**Comment by dmtrjsg** [comment]
Hey @drillprop yes you are right, looks like we need to skop that one as the earliest module where the addresses are displayed is Payments. I've [raised this with the design team](https://joystreamworkspace.slack.com/archives/C039GLGPUQ7/p1666877197711829) and we would prob end up raising a follow up ticket for this at a later stage..

**Comment by drillprop** [comment]
## Creating videos and updating
As a user:
- I can upload a video ✅ 
- I can see uploading progress on MyVideos  ✅ 
- I can see uploading progress on My Uploads ✅ There is a small bug when it's not possible in certain circumstances(issue: https://github.com/Joystream/atlas/issues/3376), but in general, it's possible
- I can see videos that uploads failed ✅ 
- I can re-upload the video if its upload failed ❌  this should be fixed in https://github.com/Joystream/atlas/issues/3130
- I can edit videos ❌  I would say that most of the time it works but I found a bug that happened to me several times already: https://github.com/Joystream/atlas/issues/3375
- I can upload .srt subtitles ✅ 
- I can upload .vtt subtitles ✅ 
- I can download uploaded subtitles(only as .vtt) ✅ 
- I can update video assets - subtitles, thumbnail, with exception of video files (we never support that) ✅ except already mentioned bug with not being able to edit video, it's possible

**Comment by rafalpawlow** [comment]
## NFT
As a user:
1. I can Mint NFT ✅
2. I can put NFT on sale - auction ✅
3. I can put NFT on sale - buy now ✅
4. I can put NFT - mixed ✅
5. I can remove my NFT from the sale ✅
6. I can change my NFT buy now price ✅
7. I can change my bid ✅
8. I can withdraw my bid ✅
9. I can sell my NFT on auction ✅
10. I can sell my NFT via buy now ✅
11. I can sell my NFT to a whitelisted member ✅
13. I can withdraw proceedings to personal ACC ✅
14. I can transfer to external polkadot acc (generic substrate address, not joystream). ✅

Everything works fine however, I found one glitch
https://github.com/Joystream/atlas/pull/3380

**Comment by rafalpawlow** [comment]
## Comments And reactions
As a user:

1. I can add like a reaction to the video ✅
2. I can undo like reaction ✅
3. I can add an unlike the reaction to the video ✅
4. I can undo unlike reaction ✅
5. I should see a dialog about transaction processing while trying multiple reactions ✅
6. I can add a comment ✅
7. I can reply to a comment ✅
8. I can edit comment and see editing history ✅
9. I can delete the reply ✅
10. I can delete the comment ✅
11. I can hide replies ✅
12. I can add any possible reaction to a comment ✅
13. I can undo comment reaction ✅
14. I can copy comment url ✅

**Comment by rafalpawlow** [comment]
## Video playback settings
Aa a user: 

1. I should see a playing video after I get to the video page ✅
2. I can toggle autoplay ✅
3. When autoplay is on I should be redirected to the next video ✅
4. I can add multiple subtitles ✅
5. I can change playback speed ✅
6. I can toggle captions ✅
7. I can switch subtitles language ✅
8. I can toggle fullscreen ✅
9. I can toggle PiP ✅
10. I can toggle cinematic view ✅
11. I can use controls from the keyboard ✅
