### ISSUE TITLE
Create CRT Flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3385]
### Context

- https://github.com/Joystream/atlas/issues/3384

### Scope
- Welcome screen  [link to figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=80%3A37156)
- Create token page scaffolding
- First stage from the flow (name, access, revenue share, creator award)
- Second stage (token assurances, only presets)
- Token Summary Screen
- All tooltips on all stages

Out of scope ⛔ 
- Previews on the left hand side
- Custom assurance inputs
- Submit token extrinsic

### Design
[Link to Figma user story > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=79%3A37125)

**Comment by polikosi** [comment]
tested on: https://atlas-git-crt-joystream.vercel.app/studio/crt

I think there should be a description. The same problem with Secure, Risky and Custom token assurances
![image](https://github.com/Joystream/atlas/assets/80429191/eb199844-67e1-46c3-b78a-7829b4f67725)

There should be no chart here. 
![image](https://github.com/Joystream/atlas/assets/80429191/777b9f9a-6238-4e25-88fe-b715aa9c08ea)

**Comment by polikosi** [comment]
Token Summary Screen
Selected "Secure" on Second stage. I expected see here information about cliff, vesting period and first payout. The same problem when I selected "Safe". Displays the information about the cliff, the vesting period, and the first payout only when I select Custom.
![image](https://github.com/Joystream/atlas/assets/80429191/1b9c42dc-a7d9-4dc1-9188-d874190255a6)

According to the design "Transaction" should be separated by a line
![image](https://github.com/Joystream/atlas/assets/80429191/550b051d-3027-45ee-87b7-c923b84f8a71)

**Comment by polikosi** [comment]
![image](https://github.com/Joystream/atlas/assets/80429191/56efd1de-5521-463e-bb2a-29f68875b850)
