### ISSUE TITLE
Create CRT Flow Previews

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3386]
### Context

- https://github.com/Joystream/atlas/issues/3384

### Scope
- Interactive Previews in the Create Token Flow on step 1 and step 2 of the journey

Design: 

⚠️ here only tooltips are interactive, and inputs are shown in the preview straight away
[Link to Figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=81%3A39413) 
<img width="523" alt="Screenshot 2022-11-01 at 17 54 15" src="https://user-images.githubusercontent.com/93924525/199250748-b899982d-5ad6-4931-acf4-d47327e616b3.png">

⚠️ this chart is interactive, pls follow the link to Figma
[Link to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=313%3A76472)
<img width="274" alt="Screenshot 2022-11-01 at 17 52 26" src="https://user-images.githubusercontent.com/93924525/199249642-9f08b3f8-0eee-48fd-8ab9-968761f41e04.png">

**Comment by polikosi** [comment]
Total revenue was removed, right?
![image](https://github.com/Joystream/atlas/assets/80429191/c9365710-5e15-49c3-a15f-ef169fd3f01c)

According to the design, the vesting period should have a pad lock
![image](https://github.com/Joystream/atlas/assets/80429191/dd865449-ca67-48ea-a5ab-2429a3d5b031)


it would be nice to add a point when you hover the mouse over the chart.
![image](https://github.com/Joystream/atlas/assets/80429191/6a5f9589-1b28-41d4-8903-7e1febe55b14)



it would be nice to add a description to each of them
![image](https://github.com/Joystream/atlas/assets/80429191/b68ee23e-bc07-48a0-989c-ec2e793b5253)

**Comment by WRadoslaw** [comment]
> Total revenue was removed, right? ![image](https://private-user-images.githubusercontent.com/80429191/285245770-c9365710-5e15-49c3-a15f-ef169fd3f01c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODQ0ODYsIm5iZiI6MTcwMTA4NDE4NiwicGF0aCI6Ii84MDQyOTE5MS8yODUyNDU3NzAtYzkzNjU3MTAtNWUxNS00OWMzLWExNWYtZWYxNjlmZDNmMDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5N2FjNjE5NDYzZjY2NzAyZWM4MDFjOWNiYWZjMzQ4Zjg4MDhhYjVhYWJmNjc5YjliMjg1ZDUzNjk2ZTQ2MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FDszU4uq04mq1--moq-y5jGVfHyYkVB0-ExDxpsim_U)
> 
> According to the design, the vesting period should have a pad lock ![image](https://private-user-images.githubusercontent.com/80429191/285252117-dd865449-ca67-48ea-a5ab-2429a3d5b031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODQ0ODYsIm5iZiI6MTcwMTA4NDE4NiwicGF0aCI6Ii84MDQyOTE5MS8yODUyNTIxMTctZGQ4NjU0NDktY2E2Ny00OGVhLWE1YWItMjQyOWEzZDViMDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYWZlNzZjNWY4YmFkYzFkOTU1NjQyYWQxOGM4ZGQ1YTI0MzQyZjNlZWIwOTE2ZjJiZjZkM2U0NDAxZjk2ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tbs8L-zny83HMAWmzvnCwlBumEpdqFHXpuLDdUfww1o)
> 
> it would be nice to add a point when you hover the mouse over the chart. ![image](https://private-user-images.githubusercontent.com/80429191/285245003-6a5f9589-1b28-41d4-8903-7e1febe55b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODQ0ODYsIm5iZiI6MTcwMTA4NDE4NiwicGF0aCI6Ii84MDQyOTE5MS8yODUyNDUwMDMtNmE1Zjk1ODktMWIyOC00MWQ0LTg5MDMtN2UxZmViZTU1YjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMTFlZWNhN2ZkYzIyOGNlNWE1NjQxZThmZTkzZGVlMDBlOWQzOTAxNDg2Mzg1OGFhMjNjZTkyZjFkODE5Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gTtPs_3ulzt6nuXBtSK_xEeMD6l5F8Hcn7SWgu6TZAw)
> 
> it would be nice to add a description to each of them ![image](https://private-user-images.githubusercontent.com/80429191/285245995-b68ee23e-bc07-48a0-989c-ec2e793b5253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwODQ0ODYsIm5iZiI6MTcwMTA4NDE4NiwicGF0aCI6Ii84MDQyOTE5MS8yODUyNDU5OTUtYjY4ZWUyM2UtYmMwNy00OGEwLTk4OWMtZWMyZTc5M2I1MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDExMjMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjM2VhOTY1M2UwM2MwZjJmYWY3M2RkZDY3NjAyYzk4YjhlZWQwZWRmYmE3Nzg1Y2EzNmYzNjgwODdlMjQ2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KWMjMBaz0N3uNhIujyMudeePAVlt6lapxuO7xg_GJkM)

Nivo supports crosshair type pointer 
![image](https://github.com/Joystream/atlas/assets/92513933/a34f4004-bbbd-45f2-ac01-96d00c3de38a)

**Comment by polikosi** [comment]
@WRadoslaw 
I realize that nivo supports crosshair type pointer, but I think it would be nice to add a dot. 
It would make it easier to see and understand where you moved the mouse on the graph.

**Comment by WRadoslaw** [comment]
> @WRadoslaw I realize that nivo supports crosshair type pointer, but I think it would be nice to add a dot. It would make it easier to see and understand where you moved the mouse on the graph.

The reason for pointing out the fact that Nivo supports the crosshair is that it doesn't support dot one out of the box, which makes implementation more time-consuming, feel free to create this as an enhancement.
