### ISSUE TITLE
Create CRT Flow Custom Params

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3387]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope
- [ ] Custom assurance options summon additional options

[Link to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=178%3A50883)

<img width="738" alt="Screenshot 2022-11-01 at 18 09 36" src="https://user-images.githubusercontent.com/93924525/199253411-cc7a9691-f6e9-4a99-b651-03e3908941df.png">

**Comment by polikosi** [comment]
tested on: https://atlas-git-crt-joystream.vercel.app/studio/crt

❌Second stage (token assurances -> Custom -> First payout)
It should be 100% maximum, no more
![image](https://github.com/Joystream/atlas/assets/80429191/067a196f-6f62-4470-b92d-d7792406837d)
❌cannot be a negative number
![image](https://github.com/Joystream/atlas/assets/80429191/dc6d4e37-2b92-4dcc-b47a-dbbfbc1e6cb1)

**Comment by polikosi** [comment]
✅Custom assurance options summon additional options
⚠️But cannot be more or less than 100%
![image](https://github.com/Joystream/atlas/assets/80429191/b59cc35b-d599-416d-896d-dad47f83f7e2)

**Comment by polikosi** [comment]
✅Custom assurance options summon additional options

Out of scope
⚠️But cannot be more or less than 100%

**Comment by polikosi** [comment]
Remove the addition and subtraction signs. 
Make only numbers and commas/dots available
![image](https://github.com/Joystream/atlas/assets/80429191/4bbaf664-0f5e-4529-b841-c37d7d045d1d)

**Comment by WRadoslaw** [comment]
> Remove the addition and subtraction signs. Make only numbers and commas/dots available ![image](https://private-user-images.githubusercontent.com/80429191/289921408-4bbaf664-0f5e-4529-b841-c37d7d045d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTk4MjgsIm5iZiI6MTcwMjM5OTUyOCwicGF0aCI6Ii84MDQyOTE5MS8yODk5MjE0MDgtNGJiYWY2NjQtMGY1ZS00NTI5LWI4NDEtYzM3ZDdkMDQ1ZDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjODI1ZDNhNjg0YTliZjQyNWJiNzZjZGExMjYzMWI2MmM3OGE1YzAxM2UwZDJlMzY3NjdlNTY0OTg5YzI3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qBek5mP-Pn-14CQMyIph92vzXx5QCKI1yHmKgMJVrr4)

We don't have to go that far, validation will not let such input pass to the summary and the chart doesn't react to it
