### ISSUE TITLE
CRT Dashboard Structure

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3388]
### Context
- https://github.com/Joystream/atlas/issues/3384

## Scope
- [ ] Scaffolding of the CRT dashboard - token page
- [ ] Create other Tabs
- [ ] Empty states for all widgets on the first tab

Out of scope:
- Balances widgets
- progress widget

### Design

[Link to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=59%3A39700)

Preview: 

<img width="534" alt="Screenshot 2022-11-01 at 18 16 44" src="https://user-images.githubusercontent.com/93924525/199254780-1f7f6887-2d9a-4778-8c88-8af59b810ce2.png">

**Comment by polikosi** [comment]
According to the design, it should contain the name of the token I currently have
![image](https://github.com/Joystream/atlas/assets/80429191/6baec819-7f38-42e0-87cb-be7a9846cb01)

**Comment by polikosi** [comment]
I expected to see 80% for channel and 20% for holders here
![image](https://github.com/Joystream/atlas/assets/80429191/90dc7a7f-70cb-42b1-b308-fb6b935fce7a)

it would be nice if the percentage of tokens was centered 
![image](https://github.com/Joystream/atlas/assets/80429191/6b04d4f9-9c06-4428-abcd-0ebb203ee1c6)

there should be a different text according to the design
![image](https://github.com/Joystream/atlas/assets/80429191/fec7a072-6053-451c-9df1-b483d803fa21)

add icons to the top holders, as it is already done for your own. 
Add text "No holders yet" below the "top holders" icons.
![image](https://github.com/Joystream/atlas/assets/80429191/ca4c9d66-b9ff-4c31-bb92-0402606fdcdb)

**Comment by polikosi** [comment]
@WRadoslaw Did you decide to skip or just forget about it?
1. It would be nice if the percentage of tokens was centered
2. Add text "No holders yet" below the "top holders" icons.
![image](https://github.com/Joystream/atlas/assets/80429191/0bf3125e-3edf-4e48-b7d8-585c68995cd4)

**Comment by WRadoslaw** [comment]
> @WRadoslaw Did you decide to skip or just forget about it?
> 
> 1. It would be nice if the percentage of tokens was centered
> 2. Add text "No holders yet" below the "top holders" icons.
>    ![image](https://private-user-images.githubusercontent.com/80429191/289933110-0bf3125e-3edf-4e48-b7d8-585c68995cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTg5NDgsIm5iZiI6MTcwMjM5ODY0OCwicGF0aCI6Ii84MDQyOTE5MS8yODk5MzMxMTAtMGJmMzEyNWUtM2VkZi00ZTQ4LWI3ZDgtNTg1YzY4OTk1Y2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2MzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NWIyNTU2MDA1NGNmMTkwODRiZTQ1NTZhNmI5YzZhYWI0YjZlOWFkMzcxZGQxNGE0NWUwZDEwNWExZGY0NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yygwO-T_wYX7IUnH-yjOz1y9cgXgQF2vpf2594oyyIY)

1. Library for charts doesn't allow (or at least I cannot find it) this type of customization
2. Forgot
