### ISSUE TITLE
CRT Dash Progress Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3389]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope
- [ ] Create progress bar component
- [ ] Create component for "step card" (name TBD)
- [ ] Create the progress widget
- [ ] Make it collapsible

Important: the default state of the widget where step 1 is active is only shown for a brief period of time after token creation confirmation modal is closed, before being closed.

Designs: 

[LInk to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=170%3A47569)

<img width="895" alt="Screenshot 2022-11-01 at 18 20 12" src="https://user-images.githubusercontent.com/93924525/199255634-dc486f87-687a-47ee-9e4f-e3d009a7dee7.png">

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk pls add more comments / link to figma where animation is covered in more detail.

**Comment by polikosi** [comment]
⚠️After confirming the creation of the token, I don't see the default state of the widget where step 1 is active. I see the widget state as in the screenshot:
![image](https://github.com/Joystream/atlas/assets/80429191/928452d3-0763-47ad-9d21-adff1044f902)

#5481

**Comment by dmtrjsg** [comment]
@WRadoslaw I believe the reference above is about this animation:
- [LINK TO FIGMA>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=529%3A152054&mode=design&t=7FEOtCaqEagPCeVf-1)

@KubaMikolajczyk can you pls share the link to the prototype where this animation can be accessed? I think we have had an accidental blank link in Figma..

Here's the issue to add it as a comment: 
- https://github.com/Joystream/atlas/issues/5513
