### ISSUE TITLE
CRT Dash "Core" Token Widgets

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3390]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope
- [ ] Transferable balance - depends on the vesting schedule and cliff - fetched from RPC
- [ ] Locked Balance - depends on the vesting schedule and cliff - fetched from RPC
- [ ] Total Revenue 
- [ ] Patronage - static % from the create token flow

Out of scope: 

- [x] #3397

### Design

[Link to Figma > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=59%3A39700)

<img width="934" alt="Screenshot 2022-11-01 at 18 38 04" src="https://user-images.githubusercontent.com/93924525/199259973-8601011e-c82d-46d4-b6a5-b53d5d59770f.png">

**Comment by polikosi** [comment]
1. I haven't started the market yet, but I see the price of tokens and total revenue.
2. "Total rev." should be written in full as "Total revenue"
3. "Transferable" box is not updated in real time

![image](https://github.com/Joystream/atlas/assets/80429191/282acb80-d7b1-4c6b-998c-828483e8b9df)

@dmtrjsg  In my opinion, the "locked" field should show the cliff and the balance of the vesting.
For example, I choose 0 cliff and 1 month of vesting, the first payout is 50%, the total value is 100k. Thus, I would expect to see 50k in the "Transferable" box, another 50k in the "Locked" box in the vesting , and both fields should be updated in real time.

**Comment by dmtrjsg** [comment]
@ignazio-bovo how is Locked balance exposed to front end now?

**Comment by polikosi** [comment]
> 1. I haven't started the market yet, but I see the price of tokens and total revenue.
> 2. "Total rev." should be written in full as "Total revenue"
> 3. "Transferable" box is not updated in real time
> 
> ![image](https://private-user-images.githubusercontent.com/80429191/285265846-282acb80-d7b1-4c6b-998c-828483e8b9df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTk2MjUsIm5iZiI6MTcwMjM5OTMyNSwicGF0aCI6Ii84MDQyOTE5MS8yODUyNjU4NDYtMjgyYWNiODAtZDdiMS00YzZiLTk5OGMtODI4NDgzZThiOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MThiYTVhMGJiMmE0YjE2NDA1MjJjZjVlMzY0OTQzODc2NWJjMjE0M2I4ODg3ZDllMjVkMTdhMDUyY2FkOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eArdlX1a5ldLRO4BaQRMV3d7UQP43AZW4hPpwskU67s)
> 
> @dmtrjsg In my opinion, the "locked" field should show the cliff and the balance of the vesting. For example, I choose 0 cliff and 1 month of vesting, the first payout is 50%, the total value is 100k. Thus, I would expect to see 50k in the "Transferable" box, another 50k in the "Locked" box in the vesting , and both fields should be updated in real time.


The same problem as before. 

![image](https://github.com/Joystream/atlas/assets/80429191/dd5b32db-6fcf-4a6d-8baa-7045aff104c9)

**Comment by WRadoslaw** [comment]
> > 1. I haven't started the market yet, but I see the price of tokens and total revenue.
> > 2. "Total rev." should be written in full as "Total revenue"
> > 3. "Transferable" box is not updated in real time
> > 
> > ![image](https://private-user-images.githubusercontent.com/80429191/285265846-282acb80-d7b1-4c6b-998c-828483e8b9df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTk2MjUsIm5iZiI6MTcwMjM5OTMyNSwicGF0aCI6Ii84MDQyOTE5MS8yODUyNjU4NDYtMjgyYWNiODAtZDdiMS00YzZiLTk5OGMtODI4NDgzZThiOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MThiYTVhMGJiMmE0YjE2NDA1MjJjZjVlMzY0OTQzODc2NWJjMjE0M2I4ODg3ZDllMjVkMTdhMDUyY2FkOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eArdlX1a5ldLRO4BaQRMV3d7UQP43AZW4hPpwskU67s)
> > @dmtrjsg In my opinion, the "locked" field should show the cliff and the balance of the vesting. For example, I choose 0 cliff and 1 month of vesting, the first payout is 50%, the total value is 100k. Thus, I would expect to see 50k in the "Transferable" box, another 50k in the "Locked" box in the vesting , and both fields should be updated in real time.
> 
> The same problem as before.
> 
> ![image](https://private-user-images.githubusercontent.com/80429191/289938198-dd5b32db-6fcf-4a6d-8baa-7045aff104c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDAyMDAsIm5iZiI6MTcwMjM5OTkwMCwicGF0aCI6Ii84MDQyOTE5MS8yODk5MzgxOTgtZGQ1YjMyZGItNmZjZi00YTZkLThiYWEtNzA0NWFmZjEwNGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YzFmNDgwZDQ1Yzc2NTRjMDQwZWJkNGFhZmQzMjI2MTlmYmMzYTdkYWFkODU5Nzk4NTg1MDIzNzE1MzYwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wjfib3Wz8Ed0txNrAMg_3vamrxGwOVjMAyq0O-qKUYQ)

1. Fixed in v5
2. Done in v4
3. It won't be, it was decided that the token balance will live on the Orion as a resolver, which doesn't allow keeping it up to date, without some polling, which isn't efficient.
4. Locked value is solely Orion instance, Atlas shouldn't try to process all data about the token for a single user just to display a locked balance.
