### ISSUE TITLE
CRT Token Page Structure

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3391]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope
- [ ] Edit page opened from top button or progress widget
- [ ] Page layout
- [ ] Preview mode

### Out of scope
- Video upload
- Benefits
- About editing
- Empty states of widgets on the right hand side of the page

#### Design

[Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=181%3A58317)

Preview: 

**Page view:**
<img width="438" alt="Screenshot 2022-11-01 at 18 58 31" src="https://user-images.githubusercontent.com/93924525/199264962-ca1f6e84-101e-4dd8-956b-72063d940122.png">

**Preview**
<img width="720" alt="Screenshot 2022-11-01 at 18 58 44" src="https://user-images.githubusercontent.com/93924525/199264973-0cd2e3dc-e2ed-42c5-871f-28c9bd246614.png">

**Comment by polikosi** [comment]
✅ Edit page opened from top button or progress widget
Once I edited a token, I can now open the edit page using the top button. Up to this point, I could edit the page from the progress bar and the button at the top.
![image](https://github.com/Joystream/atlas/assets/80429191/6c146cff-172d-4617-87b1-2d4d1743a5c8)

 ✅Page layout
 
 ✅Preview mode
