### ISSUE TITLE
CRT Token Page Select video trailer

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3392]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope

- [ ] Select video with search filtering from creator channel's videos
- [ ] Playback of the video in preview mode

#### Design

[Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=202%3A75644)

Preview

<img width="402" alt="Screenshot 2022-11-01 at 19 12 31" src="https://user-images.githubusercontent.com/93924525/199267819-a9b726ae-7374-4393-92aa-84fd169e5869.png">
<img width="525" alt="Screenshot 2022-11-01 at 19 12 41" src="https://user-images.githubusercontent.com/93924525/199267822-e76be7be-99bf-47a4-b11c-093867c7139d.png">

**Comment by polikosi** [comment]
I expected that I could write a wrong video title and then delete it and write the correct title or choose a video from the list 

https://github.com/Joystream/atlas/assets/80429191/72d0c2b8-1894-4dbe-b81a-cf3a926a38e8

✅Playback of the video in preview mode
