### ISSUE TITLE
CRT Token Page Benefits

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3393]
### Context
- https://github.com/Joystream/atlas/issues/3384

### Scope
- Title
- Description
- Changing the order of points with arrow on the right
- Removing a benefit point
- Display in the preview mode

### Out of scope
- Emoji and selection

@KubaMikolajczyk is there a cap on the number of total benefits?

### Design
[LInk to Figma > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=206%3A60621)

Preview: 
<img width="825" alt="Screenshot 2022-11-01 at 19 28 03" src="https://user-images.githubusercontent.com/93924525/199272256-f9895eb1-929a-4182-837e-941221b90d98.png">

**Comment by polikosi** [comment]
I left the "Title" and "Description" fields empty and expected to see my profile in the preview mode
![image](https://github.com/Joystream/atlas/assets/80429191/c7d31499-7511-4c09-a420-1445e153db1c)



⚠️Maybe it is out of scope
add tooltip to arrow
![image](https://github.com/Joystream/atlas/assets/80429191/588f9d42-511a-4457-8332-71ceda761cd0)
