### ISSUE TITLE
Submit token extrinsic

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3394]
### Context

- https://github.com/Joystream/atlas/issues/3384
- https://github.com/Joystream/atlas/issues/3385

### Scope
- [ ] Submit data collected in the create CRT form
- [ ] Redirect to Dashboard and display confirmation popup

### Designs
[LInk to Figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=787%3A111825&mode=design&t=oSJTQZl7gy5poqq6-1)

⚠️ 
Animation [link>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=528%3A105395&mode=design&t=psbkm1EKmvN9yA62-1)

<img width="814" alt="Screenshot 2023-09-11 at 18 16 25" src="https://github.com/Joystream/atlas/assets/93924525/f18d4c46-bf5b-449b-afa6-0d81e4a2d05d">

**Comment by polikosi** [comment]
✅display confirmation popup
❌Redirect to Dashboard. On the back ground I see token summary
![image](https://github.com/Joystream/atlas/assets/80429191/d7fa942b-f747-41bf-8f77-02354fbe4c4b)

**Comment by polikosi** [comment]
The same problem as before

✅display confirmation popup
❌Redirect to Dashboard. On the back ground I see token summary
![image](https://github.com/Joystream/atlas/assets/80429191/f0704811-7608-44c3-92d3-7df9e86d049c)
