### ISSUE TITLE
Token placeholder screen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3396]
update the visuals similar to how the Welcome screen looks like

**Comment by polikosi** [comment]
It looks good, if I get it correctly.
![image](https://github.com/Joystream/atlas/assets/80429191/f71390cf-2532-4145-a94a-2154aa7294b7)

![image](https://github.com/Joystream/atlas/assets/80429191/5fb2387b-f5cd-49b5-a70b-359602a748b8)

**Comment by polikosi** [comment]
according to the design, there should be another photo
![image](https://github.com/Joystream/atlas/assets/80429191/123a1020-8893-4e32-868e-064348770b8f)
