### ISSUE TITLE
Component: split ratio slider

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3401]
### Context
- https://github.com/Joystream/atlas/issues/3385

#### Design:
[LInk to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=5%3A4315)

Preview:
<img width="418" alt="Screenshot 2022-11-02 at 18 56 22" src="https://user-images.githubusercontent.com/93924525/199523596-dc6a1167-5261-4b44-bffd-14e572c8e485.png">

**Comment by polikosi** [comment]
Works good.
Revenue share with holders - every 10% to 100%
Annual creator reward - every 2% to 30%

![image](https://github.com/Joystream/atlas/assets/80429191/78d1cc2f-28f0-463f-ba8c-0ea7620fd363)

**Comment by polikosi** [comment]
> Works good. Revenue share with holders - every 10% to 100% Annual creator reward - every 2% to 30%
> 
> ![image](https://user-images.githubusercontent.com/80429191/284356728-78d1cc2f-28f0-463f-ba8c-0ea7620fd363.png)

everything is the same as it was then
