### ISSUE TITLE
Update Copy on the maintenance screen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3418]
### Context

Current copy for the maintenance screen specifically mentions [upgrade to Mainnet](https://www.figma.com/file/xBXWBZMqM0JAydQZ7ZaZ6D/Maintenance-page?node-id=101%3A17142), and we need smth more generic to cover all cases, including other network releases and "Deadman switch" mode.

### Scope
- [ ] Update copy on the Atlas repo to :

"[App_name] is currently unavailable due to the network upgrade, new infrastructure release rollout or operational update which required a temporary downtime.

We should be back shortly. In the meantime, feel free to connect with us on Discord."

- [ ] QA test that Gleev copy updated correctly with Logo/ App name matching the brand

**Comment by kdembler** [comment]
Closed in #3419
