### ISSUE TITLE
Add chain metadata for Signers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3434]
![Screenshot 2022-11-14 at 14.33.41.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/00549f08-80f0-4e14-8783-9381f5497223)

![Screenshot 2022-11-14 at 14.33.46.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4f42d718-e610-4dd1-9754-c16fa7644d1d)![Screenshot 2022-11-14 at 14.33.41.png]

**Comment by dmtrjsg** [comment]
@WRadoslaw do we need to design the screen that approves passing the meta-data to the signer or the screen where this is previewed?

**Comment by WRadoslaw** [comment]
If I remember correctly it will ask before the transaction, after `Sign and send` click

**Comment by WRadoslaw** [comment]
Talisman Wallet is currently having issues with supporting metadata updates. It prompts an update but does not show details when signing the transaction.

https://discord.com/channels/858891448271634473/1077516706911633448/1077523320309809182

**Comment by dmtrjsg** [comment]
Decided to release without doing any extra messaging for Talisman lack of ability to handle meta data correctly.
