### ISSUE TITLE
Create video tile variation for "uploading in progress" state when done by Auto-sync

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3448]
## Context

Autosync service will result in states of the app where multiple videos are fetched from newly joined creator YT channels, but upload is still in progress. Since the state will not be defined for the App this will result in "Video upload failed" variation of tile and toaster notification, which is not a great first experience for the creators signed up. 

We want to handle this case.

## Scope
- [x] Create video tile variation for the video upload in progress. Add a label/ badge that it is done via Auto-sync service from YPP programme
- [x] Add toaster notification variation "Video upload in progress"

**Comment by KubaMikolajczyk** [comment]
The work is done & ready to be reviewed - changed label wording a bit ✅ (work was done in My Videos file as this issue connects with my videos the most)
📄 Changelog for user flows in My Videos: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=784%3A26965&t=z774uHbtlRtvaEcc-4
📄 Changelog of a new publisher tile variant: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=6141%3A151592&t=YvEGc80a76nuU8SJ-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk nice one, few comments: 

1.  I think we need "auto-sync" label for the tiles.. so its clear where the upload are coming from. And we will keep "Syncing from youtube.." in the bottom of the tile as status.
2. Also I dont think we will notify the users with a separate event when the upload is finished, so we need to change this copy:
"Your videos are currently syncing and this might take a while. We will notify you when this process is finished." to "Your Youtube videos are being uploaded with the auto-sync service. This process will continue even after you close the browser window."

**Comment by KubaMikolajczyk** [comment]
Changes implemented ✅
https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=1801%3A45584&t=7JyMOFmqgfQ8VqJj-4

**Comment by dmtrjsg** [comment]
@drillprop totally forgot about this one, so adding this to the sprint, could you please allocate some story points to it?
