### ISSUE TITLE
YPP Opt Out feature

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3450]
## Context

- https://github.com/Joystream/youtube-synch/issues/45

## Scope
- [ ] Opt out journey to stop Auto-sync

Out of scope: 
- [ ] Opt out from YPP programme entirely

Thinking stopping participation would be enough.

**Comment by kdembler** [comment]
Flow from user perspective:
1. Click "Opt out"
2. Get a popup from signer extension, where you sign a "message" (slightly different than a transaction)
3. We send signed message to the backend (not a regular blockchain transaction flow, just a loader)

**Comment by toiletgranny** [comment]
@dmtrjsg Design-wise, I addressed this issue while working on #3449. It's ready to be implemented. Designs, docs, and changelog [can be found here](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3338%3A84773&t=f1pw4rw8EhIsAFB3-4).

**Comment by WRadoslaw** [comment]
UI implemented by #3571 
Logic is awaiting

**Comment by dmtrjsg** [comment]
resolved in #3602
