### ISSUE TITLE
A newly created auction doesn't show up in `New NFTs on sale`

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3462]
1. Create a video(but don't mint it yet)
2. After video creation, mint an nft
3. Put on sale(in this case I put for fixed price, could be important in this case, didn't test other scenarios)
4. Go to the atlas homepage
5. Check the `New NFTs on sale` tab
6. Nothing new is added
7. (Everything seems fine when you go to `Browse nfts`, but then when you go back to the homepage, you still won't see your auction) 

When you refresh the site everything works just fine. Probably some apollo cache problem

**Comment by dmtrjsg** [comment]
in the light of new homepage nft marketplace and new orion this is no longer actual
