### ISSUE TITLE
Handle claim reward errors

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3495]
## Context
#3476 followup

It's possible the claimable reward could be lower or higher than the allowed cashout(defined by `this.api.query.content.maxCashoutAllowed()` and `this.api.query.content.minCashoutAllowed()` - check the `claimRewardTx` method in `extrinsics.ts`).  We should display some snack bar or somehow notify the user what's wrong and why he can't claim his reward.  

## Scope
- [ ] Update notification toaster messages when Claimable amount exceeds/ is below min/ max runtime constraints tresholds set up on the Payout Proposal.

**Comment by dmtrjsg** [comment]
Copy for min amount threshold violated:

"Minimum claimable amount must be more than XX Joy. Accumulate more rewards before claiming again."

Copy for max amount threshold violated:
"Maximum limit on claimable amount of XX Joy exceeded. Please contact creator support in Discord."
