### ISSUE TITLE
Creator tokens - CRT Creator: Holders, Transactions, Settings, Notifications

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3501]
Issue to encapsulate design work for CRT Creator: Holders, Transactions & Settings.

**Comment by KubaMikolajczyk** [comment]
Hey the hi-fi work is done and it's ready to be reviewed 👌 Somewhere in the middle, I talk about a very important issue connected with notifications 💯 
🎥 Loom update: https://www.loom.com/share/ced5bcbe8a704e0d8671204f868ec158
📄 Figma changelog: https://www.figma.com/file/OuywwClsegx2eotkii4ea4/CRT-Creator?node-id=925%3A139042&t=WlZNgz3rjnjGznQu-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk 

Excellent work as always 🙇 , pleasure to review and not much to add really 😃 

Few very small comments:
1. Settings - are we sure we want to align these centrally and not on the left hand side, looked a bit strange for me but I don't insist
2. Chart will be limited by [Nivo.rocks](https://nivo.rocks/pie/canvas/) library so not sure if that exact behavior is possible but looks nice 👍 


Notifications: 
@KubaMikolajczyk pls feel free to address them after CRT designs are done and being tested ⭐ Absolutely agreed and you know how I always wanted to have them a bit more structured 😇

**Comment by bedeho** [comment]
# Transactions

I think there has been a conceptual mistake here, so there is subsantial space devoted to showing "transaction", either in the form of transaction history or recent transactions, and possibly other variations I have not seen. What this explicitly means in the design, as I understand it, is: people buying or selling $joy from a "creator sale" or "amm sale", as they are called. I tried to track down where this emphasis came from, and I coudl not find it in the original  [https://github.com/Joystream/atlas/issues/2400](design brief). The closest ones were
- I would like to see the history of all $CRT transfers: which I don't think we even have?
- history state events: splits, sales, AMMs, return to idle: which I don't think we even have?

Transactions, as conceived in the current design,
a) conflict with normal usage of the term transaction in blockchain parlance, so people will be expecting something else.
b) is an arbitrary subset of actions to be grouped and distinguished into its own tab
c) already has a history display on the "Sale" tab, but as I commented in the last review I don't think it is entirely workable either.

So in closing: perhaps it may have some utility to show a history interactions with the AMM or public sale, but having such a history live on the corresponding pages (as you do on the revenue share tab) should be more than sufficient. This transactions tab does not really make sense, and I am skeptical about also putting any sort of variation of this on the dashboard.

# Settings

- Be aware that creator rewards cannot be increased, only reduced.

# Holders

I think it works much better to designate the issuer  the way you have done here, using the small badge, compared to the way you have on the public token page, where you have made a one row table with a column called "Creator", as if there could be more than one. Is there a reason you can't just go with this simpler more uniform approach both places?

# Notifications

I think you make a reasonable case for doing something about this, but I think ultimately notifications will not work well before we have server-side notifications that power email messages, I'm not sure how much its worth investing in this before that part works. But I don't know how much design time it requires to go back and tackle this now as you are proposing, perhaps its really fast, in which case, it would be reasonable to deal with it now, at least if we don't expect the design in the product to change as a result of adding the server side integration. Do we?

**Comment by KubaMikolajczyk** [comment]
# Transactions

Thank you for clarification of this. I will remove the amm & creator sale records from this tab. 
Q: Should I then proceed and create a version of this tab called transfers that will focus on transfers between users? 

> I would like to see the history of all $CRT transfers: which I don't think we even have?

Yes we currently don't have transfers as it was wrongly understood by me.

> history state events: splits, sales, AMMs, return to idle: which I don't think we even have?

This history of states was supposed to be addressed in history of sales and history of revenue splits - the only part of this which is not addressed is the part of going back to idle. Which was crossed out during the exploration phase as not as important.
Q: Would you rather have a separate page with history of all states than individual history for the states on their respective pages?

# Settings

I will adjust the user scenarios to match that

# Holders

I will change it on the viewer side to match your feedback.

# Notifications

To answer this question I would have to know more about the server side integration of the notifications as Im not aware what kind of features will be available at that time for us to use in the designs. If more opportunities will be available for us when that goes live then we might consider doing this design work after it here. But the fix and refresh needs to be done at some point that's for sure :)

**Comment by bedeho** [comment]
> Q: Should I then proceed and create a version of this tab called transfers that will focus on transfers between users?

No, I don't think its worth it, scope is already gigantic. I think realistically what would be generally useful would just be a history or events tab which shows all events that exist, including transfers, with search, filtering and pagination, but this has to be demanded by users before we venture into investing in. This could cover splits, launcing sales, purchases, all of it.

> Q: Would you rather have a separate page with history of all states than individual history for the states on their respective pages?

I am not totally sure I understand this question, but hopefully what I said above is an answer?

> Notifications

Ok, why don't you go for designing it now, then we can see later when we speak to @Lezek123 about the timeline for user notifications & email integration based on Orionv2.

**Comment by KubaMikolajczyk** [comment]
OK
To sum up
1. I will remove the transactions tab entirely and do not create any major states history tab for now
2. I will make an issue for the work on Notifications which will be scheduled to be worked on soon

**Comment by KubaMikolajczyk** [comment]
🟢 Update after feedback for CRT Creator & Viewer | Removing sections, Sale & Market, Revenue share
🎥 Loom video: https://www.loom.com/share/3a441d4c7bba4f0b99d8531da984ac8b
📄 Channel page changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=9LSU5rQo1PxdSNma-4
📄 My token changelog:  https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=925%3A139042&t=Jen95QDQKLIYpAWi-4
