### ISSUE TITLE
Select Category of videos uploaded via auto-sync as part of OB flow.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3509]
## Context
Right now videos auto-synced are not showing as filtered out since category is not assigned. 

<img width="606" alt="Screenshot 2022-12-08 at 16 06 00" src="https://user-images.githubusercontent.com/93924525/206443596-2880ed13-4c94-45b2-8289-85cae5989eca.png">

## Scope
For YPP onboarding flow the Category selection/ confirmation screen after auth needs to include the selection of category manually.

**Comment by KubaMikolajczyk** [comment]
✅ The category for videos select was added to the flow & dialog overlay 
Link : https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1818%3A91087&t=5GrtAHIrXUGHd8W0-4

**Comment by drillprop** [comment]
Looks good to me!
Blocked by https://github.com/Joystream/youtube-synch/issues/77
