### ISSUE TITLE
Add support for registering applications via a metaprotocol calls

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3517]
Part of https://github.com/Joystream/joystream/issues/4307

Handle `Member & Content lead remarks` section from above issue. That means:

1. Add `CreateApp`, `UpdateApp` and `DeleteApp` messages to protobuf definitions
2. Handle member remarks with App messages in the Query Node. QN should maintain a list of all the apps
	a. Make sure that updates and deletion can be done only by the member that created the app in the first place

**Comment by dmtrjsg** [comment]
Bear in mind, applications remarks is removed
- https://github.com/Joystream/joystream/issues/4538
