### ISSUE TITLE
Wrap channel and video creation in `AppAction` messages

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3519]
Part of https://github.com/Joystream/joystream/issues/4307

1. Let the app operator provide optional `appId` via `atlas.config.yml`
2. If `appId` is provided, whenever user wants to create a new channel or video, we wrap that extrinsic in `AppAction`, get signature from Orion and send the `AppAction` as extrinsic metadata.

**Comment by dmtrjsg** [comment]
<img width="819" alt="Screenshot 2023-01-09 at 18 08 06" src="https://user-images.githubusercontent.com/93924525/211389144-6d72428b-44b2-408f-97e1-d5f90ffabd7a.png">
