### ISSUE TITLE
Display tiles that are syncing with youtube - integration

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3526]
Once this is done https://github.com/Joystream/youtube-synch/issues/88 

We should handle

- [ ] displaying snack bar that informs about syncing videos
- [ ] displaying video tiles with auto sync badge.  (UI part should be done https://github.com/Joystream/atlas/pull/3520) 

User story https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos-page?node-id=1801%3A45584&t=1f44cOYfrFj95EOq-4

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203938368319556) by [Unito](https://www.unito.io)

**Comment by drillprop** [comment]
The backend fix is deployed on our test environment. Should be doable

**Comment by drillprop** [comment]
Video is syncing if all these requirements are met: 
1. video is available in QN
2. `video.media.isAccepted` or `video.thumbnailPhoto.isAccepted` is set to false
4.  video state in ypp backend(stage/channels/{channelId}/videos) is set to `UploadStarted`. Please check how thumbnails will behave when the video state is set to `VideoCreated` or `CreatingVideo`, because I'm not sure when the video is actually added in QN.

**Comment by dmtrjsg** [comment]
Seems like this pr did not make it to the YPP v1. 
<img width="1416" alt="Screenshot 2023-02-09 at 18 48 45" src="https://user-images.githubusercontent.com/93924525/217846664-f403bc73-6d07-4b7e-a7d4-baf6f7df859d.png">

**Comment by dmtrjsg** [comment]
Superceded by: 
- https://github.com/Joystream/atlas/issues/3762
