### ISSUE TITLE
YPP cosmetic fixes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3527]
## Context

@toiletgranny has been reviewing the designs and found a few cosmetic small and medium bugs.  This ticket encapsulates the fixes described in the spreadsheet: 
- https://docs.google.com/spreadsheets/d/1B-AgxGIRTfFGD0-XoVK_vUFp2d6n9TpL1VUEbEgDj6M/edit#gid=0

Rows: 2,3,4,5,7, 8

## Scope
 Fix cosmetic bugs covered in the spreadsheet:
 
1️⃣ 
As is:
YPP page <title> says "Youtube Partner Program"

To-be: 
The YouTube name should always be displayed with a capital "You" and capital "Tube".

2️⃣ 
As is:
In the Requirements step of the Authorize channel dalog, the list of requirements fills the width of the parent container.

To-be:
There should be 64px of right padding applied on the list of requirements to make the text easier to read.

3️⃣ 
As is:
In the Requirements step of the Authorize channel dalog, in the "Your YouTube channel has at least 1 subscribers" requirement, the word "subscribers" is plural and hard-coded 

To-be:
The word "subscribers" should be in a singular form if the required number of subscribers is set to 1.

4️⃣ 
As-is:
In the "Connect with YouTube?" dialog
1. The YouTube name is displayed as "youtube",
2. The "Learn more" button doesn't work,
3. The "Close" button is labeled as "Cancel" and redirects the user to 

To-be:
1. The YouTube name should always be displayed with a capital "You" and capital "Tube". Basically, the copy shoudl be copied from Figma.
2. The "Learn more" button should open up the YPP page on Publisher,
3. The "Cancel" button should be labelled as "Close", as per Figma designs.

5️⃣ 

As-is:
In the Details step of the Authorize channel dalog:
1. The form description says "We need your email address to send you payment information. No spam or marketing materials.",
2. The form contains error messages that do not reflect the copy provided in Figma,
3. The Select component is not in its Error styling variant when not filled out (it doesn't have a red underline).

To-be:
1. The form description should match the copy provided in Figma, so it should begin with "Provide additional information...",
2. All copy should match the one provided in Figma,
3. The Select component should be in its Error styling variant.

6️⃣ 
As-is: 
referrer field has channel input and placeholder copy says "Channel handle" 

T0-be: 
Update to "Channel Name"

**Comment by toiletgranny** [comment]
~~Hey, FYI, I'm still testing this. Will update the comment once I'm finished.~~

Ok, I finished! ✅
