### ISSUE TITLE
Opt back in after opted out or access to BE was revoked on YT side 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3545]
## Scope

For the channel on Atlas side, to avoid multiple re-conects and qualification for multiple sign on rewards, we need a special state for channels that were previously participating, but opted out from the programme. From this screen the channel can re-connect again. But this would not create a new record of the same channel, but only change the status.

- [ ] Implement the state of Dashboard when the channel access was revoked on YT side. 

[Figma Link ](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3611%3A93532&t=2S6bvCNw0lEo4Cvf-1)

Preview:

<img width="884" alt="Screenshot 2022-12-21 at 20 30 12" src="https://user-images.githubusercontent.com/93924525/208955755-15dcfa91-4d0c-4a27-ae6d-cfb5be9884c9.png">

BE link: 
- https://github.com/Joystream/youtube-synch/issues/107

## Context
@WRadoslaw discovered that when YT sync (access by backend app) is disabled on the YT side, it is not reflected on our BE, and user in Atlas ends up in the Dashboard where reconnect is impossible to trigger.

Raised an issue on the BE to Re-fetch connectivity status with the same frequency as subscribers and add a flag to DB to reflect disconnected status. This can be the same as Opt Out from YPP programme.

Here's the issue for it: 
- https://github.com/Joystream/youtube-synch/issues/96

**Comment by toiletgranny** [comment]
> we need a special state for channels that were previously participating, but opted out from the programme.

Just to confirm, so are we planning to make it possible for a channel owner to opt out from the entire YPP through the dashboard? Asking as I think we discussed this two days ago and came to the conclusion that there's not much sense in opting out from the YPP entirely, knowing that the YT sync can be disabled separately anyway. 

> @WRadoslaw discovered that when YT sync (access by backend app) is disabled on the YT side, it is not reflected on our BE, and user in Atlas ends up in the Dashboard where reconnect is impossible to trigger.

How can I disable YT sync on the YT side? Is there an option to do that on the creator's dashboard on YouTube?

**Comment by drillprop** [comment]
> How can I disable YT sync on the YT side? Is there an option to do that on the creator's dashboard on YouTube?

For google account you can do this here https://myaccount.google.com/security 
![image](https://user-images.githubusercontent.com/51168865/208081079-0dc3b3bc-9bfc-4db6-9c14-bf7b59280b53.png)

For a youtube channel, it's more complicated. Go to your channel settings and click the first one(sorry I have a polish language set 😅 )
![image](https://user-images.githubusercontent.com/51168865/208081427-0015d62c-337a-4df5-a1a8-a88f2ce12fe0.png)

And when you click you'll find somewhere there, but I don't remember exactly where

**Comment by dmtrjsg** [comment]
Re Opt out from Dash and our discussion, yes that was the motion originally we concluded that it would not make sense. But in the light of the newly discovered case, and the fact that we need to design a state where BE app is disconnected from YT (same as opt out) in my view it makes sense to also add this feature (opt out/ opt in) to the Dashboard. 

To avoid re-subsribe qualifying for original reward of enabling auto-sync.

**Comment by toiletgranny** [comment]
@dmtrjsg This is ready to be implemented! Designs, docs, and changelog [can be found here](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3338%3A84773&t=xK7Ba2GpgoBv6WYI-4).

**Comment by dmtrjsg** [comment]
@drillprop @WRadoslaw adding this to sprint backlog.. 

After some deliberation I think its best to actually have a special state (as per Adam's designs, rather than opting out from YPP entirely). 

Raised a BE task for it: 
- https://github.com/Joystream/youtube-synch/issues/107

**Comment by dmtrjsg** [comment]
Since the subscribers info is required for YPP participation this is not technically feasible to keep user opted in when YT access is revoked.

On that basis, when user revokes access we show user the Landing Page based on status - Opted out From YPP.
