### ISSUE TITLE
Display error message in the toaster notiff, when daily API quota is reached.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3547]
## Context

- https://github.com/Joystream/youtube-synch/issues/98

If the quota is fully exhausted (even this 2%), the BE will return specific error. (pls see linekd issue in the context section of this ticket). 

We need a specific error to be shown on the App side in two cases: before the sign up is attempted, and during

## Scope

- [ ] When quota on daily sign ups is reached before Auth flow is triggered, as soon as "Create channel and sign up" button is clicked display toaster notiff with "Due to high demand, we've reached the quota on the daily new sign ups. Please try again tomorrow."
- [x] if the user is unlucky to be in the process of signing up during quota reached, get back to the Sign Up screen and display toaster notiff "Due to high demand, we've reached the quota on the daily new sign ups. Please try again tomorrow."

**Comment by toiletgranny** [comment]
Quick question, does it have to be the "toaster notiff" in the first case scenario? Or can it be a different form of an error message, such as a Banner component displayed permanently in place of the "Sign up" button?

**Comment by dmtrjsg** [comment]
@toiletgranny I think this case will be really really really rare, so we could just not bother.. I honestly think it would not matter much 😇
