### ISSUE TITLE
tries to create membership for selected account with existing member

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#3567]
(on l1.media)

1. connect wallet
2. select account (here it could help to see which have membership already)
3. accept terms
4. "Create membership" - not necessary

**Comment by traumschule** [comment]
On the other hand i can create a member with the same name and see message that it was created. There was no tx in the block explorer though. :thinking: 

![created](https://user-images.githubusercontent.com/31551045/208915991-36c282fe-615d-4e44-a55a-8f14f04b42c3.png)

This might be a test setup using the wrong chain, need to check.

**Comment by dmtrjsg** [comment]
@traumschule faucet creates membership for you .. so this tx is signed by the acc connected with it? 

Not a bug 

cc @drillprop

**Comment by traumschule** [comment]
I saw no tx but was probably looking on the wrong chain.
