### ISSUE TITLE
Creator Tokens — Viewer: Marketplace (CRT & NFT)

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3593]
## Scope
- I would like to see a list of all CRTs,
- I would like to see a list of all NFTs (https://github.com/joystream/atlas/issues/1873),
- _From https://github.com/joystream/atlas/issues/2640:_
   - I would like to see a list of ongoing sales,
   - I would like to see a list of newest issued $CRT.

**Comment by toiletgranny** [comment]
@bedeho Yesterday you asked me to provide rough estimations for this CRT & NFT marketplace designs. And right off the bat: I reviewed the scope and past work we did for the NFT marketplace explorations back in August (https://github.com/joystream/atlas/issues/1873), and I'm afraid I can't offer you any specific number for how long this thing will take to deliver at this point. Let me explain why.

Looking at how open-ended the last discussion you guys had on the explorations for the NFT marketplace was before eventually putting it on hold in September [(link)](https://github.com/joystream/atlas/issues/1873#issuecomment-1233003964), I'm afraid we're in no better position to create something that's more user-feedback driven (for NFTs) today than we were back then. That's also the case with CRTs.

As far as I can see, our options today are the following:

1. Thoughtful competitor analysis potentially backed up with in-depth user interviews and, of course, our gut feeling is all we can rely on today if we want to offer an engaging discovery experience for NFTs and CRTs and if we want to do it right. I think we're looking at a few weeks of work, and I'm happy to provide more precise estimates for the research phase if you're interested in going down that road. It's a rather significant time investment, but — ultimately — I think it's the safest one.

2. Alternatively, going in the spirit of being a small startup, we can skip the in-depth interviews altogether, do a slack competitor analysis, and talk this all out at a meeting (yes, a meeting! Sounds so old-school in the times of async work, doesn't it) while looking at low-fi mockups. Something along the lines of how we worked on the Joystream.org updates recently. The time investment is smaller, but the risk is higher. I think I can come up with something for us to look at and talk about for next Tuesday (a reminder that Friday is a bank holiday in Poland).

3. Ultimately, if you see other, more urgent, things we should focus our attention on right now, we can take the line of least resistance and make the bare minimum changes to the current NFT page only [(link to Figma, as Altas is no longer and Gleev is not yet)](https://www.figma.com/file/T91xLMaDc5tjGDWIVldv2h/NFT-Marketplace?node-id=1212%3A41768&t=kZfPZIRtiwwbt476-4) so that it mentions CRTs and gives everyone an option to browse a catalog of channels that have their token. And for that, I can provide rough estimates right away: 2-4 days.

Please let me know which option you would like to go with today.

cc @dmtrjsg

**Comment by bedeho** [comment]
Thank you for this breakdown, really helpful.

**Comment by bedeho** [comment]
- I'm assuming that when you in 1. talk about a few weeks, and 2. talk about Tuesday: you are talking about time until conclusion of initial research.
- I don't actually think there is more risk in 2 compared to 1, quite the reverse actually. What I expect is that if we go with 1, we end up of course spending much more time (which obviously increases cost of failure on its own), but probably end up with a bigger scope and greater number of preconceived ideas, compared to just doing the absolute minimal approach to solving the problem, and updating based on what we see.
- Given the monumental amount of time it will take to ship CRTs, I think piling even more on top of that delivery to solve plausible, but hypothetical problems around discovery, should be low priority. I can think of many other problems where we _know_ that many users will get value with much greater certainty. Just a reminder here that my POV on all of these marketplace features is that they are just much more aligned with a mode of usage where users want to buy _something_, without a clear idea of what, and this just seems to not align with a non-speculative usage pattern for both types of assets. Creators are not fungible pairs of pants, to put it starkly, that viewers will buy into arbitrarily, or this is at least not the mode we are focused on enabling with urgency.
- I'm not totally opposed to doing the marketplace stuff, but it can't be approach 1, so it boils down to what sort of timeline we can have for research+design+delivery. I'm happy with trying to nail this down by Tuesday as you suggested, but we may have to just pause it depending on what we find.

**Comment by toiletgranny** [comment]
@bedeho 

> I'm assuming that when you in 1. talk about a few weeks, and 2. talk about Tuesday: you are talking about time until conclusion of initial research.

No, in 1, by saying "a few weeks" I meant the entire thing, so not only the research.

> Just a reminder here that my POV on all of these marketplace features is that they are just much more aligned with a mode of usage where users want to buy _something_, without a clear idea of what, and this just seems to not align with a non-speculative usage pattern for both types of assets. Creators are not fungible pairs of pants, to put it starkly, that viewers will buy into arbitrarily, or this is at least not the mode we are focused on enabling with urgency.

Totally on board with how you perceive the marketplace features, but in regards to creators not being _fungible pairs of pants_ (:D), I have to say that I _can_ imagine folks willing to invest in creators not necessarily because they like the content they produce, but because this might be simply profitable. And unless we give them at least a basic directory of channels they can invest in, their only way to seek investment opportunities in Atlas/Gleev is to manually go into each channel and check if the creator has issued a token. You did say, however, that this is not the mode we are focused on enabling with urgency, and — of course — I respect that.

> I'm happy with trying to nail this down by Tuesday as you suggested, but we may have to just pause it depending on what we find.

I agree that this now sounds like the best approach, so I'm getting to work right away!

**Comment by bedeho** [comment]
Ok, I basically agree with all of your points here.

**Comment by dmtrjsg** [comment]
Final Design work is executed here: 
- https://github.com/Joystream/atlas/issues/3596

Dev epics: 

NFT: 
- https://github.com/Joystream/atlas/issues/3686

CRT: 
- https://github.com/Joystream/atlas/issues/3773
