### ISSUE TITLE
Creator Tokens — Viewer: Marketplace (CRT & NFT): High Fidelity Mockups (HiFi), Documentation & Handover

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#3596]
This phase includes activities such as:
- creating Figma mockups from scratch, this time ensuring a proper design work hygiene (through naming layers, setting up constraints, ditching all unnecessary local components, etc.),
- creating/updating global components and their documentation,
- creating designs, documentation, and prototypes for all user stories,
- creating designs for responsiveness,
- identifying and designing for empty states, error states, and edge cases,
- applying visual finishing touches,
- etc.

The expected outcome is:
- a final video walkthrough of the Figma file and a prototype for engineers,
- links to Figma designs and prototypes,
- separate GitHub issues created for changing or introducing new global components.

**Comment by toiletgranny** [comment]
@bedeho, @dmtrjsg Designs and prototypes for the new Marketplace page are ready to be reviewed and handed over to the tech team. Find out all about it here:

1. [Figma designs, documentation, user stories, components, and prototypes](https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace-page?node-id=0%3A1&t=vqN4pG8cflGya0YU-1). 
2. [Final video walkthrough on Loom](https://www.loom.com/share/71042ce839fd4838b8ff1e92f25f59c2).

![image](https://user-images.githubusercontent.com/35307309/216840050-5d1e897b-db84-44b7-b665-82af3fcc70db.png)

⚠️ When estimating the work, please make sure to include all of the dependencies, for which I created separate GitHub issues and connected them with this one using ZenHub.

**Comment by bedeho** [comment]
Fantastic work Adam, looking forward to seeing this come to life.

I'm not 100% sure why all of those issues are dependencies, at least the layout one was intended to be done independently of anything else, but I'm sure @dmtrjsg can enlighten me when the time comes.
