### ISSUE TITLE
Creator Tokens — Viewer: Video page | Token info

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3598]
This issue covers designing a way to inform the user that the video of the channel that they are currently watching has a CRT token issued.

**Comment by KubaMikolajczyk** [comment]
# Context
The idea of presenting information about the channel owning a Token comes from this user story:
> I would like to see whether a video I am watching is from a channel that has $CRT.
It's in this epic: https://github.com/Joystream/atlas/issues/2640

This was explored by me some time ago already and we chose num one of the explorations as the one to go with
![image](https://user-images.githubusercontent.com/31144205/211298611-714ccb6c-0f5b-4ed9-a4ac-8c8de7758c15.png)

And I have even already explored this idea in hi-fidelity 
![image](https://user-images.githubusercontent.com/31144205/211298835-67be5176-6e58-4dca-a744-95094786c5c1.png)

But on today's design morning standup with Adam, we discussed it and Adam noticed that the information about channel owning a token should be displayed not only on the video page but on other components where we present channel as well
![image](https://user-images.githubusercontent.com/31144205/211299154-e5898942-e7ce-452f-9b5a-52819ede75b1.png)

This led me to explore the patterns for including small badges and other marks around the avatar and channel name area. But I am aware that we want also to include channel verification in the near future to be visible next to the channel (something like Twitter or YouTube does).eg.
![image](https://user-images.githubusercontent.com/31144205/211301154-068945bc-0809-4e34-ba5a-532e85ad0b88.png)
![image](https://user-images.githubusercontent.com/31144205/211301242-b973312c-4f04-458c-8e5a-423c46981901.png)
![image](https://user-images.githubusercontent.com/31144205/211301451-fda33b3a-99a5-4be8-bc7f-e891e7466fe3.png)


# Questions

1. Are we going to implement channel verification & show it on the channel?
2. If you have any other statuses in mind that could be displayed next to the channel avatar name that we might want to have in the future please share 

The above questions are crucial for me to design those little badges/info in a way that will not overload the channel avatar + name info when used together.

**Comment by bedeho** [comment]
> Are we going to implement channel verification & show it on the channel?

Yes, an in fact verifications are likely to be required for certain $CRT features to work at certain times, more on this later.

> If you have any other statuses in mind that could be displayed next to the channel avatar name that we might want to have in the future please share

I don't ;)

**Comment by KubaMikolajczyk** [comment]
Exploration work, research and hi fi solutions for token info is done ✅
Token info on video page, token info on channel and channel verification as a bonus - a lot of things to unpack - enjoy 👍
🎥 Loom video update: https://www.loom.com/share/4aff908188c142cf9183d515ce288948
📄 Figma explorations: https://www.figma.com/file/JrPSy24YOAH9mhJU4LvjeF/Token-info?node-id=1524%3A101402&t=gPRRALBBYPwyUVC3-4

**Comment by bedeho** [comment]
Thank you for this, decided to give quick feedback since this was small.

- I also think the star+circle variation was the most graceful one.
- I think we should be mindful that the presentatio of verification and crt status  does not need to be uniform in all contexts. For example, when on the creator page, or in the creatore token markteplace, then its super important to easily distinguish verified from not, and this then justifies very attention grapping distinction between these states, in contrast to say a normal page with lots of videos, where it is actually close to irrelevant to indicate what creator has a creator token, and which does not, because the content is in focus. I hope you can bear this in mind as you design variations for other places in the app.
- Coin price is not a meaningful indicator: this is important to realize, and for that reason I think it should not be present in the preview areas anywhere here. Ill just C&P from my last review to Adam on this topic: _Unit price is not relevant, it may be actively misleading if there is a lot of diversity in how people select the supply and how it changes over time. What matters is market cap. It may be that you have seen unit price emphasised in other creator token systems, but they are very likely from contexts where either creators cannot impact supply, or supply is fixed, or option is minimal, we cannot rely upon that assumption._
- I think the tooltip makes sense, at least in some places.
- I don't think the large extra "See JBC token" thing serves any purpose. As I said, unit price does not matter, and many tokens won't have one even if it did, and more importantly the bloated labels is just taking up lots of space we may want to use for other things later (e.g. membeships, badges, etc. ) without any upside. If we want to allow the user to go to the token page, this can be in the tooltip.

**Comment by KubaMikolajczyk** [comment]
OK I will proceed with this variation :)

> I think we should be mindful that the presentatio of verification and crt status does not need to be uniform in all contexts. For example, when on the creator page, or in the creatore token markteplace, then its super important to easily distinguish verified from not, and this then justifies very attention grapping distinction between these states, in contrast to say a normal page with lots of videos, where it is actually close to irrelevant to indicate what creator has a creator token, and which does not, because the content is in focus. I hope you can bear this in mind as you design variations for other places in the app.

I feel it might be beneficial to show this little, desaturated mark on the viewer discovery part of the app as well. Due to the fact that users have something called "selective attention - _People filter out things from their environment when in focus_" and "banner blindness - _Users tune out the stuff they get repeatedly exposed to"_ when the mark is so small and desaturated, it will be easily filtered out by the eye when not looked for. But in a scenario where the user wants to specifically watch videos of channels that are verified or have a token issued this information would be really really useful to have on all discovery pages on the viewer part of the app - so one wouldn't have to solely depend on token discovery through a "marketplace" experience or randomly encountering a creator with the token, but would also have a possibility to look for those creators in a natural way by simply interacting with the app (on the main page, new noteworthy, discovery etc.). Wouldn't you agree? 

> Coin price is not a meaningful indicator:

OK dropping the coin price

> I don't think the large extra "See JBC token" thing serves any purpose.

OK I will remove it.

**Comment by dmtrjsg** [comment]
> But in a scenario where the user wants to specifically watch videos of channels that are verified or have a token issued this information would be really really useful to have on all discovery pages on the viewer part of the app

I tend to agree with this, does no harm in showing this status in the video discovery, esp that it is so tuned down.

>If we want to allow the user to go to the token page, this can be in the tooltip.

What would make sense to add to the tooltip? how about:
1. Name
2. Traded or not
3. Number of holders
4. Total "Trust Value" - amount of JOY invested to the token already by community. 
5. View token link>

@bedeho

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg Due to the issue that I encountered with too little space for those two elements to be hoverable next to each other (as their touch targets would overlap each other) - I had to create a new solution for the tooltip that merges those two concepts together - I have it almost ready tomorrow I will post an update here for the review

(With this new concept adding any additional info to the tooltip will look like too much - but I will explain more in tomorrows update on this 🙇)

**Comment by bedeho** [comment]
> But in a scenario where the user wants to specifically watch videos of channels that are verified or have a token issued

I don't buy this scenario at all, like literally 0% do I think this is likely :D 
Consumptino will not be guided by status or token presence, as a baseline - whether on YT or Twitter, no one looks for people with verified status, or even just to filter on only verifie dstatus, for what they see.

People may care about these signals when looking to buy a token, but then we are back in the marketplace area.

> Total "Trust Value" - amount of JOY invested to the token already by community.

There is no established concept like this really, not sure what it means exactly, but its not widely understood _even among crypto investors_.

**Comment by KubaMikolajczyk** [comment]
# Status
✅ The hi-fi work for this issue is ready to be reviewed. 

The work was meant to cover the following user story:
"I would like to see whether a video I am watching is from a channel that has $CRT."
From this epic https://github.com/joystream/atlas/issues/2640

🎥 Link to video update (5min): https://www.loom.com/share/610f47f24f364d8a9dd88eae6dc60291
📄 Link to figma changelogs: 
- Video page - https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video-page?node-id=6396%3A297910&t=qe6DM6y3ve4CyW4l-4
- Channel page - https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1624%3A85414&t=EauWB2YHFl4cAgqf-4

**I would advice to watch the update first to see what its all about before reading paragraphs below**

# Displaying verification & token statuses in viewer experience

I have to try to sell my POV again regarding this topic as I feel it is important. I will start by saying that I understand your POV, and correct me if I'm wrong, your gut feeling on this topic is that no one will consider "verified & token indicators" as important when simply enjoying the content on the platform as this is not their primary goal at this point. Therefore its not worth putting any additional visual clutter in the viewer experience designs as those "verified & token indicators" are not going to bring any significant value and are not that important to be there.

### 1. Verification marks are they important?

To answer this question it might be helpful to analyze the recent case of twitter. After changes in management - big changes in product development & design followed. One of those changes was the fact that everyone can buy the "blue checkmark" for $8. A widely known pattern of user verification indicator was changed to something else that you can buy. But users mental model remained that it means that the profile is verified and legitimate. Some fake account with a verification tweeted  something that in result led to huge drop in stocks of the real company that had no idea about it.
https://mashable.com/article/eli-lilly-stock-dip-twitter

Verification is an important pattern that lets users tell the difference between the real account and the fake one. Without it users can only rely on their gut feeling. The pattern of adding a verification mark next to the channel name is also widely used among many different products.

In our case, fake account could be created to potentially harm some token creators by faking their accounts and uploading controversial or vulgar content. Sure users can just inspect the video or inspect the channel and see there is the channel is marked with verification indicators, but as twitter example teach us users not always seek the 100% truth and try to check legitimacy of new information - sometimes they just go immediately to stocks (or to my portfolio in our case) and sell everything.

### 2. We already show it on the viewer part of the app
We show that the user has a verification & a token on the video page in channel info. This is a part of the viewer experience which is not "on the market side" but on the content viewer side, but still there is a need to expose this information there for the viewers so they can be aware of the fact that:
"I would like to see whether a video I am watching is from a channel that has $CRT."
From this epic https://github.com/joystream/atlas/issues/2640
Why would we want to hide this information on the level of video discovery?

### 3. We show NFTs on the video tiles
We also show an NFT pill on the video tiles of videos which has an NFT issued for them. There is a potential here for us to follow that pattern and show the token indicator there as well.

## Where?
If we decide to expose this information to the viewer there are 4 components on the viewer side of the app that can benefit from this information. And its global search, viewer video tile, channel card, and channel section. I added those to the components below. 
#### Here is the version with them:
![image](https://user-images.githubusercontent.com/31144205/213749322-a0501e8e-b67d-47ea-baf6-fa517ed6f676.png)
#### Here is the version without them:
![image](https://user-images.githubusercontent.com/31144205/213749554-5acb5f37-6736-47a5-9d2b-1b1fba379da9.png)
(I bet you had to zoom those images to see the difference ;) )

## Conclusion
I have a feeling that it might add additional value to the whole watching experience and to the whole idea of turning viewers into supporters or investors. Taking this approach could potentially make it even easier for creators to grow their tokens and for viewers to discover creators who has tokens. Not even mentioning the importance of verification indicators which I explained above. 

> I don't buy this scenario at all, like literally 0% do I think this is likely :D

Ultimately it's up to you @bedeho as I can see you have a strong feeling here so if you will "stick to your guns" its ok :) But I had to leave my POV here as well.

**Comment by bedeho** [comment]
1. hehe ok, let try it then, I don't think a mistake is very costly here.
2. Merged tooltip wise a nice solution!

**Comment by KubaMikolajczyk** [comment]
✅ The viewer part of the verification & token indicators are done and can be inspected for implementation here 👇

Flows:
- Search flows: https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=536%3A52442&t=mZSWEwXDoFYgiPWx-4
token & verification flow: https://www.figma.com/file/cRR8k0z8vx6PfuXqGeiyRx/Token-%26-verification-info?node-id=1601%3A1435&t=NcINbzY4ITzcIt7V-4

Components:
- Video tile details component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3630%3A112918&t=YxJKiyvlXhY6Kchh-4
- Channel card component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=4094%3A144644&t=YxJKiyvlXhY6Kchh-4
- Channel info component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A27109&t=YxJKiyvlXhY6Kchh-4
- Global search box component:  https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=2%3A10987&t=mZSWEwXDoFYgiPWx-4

**Comment by dmtrjsg** [comment]
Great job @KubaMikolajczyk  ⭐ 

Not meaning to complicate things and it might be late in the day so I may be missing smth but..
 
1. Why do we have to go for different treatments in the search preview with full text "verified" and "$CRT" and other components where the same is shown as icons?
 
<img width="459" alt="Screenshot 2023-01-23 at 16 45 23" src="https://user-images.githubusercontent.com/93924525/214098401-429abe17-97e2-4860-bb4d-7a764111dd4b.png">

**Comment by dmtrjsg** [comment]
Implemented here:
- https://github.com/Joystream/atlas/issues/3840
