### ISSUE TITLE
Incorrect display of locked funds

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3604]
<img width="343" alt="CleanShot 2023-01-10 at 10 35 10@2x" src="https://user-images.githubusercontent.com/12646744/211514982-8854c36d-c72b-47fa-914d-3e0c2a1c958a.png">

2 issues here:
1. The number doesn't fit in and it weirdly wraps around
2. Funds under vesting lock are also shown as "Invitation lock", maybe worth considering just changing that to "Locked funds"?

**Comment by dmtrjsg** [comment]
Thank you for raising! We discussed this before agreed not to show locked funds for Atlas users as vesting locks would mainly not apply to the Atlas user base. 

@drillprop can you pls take care of only showing the invitation lock in this field?
