### ISSUE TITLE
Add Joystream LIcense

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3609]
## Context
- https://github.com/Joystream/youtube-synch/issues/99

## Scope
- [ ] Add new section to Copyright Policy called "Content License" to **Atlas** T&Cs > https://*/legal/copyright
- [ ] Add Joystream Standard License to > https://github.com/Joystream/atlas/blob/master/packages/atlas/src/data/knownLicenses.json
- [ ] Make Joystream Standard License default choice for manually uploaded videos

Title:  "Content Licenses Supported By Joystream Platform"

1. Joystream Standard License

Joystream Standard License is the default setting for all uploads. It allows creators to retain all ownership over their content, which published on Joystream network storage nodes, while giving any App built and operated by JS Genesis, Joystream DAO or external operators that work with Joystream Blockchain to broadcast this content.

For content automatically synced from Youtube via Youtube Partnership Programme, YouTube Standard License is substituted by Joystream Standard License. 

2. CCO

The CC0 (Public Domain Dedication) License allows creators to waive all rights to their creations and release them into the Public Domain

For the synced videos with Creative Commons License, Auto-sync service assigns CCO license, explained below. 

More information can be found following _this link_ [https://creativecommons.org/share-your-work/public-domain/cc0] 

3. Custom License

Joystream channel operator may choose to add custom license to the uploaded content.

4.  Other Licenses

Other licenses supported by Joystream are:
- PDM - Public Domain - For items which are not protected by copyright. This is not a license, but rather a copyright status. Some government-produced works, items with expired copyrights, and those which are ineligible for copyright protection may be included in this category.
- CC BY - Creative Commons Attribution License - Sharing and adapting this content is permitted, but attribution must be provided. Read the License Deed for more information.
- CC_BY_SA - Creative Commons Attribution-ShareAlike License - Sharing and adapting this content is permitted, but attribution must be provided. Any derivative works must be distributed under the same license. Read the License Deed for more information.
- CC_BY_ND - Creative Commons Attribution-NoDerivs License - Sharing this content is permitted, but attribution must be provided. You may not remix, transform, or build upon the material. Read the License Deed for more information.
- CC_BY_NC - Creative Commons Attribution-NonCommercial License. Sharing and adapting this content is permitted, but attribution must be provided. Commercial use is not permitted. Read the License Deed for more information.
- CC_BY_NC_SA - Creative Commons Attribution-NonCommercial-ShareAlike License - Sharing and adapting this content is permitted, but attribution must be provided. Any derivative works must be distributed under the same license. Commercial use is not permitted. Read the License Deed for more information.
- CC_BY_NC_ND - Creative Commons Attribution-NonCommercial-NoDerivs License. Sharing this content is permitted, but attribution must be provided. You may not remix, transform, or build upon the material. Commercial use is not permitted. Read the License Deed for more information.

5. License Config File

Licenses supported may be updated at any time and full set of licenses that are available for selection in the App upon video upload or uploaded via Command Line interface are contained in this file: https://github.com/Joystream/atlas/blob/master/packages/atlas/src/data/knownLicenses.json

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203870588626346) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
"code": 1009,
    "name": "Joystream License",
    "longName": "Joystream Standard License",
    "description": "Joystream Standard License is the default setting for all uploads. It allows creators to retain all ownership over their content, which published on Joystream network storage nodes, while giving any App built and operated by JS Genesis, Joystream DAO or external operators that work with Joystream Blockchain to broadcast this content.",
    "url": "play.joystream.org",
    "attributionRequired": false
    
 
 
 __
 
  ⚠️  confirm license code with @zeeshanakram3

**Comment by bedeho** [comment]
Looks solid, just update hosting: play.joystream.org

**Comment by dmtrjsg** [comment]
@bedeho pls be informed, that after your initial review  I am adding requirement to add the license information under new header to the Copyright Page.

**Comment by dmtrjsg** [comment]
License field seem to be empty: 

https://atlas-git-ypp-joystream.vercel.app/video/414

<img width="864" alt="Screenshot 2023-01-30 at 18 55 19" src="https://user-images.githubusercontent.com/93924525/215569093-9f9180bb-836d-4526-98fa-8e3a4ca0ba29.png">


I think the Backend part is not fully done yet..
