### ISSUE TITLE
We should inform user about `nftPlatformFeePercentage` when user is listing nft

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3621]
So this happened to me during testing gleev:
1. I listed nft for 100 joy for a fixed price.
2. Someone bought this nft for 100 joy.
3. I went to my channel and checked my channel account and surprisingly noticed that I received 98 joy, not 100 joy. 

This happened because every time someone buys NFT we're taking the so-called `nftPlatformFeePercentage`. In this particular case, it was set to 2%.  It's displayed only on Purchase View https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?node-id=1236%3A26860&t=K9VBQmZPqx2cwp5V-4 
![image](https://user-images.githubusercontent.com/51168865/212324927-129a853e-59ed-45c8-9da6-803bd7dbece3.png)

The problem is this information should be displayed to a seller as well because he's actually losing some money when he lists his videos. I checked the designs and we don't inform the user that he won't receive all the money. We only inform about the creator's royalties, not platform royalties.  
https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=2393%3A85860&t=q9EUF0iw0C5Dg1jL-4

**Comment by dmtrjsg** [comment]
Agreed to show the platform fee on the confirmation page
Perhaps also on the page where price for NFT is set up, but for @KubaMikolajczyk and @toiletgranny to decide if we need it in both places..

**Comment by KubaMikolajczyk** [comment]
The platform royalties (its not a fee as its not a one time thing - its being deducted each time the NFT is sold so its a royalty) are added to the summary of the NFT Workspace summary (step 3). I would vote against adding it to the screen where user sets the NFT price as we currently set creator royalties on different screen and showing them both at the end seems logical.
 
📄 Link to figma changelog: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/Video-workspace?node-id=1945%3A109809&t=LYqzRjIRyXrKucJW-4

**Comment by dmtrjsg** [comment]
Might be a good one to start with for @attemka..
