### ISSUE TITLE
[USERSNAP] Expected no starting price, since i disabled the toggle

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3624]
**Sender**: None
**Taken at**: https://gleev.xyz/video/5
**Fields**:
- Expected Result: Expected no starting price, since i disabled the toggle
- Houston, we have a problem.: Disabled the NFT auction starting price, but it still set a starting price

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/51bc9f7a-9f1e-4099-8e1f-e5bb37f35c33-annotated_e8bb9bec-a9cd-464a-bbae-351cb4344280.png?etag=85b47d679fb72d70aaf4b653a287e8c8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/51bc9f7a-9f1e-4099-8e1f-e5bb37f35c33-annotated_e8bb9bec-a9cd-464a-bbae-351cb4344280.png?etag=85b47d679fb72d70aaf4b653a287e8c8)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 2560x1440
**Browser size**: 2560x1254
**[Open #26 in Usersnap](https://app.usersnap.com/l/feedback/f91e583e-54fc-4142-84e9-f2d75fba8bc9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by drillprop** [comment]
Currently, it's not possible to create an auction without starting price: 
![image](https://user-images.githubusercontent.com/51168865/236400469-b1532881-f76c-4cbe-bc10-962563b8d24a.png)
 I'll remove the toggle.

**Comment by dmtrjsg** [comment]
@drillprop you mean it is not possible on the blockchain level?

**Comment by drillprop** [comment]
> @drillprop you mean it is not possible on the blockchain level?

There is a value on the chain called `minStartingPrice`, and it's possibly adjustable, but I don't know how to adjust it, who can do it, and if it's actually possible to change it to 0.  

Anyway, on the front end, I removed this switch above the input. It will show only if the `minStartingPrice` equals 0. Otherwise, the user will see the input with the default minimum bid
