### ISSUE TITLE
[USERSNAP] Why can't I scroll down on this screen?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3625]
**Sender**: None
**Taken at**: https://gleev.xyz/member/web3mercury?tab=Activity
**Fields**:
- Expected Result: Why can&#39;t I scroll down on this screen?
- Houston, we have a problem.: No scrolldown?

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5547e4cb-b69c-43a3-8899-160331d870dc-annotated_709cc28f-2b02-4809-8c25-2a603d446375.png?etag=7a94ec7ad4e25de20b64a5291893faac)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5547e4cb-b69c-43a3-8899-160331d870dc-annotated_709cc28f-2b02-4809-8c25-2a603d446375.png?etag=7a94ec7ad4e25de20b64a5291893faac)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #27 in Usersnap](https://app.usersnap.com/l/feedback/44b5e1b3-bd7d-4f28-b342-50e7ba348391?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by iamnamananand996** [comment]
[screen-capture (5).webm](https://user-images.githubusercontent.com/31537362/215262006-c52be0d7-e75b-4495-a489-b8658ffd3dcd.webm)


### It seems like this is working now nicely.
I have checked this issue with **Chrome (Version 109.0.5414.120 (Official Build) (64-bit)) and Microsoft Edge**.
