### ISSUE TITLE
Introduce geolocation awareness in SP selection

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3626]
Same as https://github.com/Joystream/atlas/issues/2748 but for storage nodes. Currently when uploading a random node is selected, it is best to sort them by geographical closeness as well

**Comment by dmtrjsg** [comment]
@kdembler thank you for raising sir, how urgend do you feel it is, what's the impact of not doing it right now?

**Comment by kdembler** [comment]
I think it's quite important to do so. Because the storage bucket is selected at random, I can sit in Asia and upload to a node in US, which can result in poor performance or errors along the way. Also, there's already a mechanism set up for doing this for distribution buckets so the implementation should be fairly quick

**Comment by dmtrjsg** [comment]
@attemka fyi another candidate to add to sprint if we are running out of issues..

**Comment by traumschule** [comment]
We currently have have functional SP in Canada, Singapore and EU (France, Germany). This could indeed help upload performance, reliability and cut unnecessary traffic (delays).
