### ISSUE TITLE
Exclude channels which are apps from showing them in Atlas

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3627]
# Background

https://github.com/Joystream/joystream/issues/4158

# Proposal

Atlas has to _somehow_ deal with these new channels, but it's not at all obvious how much effort should be put into doing this in a sophisticated way, in particular before creator tokens exist. I just want to higlight that this is just as much a product design as a pure engineering problem.

**Comment by attemka** [comment]
## Scope
 
All instances of atlas should exclude channels that are Apps  and  all its videos from all atlas instances to show in 

- Categories
- Featured section
- Discover new channels section
- Search

**Comment by attemka** [comment]
@attemka to check if orionv1 can support hiding channels

**Comment by bedeho** [comment]
I think this is a fine starting point, but remember that this feature lands _after_ orionv2, which now apparently is like 2weeks away, so you probably want to look at v2 for this.

**Comment by dmtrjsg** [comment]
Agreed to only build this for Orionv2

**Comment by dmtrjsg** [comment]
Closed in favour of decision to progress with Apps as members (aka first class citizens)
