### ISSUE TITLE
Add message on payout cadence to YPP dashboard 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3636]
Add message somewhere to the dashboard:

Rewards are calculated and paid on a weekly basis, every Friday, for the previous calendar week. Your first payment will involve the reward for the sign up!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203870938777897) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Decided to use banner between widgets and rewards tasks. In the designs feel free to drop the second reward (posting atlas videos on Youtube)

**Comment by dmtrjsg** [comment]
Also, let's pls add a message that only verified channels will be rewarded. 

Once your channel is verified, you will qualify for the rewards. Payouts are made on a weekly basis, every Friday, for the previous calendar week. 
Your first payment will involve the reward for the sign up of XXXX Joy!

**Comment by KubaMikolajczyk** [comment]
✅ The banner with information is added to the designs and the second reward (Share gleev on YouTube) is dropped both on dashboard and YPP landing page
📄 Link to figma changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3338%3A84773&t=lJdejs90CJmVKnCi-4
