### ISSUE TITLE
Inform Creators during YPP Onboarding - Opt in to Autosync page that they will only get paid for Auto-synced videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3642]
## Context

We discovered that operationally it is unfeasible to track the manually uploaded videos/ de-dupe with auto-sync and reward in automatic way at scale, so have to drop this part. Meaning we will only reward creators for the auto-synced videos. 

## Scope

I suggest to add a warning when they try to opt out that they will not be compensated for manually uploaded videos; or maybe a combination of both reinforcing that they will be paid if opted in/ and not paid if opted out. But this needs to be a clear message (to increase the chances of opting in).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203780318565104) by [Unito](https://www.unito.io)

**Comment by KubaMikolajczyk** [comment]
✅ Added a banner to the flow where users can decide to opt-out of auto sync
📄 Figma changelog file: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3338%3A84773&t=lJdejs90CJmVKnCi-4

**Comment by dmtrjsg** [comment]
@WRadoslaw  pls fyi:

Change copy from: 
"We cannot reward videos uploaded manually. To get rewards for auto uploaded videos consider switching to syncing Youtube videos."

To 
"Manually uploaded videos are not qualifying for programme rewards. To get rewards for content upload consider switching to syncing Youtube videos."
