### ISSUE TITLE
Idea: How to run experiments

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3653]
# Background

We are increasingly going to want to address problems, for example identified by talking to users or observing problematic conversion rates in key flows, but where it is not obvious what among a variety of alternative fixes is ideal. Some times it may even be that one solution is better than the other, but that the differential is sufficiently small that the differential cost of execution still warrants going with the sub optimal approach. Either way, having solid data is a prerequisite for answering such questions. While we have user testing at the design stage currently, this sort of tests are both slow to organize, and also ecological validity is both lower, and hard to quantify with any level of confidence. Being able to make that determination based on data from real users using the product organically is the first-best approach.

# Proposal

Make it possible for an Atlas operator to run multiple AB tests in parallel, in production, without down-time, and deploy this capability in Gleev specifically. Obviously, this sort of activity requires tooling and integrations outside of the Atlas code base specifically, but thinking about how that sort of system should work will generate some set of required changes to Atlas to unlock this workflow for app teams, and we should lead the way on this with Gleev.

**Comment by dmtrjsg** [comment]
Great stuff! more effective with high traffic for statistical significance of experimentation on deeper flows.

Here are the two tools I know, have VWO hands on experience in eCommerce context. We could look into the instrumentation efforts at least and see if that can work with our stack. 

https://docs.developers.optimizely.com/digital-experience-platform
https://vwo.com/fullstack/server-side-testing/

VWO historically was cheaper, but was limited in capabilities. Seems to be on par rn with Optimizely.
