### ISSUE TITLE
Add new Gleev Categories

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3657]
## Context
https://discord.com/channels/811216481340751934/1035131444080680971/1066013334341693540

## Scope
- [ ] Add "Crypto Art"
- [x] Add "Education" 

Icons and images to be designed

**Comment by KubaMikolajczyk** [comment]
✅ The work is done.

- 2 new icons added for crypto art & tutorials categories
- 2 new cover images are added for crypto art & education categories
- Tutorials icon moved to be used as education icon
- Original images added to images folder (Those need to be converted by devs to webp)

📄 Crypto art category: https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=2037%3A17485&t=YwIgPX6dnYrpr5Du-4
📄 Education category: https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=2037%3A17507&t=YwIgPX6dnYrpr5Du-4
📄 Tutorials category: https://www.figma.com/file/UdBMxrLspjcf6IVYYJS8YP/Discover-page?node-id=1822%3A7044&t=YwIgPX6dnYrpr5Du-4
⚪️ Github folder with images: https://github.com/Joystream/atlas-resources/tree/main/video-categories/gleev/original

**Comment by attemka** [comment]
@attemka to create QN categories
