### ISSUE TITLE
Coordinate signer recommendation with browser

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3674]
Currently, the user will be recommended to install a signer even if that signer is not compatible with their browser. This leads to a bad experience where the user is sent to a new app, like an extension store, even though the install will not work. 

One alternative way to deal with this is to only suggest those extension which are known to work for the same browser&device the user is currently on. If none are compatible, explain that, and show an alternative list of browsers that work for this device, where there are known signers working.

**Comment by dmtrjsg** [comment]
**Context**

Supported browsers:

Subwallet: 
Chrome, FF, Brave, Edge

Polkadot: 
Chrome, FF, * (probably also supports Brave and Edge via Chrome extension)

Talisman:
Chrome, FF, Brave, Edge, Arc

* Firefox has its own store, while all others share the same link.  Other browsers are based on Chrome. 

Solution: 
If browsers are based on Chrome, keep the links for Chrome to install. 
If browsers are based on FF, link to firefox store. 
If the browser is neither (e.g. Safari), we need to ask them to access app from another browser.
