### ISSUE TITLE
Remove personal info from the scope of YT permissions given to Atlas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3687]
## Scope
- [ ] We only need YT channel data and email

## Context

![Screenshot 2023-01-26 at 19.09.21.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/bc0a8908-c670-4fa7-abe7-bbc00b01490d)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203843312297610) by [Unito](https://www.unito.io)

**Comment by attemka** [comment]
@dmtrjsg does it happen when you're trying to opt-in your account to YPP?

**Comment by drillprop** [comment]
> @dmtrjsg does it happen when you're trying to opt-in your account to YPP?

@attemka 
No, this is displayed once you're signing into the Ypp program https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=1607%3A93324&t=uG6yZNtxD2vsY2P2-4

I think we need to remove ` https://www.googleapis.com/auth/userinfo.profile` from the scope inside `packages/atlas/src/views/global/YppLandingView/YppAuthorizationModal/YppAuthorizationModal.hooks.tsx`

And this should do the job.

**Comment by attemka** [comment]
> No, this is displayed once you're signing into the Ypp program

thanks, yes, I meant the same screen.

@dmtrjsg I'll remove user's profile from the scope, but we need to pass openid, which means that permission to'Associate you with your personal info on Google' should stay for OIDC (Open ID Connect) to work and we can parse user's email into sign-up modal.
