### ISSUE TITLE
Market and Private Sale video run through

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3712]
Record a run through of the happy path for the finalised flow for opening Market and Private sale from creator and buyer's  POV.

Imho best to do 2 videos:
- Creator Market Sale + Buyer Minting of tokens
- Creator Private Sale + Buyer Private Purchase of tokens

**Comment by KubaMikolajczyk** [comment]
Two videos of those happy paths are done ✅
CRT Market: creating, buying & selling : https://www.loom.com/share/c94361bd675841bbb9e79d338e976b80
CRT Sale: creating & buying: https://www.loom.com/share/3a78c6ec0c52440b99e5b412985aeebc
