### ISSUE TITLE
Support YouTube attribution for videos and channels

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#3714]
# Background

https://github.com/Joystream/youtube-synch/issues/139

# Proposal

The simplest level of support is just to make sure that the updated QN schemas work fine, not sure how much effort that requires - if any, just making issue to be certain concern is not missed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203878755864415) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Atlas side only adds types to QN to support point 4 from: 
- https://github.com/Joystream/youtube-synch/issues/139
