### ISSUE TITLE
(2nd round Test) Creator Tokens — Viewer & Buyer

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3725]
This includes conducting moderated usability tests on prototypes from "[Channel page](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1902%3A153908&t=01fzJVRPcJRqFPLw-1)" file (Viewer) & [My portfolio](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=5%3A2990&t=a3SDKGSugYUGvdf8-1) file (Holder). The tests should cover happy path flows for:

Buying, selling tokens on market & sale
Revenue share experience (state recognition, claiming, unlocking)
The expected outcome is a brief summary of key findings, a list of recommendations, and a list of test participants to be paid out.

Depending on the results, the next step is either proceeding finalizing the designs as it is or performing necessary changes on the hi fi designs.

**Comment by KubaMikolajczyk** [comment]
# Overview
This is the final round of moderated tests which the primary goal is to find out if users understand everything and are able to perform such actions as:

- Buy on market
- Sell on market
- Buy on sale
- Recognize states of revenue share
- Participate in revenue share

# Wallets to pay
(We agreed to pay $30 worth of BCH)

169m3YZbHxhVAdEyezKAJbCSJhkbqpSRoG
qphaa35c0rszdx4xml958k38yfw0t9u5jccw68usrg
1P7hP9MA4prfsrLm1QwnF8KgG5TA3mFBvP 

# Recordings links
All session recordings: https://drive.google.com/drive/u/0/folders/1F_z81_NN-0wnvsWLM9usHzdcL4LGp5Iv

# Key findings

### 1️⃣ Lack of information about cliff, vesting and first payout before engaging with sale
Issue: When participants reached the vesting and cliff modal screen in the flow of buying on a sale all of them stated that they were "shocked" at first because this information weren't presented to them before they started the purchase flow.
![image](https://user-images.githubusercontent.com/31144205/223078883-75522655-4a71-48f9-a61b-75f9b2f927cc.png)

Recommended solution: We should present the information about cliff, vesting and first payout in the token widget (the first thing that users see) so they will get this information before they decide to buy. This will reduce possible irritation caused by lack of information on early stage of this flow. (red arrow points to where this information should be placed)
![image](https://user-images.githubusercontent.com/31144205/223079034-300ffc04-de55-4cd0-a998-780f5177802f.png)

### 2️⃣ Currency & currency conversion
Issue: Users seem to be confused a little by the currency conversion (shown in the image below) - most of them say that they didn't know that its a conversion and didn't know what is the currency here. 
This looks like a potential "first timer" problem - someone who is not yet familiar enough with JOY symbol can be confused about it & then if there is another currency below it can also create a confusion.
![image](https://user-images.githubusercontent.com/31144205/223082703-f5197b58-b12c-4353-af66-2c49dd80ab5e.png)

Recommended solution: We can add a label "JOY" for the joy icon so it will be easier to learn the currency symbol. And for the currency conversion we can use approximately equal sign (≈) before the conversion to further bring the msg that it is indeed a conversion rather than just a second currency.
![image](https://user-images.githubusercontent.com/31144205/223082942-096a2208-e875-4f87-847f-b6d096e53027.png)

### 3️⃣ Learning about all token states
Issue: Users wanted to be able to learn about all states (No sale, market, sale) as they were browsing the token page as when they were presented with the "market" state they wanted to know in what kind of other states the token can be.
![image](https://user-images.githubusercontent.com/31144205/223085550-52e30970-d42f-416d-8baa-2910bc46a5c7.png)

Recommended solution: We can rework a bit the part of the token widget where the type is presented and provide there a way for the users to learn more. Either a dialog with information, link to a video or link to an external notion documentation about this - with the latter being probably the easiest to implement.

### 4️⃣ Total supply important but not visible enough
Issue: Total supply was repeatedly mentioned as one of really important factors which will guide buyer through the purchase decision process - however it is currently really small and users had hard time finding it.

Recommended solution: We should move total supply to the token header widget and either make two lines of information with 2 info items in row, or move annual reward to the expandable statistics as this information is not that important as the others.
![image](https://user-images.githubusercontent.com/31144205/223085686-d833b215-5b7a-4aad-8059-c526f0d34a59.png)

### 5️⃣ Total in CRT trade dialogs
Issue: 
(Part 1/2) When either buying tokens users were confused they didn't see the total of the transaction - they said that they would expect to see the 10020 JOY total summing up what they would spend and fees in one when purchasing in the scenario on the image below
![image](https://user-images.githubusercontent.com/31144205/223087080-d3eac522-1a39-45fb-ab4c-a232c05029d4.png)

(Part 2/2) But they also lacked a total of what they would get and fees in one when selling. In scenario on the image below they said that they would want to see 9980 JOY as a total.
![image](https://user-images.githubusercontent.com/31144205/223087700-e7560303-acc8-4e10-b6db-d3e42d166e94.png)

Recommended solution: I would have to research possible solutions for this one as we would have to try and make two different scenarios with different input currency and output currency somehow use a similar pattern of displaying information. No obvious solution on this one for now.

### 6️⃣ Max button in input fields in CRT trade dialogs
Issue: Because of the small gap between the max button and the currency conversion most users were reading this as "you can spend max of $xxx" - this issue can be caused by the fact that they couldn't enter their own value and it was filled for them in the prototype but we shouldn't just dismiss the fact that it was the most common interpretation of this pattern.
![image](https://user-images.githubusercontent.com/31144205/223089194-71fdd8ec-c395-463e-887a-a4ee95249f8d.png)

Recommended solution: Change the text button for a regular small button so its more obvious that this is an actionable element rather than a label for the conversion
![image](https://user-images.githubusercontent.com/31144205/223089625-b70fd47e-2f55-4cf1-89b7-f94dad63bbb4.png)
 or change the placing of this function entirely as one of the feedback from the users was that they lack the option offered by the "binance" platform to choose other % values of your current balance then only Max = 100%. There user can choose in 25% increments.
![image](https://user-images.githubusercontent.com/31144205/223090251-18b8944a-e908-4f79-8273-44ddf70571fd.png)
So it would look like this:
![image](https://user-images.githubusercontent.com/31144205/223093999-fc42dc38-45c0-4147-a33c-76fbbc6161d2.png)

### 7️⃣ Vesting explanation
Issue: Users does not know in the summary of CRT trade dialog how they will receive the funds over the vesting time: gradually or at once at the end.
![image](https://user-images.githubusercontent.com/31144205/223099532-f808acc1-05f0-40a1-9cf2-87c07f787be1.png)

Recommended solution: We need to add an explanation in the modal about the vesting and how it will be released to them after purchase.

### 8️⃣ Better explanations
Issue: Users had a problem with explanations offered for total revenue and annual reward as they didn't know all revenue sources and didn't understand how the annual reward is generated or what it means. Also some explanation is needed for items in expandable statistics.
![image](https://user-images.githubusercontent.com/31144205/223147342-f66b5eaa-6651-436e-b310-1e0fedb56a6f.png)

Recommended solution: Add sources of revenue in total revenue tooltip and work on copy for annual reward. Add tooltips for statistics.

### 9️⃣ Short description
Issue: When being directed to token page from eg. marketplace users most probably are unaware about what this token & channel is about and it was rightfully pointed out to me that we are missing a short description in the token page.

Recommended solution: We already added short description on the NFT market on CRT tiles and we wanted to add it also to the token page. - we should do just that. The best space for it would be under the token name.
![image](https://user-images.githubusercontent.com/31144205/223153283-295fce4e-299a-4e29-9656-e1f1c72abe35.png)
![image](https://user-images.githubusercontent.com/31144205/223153505-e8c7e803-8630-4483-ae08-9bfd1afa82c6.png)

**Comment by dmtrjsg** [comment]
Excellent work and useful insights, well done ⭐ 

**1. Cliff and vesting**
Agree to add cliff and vesting info as a chart with tooltip under "Buy" or if it takes too much space, present it as the very first screen (before adding how much user wants to buy).
**2. Currency coversion**
Agree with suggested approach
3. **Learn about token sale types** 
Easiest to accentuate may be also tinker with the CTA. So instead of Buy we could use Buy on Creator Sale/ Buy on Market. Or move this info to the "Token header" block above. Tooltip can further explain the two different options in the popup, with similar visuals that we use for creator but with the buyer-focused copy. 
4. **Total supply**
This one is arbitrary, and can be set up by creator so I doubt this is a better indicator (or even good enough) for driving purchasing decisions. We could explore the 2x2 layout of the token header tho. 
5. **Fees**
Fees will always be paid in JOY tokens, and we would not want to add this to the TOTAL sale scenario. I suggest to just move the fees to the very bottom.. saying You will spend X ABC + 20 JOY in Transaction Fees.
6. **Max button**
Quite like the diff % toggles 👍 . Looks good and seems effective. 
7. **Cliff and vesting explanations.** 
Id say we could add a para: "You will start getting your tokens based after your cliff passes and get full amount by the end of the vesting duration." 
8. **Tooltips**
As discussed today on the call it will be our focus for the entire journey this week. For annual reward here suggest to go with "This is a portion of channel tokens that creators receive on the annual basis and keep in their own pocket."
9. **Short description**
Nice to have our idea validated with the users 😃
