### ISSUE TITLE
(2nd round Test) Creator Tokens — Owner & Issuer

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#3726]
This includes conducting moderated usability tests on prototypes from "[My token](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=5%3A2990&t=ZRHEfgDiUXjFRLqI-1)" file (Owner & Issuer experience). The tests should cover happy path flows for:

Starting a market vs starting a sale
Creating a revenue share as a creator
The expected outcome is a brief summary of key findings, a list of recommendations, and a list of test participants to be paid out.

Depending on the results, the next step is either proceeding finalizing the designs as it is or performing necessary changes on the hi fi designs.

**Comment by KubaMikolajczyk** [comment]
# Overview
This is the final round of moderated tests which primary goal is to find out if users understand everything and are able to perform such actions as:
1. Start a market
2. Start a sale
3. Start a revenue share

# Wallets to pay
(We agreed to pay $40 worth of BCH)
- qzv9yhjnawqrmpgdcufca40nw90e3zhckuswsdu0xc
- qpqg2qwnnmwhlxhnjwtdll7acw2gwfv9cgc6jl8u23
- 12q7HrVEd2i6MkYeaUAZ1EnD36wpfUSMZ9
- qrlcs3ycwlja9vkvztclxrg5tk6rs4vllue7g0clnj

# Recordings links
Session 1: https://drive.google.com/file/d/13TDVQsBb1MUZ8W6bA7-bTbgAfUI4EDyL/view?usp=sharing
Session 2: https://drive.google.com/file/d/17x3U0Evnvxjvcs_vK6zDMSQygPYcaHBx/view?usp=sharing
Session 3:https://drive.google.com/file/d/1sR2QRWusX0PZFK0XeBxsUE2ve741iUP2/view?usp=sharing
Session 4: https://drive.google.com/file/d/1Hn5Lz33wypA4wCd5d33lRGI-I1Vnj20r/view?usp=sharing

# Key findings
### 🟢 No major issue was found. All participants were able to complete all tasks successfully.

- They knew the difference between market and sale and based on a set of questions for eg.: "You want to sell your tokens for a special price but only for a week. Would you choose sale or market?", were able to select the correct event type to perform that action
- They knew how the market works and how the sale works and what charts featured in those flows represent
- They knew what is vesting and cliff and could tell me how this would work
- They understood both market and sale pages and could successfully identify all new transactions on their sales
- They knew how to start a revenue share both from the dashboard and the revenue share page

### 🟠 The only issue spotted so far is lacking the information in some parts and the biggest problem found is in revenue share.

1️⃣ On the sale and market page one participant mentioned that it would be a lot easier for him to tell the exact difference if the "benefit" labels would be more similar to each other.
![image](https://user-images.githubusercontent.com/31144205/217840201-a11247f6-8ef5-4e49-8c42-59a4ea99f2c3.png)

2️⃣ On market summary one participant lacked additional information about how the bonding curve works as it seemed counter-intuitive that "if there is more total supply the price is higher" - even though he understood the concept itself.
![image](https://user-images.githubusercontent.com/31144205/217840323-1967ec3c-8308-4720-9503-115709f7f7e4.png)

3️⃣ On sale vesting and cliff the 3/3 participants lacked information about when the tokens are released during the vesting period: gradually or at the end?
![image](https://user-images.githubusercontent.com/31144205/217840487-a65ab561-49f6-4768-8806-53521f17649c.png)

4️⃣ On-sale page users didn't know when they will receive the revenue from the sale. We need to inform them about it.
![image](https://user-images.githubusercontent.com/31144205/217840657-959e17d0-81bf-4c37-a806-f2553aab5ba6.png)

5️⃣ When 3/3 of participants created a revenue share they were confused about where the tokens that they have withdrawn went to - as we do not offer a visual representation of the membership wallet there they were confused that their tokens disappeared. (Most of them didn't even notice the snack bar with the information that it was withdrawn to their wallet they just closed it)
![image](https://user-images.githubusercontent.com/31144205/217840830-14b14b8c-7378-4063-85ed-76952848925f.png)

6️⃣ On the revenue share page the following information was missing: where the withdrawn tokens went, what will happen with those 200 tokens if not claimed, what your holders have to do in order to receive their share, can they stake any amount that they want of your token or do they have to stake all they have
![image](https://user-images.githubusercontent.com/31144205/217840929-e631db82-1a91-4145-981b-3671c09a685e.png)

7️⃣ 2/4 participants didn't know how the market works - they thought that people will be providing liquidity to the liquidity pool. I had to explain that it is not how it works here - they lacked an explanation about it.
![image](https://user-images.githubusercontent.com/31144205/218266586-d0ffa167-6d67-4e42-87aa-6035b2d0c8e0.png)

**Comment by dmtrjsg** [comment]
Great stuff man, thanks for sharing the early insights!

Few comments on the above: 

> the "benefit" labels would be more similar to each other.

what do you mean here exactly?

>  bonding curve works as it seemed counter-intuitive

A tooltip with broader context would probably be useful. @ignazio-bovo are we planning to add anything more detailed wrt bonding curve specifics to the handbook? Didn't find this when checked gitbook: https://handbook.joystream.org/system/projecttoken

> when the tokens are released during the vesting period: gradually or at the end?

Worth adding a sentence covering exactly that to the small para description before the param set up. I'm actually not sure myself what the dynamics there from the top of my head. 

> Most of them didn't even notice the snack bar with the information that it was withdrawn to their wallet they just closed it)

Confirmation popup with Ok I acknowledge would be appropriate?

> where the withdrawn tokens went, what will happen with those 200 tokens if not claimed, what your holders have to do in order to receive their share, can they stake any amount that they want of your token or do they have to stake all they have

Great insight, we should def address that 👍

**Comment by bedeho** [comment]
Fantastic work!

Are we allowed to publish these videos? they were really interesting, perhaps we can ask the folks if they are ok with that? Same goes with you a well of course, just let me know.

**Comment by dobertRowneySr** [comment]
> A tooltip with broader context would probably be useful. @ignazio-bovo are we planning to add anything more detailed wrt bonding curve specifics to the handbook? Didn't find this when checked gitbook: https://handbook.joystream.org/system/projecttoken

You mean having explicitly written that: the more the supply the higher the price?

**Comment by dmtrjsg** [comment]
@ignazio-bovo sorry I thought there's more to it :) I guess not relevant if that's as easy as that and no parameters / limits are in play.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg 
>the "benefit" labels would be more similar to each other.

>what do you mean here exactly?

I was told that it would be much easier to compare something of more similar meanings eg. Low risk vs High risk or Easy vs complex - Im not saying that those words fit in our scenario because they don't but the thought behind this was to make the benefits more similar in meaning so those will be easier to understand as eg. Direct revenue / Liquidity cannot be compared easily.

> Worth adding a sentence covering exactly that to the small para description before the param set up. I'm actually not sure myself what the dynamics there from the top of my head.

Im almost sure its gradually :) If my memory is not failing me.

> Most of them didn't even notice the snack bar with the information that it was withdrawn to their wallet they just closed it)

> Confirmation popup with Ok I acknowledge would be appropriate?

We can try something like that

@bedeho 

Thank you! If it comes to me I don't have anything against sharing my image but Im worried that we are not allowed to publish them as when asking for recording permission we always stated that it's for internal purposes only. We can ask them for permission if you feel there is a value in sharing those sessions but I see a big chance they will decline as those folks care about their privacy a lot. wdyt?

**Comment by bedeho** [comment]
> care about their privacy a lot. wdyt?

ok, lets skip then :)

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg I created a video update to show you all of the solutions for the problems highlighted in this issue ✅

🎥 Video update: https://www.loom.com/share/44d53024b0fb40c18d60644bd013985d?sid=6adad61e-39cb-419d-b378-322475fe2c85

**Comment by dmtrjsg** [comment]
### Copy link to sale
I think having it as a primary CTA would be best for adoption.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @WRadoslaw all of the changes are implemented into final designs - everything is described with visuals in the changelog ✅

📄 My token changelog: https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=2861-30458&mode=design&t=PHsACZPBQKWECDDC-4
