### ISSUE TITLE
Update ImageCropDialog with latest design

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#373]
Some design changes has been made to the `ImageCropDialog`:
- zoom in/out icons should be updated and should now be clickable to allow adjustment of zoom (@eldiegod 😛)
- updated overlay color and overlay border color

**Comment by eldiegod** [comment]
haha, it just made sense 🤷‍♂

**Comment by kdembler** [comment]
it did, but now we have new icons for that and proper support in the button component so it was worth the wait I guess 😏
