### ISSUE TITLE
Toaster notifications need to disappear after few seconds

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3737]
## Context

Toaster notifications
![Screenshot 2023-02-07 at 18.59.04.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/221cc109-f2e7-4e54-9653-512b3ce46be3)

## Scope

- [ ] Or error/ success and other cases need to disappear automatically after 4 seconds

**Comment by drillprop** [comment]
Fixed, and set snack bar timeout to 5 seconds as the design requires https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=4606%3A140987&t=Wfs9GeZgHIK8moy2-4
