### ISSUE TITLE
Payments: Claimable balance issues

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3738]
Instance: https://atlas-git-ypp-joystream.vercel.app/
Env: Atlas-next

Tested on channelID= 2

`Link to tx: https://polkadot.js.org/apps/?rpc=wss://atlas-dev.joystream.org/ws-rpc#/explorer/query/0xe1a538b7ab7c5aea15b15039a50170a426ca52b6641671a83335da06d9ad6b3a`

Issues:
1. Claimable balance did not get reduced after claimed
![Screenshot 2023-02-07 at 19.36.16.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/716148db-baf0-4b33-b020-5b4b946a26a1)

2. On second attempt erroneous limit exceeded message was displayed in toaster: 
![Screenshot 2023-02-07 at 19.30.56.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/816c0392-526d-4b68-8263-f02ff8dca87a)

____

updated claim limit to 36k and tried again with different account: channelId=1

`LInk to tx: https://polkadot.js.org/apps/?rpc=wss://atlas-next.joystream.org/ws-rpc#/explorer/query/0x51f5ebb9a6833775986deb1123a69ae50b06355465bd314919dd47cccc2c035b`

1. Claimable balance did not reduce after claiming

<img width="1430" alt="Screenshot 2023-02-07 at 19 44 00" src="https://user-images.githubusercontent.com/93924525/217293010-618b2671-be12-49ad-bb9b-0629b0ffdaab.png">

2. Second attempt gave me "smth went wrong"

<img width="1498" alt="Screenshot 2023-02-07 at 19 45 08" src="https://user-images.githubusercontent.com/93924525/217292925-7d11140e-7bc2-450f-96c2-a2c327104fbe.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203921714827766) by [Unito](https://www.unito.io)

**Comment by drillprop** [comment]
This was a QN bug, and it's already fixed here https://github.com/Joystream/joystream/pull/4594. 

To make this work on the atlas side we need to update the atlas-next environment
