### ISSUE TITLE
[USERSNAP] I expect to be able to change thumbnail path since it was not set yet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3745]
**Sender**: disgaea.top@gmail.com
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: I expect to be able to change thumbnail path since it was not set yet
- Houston, we have a problem.: seems that issue was with `Thumbnail image`, an error occured during upload and I cannot re-upload new one since video was minted as NFT

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/29ca8220-4706-43cc-910a-7d421b0e468c-annotated_299c4d18-6a74-4517-84fd-1c2b1310058f.png?etag=1a08c28d9eac787f45865961dcaac4c8)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/29ca8220-4706-43cc-910a-7d421b0e468c-annotated_299c4d18-6a74-4517-84fd-1c2b1310058f.png?etag=1a08c28d9eac787f45865961dcaac4c8)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 2560x1440
**Browser size**: 2560x1297
**[Open #28 in Usersnap](https://app.usersnap.com/l/feedback/5607d4ab-bf0c-4800-b0f0-8ea236de8a2d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Let's put it on ice before we get more data to validate the tradeoff of avoiding this rare bug and removing the option to mint NFT in the same tx that uploads a video (as that is the only way to really prevent this again from happening)

**Comment by bedeho** [comment]
1. Why do you say there is a tradeoff here?
2. I do believe all the user has to do here is just manually retry the upload, which should work even if an NFT has been minted.
3. The main problem here is that the user is not really instructed to do anything to fix it, they are just told there is an error.
4. I believe we will soon have Orion assisted uploads, which totally solves this problem, so I'm not sure its worth doing much in the interim to fix this, also as most publishers will use YPP, not Atlas studio, to publish.

**Comment by dmtrjsg** [comment]
@bedeho 

> which should work even if an NFT has been minted.

Afaik there's no way to update any assets for the NFT, including the thumbnail.

> main problem here is that the user is not really instructed to do anything to fix it

There's a toaster notification which takes user to the uploads, but this cannot be done for NFTs :<

> so I'm not sure its worth doing much in the interim to fix this

OK let's keep it in the icebox, I think this problem is really really rare.. 


cc @attemka @drillprop

**Comment by bedeho** [comment]
> Afaik there's no way to update any assets for the NFT, including the thumbnail.

The problem is not _changing_ the asset on the blockchain side - which is where the NFT based immutability is enforced, its about actually successfully uploading the asset to some initial storage provider, after already having made accomodations for it on-chain with the initial upload.

**Comment by dmtrjsg** [comment]
I understand this conceptually but am not sure if that's how App is built wrt to this use case rn, so @attemka and @drillprop pls chime in.

**Comment by bedeho** [comment]
If I am not mistaken, and an asset associated with a video with a minted NFT still allows for uploading the video to a storage provider until it has been accepted on chain, then the user just needs to go to the upload screen to complete the upload, probably be reproviding the same asset.

Problem here is user does not understand this is what they are supposed to do.

**Comment by dmtrjsg** [comment]
This will be solved in:
- https://github.com/Joystream/atlas/issues/3745

cc @bedeho
