### ISSUE TITLE
[USERSNAP] NFT here https://gleev.xyz/video/442 Buy now price is 2.5K, I use Talisman, and Im logged in. When I click buy now on the purchase screen, it disables the button and nothig happens. I don't see a signer dialog open. My hunch is that it is som...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3746]
**Sender**: None
**Taken at**: https://gleev.xyz/video/442
**Fields**:
- Expected Result: NFT here https://gleev.xyz/video/442
Buy now price is 2.5K, I use Talisman, and Im logged in. When I click buy now on the purchase screen, it disables the button and nothig happens. I don&#39;t see a signer dialog open. My hunch is that it is somehow due bug in the interaction between signer and app, e.g. signer nott showing or sometthing, but I am not sure.
- Houston, we have a problem.: Trying to use buynow

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/630051fb-42fa-41c7-a9cc-29fa7454ef2e-annotated_10395afa-4412-4d6d-a565-c960c474ad65.png?etag=941cde1e39573975e5d37bdb157740bc)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/630051fb-42fa-41c7-a9cc-29fa7454ef2e-annotated_10395afa-4412-4d6d-a565-c960c474ad65.png?etag=941cde1e39573975e5d37bdb157740bc)*

**Browser**: Firefox 109 (macOS Catalina)
**Screen size**: 1680x1050
**Browser size**: 1486x855
**[Open #29 in Usersnap](https://app.usersnap.com/l/feedback/887567d3-a4b2-4162-b76f-edc1c1fd27ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by attemka** [comment]
@WRadoslaw please try to reproduce and close as done if its already fixed an atlas side

**Comment by WRadoslaw** [comment]
Couldn't reproduce
