### ISSUE TITLE
Update T&Cs styling

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3754]
## Context

Finalising T&Cs

## Scope

- [ ] Update headers structure to 

h1: Terms & Conditions
h2: Key Information; YPP
h3: Section headers

- [ ] Two diff font sizes used in markup and Tiers component 14/16px.  Needs to be 16 everywhere.

___________

✅ Already merged in a separate pR:
- [ ] Make hyperlinks clickable: 
![image](https://user-images.githubusercontent.com/51168865/217753536-6c6c7e11-5de5-49b6-a7d2-e660cdd09433.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203935643509260) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@WRadoslaw hey sorry to jump in, but there was also the point about the headers sctructure we discussed on the standup that was meant to go to the same issue 😬 

I am also awaiting Zeeshan's confirmation re mandatory scopes, and if confirmed we may need to update the YT sync subsection. This is now pending, based on the outcome of: 
- https://github.com/Joystream/youtube-synch/issues/144
