### ISSUE TITLE
Authorised wallet needs to be stored in the local storage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3758]
## Context

Follow up on: 
-  https://github.com/Joystream/atlas/issues/3641

This also happens on Chrome. 

We need to ensure this is correctly implemented on all browsers that support polkadot wallets

FF
Chrome
Arch
Brave

## Scope
AR:
Open new window on crhome
App asks you to connect wallet
Clicking on Polkadot shows eternal spinner
![Screenshot 2023-02-09 at 19.53.28.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/bbb5c89c-42b7-44ce-ad28-2eb078113372)
After page reload wallet is connected with prev account used

ER: 
After the wallet was once authorised with the browser, the app does not ask to connect wallet, but shows the latest used member or invites to create membership for guest users

**Comment by drillprop** [comment]
I refreshed gleev 10 times on firefox and chrome and I can't reproduce this at all. Did you create this issue after the release or before the release?

**Comment by dmtrjsg** [comment]
Resolved, could not reproduce.
