### ISSUE TITLE
Synced videos still appearing as failed videos

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3762]
As the title says. 

Video tiles with variant `auto-sync` are displayed for a few seconds and then, once the video is uploaded, the tiles are marked as `upload failed`. 

After the page refresh tiles are correct - i.e. they have status uploaded and you see the correct thumbnail and you can watch the video.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203945359351603) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
Sorry to say this but, failed uploads are displayed each time I am trying with new videos:

<img width="1268" alt="Screenshot 2023-02-16 at 15 07 49" src="https://user-images.githubusercontent.com/93924525/219349651-e7117acd-8980-4f64-88e3-e0a350e0d3fa.png">


<img width="627" alt="Screenshot 2023-02-16 at 15 06 46" src="https://user-images.githubusercontent.com/93924525/219349623-96bd4582-4768-44ff-a425-7d6edef47091.png">

**Comment by dmtrjsg** [comment]
@attemka 
Thumbnail still shows as upload failed: 🟥 
That's the video: https://dev.gleev.xyz/video/168 < is it possible to see if that as due to the bug of assigning videoIDs?
