### ISSUE TITLE
How to get Featured Banner UI Work

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3778]
## Context
- https://github.com/Joystream/atlas/issues/3686

## Scope
- Section banner and copy
- The “How to get featured?” banner should be displayed only for users with a connected Joystream membership account to which a channel is assigned 
- Flow w preview of thumbnail  
- Conf toaster for success and "You can only request to feature NFTs that belong to your channel"
- Can be closed with x

## Design

[link >](https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace-page?node-id=478%3A206508&t=TO7oWuZTnWUYZ7pM-1

Preview
<img width="790" alt="Screenshot 2023-02-13 at 12 07 35" src="https://user-images.githubusercontent.com/93924525/218403754-afd00ae8-8a8c-4167-a66b-7aca941bd42e.png">

**Comment by attemka** [comment]
duplicates #3783
