### ISSUE TITLE
All NFTs filters and sorting

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3781]
## Context
- https://github.com/Joystream/atlas/issues/3686

## Scope

Filters: 
- Last price (cursor focus on min)
- Status
- Other filters
- Clear filters

Sorting: 
- newest / oldest

## Design
[Link to figma> ](https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace-page?node-id=472%3A97553&t=TO7oWuZTnWUYZ7pM-1)

Preview
<img width="760" alt="Screenshot 2023-02-13 at 12 21 47" src="https://user-images.githubusercontent.com/93924525/218406914-2c98ba61-6f93-450a-b8cb-146817bfb443.png">

**Comment by attemka** [comment]
closed as duplicate of #3780
