### ISSUE TITLE
Problem when Accept T&Cs clicked twice

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3789]
To be triaged

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203975393536961) by [Unito](https://www.unito.io)

**Comment by drillprop** [comment]
What about something like this? 

https://user-images.githubusercontent.com/51168865/219006712-11d39edf-048a-4e2b-9c00-13e864e38822.mov
