### ISSUE TITLE
Token Start Market Flow UI

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3797]
## Context

- https://github.com/Joystream/atlas/issues/3384

## Scope
- Starting Market Screen One 
-- Price input
-- T&Cs
-- Token widget preview (incl total supply)
- Summary Screen

🚫  Out of scope: 
- Token widget fiat denomination
- Chart
- Submit tx

## Designs

[link> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=817%3A108160&t=KiTZ2klK5CxMQJBl-1)

Preview: 
<img width="835" alt="Screenshot 2023-02-15 at 18 27 23" src="https://user-images.githubusercontent.com/93924525/219055290-c1c7f810-cfb4-4763-b35f-4f44c47ad246.png">

<img width="867" alt="Screenshot 2023-02-15 at 18 32 08" src="https://user-images.githubusercontent.com/93924525/219056516-81a9a75a-1950-4de1-b24c-6ec14fa15098.png">

**Comment by polikosi** [comment]
- Starting Market Screen One

1. On the first page shoudn't be a chart. I expected to see the "price per unit".
2. When I enter a negative number in the price field, the page crashes.
3. T&Cs  text does not match the design.

- Summary Screen
1. Add text above the graph that describes it


![image](https://github.com/Joystream/atlas/assets/80429191/afa39c88-b791-4965-9b74-fbc8b53f99d2)
![image](https://github.com/Joystream/atlas/assets/80429191/cb948ff2-d585-4ecd-8055-78b8ea1b469b)

https://github.com/Joystream/atlas/assets/80429191/373c7f28-32cb-48b1-bde4-9da1d619e2b6
