### ISSUE TITLE
Token Start Market flow Chart

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3798]
## Context

- https://github.com/Joystream/atlas/issues/3384

## Scope
- Chart
⚠️ Chart needs to be a straight line, where A is the slope:
<img width="572" alt="Screenshot 2023-02-15 at 18 36 49" src="https://user-images.githubusercontent.com/93924525/219058619-aeed4c21-e8ef-42de-81bc-bfcfd4f3ce5f.png">

BE required

## Designs

[link> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=1219%3A159180&t=KiTZ2klK5CxMQJBl-1)

Preview: 
<img width="660" alt="Screenshot 2023-02-15 at 18 34 26" src="https://user-images.githubusercontent.com/93924525/219058599-25cb3ee5-225d-4518-be2e-90e106f82dd6.png">

**Comment by polikosi** [comment]
![image](https://github.com/Joystream/atlas/assets/80429191/546c3842-d0a3-4ffd-b5ea-97da505e3d8b)

**Comment by dmtrjsg** [comment]
@WRadoslaw I believe in this issue the following points would need to be finalised:

- chart title missing "how token price rises with growing total supply"
-  Y axis scale is a bit off (ideally needs to be 1k / 4k rounded up to full thousands.)
-  tooltip on chat hover is missing
