### ISSUE TITLE
Token Market Tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3802]
## Context

- https://github.com/Joystream/atlas/issues/3384
⚠️  The price depends on the bonding curve, 

## Scope
- Transactions Table
- Widgets
Current Price
Bought
Sold

## Design
[Link to Figma > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=840%3A110381&t=KiTZ2klK5CxMQJBl-1)

Preview: 
<img width="765" alt="Screenshot 2023-02-15 at 19 03 36" src="https://user-images.githubusercontent.com/93924525/219065412-18f10631-ff6e-4992-a372-7721a0e551b4.png">

<img width="811" alt="Screenshot 2023-02-15 at 19 04 28" src="https://user-images.githubusercontent.com/93924525/219065614-afc5baaf-ea51-44f5-9d0c-9cbda0602e52.png">

**Comment by polikosi** [comment]
I can't see the Market and Settings pages soso I can't see the transaction table, the row of widgets and the market transaction table
![image](https://github.com/Joystream/atlas/assets/80429191/7389963f-ae14-43ca-a761-3f35cabf52be)

**Comment by polikosi** [comment]
I don't see the message that I have successfully launched the market at the bottom of the page

**Comment by WRadoslaw** [comment]
> I don't see the message that I have successfully launched the market at the bottom of the page

Snackbars were deprecated in favor of success modal
![image](https://github.com/Joystream/atlas/assets/92513933/6185d780-8ed8-4816-902d-cff3fcaa352e)
