### ISSUE TITLE
Token Close Market Token Sale

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3804]
## Context

- https://github.com/Joystream/atlas/issues/3384

## Scope

- [ ] Close the market flow

⚠️ Closing the market requires mapping of the THRESHOLD param, which will be stored on Chain. 

[link to gitbook> ](https://handbook.joystream.org/system/projecttoken#amm)
NB: The AMM Sale can be finally closed at any given time by the Issuer provided that the following condition holds:  Where THRESHOLD is a governance-set percentage. Notice that if THRESHOLD = 0 then every token minted through the AMM must be also burned for the AMM sale to be closed.

## Design
[LInk to figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=817%3A108181&t=pi68hEmU37cQPyyw-1)

<img width="625" alt="Screenshot 2023-02-15 at 19 23 16" src="https://user-images.githubusercontent.com/93924525/219071162-e0b436da-968a-48b4-945b-e2992bd61a54.png">

[Link> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=817%3A108188&t=pi68hEmU37cQPyyw-1)

<img width="420" alt="Screenshot 2023-02-15 at 19 27 34" src="https://user-images.githubusercontent.com/93924525/219072538-d436e3ff-0662-4382-8889-7b3581c2bbf3.png">

**Comment by polikosi** [comment]
I expected to see the name of my token here - TK4.
I can also close the market, although I don't have enough tokens to do so.
![image](https://github.com/Joystream/atlas/assets/80429191/58b496e2-bd70-461e-917b-b56af0b67578)
