### ISSUE TITLE
Token Market: Dashboard Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3805]
## Context

- https://github.com/Joystream/atlas/issues/3384

## Scope

- [ ] Dashboard widget for Marketplace

## Design
[Link to figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=862%3A119296&t=pi68hEmU37cQPyyw-1)

Preview: 
<img width="842" alt="Screenshot 2023-02-15 at 19 28 35" src="https://user-images.githubusercontent.com/93924525/219073010-bed6a57e-9f79-429a-80cd-b4529c1b1b49.png">

**Comment by polikosi** [comment]
blocked https://github.com/Joystream/atlas/issues/3802#issuecomment-1825578563

**Comment by polikosi** [comment]
Change "Show sales" to "Show market" as I launched the market, not sales
![image](https://github.com/Joystream/atlas/assets/80429191/8afc7d61-4478-49c7-a737-4cda1c5b7053)
