### ISSUE TITLE
Token Market: Notifications

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3806]
## Context

- https://github.com/Joystream/atlas/issues/3384

## Scope
Notification when tokens bought or sold on AMM

- [ ]   When clicked the user should be moved to the market tab on my token page where they can inspect the new purchase

## Design
[Link to Figma> ](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=1808%3A56000&t=p9dWoECe0cvKOxe0-1)

<img width="919" alt="Screenshot 2023-02-15 at 19 31 57" src="https://user-images.githubusercontent.com/93924525/219073916-90a4bca0-2e8d-48f6-aa2f-620073cb5b65.png">

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg Issuer notifications are ready to be reviewed ✅

🎥 Video update (1:30, really short explanation of all new notifications): https://www.loom.com/share/9c495dcd7b9e40da86a9738d1f6b9253?sid=fdbe3acc-141d-40a2-8fab-f2566c7686ed

📄 Notifications events changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2476-81271&mode=design&t=pgqmuSktkmpn8ROv-4

📄 My channel settings changelog: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=2029-83165&mode=design&t=oRLghr3FVsaJTjCw-4
