### ISSUE TITLE
Upload failure management

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#381]
# Background

Uploads, that is the act of putting a local copy of some media onto the storage system, is an indepenent action from publishing content, and it is subject to various failure modes. The goal of this issue is to describe how we could handle these failures in Atlas. 

# Proposal

The following state machine diagrams for the product state shows how should be displayed for every possible state and event.

## My Uploads scene

![Screenshot 2021-03-15 at 19 04 16](https://user-images.githubusercontent.com/437292/111200121-af3b1800-85c1-11eb-93db-ecf73ef011a6.png)

## Individual assets

![asset_component(1)](https://user-images.githubusercontent.com/437292/111277820-25c72c80-8639-11eb-887d-ee7a9f35d5be.png)

**Comment by kdembler** [comment]
Looks good to me, should handle all the cases I think. One thing worth noting I think is that in the `Internet available variation` if the host _is_ reachable and the assent _isn't_ available, then the file needs to be exactly the same as before, otherwise a new transaction will need to be created

**Comment by bedeho** [comment]
> Looks good to me, should handle all the cases I think. One thing worth noting I think is that in the Internet available variation if the host is reachable and the assent isn't available, then the file needs to be exactly the same as before, otherwise a new transaction will need to be created

Yes so the label `User picks valid file` could be changed to `User picks same file` to be a bit more clear.

**Comment by bedeho** [comment]
# Fungible upload hosts version

![asset_component](https://user-images.githubusercontent.com/437292/111763158-172f7e00-88a2-11eb-9be7-eac92aec0e63.png)
