### ISSUE TITLE
Orion manual test script

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3821]
**URL for testing**: https://atlas-324y6vv7p-joystream.vercel.app/
The URL is only temporary, In the future, we will use something like https://atlas-git-orion-2-joystream.vercel.app/ . For now please check if the URL for testing didn't change, before doing the test. I'll update this, once there will be new changes. 

Make sure that the environment is set to `Atlas dev testnet`.  It should be set by default, but it's worth checking. 

**Grapqhl playground for testing**: [https://194.233.167.225.nip.io/orion/graphql](https://194.233.167.225.nip.io/orion/graphql) or https://atlas-dev.joystream.org/query-node/server/graphql but you need to setup the URL(instructions in the next section below)

**Dev environment for comparison purposes**: [https://atlas-git-dev-joystream.vercel.app/](https://atlas-git-dev-joystream.vercel.app/)  **Important note:** views and follows count will be different than in the Orion v2 environment 

## Instructions on how to use operator mutations

******************************************Setup your playground******************************************

1. First, go to [https://atlas-dev.joystream.org/query-node/server/graphql](https://atlas-dev.joystream.org/query-node/server/graphql), change the URL in the URL input to [https://194.233.167.225.nip.io/orion/graphql](https://194.233.167.225.nip.io/orion/graphql)

![image](https://user-images.githubusercontent.com/51168865/220332625-3e29a27c-7052-461d-a084-818a49921e42.png)

1. Open headers at the bottom. And paste: 

```jsx
{
  "x-operator-secret": "ask-me-for-password"
}
```

After setting this up you should be able to run the following mutations(replace the input inside the chevrons `< >`) : 

- **********Exclude/restore content**********

Exclude

```jsx
mutation {
  excludeContent(type:<write here Channel, Video, or Comment>, ids: [<ids that needs to be excluded here>]) {
    numberOfEntitiesAffected
  }
}
```

Restore

```jsx
mutation {
  restoreContent(type:<write here either Channel, Video or Comment>, ids: [<ids that needs to be restored here>]) {
    numberOfEntitiesAffected
  }
}
```

- **************************************************Set supported categories**************************************************

```jsx
mutation {
  setSupportedCategories(
    supportedCategoriesIds: [<categories taken from QN>],
    supportNewCategories: false,
    supportNoCategoryVideos: false
  ) {
    newNumberOfCategoriesSupported
    newlyCreatedCategoriesSupported
    noCategoryVideosSupported
  }
}
```

- **Set video view per ip limit**

This mutation changes how often a certain user can add a video view. 

```jsx
mutation {
  setVideoViewPerIpTimeLimit(limitInSeconds: < limit in seconds > ) {
    limitInSeconds
  }
}
```

- **Set kill switch**

Go to maintenance mode

```jsx
mutation {
  setKillSwitch(isKilled: true) {
    isKilled
  }
}
```

- **Set video hero**
Video poster and video cut, should be uploaded to some external service - currently, we're using Linode
```jsx
mutation {
  setVideoHero(videoId: <QN video id>, heroTitle: <hero title>, videoCutUrl: <URL of video>, heroPosterUrl:<URL to video poster or thumbnai>) {
    id
  }
}
```

- **********************************************Set category featured videos**********************************************

videos should receive an array of videos, that contain id of the video(taken from QN) and videoCutUrl - URL to this video. Video cut should be uploaded to some external service - currently, we’re using Linode. 

```jsx
mutation {
  setCategoryFeaturedVideos(categoryId:<category id taken from the atlas config>, videos: [{
    videoId: <video id>
    videoCutUrl: <video cut URL>
  }]) {
    categoryId
    numberOfFeaturedVideosSet
    numberOfFeaturedVideosUnset
  }
}
```

# Viewer

## Homepage

**************Top bar - notifications**************

******As a user, I want to see that someone bid on my NFT****** 

- [x]  I see the correct date
- [x]  I see the correct video title
- [x]  I see the correct user
- [x]  I see the correct amount

****As a user, I want to see that someone outbid me****

- [x]  I see the correct date
- [x]  I see correct video title
- [x]  I see the correct user
- [x]  I see the correct amount

****As a user, I want to see that someone has accepted my bid in open auction****

- [x]  I see the correct date
- [x]  I see the correct video title
- [x]  I see the correct user
- [x]  I see the correct amount

****As a user, I want to see that my auction has been settled****

- [x]  I see the correct date
- [x]  I see the correct video title

****As a user, I want to see that the auction I have won has been settled****

- [x]  I see the correct date
- [x]  I see the correct video title

*As a user, I want to see that the _open_ auction I participated in has ended*
- [x]  I see the correct date
- [x]  I see the correct video title

🆕 *As an auction participant, I want to see that the _timed_ auction I participated in has ended*
~- [ ] 🔴 As winner I see the auction has ended and I need to settle~ 
~- [ ] 🔴 As nft original owner I see the auction has ended and winner needs to settle the auction~
Edit: this was never supported either in orion v2 or in orion v1

- [x] 🔴 As losing bidder I see the auction has ended and I can withdraw my bet

Edit: This one should work on open auctions. I receive the correct notification. You don't need to withdraw a bet in an English auction

*As a user, I want to see that someone commented on my video* 

- [x]  I see the correct date
- [x]  I see the correct video title
- [x]  I see the correct user
- [x]  I can go to this comment by clicking the notification

*As a user, I want to see that someone replied to my comment* 

- [x]  I see the correct date
- [x]  I see the correct video title
- [x]  I see the correct user
- [x]  I can go to this comment by clicking the notification

******Top bar - search****** 

- [x]  As a user, If I type something in search input I’ll see three suggested results for video and three suggested results for the channel. **Small note** - it should work the same as in orion v1, we didn’t improve searching queries yet.
- [x]  When I press enter after a search I should be redirected to the search page and I should see the correct videos and channels.  **Small note** - it should work the same as in orion v1, we didn’t improve searching queries yet.

********************Video hero********************

- [x]  As a user, I can see a video hero placeholder with generated text
- [x]  As a user, I can see video hero when it’s set
- [ ]  ⚠️ (blocked) As a gateway operator, I can set video hero on the homepage

******Popular on Atlas******

- [x]  As a user, I see correctly `popular on atlas` section.
- [ ]  🔴 (🐞 described in comments) The videos in the section should show the 24 most viewed videos from the last 7 days

**New NFTs on sale**

- [x]  As a user, I see correctly `New NFTs on Sale` section.
- [x]  I should see recent open auctions
- [x]  I should see recent buy-now auctions
- [x]  I should see recent english auctions

**********************************Top 10 this week**********************************

- [x]  As a user, I see correctly top watched videos this week

********************************************Discover new channels******************************************** 

- [x]  As a user I see channels that have at least 4 videos
- [ ]  🔴 As a user, I see *a* list of 15 most followed channels out of 100 newest channels in random order(the order should change once you refresh)
- [ ]  🔴 I can follow the channel
- [ ]  🔴 I can unfollow the channel

**********************All content**********************

- [x]  As a user, I should see all content sorted by created date, descending
- [x]  When I click to show more videos, it should load the next videos correctly

## Popular

********Top 10 videos this month********

- [x]  As a user I should see the top 10 videos this month, sorted by views count(from this month)

**********************************Popular videos**********************************

- [ ]  🟡 As a user, I should see a list of 50 the most viewed videos, sorted by date creation

**********************************Popular channels**********************************

- [x]  As a user, I should see a list of the 15 most watched channels in random order
- [ ] 🟡  I should see only channels that have at least 4 videos

## Video NFTs

- [x]  As a user, I can sort by newest, and oldest
- [x]  As a user, I can see the correct number of NFTs
- [x]  As a user, I can see the correct number of pagination buttons
- [x]  As a user, I can filter NFTs by status, by selecting one checkbox,  and the NFTs number is displayed correctly and I see the correct results
- [x]  As a user, I can filter NFTs by status, by selecting multiple checkboxes,  and the NFTs number is displayed correctly and I see the correct results
- [x]  As a user, I can filter NFTs by date minted, and the NFTs number is displayed correctly and I see correct results
- [ ]  🔴 As a user, I can filter NFTs using other filters, and the NFTs number is displayed correctly and I see correct results
- [ ]  🚫 (blocked) As a user, I can use combined filters - status, date minted, and other filters, and the NFTs number is displayed correctly and I see correct results

## New & Noteworthy

**Recently uploaded**

- [x]  As a user, I see recently uploaded videos

********************************************Promising new channels********************************************

*As a user I see:* 

- [ ]  ⏯️  (to retest on prod) a list of the 15 most watched channels out of 100 newest channels in random order
- [x]  channels that have at least 4 videos

## Discover
- [ ]  🔴 As a user, I  see the correct number of videos of categories.
- [ ]  🔴  As a user, I see the categories chart displayed correctly(this one 👇)

![image](https://user-images.githubusercontent.com/51168865/219316594-5609a208-f2f9-471c-9938-51d4f7e6b92f.png)

## Channels

******************************Top 10 channels******************************

- [ ]  🚫 (blocked) As a user, I  see the correct ten most followed channels.

********************************************Discover new channels******************************************** 

*As a user I see:* 

- [x]  channels that have at least 4 videos
- [x]  list of 15 most followed channels out of 100 newest channels in random order(the order should change once you refresh)

**Channels in your language**

- [x]  As a user, I can change channel language
- [ ]  🔴 As a user, I see channels that have at least 1 video
- [x]  As a user, I see channels that are ordered by creation date
- [x]  As a user, I see `No channels found` when there are no channels in my language with at least one video

## Category view

************Video hero************

- [x]  As a user, I see featured category video when it’s set
- [ ]  As a gateway operator, I can feature category videos

**All videos**

- [x]  As a user, I see the correct number of videos
- [x]  As a user, I see I can sort all videos by creation date
- [ ]  🔴  As a user, I can change language and I see videos in this language, and the correct number of videos
- [x]  As a user, I can apply the date uploaded filter and I see the correct videos and the correct number of videos
- [x]  As a user, I can apply a date length filter and I see the correct videos and the correct number of videos
- [ ]  🔴 As a user, I can apply other filters and I see the correct videos and the correct number of videos
- [ ]  🔴 As a user, I can combine different filters and I see the correct videos and the correct number of videos

## Profile view

****************************Nfts owned tab****************************

- [x]  As a user, I see the correct number of NFTs in the badge of the NFTs owned tab
- [x]  As a user, I can sort NFTs by date of creation
- [x]  As a user, I can sort NFTs by status

************Activity************

- [x]  As a user, I see the member listed an NFT. The date, thumbnail, and member are correct.
- [x]  As a user, I see the member removed NFT from sale. The date, title, thumbnail, and member are correct.
- [x]  As a user, I see the member minted NFT. The date, title, thumbnail, and member are correct
- [x]  As a user, I see this member placed a bid. The date, title, amount, thumbnail, and member are correct
- [x]  As a user, I see that another member placed on bid on NFT from this member. The date, title, amount, thumbnail, and member are correct
- [x]  As a user, I see the member purchased an NFT. The date, title, amount, thumbnail, buyer, and seller are correct
- [x]  As a user, I see the member sold an NFT. The date, title, amount, thumbnail, buyer, and seller are correct
- [x]  As a user, I see the member withdrew his bid. The date, title, thumbnail, and member are correct
- [x]  As a user, I see the member change price. The date, title, amount, thumbnail, and member are correct

******************Overview******************

- [x]  As a user, I see the correct number of NFTs bought
- [x]  As a user, I see the correct number of NFTs sold
- [x]  As a user, I see the correct number of NFTs created
- [x]  As a user, I see the correct number of bids placed

## Channel view

- [x]  As a user, I see the correct members in the “NFTs collected by” widget
- [x]  As a user,  I can sort videos by date
- [x]  As a user, I can sort NFTs by date
- [x]  As a user, I can apply a status filter to the NFTs tab, and I see the correct NFTs
- [x]  As a user, I see the correct number of views in the Information tab
- [x]  As a user, I see the correct number of videos in the Information tab
- [x]  As a user, I can follow and unfollow the channel
- [x]  As a user, I see the correct number of followers
- [ ]  As a user, I can report the channel

## Video view

******Video and video details******

- [ ]  As a user, I see the correct views number, and the views are increasing, when I play the video.   ************************Important note:************************ since orion v2, adding views is limited by IP. You can only add one view for 5 seconds per video. The time frame could be tweaked by the operator by running the `setVideoViewPerIpTimeLimit` mutation.
- [ ]  As a user, I can report the video
- [x]  As a user, I can follow and unfollow the channel

****************Comments****************

- [x]  As a user, I see the correct number of comments
- [x]  As a user, I see correctly my reactions on comments(highlighted)
- [x]  As a signed user, I can edit my comments and see comment edit history correctly, when I click the `edited` label
- [x]  As a signed user, I see my comments(that’s not a reply) on the top

*As a user, I can sort comments by*

- [ ] 🔴  most popular
- [x]  newest
- [x]  oldest

********************Nft widget********************

- [x]  As a user, I see the correct channel under **`This NFT is owned by`**

**********************Nft history**********************

- [x]  As a user, I see the member minted the NFT
- [x]  As a user, I see the member put NFT on sale(buy now).
- [x]  As a user, I see the member put NFT on auction
- [x]  As a user, I see the member withdrawn the bid
- [x]  As a user, I see the member placed the bid
- [x]  As a user, I see the member won the auction
- [x]  As a user, I see the member bought the nft
- [x]  As a user, I see the member removed the auction from sale
- [x]  As a user, I see the member changed the price of buy now auction

**********************************More from channel**********************************

- [x]  As a user, I see videos from the channel

****************************More in category****************************

- [x]  As a user, I see more videos from the same category

## Gateway operator filters - config

```yaml
blockedDataObjectIds: [] # Array of data object IDs that should be blocked from being displayed in the app
blockedVideoIds: [] # Array of video IDs that should be blocked from being displayed in the app
blockedChannelIds: [] # Array of channel IDs that should be blocked from being displayed in the app
```

~As a gateway operator, I can block data object IDs. The videos that contain the blocked data object id won’t show publicly as videos and as NFTs.~ Edit: We won't be fixing this

~- [ ] 🔴They won’t show on the homepage~
~- [ ]  🔴 They won’t show on the video view~ 
~- [ ]  🔴 They won't’ show on the Channel view~
~- [ ]  🔴They won’t show on the video category view~
~- [ ]  🔴They won’t show on the nfts view~

As a gateway operator, I can block video ids. The blocked videos won’t show publicly as videos and as NFTs

- [x]  They won’t show on the homepage
- [x]  They won’t show on the video view
- [x]  They won't show on the Channel view
- [x]  They won’t show on the video category view
- [x]  They won’t show on the nfts view

As a gateway operator, I can block channel ids. The channels and videos/nfts that belong to these channels won’t show publicly

- [x]  They won’t show on the homepage
- [x]  They won’t show on the video view
- [x]  They won't show on the Channel view
- [x]  They won’t show on the video category view
- [x]  They won’t show on the nfts view

## Gateway operator filters - orion v2 mutations

- [x]  As a gateway operator, I can exclude video, channel, or comment using `excludeContent` mutation
- [x]  As a gateway operator, I can restore video, channel, or comment that was previously excluded using `restoreContent` mutation
- [ ]  As a gateway operator, I can set supported categories using `setSupportedCategories` mutation
- [x]  As a gateway operator, I can change video view per it time limit, using `setVideoViewPerIpTimeLimit` muatation
- [x]  As a gateway operator, I can turn and turn off maintenance mode using `setKillSwitch` mutation
- [x]  As a gateway operator, I can set video hero, using `setVideoHero` mutation
- [ ]  As a gateway operator, I can set category featured videos using `setCategoryFeaturedVideos` mutation

*****************Not implemented yet in orion:*****************

- [ ]  As a gateway operator, I can check the video report and channel reports

**Comment by dmtrjsg** [comment]
Dmitry - homepage and gw operator ones
~Attemka - vide pages, nfts, video view~

**Comment by dmtrjsg** [comment]
## Issues to triage, unrelated to Orion but found during testing. 

- [x] 1️⃣  notifications for channels show only in studio. ER: displayed on viewer side as well for members that have the channel connected to their membership. (when you switch to channel profile on viewer side notifications still do not show)
- [x] 2️⃣  Outbid message has typo, needs to be outbid AT instead of outbid FOR (as we display actual price and not delta)
<img width="562" alt="Screenshot 2023-02-21 at 18 24 47" src="https://user-images.githubusercontent.com/93924525/220371928-f8ab751e-820f-4590-a835-75fe89f932ac.png">
- [x] We allow to place bid with insufficient balance: 

<img width="509" alt="Screenshot 2023-02-21 at 18 45 58" src="https://user-images.githubusercontent.com/93924525/220377700-88c85601-9a3d-4c77-940f-0e4c74d5f659.png">
<img width="751" alt="Screenshot 2023-02-21 at 18 45 37" src="https://user-images.githubusercontent.com/93924525/220377711-48dfe0f1-5b99-48d8-ac12-9d49a81c06e4.png">

- [x] 4️⃣ if someone comments on NFT the creator gets notification, but new owner of NFT does not. Suggestion to Add notification for NFT owner. "123 commented on your nft"



## 🔴  Issues from core use cases: 

- [x] Popular on Atlas section shows 41 videos and the oldest is created 3 months ago.  Videos are sorted by date created starting from newest. 
- [x] Number of followers on homepage displays as 1. Does not increment/ decrement with following and unfollowing. Tracking issue https://github.com/Joystream/orion/issues/78
- [x] blocking data object ids by the operator(in atlas config) is not working currently. We're getting mixed results in various places.

**Comment by dmtrjsg** [comment]
⚠️ To test settled auction
NFT: https://atlas-qq3f942az-joystream.vercel.app/video/134
member who placed the bid: birdStereo 
to check: bird stereo won, has settled auction ->  SpaceFamilyKingdom to see notification that auction is settled

**Comment by drillprop** [comment]
I'll take `Gateway operator filters - config`

**Comment by drillprop** [comment]
> - [ ] 🔴They won’t show on the homepage
> - [ ]  🔴 They won’t show on the video view 
> - [ ]  🔴 They won't’ show on the Channel view
> - [ ]  🔴They won’t show on the video category view
> - [ ]  🔴They won’t show on the nfts view

blocking data object ids is not working at all. We're getting mixed results in various places

**Comment by dmtrjsg** [comment]
### Homepage
🆕 *As an auction participant, I want to see that the _timed_ auction I participated in has ended*
- [x] 🔴 As winner I see the auction has ended and I need to settle
- [x] 🔴 As nft original owner I see the auction has ended and winner needs to settle the auction
- [x] 🔴 As losing bidder I see the auction has ended and I can withdraw my bet

-> this notification is not sent at all

### Popular

**Videos**

- [ ]  🟡 As a user, I should see a list of 50 the most viewed videos, sorted by date creation -> Shows 45 videos

**Channels**
- [ ] 🟡 I should see only channels that have at least 4 videos

> https://atlas-2c7emdwly-joystream.vercel.app/channel/54?tab=Videos < this channel has 4 videos and not included into popular. Condition is set to strictly above 4, and not >=.

**NFTs**
- [ ] 🔴 As a user, I can filter NFTs using other filters, and the NFTs number is displayed correctly and I see correct results

This video is not included into promotional materials but is filtered out when "exclude promo: filter applied: https://atlas-2c7emdwly-joystream.vercel.app/video/134

**Channels**
- [ ] 🔴 As a user, I see channels that have at least 1 video
[Example Channel> ](https://atlas-qq3f942az-joystream.vercel.app/channel/16?tab=Information)
Check "Malay"

⏯️  **To be retested on Prod**
- [ ]   a list of the 15 most watched channels out of 100 newest channels in random order

## Discover
- [ ]  🔴 As a user, I  see the correct number of videos of categories.
- [ ]  🔴  As a user, I see the categories chart displayed correctly(this one 👇)

**Category page**

- [ ] 🔴 As a user, I can change language and I see videos in this language, and the correct number of videos

**Video Page**
Comments

- [x] 🔴 As a user, I can sort comments by  most popular
Comment with no reactions and replies was filtered out. [See here> ](https://atlas-2c7emdwly-joystream.vercel.app/video/134)

**Search**
- [ ] 🔴 Cannot search for "aliceChannel" - no search suggestions

**Comment by dmtrjsg** [comment]
- [x]  When I settle an auction, tx completed and then error was shown: 

Tx: https://polkadot.js.org/apps/?rpc=wss://atlas-dev.joystream.org/ws-rpc#/explorer/query/0x58b4ab0a351090e55544aa38efecc0e6daaa6e3907f90b2b0ab43dc8e6e23d9e

<img width="1445" alt="Screenshot 2023-02-23 at 16 44 43" src="https://user-images.githubusercontent.com/93924525/220909768-64ea1394-4d85-42a7-92de-c007bdba5262.png">

- [x] When filters applied on Page 3 for NFTs the result shows as empty: 

<img width="1335" alt="Screenshot 2023-02-23 at 17 08 34" src="https://user-images.githubusercontent.com/93924525/220915489-eed6bae4-1478-45b4-920c-09c356989ecc.png">

- [x] Cannot change category of a video

**Comment by drillprop** [comment]
@dmtrjsg 
**Please retest:** 
> - [x] 🔴 Cannot search for "aliceChannel" - no search suggestions

should be fixed
> - [x] 🔴 As a user, I can sort comments by  most popular
Comment with no reactions and replies was filtered out. [See here> ](https://atlas-2c7emdwly-joystream.vercel.app/video/134)

works for me, I don't see anything wrong here 
![image](https://user-images.githubusercontent.com/51168865/221125282-e523b895-d853-43f4-97eb-05ecf0f371cb.png)

> **Channels**
> - [x] 🟡 I should see only channels that have at least 4 videos

should be fixed

> - [ ]  ⚠️ (blocked) As a gateway operator, I can set video hero on the homepage

Is this blocked? You managed to set the video hero, didn't you? 

**Other issues**

> As a gateway operator, I can block data object IDs. The videos that contain the blocked data object id won’t show publicly as videos and as NFTs.
> - [ ] 🔴They won’t show on the homepage
> - [ ]  🔴 They won’t show on the video view 
> - [ ]  🔴 They won't’ show on the Channel view
> - [ ]  🔴They won’t show on the video category view
> - [ ]  🔴They won’t show on the nfts view

As we discussed on discord I won't be fixing that, not worth it

> ## Discover
> - [ ]  🔴 As a user, I  see the correct number of videos of categories.
> - [ ]  🔴  As a user, I see the categories chart displayed correctly(this one 👇)

I think this works correctly. In my orion v2 PR, we only support one category that exists in QN("Action category"), so the count should be correct. This is a very similar problem to https://github.com/Joystream/atlas/issues/3873 
We need to update our categories in the config and match them with categories in QN.  We will need to retest this of course once the issue is resolved

**Comment by dmtrjsg** [comment]
Superseded by 
- https://github.com/Joystream/atlas/issues/3877
