### ISSUE TITLE
Hide YT synced videos from My Uploads

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3822]
## Context
Problem is that YT synced videos show as failed in My Uploads every time.  Suggestion as a quick fix is to hide them altogether, if synced from YT as it opens up the venue of manually re-uploading hence stopping the auto-upload.

## Scope
- Hide videos from uploads

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1203984525712217) by [Unito](https://www.unito.io)

**Comment by attemka** [comment]
waiting for [this](https://github.com/Joystream/youtube-synch/issues/139) to be implemented
