### ISSUE TITLE
CRT Viewer: Token Page - Description

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3825]
## Context
- #3384 

## Scope

Creator token description
- Description Pending
- CRT Video 
- Benefits
- About

## Design

[Link to Figma>](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117615&t=XWyT31UxvE7yKN66-1)

Preview:
<img width="346" alt="Screenshot 2023-02-16 at 17 25 19" src="https://user-images.githubusercontent.com/93924525/219376919-1d20eaf9-a915-48c4-8eca-2e755a9187d2.png">

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/32?tab=Token

✅ Description Pending
✅ CRT Video
✅ About
⚠️ Benefits
- There is no option to delete all the benefits. I added 3 benefits, then deleted the 1st one - ok, 2nd one - ok, 3rd one - preview shows it deleted, but after saving it still shows. 
- No option to add an icon
- In view mode, the placeholder is vertically stretched (ellipse)
<img width="878" alt="Screenshot 2023-12-01 at 20 09 31" src="https://github.com/Joystream/atlas/assets/46903215/7f0eff41-a9e8-43bb-bb73-0eee44f033ae">
