### ISSUE TITLE
CRT Viewer: Token Page - Header Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3826]
## Context
- #3384 

## Scope

Creator token description
-  Header widget
- Tooltips on Hover

## Design

[Link to Figma>](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1963%3A105418&t=XWyT31UxvE7yKN66-1)

Preview: 
<img width="583" alt="Screenshot 2023-02-16 at 17 27 55" src="https://user-images.githubusercontent.com/93924525/219377730-874ac5a0-f8ef-4cbc-b36c-52c5520ac982.png">

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/39?tab=Token

⚠️ Header widget
-Short description duplicates information from the About section
-"invitу only" badge seems to be hardcoded, as it shows up regardless of the settings when the token is created

<img width="1327" alt="Screenshot 2023-12-06 at 16 02 01" src="https://github.com/Joystream/atlas/assets/46903215/2bc07966-0c9b-4b4b-88dc-91ec8210e3b5">

✅ Tooltips
<img width="343" alt="Screenshot 2023-12-06 at 16 08 52" src="https://github.com/Joystream/atlas/assets/46903215/46e6aa66-8880-4117-98cd-190e4d6fc88e">
<img width="266" alt="Screenshot 2023-12-06 at 16 09 00" src="https://github.com/Joystream/atlas/assets/46903215/efad7041-d212-41c1-bdd5-bca1b0c9dd20">
<img width="353" alt="Screenshot 2023-12-06 at 16 09 08" src="https://github.com/Joystream/atlas/assets/46903215/5687b42a-c5d0-416d-a317-e8327ef8b1ad">
<img width="259" alt="Screenshot 2023-12-06 at 16 09 15" src="https://github.com/Joystream/atlas/assets/46903215/2aa0f99b-8bf0-49a6-a47b-ab6c4341e951">

**Comment by WRadoslaw** [comment]
> -Short description duplicates information from the About section

@KubaMikolajczyk there is no short description field in the schema and form for the CRT, should we just delete it?
