### ISSUE TITLE
CRT Viewer: Token Page - State and Stats

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3827]
## Context
- #3384 

## Scope

- Token Default State  (no sale, no whitelist, no rev share)
- Statistics

⛔ Out of scope:

All other states -  will be implemented together with the relevant flows.

## Design

[Link to Figma>](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1963%3A105418&t=XWyT31UxvE7yKN66-1)

<img width="185" alt="Screenshot 2023-02-16 at 17 30 24" src="https://user-images.githubusercontent.com/93924525/219378395-e55f227c-dc8e-4b13-bed8-8483351edb2e.png">

**Comment by thesan** [comment]
https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel?type=design&node-id=1963-109145

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/39?tab=Token

✅ Token Default State (no sale, no whitelist, no rev share)
✅ Statistics

State after token creation

<img width="428" alt="Screenshot 2023-12-07 at 13 43 17" src="https://github.com/Joystream/atlas/assets/46903215/d18e7a50-93c5-4934-8ba8-dd7b265ffaf7">
<img width="434" alt="Screenshot 2023-12-07 at 13 41 47" src="https://github.com/Joystream/atlas/assets/46903215/de214fec-004e-41fb-86e9-e4d779daf878">
