### ISSUE TITLE
CRT Viewer: Token Page - Holders Table

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3829]
## Context
- #3384 

## Scope

- [ ] Holders Table Preview
- [ ] Holders Table Full View in Modal
- [ ] Holders Table - Hover view all tokens

## Design

[Link to Figma> ](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117720&t=XWyT31UxvE7yKN66-1)

<img width="382" alt="Screenshot 2023-02-16 at 17 36 21" src="https://user-images.githubusercontent.com/93924525/219379609-d8a2ff09-034b-4f30-a287-13e621235a65.png">

<img width="333" alt="Screenshot 2023-02-16 at 17 36 31" src="https://user-images.githubusercontent.com/93924525/219379641-17236259-c90b-49d0-902a-86d3eeae8057.png">

<img width="454" alt="Screenshot 2023-02-16 at 17 36 40" src="https://user-images.githubusercontent.com/93924525/219379650-3669ae59-79c7-4a04-ad03-aa63dadc0834.png">

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/23?tab=Token

⚠️ Holders Table Preview
- holder name and avatar incorrect
- we could limit the list and show only the top 10 holders here
<img width="430" alt="Screenshot 2023-12-07 at 14 29 04" src="https://github.com/Joystream/atlas/assets/46903215/e13544f6-7f59-4fe6-aac0-e8edf2a307ed">

 ✅ Holders Table Full View in Modal
<img width="497" alt="Screenshot 2023-12-07 at 14 29 35" src="https://github.com/Joystream/atlas/assets/46903215/3800dc3c-25a0-4ee1-b35f-befc19b51f28">

 ⚠️ Holders Table - Hover view all tokens - looks like not implemented yet
