### ISSUE TITLE
CRT Viewer: Token Page - Buy Token On Sale

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3830]
## Context
- #3384 

## Scope

- [ ] Token on sale widget
- [ ] Step 1 - how much to buy (excl Max?)
- [ ] Step 2 - Cliff and Payouts chart and params 
- [ ] [All validations: link > ](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=2000%3A122810&t=XWyT31UxvE7yKN66-1)

☝️ T&Cs are scrollable

Out of scope: 
Submit TX 
Conf modal
Buy max 
Chart for Vesting and Cliff

## Design

[Link to Figma> ](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117720&t=XWyT31UxvE7yKN66-1)

Preview: 

<img width="201" alt="Screenshot 2023-02-16 at 17 45 18" src="https://user-images.githubusercontent.com/93924525/219381535-10e98886-3acd-4b1b-8615-fa18a451d77a.png">
<img width="297" alt="Screenshot 2023-02-16 at 17 45 21" src="https://user-images.githubusercontent.com/93924525/219381548-f0f4ee1e-d652-4def-926a-5e8a6acd3e04.png">
<img width="286" alt="Screenshot 2023-02-16 at 17 45 27" src="https://user-images.githubusercontent.com/93924525/219381565-71e9c354-a5b5-426c-81af-650eb4222866.png">

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/

@dmtrjsg Sale tokens option is disabled on testing env, there is another env where we can test?

<img width="1169" alt="Screenshot 2023-12-07 at 15 17 02" src="https://github.com/Joystream/atlas/assets/46903215/d6f7609c-1962-4e5e-8bcf-697464700ce5">
