### ISSUE TITLE
CRT Viewer: Token Page - Buy Token On Market UI

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3834]
## Context
- #3384 

## Scope

- [ ] Buy tokens widget
- [ ] Amount input
- [ ] T&Cs
- [ ] Conf Modal

## Design

[Link to Figma>](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117678&t=XWyT31UxvE7yKN66-1)

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/23?tab=Token

✅ Buy tokens widget
✅ Amount input
✅ T&Cs
✅ Conf Modal
⚠️ tooltips empty 

<img width="425" alt="Screenshot 2023-12-07 at 15 45 45" src="https://github.com/Joystream/atlas/assets/46903215/0a1c5685-b281-4aff-acab-f792179fe1f2">
<img width="504" alt="Screenshot 2023-12-07 at 15 29 48" src="https://github.com/Joystream/atlas/assets/46903215/7301f838-6359-4fd2-a733-cde3f9ae4d5a">
<img width="497" alt="Screenshot 2023-12-07 at 15 31 45" src="https://github.com/Joystream/atlas/assets/46903215/f3b28943-f569-4bde-abd8-119d3fd219b7">
<img width="496" alt="Screenshot 2023-12-07 at 15 32 56" src="https://github.com/Joystream/atlas/assets/46903215/13f4a499-579b-4312-be75-73a0aed40b8c">
<img width="505" alt="Screenshot 2023-12-07 at 15 34 07" src="https://github.com/Joystream/atlas/assets/46903215/9bfcc2e9-5a1d-4787-878d-8c1f80d9c447">
