### ISSUE TITLE
CRT Viewer: Buy Tokens on Market - Submit tx

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3835]
## Context
- #3384 

## Scope

- [ ] Submit purchase tx for AMM

## Design

[Link to Figma>](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117678&t=XWyT31UxvE7yKN66-1)

**Comment by polikosi** [comment]
tested on: https://atlas-o35urjwe5-joystream.vercel.app

1. I can't see any confetti when I have successfully bought tokens. 
2. By the design, I expected to see a different photo on the "Congratulations on your purchase" dialog
3. I can't see the snackbar after closing the dialog
![image](https://github.com/Joystream/atlas/assets/80429191/770ee76d-c70e-447c-965b-c2640d2ee339)

Perhaps it was not included:
In the list of owners on the token page, I see only candidate1 (he started the market), but I also bought tokens on candidate2, 3, 7.
![image](https://github.com/Joystream/atlas/assets/80429191/a19e1ec2-578d-4646-8a9b-e6947fbc7711)

**Comment by polikosi** [comment]
1. I can't see the snackbar after closing the dialog
2. it would be nice if the sorting by the amount of tokens was the same as on the "holders" page
![image](https://github.com/Joystream/atlas/assets/80429191/f089a87e-3dad-4e28-9374-efff1455d5dc)

**Comment by WRadoslaw** [comment]
> 1. I can't see the snackbar after closing the dialog

Which dialog?

**Comment by ivanturlakov** [comment]
> Which dialog?

According to design after user clicks on Continue button on "Congrats on your purchase" modal > the Modal should be closed and a snackbar appears on bottom left

<img width="223" alt="Screenshot 2024-01-30 at 19 32 14" src="https://github.com/Joystream/atlas/assets/46903215/8f1fa5c2-738c-4a12-b7a2-af8249751719">

Holders Table > Members links => Member not found
