### ISSUE TITLE
CRT Viewer: Token Page - Sell tokens on Market

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3836]
## Context
- #3384 

## Scope

- [ ] UI and Submit Sale tx for AMM 

## Design

[Link to figma> ](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=1903%3A117692&t=XWyT31UxvE7yKN66-1)

Preview: 
<img width="286" alt="Screenshot 2023-02-16 at 18 03 54" src="https://user-images.githubusercontent.com/93924525/219386325-d4faaef5-33f2-4225-a520-f4728502058a.png">

**Comment by ivanturlakov** [comment]
Tested on https://atlas-o35urjwe5-joystream.vercel.app/channel/23?tab=Token

Design
<img width="602" alt="Screenshot 2023-12-09 at 17 25 15" src="https://github.com/Joystream/atlas/assets/46903215/736a8845-71d2-484a-bb4a-31797aee232e">

- Placeholder design a bit missed(input field)
- Tooltips is empty
<img width="498" alt="Screenshot 2023-12-09 at 17 21 08" src="https://github.com/Joystream/atlas/assets/46903215/7548485b-251a-434b-b23c-1773cadec15f">
<img width="498" alt="Screenshot 2023-12-09 at 17 21 17" src="https://github.com/Joystream/atlas/assets/46903215/e8d27c93-a582-44ac-90e9-61ee536b2d03">

Tx Failed
https://polkadot.js.org/apps/?rpc=wss://3.123.129.217.nip.io/ws-rpc#/explorer/query/0x5a8f6f453e7f65853c1f71691062f3c05862bc8182ccb1dffaa589dccf5b9255
<img width="1440" alt="Screenshot 2023-12-09 at 17 21 40" src="https://github.com/Joystream/atlas/assets/46903215/8ef65de2-acca-49f5-9d3c-f5e3007c8b7a">
