### ISSUE TITLE
CRT Viewer: Notifications (Minting,  Sale and AMM)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3837]
## Context
- #3384 

## Scope

- [ ] Token Buyer Notifications Triggers and UI

## Design

[Link to figma>](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=1824%3A56060&t=u3JcLppfMCaRrgFd-1)

<img width="758" alt="Screenshot 2023-02-16 at 18 06 24" src="https://user-images.githubusercontent.com/93924525/219386837-69aec5a9-b7d6-4794-9f21-de523771aaaa.png">

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg Viewers notifications are ready to be reviewed ✅

🎥 Video update (1:30, really short explanation of all new notifications): https://www.loom.com/share/9c495dcd7b9e40da86a9738d1f6b9253?sid=fdbe3acc-141d-40a2-8fab-f2566c7686ed

📄 Notifications events changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=3272-20368&mode=design&t=pgqmuSktkmpn8ROv-4

📄 Membership profile settings changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=3537-76643&mode=design&t=pX7smdnfUJpdZVu2-4

**Comment by ikprk** [comment]
That's already done
