### ISSUE TITLE
Verified channel status display

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3840]
## Context
- https://github.com/Joystream/atlas/issues/3384

✅ The viewer part of the verification & token indicators are done and can be inspected for implementation here 👇

⚠️ Channel verification status will be handled via metaprotocol
- https://github.com/Joystream/joystream/issues/2586

## Scope
- [ ] Implement new components
- [ ] Display based on channel attributes (token; verified)
- [ ] Video tiles/ channel info

## Design

Flows:
- Token & verification flow: https://www.figma.com/file/cRR8k0z8vx6PfuXqGeiyRx/Token-%26-verification-info?node-id=1601%3A1435&t=NcINbzY4ITzcIt7V-4

Components:
- Video tile details component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=3630%3A112918&t=YxJKiyvlXhY6Kchh-4
- Channel card component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=4094%3A144644&t=YxJKiyvlXhY6Kchh-4
- Channel info component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=216%3A27109&t=YxJKiyvlXhY6Kchh-4
- Global search box component:  https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=2%3A10987&t=mZSWEwXDoFYgiPWx-4

## Out of scope ⛔ 
- Search box 
- Search result page (these will not feature channels going forward, only videos)
- Search flows: https://www.figma.com/file/8JhE2GxIjjLP3WU37xPnDH/Search-results-page?node-id=536%3A52442&t=mZSWEwXDoFYgiPWx-4

**Comment by dmtrjsg** [comment]
Workflow is covered here: 
- https://github.com/Joystream/atlas/issues/4950

**Comment by ivanturlakov** [comment]
@dmtrjsg what Pioneer env can I use for setting up Lead and verifying the channel?

As far as I understand the possibility of channel verification(CLI, Extrinsic) is currently under development
