### ISSUE TITLE
Creator: Views Token Holders in Tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3841]
## Context
- #3384 

## Scope
- [ ] Holders tab 
- [ ] Holders table with Creator as first holder
- [ ] Show all holders in Table
- [ ] Pagination

## Design

[Link to figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=929%3A142085&t=hK2YV8zEDY5qSApe-1)

<img width="765" alt="Screenshot 2023-02-17 at 14 10 30" src="https://user-images.githubusercontent.com/93924525/219615571-40e0f7ab-00f0-460a-bb0b-ed6a002e871c.png">

**Comment by polikosi** [comment]
I expected to see <1% of tokens in the "Allocation" column.
As the creator, I should be at the top of the list.
![image](https://github.com/Joystream/atlas/assets/80429191/1b29359d-2556-4bfe-a7d4-585340fedf00)

I expected to see 2 pages or a pagination component that allows to display more than 10 owners, as there are more than 10 owners here. 
![image](https://github.com/Joystream/atlas/assets/80429191/affacf0a-6f32-4d3d-b8ce-a5b8a41256e7)

**Comment by polikosi** [comment]
It's a bit out of line with the design especially the page switcher. 
Also, please add pagination.
![image](https://github.com/Joystream/atlas/assets/80429191/0ef0a06c-2051-4d56-af1f-e9958d9d0280)
