### ISSUE TITLE
Creator: Token Holders Widget on Dash

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3842]
## Context
- #3384 

## Scope
- [ ] Pie chart widget 
-- default state
-- top 3 holders
-- the rest of holders
-- do not display numbers in small segments on the chart
- [ ] Interaction - opacity change on hover

## Design

[Link to figma](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=1013%3A159646&t=hK2YV8zEDY5qSApe-1)

Preview: 
<img width="502" alt="Screenshot 2023-02-17 at 14 12 29" src="https://user-images.githubusercontent.com/93924525/219616358-9b50850e-85fd-41f4-8d64-09826ec70eca.png">

**Comment by polikosi** [comment]
1. Not show how many I have tokens.

2. The top 3 owners are not displayed correctly. I expected to see in top 3 holders candidate15, candidate3, candidate2.

![image](https://github.com/Joystream/atlas/assets/80429191/d7f76c2d-bafa-4e78-bc87-4c8744c6b43c)

![image](https://github.com/Joystream/atlas/assets/80429191/1b19add2-d6b3-4999-a737-9fded75afa97)

**Comment by polikosi** [comment]
The percentage of tokens held by the owners is incorrectly displayed and not displayed on the pie chart
![image](https://github.com/Joystream/atlas/assets/80429191/2ec6de87-1d94-46b5-8982-cadb65b5541f)
![image](https://github.com/Joystream/atlas/assets/80429191/d9370759-166a-4de3-b7f1-8b093b72a4f0)

**Comment by WRadoslaw** [comment]
> The percentage of tokens held by the owners is incorrectly displayed and not displayed on the pie chart ![image](https://private-user-images.githubusercontent.com/80429191/290582291-2ec6de87-1d94-46b5-8982-cadb65b5541f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzAxODMsIm5iZiI6MTcwMjYyOTg4MywicGF0aCI6Ii84MDQyOTE5MS8yOTA1ODIyOTEtMmVjNmRlODctMWQ5NC00NmI1LTg5ODItY2FkYjY1YjU1NDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MDM0ZTk5ZmVjNGU5MjU0YjVlMzcxZTY5MWY5YzI1Zjg1MDhkOTEyODQ3ODFjMzdmYjg4NjU1MmVmYzFhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5QzDXWVDks6Ot82FbizKfL5WlREn_RwEQLwhHO_TS1g) ![image](https://private-user-images.githubusercontent.com/80429191/290582463-d9370759-166a-4de3-b7f1-8b093b72a4f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzAxODMsIm5iZiI6MTcwMjYyOTg4MywicGF0aCI6Ii84MDQyOTE5MS8yOTA1ODI0NjMtZDkzNzA3NTktMTY2YS00ZGUzLWI3ZjEtOGIwOTNiNzJhNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA4NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjFhMWZkNWJhZmExZWIxZDA0OGU5Mzg4YzY1ZDdlMTFlNDE0ZjFmNTQ2NGUxMDYyNTY3MjVkY2RiZjI5ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KlCMDp0zRBzdh1CfmjzfAk2YmEG0N8jMnM_RNtmdEqY)

Done in v6
