### ISSUE TITLE
Creator: Revenue Share Tab

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3844]
## Context
- #3384 

## Scope
- [ ] Revenue Share Tab
- No ongoing sale placeholder widget
- [ ] Revenue Share Widgets
-- Revenue Share ratio

⚠️ only do revenue share ratio widget in this version.

⛔ Out of scope:
-- Current state
-- Channel balance

Changes will be covered here:
- https://github.com/joystream/atlas/issues/4856

## Design
[Link to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A104748&t=9ogR3tZzrka32tXb-1)

Preview: 
<img width="683" alt="Screenshot 2023-02-17 at 14 36 19" src="https://user-images.githubusercontent.com/93924525/219621368-16fdc2c2-de27-4d10-8a33-5f0f1e2a60c4.png">

**Comment by polikosi** [comment]
here should be "No ongoing revenue share"
![image](https://github.com/Joystream/atlas/assets/80429191/075e6b53-436c-40aa-88ca-40e7ead15513)
