### ISSUE TITLE
Creator: Start Revenue Share

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3845]
## Context
- #3384 

## Scope
- [ ] Start Revenue Share UI

Amount
Duration
[Validations> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A106193&t=9ogR3tZzrka32tXb-1)

🚫 out of scope: 
Submit tx
Conf toaster
Rev Share Widget
Rev Share History

## Design
[Link to Figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A104734&t=9ogR3tZzrka32tXb-1)

Preview: 

<img width="258" alt="Screenshot 2023-02-17 at 14 43 49" src="https://user-images.githubusercontent.com/93924525/219622857-68250c1e-2409-46ff-9f53-839085655cc3.png">

**Comment by polikosi** [comment]
By design, the user cannot choose the amount to share
#5586 
#5589 
#5590
