### ISSUE TITLE
Creator: Start Rev share submit tx

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3846]
## Context
- #3384 
- https://github.com/Joystream/atlas/issues/3845

## Scope
- [ ] Submit Tx for revenue share

## Design
[LInk to figma> ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A107747&t=9ogR3tZzrka32tXb-1)

<img width="433" alt="Screenshot 2023-02-17 at 14 46 13" src="https://user-images.githubusercontent.com/93924525/219623833-0963b51f-adbc-4a9f-9aa8-c850e0799a48.png">

**Comment by polikosi** [comment]
I did not receive any notification at the bottom about the start of revenue share after I started it.

I get only this
![image](https://github.com/Joystream/atlas/assets/80429191/9d00dbd8-5308-4429-b57e-a7de32cb742a)
