### ISSUE TITLE
Creator: Revenue Share progress widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3847]
## Context
- #3384 

## Scope
- [ ] Revenue share progress widget

## Design
[LInk to Figma>](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A107012&t=9ogR3tZzrka32tXb-1)

<img width="750" alt="Screenshot 2023-02-17 at 14 47 57" src="https://user-images.githubusercontent.com/93924525/219624842-fd46995d-becb-4286-a1bf-0d2c58fe4448.png">

**Comment by dmtrjsg** [comment]
Superseded by: 
- https://github.com/Joystream/atlas/issues/4856

**Comment by polikosi** [comment]
![image](https://github.com/Joystream/atlas/assets/80429191/bb592a37-f6c8-4760-a2fa-06ed32ebbace)

**Comment by polikosi** [comment]
According to the design, when the revenue share is active, it should be "Holders staked". When the revenue share is over, it should be "Ended on" and the number of participants as in the screenshot.
![image](https://github.com/Joystream/atlas/assets/80429191/36e679d9-17d8-4add-95bd-1bd556c2fcaa)
