### ISSUE TITLE
Creator: Staked Holders for Rev Share

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3849]
## Context
- #3384 

## Scope

- Staked holders table

## Design
[Link to Figma > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A107012&t=9ogR3tZzrka32tXb-1)

Preview: 
<img width="853" alt="Screenshot 2023-02-17 at 14 53 06" src="https://user-images.githubusercontent.com/93924525/219627886-1c4e91b0-730a-4767-8066-196d63c18833.png">

**Comment by polikosi** [comment]
blocked by this bug #5600

**Comment by WRadoslaw** [comment]
> blocked by this bug #5600

can be retested

**Comment by polikosi** [comment]
Please add the name of the table "Staked holders"
![image](https://github.com/Joystream/atlas/assets/80429191/a23ac203-bc00-46d9-8ce1-05ea31dc50d0)
