### ISSUE TITLE
Creator: Close completed Revenue Share

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3850]
## Context
- #3384 

## Scope

- [ ] Stop revenue share button 
- [ ] Stop revenue share flow 
- [ ] Submit rev share Tx
- [ ] Conf message in toaster

## Design
[Link to Figma > ](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A107012&t=9ogR3tZzrka32tXb-1)

Preview: 

<img width="838" alt="Screenshot 2023-02-17 at 14 56 52" src="https://user-images.githubusercontent.com/93924525/219628836-97555763-52ae-4255-b95b-32da7c48efa0.png">

<img width="318" alt="Screenshot 2023-02-17 at 14 58 06" src="https://user-images.githubusercontent.com/93924525/219629206-6ba97570-92d5-4436-8f0b-0ee3d97792c3.png">

**Comment by polikosi** [comment]
- Conf message in toaster
missing comma after 19
![image](https://github.com/Joystream/atlas/assets/80429191/7b07907c-5607-47d8-93d0-0236f6a966ee)

**Comment by WRadoslaw** [comment]
> * Conf message in toaster
>   missing comma after 19
>   ![image](https://private-user-images.githubusercontent.com/80429191/288407587-7b07907c-5607-47d8-93d0-0236f6a966ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQyMjQsIm5iZiI6MTcwMjI5MzkyNCwicGF0aCI6Ii84MDQyOTE5MS8yODg0MDc1ODctN2IwNzkwN2MtNTYwNy00N2Q4LTkzZDAtMDIzNmY2YTk2NmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MjExYTNkZDIxZWMwOWU3NDY5ZjZiMjczYmYyYzBjODhlYjYxMzQzNTBiNmE0YzBkMGVlOGEzYTM3MGVhMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZaYn6G4XUHe_tCsuLM3f2rmHr8yuT0soHvqY_8C1Rdo)

fixed
