### ISSUE TITLE
Creator: Revenue Share Dash Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3851]
## Context
- #3384 

## Scope

Revenue share DB widget

- [ ] Status
- [ ] Link to rev share db
- [ ] Ratio
- [ ] States:
-- Not started
-- In progress - show holders
-- Close button when time is up

## Design
[Link to Figma >](https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?node-id=787%3A108919&t=Jr927MfdV4FKUzL3-1)

Preview: 
<img width="417" alt="Screenshot 2023-02-17 at 14 53 46" src="https://user-images.githubusercontent.com/93924525/219630030-7bba4a83-64f8-4493-bd67-b528d630aeb5.png">

**Comment by polikosi** [comment]
- sorry but I didn't see where I can find "Link to rev share db".

- Ratio shows but show incorrect value.

- The close button after the time is up is displayed on DB, but when I click on it, nothing happens. I can close only on the 
"revenue share" tab.

![image](https://github.com/Joystream/atlas/assets/80429191/32dfb852-ffd4-4d5c-bfc7-8277357d63b9)

**Comment by WRadoslaw** [comment]
> * sorry but I didn't see where I can find "Link to rev share db".
> * Ratio shows but show incorrect value.
> * The close button after the time is up is displayed on DB, but when I click on it, nothing happens. I can close only on the
>   "revenue share" tab.
> 
> ![image](https://private-user-images.githubusercontent.com/80429191/288192543-32dfb852-ffd4-4d5c-bfc7-8277357d63b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQyMzgsIm5iZiI6MTcwMjI5MzkzOCwicGF0aCI6Ii84MDQyOTE5MS8yODgxOTI1NDMtMzJkZmI4NTItZmZkNC00ZDVjLWJmYzctODI3NzM1N2Q2M2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MTFhYzZhNDgwZjJlZjdmMmM2ZjAzMDQwZWE1OTJhZWE2NjA3MzZhMjE0ZjMyOTkxMDZlZTYwMTQ3MGIxOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._fEyZW_ZXq6y2naJb9FP6Ux3dLaeMIvAnh-t5MlmFpw)

fixed

**Comment by polikosi** [comment]
Add there sign plus "+" before the number.
And change "Ended on" to "Holders staked" while revenue share is active.
![image](https://github.com/Joystream/atlas/assets/80429191/da346772-0da9-4034-b05c-ee5cf4375427)
