### ISSUE TITLE
CRT Viewer: Revenue Share Widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3852]
## Context
- #3384 

## Scope
- [ ] All variations of widget for revenue share on the token page

Not started
Started
Claim
+ View in portfolio link

## Design
[Link to Figma> ](https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel-page?node-id=2068%3A151784&t=RVP6zlnZtuaPrPRe-1)

Preview:
<img width="426" alt="Screenshot 2023-02-17 at 15 07 21" src="https://user-images.githubusercontent.com/93924525/219633291-bb301f1f-3b00-43ff-ad10-c1e0be7f41d4.png">
<img width="331" alt="Screenshot 2023-02-17 at 15 07 03" src="https://user-images.githubusercontent.com/93924525/219633307-8d7a8f97-4bee-4b74-8241-bab2bae41b61.png">

**Comment by polikosi** [comment]
on the token page, I do not see information about the revenue share in any variations.
Also I don't see "View in portfolio link" on the token page

- not started

![image](https://github.com/Joystream/atlas/assets/80429191/9651bad4-097f-4519-bcd9-50155ab2738a)

- started

![image](https://github.com/Joystream/atlas/assets/80429191/95880c20-0e16-47db-b4a7-e1466b67b5f5)

- claim
![image](https://github.com/Joystream/atlas/assets/80429191/fa9ee213-4851-44e2-bac5-5700d7658768)

**Comment by WRadoslaw** [comment]
> on the token page, I do not see information about the revenue share in any variations. Also I don't see "View in portfolio link" on the token page
> 
> * not started
> 
> ![image](https://private-user-images.githubusercontent.com/80429191/288474789-9651bad4-097f-4519-bcd9-50155ab2738a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQyNjMsIm5iZiI6MTcwMjI5Mzk2MywicGF0aCI6Ii84MDQyOTE5MS8yODg0NzQ3ODktOTY1MWJhZDQtMDk3Zi00NTE5LWJjZDktNTAxNTVhYjI3MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZGIyMTg3NzYyODcyMjZjYzAzMTVhZGIxODNlN2M4Y2RiZDY4Y2U5ZWQ4ZTc3YjlhYjE4NjAwN2VkMGEyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5CLr-NrDSkDv2gFlNqmXcLZJgESUDrvLUhznKjGyQ8Y)
> 
> * started
> 
> ![image](https://private-user-images.githubusercontent.com/80429191/288474404-95880c20-0e16-47db-b4a7-e1466b67b5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQyNjMsIm5iZiI6MTcwMjI5Mzk2MywicGF0aCI6Ii84MDQyOTE5MS8yODg0NzQ0MDQtOTU4ODBjMjAtMGUxNi00N2RiLWI0YTctZTE0NjZiNjdiNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjRiZDliMDcwN2JhNjkwM2NhYTM3MTIzYmFjYWRjMTkyOTY2NmM3MjljYWQ2ZGYyMzEyNTQ2NWViODEyNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoMq5RSatRY-dv3topavUwICchWpudi-gBjRoUISLvE)
> 
> * claim
>   ![image](https://private-user-images.githubusercontent.com/80429191/288476486-fa9ee213-4851-44e2-bac5-5700d7658768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQyNjMsIm5iZiI6MTcwMjI5Mzk2MywicGF0aCI6Ii84MDQyOTE5MS8yODg0NzY0ODYtZmE5ZWUyMTMtNDg1MS00NGUyLWJhYzUtNTcwMGQ3NjU4NzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDExMjYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWY4YmI4OWEwOWYxYzk3MGViYjA2NjliOTRhODVmMjY5NGI1ZmJhMjMzOTM2NWQ3ODNmYTM3NGQ0YWZjYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lgv1jdv_HX4HXG8_kOHq2jDfhlm235PMl4BiY6qqTRU)

ready to be retested

**Comment by polikosi** [comment]
Add link "See in portfolio in each stages" 
![image](https://github.com/Joystream/atlas/assets/80429191/15dbd4c4-7e6b-4bb8-a941-536e626dde56)

I didn't receive a notification about the start of revenue share
![image](https://github.com/Joystream/atlas/assets/80429191/7b87b8ee-3c40-48a1-bc54-bfcc5215614b)


- less than 48, more than 24
ACcording to the design there should be shown relative date and time. For example: Tomorrow at 11:00
![image](https://github.com/Joystream/atlas/assets/80429191/470ba836-48bd-4611-8001-9f65ac1badd1)
