### ISSUE TITLE
Holder: Token Portfolio

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3856]
## Context
- #3384 

## Scope
- [ ] Potfolio link in profile drop down
- [ ] Empty State
- [ ] Tokens Table

## Design
[Link to figma> ](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1201%3A163788&t=XolD3kk1lOSp2O9T-1)

Preview: 
<img width="244" alt="Screenshot 2023-02-17 at 15 23 13" src="https://user-images.githubusercontent.com/93924525/219638269-ddec850d-42aa-49e5-89ce-f67c36d40823.png">

<img width="673" alt="Screenshot 2023-02-17 at 15 22 07" src="https://user-images.githubusercontent.com/93924525/219638305-9a56aed0-d647-4a60-990f-bd07b129dad2.png">

**Comment by polikosi** [comment]
Remove one $ sign in the Transerable column
![image](https://github.com/Joystream/atlas/assets/80429191/dba9eb5f-7d2f-45c7-97c3-e2688d3404e2)

**Comment by polikosi** [comment]
I expected the NFT tab to open because I have an NFT but no tokens

https://github.com/Joystream/atlas/assets/80429191/597cd0d1-6a08-4d00-9fe3-bcf41d229a94

**Comment by WRadoslaw** [comment]
> I expected the NFT tab to open because I have an NFT but no tokens
> 
>  2023-12-14_18h34_58.mp4

@KubaMikolajczyk @bedeho I leave the decision to you, we still display 2 widgets and joy balance info in the first tab, I dont see a reason to skip it bcs user has no CRTs

**Comment by bedeho** [comment]
> I leave the decision to you, we still display 2 widgets and joy balance info in the first tab, I dont see a reason to skip it bcs user has no CRTs

I guess the question is what is shown by default when you only have one or the other? perhaps it can add some value by just showing the one you have if you only have one, and if you have both, I guess it shows last opened? What do you think of that?
