### ISSUE TITLE
Holder Portfolio: Buy from Sale/ Sell and Buy from AMM

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3859]
## Context
- #3384 

## Scope
- [ ] Controls to start 

AMM: 
Sell 
Buy

Links to the same flow as buying/ selling from the token details page, but redirects to portfolio with conf message after

## Design
[Link1>](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1202%3A71665&t=XolD3kk1lOSp2O9T-1)
[Link2>](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1232%3A55795&t=XolD3kk1lOSp2O9T-1) 
[Link3>](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1232%3A55802&t=XolD3kk1lOSp2O9T-1)

Out of scope ⛔ 
Sale: 
Buy

**Comment by polikosi** [comment]
AMM 
Buy:
I can't buy on portfolio page but I can buy from the token page.
![image](https://github.com/Joystream/atlas/assets/80429191/413bf9de-7286-45ff-9756-d36d21d08453)

Sell: 
Doesn't have a Sell button
![image](https://github.com/Joystream/atlas/assets/80429191/0b7f1501-4aab-4579-9a8c-0fa973521178)

**Comment by dmtrjsg** [comment]
@polikosi can you pls add the list of links with bug descriptions as comments to the master QA tracker issue?

**Comment by polikosi** [comment]
Sell:
No "Sell" button
![image](https://github.com/Joystream/atlas/assets/80429191/05c3f51d-3312-45ac-8d4a-e270b5f4c87d)
