### ISSUE TITLE
Holder Portfolio: Notifications (revenue share)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3861]
## Context
- #3384 

## Scope
Notifications for token holders: 

- Rev share created 
- Rev share started
- Revenue share ended
- Token sale started
- Market started

## Design
[Link to Figma>](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?node-id=1912%3A56091&t=JZq1rBRilvJyYlL2-1)

<img width="904" alt="Screenshot 2023-02-17 at 15 40 48" src="https://user-images.githubusercontent.com/93924525/219644911-308eb2d0-10ef-43c3-8f21-de4fa39d0fb5.png">

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg Holders notifications are ready to be reviewed ✅

🎥 Video update (1:30, really short explanation of all new notifications): https://www.loom.com/share/9c495dcd7b9e40da86a9738d1f6b9253?sid=fdbe3acc-141d-40a2-8fab-f2566c7686ed

📄 Notifications events changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=3272-20368&mode=design&t=pgqmuSktkmpn8ROv-4

📄 Membership profile settings changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=3537-76643&mode=design&t=pX7smdnfUJpdZVu2-4

**Comment by ikprk** [comment]
That's already done in app
