### ISSUE TITLE
Holder Portfolio: Revenue Share widget

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3862]
## Context
- #3384 

## Scope
- [ ] Revenue share widget
- [ ] Revenue share all timer variations
- [ ] Expandable section for multiple shares

## Design
[Link to Figma>](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1274%3A68836&t=XolD3kk1lOSp2O9T-1)

**Comment by polikosi** [comment]
As you can see in the screenshot, there is no expanded section for multiple shares, while I have more than 3 active ravenue shares.

![image](https://github.com/Joystream/atlas/assets/80429191/8a750cf8-1e5a-4067-9722-dc4c02b437cd)
![image](https://github.com/Joystream/atlas/assets/80429191/5ef583ca-f772-46c2-9ed6-b68f07aeb723)
