### ISSUE TITLE
Holder Portfolio: Stake Tokens for Revenue share

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3863]
## Context
- #3384 

## Scope
- [ ] Revenue share - stake tokens  flow 
- [ ] Revenue share - submit tx
- [ ] Locked tokens display in table

## Design
[Link to Figma>](https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/My-portfolio?node-id=1274%3A68836&t=XolD3kk1lOSp2O9T-1)

<img width="656" alt="Screenshot 2023-02-17 at 15 46 32" src="https://user-images.githubusercontent.com/93924525/219645931-581350b5-1c6e-4b88-9011-104c8772a290.png">
<img width="429" alt="Screenshot 2023-02-17 at 15 46 22" src="https://user-images.githubusercontent.com/93924525/219645941-7780c4a2-738b-4793-a273-2384b6d3b088.png">
<img width="613" alt="Screenshot 2023-02-17 at 15 46 19" src="https://user-images.githubusercontent.com/93924525/219645946-8742087d-5733-4808-bdc0-e03cbdd95ffb.png">

**Comment by polikosi** [comment]
blocked by this https://github.com/Joystream/atlas/issues/5600#issuecomment-1843215484

**Comment by WRadoslaw** [comment]
> blocked by this [#5600 (comment)](https://github.com/Joystream/atlas/issues/5600#issuecomment-1843215484)

ready for restest

**Comment by ivanturlakov** [comment]
Tested on https://atlas-dj3xj8za5-joystream.vercel.app/portfolio

✅ Revenue share - stake tokens flow
✅ Revenue share - submit tx
⚠️ Locked tokens display in table

🔒 icon missed(your tokens column)/alignment
<img width="1322" alt="Screenshot 2023-12-21 at 17 19 20" src="https://github.com/Joystream/atlas/assets/46903215/10815588-5456-4d39-ab87-009f8a486e22">
**Design**
<img width="1248" alt="Screenshot 2023-12-21 at 17 23 42" src="https://github.com/Joystream/atlas/assets/46903215/ec634fc6-9d21-47ba-aedd-ddd3d2787a26">


ALC & QWE are Locked, pls add 🔒 icon (not sure maybe the icon is only for vesting case)
<img width="1322" alt="Screenshot 2023-12-21 at 17 39 06" src="https://github.com/Joystream/atlas/assets/46903215/9e75a96d-ce12-4c4a-a3d2-7a72ff93afbf">
**Design**
<img width="1164" alt="Screenshot 2023-12-21 at 17 40 55" src="https://github.com/Joystream/atlas/assets/46903215/52e51de2-4877-46b9-b82f-8125f644bd66">
