### ISSUE TITLE
Retest setting auction

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3872]
## Context
https://github.com/Joystream/atlas/issues/3821#issuecomment-1441711123

**Comment by drillprop** [comment]
Tested with three different auctions on `orion v2` branch and `dev` branch and I can't reproduce. I think you had some connection issues. 
Also, you said to me yesterday that you didn't know how to set English auction that lasts shorter than a day. You can do this, you need to just select pick specifying the date in the NFT form and select the correct hour and date 
![image](https://user-images.githubusercontent.com/51168865/221156716-59ec117d-97ac-4242-b957-37e996e2c522.png)
