### ISSUE TITLE
Error codes display for infra/ services outage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3885]
> When we say the service does not work, what type of error would user be exposed to?

Creators will not be exposed to these errors, since they are interacting with Atlas and Atlas does not know about anything apart from Onboarding component. 

If error is in the onboarding component then the error will be returned > (Google API is down or QN is down or Quota is finished).
Error codes exist and returned by BE for:

* [ ] Quota is limited @attemka to add "Sign up quota is reached. Please try again later."
* [ ] Google APi is down - same error code as comes from YT @attemka to  add "Google API is down. Please try again later."
* [ ] QN is down - signups/ video creation/ upload to storage node not working; Zeeshan Akram will add error code - "Query Node is down. Signups, video creation and upload to storage node is impacted. Please try again later."

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204079184129674) by [Unito](https://www.unito.io)

**Comment by attemka** [comment]
blocked by https://github.com/Joystream/youtube-synch/issues/156
