### ISSUE TITLE
Video page takes 15 seconds to load

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3886]
## Context
New videos take 15-20s  to load, which is in the dead zone from usability pov:
- https://gleev.xyz/video/917

The performance was not great last week (circa 4-6 seconds to load) but deteriorated dramattically. 

We've looked into it on the standup and concluded that fetching distributor node details takes 15 sec. Bad requests were found on QN logs. Orion instance was moved recently so that may have contributed to it. 

Issue requires further investigation. 

## Scope
- [ ] Investigate and define the root cause of the issue
- [ ] Suggest treatment on how to fix it

**Comment by drillprop** [comment]
So the main suspect is the `GetDistributionBucketsWithBags` query that we're running initially on the page. We need to run this to resolve the assets and display them on the page. 
```
fragment DistributionBucketOperatorField on DistributionBucketOperator {
  id
  metadata {
    nodeEndpoint
    nodeLocation {
      coordinates {
        latitude
        longitude
      }
    }
  }
  status
}

query GetDistributionBucketsWithBags {
  distributionBuckets(limit: 100, where: { distributing_eq: true }) {
    id
    bags {
      id
    }
    operators {
      ...DistributionBucketOperatorField
    }
  }
}
```

In the query response, we're getting thousands of bags of ids.

https://user-images.githubusercontent.com/51168865/222097278-e20614a2-05c7-4234-bae0-ab08da8630c4.mov

And the reason why there are so many bags is that someone created thousands of channels recently(check the daily channels created) https://dapplooker.com/dashboard/joystream-mainnet-dashboard-328 

I think we did this that way to avoid fetching nodeEndpoint for every asset separately. With the current approach, we do this only once. Unfortunately, the query is taking 10-15 seconds.   We need to change the approach to how we resolve the assets. The code responsible for it is inside of `assets.provider.tsx` 


@kdembler I know, you worked on resolving assets, feel free to chime in. Any ideas on how we could resolve this problem?

**Comment by attemka** [comment]
So here's my thoughts on solving this issue, partially they're taken from the brainstorm with @WRadoslaw and @drillprop:

The goal for us it to get the operator for all the assets appearing on the page, so I don't think we need to fetch every single bag of the operator. So I think the process of the fetch should look like:

1) collect all the bags names from the content fetched
2) request all the distribution buckets containing selected bags
3) select the closest bucket

Query execution example for 50 buckets in the request:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/13239251/222133097-120cd00b-d4ec-44ac-9d28-cc0adba25ae3.png">

**Comment by kdembler** [comment]
Yeah, the current approach is definitely not scalable, imagine what this would look like if we had millions of channels.

> I think the process of the fetch should look like:
>
> 1. collect all the bags names from the content fetched
> 2. request all the distribution buckets containing selected bags
> 3. select the closest bucket

I think that sounds promising, although may be a bit tricky to decide when all the content is fetched. Btw, have you guys experimented with fetching the providers alongside the content? So including operator data with every video that's fetched? My guess is it may be as slow as this huge query because of all the nesting, but maybe worth checking?

**Comment by attemka** [comment]
@kdembler I temporarily changed query for fetching providers. Orion v2 will support provider selection on the backend side.
