### ISSUE TITLE
Learn more button is wrongly displayed on the `connect with youtube` modal

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#3899]
![image](https://user-images.githubusercontent.com/51168865/223355027-676388c3-97a7-4437-a341-1758c8831525.png)

Learn more should be a single line of text

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203868726963296/1204143527653570) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
@attemka also noticed the same issue here, didn't test this on preview branch but hoping solution would cover this as well ;) 

<img width="668" alt="Screenshot 2023-03-10 at 18 26 34" src="https://user-images.githubusercontent.com/93924525/224355976-cd6d40e7-b779-4abe-be83-ba5d80330873.png">
