### ISSUE TITLE
Member Remarks payments do not get displayed in payment table

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3920]
## Context

ER: Member Remarks Payments shown in the payout table by the channel
AR: Payments did not appear

CLI tx:

![Screenshot 2023-03-13 at 19.05.04.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/90828331-6787-4842-aa4e-15095002ccb7)

TX: 

Sending members.memberRemark extrinsic from tomatoCharge...
Tx params: [
  [
    '21',
    'R4\n2rational example: YPP rewards cycle 12; total:2000',
    [ 'j4To6jgKfy8MgiMRDXzc15ggN8AnFAS8cUFkx3tReSy1TWA8y', '2,000' ]
  ]
]
? Tx fee of 13.9027 mJOY will be deduced from you account, do you confirm the 
transfer? Yes
Extrinsic successful!
Member 21 successfully paid channel 4 with amount 2000!

┆Issue is synchronized with this [Asana task]
(https://app.asana.com/0/1202078489349362/1204168278838062) by [Unito](https://www.unito.io)

**Comment by WRadoslaw** [comment]
Two things: 

1. Not sure why, but I don't see your payment on the Orion. 

Here is a query(https://atlas-next.joystream.org/orion/graphql): 
```
query MyQuery {
  events {
    data {
      ... on MetaprotocolTransactionStatusEventData {
        __typename
        result {
          ... on MetaprotocolTransactionResultChannelPaid {
            __typename
            channelPaid {
              id
            }
          }
        }
      }
    }
  }
}
```

2. Even if this event would be on there, it offers only the data about the channel that is being paid. So there isn't really a way to determine sender and description.

![image](https://user-images.githubusercontent.com/92513933/224943167-a01feac3-ac30-4f16-9884-3a70026761c2.png)
