### ISSUE TITLE
Cannot put NFTs already bought on Sale or Auction

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3921]
## Context

Cannot put already purchased NFT on sale
ENV: https://atlas-flhjkrzad-joystream.vercel.app

VideoID=3

⚠️ Same with Video=4 (Owned by other member)

<img width="1500" alt="Screenshot 2023-03-13 at 19 33 19" src="https://user-images.githubusercontent.com/93924525/224766831-4ee35ce2-f4fe-4c0e-b567-77f306c803e2.png">

![Screenshot 2023-03-13 at 19.33.57.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/44804470-c0d8-4bd0-85eb-fe31254fd20e)
ACC = tomatoCharge (ask me for JSON if you need to retest)

**Comment by WRadoslaw** [comment]
Both of these NFTs are in the sale, ID 3 is listed as buy now and ID 4 as open auction. 

Data polkadot explorer:
ID 4:
```
{
  inChannel: 4
  nftStatus: {
    owner: {
      Member: 17
    }
    transactionalStatus: {
      OpenAuction: {
        startingPrice: 200,000,000,000
        buyNowPrice: 500,000,000,000
        whitelist: []
        bidLockDuration: 300
        auctionId: 2
        start: 86,959
      }
    }
    creatorRoyalty: 2.00%
    openAuctionsNonce: 2
  }
  dataObjects: [
    22
    23
  ]
  videoStateBloatBond: {
    repaymentRestrictedTo: j4WJCiLsSS8L8UqvQk1pnjfRAnPwmhQqZ62rLyUeAApqSaWbd
    amount: 2,467,438,100
  }
}
```

ID 3:
```
{
  inChannel: 4
  nftStatus: {
    owner: {
      Member: 18
    }
    transactionalStatus: {
      BuyNow: 100,000,000,000
    }
    creatorRoyalty: 5.00%
    openAuctionsNonce: 0
  }
  dataObjects: [
    20
    21
  ]
  videoStateBloatBond: {
    repaymentRestrictedTo: j4WJCiLsSS8L8UqvQk1pnjfRAnPwmhQqZ62rLyUeAApqSaWbd
    amount: 2,467,438,100
  }
}
```

I guess this could be a mapping problem since I don't see any associated events. 

cc @Lezek123 

Playground: Atlas Next

**Comment by Lezek123** [comment]
My bad, the event processor on atlas-next was dead for a while due to a deployment mistake I made which prevented it from restarting. It should be up to date now.

**Comment by dmtrjsg** [comment]
Resolved
