### ISSUE TITLE
Better removal visuals from Continue Watching

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#393]
When I remove a single video, all videos temporarily disappear, a full row of loading items is displayed for a brief moment, and then the actual videos snap back in without the video I removed. This does not look very good.

1) Removal of a given video should not result in hiding others, even temporarily.
2) The single video should gracefully disappear, and the adjacent videos should slide in to take its place, or something like this. I know the animations will get redone later by the designers, but this looks quite rough as is.

**Comment by kdembler** [comment]
Yeah, I really didn't like this behaviour but this was a technical constraint for the current release related to how we fetch the data (it was always batched, so we needed to refetch the full batch). Things changed and we should be able to achieve this much more easily after `sumer` gets merged
