### ISSUE TITLE
Channel Balance > Total Earned by 1 JOY

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3930]
## Context

There's a discrepancy between Total Earned and Channel balance for all NFTs + Royalties of 1JOY. 

## Details

Channel ID = 4
Env = https://atlas-flhjkrzad-joystream.vercel.app/studio/payments

![Screenshot 2023-03-15 at 13.02.20.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/c8874594-9eab-4a91-b88b-bc196f0b55d3)

After resell of other NFT:
<img width="1378" alt="Screenshot 2023-03-15 at 13 10 29" src="https://user-images.githubusercontent.com/93924525/225278008-308391f6-4a40-424f-92f4-bfa5cd81ef87.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1204183707299476) by [Unito](https://www.unito.io)

**Comment by drillprop** [comment]
Everything looks good to me. Tested on: https://atlas-8negieozg-joystream.vercel.app/studio/payments

![image](https://user-images.githubusercontent.com/51168865/225563483-e5f6550e-847c-47c6-89db-8c3716b24614.png)
