### ISSUE TITLE
Referred accounts showing in the YPP dashboard

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3979]
## Context

In referral programs it's quite common for the referrer to add some incentive to the referee, to use their sign up link, since there is no inherent incentive for the referee to do so, unless that is built into the program, which I don't think is the case here(?)..

If referrer is able to see who they have successfully referred, they can manually reward the person for using their link, however they wish, retroactively..

Referrer could for example say: if you use my referral link I will split the reward with you. Now referee is incentivized to use the referral link

## Scope
- [ ] Display channels that signed up using referrer link in the YPP dashboard of the referrer

Channel Titles/ Avatar / Their Popularity Tier and How much that was in USD for the referrer

**Comment by KubaMikolajczyk** [comment]
The work is done and ready to be reviewed ✅

I added an additional tab with referrals table, a bunch of user stories explaining the behavior & RWD to explain the resizing of the new page everything is covered in this changelog.

📄 Youtube Partner Program changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=WEVuCMrGgopEKM9M-4

**Comment by dmtrjsg** [comment]
Love the approach, added one small comment to figma re column header title, and have a question: should we also add a notification for this so the "unread" referrals counter cascades up to the channel notifications?

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg loved the idea about the notification - I added a new notification event for the publisher to notify about someone using your referral link to sign up.

📄 Notifications changelog: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=1111-55611&mode=design&t=fADraqjLeIHfdvvX-4

* I also implemented your comments to the designs so everything is done ✅

**Comment by dmtrjsg** [comment]
Exclude sorting for the first release..By default let's show newest referrals on top.

@ignazio-bovo can you pls add [this ](https://github.com/Joystream/atlas/issues/3979#issuecomment-1635460815)to the notifications tracker in the resolver list.
