### ISSUE TITLE
Confusing pagination

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#3989]
https://gleev.xyz/channel/7712?tab=Videos

It looks like the pagination is broken: two pages are selected at the same time.
~If page 8/12 has no videos the user should not be able to select it.~
~If it's a loading in process thing it shouldn't say "No videos in this channel".~

![pagination](https://user-images.githubusercontent.com/31551045/228525070-5d6d5b2f-88d9-4ea9-a13a-e3571a0c07da.png)

**Comment by drillprop** [comment]
Thanks for reporting:
>If page 8/12 has no videos the user should not be able to select it.
>If it's a loading in process thing it shouldn't say "No videos in this channel".

fixed in https://github.com/Joystream/atlas/pull/3985

> It looks like the pagination is broken: two pages are selected at the same time.

Will fix this. This is a minor CSS issue. I would consider using :focus-visible here - https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible
