### ISSUE TITLE
YPP - YouTube brand guidelines compliance

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#3990]
## Context

Google verification team requested updates to the product designs.

![Screenshot 2023-03-29 at 14.38.28.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/81765750-b00b-4eb3-937c-6f0589bde713)
![Screenshot 2023-03-29 at 15.41.18.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/22b787d1-d03e-490d-a58e-d1ea6fd85bfe)

[Link to Branding Guidelines> ](https://developers.google.com/youtube/terms/branding-guidelines)

## Scope

- [ ] Add colour YT logos next to CTAs for sign up to YPP
- [ ] Add B&W logo to the bottom of the landing page (blue banner)
- [ ] Logos must point to youtube.com

**Comment by KubaMikolajczyk** [comment]
https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=4118-100344&t=6GyIdBGH9EJx1k4A-4
The current mockup of the solution is here ✅

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk can we use these in our final designs https://developers.google.com/youtube/terms/branding-guidelines#dark-logo.

So that we do it in one go and deploy before sharing the updated flow on dev/ prod with the Google team:

- #4088
