### ISSUE TITLE
Geolocation fallback

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#3998]
For #3997 we need to take into account that in some cases the geolocation requests fail with the effect that logs will lack origin data. 

This can happen for example due to Cloudflare blocking the request (hidden bot check).

> Access to XMLHttpRequest at 'https://geolocation.joystream.org/' from origin 'https://gleev.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}

Failed to get user coordinates: Network Error 
{message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: {…}}
code: "ERR_NETWORK"
message: "Network Error", name: "AxiosError". request: {url: 'https://geolocation.joystream.org'}
```

Which fallback alternatives are available?

**Comment by dmtrjsg** [comment]
@traumschule hey man we've tried to test, but struggling. How to reproduce this error?

**Comment by traumschule** [comment]
Probably just me. Cloudflare blocks most Tor exit nodes unless one does some header voodoo like Tor Browser. Thanks for trying.
