### ISSUE TITLE
Do not fetch from buckets with `distributing: off`

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#3999]
Atlas does not filter buckets with the `distributing` flag turned off. This causes extra delays because it takes a full timeout until another provider is selected (20s each).

As bedeho [demonstrated](https://gleev.xyz/video/1301) waiting times of 40s can be experienced when two disabled buckets are selected in a row. This is a major drawback for atlas users (#3954).

Also Atlas should be able to try the same asset from multiple locations opportunistically and ditch connections with slower response time or throughput.

**Comment by drillprop** [comment]
@Lezek123 could you confirm that we already do this in Orion v2?

**Comment by drillprop** [comment]
Yeah, It looks like it, here's the change: https://github.com/Joystream/orion/pull/49/files#diff-2c0d7f07209499a345e9c6d4dcee7c7b7f1b60fb871abc8e9c5eb623f2794562R128

The Orion v2 release should happen this week. I'll close the issue after the release.

**Comment by drillprop** [comment]
Orion v2 released https://github.com/Joystream/atlas/releases/tag/v2.0.0
