### ISSUE TITLE
Create design for failed video playback

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#40]
Currently we have a design for an error-wide view - what happens when the full view fails to load. We use that in the video playback view when we fail to fetch the video metadata. However, there's also another case we have to handle - what happens when the video media file fails to load for some reason. A design should be created that handles this case

![](https://user-images.githubusercontent.com/437292/100516333-7ba7bf80-3183-11eb-8711-d08bc5de4c4d.png)

**Comment by KubaMikolajczyk** [comment]
This was covered in player component redesign.
https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=9977%3A263927
