### ISSUE TITLE
Idea: Add version info to product

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4015]
# Background

We are now entering an environment where multiple versions of Atlas may be live across distinct gateways, and there may be versions of Atlas released, but which are yet deployed anywhere. It is therefore harder for a non-operator attempting to provide user support or debugging of problems to quickly determine what features or bugs they should expect to be present or not.

# Proposal

Add some very discrete indicator of what version of Atlas a given deloyment is using in the UI itself, and also add automatically as a payload to product feedback widget. One very natural location could be here 

![Screenshot 2023-04-01 at 14 56 03](https://user-images.githubusercontent.com/437292/229290201-218fe7fa-2abc-4a1c-9c64-53d0216538bd.png)

Perhaps rephrasing "built on Atlas vX <newline> Powered by ... "

**Comment by dmtrjsg** [comment]
Add version to Adming Panel

**Comment by dmtrjsg** [comment]
On every tab: 
<img width="454" alt="Screenshot 2023-04-12 at 12 30 09" src="https://user-images.githubusercontent.com/93924525/231399782-b6b1c442-b218-4789-a023-4a464e813752.png">

**Comment by bedeho** [comment]
I again ran into this problem today, I have been told about htis admin panel multiple times, dont remember how to trigger it. Can we at least add a button to the admin panel somwhere? very discrete, people will need this in practice.
