### ISSUE TITLE
My videos view takes long to load

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#4025]
It's happening, because we are waiting for a response from the YPP backend, to get synced videos first, and after that we're starting fetching videos from Orion. 
We are doing this, because we want to know which videos are syncing in advance, to not show users failed video tiles in the dashboard when upload on the YPP backend is still in progress. 

The goal of this task will be to figure out a better algorithm that will load faster videos and won't break the syncing tiles

**Comment by kdembler** [comment]
I think part of the issue is that also you don't stop fetching after first 404 from the backend but only once it fails 3 times (with timeout in between), that's probably the react-query behaviour
