### ISSUE TITLE
Order of synced videos from YT is not matching Youtube

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4030]
YT Channel: https://www.youtube.com/@rocketstar8924/videos
Gleev channel: https://gleev.xyz/channel/21903?tab=Videos

Below two screenshots of videos sorted by data uploaded newest first. there's a big mismatch:
![Screenshot 2023-04-04 at 15.53.49.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4576d5f0-8191-4c8e-8d46-ae4f1f49267e)

![Screenshot 2023-04-04 at 15.53.56.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/c7584a6c-39c6-40d6-a5e5-1fd608536810)

**Comment by zeeshanakram3** [comment]
This is expected based on the YT-synch algorithm that picks videos to upload on Joytream. YT-Synch prioritises syncing videos with more view(on YT) over the videos with less video. That's why you see videos published in different order

One way to present the videos in the same order is to set `publishedBeforeJoystream` field in video metadata to when video was published on Youtube, and then sort the videos on Gleev based on this field instead of `newest`?

**Comment by dmtrjsg** [comment]
@zeeshanakram3 thanks for the explanation, I personally think since these videos will get featured on Homepage, and Newest and feed to the recommendation algorithms it is worth just keeping the same chronology of uploads that is done on Youtube. For time-sensitive videos like News/ podcasts/ investment reviews the recency is quite important in consuming the content so if we do not change the YT sync algorythms we are stepping into the risky zone of recommending dated videos. 

@bedeho please let me know if you think that this reasoning is flawed.

**Comment by bedeho** [comment]
Leaving aside how exactly downloading should be prioed by infra: the way it is downloaded should not be informed or depend on how the website displays content, these are separate concerns.

If we want a specific kind of property to satisfied about how videos are featured on the website, then the presentation logic for this on the website must deal with that on its own. I think you also should not really think of this real-estate as a proper discovery surface for consumers, it is just a place to show dynamic content demonstrating that the system is evolving and relevant, not a place for people to find real content to consume aligning somehow with their preferences.

**Comment by dmtrjsg** [comment]
@bedeho 

> the presentation logic for this on the website must deal with that on its own.

Ok I guess in this case we would need to introduce the logic that Zeeshan suggests and for YT-synced videos pull them to other areas of the site where they are mixed with manual uploads considering `publishedBeforeJoystream` value.

**Homepage Implication**
So let me give you an example.. With the update homepage that represents a clean feed of videos mixed from New videos uploaded (or synced), Popular videos from Channels that user follows, and Featured/ Most popular videos on Gleev, the synced videos added as part of the "New videos" must be adjusted for 'publishedBeforeJoystream' date.

**Channel/Videos implication**
If someone wants to go to channel, which has a mix of manually uploaded and YT synced videos, and views videos in the chronological order (by setting sort by Newest) we need to look at two separate properties for videos to be able to present them in the real chronological order. 

Considering how much this complicates these, is it not worth updating the syncing algorythm?

Maybe Im being thick here 😅 and easier to discuss on the call, tomorrow after standup..

**Comment by bedeho** [comment]
> discuss on the call, tomorrow after standup..

this

**Comment by dmtrjsg** [comment]
@zeeshanakram3 

Following discussion agreed to:
1. ~Prioritise sync scheduling based on the channel subscribers count, and not on videos popularity~
2. Within same channel, keep the same order of the videos for syncing, starting from the oldest to newest. So that channel/videos in Gleev after syncing has the same order of videos as there are on YT channel.
3. Record the date of upload to YT to `publishedBeforeJoystream` of newly imported videos so that this date can be further used in homepage feed/ recommendations / search results sorting in addition to the date of upload to Joystream network.

**Comment by dmtrjsg** [comment]
Issue moved to [Joystream/youtube-synch #178](https://github.com/Joystream/youtube-synch/issues/178) via [**Zenhub**](https://www.zenhub.com/)
