### ISSUE TITLE
centering logo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4044]
![Screenshot 2023-04-07 at 12.32.25.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/d552c76a-d2a3-4cac-a0bc-cacc614e91f9)

**Comment by WRadoslaw** [comment]
Not sure why, but for me, logo is centered both on gleev and atlas

**Comment by WRadoslaw** [comment]
Happens only on firefox
