### ISSUE TITLE
Display modal informing users of Web3 content upon first video upload in the studio

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4051]
## Context
We have a growing number of channels that upload non Web3 content to Gleev and then enquire why their channel is taken down

## Scope
- [ ] Add modal to the first upload of video that informs users about Web3 focus and that channels who do not comply this may be taken down from Gleev. 
- [ ] This should be some sort of an image rather than text as everyone needs to read it

@ Dev modal needs to be configurable
- [ ] Add this to config as URL to image, if not added we don't show this popup modal up

**Comment by KubaMikolajczyk** [comment]
The work for this issue is ready to be reviewed ✅
🎥 Loom video (8min): https://www.loom.com/share/169d0b6a1328497782fa5f59c1b14f02
📄 Figma files: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos?node-id=2209-38682&t=Ll1xad3bTlRnlUD3-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk  Let's go with your recommendation of showing category pills with white text.

Copy: 
H: Content policy
B: Gleev solely focuses on Web3 and Crypto content falling under a range of categories shown above. Please make sure that newly uploaded content is correctly mapped to the category. Uploading content on other topics will result in your channel been excluded from the App.
Consent: I will adhere to the content policy when uploading new videos.

**Comment by bedeho** [comment]
- Question: will the icon used when showing the categories require new icons, or does this reuse the category icons?
- I think the emphasis on the categories actually is not the most effective way of communicating the point of this screen, all the work is actually being done by the title, and the one word `Web3` here. If I show you just the categories, this could in principle be about lots of different things.
- Wouldn't it be easier to just have the title and text, both communication and engineering wise?
- Remember quite apart from everything else that operator should be able to configure app to not show such a screen at all, e.g. if they don't have any particular content focus they feel needs to be explicitly stated.

**Comment by KubaMikolajczyk** [comment]
Thank you for your feedback guys 🙇‍♂️

@bedeho 
> Question: will the icon used when showing the categories require new icons, or does this reuse the category icons?

We have quite a few category icons designed already - the current set is 27 unique icons - we could make it possible for users to pick from them for their categories in platforms, and possibly propose a set of colors to pick for the categories as well to try and keep the best usability of those colors (with a possibility to choose custom).

> I think the emphasis on the categories actually is not the most effective way of communicating the point of this screen, all the work is actually being done by the title, and the one word Web3 here. If I show you just the categories, this could in principle be about lots of different things.

I agree that the category pills are not the most important here. I wouldn't treat it though as a stand-alone solution for conveying the message (that you have to upload content of some kind - as you pointed out those categories can surely be used for different types of content) but rather as a visual supplement to the main message which is indeed conveyed by the header and copy of the dialog.

> Wouldn't it be easier to just have the title and text, both communication and engineering wise?

Displaying categories of the platform in form of pills on the dialog is additional engineering work. Not so big from my POV but we would need an engineer to tell us the estimates here - ultimately if we don't believe that those would add to the experience of this dialog then we shouldn't invest time in it. 

Communication-vise though I see it as a nice supplement - we give a possibility for the user who starts their publishing journey to ask themselves if their content, first of all, is of the right type (like in Gleev's case Web3 type) and then if this Web3 content they produce fall under any of available categories - alternatively, the user will learn about categories only later in the video workspace form where they will be required to pick one for their video. So to sum up from the point of communication I see there an opportunity of familiarizing user with this concept early.

> Remember quite apart from everything else that operator should be able to configure app to not show such a screen at all, e.g. if they don't have any particular content focus they feel needs to be explicitly stated.

Yes this dialog should be 100% optional - but can be a nice feature to offer for operators. As I imagine you can only have so many platforms that host "all content" and there is much bigger potential in making platforms that touch on specific "niche" - the need for this solution came from gleev which is the exact case I mention here so I assume this is likely to be repeated by others.

**Comment by dmtrjsg** [comment]
So after speaking with the dev team we thought that since there is no restriction on the number of categories at a large number that may be problematic.. 

Let's just go with the hard and fast version which has an image on top, rather then category pills. 

Also since the App_content_focus is already present in the config as Web3 and Crypto we will go with this option: 

<img width="566" alt="Screenshot 2023-04-13 at 12 32 03" src="https://user-images.githubusercontent.com/93924525/231702311-f05adda0-aa23-4d59-914a-b0ecd07a90ae.png">

<img width="565" alt="Screenshot 2023-04-13 at 12 33 29" src="https://user-images.githubusercontent.com/93924525/231702506-07f83209-e526-476c-814c-64ee556c6c55.png">


cc @KubaMikolajczyk @bedeho

**Comment by bedeho** [comment]
> Let's just go with the hard and fast version which has an image on top, rather then category pills.

Do you mean that you can't configure it? I think that would be a mistake. Remember that someone may also want to have an experience where  categories really have no user facing function at all, so the discover tab is hidden and users dont know they exist. I also think that for certain types of content verticals the imagery in that picture would actually just cause confusion.

**Comment by dmtrjsg** [comment]
No I mean without the categories displayed in the modal. We already have all params for putting together this modal (like AppContentFocus and AppName), and image will also be configurable. 

Sorry I meant fast, but not hardcoded 😅
