### ISSUE TITLE
Quick win: better information on playback problems

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4056]
# Background

A major UX problem currently for any Atlas instance is that playback often is very slow, or fails entirely. I have tended to just assume that that this is always a content delivery problem, but after getting some hand holding I got to the bottom of this case today

![Screenshot 2023-04-09 at 00 19 08](https://user-images.githubusercontent.com/437292/230744844-7adbe829-049f-40de-8a03-9f5e15650f0c.png)

Here one clearly sees that its not a delivery problem, its a codec problem. This source of playback problems is likely pervasive, as we don't have transcoding at this time. There are however probbably many other problems that can manifest in the same way, and the user currently has no easy way of understanding what is wrong, and if a support person looks at the screenshot, they also will not easily know. In the future we will have transcoding and better infra logging, but until then, and probably complementary to it, there may be a case for doing better on making errors a bit more intelligible to users while the platform is in the early stages.

# Problem

Make the slightest and most discrete form of error explanation somewhere in the playback screen, which can explain what exact problem may be the source at any given tim. It should be discrete and short, but again granualr enough that it can distinguish say distributor not being resolvable, from it just not responding, from it jsut being super slow, from the codec being a problem, etc.

**Comment by dmtrjsg** [comment]
For playback options: 

- there is lack of connection, 
- ssl bad, 
- extremely slow 
- bad codec

and other issues we need to be able to handle and display error in the UX for the users
