### ISSUE TITLE
Wrong comments under a video

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#4076]
To reproduce:
1. Go to https://gleev.xyz/video/2351 
2. Check the comments
3. Click one of the channel's videos in the `more from` section here 👇🏻 
![image](https://user-images.githubusercontent.com/51168865/231670910-3b19c8d7-f320-420d-bb8a-bfe652865e40.png)
4. Check the comments on that video
5. Go back to the same video from point one - `2351` by clicking on the video in the `more from` section
6. Recheck the comments. You'll notice that you see the same comments from nr 4. Comments are not loaded

**Comment by dmtrjsg** [comment]
Looks like its a cache issue. We need to somehow refetch the correct comments.
