### ISSUE TITLE
Add ability for users to trigger admin panel from the footer of the side nav

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4086]
RN we use ctrl+shift+D to trigger admin panel. The suggestion here is to surface this trigger to UI. Smth subtle to the footer of the side nav could work.

**Comment by dmtrjsg** [comment]
hey @bedeho do you still believe in the need for this issue?

**Comment by bedeho** [comment]
yeah I would say so acually, I still was strugglign to open it today when you gave me direct instructions, because it was not +dev, it was +d, perhaps I was being dense, but to me its a no brainer, 0 effort, has value to key people doing customer support, debugging, makes life simpler, no users are harmed

**Comment by KubaMikolajczyk** [comment]
@bedeho @dmtrjsg - Is this little link called "Admin Panel" in the bottom enough for us or do we want to put some additional emphasys on that? 
![image](https://github.com/Joystream/atlas/assets/31144205/c1decd1f-765b-48f5-b32e-e03de49a7a92)
📄 Link to component: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=216-100911&mode=design&t=hQt2OaAqyc38fMsz-4

**Comment by dmtrjsg** [comment]
I'd put that link underneath Joystream not to mix up with the legal info links...

**Comment by KubaMikolajczyk** [comment]
> I'd put that link underneath Joystream not to mix up with the legal info links...

I dont know if keeping all links together is an issue here and putting it under the Joystream takes a lot of vertical space from the sidenav footer + breaks the layout a bit look: 
![image](https://github.com/Joystream/atlas/assets/31144205/db678246-fbc0-4d30-841d-ac5d5b22cf6d)

We can add it next to the Github link like that wdyt? 
![image](https://github.com/Joystream/atlas/assets/31144205/834a6c8b-85e4-43bb-a5eb-3a5e3f2b666a)

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk Yes next to the GH icon is best,. great job 👍
