### ISSUE TITLE
Google Oauth branding guidelines

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4088]
## Context

Request from google verification team:

If your app uses Profile and Email scopes for Google user account sign-in, make sure that this sign-in button complies with the [Google Sign-in Branding Guidelines.](https://developers.google.com/identity/branding-guidelines) 

Also ensure that any in-app branding (including in any buttons used to launch the Google Product OAuth integration) comply with the [Google APIs Branding Guidelines](https://about.google/brand-resource-center/guidance/apis/) . If your app uses any of the following products, please comply with product-specific branding guidelines:  

YouTube API

## Scope

1️⃣  Add Youtube logo and Google logo to YPP landing page. 
2️⃣  Add info to YPP landing page "Gleev uses Google OAuth to get access to your public profile and account email address as part of sign up flow, and integrates with YouTube API to obtain details about your YouTube channel data, such as followers and video statistics. 
3️⃣   Add google branded button to the modal which triggers Oauth screen

I think its safer to use Google provided button for that.

Assets are available on the linked page. Includes sign-In buttons in PNG, SVG, EPS, and Sketch formats, in many resolutions. Includes base, hover and press states.

These files require the [Roboto font](https://developers.google.com/identity/branding-guidelines#font).

**Comment by KubaMikolajczyk** [comment]
All requirements are implemented into designs ✅
https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=3338-84773&t=Mk6227nURJ9RE5ux-4

**Comment by dmtrjsg** [comment]
Button style: https://developers.google.com/identity/branding-guidelines

**Comment by dmtrjsg** [comment]
@WRadoslaw let's asdd "sign up with Google to the Landing page in all places instead of Sign In. 

And push the changes... this is most likely what they meant and based on some more research on similar sites who sign up with Youtube that's what they've done. 

+ We don't need to show Youtube and Google accounts next to all sing up buttons on the landingj page, but all of them need to be "sign up with google".


I've also fired an email to the google team but most likely thats what they meant.. 

cc @attemka @KubaMikolajczyk
