### ISSUE TITLE
Idea: YPP onboarding flow simplified

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4091]
Note: I think there was an issue for this _somewhere_, but I cannot find it now.

# Background

I was on a call with a new creator while onboarding, and it struck me that its kind of pointless to require them to populate channel metadata, and even membership creation. They really just want to skip it and move forward. Some extra evidence that people even are willing to setup a blank profile for a real youtube creator account is that among the currently verified accounts we see multiple not setup yet even in terms of avatar.

![Screenshot 2023-04-17 at 22 54 08](https://user-images.githubusercontent.com/437292/232608418-7488230d-3ae6-475f-af16-4b37b8b471ef.png)

I have not looked at full profiles, in terms of cover photo, descriptions, names, but I suspect multiple components may be missing even for the other ones.

# Proposal

Signing up through YPP flow requires no manual data entry or uploading of any kind. Even hiding membership profile setup, or simplifying it to just set handle or something, basically trying to strip it even further down to the absolute bare minimum. This will require changes both in youtube-synch and Orion, and obviously Atlas, and it may also interact with the new user accounts work in Orion, depending on when we want to release this. It may be best to just aim for releasing this simplification with user accounts, and just focus on having new designs or that version of Atlas may be simpler

**Comment by dmtrjsg** [comment]
relates to #1820

**Comment by KubaMikolajczyk** [comment]
New iteration with ideas to shorten the flow for this issue is here:
🎥 Loom video: https://www.loom.com/share/ac531ccf63604ab08e72bcbda9489ebb
📄 Figma file: https://www.figma.com/file/C3hvYPVkZ7TcjAsXfqizSD/User-accounts?type=design&node-id=2433-86190&t=Wau0pqdtBoXDMwLU-4

**Comment by dmtrjsg** [comment]
After double checking with Zeeshan it is confirmed we can have the assets from YT channel fetched via API to pre-create the membership and channel, namely:
- Use YT channel name as both Membership Handle and Channel title.
- Use YT channel avatar as avatar for both
- Use YT channel description as Joystream channel description. 

There's no harm in pre-creating the above as opposed to pre-populating the form-fields as creators can edit the assets after creating the profile. 

The challenge of doing everything automatically would only be in assuming their category for syncing. That leaves me with the idea that the final screen of the journey could be their "ypp dashboard settings where they'd need to select the category and confirm syncing. This in fact may be beneficial for another reason, as we will get this message about auto-syncing enabled right away crystal clear and can avoid tinkering with the messaging on the success modal: 
- https://github.com/Joystream/atlas/issues/4146


+ Feedback on Loom video: 
0. We need to keep the disclosure message somewhere in the flow `Gleev uses Google OAuth to get access to your public profile and account email address as part of sign up flow, and integrates with YouTube API to obtain details about your YouTube channel data, such as followers and video statistics.` Possibly moving it out to the landing page if modal will get deprecated. This is a strong requirement from the Google Auth team.

The shortest flow I envision in case we don't want to land them to the settings page with category selector (which is probably not ideal on a second thought) would be:

1. landing page (cta - sign in with Google) -> 
2. google Auth page (we cannot customise it) ->  
3. provide password -> 
4. save seed -> 
5. select category + accept t&Cs -> 
6. get on the videos page with spinner Videos will start syncing within next 30 mins.

**Comment by KubaMikolajczyk** [comment]
That is awesome! So we can skip the whole creating membership and channel part essentially here. The only part that I'm not entirely sure about is moving the auto sync process to the dashboard as the user would have to manually fire it from there after enrolling in the program - It would not be a part of one flow, user would have to make another action to do that. If we consider this approach we could just leave the dialog asking the user about auto sync enrollment & categories for videos in the flow.
![image](https://github.com/Joystream/atlas/assets/31144205/62ac30bd-fa81-46a8-9520-ef766550d3b8)

**Comment by KubaMikolajczyk** [comment]
OK basically after the above comment was updated I agree with the idea @dmtrjsg

**Comment by dmtrjsg** [comment]
Ok then let's re-do the screen removing the Opt out option from here, and only asking for category. We could probably combine it with the T&Cs step :)

**Comment by KubaMikolajczyk** [comment]
The next iteration is in ✅ ready to be reviewed
🎥 Loom video: https://www.loom.com/share/15a677d95ff841ffa957ffbdffd5ca51
📄 Figma file: https://www.figma.com/file/C3hvYPVkZ7TcjAsXfqizSD/User-accounts?type=design&node-id=2442-119862&t=Wau0pqdtBoXDMwLU-4

**Comment by dmtrjsg** [comment]
~I like the 4th iteration, I think its nice and smooth. Extra screen with requirements I feel is not out of place and saves from overloading subsequent steps in the flow 👍~

I am thinking again and why don't we go with the shortest possible path: 
1. Remove the modal (have disclosure text on the landing page)
2. Remove the "Congratulations screen" as spinner tells the story about videos being synced. 

I wonder if we should not land the users to the YPP dashboard after they sign up, as there is a banner that their channel is getting verified, before payouts are done. And they see some info on the referrals etc..

**Comment by KubaMikolajczyk** [comment]
Under 2 minutes video of next iteration ✅
🎥 Loom video: https://www.loom.com/share/9896bf9375d64713a017629a1178813d
📄 Figma file: https://www.figma.com/file/C3hvYPVkZ7TcjAsXfqizSD/User-accounts?type=design&node-id=2442-119862&t=Wau0pqdtBoXDMwLU-4

**Comment by dmtrjsg** [comment]
Nice! 

The flow is good, all we need is to slightly rework the content of this modal :

<img width="580" alt="Screenshot 2023-05-29 at 20 43 13" src="https://github.com/Joystream/atlas/assets/93924525/06982728-40f5-43b0-8650-84a7424e9b43">

Change H1 to. Youtube Auto Sync
Change undercopy to: Gleev automatically syncs all your YouTube videos. 
Remove: learn more link

I think re Web3 content banner -> this can go to the YPP dashboard to the "When will I get paid?" by means of extra copy: "We only reward crypto / web3 content creators. All other channels will be suspended from the programme and removed from Gleev."

But honestly I think we can change the landing page slightly, from what we have now in the highlighted to "Get Paid For Syncing Crypto Content"

<img width="867" alt="Screenshot 2023-05-29 at 20 48 36" src="https://github.com/Joystream/atlas/assets/93924525/6cbf21ef-7a41-43ab-9961-c551d1fa1889">

**Comment by KubaMikolajczyk** [comment]
I totally agree with the changes to the Youtube sync dialog 🙌

If it comes to the landing I'm not sure if we will benefit from changing the title as its main msg is the phrase "your YouTUbe channel" but I think we would be in the clear to even delete the banner from the dialog as well as we have this information in the subtitle. (its not in the implementation apparently but its in the designs - look at the subtitle it clearly states the type of content which needs to be uploaded)
![image](https://github.com/Joystream/atlas/assets/31144205/b51e32d9-b83f-4c0f-b51e-f48a81dadc11)

So we can just remove the banner from the dialog and after copy changes it would look like this
![image](https://github.com/Joystream/atlas/assets/31144205/eb33f538-7afc-4c30-9204-73c43bf31dc4)

Here is the link to the #6th iteration - no need to record a walkthrough I suppose at this point but just leaving it here: https://www.figma.com/file/C3hvYPVkZ7TcjAsXfqizSD/User-accounts?type=design&node-id=2444-106725&t=Wau0pqdtBoXDMwLU-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk yes totally agreed, excellent let's go with that ⭐

**Comment by bedeho** [comment]
> I'm not sure if we will benefit from changing the title as its main msg is the phrase "your YouTUbe channel" but I think we would be in the clear to even delete the banner from the dialog as well as we have this information in the subtitle. 

I don't agree with the suggested change to the title, or to remove it. Wither either change, we are reducing the likelihood people understand quickly that they dont have to start using some new thing where they have to do a lot of manual work, making a profile etc. I think the current design likely underemphasises this also. But in any case, I am guessing, and so are we all here, so lets not start doing changes for the purposes of conversion optimisation here out of context. I think we probably should think about this, but not here now.

**Comment by KubaMikolajczyk** [comment]
> I don't agree with the suggested change to the title, or to remove it. Wither either change, we are reducing the likelihood people understand quickly that they dont have to start using some new thing where they have to do a lot of manual work, making a profile etc. I think the current design likely underemphasises this also. But in any case, I am guessing, and so are we all here, so lets not start doing changes for the purposes of conversion optimisation here out of context. I think we probably should think about this, but not here now.

So we all agree to keep the current designs for the title and the landing 👌 And improve it later on

**Comment by KubaMikolajczyk** [comment]
@bedeho @dmtrjsg @attemka I updated all of the designs for YPP page with the last iteration of the flow that we agreed to move with yday and added a new flow to the sign up / log in page (& updated some local content overrides components) Everything is explained here:

🎥 Loom video: https://www.loom.com/share/44e7a6bf15a44083a8c7d602f9667cab
📄 YPP figma changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&t=SM8AnXwbF05GS2zM-4
📄 Sign up / Log in changelog: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&t=k54bnORivbshxAzj-4

**Comment by bedeho** [comment]
Thank you very much Kuba!

1. All the small text looked _brutal_, and in particular so close to the CTA, would risk making people nervous about being tricked into some fine print terms that are bad, and having to read it.
2. How is it that this is required, yet our app is live and verified? 
3. On a related note ot the last one: how is it that we are supposed to iterate on this pge, do AB testing, etc. while keeping YouTube in the loop, is there some process for how we get reapproved? do they check the page regularly? Perhaps @dmtrjsg can weigh in here.
4. I don't think we can _force_ the user to use the same email as YouTube? I think this is quite different from auto-populating with that email. I have many emails, I use them for distinct purposes, and forcing me to use a specific arbitrary one, and also not making me aware of that, is not good. Also, keep in mind that that the email in their youtube may in theory already be occupied in the backend of youtube-synch, so it may also just not be feasible, at least in theory. For these reasons I think we should suggest the youtube email if it is not already occupied in the backend, if it is occupied, we should leave the email field blank and require the user to specify.
5. I don't think we need to display "channel is being created" after signup because I assume we do not arrive at this screen if channel creation failed, I don't think that is really possible. Please consult @attemka on how this is dealt with or should be dealt with. If channel creation fails, really we are in a serious error mode. I also don't think its worht saying "channel _was_ created", because that is obvious, that is what they were just trying to do, and it just distrats from the more important message of telling them that synching is ongoing, which users easily get confused about.

**Comment by KubaMikolajczyk** [comment]
@bedeho thank you for the review 🙏

1,2 - I agree its brutal. Tbh, the only other thing we can do is to pack this text into an additional dialog and show it at the beginning of the journey. We have it on landing page only because we tried to make the journey as short as possible. Look at the dialog wdyt?
![image](https://github.com/Joystream/atlas/assets/31144205/bb45294b-0050-45ff-9191-4a564359ce22)

3. I think Dmitry will have to answer that.
4. I totally agree with that! I will make the changes
5. Also agreed! gonna change that too

**Comment by KubaMikolajczyk** [comment]
All of the feedback is implemented along with figma comments and is ready for implementation ✅

**Comment by KubaMikolajczyk** [comment]
Lastly all of the additional scenarios raised by Dima [here](https://discord.com/channels/811216481340751934/1035122951126798386/1112770841898385438) are covered:

> We need to be mindful of the cases when this flow has unsuccessful outcomes
> 1. YPP program reqs are not met -> shown right after google auth screen. User cannot progress.
> 2. Backend connection unavailable so we cannot create membership (after password is provided). User needs to try again later.
> 3. RPC node connection unavailable (so membership and channel not created) even after password is provided. User needs to try again later.
> 4. If handle already exists, then we can add a 1 or 2 to the handle.

YPP reqs not met: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=1791-99152&t=i5aqsIgdDodZOugR-4

Backend connection: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4370-92860&t=i5aqsIgdDodZOugR-4

RPC node connection: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4370-92961&t=i5aqsIgdDodZOugR-4

Instructions about using google data to create channel & membership: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4324-91252&t=i5aqsIgdDodZOugR-4

**Comment by dmtrjsg** [comment]
Implementation is here:
- #4283
