### ISSUE TITLE
Allow custom "utm" snippets for tracking email campaign efficiency via livesession

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4097]
## Scope

We need to allow /ypp page resolve even when an extra query parameter added to it like /ypp?email-campaign-123

## Context
This would be used in livesession to filter all sessions originating from a particular email campaign

**Comment by drillprop** [comment]
I don't think we need to do change in the code. It should work out of the box. 
Please try with these URLs: 
https://gleev.xyz/ypp?email-campaign=example@email.com
https://gleev.xyz/ypp?email-campaign=example2@email.com
https://gleev.xyz/ypp?email-campaign=example3@email.com

**Comment by dmtrjsg** [comment]
Yes this worked, thank you for validating this!
