### ISSUE TITLE
Glider has inconsistent spacing

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#41]
Right now, our integration with Glider has inconsistent spacing, to be more precise, it does not take into account the margin of child elements, making it hard to do things like aligning arrows to the edges of the Carousel children (see issue Joystream/joystream#1708 part 2). It also looks like the way glider is sizing children its slightly different from what CSS grid does, this effect has been observed (see Joystream/joystream#1649 ) but it might be caused by the same issue described above.

Improve the `Carousel` to work exactly like the `Grid` component does in terms of spacing and maybe introduce a `gap` to space the children elements in a way that is consistent with Glider internal workings.

If this is not possible, we might want to consider rewriting a Carousel implementation from scratch that supports this.

**Comment by bedeho** [comment]
What is the status of this?

**Comment by fcescob** [comment]
This is not actively being worked on for now. Since it might take a while to fix and we might change how the carousel works (if new design requires it), I suggest to put this off for now and re-evaluate later.

**Comment by kdembler** [comment]
New carousels don't have this problem anymore :+1:
