### ISSUE TITLE
UX Bug: Upload manager not aware of NFTs blocking changes to metadata

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4101]
# Background

This saga https://discord.com/channels/811216481340751934/1035131444080680971/1098296511089086537. 

# Proposal

There is not really a great solutoin here, except to explain that the user is permanently unable to provide an asset that failed during upload, which is really an untenable solution, as the failed upload will live there forever. Not sure what to do here.

**Comment by dmtrjsg** [comment]
@bedeho I think we should not do it, as we will remove creating and minting asset at the same time so this will not happen. For the 3 videos that sadly had this happened to them we can only hide them from Gleev on the Orion Side. So I suggest to close it, please let me know if you think otherwise.

**Comment by bedeho** [comment]
Seems like best ssolution now.
