### ISSUE TITLE
Idea: hide `not for sale` NFTs on Market page by default

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4114]
It seems that there are a huge number of NFTs that are `not for sale`, when going to the `Market` page I see tons of these and no actually "for sale" NFTs unless I change the view options.

I think that the default view should exclude `not for sale` NFTs because it makes the NFT market as a whole look like it doesn't have activity.

**Comment by dmtrjsg** [comment]
This will be superceded by 
- #3686 

which is due to get released
