### ISSUE TITLE
Combined member & channel drop down confusing

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4115]
# Background

For the longest time I have really struggled with this drop down in the app, but I was not able to articulate why.

![Screenshot 2023-04-22 at 19 48 27](https://user-images.githubusercontent.com/437292/233799204-867147b0-9554-4fd3-96e5-d0ae67f3fe97.png)

I would go there, and expect to see some things pertaining to my membership or my channel, but it would show other things, and I would see tons of identical avatars, like this

<img width="280" alt="Screenshot 2023-04-22 at 19 51 16" src="https://user-images.githubusercontent.com/437292/233799309-6235ebc8-c443-4ca7-9f06-7958e4583a39.png">

this is from the studio view, on how I even have _two_ avatars in the top menu. The avatars inside the drop down are actually two distinct buttons, while at the top they are one. Likewise, when you need to switch, the button you are looking for is dimmed out inside the dropdown, so you are extremely likely to miss it, as I have many times. This is a bit of a mess.

# Proposal

- Stop showing avatars inside the drop down, ever.
- Show one or two avatars inside the top menu, depending on whether user is in member or studio mode, and make each two distinc buttons, which show two distinct drop downs with distinct content.

**Comment by KubaMikolajczyk** [comment]
The proposed solution from me is ready to be reviewed ✅ 

In this Loom, I'll be showing you around the production and discussing how we can simplify the navigation for our users. I'll be covering topics such as the dropdowns for membership and channel, creating new channels, and logging out. I'll also be comparing our navigation to YouTube's and proposing a solution for having two different dropdowns. Chapters include: Viewer Experience, Studio Experience, YouTube Comparison, Future Navigation, and Creating New Channels 

(Oh and this description was generated by Loom's AI preety nice right? :D )

🎥 Loom video: https://www.loom.com/share/106d728ae23743d9a034b704db235846
📄 Figma explorations: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=4645%3A137109&t=86KTOo8xrUn4wowt-1

**Comment by dmtrjsg** [comment]
Loved it ❤️  nice and simple and not too many options in the menu as well, which is good. Agreed with the argumentation to keep only a single drop down in distinct views. 

Small remarks:
1. Log in / log out -> I suggest to go with Sign in / Sign out
2. Channel has its own account connected to it, which members may need to share (know) in certain cases, so let's also show it in the header of the drop down for channel view.

**Comment by KubaMikolajczyk** [comment]
The Member & Channel dropdowns are implemented in the designs with all of the feedback ✅ and also multiple other pages have user stories featuring the usage of those dropdowns - if this sounds complicated everything is explained in the video below 😄

🎥 Loom video: https://www.loom.com/share/297add3e4b134c05aef2396e9a06e495?sid=85163bd9-3919-4d4d-b9f2-aae12acfd7ed

### Components
📄 Side navigation changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9779-174960&t=k3tzxt6jSPZynH1Z-4
📄 Top navigation changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9151-168457&t=k3tzxt6jSPZynH1Z-4
📄 Account dropdowns changelog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9258-167766&t=k3tzxt6jSPZynH1Z-4

### Pages
📄 Sign up/ Log in changelog: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&t=2nP54khrpusnhNdb-4
📄 Membership profile changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2912-46498&t=6e0KbFPxhIUm9laV-4
📄 My channel changelog: https://www.figma.com/file/zi5siPUXme0Fivq2i40XBd/My-channel?type=design&node-id=703-5383&t=AQpEL1ycU1R5KYtV-4
📄 Channel changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel?type=design&node-id=2386-171791&t=Zcj33qfMlVhyDM6o-4

**Comment by drillprop** [comment]
Love the new changes! <3 The component now is super simple and straightforward.
I have one question though. Maybe I watched the loom video inattentively, but I didn't find an answer, how does the animation of showing and hiding the new account dropdown should look like? Should we use the same animation we have in dialogs? Or maybe it should be just instant, without animation?

**Comment by KubaMikolajczyk** [comment]
@drillprop thank you for watching it and Im glad you like the new solution 🙌 
You are right I missed the opening and closing animation in docs - but its now added here ✅ https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9258-167766&t=ZJV6myyoXx6X8Xdd-4
