### ISSUE TITLE
YouTube Branding Update

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4116]
## Scope

1. Remove Google brand watermark from the sign in page
2. Update Youtube Logo from Watermark to Actual Logo with The Red colour. 
3. Update CTAs on the sign in buttons to "Sign in with Youtube". 
4. Link Youtube logo with youtube.com

Logo can be downloaded from: https://developers.google.com/youtube/terms/branding-guidelines#youtube_icon

## Context

YPP sign in flow needs to be updated to comply w branding guidelines

<img width="845" alt="Screenshot 2023-04-24 at 09 36 30" src="https://user-images.githubusercontent.com/93924525/233913386-2e455122-362e-4af9-a30e-223338b2ebff.png">

<img width="566" alt="Screenshot 2023-04-24 at 09 35 44" src="https://user-images.githubusercontent.com/93924525/233913394-95841c4b-a056-4abb-ad8a-e9b52dd0cef7.png">

**Comment by dmtrjsg** [comment]
For Landing Page:
1. YouTube Logo > Convert to Red colour logo, White "YouTube"; CTA = Change text to Sign in with YouTube; Remove Google Logo
2. Same, as above, but keep Google Logo.
3. Same as above, but use Sign in with Google Design button (Change text Sign in with Youtube)
4. Use Sign in with YouTube Button (design it in red), remove the logos. 

For Popup Modal:
1. Change CTA to Sign in with Youtube, keep google button
2.  Change button to our own button, change CTA to Sign in with Youtube3.
3. Change button to Sign in with Youtube

**Comment by KubaMikolajczyk** [comment]
Variants of designs prepared for export here: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?node-id=4251-95934&t=N62yX47TNTCDc9nC-4
