### ISSUE TITLE
Update messaging that videos will get synced automatically 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4146]
## Context

![Screenshot 2023-05-04 at 17.27.35.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/1d11e3b5-9c22-4abe-aae0-b6b84da1d2d9)

## Scope

- [ ] Update this screen with more visible info that videos will start syncing  automatically within the next 30 minutes. 

![Screenshot 2023-05-04 at 17.54.35.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/2fe3be41-de7e-49a2-b74b-e79167534527)

**Comment by KubaMikolajczyk** [comment]
Tackled in https://github.com/Joystream/atlas/issues/4091
