### ISSUE TITLE
Follow up: Hero carousel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4176]
1. Hover components
2. Dim side videos more
3. Carousel does not work when only 3 featured NFTs
4. Hovering on video must turn cursor to clickable -> Clicking on video should take to video page

**Comment by KubaMikolajczyk** [comment]
Also Not showing the min bid value 
<img width="351" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/1db7c487-8400-4373-8711-5484c38e3973">

**Comment by dmtrjsg** [comment]
Due ot bug in the lib of not showing right arrow when < 3 are featured, we took the decision to add a condition and hide it in this case. Minimum number of featured NFTs that are ON SALE or will be auctioned in the future must be 4.
