### ISSUE TITLE
Marketplace implementation feedback

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#4180]
Great work on Marketplace implementation! 
I went through it and found only a few issues:

1. The hovering over avatars on NFT card don't work properly
https://github.com/Joystream/atlas/assets/31144205/6c94a0f3-fcaa-48cd-9eb6-9fb7ff207976

2. The title row in the implemented table needs a fix. Notice that on designs the number on NFTs sold is aligned together with the value to the right side & the sales volume title is always displayed in one line regardles of [screen width](https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=478-157193&t=TXPc9RTsRf8SX8y4-4)

<img width="250" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/1715f24f-fbbc-47b7-9f9d-1224571bd557">
<img width="250" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/7393613f-65e3-42a1-bb63-0056464c3e4a">

3. The hero carousel height x width ratio changes when switching to full screen
Window
![image](https://github.com/Joystream/atlas/assets/31144205/5b6de1ea-9cc1-4f0b-9745-33c399afc0c3)
Full screen
![image](https://github.com/Joystream/atlas/assets/31144205/8a23d34f-6f0e-4a57-8352-a8402a6946a1)

4. The hero carousel "item" should be clickable and should move user to the video/NFT page with the NFT widget expanded - this was not a part of the documentation for this component but as it is right now user doesn't have any optionto open the page where they will be able to interact/purchase the NFT - in short clicking on the single item in carousel should have the same effect as clicking on NFT card

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk re 3 - which ratio is the right one? ; 4 is addressed.

**Comment by KubaMikolajczyk** [comment]
> @KubaMikolajczyk re 3 - which ratio is the right one? ; 4 is addressed.

It should keep 16:9 aspect ratio - the weird thing here is that it changes the height without changing the width of the browser - same window and full screen have the same width but the height jumps a lot in the full screen

**Comment by WRadoslaw** [comment]
@KubaMikolajczyk could you elaborate on 1st point?

**Comment by KubaMikolajczyk** [comment]
> @KubaMikolajczyk could you elaborate on 1st point?

The hover effect on the avatars dims and highlights the avatar in a strange way - the avatars are highlighted only when I hover with mouse under them and stay dimmed when I hover on top of them it should be visible on the video I included there
