### ISSUE TITLE
Subwallet link from install wallet points to Chrome extension when user runs FireFox browser

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4189]
## Context

Rn subwallet is linked to Chrome on both Chrome and FF. 

## Scope
- [ ] Update the link for FF browsers to >
https://addons.mozilla.org/en-GB/firefox/addon/subwallet/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

**Comment by WRadoslaw** [comment]
@dmtrjsg I think this can be closed since we won't display uninstalled wallets after introducing user accounts
