### ISSUE TITLE
Carousel problems when video preview is hovered

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#42]
The Carousel Arrows are aligned to the middle of a video preview cover, but when hovering a video preview, the cover raises up by ~8px and the button looks misaligned. 
See here:

![image](https://user-images.githubusercontent.com/29527327/99644266-04b94b00-2a4e-11eb-90ee-e33b795b3c62.png)

**Comment by kdembler** [comment]
Another issue is that the shadow associated with the carousel's next button doesn't take the hover state of the video preview into account. If the shadow stays as in the design, the video preview will rise, exposing some part of it without the shadow which looks bad:

<img width="417" alt="Screenshot 2020-12-02 at 16 21 29" src="https://user-images.githubusercontent.com/12646744/100892321-7ebfea00-34ba-11eb-8c32-9a916fad24d0.png">

**Comment by KubaMikolajczyk** [comment]
The carousel component was reiterated and this issue should not be a problem anymore ☝️ 
Carousel component: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8426%3A593
Should we close this @kdembler ?

**Comment by kdembler** [comment]
Yes, closing!
