### ISSUE TITLE
Implement Twitter Card Functionality (Summary + Player)

### ISSUE THREAD

**Issue by DzhideX** [Joystream/atlas#422]
This issue will be used to track the progress of the changes for the Atlas Twitter Card Implementation (Relevant issue: https://github.com/Joystream/atlas/issues/416)

We agreed to take the following approach in this exact order:

- [ ] [Summary Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary) for the static pages (routes: `/`,`/videos`,`/channels`).
- [ ] Summary Cards for dynamic content pages (routes: `videos/xxx`,`channels/xxx`).
- [ ] [Player Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/player-card) for specific videos that will allow those videos to be played directly in the card.

**Comment by kdembler** [comment]
We can track this in #416
