### ISSUE TITLE
Homepage rankings: limit the number of videos shown form the same channel in a row on the homepage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4224]
## Context

In the new release we've implemented the new ranking system. 

It has a scoring based on the weights of:
- newness (30-A days)
- views (B x views)
- comments (c x comments)
- reactions (d x reactions)

It results in the highest relevancy given to popular content with max engagement (views x comments x reactions), followed up trending content followed by brand new content before showing less trending/ popular content. 

What the problem is that every time we onboard a new channel via YPP, their videos are stacked taking up a few scrolls of the screen and it can be 10s and 100s of videos from the same channel. 

The objective of this issue is to somehow limit the number of videos shown on the homepage from the same channel that have same ranking. 

We have to be mindful of course to try and implement the solution that 
- tries to involve client side processing as little as possible, so ideally smth done on the orion side
- tries to maintain the speed of new content upload that we are enjoing now

## Scope

- [ ] Enhancement of content to limit the number of videos from the same channel to be shown consequently in the homepage feed to a max of 3-5.

**Comment by dmtrjsg** [comment]
Decided to  look into effort of trying and adding the (YT timestamp of the videos) to the calculating of the newness. 

Like (7*x timestamp of Joystream + 3*x timestamp of YT)/10

**Comment by dmtrjsg** [comment]
R =  (newness (30- A)) + (B x views) + (c x comments) + (d x reactions)

A = (F x timestamp of Joystream + G x timestamp of YT)/ (F+G)

**Comment by Lezek123** [comment]
The new formula:
```
R = (N * -A) + (B * views_num) + (C * comments_num) + (D * reactions_num)
N = (E * days_since_published_on_gleev + F * days_since_published_on_yt) / (E + F)
```

Mutation:
```graphql
mutation {
  setVideoWeights(
    newnessWeight: A,
    viewsWeight: B,
    commentsWeight: C,
    reactionsWeight: D,
    joysteamTimestampSubWeight: E,
    ytTimestampSubWeight: F
  ) {
    isApplied
  }
}
```
