### ISSUE TITLE
Idea: Better environment control

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4225]
When a new version of Gleev was put in production today, with marketplace and the like, I was starting in dev mode, and also later all my channel follows seem to have disappeared. In order to even get to production, I had to go into my local storage and mess around.

Seems like whatever we are doing with local storage to control the environment is not really the right approach, should not be needed?

**Comment by bedeho** [comment]
This issue was not narrowly intended to focus on this one deployment glitch, but rather to raise the question of whether we are at all using the right approach to have such client side local storage state to solve whatever problem that state is intended to solve. It seems incorrect to me. For example, why should it not be possible to use gleev.xyz and dev.gleev.xyz interchangeably _at the same time_?

So really I'm asking
a) what problem are we solving by putting identifiers relating to environment in local storage
b) why is this the best solution, if it is.

**Comment by attemka** [comment]
@bedeho 

> what problem are we solving by putting identifiers relating to environment in local storage

this is used to keep the state value persistent so on e.g page reload we'll keep the saved env, if it was changed.

> why is this the best solution, if it is

as otherwise we'll lose our env settings in case of page reload

**Comment by attemka** [comment]
@bedeho small reminder that you've asked not to close this issue. Is it still relevant?

**Comment by bedeho** [comment]
My understanding is that this approach to solving the problem is not optimal, as it introduces extra client side state that has to be managed. But if Atlas team does not agree, then close, I don't have time to hash it out further at this time, if problems appear again then it can be reopened.
