### ISSUE TITLE
My Profile: visual changes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4233]
## Context
- https://github.com/Joystream/atlas/issues/4132

## Design

[Link to Figma>](https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2961%3A88715&t=eUlvDxfWiX54aLi5-1)

## Scope
- [x] Add settings button to own profile
- [x] Update Tab name to NFTs (from my NFTs)
- [x] Update NFT tiles to new component section
- [ ] Update Activity cards with new component
- [ ] Update grid of channels (esp check RWD cases)

**Comment by drillprop** [comment]
>  Add settings button to own profile

fixed in #4275 

> Update Tab name to NFTs (from my NFTs)
> Update NFT tiles to new component section

Fixed in #4271
