### ISSUE TITLE
Email already taken

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4234]
In case of : Sign up attempt with external wallet trying to use email that is already taken by existing Orion account

We need to show on form validation saying 
"Email is already taken"

**Comment by KubaMikolajczyk** [comment]
✅ Ready to be reviewed: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=3079-74679&t=ykxol6nHmOpqwAAb-4
