### ISSUE TITLE
Conf toaster shows too high 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4237]
needs to be 16px from the bottom of the screen

https://www.loom.com/share/dc3ab342a7c74aa781311470dcb24741 : 8min 11 sec

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk in the studio we had to show the conf notification above the action panel (in the very bottom of the page where the fees are displayed). So please advise if that's still needed..

**Comment by KubaMikolajczyk** [comment]
Yes it would be still really nice to show notifications above the action pannels, but if there will be no action bottom pannel the snackbars should be displayed lower than they are currently.
