### ISSUE TITLE
How to avoid this error: InvalidStorageBucketsNumWitnessProvided 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4250]
## Scope

- [ ] Martin:  "The witness being 3 here, means Atlas is not counting bucket 3, which IS assigned that bag, but NOT active." 
- [ ] Storage WG Lead: So this channel is assign to a bucket 3 that which is was in transition from one worker to another The application should auto recover by select another bucket

## Context

- ⚠️  see this discord chat !: https://discord.com/channels/811216481340751934/812344681786507274/1111306944796434452

![Screenshot 2023-05-25 at 17.27.56.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/c81d98c1-f533-482e-bcfb-97697485e8ae)

**Comment by dobertRowneySr** [comment]
This error arises when trying to upload assets when updating channels and/or videos.
The parameter is required when trying to upload assets on a update-{channel, video} operation.
It must be set to the number of buckets storing the targeted bag.
```rust
    /// Witnessed number of storage buckets assigned to store the channel bag.
    /// Required if assets_to_upload or assets_to_remove are provided.
    pub storage_buckets_num_witness: Option<u32>,
```

 ref:
https://github.com/Joystream/joystream/issues/4064
