### ISSUE TITLE
Creating channel flow improvement

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#4255]
# Context
Im working on updating the designs for my channel as the notifications settings will need to be added there and we don't have a working design file for it. 

# Doubts
Inside of this file we also do have a page for channel creation. 
![image](https://github.com/Joystream/atlas/assets/31144205/7a1cfcaa-3b48-4f5d-b431-2b8aa0ed2d96)

- And as I'm updating the old designs I started to question the way that we handle user channel creation as a flow. My doubts here go hand by hand with the issue of redesigning the YPP sign up flow where we wanted to make it as simple as it can be as the creators would be happy to sign with an empty channel even than to provide all assets upfront. 
- Additionally, in our current flow we have a "fake" WYSIWG experience - I say fake as only channel, cover and channel title are on their future places, while description, language or publicness are not displayed there on the viewer side of this experience. So the way of showing it as a "preview" of the channel works only for cover, avatar & title while creating a heavy flow for the users.

# Less is more?
When we look at Youtube the only thing they ask for is to "confirm" the name and handle that they already took from my "google account" and they give users a simple opportunity to upload an avatar if they want to. But they don't have to put any effort here other than click create channel button.
<img width="764" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/4849c6e8-1450-4949-bcf8-0893a7c22d81">

So effectively the whole experience of creating a channel is one click and is held in a lightweight modal fashion. Then an empty channel is created and the channel page is shown to the user where one of the button say "customize channel" - so if they want to add additional assets its right under their mouse right away after channel creation.

![image](https://github.com/Joystream/atlas/assets/31144205/35315ab8-f468-45ac-8a62-544c6cb27a2d)

When clicked we land on the YT studio side of the experience where user can upload their avatar, cover image and anything else they might want.

![image](https://github.com/Joystream/atlas/assets/31144205/7760004e-1e1c-470e-a5ab-f634c0b54906)

# Blue bird follows
Then the twitter may not be the exact same type of platform but lets look how they handle creating you "social channel".
![image](https://github.com/Joystream/atlas/assets/31144205/7fd5b3f8-010a-41a3-98a0-382e0e18080f)
![image](https://github.com/Joystream/atlas/assets/31144205/52f20567-e61f-4b17-b9b1-0aae073ff51f)
![image](https://github.com/Joystream/atlas/assets/31144205/27f9c7a3-999a-44af-9389-8db509e79bf8)
![image](https://github.com/Joystream/atlas/assets/31144205/80d2df2c-34fc-4af5-8a76-adbcf5c9b9af)
And then an empty profile is created for you with an option to edit this profile with a button.
![image](https://github.com/Joystream/atlas/assets/31144205/a3cc514f-87a2-4e95-a330-b8945fefde9a)

# How we can improve?
We could get rid of the create channel screen
![image](https://github.com/Joystream/atlas/assets/31144205/9c4d4cec-a2bc-4726-b3cd-01d8893ce492)

And remove the create channel page
![image](https://github.com/Joystream/atlas/assets/31144205/7adf1e16-ea8a-4971-ba48-4c3421cf8f8e)

And simply add create channel button in membership dropdown when user does not have a channel created. Instead of "studio" button.
![image](https://github.com/Joystream/atlas/assets/31144205/1fb292f7-ebd7-4e2a-af9d-0e1406a83fbd)

When clicked we could just show a dialog like this one.
![image](https://github.com/Joystream/atlas/assets/31144205/afe04ff3-a032-4dc2-b87b-2d5679e68610)

Which would then create an empty channel - and we would move the user to their channel page on the viewer side. There we would add a button that would be shown only for channel owner and allows to customize channel. The same way as we shoe "settings" button on membership profile only for the membership owner.
![image](https://github.com/Joystream/atlas/assets/31144205/f698e20c-a77a-4b0f-a583-58fc9f58c026)

We would then get rid of the old variant of my channel page
![image](https://github.com/Joystream/atlas/assets/31144205/4de5234a-c345-40f5-be35-75736700d81a)

And instead show a new variant of this page that would be unified with other settings pages and would not try to force WYSIWYG experience to the user where its not needed. 
![image](https://github.com/Joystream/atlas/assets/31144205/c9bb2c26-a131-48f9-92f5-bd28675f0357)

And finally the new page would fit nicely with the channel settings that we want to place there anyway. (notification types in here are just a placeholder for now)
![image](https://github.com/Joystream/atlas/assets/31144205/1fbf5ae0-7173-453f-834e-4093319dafeb)

# Conclusion
If I get a green light from you to simplify this whole flow we can:
- make it a lot easier for a new user to create a channel
- make it easier to later on edit the channel settings  
- make it a lot easier to navigate between the viewer view of the channel and the channel settings
- and we would address the YPP sign up flow issue here as well.

 I see no downsides to this approach, but I wonder what do you think about it, your thoughts on this subject are highly appreciated @bedeho @dmtrjsg .

**Comment by bedeho** [comment]
1. Perhaps I am confused here, but am I correct in understanding that there is no actual direct relationship between adding a settings page and changing how this signup flow+channel settings page work? Its just that working on the former made you think of the latter?
2. I think overall overall you are probably right to try to shorten path to having a channel successfully created.
3. I don't see it as necessary to deal with this now in order to add notification settings, per say. We could just just have the "general" tab that looked like "my channel page" as it is. 

If I have the correct understanding, I would say that this change is useful, but not high value compared to all the other things we could spend design&tech cycles on. The benefits you list are not important above and beyond the YPP signup simplification we are alreayd doing, and which is orthogonal to this, as in that case all the data will be fetche from youtube, user will not be manually be providing it any longer.

The only exception I would make is perhaps dropping the "create channel screen" as it appears to truly serve no purpose at all in retrospect, unless I am forgetting some place where it is directly linked to or some flow that needs it. I assume you checked this.

**Comment by dmtrjsg** [comment]
@bedeho I don't see how this can take more than a few hours of development to move from what we have now, to your approach, Kuba, especially as the layout is exactly the same way as it is on member profile and all endpoints stay the same.  We also need to change the designs of the drop downs, so new trigger to create channel right from the top nav may be the right way forward in the light of splitting the Member from Channel drop downs..

However you are right as in context of refreshed YPP onboarding flow with managed wallet, there's no difference how manual create channel looks like. But, create channel is one of the oldest designs we've created and in fact the very last page that has not undergone the changes.  

Now re timing and criticality of this, I see how the redesign of this can be synergetic in terms of the design patterns to be rolled out together with the updated Member Profile and there will hardly be a better time to do it, as we are all in context of this and easy to do it together with the profile updates. 

Overall my pov is I'd say its worth it as the change is very small and we will achieve consistency with the profile page and simplify creating channel further. 

@KubaMikolajczyk 

Comments on the details

1. Re create channel screen (studio landing page), if we remove it, what would guest user without channel see if they go to url *.xyz/studio? I think that's the only use case we need to figure out before agreeing to kill it. 

2. Re top nav drop down, I am not sure if just swapping "studio" for "Create channel" would work, as we ultimately agreed to split the profile and channel drop downs by ways of introducing second avatar to the top menu? I'd expect in this scenario for the new channel drop down to accommodate all menu items relating to channel, including its creation.

**Comment by bedeho** [comment]
> I don't see how this can take more than a few hours of development to move from what we have now, to your approach

If this is true, and you also include time for QA and design documentation and the rest of it, then ok, sure

**Comment by dmtrjsg** [comment]
@bedeho yes we've discussed it again on the design sync call and it does seem to hold up esp from the collateral efforts while we are redoing all these concepts, so thank you for approval here. 

Also as noted in Discord, we decided that we will create a happy path concept of the YPP sign up just to make sure once again these changes are congruent with the YPP flow and to confirm that we are covering all the bases without any conflicts or gaps 👍  So next review will  be on 
- YPP sign up flow
- Redesign of the channel/ member drop down contents
- Tuned simplified channel creation flow which is covered above in the light of the first two points

cc @KubaMikolajczyk @attemka

**Comment by KubaMikolajczyk** [comment]
The work is done and ready to review but all further conversations and reviews should be done in #1820 ✅
