### ISSUE TITLE
Fiat Denomination of Prices: API for USD rates compatible with Coinmarketcap

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4258]
## Scope
- [ ] Compare the price feed APIs from CMC ([link to documentation](https://coinmarketcap.com/api/documentation/v1/))

## Context
With `Carthage` release, all components that had JOY prices also displayed such prices in FIAT denomination. We chose a single currency for this - USD.

Background epic
- https://github.com/Joystream/atlas/issues/2607

Joy tokens are likely to get listed in June, which will enable displaying FIAT denomination of prices in Atlas (gleev). for 

- asset prices (NFTs)
- tx fees
- channel and member account balances
- tokens transfer and withdrawal dialogues
- channel payment history
- member and channel payment notifications

The exchanges where JOY token is listed is likely to change over time, and in order to save us from implementing their APIs, the suggestion is to rely on CoinMarketCap instead. This issue is about integrating to CMC for the USD/currency_x exchange rate, so that once listed JOY/UDS feeds can be enabled quickly.

**Comment by WRadoslaw** [comment]
1. Top selling channels
![image](https://github.com/Joystream/atlas/assets/92513933/d3aa592f-7715-40c7-8982-f6dc193d3352)

2. NFT tile
![image](https://github.com/Joystream/atlas/assets/92513933/965d8dcd-015c-46d1-92c4-310e77481fb9)
![image](https://github.com/Joystream/atlas/assets/92513933/f90aecd4-9b5c-4610-a874-30499cc4da2b)

3. Payments widgets
![image](https://github.com/Joystream/atlas/assets/92513933/190f8013-e791-497f-8dda-271956461228)

4. Member dropdown
![image](https://github.com/Joystream/atlas/assets/92513933/0be4f61f-3d3b-48eb-b5ed-a72e920f017f)

**Comment by dmtrjsg** [comment]
@WRadoslaw could we place the denomination right under joy values like you did in the top selling channels in other places as well?  as Iooks great there and nothing else is needed imho 👍

**Comment by KubaMikolajczyk** [comment]
It looks fine in those places listed here ✅ I also added some fiat denomination designs here in design issue : https://github.com/Joystream/atlas/issues/4368#issuecomment-1612801348

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk 

If you don't mind we will go ahead and release the current version, but as a follow up we'd need your steering on these two cases; 

1. NFT main hero carousel


<img width="510" alt="Screenshot 2023-06-29 at 14 24 35" src="https://github.com/Joystream/atlas/assets/93924525/d43f6d0f-d9cd-49de-b9a8-86ec7a234df2">

2. Tx Fees (suggest to do it in the tooltip)

<img width="600" alt="Screenshot 2023-06-29 at 14 20 42" src="https://github.com/Joystream/atlas/assets/93924525/629a5b1f-ab5f-41e0-84dd-cbb2f4fd3506">


@WRadoslaw 

for the buying/ bidding I think we can just add an extra line to this screen "Price USD" and rename "Price" to "Price JOY tokens"
<img width="1280" alt="Screenshot 2023-06-29 at 14 22 49" src="https://github.com/Joystream/atlas/assets/93924525/2ba6e910-1628-420d-8d04-b29b4aa098e1">

wdyt?

**Comment by KubaMikolajczyk** [comment]
☝️ Tx fees are covered here in dialog footers: https://github.com/Joystream/atlas/issues/4368#issuecomment-1612801348

**Comment by KubaMikolajczyk** [comment]
Fiat denominations for NFT main hero carousel ✅ : https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=1111-117734&mode=design&t=oIbVFYbddsYlK1cT-4

**Comment by KubaMikolajczyk** [comment]
NFT purchase view is a really outdated file (and it needs an update badly - I made an issue for that in the past) but I've made a temporary fix to show the denomination.

Long after the "NFT purchase view" was created - all lists in the app are gradually changing to one unified component made specificly for summary lists - this component is called "summary row" - Im using this component all across CRTs and will gradually change all summaries in the app for this: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=11931-303391&mode=design&t=SRpq56bAEqMiOzFS-4

So I created a temporary representation of NFT purchase view page using this component which is built to consider all various need of different summaries across the whole app - with denominations fiat included - and here is the page: https://www.figma.com/file/wjeAOZq77pSUFZsYXJqKIB/NFT-purchase-view?type=design&node-id=3111-26451&mode=design&t=oQknQTsVU6ZoMAm1-4

"NFT purchase view" - still needs to be updated though...
