### ISSUE TITLE
a newbie needs instructions

### ISSUE THREAD

**Issue by 457eh47htg** [Joystream/atlas#4266]
![Screenshot (1)](https://github.com/Joystream/atlas/assets/135071365/500d757c-027d-432e-bc83-5b611a0033ed)
hello, so i tried searching internet for any detailed joystream atlas operating but i just cant find the one, anyone can help me with this and ill be grateful

**Comment by traumschule** [comment]
Hi @457eh47htg i'm not sure if atlas was tested on windows. Did you also try on a linux based distro?

**Comment by 457eh47htg** [comment]
@traumschule i didnt actually so it hasnt been tested. is it possible to run it or its not even programmed for the OS

**Comment by dmtrjsg** [comment]
@457eh47htg.  Looks like you have not got Yarn installed. Try to do 
`npm i -g yarn`. For detailed info please feel free to check the [operator guide](https://github.com/Joystream/atlas/blob/master/docs/operator-guide.md) for details..
