### ISSUE TITLE
`Propagating changes` modal forever

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4273]
Block: [2,503,165](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.joystream.org#/explorer/query/0xb54463b2bb1c23b874431fb322a0debe63fa43470e876929b06aacef831c4673)
> Uncaught (in promise) Error: Cannot convert 'Normal' via asOperational

1. Go to URL: https://l1.media/video/9333
2. Place auction bid
3. Wait

**Expected behavior**

Modal disappears.

**Screenshots**

![propagating](https://github.com/Joystream/atlas/assets/31551045/0cec82e7-55f9-49d8-943c-a8da534bea01)

- OS: Debian
- Browser: Chromium

**Additional context**

Pressing Escape or clicking `X` / `Cancel` has no effect.

**Comment by dmtrjsg** [comment]
@drillprop did you make the changes to not wait for Orion "block height" to be same as RPC but proceed?

**Comment by dmtrjsg** [comment]
Atlas version needs to be updated to the latest one to resolve this..

**Comment by traumschule** [comment]
After updating it looks similar. `url: undefined` - what could cause this?
![urlundefined](https://github.com/Joystream/atlas/assets/31551045/1d30b4b7-aff4-409b-8686-6e8956574358)

**Comment by traumschule** [comment]
After upgrading the GW following different errors appear and the modal disappears.
> Uncaught (in promise) Error: Cannot convert 'Ready' via asFuture
> Uncaught (in promise) Error: Cannot convert 'Broadcast' via asFuture
> Uncaught (in promise) Error: Cannot convert 'Retracted' via asFuture
> Uncaught (in promise) Error: Cannot convert 'Normal' via asOperational
```
polkadot-worker-8d6b0671.js:6 Successful transaction: Withdraw, Transfer, Withdraw, Deposit, Deposit, BidMadeCompletingAuction, ExtrinsicSuccess
on network: wss://rpc.joystream.org:9944
in block: 0x28b2ba3bb52750892b0a3f2fbb92ff5a592612b9be40029cc8a80a4f1163f650
extrinsic hash: 0xe33d30be8ddb481f5f999e4947f59e9bc0502f73fb5a52dff87a4e21d38144e4
more details at: https://polkadot.js.org/apps/?rpc=wss://rpc.joystream.org:9944#/explorer/query/0x28b2ba3bb52750892b0a3f2fbb92ff5a592612b9be40029cc8a80a4f1163f650
```
> Uncaught (in promise) Error: Cannot convert 'Normal' via asOperational
