### ISSUE TITLE
Atlas shows encoding error even if video can be played by the Browser

### ISSUE THREAD

**Issue by zeeshanakram3** [Joystream/atlas#4298]
On Safari, Atlas player shows encoding errors for some videos even if the video is playable. 

For example for video https://gleev.xyz/video/9938 Gleev outputs an encoding error, it's a `mp4` video containing `h264` codec.

<img width="1014" alt="image" src="https://github.com/Joystream/atlas/assets/37098720/51d184b0-6dfb-4390-a212-017d4e045f60">

But media assets can be directly played on Safari i.e., opening the asset file for the above video using `https://sieemmanodes.com/distributor/api/v1/assets/21190` plays the video successfully.

I noticed this problem with some other videos too.

**Comment by drillprop** [comment]
If you cannot reproduce try to open this video in safari https://gleev.xyz/video/11692

**Comment by drillprop** [comment]
After merging https://github.com/Joystream/atlas/pull/4346 I couldn't reproduce this anymore. I tried different videos, tried different distributors and locations. Seems working to me.
