### ISSUE TITLE
Thumbnail upload error: Cannot convert 'Module' via asOther

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4314]
![](https://cdn.discordapp.com/attachments/815192060276506664/1117573905343856700/Screen_Shot_2023-06-11_at_5.59.20_PM.png)
reported [here](https://discord.com/channels/811216481340751934/815192060276506664/1117568390438060052)

**Comment by dmtrjsg** [comment]
Response is here> https://discord.com/channels/811216481340751934/815192060276506664/1117786760236236910
