### ISSUE TITLE
Variation of settings screen for users logged in with wallet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4319]
## Context
Link to [Discord post>
](https://discord.com/channels/811216481340751934/1035122951126798386/1117744687525150850)

## Scope

- [ ] Storing the log in type upon sign in to show this variation of the page
- [ ] Settings page that does not have  password/ seed and cannot connect the wallet again

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk 

Easy solution may be to just remove the tab (for wallet users), and the cost that we are paying is that user will not be able to look up their email.. so maybe we can show it in the Drop down as YT does? just a thought...

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg I looked at it and I have a different but still easy solution to this problem. I propose we keep the tab and just dont display the sections to those users that they cannot use such as seed, password and connect wallet, but we keep the membership address and email address sections there - so they create a mental model for the future about where to look for those information if they create new accounts - from my POV there is no need to alter this experience of tabs.

🎥 Loom video: https://www.loom.com/share/7ddbce86af1e4850a96bad36c3accba5?sid=ffaebdd0-fb3d-440e-9fa2-8b6cf264d60c
📄 Figma changelog: https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2912-46498&t=5mD6u7JjY0bC9usy-4
