### ISSUE TITLE
Rename JOY to JOYSTREAM

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4321]
## Context

The ticker of the JOY tokens will be `JOYSTREAM` when listed next week so suggestion is to update it in Atlas, where it is written in plain text and not shown as icon. 

## Scope
- [ ] Find and replace all places where JOY is written in plain text to JOYSTREAM
- [ ] Where interfaces are breaking because of this change, swap the "JOY" to icon we are using

**Comment by traumschule** [comment]
Same as https://github.com/Joystream/pioneer/issues/4429#issuecomment-1589000133

**Comment by dmtrjsg** [comment]
Decided not to do it for the time being
