### ISSUE TITLE
[USERSNAP] Не получается загрузить видео, хотя кнопка активна

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4331]
**Sender**: salient847@gmail.com
**Taken at**: https://gleev.xyz/studio/video-workspace
**Fields**:
- Expected Result: Не получается загрузить видео, хотя кнопка активна
- Houston, we have a problem.: Не загружает видео
**Screenshot comments**:
1: При попытке загрузить видео ничего не происходит, хотя кнопка активна

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3e34336-cdc8-46fa-929a-07f34c60dc33-annotated_69b2113f-d469-4916-a1dd-9ce1987797a6.png?etag=549b558f911ae35909f7062c482da2e4)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3e34336-cdc8-46fa-929a-07f34c60dc33-annotated_69b2113f-d469-4916-a1dd-9ce1987797a6.png?etag=549b558f911ae35909f7062c482da2e4)*

**Browser**: Chrome 109 (Android 12)
**Screen size**: 393x873
**Browser size**: 393x737
**[Open #43 in Usersnap](https://app.usersnap.com/l/feedback/b8aab829-7562-4b21-b025-3bcc113629bc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Andromalius77** [comment]
what video format?

**Comment by dmtrjsg** [comment]
Looks like the screen doesn't scroll up at the point of hitting the error at this viewport.

**Comment by dmtrjsg** [comment]
action was fixed and viewport positioning was fixed as part of it
