### ISSUE TITLE
Update YPP Landing page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4343]
## Context
Re-evaluation of rewards based on JOYSTREAM token price on MEXC

## Scope

- [ ] Update YPP landing page rewards
- [ ] Update Dashboard rewards
For Tier1:
Sign up: 20 USD
Referral: 10 USD
Video Sync: 3 USD
- [ ] Display rewards in USD* ⚠️ since the feed is not connected to, let's not display live JOYStream values, but only show USD
- [ ] Add clarification on the currency of payment: * rewards are paid in JOYSTREAM tokens based on the exchange rate on the date of payout
- [ ] Make Tier 3 popularity selected by default (with 100$ per sign up)

- [ ] Multipliers stay the same ✅

**Comment by KubaMikolajczyk** [comment]
We currently have (in designs at least) the exact msg about rewards being paid in JOY tokens right below those cards look at the screenshot - do you think that this info is not sufficient? 
![image](https://github.com/Joystream/atlas/assets/31144205/c747fc8c-d5d3-47ac-a4f7-eec1aed717b4)

**Comment by dmtrjsg** [comment]
Thanks that would do just fine 👍  @KubaMikolajczyk
