### ISSUE TITLE
[USERSNAP] Two weeks have passed and the coins are still not credited to my balance

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4354]
**Sender**: slinzv888@gmail.com
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: Two weeks have passed and the coins are still not credited to my balance
- Houston, we have a problem.: Two weeks have passed and the coins are still not credited to my balance

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1effd36a-3e8a-4a77-b8a4-99ca4e5a37dc-annotated_d093e4e8-e6c8-45e4-9642-8214df57e346.png?etag=2b26afa8dfbaac2088d81f966ec64669)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1effd36a-3e8a-4a77-b8a4-99ca4e5a37dc-annotated_d093e4e8-e6c8-45e4-9642-8214df57e346.png?etag=2b26afa8dfbaac2088d81f966ec64669)*

**Browser**: Chrome 114 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x937
**[Open #46 in Usersnap](https://app.usersnap.com/l/feedback/bc8635d7-40ab-41bb-a18e-f33b5ed8b492?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment]
Forwarded the feedback on [discord](https://discord.com/channels/811216481340751934/1069532790909046815/1122159425214500966), can be closed i guess.

**Comment by dmtrjsg** [comment]
The response was sent via email to the email behind the reporter of the issue
<img width="807" alt="Screenshot 2023-07-12 at 11 40 31" src="https://github.com/Joystream/atlas/assets/93924525/2ccc70d3-4917-445d-bf57-c542c55fdb38">
