### ISSUE TITLE
Optimistically cache whole video

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4356]
Question: why doesn't the player load the whole video into cache while the page is open.
I am fine to pause and wait (do something else) while the video loads but the player doesn't even try to buffer during pause.

I can watch the first 30s, then pause waiting for the rest to be cached but it won't. Then jump and play from the start - expecting it to be cached already - but instead it will start to buffer and wait again.

**Comment by dmtrjsg** [comment]
This is not applicable for the long videos, imagine 1hr long for a 4k video.. Even YouTube doesn't do that so we are not sure if that's a good way forward based on this consideration. 

We are open to feedback @traumschule 👍

**Comment by traumschule** [comment]
What options do we have to buffer better? Doesn't have to be an hour but everything <5 min should be possible to cache and give enough time to refill the buffer.
This might need some research how other players handle it.
My guess is yt uses a smart way to buffer most parts at low rate (180k) to allow faster seeking and loads higher resolution on demand.
