### ISSUE TITLE
Review FIAT pricing display

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4368]
## Context
- https://github.com/Joystream/atlas/issues/2607

## Scope

- asset prices (NFTs) - we already have this implemented on nft widget so this could be partly done, never had on tiles or in market place
- tx fees - are displayed in different way in the app(sometimes in dialogs, sometimes in action bar, I think also in tooltip) - this definetely need a design
- channel and member account balances - never had this, and it's not a lot of space there, I don't see this without designs
- channel payment history - needs to be implemented, designs already available
member and channel payment notifications - there are no designs as far I remember
- NFT history
- NFT widget
- Send funds dialog
- Withdraw fund dialog
- Token Input (used in: change price dialog, nft purchase dialog, Send funds dialog, Withdraw fund dialog)

**Comment by KubaMikolajczyk** [comment]
Below  I list couple of components and which have the fiat denomination added:
(This is not a full list but its a start)

# Components

⚙️ (NEW) Action bar (added denomination + behavior in docs) : https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9724-174396&mode=design&t=rXx0CEJkdcR5W0bW-4

⚙️ (NEW) Dialog footer (exactly same behavior as action bar + explained placement of it) : https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=9274-172494&mode=design&t=rXx0CEJkdcR5W0bW-4

⚙️ NFT history (already prepared for fiat denomination) : https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=2077-123369&mode=design&t=1XiXlfCx9TQnWluK-4

⚙️ NFT Widget (already prepared for fiat denomination) : https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=2077-112135&mode=design&t=1XiXlfCx9TQnWluK-4

⚙️ NFT Bid row (Already prepared for fiat denomination) :https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=2077-114018&mode=design&t=1XiXlfCx9TQnWluK-4

**Comment by dmtrjsg** [comment]
Resolved in https://github.com/Joystream/atlas/issues/4258 and PR was raised against it
