### ISSUE TITLE
User accounts are not working on safari

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#4374]
Go to https://atlas-git-accounts-joystream.vercel.app. The content is not displayed, because cookie is not saved in the browser for some reason

**Comment by drillprop** [comment]
It looks like this is a domain issue, nothing to do on the front-end level. The domain of the orion auth API needs to be the same as the front end. 
So for example, if gleev has https://gleev.xyz/ orion-auth API should have an endpoint https://orion.gleev.xyz/orion-auth/api/v1 or similar

**Comment by dmtrjsg** [comment]
@mnaamani @ignazio-bovo  guys could you pls take a look at this one? Otherwise it will make Gleev not usable for Safari users unless specific settings are updated on the Safari browser advanced settings.

**Comment by mnaamani** [comment]
> @mnaamani @ignazio-bovo guys could you pls take a look at this one? Otherwise it will make Gleev not usable for Safari users unless specific settings are updated on the Safari browser advanced settings.

Its as @drillprop explained a matter of the domain. Should we add a DNS record for orion.gleev.xyz ?
