### ISSUE TITLE
Missing fiat denomination

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#4379]
After reviewing Radek's PR https://github.com/Joystream/atlas/pull/4370 I found some of the places where we don't have fiat denomination 
1. Notification widget
![image](https://github.com/Joystream/atlas/assets/51168865/05d54152-ba0b-41b2-befa-ed633a55ad32)
2. Notification center 
![image](https://github.com/Joystream/atlas/assets/51168865/b8aef5f2-e9fc-4cc4-a5be-5d2974ff5e73)
3. Member activities(tab in member profile)
![image](https://github.com/Joystream/atlas/assets/51168865/12bda2bb-0ab3-4278-96c7-04107e2a9d10)
4. Like dialog
![image](https://github.com/Joystream/atlas/assets/51168865/a562e4ab-d186-4016-b5ce-08ca4890dbe6)
5. Last step of NFt workspace 
![image](https://github.com/Joystream/atlas/assets/51168865/7906960c-337c-4f2a-b08d-b1f7be43597c)
6. Channel balance in channel view
![image](https://github.com/Joystream/atlas/assets/51168865/f47a645c-887e-4049-926a-cb32548978b4)

**Comment by KubaMikolajczyk** [comment]
Thank you @drillprop for catching those missing items ✅ 

The notification related denominations will be tackled in the Notifications rework which will be available to work on really soon - the denominations will look like this. The links to those solutions will be attached when the work on notifications file will be done.
1. New notifications widget
![image](https://github.com/Joystream/atlas/assets/31144205/3bdcd81f-d0a7-417e-83ce-bd6659c70ef2)
2. New notifications center
![image](https://github.com/Joystream/atlas/assets/31144205/0911466c-2d1b-4a2f-bf14-4b7f652c14db)

In other cases the denominations were added to the components and are ready to be implemented:
3. Member activities (tab in member profile) - while updating please look at how the price should be displayed in terms of color and how member hovering should behave
https://www.figma.com/file/yhZpTHdf1sxJx13uRZ71GV/Membership-profile?type=design&node-id=2912-46498&mode=design&t=boT3mqSR77IJyu8a-4
![image](https://github.com/Joystream/atlas/assets/31144205/ab70b194-d4e9-479b-b4b5-e5d4264a5898)

4. Like dialog
https://www.figma.com/file/sMydmZJlzhK91FTIPOd7D2/Video?type=design&node-id=2470-220668&mode=design&t=6OScpSnT36jHTAIr-4
![image](https://github.com/Joystream/atlas/assets/31144205/93428e8d-c7d5-4e91-a618-6f79e9aa78e6)

5. NFT Workspace (Summary)
This is one of the cases where we should use the unified summary row component - I went ahead and changed all previous summary rows in NFT Workspace for this new summary rows components.https://www.figma.com/file/7LCeeLg9cCFSDAS4alvniX/NFT-Workspace?type=design&node-id=1-14419&mode=design&t=Zqnerm0owRwolHVt-4

![image](https://github.com/Joystream/atlas/assets/31144205/31abe762-afec-4f6c-9477-9a885748583e)

 (Please bear in mind that it's not enough to just add the denomination here - whole row has to be changed to summary row component which can be found under this link - https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=11931-303391&mode=design&t=JRxHCSrahbFpYynh-4)


6. Channel balance
![image](https://github.com/Joystream/atlas/assets/31144205/b890d0f0-e868-4a00-b157-8ba22da12e03)
https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel?type=design&node-id=1902-153566&mode=design&t=OqXioLioblnWF3F7-4
