### ISSUE TITLE
User accounts follow-ups

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#4389]
1. When user goes back from seed step on sign up and instantly tries to go forward, it will trigger captcha error, but won't scroll container to error message.
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/8c3ac394-b9e6-4a06-ab5b-bde184755d03)
2. We have different approaches for show/hide password UI throughout the app. Sometimes it's only accounts and sometimes it's copy + icon.
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/3d772753-d4ed-42b9-8717-a51b42628ede)
3. No padding in create channel modal - first step
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/38bdc0a2-fcf4-4fea-b339-41b04df82be9)
4. Studio logo is redirecting into empty page (only sometime - not sure why)
![image.png](https://images.zenhubusercontent.com/61b33b1e8ddbc86c62bdcd28/39057835-e437-46a8-a1ff-ecea0ccc6dbd)

**Comment by KubaMikolajczyk** [comment]
@WRadoslaw  Thank you for catching the inconsistency in num 2. I didn't view it as an issue but I agree with the direction to unify as much as we can - therefore I would go for only icon approach and resign from labels in password inputs. I already corrected that in the file: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&mode=design&t=e7abdQ8TjxawURhf-4
