### ISSUE TITLE
Play/pause loop issue still seems to be present

### ISSUE THREAD

**Issue by blrhc** [Joystream/atlas#442]
@kdembler I am getting this bug again https://github.com/Joystream/atlas/pull/392 in the live version of Atlas.
Perhaps there is a further fix needed to resolve it?

It only seems to happen if you click on the video timeline when the video is playing.

https://user-images.githubusercontent.com/4144334/114284325-01e3e480-9a47-11eb-9aa2-a776897e78d3.mov

**Comment by kdembler** [comment]
Oh wow, that's a nasty one... The issue with it is that it's so hard to reproduce it consistently. Will take a look

**Comment by kdembler** [comment]
Worked on in #314

**Comment by mochet** [comment]
A user in Telegram reported the same issue still happening, they said it happens when they rewind a video @kdembler

**Comment by kdembler** [comment]
Yep, it's not deployed yet
