### ISSUE TITLE
User accounts- bugfixing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4436]
Hey team! (@dmtrjsg @attemka) 
I had an opportunity today to test the User Accounts implementation and it looks awesome 🙏👌 however I stumbled upon issues that didn't allow me to continue testing and I was not able to create a new account - more about that below.

# Sidenote
## Not able to check wallet sign in
I was not able to check if logging to an already existing membership with wallet works properly (I cannot test that) as I had no membership on dev.gleev.app in the past apparently. And I have to say I like the dialog you guys made for this scenario as it was not covered in designs.
<img width="580" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/afac7510-48b5-4027-a128-2a725f5a8a80">

## Not able to check full sign up
I was not able to move past create membership profile step in create account flow as it was not letting me do so on many different browsers (chrome & arc - restarted a lot of time + restarted mac) - look point 3

## YPP throws this error 
<img width="702" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/3bc26554-2c0f-4fa2-888a-483fc14444f9">

# Improvements
From what I was able to get access to:

### 1. No error on caqptcha validation when member name is entered
When I click continue without confirming the captcha after entering member name there is no error msg below it - should be smthn like this https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2924-50212&mode=design&t=vanLKobUtIYL9tWi-4
<img width="514" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/6f62e4f1-d986-4852-b22e-589f05ef3d20">

### 2. Member handle in constant loading state
When I enter member name and the loading starts it didn't finish on chrome and arc browsers.( the only 2 I use)

### 3. I cannot progress with creating a membership 
Video expalining below:
https://github.com/Joystream/atlas/assets/31144205/c4ee73a8-9d90-40c1-ad48-143f079aa1ab

### 4. No tooltip on password icon button (no show/hide)
When I hover the show icon button on password I should have a tooltip with the action name displayed on top of it - same for hide when its the oposite action I want to perform - it should look like this https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2924-50276&mode=design&t=vanLKobUtIYL9tWi-4
<img width="489" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/49760cf7-6679-417d-aafa-792efc6cbf51">

### 5. Cursor jumps to the beginning of the input when show/hide
When I show or hide the password the cursor jumps to the beginning which is not a desired behavior.
https://github.com/Joystream/atlas/assets/31144205/df742656-624e-4101-ab5e-572853ee792d

### 6. Form validation of change password
We should change the word mnemonic as its not used in the designs to "Enter wallet seed."
<img width="489" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/201ede48-545a-4d47-b840-7b90644cfa67">
<img width="455" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/bfaa07c7-ad60-4323-80dd-ff766d8bc22c">

### 7. YPP not met req dialog is not here
Right now in implementation after we dont meet the requirements for the YPP we are brought back to first dialog in the flow while we have a special dialog for this scenario in the designs - in the designs it looks like that https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=1638-99413&mode=design&t=UQYHHnbGpjTKQl37-4 
and in implementation like that
<img width="673" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/be964200-452a-4fef-8fe0-cd933e288db7">

**Comment by WRadoslaw** [comment]
1. Couldn't reproduce 
![image](https://github.com/Joystream/atlas/assets/92513933/f71bb737-ba40-41dd-aa06-8cd08c3bceb6)
2. Couldn't reproduce
3. This is prolly no. 2 sub-issue and couldn't reproduce it
4. Valid
5. Couldn't reproduce 
6. @dmtrjsg Using "seed" word is not correct for expected input. Generaly mnemonic and seed are the same thing, but if user was to provide the seed in here it think it would be processed incorrectly. Processing function will work only with mnemonic which is user-friendly seed representation.
7. Valid

**Comment by dmtrjsg** [comment]
re 6 @WRadoslaw can we just rename mnemonic to `wallet seed phrase`, as this will get connected in the user's head. On the screen of saving one it is called seed so need to match otherwise non crypto natives will struggle.

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk also could not reproduce a bulk of thse.. are you using `Brave` to test? Chrome and FF are the ones that we support generally 😬

**Comment by KubaMikolajczyk** [comment]
> @KubaMikolajczyk also could not reproduce a bulk of thse.. are you using Brave to test? Chrome and FF are the ones that we support generally 😬

Im using chrome :)

**Comment by WRadoslaw** [comment]
> wallet seed phrase

On it
