### ISSUE TITLE
User accounts - Cannot create new account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4437]
browser FF
no extensions need to be installed

it lets me go through full but gives a 404 in the very end in the toaster modal. 

Console: ![Screenshot 2023-07-14 at 14.59.31.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/0dbc7c0e-d28b-439e-816c-7a0903517d01)

**Comment by WRadoslaw** [comment]
@dmtrjsg 
Couldn't reproduce with and without incognito mode.

**Comment by WRadoslaw** [comment]
Although I might have an idea what's going on
