### ISSUE TITLE
Channel view: video thumbnails staying the same between pages

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4441]
## Problem
1. Open this channel: https://gleev.xyz/channel/26363?tab=Videos
2. Go to bottom of thumbnails, click page `2` or click `>` icon
3. The names on the 2nd page of videos update but the thumbnails remain the same

Also if I go to the end page, then I get the end page thumbnails sticking on every page

**Comment by attemka** [comment]
duplicate of #4421
