### ISSUE TITLE
Authorisation failed modal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4452]
When authotisation failed (see image)
![Screenshot 2023-07-17 at 19.57.48.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/410d7a12-373a-49ed-815d-190dc1c0e32c)

ER: user clicks sign up and requirements modal will show
AR: authorisation failed modal shows, clicking "back" results in no action at all

**Comment by attemka** [comment]
@KubaMikolajczyk what should the "back" button do? Does it send user back to google auth window?

**Comment by attemka** [comment]
@KubaMikolajczyk decided to remove it, as it leads out of website
