### ISSUE TITLE
Restore user menu if wallet is connected

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4481]
After setting any orion auth url (#4480) the former user menu with `Switch account` is gone.

In case the user connected a wallet with memberships i suggest to show the menu again instead of `Sign in`. Also to reach studio with channel uploads.

**Comment by bedeho** [comment]
What is the actual problem? the fact that a menu item is gone is not a direct problem.

**Comment by dmtrjsg** [comment]
@traumschule 

Just tested this morning and there's a choice to sign in with the wallet for all members who have had a membership with us previously. 

<img width="1041" alt="Screenshot 2023-07-24 at 11 15 43" src="https://github.com/Joystream/atlas/assets/93924525/1c91effc-973e-4ecf-82ff-beace36382c8">

**Comment by dmtrjsg** [comment]
I understand the issue is now resolved? If not please feel free to continue on Discord.

**Comment by traumschule** [comment]
It's not. That screen alone doesn't help you to access the former profile menu unless a new GW account with email is registered. Or did you manage that without?
If not it's a downgrade i'll keep l1.media on 3.6 so long.
But there will be other GW with the newest version soon as well.

**Comment by dmtrjsg** [comment]
@traumschule why is adding an email such a problem? I really don't see it that way.

**Comment by traumschule** [comment]
First off it's a great idea and can be an improvement for gleev but it should not be mandatory. 
1. It's a downgrade and disrupts what our users are accustomed to do.
2. It's not in cooperation what all GW operators want. This change is basically forced upon us without prior consideration. As CM i recommend again to involve the DAO more in such decisions.
3. It may not even be what users want long term. Some want to keep using wallets without telling the GW their email. Does this seem so unlikely to you?
4. Not all GW may want to implement extensive user tracking and profiling.
5. Choice over force: Let users decide to do it, or just keep doing what they were used to. Seems to me this is the best option without extra costs since the former menu is already fully developed. Suggest to restore in case no email account is being selected, basically when user chooses "Back".

![no membership](https://github.com/Joystream/atlas/assets/31551045/8a35c511-6508-4e03-8873-f7f0aa1b538a)
