### ISSUE TITLE
Handle the case of informing the users that sync starts after the channel is verified

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4512]
## Context
- https://github.com/Joystream/youtube-synch/issues/224

## Scope
Upon success of YT sign up we need to 
- [ ]  Add info about the sync to the splash screen
- [ ]  Update the copy of the info bar in the YPP dashboard

"Your channel needs to get verified before content syncing starts.  It normally takes 12-48 hours for channels to get verified."

**Comment by KubaMikolajczyk** [comment]
The changes can be found here ✅ : https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4497-96722&mode=design&t=DrBv5OcngjlM64b3-4
