### ISSUE TITLE
Add verification status to referrals table for YPP dashboard

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4517]
## Context

Improvement for the referral table  to avoid support requests

[Message in discord](https://discord.com/channels/811216481340751934/1035122951126798386/1134439630989693058)

## Scope
- [ ] Add column "status" with values `unverified` "display as "verification pending", `verified`, `suspended`.
- [ ] Add tooltip "Only verified channels result in the referral rewards. Verification normally takes 12-48 hours."

**Comment by KubaMikolajczyk** [comment]
The status column is added to the designs ✅ and additional user story is created to showcase those functions:

📄 YPP changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=DrBv5OcngjlM64b3-4
