### ISSUE TITLE
Emphasis more content focus during onboarding flow

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4528]
## Suggestion
- [ ] Put more emphasis on the first requirement in the reqs modal.

## Problem
There are about 40% of channels signing up that do not have crypto focus. Supposition is that they miss the key part of the requirements. 
![Screenshot 2023-07-31 at 13.20.31.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/61632dbf-04aa-48cd-941a-b8b916f1d9d6)

**Comment by KubaMikolajczyk** [comment]
Warning color used to emphasise the importance of the paragraph just as we talked it through: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4354-96642&mode=design&t=ezVoyi7ULqVC49gM-4
