### ISSUE TITLE
Channel Assets Upload Error

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4544]
channel=26678

https://github.com/Joystream/atlas/assets/93924525/e2eb293c-26cc-4c56-9a66-4a0de471e711

**Comment by dmtrjsg** [comment]
Thing to check: functionality of changing storage bucket if current one is not responding.

**Comment by dmtrjsg** [comment]
Just re-tested on dev. 

ER: assets from YT channel uploaded automatically
AR: Assets uploading failed. NB the corresponding YT channel did not have Ava and Background image set up: https://www.youtube.com/channel/UCItgeWeEm8IpF9e2Sm_iKAg

<img width="771" alt="Screenshot 2023-08-02 at 13 32 25" src="https://github.com/Joystream/atlas/assets/93924525/167de71b-dd6a-4c47-8a13-0677d035b37e">



<img width="1508" alt="Screenshot 2023-08-02 at 13 32 11" src="https://github.com/Joystream/atlas/assets/93924525/bc766e2b-6a33-4a7c-8c00-a6d15e01224c">

**Comment by dmtrjsg** [comment]
Please share bag and bucket ID for this case to relay back to the storage Lead.

**Comment by thesan** [comment]
Block of the transactions:
- [3367732](https://polkadot.js.org/apps/#/explorer/query/0x42be3222a90275d24f5d458a7e4cef23c8ce228dbd77704ba6036b024911aa28)
- [3367797](https://polkadot.js.org/apps/#/explorer/query/0xe4df8c0734837948d37be1e4ef818f1cc5aa53c478a45ce0505c52ab9939cfd5)
