### ISSUE TITLE
Add a note about YPP sync service operatoinal status

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4551]
## Context
More service outages are expected for the sync service in teh future. REcent one resulted in substantial number of support requests. In order to better inform our users, let's add smth for them to the dashboard. 

⚠️ Depends on this issue:
- https://github.com/Joystream/youtube-synch/issues/232

## Scope
- [ ] Add a service status indicator to the YPP dashboard/ to "My videos"
- [ ] Shows sync status [green - fully operational, yellow - operating w delays, red - on pause] and human-moderated comment.

**Comment by KubaMikolajczyk** [comment]
Hey @dmtrjsg I explored the possible solution for this issue and recorded a video about it ✅

🎥 Video update:  https://www.loom.com/share/18db14e1136b4ec5acc9e81d6fa1ac59?sid=eda93b69-69f9-45b9-b978-677b8bb4f62c

📄 YPP Status exploration file: https://www.figma.com/file/2VVTbmhcdTuqIimECMHNRB/YPP-Status-Explorations?type=design&node-id=1-9441&mode=design&t=4LuzCikdlYAiZCTZ-4

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk looks great, thanks for that! just few small comments: 

1. Rename to YPP Sync Status
2. Suggest to make the animation stop after 3-4 seconds so its not always asking for attention if someone is spending longer time on a page.

**Comment by KubaMikolajczyk** [comment]
The solution is implemented in the final files ✅ 

- Finalized the component with all of its documentation
- Added user stories for displaying the YPP Status pill on my videos page and on YPP Dashboard
- Added YPP Status pill to all of RWD screens 

@dmtrjsg please take a look at the default copy for the tooltips displayed for the states and suggest any changes if needed - [Link](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=13992-344162&mode=design&t=2SNsbOXHmd5ibbDl-4).

📄 YPP Status pill component docs: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=13992-344162&mode=design&t=2SNsbOXHmd5ibbDl-4

📄 My videos changelog: https://www.figma.com/file/LF7LOMhOA46bRcYHWlw1Bq/My-videos?type=design&node-id=784-26965&mode=design&t=iiufipazUqdyE3J5-4

📄 YPP Dashboard changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=SEqfLEHJWWb5mXXn-4
