### ISSUE TITLE
Reconsider the sizing of scrollable modals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4574]
https://gleev.xyz/video/62783
![Screenshot 2023-08-07 at 11.30.56.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/4c0f14d3-6431-4977-9ef1-f3172717198f)

**Comment by KubaMikolajczyk** [comment]
The work is done here and can be reviewed ✅

🎥 Video update: https://www.loom.com/share/a195e89ef0e942ec8d2c88d39fe0bd9b?sid=5631c306-0e98-4562-80c5-4a885e63474f

📄 YPP Changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=SgzSZPfrnc7E0hee-4

📄 Sign up changelog: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&mode=design&t=ShKWtjoDSKTLN4JY-4

**Comment by dmtrjsg** [comment]
Captured in 
- https://github.com/Joystream/atlas/issues/4574
