### ISSUE TITLE
Unable to login via wallet: problem with signature

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4584]
* Trying to login via marketplace page: https://gleev.xyz/marketplace
* Get prompt to choose membership, select it
* Wallet launches signing prompt and shows this data `{"joystreamAccountId":"j4V3RkKua5wbpFUP31YGyPhXnWaRAJvAKLzGqfS4dKDnoutCm","gatewayName":"Gleev","timestamp":1691449979000,"action":"login"}`
* Sign the data successfully
* Error: `There was a problem with signature. Please try again.`

Screenshots:
![image](https://github.com/Joystream/atlas/assets/50830161/6a05c6b8-b03d-497a-b278-cd54c7ab14e9)
![image](https://github.com/Joystream/atlas/assets/50830161/fcac4056-3a41-49f1-818e-97192c787e76)

**Comment by dmtrjsg** [comment]
Additional info:
<img width="765" alt="Screenshot 2023-08-08 at 14 50 47" src="https://github.com/Joystream/atlas/assets/93924525/dd4e30d8-3856-4726-bc15-711ea44371ed">
<img width="872" alt="Screenshot 2023-08-08 at 14 50 53" src="https://github.com/Joystream/atlas/assets/93924525/df65aba6-f065-4530-a81c-309ddc2e2a31">
<img width="875" alt="Screenshot 2023-08-08 at 14 50 59" src="https://github.com/Joystream/atlas/assets/93924525/4f4c8ac7-0a39-49dc-b285-758149df108c">
<img width="582" alt="Screenshot 2023-08-08 at 14 51 05" src="https://github.com/Joystream/atlas/assets/93924525/ef4e2183-1f0c-494f-9915-0ff3928a7f71">

**Comment by dmtrjsg** [comment]
Resolved, the acc used in the signer had a different encryption not supported any longer.
