### ISSUE TITLE
Segment V - integrate with Livesession

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4603]
We need to send Track Event to Segment everytime Livesession rec starts for a user

[Here's how>](https://livesession.io/help/segment-integration/#:~:text=To%20make%20this%20integration%20works,debugger%20and%20find%20LiveSession%20Recording.)

**Comment by traumschule** [comment]
Please keep in mind to make the use of Livesession optional.

**Comment by attemka** [comment]
@traumschule both livesession and segment always were optional

**Comment by traumschule** [comment]
Good! This should be a design principle for all new future features.
