### ISSUE TITLE
Issue with assets upload for channel 26678

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4610]
The assets where uploaded to the storage node as a result they appear in the QN:
```gql
{
  storageDataObjects (
    where: {
      createdAt_gte: "2023-08-09T08:00:00.000Z",
      createdAt_lte: "2023-08-09T09:00:00.000Z",
      isAccepted_eq: false
      storageBag: { id_eq: "dynamic:channel:26678" }
    }
  ) {
    createdAt
    id
    ipfsHash
    storageBagId
    isAccepted
    type { __typename }
  }
}
```
![Screenshot from 2023-08-18 15-42-47](https://github.com/Joystream/atlas/assets/6571453/594eeed1-8935-46d3-a5f6-a230f57da1ae)

And `storage.DataObjectsUpdated` was emitted here: https://polkadot.js.org/apps/#/explorer/query/3485552

However `storage.acceptPendingDataObjects` was never called. The next tx is `content.ChannelPayoutsUpdated` 28 blocks later.

**Comment by thesan** [comment]
I just realized that the QN doesn't create new `storageDataObjects` entities when retrying to upload a channel avatars or covers. Instead it replaces the existing ones. So this is the same network issue that causes #4544
