### ISSUE TITLE
Simplify YPP page

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4672]
I was looking at someone screen sharing and talking about signing up for YPP, and it was very clear that they understood the two "sign in" buttons as fungible, the one from Google and the one for the app. This is obviously not hte case, and the latter is sort of out of place on the YPP page, because we don't want people to sign in there, we want them to authenticate through google API.

For this reason I thought we def. should hide the "sign in" button that is for the app, in the top right corner, but this just got me thinking: why do we even show the whole top bar with search and all the rest of it? This is all a distriction, there should just be a singular focus on getting someone into YPP, so instead we could just drop the entire top bar, put a small gleev logo over the hero tagline, and call it a day. Something like that.

**Comment by dmtrjsg** [comment]
@bedeho How about we also rename it to `Sign up with Google`? As that is actually what they are doing here..

**Comment by bedeho** [comment]
Agree, its not great, but I did not know what brand constraints we had, do as you lke.

**Comment by KubaMikolajczyk** [comment]
@bedeho Is this the kind of approach that you wanted to explore? 👇wdyt?
![image](https://github.com/Joystream/atlas/assets/31144205/a72f452b-6549-4f52-98f9-2010d6a38ca6)

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk can we also update the "Reupload ... " to 
"YouTube videos get automatically synced to your Gleev channel, without any additional effort. Rewards for synced videos  are subject to program terms and conditions."

**Comment by KubaMikolajczyk** [comment]
![image](https://github.com/Joystream/atlas/assets/31144205/10eaa2e7-f516-4a64-a552-b62f02878d6a)

Let me know if this is the way to go - then I will update the final designs with this approach :)

**Comment by bedeho** [comment]
I think that is perfect!

**Comment by KubaMikolajczyk** [comment]
The changes are implemented into final designs & RWD ✅

📄 YPP Changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=476Gsi0qGAR9DcmF-4
