### ISSUE TITLE
Clean up notifications

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#470]
The design includes displaying success/failure snackbars/dialogs after specific flows succeed/fail. We should add those kind of announcements to the app. General idea is this:

- if something major happened that may change the users flow, display the dialog with message, for example:
    - new channel created and after accepting the user will be redirected
    - new video published
    - error in transaction happened
- if something more minor happened, we should use a snackbar:
    - channel updates saved
    - asset successfully uploaded

We should first create a list of all kinds of interactions like this with proposed notification and then implement that

**Comment by mikkio-j** [comment]
Here's the list of notifications yet to be implemented:

###### Snackbars:

- Draft/video deleted
- Assets uploaded
- Assets uploading
- Draft saved
- Draft opened in tab
- internet connection restored

###### Dialogs:

- remove draft and possibly remove video (if not covered in #529)

**Comment by kdembler** [comment]
- What about channel/video edit?
- I don't think we should have a snackbar on draft saved because that will be happening continuously
- Probably also asset upload error, unless that's part of uploads error handling
- What about "Internet connection lost"? Does that exist already?

**Comment by mikkio-j** [comment]
> * What about channel/video edit?
> * I don't think we should have a snackbar on draft saved because that will be happening continuously
> * Probably also asset upload error, unless that's part of uploads error handling
> * What about "Internet connection lost"? Does that exist already?

1. Ah yes, that I've already implemented and forgot to put it here
2. Yeah, that would be an issue. Understood.
3. That's the part of asset upload error
4. Does not exist, forgot to put it here
