### ISSUE TITLE
Test error handling

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#472]
We should make sure all of publishing views properly handle all kinds of possible errors. This includes:
- blockchain related errors
- failure to fetch some data from the query node
- failure to upload data to storage provider

We should handle those as gracefully as possible and make sure user always have some way to recover and they understand what happens.

**Comment by drillprop** [comment]
To be honest, didn't find much:
1. This is not related entirely to error handling. When a user will go to the studio for the first time, he will see this dialog: 
![image](https://user-images.githubusercontent.com/51168865/117968632-ae570600-b326-11eb-9682-f990df77dece.png)
Unfortunately, if he chooses to reject he will just see `Add extension` step in `/signin`. Then if the user changes his mind after all and he will want to allow access,  it could be not obvious to him how to do it (he will need to go polkadot extension ⇒ settings ⇒ manage website access). Maybe we could add some information in the `ExtensionStep`: 

> If you have installed the extension and still see this dialog, follow these steps to fix it.... -> and some steps to fix it 

2. Signed user still can go to `studio/membership/new` and if he tries to create a member he will see this dialog. 
![image](https://user-images.githubusercontent.com/51168865/117969095-49e87680-b327-11eb-8264-bc4e9d909bc3.png)
which doesn't say much. Solution: we should redirect the user if the accountId is set in localStorage.
3. If a user has no internet connection he could still perform some actions and it's not ideal. He could click `new membership` on the membership hub and even go through all steps. He can click his accounts on the membership hub. In my opinion, we should disable these buttons/tiles
4. There is a bigger problem when there is no node connection. A user can still publish changes and he won't see any error(except `no node connection` notificaion). For example, if he uploads a video,  he'll see waiting for signature dialog just hanging infinitely. 
5. Unfortunately there is still a problem with image validation. My PR https://github.com/Joystream/atlas/pull/587 didn't solve this entirely. I didn't cover channel creation, only video creation. In create channel view, image crop dialog will show up even if you pick an image that is not supported or it's broken. We didn't handle errors there.
6. ~~There are some issues regarding create member validation, but @mikkio-j  is handling them in https://github.com/Joystream/atlas/pull/600 so I'll just ignore this.~~
7. I didn't properly test uploads errors. I will look at it again when we merge: https://github.com/Joystream/atlas/pull/530 

Should I create separate issues for all these points? Or just one like Mikołaj did with responsive tweaks?

**Comment by drillprop** [comment]
Regarding point 6: There are two issues with validation in the create member view.
Images validation not working correctly:
![membership bug](https://user-images.githubusercontent.com/51168865/118013581-8c737880-b352-11eb-8db6-c91cae0a1331.gif)
You can still submit the form when you exceed the about's maximum characters limit
![image](https://user-images.githubusercontent.com/51168865/118014210-3c48e600-b353-11eb-8945-fb79f93123a6.png)

**Comment by kdembler** [comment]
Wow, great job on that! I think we can try to do one mega issue out of that

**Comment by drillprop** [comment]
moved to #606
