### ISSUE TITLE
Bug: momentary "oops" error message when loading videos and channels

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4723]
# Problem
Very frequently when I load a random video by clicking a link from outside of Atlas/Gleev the page will display an "Oops an error has occurred message" and then it loads properly after a few seconds without reloading. This happens with both channels and videos

The timing of this seems to happen with these `error 400` requests: 
![image](https://github.com/Joystream/atlas/assets/50830161/dd0ed200-769b-44e1-bb3b-18d5d11ae057)

They are:
- `{operationName: "GetBasicVideos",…}`
- `{operationName: "GetCurrentAccount", variables: {},…}`
- `{operationName: "GetKillSwitch", variables: {},…}`
- `{operationName: "GetUserCommentsAndVideoCommentsConnection",…}`
- `{operationName: "GetFullVideos",…}`

**Comment by dmtrjsg** [comment]
Adding to current sprint to get fixed
