### ISSUE TITLE
Handle errors in uploads

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#474]
We should automatically handle errors in uploaded assets. For example, if the storage provider becomes unreachable, we should pick another one and start over. Full flow can be seen here: https://github.com/Joystream/atlas/issues/381#issuecomment-802704377

This will also include some additional handling in the uploads view in case the app doesn't have access to the file anymore. When the app loads and there are some pending uploads, we should display a toast, like so: 
<img width="456" alt="Screenshot 2021-04-26 at 10 47 49" src="https://user-images.githubusercontent.com/12646744/116055308-dbe05600-a67c-11eb-846e-7237645e8347.png">

The uploads manager should probably also use the query node to do some initial sync on assets

**Comment by eldiegod** [comment]
Should this be fixed here?:

After clicking "start publishing" without having added a thumbnail the file drop shows this error but the upload starts and its successful 

<img width="1674" alt="Screenshot 2021-05-04 at 10 40 03" src="https://user-images.githubusercontent.com/10615263/116979459-520c3a80-acc5-11eb-86ee-55d96df351c6.png">

@kdembler

**Comment by kdembler** [comment]
huh, that shouldn't happen, but no, that's a separate issue

**Comment by kdembler** [comment]
fixed in #543 (issue reported by @eldiegod in a comment)
