### ISSUE TITLE
Test responsiveness of the views

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#475]
We should test the publishing views on a mobile view and make notes of any needed improvements

**Comment by mikkio-j** [comment]
##### Test responsiveness of the views

- Signin
  - Coins on small screen should not be visible (found in:  `join?step=0`)
<img src="https://user-images.githubusercontent.com/59691518/117788462-b68c4400-b247-11eb-8963-7028bd0612d9.png" width="200" />

  - Dialog's content not scrollable - covered in other issue (#477) (found in: `join?step=2`)
  - Joystream logo not aligned on smaller screens
  <img src="https://user-images.githubusercontent.com/59691518/117788600-d1f74f00-b247-11eb-86a2-ed2e095ccae1.png" width="200" />

- New channel
  - Select for language and privacy for smaller screens (some languages are not visible as well as second item in privacy)
  <img src="https://user-images.githubusercontent.com/59691518/117788644-dc194d80-b247-11eb-9f0d-b8d5ad78f502.png" width="200" />

- My videos
  - no videos svg illustration overflow (horizontal scroll)
- Video sheet
  - "Add new video" should not be visible on smaller screens
- Uploads view
  - Needs some general tweaks in upload bars and dropdown (not covered in designs). We've discussed that during one of the meetings and came to conclusion that it's not in the scope of sumer release
