### ISSUE TITLE
Opening Up Gleev: Short-term

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4777]
# Background

At this point we are turning away the majority of creators that are signing up to YPP, and this is costly in many regards. We need a way to opening it up to more creators while preserving the integrity of the experience, not breaking the YPP economics and having a workable operational routine.

# Proposal

This proposal is an iteration of the proposal made in this longer [Gleev Strategy Document](https://docs.google.com/document/d/1_ogZHkm0jUq_QFNKxyXeeOt2KzESsHUaNAIE2Rf_-gI/edit). Reading that document will help aid the understanding of _why_ this proposal is made.

# A note on categories

Recall that videos have categories on-chain, in their metadata, and that yt-synch backend has a default category set for channels, so that all replicated videos from YT have this category set on-chain during publication, and lastly Atlas itself has a notion of _display categories_ which basically are synthetic app level categories, and a mapping exists from on-chain video categories for display categories. Display categories are used in the discovery tab of Atlas, and nowhere else (is this true?).

For this issue I propose the following in order to have an easy way to facilitate the proposal below.

1. We expand the number of public video categories to be much broader, covering a wide range of topics where creators are unlikely to find it difficult to categorize their vertical properly.
2. We drop the discovery page, and in general do not use display categories for anything for the foreseeable future. We may consider adding it back later for the long term plan, perhaps as community specific display categories, but no reason to over-engineer now.
3. We introduce a new database field `block_from_home_screen:bool` for channel entities, it is private, so it should not appear in schemas or public API for Orion (I hope and assume Subsquid supports this). When the value of this field is true, then the home page query excludes all videos of from such channels from the result. The idea is that this field allow us to manually control what topics we don't want presented on the home screen specifically. It should be easy for an operator to update this value the same way they are updating values about general filtering for channels today, however that is done.

# Proposal

The idea here is to keep our marketing and home page focused, so that the first impression retains its current coherence, but then to allow us to welcome everyone we are currently turning away.

- Keep doing marketing focused on crypto only.
- Home screen only shows crypto content for users that do not have an account, but the rest of the app still shows all content which is linked to through hard links, or search results or the discovery page, or next video, or marketplace features/lists.
- All references to content focus are removed from the app.
- YPP has uniform payment terms across all content types.
- On-chain categories are diversified, and continuously diversified to match the pool of creators that join.
- When creators sign up as part of YPP flow, they have to pick which on-chain category they fit into, and this value is stored in yt-synch backend as today: this will be a much larger number of categories than today.
- The default value of new channels in Orion is `block_from_home_screen := true`.
- Creators are automatically synced right away, and they will be paid at the end of the week as long as the channel is not a straight up fraid attempt, like white noise videos.
- A retroactive, possibly weekly or daily, manual check is done on the content, and if the channel crypto related, then `block_from_home_screen := false`
- The payment schedule will be made more fine grained, and payout rates will be reduced, so as to accommodate increased throughput within existing budgets.

Notice that we do not try to deal with the fact that the creator may identify their videos with incorrect on-chain channels.

## TODO

At the very least the possible is needed

- a more sophisticated way of picking on-chain video categories during signup flow is needed, in particular which scales with a much larger number of categories.
- Pick a new suitable set of categories, a large number is appropriate here, to make sure to reflect the true diversity of content out there.
- Drop Discovery area: not used, not critical, does not scale to number of display categories.
- Update Orion schema and allow operator to update given channel value.
- Retroactively verify backlog of old creators who tried to sign up in the past, but not all at once.
- Do Orion migration that sets all currently verified channesl to have `block_from_home_screen := false`

**Comment by attemka** [comment]
@bedeho A few questions after reading this + [Gleev Strategy Document](https://docs.google.com/document/d/1_ogZHkm0jUq_QFNKxyXeeOt2KzESsHUaNAIE2Rf_-gI/edit):

1. It's not clear to me how will the homepage content be managed after these categories changes. From this issue: 
>  When the value of this field is true, then the home page query excludes all videos of from such channels from the result.

From the document: 
> Home screen only shows crypto content for users that do not have an account, but the rest of the app still shows all content 

So, what will be the new positioning of the Gleev? Currently it's the Atlas for crypto content **only**, but after the changes it seems like it will be the Atlas for all content with a slight bias towards the crypto?
I assume it would be the case that Gleev will attract some users who are completely uninterested in crypto topic, how will the homepage look for them if all non-crypto content is hidden from the homepage by default?

2. How will the apps ecosystem look like? I might get it wrong, but as far as I understand it now we have a Gleev, crypto-specific app, and if someone wants to extend the categories with the topic he likes he can create a new topic-specific app. Would it even be the case after these changes?

**Comment by dmtrjsg** [comment]
@bedeho 
Why would we want to add the `block_from_homepage` parameter, if we can
1. Map all current crypto sub-categories to a single Crypto category
2. Simply limit the homepage feed to display Crypto category only?

That would allow us to add more categories and mixed categories to homepage feed setting later.

**Comment by bedeho** [comment]
> It's not clear to me how will the homepage content be managed after these categories changes. From this issue:

Home page only shows crypto content, but rest of app allows playback, search and linking to any kind of content, that is desired effect. The idea is that this is achieved by having a new field which marks channels for being suitable for being on home page or not.

> So, what will be the new positioning of the Gleev? Currently it's the Atlas for crypto content only, but after the changes it seems like it will be the Atlas for all content with a slight bias towards the crypto?

The document tries to explain it, but briefly stated. The core premise here is that
- we are actively targeting crypto creators, and also most consumers who want to understand our project, are from crypto, for their sake, our product will be more coherent if it only shows crypto when you land on it and start exploring.
- we want to allow non-crypto creators as well, but we are not expecting strong consumer demand for this, so we just disregard consumers of non-crypto, worst case, they have to know about the exact video or channel they care about.

> How will the apps ecosystem look like? I might get it wrong, but as far as I understand it now we have a Gleev, crypto-specific app, and if someone wants to extend the categories with the topic he likes he can create a new topic-specific app. Would it even be the case after these changes?

So short term, there is no app ecosystem, there is just Gleev, keep that in mind, that is already in the document. l1media is totally unmaintained, many versions behind, not even YPP. So no need to expct things to change spontanously. Long term, we want more apps, but we want those apps to be more differentiated as experiences in a deep way, not just by content focus. So we will turn effectively Atlas into app that allows you to launch content focused experiences on-demand, just like you can launch topic focused subreddits on-demand, solving all the insane complexity of hosting running Atlas, as described.  At that point, other applications should try to differentiate themselves in a more deep way than just forking features of Atlas, but again, this is much longer term in my opinion.

**Comment by bedeho** [comment]
> That would allow us to add more categories and mixed categories to homepage feed setting later.

So this is a different experience, it could be done, I'm not sure I buy it, I suspect we just end up with what we currently have, which is a discovery section that people don't use. People use what you show them, unless they have a very strong idea of what they are trying to do. _But_, I have an open mind about this.

But for this to work, what you are describing of mapping on-chain categories to dispaly categories, is not ideal. That reintroduces the problem of having display be contingent on possibly incorrect, or at least mismatching, with public data. The public data has different semantics, its what the creator says the video is about, which is not the same. So what we would have to do would be to have app level category space , and then for each channel have the app level category of that channel, and then the app use this. This is not the same as current display categories, as display categories are mapped into using on-chain video categories. So the difference between what this would look like, and what I describe above, is that `block_from_homepage`  would instead be called `app_category: AppCategoryId`. My suggestion is that we just leave display categories as they are, but just remove this part of the experience, and later revisit what to do with them, that seems costless.

We could do this, perhaps its even a good idea - if the time from this going into production to having proper communities, however

**Comment by dmtrjsg** [comment]
Dev scope is captured here:
#4772
