### ISSUE TITLE
Channel not found flashes

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4790]
**Describe the bug**

When I load channels, I very briefly - perhaps for 300ms, see the standard error message for when an invalid channel id is provided, namely

![Screenshot 2023-09-01 at 22 29 51](https://github.com/Joystream/atlas/assets/437292/3ddc0863-094b-4f2f-922e-3829c7dbc194)

and then 

**To Reproduce**

1. Go to any channel URL, e.g `https://gleev.xyz/channel/28147?tab=Videos`

**Expected behavior**

Seeing the loading state and then the channel.

**Screenshots**

See above.

**Device (please complete the following information):**

- OS: macOS Ventura 13.4.1
- Browser: Firefox 116.0.3 (64-bit)

**Additional context**

Likewise, when I input an invalid channel ID, I actually also see the proper loading state intermittently, and only then the failed state is shown.

**Comment by dmtrjsg** [comment]
To be solved with
- https://github.com/Joystream/orion/issues/180
