### ISSUE TITLE
Something went wrong flash

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#4798]
Basically exact same issue as this https://github.com/Joystream/atlas/issues/4790, except that the "somethign went wrong" error message flashes, happens all the time, but not reliably, when you use a link at least. Is really bad for UX, as you feel something failed, and you are still kind of confused when page loads about whether you where phished or something else.

**Comment by dmtrjsg** [comment]
To be solved with
- https://github.com/Joystream/orion/issues/180
