### ISSUE TITLE
Remove pre-population of emails from YT

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4807]
## Context
@plus.google.com emails are populated for branded channels and people don't change it, that causes support requests. 

## Scope
- [ ] Remove pre-population of emails from YT to the sign up flow form

**Comment by WRadoslaw** [comment]
@dmtrjsg we can ensure that pre-population only works if the email ends with `@google.com` and if it isn't just the user will have to input it

**Comment by dmtrjsg** [comment]
Yeah that works 👍
