### ISSUE TITLE
YPP 2.0 - Sign up flow update

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4825]
## Context
- https://github.com/Joystream/atlas/issues/4772

## Scope

1. YPP reqs update - update reqs for quality/ frequent/ original content/ at least 1 video every month, last 3 months. 

List of requirements> 

💡 Original content, without reposts from other creators.
💡 Organic audience without bots, ramped up subscribers and fake comments.
💡 Must be older than 3 months.
💡 Has at least 100 followers.
💡 Has at least 10 videos, all of which are older than 1 month.
💡 Has at least 1 video per month posted over the last 3 months.

⚠️ Let's make sure that we also display the correct "failed" requirements modal. 

2. Channels select category from a larger diverse set:
Art
Animation and Film
Autos and Vehicles
Business and Finance
Crypto
DIY
Education
Entertainment
Lifestyle
Memes and Humour
Music and Music Videos
Nature
News and Current Affairs
People and Blogs
Pets and Animals
Sports
Technology
Travel
Unboxing
Video Games

3. Seed phrase is not copied to buffer but exported to a text file on the machine. 

4 🆕 
- https://github.com/Joystream/atlas/issues/4574

2:31 in the video linked in the comments

5 🆕 
Remap all currently active categories on Gleev to a single "Crypto Category"

out of scope:
~Language is pre-populated from the YT channel, but can be changed~

**Comment by KubaMikolajczyk** [comment]
The work is done here and can be reviewed ✅

🎥 Video update: https://www.loom.com/share/a195e89ef0e942ec8d2c88d39fe0bd9b?sid=5631c306-0e98-4562-80c5-4a885e63474f

📄 YPP Changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=SgzSZPfrnc7E0hee-4

📄 Sign up changelog: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=2013-33819&mode=design&t=ShKWtjoDSKTLN4JY-4

**Comment by dmtrjsg** [comment]
[Link to requirements modal>](https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=4499%3A97733&mode=design&t=yH08Gb0RK74wr5HN-1)
