### ISSUE TITLE
Reward withdrawal/claim: disallow Polkadot formatted addresses

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#4874]
Background: https://discord.com/channels/811216481340751934/1147348817692340284/1152219779160096849

This is now I think the 2nd or 3rd time that a user has sent funds to a Polkadot address which is on an unsupported exchange. It seems like it would be prudent to verify addresses have Joystream or at least Substrate generic address formatting to help avoid this.

**Comment by dmtrjsg** [comment]
@mochet thanks for raising this issue. We will include the validation of address format to the next release which allows to withdraw to external address from 
- Payouts dashboard withdrawal
- Member drop down transfer modal

Check for 
- length
- prefix
...

Display validation error on the field input 
"Address does not follow Joystream or Substrate Generic format"

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk 

Artem has added a validation for address format but we don't want to simply disallow and block transfers to polkadot generic accounts and show a message  "Address does not follow Joystream format. Make sure that destination address supports Joystream token before transfer." May I ask you to update the transfer/ withdraw modal designs to accommodate for it.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg  The text field for entering the address together with users interactions with it are captured in user stories ✅ and ready to be reviewed:

📄 Withdrawal: https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?type=design&node-id=2659-35330&mode=design&t=O4AIFrrWeeRr1nuc-4

📄 Withdraw to external wallet: https://www.figma.com/file/ZFRXsyGvnBXnkDUUGc5vyR/My-payments?type=design&node-id=3321-7796&mode=design&t=O4AIFrrWeeRr1nuc-4
