### ISSUE TITLE
Notifications QA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4891]
# Test

## links
Orion dev epic
- https://github.com/Joystream/orion/issues/126
Orion events:
- https://github.com/Joystream/orion/issues/155

## Data for Testing

Env: https://atlas-git-fork-thesan-feature-orion-notifications-joystream.vercel.app/

acc1: notifqa1
`hollow adjust faith actress again rebuild door whip orient favorite wide zone`
creds: notifqa1@gmail.com / Passw0rd123&
channel: notifqa1channel  (id - 260)

acc2: notifqa2
`meadow maple syrup weapon correct comfort husband rally chronic advance soldier expire`
creds: notifqa2@gmail.com / Passw0rd123& 
channel: notifqa2channel

### Member
- Channel created
- Someone replied to your comment
- Someone reacted to your comment
- Followed channel posted new video
- Followed channel put a new nft on auction
- Followed channel put a new nft on sale
- NFT bid outbid (someone places a higher bid than your own)
- NFT open auction bid won
- NFT open auction bid lost

#### Engagement
- New Channel follower
- Comment Posted To Video
- Video Liked
- Video Disliked

#### YPP
- YPP Channel verified
- YPP Channel suspended

#### NFTs
- NFT purchased
- NFT bid received (for auction creator)
- NFT royalty payment received
- Channel received direct payment (via member remark)
- Funds withdrawn from channel account (to member acc)

#### Moderation
- Channel excluded from App
- Video is excluded from App
- Video featured as Hero
- Video featured on Category page
- NFT is featured on the Marketplace

**Comment by dmtrjsg** [comment]
# MEMBER

_______________________


## Basic
1. By default the membership icon displays `2`. No actions were done at all at this point. Only created membership.

<img width="295" alt="Screenshot 2023-09-18 at 18 12 07" src="https://github.com/Joystream/atlas/assets/93924525/dcfe1688-4d91-456f-bf5f-74d8d3459cc7">

2. As soon as channel is created, the profile drop down display counter in studio
<img width="306" alt="Screenshot 2023-09-18 at 18 23 30" src="https://github.com/Joystream/atlas/assets/93924525/3fe4eecf-2150-4321-9cfe-3e62720e4e90">

3. Channel Avatar not showing
<img width="378" alt="Screenshot 2023-09-18 at 18 36 32" src="https://github.com/Joystream/atlas/assets/93924525/f62b04b0-969d-4eb5-a49f-a472964dae93">

## Engagement User
1. Someone replied to your comment ⛔. Needs to go to `Member notifications`, now in channel. Also check spelling please.
<img width="481" alt="Screenshot 2023-09-18 at 18 55 01" src="https://github.com/Joystream/atlas/assets/93924525/59c4fea2-ad45-4663-8799-2727bfa1d586">
2. Someone reacted to your comment ✅ 



## NFT user
1. Channel added NFT on auction ✅ 
2. Channel added NFT on sale  ✅ 
3. Someone placed higher bid ⛔  - just not showing at all
4. You won NFT auction ✅ 
5. You lost NFT auction ✅ 


## Hyperlinks 
1. Comment reaction only redirects to video page, and not to the comment itself. 🟡 
2. NFT on Auction and on Sale would need to have expanded widget
3. You lost NFT auction. Add "Withdraw your bid". To the notification text.

**Comment by dmtrjsg** [comment]
# CHANNEL
_________________

## Engagement
1. New channel follower ✅ 
2. Comment added to video 🟡  - screen should focus on comment, not just redirect to video.
3. Dislike 🟡  does not display member handle correctly
<img width="450" alt="Screenshot 2023-09-19 at 15 02 38" src="https://github.com/Joystream/atlas/assets/93924525/568b306c-e2b7-40d6-90b7-18f1d478960e">

<img width="1357" alt="Screenshot 2023-09-19 at 15 02 55" src="https://github.com/Joystream/atlas/assets/93924525/56bd6132-8305-4d61-8fa5-98744da667a4">
4. Like 🟡  does not display member handle correctly (same as dislike)

## YPP 
🚫 Cannot test before its merged to Dev

## NFT

1. NFT bid received (for auction creator) 🔴   - no notification at all
2.  NFT purchased - 🟡 
3. NFT royalty payment received - 🟡 
Avatars are blank in both cases above
<img width="424" alt="Screenshot 2023-09-19 at 15 33 29" src="https://github.com/Joystream/atlas/assets/93924525/dd89bbbf-b382-4e38-b4d6-0d249ee68415">

4. Channel received direct payment (via member remark) 🚫   - blocked, pending instructions how to pay channels on dev
5. Funds withdrawn from channel account (to member acc) 🔴   no notification at all

## Moderation

1. Channel excluded from App - 🔴 
`Was testing "excluded channel" notifications.  Expected scenario was that once the channel is excluded by moderator, channel owner would receive this notification in their studio (so to their channel). 
It appears that once the channel is excluded it totally vanishes from the app, and owner does not see it at all or have access to the studio side for such channel. 
Suggest to keep the channel in the studio view but only hide from the "viewer side". 
If that is technically challenging, I think we should show such notification on the member side.` 
2. Video is excluded from App - 🔴  no notifications at all
3. Video featured as Hero - deprecated as discover page is now gone ⚫ 
4. Video featured on Category page - deprecated as discover page is now gone ⚫ 
5. NFT is featured on the Marketplace 🔴  no notification at all

**Comment by dmtrjsg** [comment]
### Atlas

-  NFT on Auction and on Sale would need to have expanded widget
-  You lost NFT auction. Add "Withdraw your bid". To the notification text.
-  NFT purchased , NFT royalty payment received : Avatars are blank

### Everything else is Orion 
Linked to PR 195

**Comment by thesan** [comment]
### Fixes needed on Atlas
-  NFT on Auction and on Sale would need to have expanded widget
-  You lost NFT auction. Add "Withdraw your bid". To the notification text.
- Channel Avatar not showing

### Missing notifications Orion
- `HigherBidPlaced`
- `NftFeaturedOnMarketPlace`
- `CreatorReceivesAuctionBid`
- `VideoExcluded`
- `ChannelExcluded`
