### ISSUE TITLE
Playback issue on Mobile

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4898]
Video example: https://gleev.xyz/video/97910

Plays smoothly from Desktop on Chrome
Playback does not start on mobile from Chrome or Safari

Test session: https://app.livesession.io/app/sessions/f984a5c2-1e66-40c3-59db-4b940eed9e89/2ec240e0-23f0-4c44-5f1f-002ce3fcdfd8

<img width="1107" alt="Screenshot 2023-09-19 at 14 42 08" src="https://github.com/Joystream/atlas/assets/93924525/a9f21176-53a8-4961-9e6d-2c000c1937dc">

___________
Reported by user from `The Uk (B14 6RY) Virgin media provider`

[IMG_4738.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGF5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10aa5cfdc4719556103908c7f7c99ef17ec033a1/IMG_4738.pdf)

Livesession link: https://app.livesession.io/app/sessions/9703df2e-4351-4389-747b-068900e7abbc/1f1a1819-bff2-44b6-6e2d-ee87ace24d22

Screenshot of console errors from Livesession
<img width="1402" alt="Screenshot 2023-09-19 at 14 40 53" src="https://github.com/Joystream/atlas/assets/93924525/6f85d895-5c2f-44c6-957a-c6a3320c249c">

**Comment by WRadoslaw** [comment]
Issue is caused by iPhone not supporting one of the codec, no obvious fix in Atlas
