### ISSUE TITLE
Update Categories on Chain, Gleev and Orion

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4925]
1. Create categories on chain
2. Share the codes for them here in the comment
3. Prepare Gleev config to get updated on the day of release

Categories list:
- Art
- Animation and Film
- Autos and Vehicles
- Business and Finance
- Crypto
- DIY
- Education
- Entertainment
- Lifestyle
- Memes and Humour
- Music and Music Videos
- Nature
- News and Current Affairs
- People and Blogs
- Pets and Animals
- Sports
- Technology
- Travel
- Unboxing
- Video Games

**Comment by attemka** [comment]
Categories created:
- Art - **4209396-2**
- Animation and Film - **4209546-2**
- Autos and Vehicles - **4209572-2**
- Business and Finance - **4209583-2**
- Crypto - **4209591-2**
- DIY - **4209595-2**
- Education - **4209603-2**
- Entertainment - **4209609-2**
- Lifestyle - **4209637-2**
- Memes and Humour - **4209643-2**
- Music and Music Videos - **4209650-2**
- Nature - **4209658-2**
- News and Current Affairs - **4209664-2**
- People and Blogs - **4209674-2**
- Pets and Animals - **4209679-2**
- Sports - **4209685-2**
- Technology - **4209691-2**
- Travel - **4209700-2**
- Unboxing - **4209707-2**
- Video Games - **4209721-2**
