### ISSUE TITLE
Maintenance screen for CRTs

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4937]
## Context
We are adding an option to disable CRTs from the runtime

## Scope
- [ ] Create a version of the maintenance screen for _only_ CRTs (CRTs module is disabled)

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg I have a simple concept for the maintenance screen with key visuals presenting the idea of maintenance being done on the CRTs module ✅

📄 Maintenance changelog: https://www.figma.com/file/xBXWBZMqM0JAydQZ7ZaZ6D/Maintenance-page?type=design&node-id=916-16424&mode=design&t=uG2AAdGErx7uk2r5-4

**Comment by dmtrjsg** [comment]
If its not too much work - we need to add a way for Atlas to actually check if the pallet is disabled. Manual on-off state is also okay if saves us a lot of time. NB: Builders WG QA team will be testing as part of Nara release qa.

**Comment by dmtrjsg** [comment]
Channel was suspended due to misleading content. Example: https://www.youtube.com/watch?v=ga0cLA6AbYk

**Comment by dmtrjsg** [comment]
Confirmed to invoke it manually from config upd.

**Comment by dmtrjsg** [comment]
@WRadoslaw pls add a manual on how to to enable this for the builders

**Comment by WRadoslaw** [comment]
In `atlas.config.yml` change entry `general.crtMaintenanceMode` to `true` to show maintenance and `false` to disable it
