### ISSUE TITLE
Referrals tab with the updated tiers

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4943]
## Context

Current designs of the referrals dashboard has 
- channel title
- channel tier 
- status (unverified, verified, suspended)
- date of sign up
- rewards

With the new tiers which combine the verification status and the tier itself (as well as suspended + reason) the table needs a redesign

## Scope
- [ ] Update referrals tab to combine verification status and the new updated tier or suspended reasons

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg  The referrals table is updated with a new proposition for displaying ranks and statuses of recommended channels - its ready to be reviewed ✅

📄 Referrals changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=oyvr8Fx96MkSz91U-4
