### ISSUE TITLE
Additional icons for YPP 2.0

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#4956]
- static icon for "Verification pending"
- icon for the "opted out state" which is now added to the list of states so channels which opt out will be shown in the referrals table (this is a temp solution but we still need to show it somehow)

**Comment by KubaMikolajczyk** [comment]
Added the verification pending static icon to the api icons and opted opt state to referrals and dashboard ✅

📄 Static icon: https://www.figma.com/file/1uxugLps6oooI38PGmdrn9/Figma-API--%3E-Storybook?type=design&node-id=2645-501&mode=design&t=lnYoOGOACpVo6h7G-4

📄 YPP changelog: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=3338-84773&mode=design&t=AAq0sxScVGATWnle-4
