### ISSUE TITLE
Loading screen flashing in sign in view

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#500]
When a user is going through the second step of signing in on `signin/join` and creates an account in Polkadot extension, the loading screen flashes for a second
![Nagranie z ekranu 2021-04-22 o 16 47 27](https://user-images.githubusercontent.com/51168865/115735635-ee137900-a38a-11eb-8219-b2d6a04b2407.gif)

This is happening because we are using `useMemberShips` query in `StudioLayout`
```js
      {extensionConnectionLoading || activeUserLoading || membershipsLoading ? (
        <StudioLoading />
      ) : (
        <>
              <Routes location={displayedLocation}>
               // ...
                <PrivateRoute
                  path={relativeRoutes.studio.signInJoin()}
                  element={<SignInJoinView />}
                  isAuth={!hasMembership}
                  redirectTo={ENTRY_POINT_ROUTE}
                />
             // ....
       </>
```
Basically, every time user creates a polkadot account, the number of `accounts`(which we use as an argument in `useMemberShips`) will increase. This will cause `userMemberships` to refetch and as the result, the loading screen will show up. 

Unfortunately, we cannot just get rid of it.  If we do that, we will see the flashing of `SignInJoinView` every time the user visits `/studio`

**Comment by kdembler** [comment]
This has slightly changed since the issue was created but the behaviour still exists. I think it will happen only when you add the first Polkadot account. We would probably need some condition that checks if the app has already initialised and if so, don't show the full page loader again. Ping me for more info
