### ISSUE TITLE
CRT integration issues

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#5030]
The aim of this issue is to group all problems encountered during Orion integration with UI part of crt dashboard tabs (settings are out of scope).

1. How can we get holder token transferable balance, from orion we get total and locked balances, plus vestings. I don't see any rpc level subscription to get this info.

UI ref: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejQ3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cf40ab2aad0b01443e3682a899b7325b3a1ba08/image.png)

2. It was discussed, but just to confirm and have a record of it. How to check how many holders can participate in revenue share in general? 

UI ref: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGc3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35906faec178a07e3a7a9ffd0e0222c0ae984a84/image.png)

3. How to check how much earnings will holder receive before staking their tokens?

UI ref:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHM3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--228f556a6b737946c7e9ce79e6f2dd99e4201c6b/image.png)

4. How to parse tokens into fiat value? 

5. How to check whether the revenue share participant claimed their tokens back (`RevenueShareParticipation`)? We need to to correctly display either a button or status pill. We could add a flag to entity to indicate that given participation was claimed.

6. Atlas only: Introduce pagination for holders table
7. Atlas only: Create a parent drawer for picking market or sale and integrate crt market modal with it.
8. Atlas only: Followup integration for participation widget on revenue share. Rn it almost doesn't represent real data. We don't know what are the boundaries for max holders/earnings.
9. Atlas only: Follow logic got broken due to differences of schema

**Comment by dmtrjsg** [comment]
1. Transferable balance
Total balance - locked by vesting - staked amount (they overlap as holders can stake locked tokens!)
If staked = 0, then transferable= Total - unvested
If staked >0, then unvested amount is prioritised for staking, then you stake your free tokens. 
Formula for getting the `free CRT balance = total balance - max[locked,staked]` 

⚠️  FE would need to calculate the new amounts we display to every user in the UI. 
For that there will be a Resolver built on Orion side.
- transferable
- vesting schedule
- staked

2. Can someone stake tokens who buys them during the revenue split?
- Yes.

3. How to get the dividend amount in JOY tokens for staking CRTs?
- ⚠️ Currently not present in Orion, nor RPC. Agreed to add resolver on Orion side so Atlas would just fetch this value and display. 
`Formula = Total Revenue Split allocation * creator tokens staked amount / Creator Token Issuance`

4. How to convert CRT token value to JOY token value? We have er for JOY <> USD but how do we know the price of CRT in JOY?
- If the market is open we can get it from the AMM. Formula @ignazio-bovo to share, @WRadoslaw to comment if that can be handled on the FE 
- If the market is closed but the sale is open. Check Sale price. 
- if the market is closed and sale is closed, take latest historical price. 
⚠️ Add extra field for token entity - latest price to be added to Orion mappings. 

5. `RevenueShareParticipation` has no info about status of members if they _unstaked already_ or not?
- ⚠️ new flag will be added to `RevenueShareParticipation` with the status whether the stake was recovered.

**Comment by WRadoslaw** [comment]
## Update 19.10.2023

During token preview implementation I noticed that in UI we have a lot of aggregated statistic values. Calculating them in Atlas is inefficient both performance- and bandwidth- wise. 

Required fields: 
1. Market cap for token
2. Total revenue generated by the token
3. Total revenue shares (we assume that it's it aggregated value of earnings for all revenue shares)
4. Total transaction volume (not sure what should it represent)

UI ref:
![image](https://github.com/Joystream/atlas/assets/92513933/eae848a0-68b9-45bf-a7d5-60777674c35b)

**Comment by dobertRowneySr** [comment]
# A few solution for the above problems:
> Transferable balance
Total balance - locked by vesting - staked amount (they overlap as holders can stake locked tokens!)
If staked = 0, then transferable= Total - unvested
If staked >0, then unvested amount is prioritised for staking, then you stake your free tokens.
Formula for getting the free CRT balance = total balance - max[locked,staked]

We can resort to a resolver in order to compute this without modifying the runtime further.
The resolver will take a required `blockHeight` in order to compute how much has been vested and from there loop through all the Account active vesting schedules obtaining the total `locked` amount. Then the `transferrable_balance` can be easily computed

> How to convert CRT token value to JOY token value? We have er for JOY <> USD but how do we know the price of CRT in JOY?

As mentioned after processing any event related to price alteration we can update a field called `lastPrice` on the creator token entity

> Can someone stake tokens who buys them during the revenue split?
I believe I lost what are the implications of this in the FE

> Market cap for token

If we add the `lastPrice` fields then we can do `totalSupply * lastPrice` to get the price in HAPI then you can do the conversion in USD on Atlas

> Total revenue generated by the token

@KubaMikolajczyk can you please specify how you would compute (or imagine this would be computed)?
> Total revenue shares (we assume that it's it aggregated value of earnings for all revenue shares)

@KubaMikolajczyk same

> Total transaction volume (not sure what should it represent)

@KubaMikolajczyk same

**Comment by dmtrjsg** [comment]
@ignazio-bovo 

Let me try to handle it

1️⃣ Total Revenue - This is a duplicate of the total revenue shown on top of the screenshot. It will only be shown once (on top, so designs will be updated to get it removed form statistics). 
`Total revenue formula = Memeber remark payments + Council payouts claimed + NFT sales revenue + NFT royalties.`
2️⃣ Total Revenue Shares - so when channel starts a revenue share, there's a certain amount that is allocated to the token holders (based on revenue share split)
`Formula = SUM of all historical (Revenue Share Amount in JOY*Rev share ratio)`
3️⃣ Total Tx volume  - same concept as trading volume
`Formula =  CRT Tokens purchased on AMM + CRT tokens sold on AMM`

**Comment by dmtrjsg** [comment]
Update from Bedeho: 

@ignazio-bovo @WRadoslaw 

```
`Tx Volume` is just trading volum in JOY, so total JOY transacted with AMM over some period of time. So whenever there is transaction with AMM, the amount of JOY exchanged is added to the volume. 

As far as data goes, so what Orion tracks, I think we def. need a volume timeseries: so basically total volume for each CRT on a per block basis.
Other related timeseries worth tracking could also be fees paid the amm.

However, as far as showing "current volume daily/hourly" on each CRT, like in the UI, if we don't want to do any client side compute, then I think we need a new custom URL endpoint in Orion which does this computation on a per need basis, rather than track historical volume per day, as that will be a lot of compute overhead for limited benefit. Not sure if there is some cheap way to do this which is worth it, but not sure its worth doing now even if possible.
```

Also updated formula to `Formula =  CRT Tokens purchased on AMM + CRT tokens sold on AMM`

**Comment by WRadoslaw** [comment]
## Update 23.10 

To simplify update logic for token metadata I propose to change the behavior of two fields.

### Benefits 
Simple full replacement:

1. No prop on metadata - do nothing
2. Empty array - remove all
3. Array with some items just replace them

### Video trailer

1. If there is no prop/it is null or undefined - remove the trailer
2. If there is, just switch it up

**Comment by dmtrjsg** [comment]
Updated comment to add point about duplicated `total revenue` here: 
- https://github.com/Joystream/atlas/issues/5030#issuecomment-1771180492

**Comment by dobertRowneySr** [comment]
> 3️⃣ Total Tx volume - same concept as trading volume `Formula = CRT Tokens purchased on AMM + CRT tokens sold on AMM`

This is already retrievable from the `AmmCurve` entity

**Comment by dmtrjsg** [comment]
`Total revenue formula = Memeber remark payments + Council payouts claimed + NFT sales revenue + NFT royalties.` was updated in [this comment](https://github.com/Joystream/atlas/issues/5030#issuecomment-1771180492)

**Comment by dmtrjsg** [comment]
@ignazio-bovo mate we need a resolver for `Total revenue`, as fetching this and calc on fe turns out too big in context of all other elements on the page.
