### ISSUE TITLE
Tech debt: Refs in providers

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#5033]
This problem came to our attention thanks to #5028, it looks like our blacklisting logic is not working correctly, so the user will try to upload to the same storage operator even tho an error is expected. 

This issue is caused by the usage of react `useState` hook in providers for values that are not bound to UI in any way. This results in unexpected behavior of in this example operator blacklist, it's simply just not updated at the time on retry. 

A solution for this would be switching from `useState` to `useRef`, it will enforce data to be in the latest state without relying on renders.

**Comment by dmtrjsg** [comment]
Causes the error here: 
- https://github.com/Joystream/atlas/issues/5028
