### ISSUE TITLE
Introduce Featured video on channel page

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#51]
Some version of a very prominent intro video on a channel page.

**Comment by kdembler** [comment]
Unless we pick this video somehow locally in Atlas, this will need support from the query node and is likely blocked by #122

**Comment by bedeho** [comment]
I think this issue needs to be marked as an idea, not as something we are going to do, sorry it took any of your time. Will add.

**Comment by kdembler** [comment]
No problem

**Comment by eclipsingbinary** [comment]
This would be a good idea
would love to see introduction or featured videos when I visit channels
I don't know if there is any research on the success of those in other platforms but I personally like them

**Comment by bedeho** [comment]
I think we actually just need a proper highly customizable landing page for channels, that is pretty clearly important, having a featured video is just one possible subcomonent of that.

**Comment by bedeho** [comment]
Superceeded by https://github.com/Joystream/atlas/issues/3694
