### ISSUE TITLE
Allow dynamic page title

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#510]
Dynamic page title would be a nice addition to Atlas - the browser tab name could change depending on the content displayed. (video, channel, "add new video", etc)

**Comment by MIPB** [comment]
Can I try to solve this issue?

**Comment by kdembler** [comment]
Sure thing, feel free to give it a try. I'm not exactly sure how this would work though - if we want the title to be truly dynamic, then we would need to use the data used on a given page. For example, how do you set it to the title of the video? It's doable, but may be a bit tricky. I suggest we discuss the solution here first to make sure it fits nicely and start implementation then

**Comment by brabbuss** [comment]
@MIPB @kdembler I should've probably piped in here before working on this issue. I had begun adding dynamic titles and interpolating in relevant information as well as copy for while the video is loading. 

I was unsure of procedure, but I can hold off from coding any further just let me know! Anything I should know going forward? Still new to open source projects.

ex: 
![Screen Shot 2021-04-26 at 1 09 59 PM](https://user-images.githubusercontent.com/66697338/116137593-fae8e300-a690-11eb-8489-15bd0ab99f49.png)
![Screen Shot 2021-04-26 at 1 09 47 PM](https://user-images.githubusercontent.com/66697338/116137600-fde3d380-a690-11eb-8fce-e94d28934991.png)

**Comment by MIPB** [comment]
I see @brabbuss has already started the improvement so I'll let him work on it. Looks good 👍

**Comment by kdembler** [comment]
Oh wow, got a little crowded in here! @brabbuss if you're already working on it, please continue, but going forward it's a good idea to mention when you start working on something so we don't run into situation where two community members work on the same thing 😅 

Since you already have something working, I guess at this point, just open a draft PR once you feel good about it (doesn't have to be yet implemented for all the views) so we can discuss there. Thanks! 👍

**Comment by brabbuss** [comment]
@kdembler @MIPB thanks! And sorry for the lack of communication there, I'm very new to the open source workflow.

@kdembler Is there a specific timeline where you'd prefer this issue be resolved by, or some general cadence to resolving issues? And will do on the draft PR - thanks all 😅

**Comment by kdembler** [comment]
No worries, we managed to resolve this on time! And welcome to the open source community :)

Regarding the timeline, there isn't any really, that's just something that came to my mind today, it's not part of any bigger release. So as long as it doesn't drag for over a month, it's fine with me 😄

**Comment by brabbuss** [comment]
@kdembler Perfecto, and thank you for the warm welcome 😀
