### ISSUE TITLE
Repeat sign up attempt when membership was already created

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5134]
## Context
We have a lot of users timing out on signing up to YPP. When they do- they cannot sign in or sign up again as memebrship already exists. 

Here's the detailed error breakdown in the flow: 
- https://github.com/Joystream/atlas/issues/5134#issuecomment-1786986268

## Scope
Originally suggested
- [ ] Suggest how the backend error response needs to be modified so we can help such users to continue with sign up, instead of deleting the record manually and trying again. 

⚠️ after discussing with the team the suggestion was for such users to create a flow where they can continue the sign up flow with existing chain membership (by providing their seed phrase) and create Orion account (by adding email and password).

**Comment by dmtrjsg** [comment]
ℹ️  Some users do not have membership created but already added to YPP table

<img width="758" alt="Screenshot 2023-10-26 at 12 16 23" src="https://github.com/Joystream/atlas/assets/93924525/bdda062b-c60d-417a-9c72-f432b5f99ffb">

**Comment by dmtrjsg** [comment]
membership = chain
account = orion
user record=  yt sync be

1. After user comes back from GoogleAuth page (and grants access) Atlas takes YT auth code and sends it to YT BE `users` endpoint
2. YT BE creates user in the `users` table using the auth code and adds info below
```
email: string
userId: string
..
```
  3. Then if they abandon / timeout due to Orion sync taking too long at the point of creating membership -> the user record is created, and on-chain membership also but Orion account is not 🚫 
  
In such cases the users see this modal for hours:
<img width="300" alt="Screenshot 2023-10-31 at 15 05 17" src="https://github.com/Joystream/atlas/assets/93924525/d3e3237f-7573-4cf2-b5cd-dab0e2e48170">

The result would be:
Membership created
Orion account not created

⚠️  Then they cannot sign in or sign up again

**Comment by WRadoslaw** [comment]
![flow-exca](https://github.com/Joystream/atlas/assets/92513933/c19ba887-5edd-4a34-b2f5-657ff7a60d5d)
