### ISSUE TITLE
CRT Follow up Design Feedback

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5201]
## Context

Feedback to [this video review>](https://www.loom.com/share/04acff853aff489bb0730ffced580aa4?sid=a854d124-3f3a-455c-94f1-f4fffacfd910)

### Excessive use of `$` symbol. 

I find it a little confusing why we have so many $ symbols in the dialogs.. if we have the name of the token as a three symbol ticker why not use that instead? (remember that we also want to be showing the denominations in the Fiat, for which USD is used across where $ sign seems more appropriate in my opinion).

### Summary modal
Feels like would be good to introduce some sort of headers, as the flat list of 8 points is hard to navigate
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdytQQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06300ab63cf0ab12376ee8545b01831736be5b97/Screenshot%202023-11-01%20at%2014.21.35.png)

### Cliff and Vesting on token page
Agree to add it before purchase, but can we make sure that CTA is above the screen fold line pls.

<img width="112" alt="Screenshot 2023-11-01 at 14 58 36" src="https://github.com/Joystream/atlas/assets/93924525/8884cbb7-de68-4283-b973-27db5c752b62">

### Portfolio changes
Like them all, separate section for JOY tokens would be best imho

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @attemka I finished implementing all of the changes into designs for CRT Portfolio and CRT Viewer ✅

🎥 Video update: https://www.loom.com/share/56b8b35886fa4c60a2b1c4c0b16c10d6?sid=38a2430f-e558-497a-9e3f-8cebc736f988

📄 Portfolio changelog: https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/Portfolio?type=design&node-id=1355-78829&mode=design&t=yX2g9J1VSYqH5KWm-4

📄 Channel changelog: https://www.figma.com/file/POw4j95jszfIP5bGfas2IC/Channel?type=design&node-id=2386-171791&mode=design&t=vc3GQIG66x8uBbWN-4

📄 Component token header: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=12314-271113&mode=design&t=TTgpsIahDWO3k7Gt-4

📄 Component token widget: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=12314-275912&mode=design&t=TTgpsIahDWO3k7Gt-4

📄 Component CRT trade dialog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=10959-185618&mode=design&t=TTgpsIahDWO3k7Gt-4

📄 Component CRT Trade terms dialog: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=10967-191141&mode=design&t=TTgpsIahDWO3k7Gt-4

📄 Component CRT trade summary: https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?type=design&node-id=14338-48183&mode=design&t=TTgpsIahDWO3k7Gt-4

**Comment by dmtrjsg** [comment]
# Scope

## Portfolio
<img width="554" alt="Screenshot 2023-11-06 at 15 03 08" src="https://github.com/Joystream/atlas/assets/93924525/dd175076-013c-4370-a74c-74aaa87e9108">

## Channel
<img width="479" alt="Screenshot 2023-11-06 at 15 03 03" src="https://github.com/Joystream/atlas/assets/93924525/76ff9562-9c73-4db1-9f2f-35d09c15952c">

**Comment by WRadoslaw** [comment]
CRT Trade dialog will be handled in #5323

**Comment by WRadoslaw** [comment]
Channel token view will be handled in #5339
