### ISSUE TITLE
[USERSNAP] I try to create membership but say already done but i try 3 days ago server issue not create membership. Please release this i want create membership

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5207]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: I try to create membership but say already done but i try 3 days ago server issue not create membership. Please release this i want create membership
- Houston, we have a problem.: Said already have membership but its wrong
- Your Channel and Account Details: mdratulmolla0177@gmail.com
- Email or Discord handle for feedback: mybinance2022s@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 385x854
**[Open #305 in Usersnap](https://app.usersnap.com/l/feedback/2b7bce15-dbd1-42fe-bea9-f05ffa7d6a60?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
