### ISSUE TITLE
[USERSNAP] Need delete and new one

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5208]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Need delete and new one
- Houston, we have a problem.: I have problem with account past ago i create account with email imamkhoiri43@gmail.com but failed when i create again account already created how to fix because i save the prase but cant
- Your Channel and Account Details: imamkhoiri43@gmail.com
- Email or Discord handle for feedback: imamkhoiri43@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 393x873
**[Open #306 in Usersnap](https://app.usersnap.com/l/feedback/6a0fca9f-0e59-475d-96ea-2e717fb61bfc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
