### ISSUE TITLE
[USERSNAP] Bisa terdaftar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5209]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Bisa terdaftar
- Houston, we have a problem.: Tidak dapat mendaftar
- Your Channel and Account Details: ariefin873@gmail.com
- Email or Discord handle for feedback: ariefin873@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x800
**[Open #307 in Usersnap](https://app.usersnap.com/l/feedback/3a1f02d2-08b3-4611-ac86-829f2cf37217?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
