### ISSUE TITLE
[USERSNAP] i see my dashboard

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5224]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: i see my dashboard
- Houston, we have a problem.: when i want to go to my dashboard, it keeps saying something went wrong
- Your Channel and Account Details: raraiyy@gmail.com
- Email or Discord handle for feedback: raraiyy@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**[Open #313 in Usersnap](https://app.usersnap.com/l/feedback/5cbf16ab-0c23-419b-a52f-7180f6d4cd9a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Instruct creator to follow the steps on the document for their issue. 
https://joystream.notion.site/Troubleshooting-Sign-Up-Sign-in-8b127a6da0a44650866e6828715b0009
