### ISSUE TITLE
[USERSNAP] Please check my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5229]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Please check my account
- Houston, we have a problem.: I cant regist
- Your Channel and Account Details: @sindusj
- Email or Discord handle for feedback: Sindukurniawan21@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 446x965
**[Open #318 in Usersnap](https://app.usersnap.com/l/feedback/cc8bbde0-eee0-4ae0-b56a-137d2f564c6d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
