### ISSUE TITLE
[USERSNAP] pense que tan pronto lo subi a yourtube se veria aqui y aun no se refleja desde anoche

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5231]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: pense que tan pronto lo subi a yourtube se veria aqui y aun no se refleja desde anoche
- Houston, we have a problem.: video subido en youtube
- Your Channel and Account Details: @cheotrabajandoenlaruta https://www.youtube.com/channel/UCnkMPgTUszObDfVS6gbiQJA
- Email or Discord handle for feedback: jdpmatico@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1360x768
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/20e1036a-07b5-450d-a4df-c9dc72b6bf4b_screen_recording_a98b8114-c7e1-48f1-a7ea-1f0035992ae0.webm?etag=0a3b234fce6f2e94b2806e38e5b49ad0)**
**[Open #320 in Usersnap](https://app.usersnap.com/l/feedback/bdbf2e0a-61fd-47de-9f41-fb3297a28541?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Advise the creator that the issue is already addressed and the team is already working on it.
