### ISSUE TITLE
[USERSNAP] it should be signed in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5232]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: it should be signed in
- Houston, we have a problem.: I can&#39;t sign in for several days
- Your Channel and Account Details: divebomb94@gmail.com
- Email or Discord handle for feedback: divebomb94@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**[Open #321 in Usersnap](https://app.usersnap.com/l/feedback/e926fd7a-7803-4426-a97a-5529b8de6fe1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
