### ISSUE TITLE
[USERSNAP] Please help me

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5237]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Please help me
- Houston, we have a problem.: Account not connected
- Your Channel and Account Details: Fmdesitone
- Email or Discord handle for feedback: Fmdesitone@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x817
**[Open #323 in Usersnap](https://app.usersnap.com/l/feedback/dad7f154-2076-45d4-a6c3-22a08cc0e948?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
