### ISSUE TITLE
[USERSNAP] Tolong diperbaiki dan ditingkatkan

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5240]
**Taken at**: https://gleev.xyz/payment
**Fields**:
- Expected Result: Tolong diperbaiki dan ditingkatkan
- Houston, we have a problem.: Tolong saya tidak bisa maduk ke akun saya
- Your Channel and Account Details: USERNAME SAYA: anisfuad1
Email: anisfuad1mmm@gmail.com
- Email or Discord handle for feedback: anisfuad1mmm@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 412x892
**[Open #325 in Usersnap](https://app.usersnap.com/l/feedback/56ce0529-438c-4e54-8200-8a01ab529066?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
