### ISSUE TITLE
[USERSNAP] When i try to create membership says Already have but i Don't created.  3 days ago i try but says error.  Now want to create membership but can't. Please sir release sir. Help me to create membership.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5241]
**Taken at**: https://gleev.xyz/ypp?referrerId=33834
**Fields**:
- Expected Result: When i try to create membership says Already have but i Don&#39;t created.  3 days ago i try but says error.  Now want to create membership but can&#39;t. Please sir release sir. Help me to create membership.
- Houston, we have a problem.: Membership Problem
- Your Channel and Account Details: mdratulmolla0177@gmail.com
- Email or Discord handle for feedback: bitget623@gmail.com

**Browser**: Chrome 118 (Android 11)
**Screen size**: 395x877
**[Open #326 in Usersnap](https://app.usersnap.com/l/feedback/d0c7e26b-0732-4709-ab55-4ed9b83f6033?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
