### ISSUE TITLE
[USERSNAP] I hope my new video can sync on the gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5244]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: I hope my new video can sync on the gleev
- Houston, we have a problem.: My new video not synced on Gleev
- Your Channel and Account Details: Lapakcuan, jonihermawan778@gmail.com, silver tier
- Email or Discord handle for feedback: jonihermawan778@gmail.com //@0xsht

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0bb540e1-ddc2-4fff-b788-05b4df190716-annotated_7efba997-1e1e-42b1-88ff-a560177d4b3d.png?etag=9f7b387eac9125f008d54f5cde6a2a5a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0bb540e1-ddc2-4fff-b788-05b4df190716-annotated_7efba997-1e1e-42b1-88ff-a560177d4b3d.png?etag=9f7b387eac9125f008d54f5cde6a2a5a)*

**Browser**: Chrome 95 (Android 12)
**Screen size**: 360x820
**Browser size**: 360x736
**[Open #328 in Usersnap](https://app.usersnap.com/l/feedback/3f925c1f-5148-4395-9e59-4871df382df6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Advise the creator that the issue is already addressed and the team is already working on it.
