### ISSUE TITLE
[USERSNAP] hig demand sign up

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5245]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: hig demand sign up
- Houston, we have a problem.: can syncronize youtube chanel
- Your Channel and Account Details: frr.6661@gmail.com
- Email or Discord handle for feedback: frr.6661@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x640
**[Open #329 in Usersnap](https://app.usersnap.com/l/feedback/7c4ce33e-f9e4-45ba-8346-5746fdbc52a4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Advise the creator to try after the reset of the daily limit.
