### ISSUE TITLE
[USERSNAP] Error cannot register

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5249]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Error cannot register
- Houston, we have a problem.: can&#39;t signup
- Your Channel and Account Details: https://www.youtube.com/@ntuyyyt8427
koflock43@gmail.com
- Email or Discord handle for feedback: koflock43@gmail.com

**Browser**: Chrome 116 (Linux)
**Screen size**: 393x873
**[Open #330 in Usersnap](https://app.usersnap.com/l/feedback/691c305a-0f60-424e-9c6f-506e1c0e57b6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
