### ISSUE TITLE
[USERSNAP] I had a problem not being able to connect to YouTube

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5252]
**Taken at**: https://gleev.xyz/ypp?referrerId=31499
**Fields**:
- Expected Result: I had a problem not being able to connect to YouTube
- Houston, we have a problem.: Can&#39;t connect to YouTube 
- Your Channel and Account Details: kapal020500@gmail.com
- Email or Discord handle for feedback: kapal020500@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 393x873
**[Open #331 in Usersnap](https://app.usersnap.com/l/feedback/bd31e646-a0f8-48de-aece-51836b8cd52f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
