### ISSUE TITLE
[USERSNAP] Login lancar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5253]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Login lancar
- Houston, we have a problem.: Login gak bisa padahal email Ama password bener
- Your Channel and Account Details: kaptensoleengs@gmail.com
- Email or Discord handle for feedback: kaptensoleengs@gmail.com

**Browser**: Chrome 111 (Android 10)
**Screen size**: 360x806
**[Open #332 in Usersnap](https://app.usersnap.com/l/feedback/e16d41e5-95c7-4317-8084-d1d2c8083a3a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator of successful registration, but unfortunately, the channel didn't meet the verification criteria.
