### ISSUE TITLE
[USERSNAP] Nothing work connect to YouTube 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5257]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Nothing work connect to YouTube 
- Houston, we have a problem.: Cant signup ypp
- Your Channel and Account Details: aayu42277@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x851
**[Open #335 in Usersnap](https://app.usersnap.com/l/feedback/c7f975d7-49d7-49a8-a347-66ea02936fe5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
