### ISSUE TITLE
[FEATURE REQUEST] I am not creating  account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5258]
**Taken at**: https://gleev.xyz/ypp?referrerId=31837
**Fields**:
- Which feature are you missing?: I am not creating  account 
- What problem would that solve for you?: something with wrong problem show 
- Share your Email or Discord so we can get in touch: tgridoy5@gmail.com
- Your Gleev channel ID or Title: https://youtube.com/@tssgaming5299?si=agxs-tZSeszBAJCm

**Browser**: Chrome 118 (Android 10)
**Screen size**: 501x1114
**[Open #87 in Usersnap](https://app.usersnap.com/l/feedback/f871404b-83a6-4408-90f4-3bbafb4cf6ad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informing the creator that the channel https://www.youtube.com/@tssgaming5299/videos has been previously registered with a different email address. Unfortunately, it did not meet the criteria for verification.
