### ISSUE TITLE
[USERSNAP] Say already have but i Don't have membership.  I try some days ago but Server issue says error.  Please sir help me to create membership 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5259]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Say already have but i Don&#39;t have membership.  I try some days ago but Server issue says error.  Please sir help me to create membership 
- Houston, we have a problem.: Membership problem 
- Your Channel and Account Details: Football premik Ratul Jr
mdratulmolla0177@gmail.com

- Email or Discord handle for feedback: bitget623@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 385x854
**[Open #336 in Usersnap](https://app.usersnap.com/l/feedback/f9f80b97-4b28-488e-8dc6-ec267b9630a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
