### ISSUE TITLE
[USERSNAP] Tidak berfungsi

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5261]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Tidak berfungsi
- Houston, we have a problem.: Sulit masuk
- Your Channel and Account Details: Dolifdolchanel@gmail.com
- Email or Discord handle for feedback: Dolifdolchanel@gmail.com

**Browser**: Chrome 111 (Android 10)
**Screen size**: 427x949
**[Open #337 in Usersnap](https://app.usersnap.com/l/feedback/f670f91d-98fd-4349-a4b1-871a393d8f1c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
