### ISSUE TITLE
Feedback on Notifications Email

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5263]
## Scope
- [ ] Email template looks different compared to designs

[Reference to Designs>](https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=2793%3A31264&mode=design&t=LsMcEZaWL9IsrClp-1)

<img width="539" alt="Screenshot 2023-11-08 at 14 16 17" src="https://github.com/Joystream/atlas/assets/93924525/d28c351e-cd3a-481f-a2b2-2d4b20ce9632">

- [ ] Also "unsubscribe"  should get user to sign up modal and get to notifications for channel OR member depending on the email

**Comment by KubaMikolajczyk** [comment]
The email template was updated some time ago and the current implementation seems to be using the old designs
`🟠 Hovewer I need to add on a sidenote that the current implementation is using serif font to display while we should be using IBM Plex Sans to display all fonts in the msg or any other sans-serif font as a fallback.`

Current designs can be accessed here: https://www.figma.com/file/Goequb9eZDL6WxK7T74oxS/Notifications?type=design&node-id=3334-3027&mode=design&t=hiE7Whu01qzIdeID-4
<img width="582" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/316cd0a6-087e-4b0b-8ad6-1603aa7c3de4">
