### ISSUE TITLE
Idea: auto-save generated seeds

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#5268]
# Problem
Users get a seed when signing up on Gleev/Atlas and are told to write this down and store it safely but few users do.

# Solution
When the seed is generated automatically save it as a text file/JSON file to the user's device. This behavior used to be default in polkadot-js in the days before we had Pioneer v2 and meant that the chance of losing the seed was minimal.

Ideally the filename should be something distinct and easy for users to search for in their download folder (such as starting with `gleev`

**Comment by dmtrjsg** [comment]
Let's have a checkbox with "save as text file" by default mark as true. When user goes to next step the seed is saved to their device. 

Filename mnemonic.txt can remain.

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg @mochet The dialogs and flows featuring wallet seed were updated to include the new approach to downloading the wallet seed file  - everything is described in the visual changelog ✅

📄 Sign up changelog: https://www.figma.com/file/ymHYOFItrmFaLeBC5Z4tpQ/Sign-up-%2F-Log-in?type=design&node-id=3467-20505&mode=design&t=dupytRUtO5tYjFrT-4
