### ISSUE TITLE
[USERSNAP] Can you delete my referral

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5273]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Can you delete my referral
- Houston, we have a problem.: I can&#39;t Join youtube partner program
- Your Channel and Account Details: Nayaka zea
- Email or Discord handle for feedback: zeanayaka@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x780
**[Open #340 in Usersnap](https://app.usersnap.com/l/feedback/3e35cc48-e2d9-4780-8f1c-680169fb6673?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item:  Informed the creator successfully registered but  it didn't meet the requirements to be verified.
