### ISSUE TITLE
[USERSNAP] Can't Log In or Sign Up again

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5274]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Can&#39;t Log In or Sign Up again
- Houston, we have a problem.: Sign up but the website refresh 
- Your Channel and Account Details: sambidofficial@gmail.com
- Email or Discord handle for feedback: sambidofficial@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 392x871
**[Open #341 in Usersnap](https://app.usersnap.com/l/feedback/c61d6791-4b26-41b1-97eb-4115f2539e7f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
