### ISSUE TITLE
[USERSNAP] Im trying to log in my account but the system says cant verify my membership, And then i just try to register again with my same email, but the system tell me my account was already registered.. im so confused right now

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5275]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Im trying to log in my account but the system says cant verify my membership, And then i just try to register again with my same email, but the system tell me my account was already registered.. im so confused right now
- Houston, we have a problem.: I cant login
- Your Channel and Account Details: blitzbrigade925@gmail.com
- Email or Discord handle for feedback: blitzbrigade925@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5946567a-ba0f-458e-911b-cd3307f701e0-annotated_8962ebe1-057f-4610-a386-13ee8b00371e.png?etag=4f214198cbc32f4c05139ed577fd53c7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5946567a-ba0f-458e-911b-cd3307f701e0-annotated_8962ebe1-057f-4610-a386-13ee8b00371e.png?etag=4f214198cbc32f4c05139ed577fd53c7)*

**Browser**: Safari 17 (iOS)
**Screen size**: 375x812
**Browser size**: 375x634
**[Open #342 in Usersnap](https://app.usersnap.com/l/feedback/f2839a0b-1b71-4c02-8109-f7391d8ab1ec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
