### ISSUE TITLE
Post release follow up fixes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5283]
There's a few things we need to follow up on post Gleev release
- YPP landing page carousel still not showing
- Referrals page reward values need to be updated (x2)
- Referrals page - tiers cards have cutoff headers on mobile

**Comment by KubaMikolajczyk** [comment]
@dmtrjsg as requested the re-review of the mobile RWD for referrals page below:

1. The margin here should be 32px from XXS to SM, it starts getting bigger from SM
<img width="296" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/bcba1ca4-c23a-4237-b3e7-119ba3414797">
2. It looks like on minimum width 320px this illustration is not centered
<img width="302" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/b402d651-1373-4363-8176-7b5117f4bff4">
3. On minimum width 320px this text inside of the step should be justified to the left side not to the center
<img width="304" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/883d311e-543a-4bf6-8513-992af3d0a42b">
4. The gap between top referrers title and the first top referrer on XXS should be 48px not 72px
<img width="293" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/af878c33-91d0-4f35-8582-be57bdaf3f63">
5. Referrals nav item is not present in bottom nav menu which is displayed on mobile
<img width="422" alt="image" src="https://github.com/Joystream/atlas/assets/31144205/30a4fb43-0afe-4ad3-b5b2-1ffb0b7ab045">

**Comment by dmtrjsg** [comment]
🚫 Referrals page video playback only works for me (iPhone13) once clicked on the step. When clicked it opens it full 
screen.

✅  Desired outcome - should play without fullscreen mode on mobile devices.

**Comment by KubaMikolajczyk** [comment]
I succeded in replicating it really opens a player when using the steps on mobile
