### ISSUE TITLE
Update images with referral rewards

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5296]
1. Homepage banner
2. Bottom of referral page components

New values:
Bronze - 1$
Silver - 25$
Gold - 50$
Diamond - 100$

**Comment by KubaMikolajczyk** [comment]
The channel rows with corrected values are here: https://www.figma.com/file/AHeOPBgaJxmZb0zamEHhq8/Referrals?type=design&node-id=1869-13060&mode=design&t=pSVJPjpnzUU2FQDS-4

`Note: I realized two last rows were named wrong so I corrected the mistake - please consider that when switching to new assets to retain thew looping effect`
