### ISSUE TITLE
[FEATURE REQUEST] No login from tomorrow 10 November night

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5306]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: No login from tomorrow 10 November night
- What problem would that solve for you?: I invited friend to join for me on 9th November but still pending not verified yet.  And I couldn&#39;t login to the Gleev site, but I&#39;m trying tomorrow night, it&#39;s not loading, so I can&#39;t login.. It would be great if you could help me.  I used to make content with the site
- Share your Email or Discord so we can get in touch: hafezawlia59@gmail.com
- Your Gleev channel ID or Title: H M Awlia Islam 

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x851
**[Open #99 in Usersnap](https://app.usersnap.com/l/feedback/e4eb7f59-dd43-4005-81d6-52f21d3a6974?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
