### ISSUE TITLE
[FEATURE REQUEST] Membership is not creating 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5330]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Which feature are you missing?: Membership is not creating 
- What problem would that solve for you?: It&#39;s not creating 
- Share your Email or Discord so we can get in touch: tajibsujon1988@gmail 
- Your Gleev channel ID or Title: https://youtube.com/@ZEP2109?si=dUlWglzmWvbm0vp0

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x873
**[Open #105 in Usersnap](https://app.usersnap.com/l/feedback/433c80c1-20a0-44db-8d9d-7a0955f1a8b4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
