### ISSUE TITLE
[USERSNAP] This Youtube channel is already signed up and connected with joystrem membership but not login Please solve my problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5331]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: This Youtube channel is already signed up and connected with joystrem membership but not login
Please solve my problem 
- Houston, we have a problem.: Something went wrong
- Your Channel and Account Details: m.ahashanul94@gmail.com
- Email or Discord handle for feedback: m.ahashanul94@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 513x1111
**[Open #367 in Usersnap](https://app.usersnap.com/l/feedback/b64d6ef4-231b-43e1-97de-4d3cf43f255c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
