### ISSUE TITLE
[USERSNAP] Errors always occur when uploading or changing profile photos. tired of this platform, even though I just tried it

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5332]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Errors always occur when uploading or changing profile photos. tired of this platform, even though I just tried it
- Houston, we have a problem.: lemot
- Your Channel and Account Details: pandu aselsha 
- Email or Discord handle for feedback: panduadeselsha@gmail.com

**Browser**: Chrome 103 (ChromeOS)
**Screen size**: 1366x768
**[Open #368 in Usersnap](https://app.usersnap.com/l/feedback/21d58a2b-cb61-4f19-be03-3b744c47d5e4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
Tried changing avatar for both membership and channel on prod, zero problems.

**Comment by dmtrjsg** [comment]
Should be sorted out by changes in this issue:
- https://github.com/Joystream/atlas/issues/5262
