### ISSUE TITLE
[USERSNAP] hi, it isn't fixed. It'll be same, when i tried.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5333]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: hi, it isn&#39;t fixed. It&#39;ll be same, when i tried.
- Houston, we have a problem.: i can&#39;t sign up
- Your Channel and Account Details: channel : isnazz
email : nnaazz100402@gmail.com

- Email or Discord handle for feedback: nnaazz100402@gmail.com

**Browser**: Firefox 119 (Windows 10)
**Screen size**: 1138x640
**[Open #369 in Usersnap](https://app.usersnap.com/l/feedback/740e6df0-6cf0-44a9-aeda-60053954f6cb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
