### ISSUE TITLE
[USERSNAP] I have registered with my YouTube account, but for the past 5 days I have not been able to log in using the email address associated with my YouTube, please help so I can log in to my account.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5343]
**Taken at**: https://gleev.xyz/legal/tos
**Fields**:
- Expected Result: I have registered with my YouTube account, but for the past 5 days I have not been able to log in using the email address associated with my YouTube, please help so I can log in to my account.
- Houston, we have a problem.: can&#39;t log in
- Your Channel and Account Details: @icomica7686
Email: icomica2@gmail.com
- Email or Discord handle for feedback: icomica2@gmail.com

**Browser**: Chrome 108 (Android 11)
**Screen size**: 424x918
**[Open #371 in Usersnap](https://app.usersnap.com/l/feedback/0ca2c81b-e6b4-4d56-951f-a622b7d64f1c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
