### ISSUE TITLE
[USERSNAP] My id is not login but my youtube channel is connected  please help me..

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5345]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: My id is not login but my youtube channel is connected  please help me..
- Houston, we have a problem.: Something went wrong
- Your Channel and Account Details: m.ahashanul94@gmail.com
- Email or Discord handle for feedback: m.ahashanul94@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8091fe35-add9-471c-bcb5-779f7bc1a19f-annotated_6626f782-865f-4714-bb83-7adf4cdf0f43.png?etag=60e01bda8a08e82983f3edd24250aebf)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8091fe35-add9-471c-bcb5-779f7bc1a19f-annotated_6626f782-865f-4714-bb83-7adf4cdf0f43.png?etag=60e01bda8a08e82983f3edd24250aebf)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 513x1111
**Browser size**: 467x910
**[Open #372 in Usersnap](https://app.usersnap.com/l/feedback/bc1d25be-bb9e-46bb-92da-aaba127dd848?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and sent instruction to recover seed phrase if misplaced.
