### ISSUE TITLE
[USERSNAP] I cannot log in after I created an account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5353]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: I cannot log in after I created an account 
- Houston, we have a problem.: I can&#39;t log in 
- Your Channel and Account Details: https://www.youtube.com/@Earnvip

abdulrhmanmakrm20@gmail.com
- Email or Discord handle for feedback: abdulrhmanmakrm20@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ceec54ce-a554-4c43-900e-e9ac00a48c10-annotated_5154cef3-9d7c-4d8d-9d03-b10ecbef42ed.png?etag=f32882c1945c8cb697cf3870ea2fc23c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ceec54ce-a554-4c43-900e-e9ac00a48c10-annotated_5154cef3-9d7c-4d8d-9d03-b10ecbef42ed.png?etag=f32882c1945c8cb697cf3870ea2fc23c)*

**Browser**: Chrome 117 (Android 10)
**Screen size**: 393x873
**Browser size**: 393x736
**[Open #376 in Usersnap](https://app.usersnap.com/l/feedback/48950d17-7f6b-4860-a8aa-98ef301bf301?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
