### ISSUE TITLE
[USERSNAP] How toh slove my problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5358]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: How toh slove my problem
- Houston, we have a problem.: I can&#39;t sign in
- Your Channel and Account Details: YT RASHIDUL
- Email or Discord handle for feedback: bijoyislam651@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 513x1140
**[Open #381 in Usersnap](https://app.usersnap.com/l/feedback/83430af0-c665-476e-982b-4de3fd89f10c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
