### ISSUE TITLE
QA for CRTs

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5360]
## Context

Testing CRTs functionality as part of v1 release, aligned with runtime Nara release

## Where to test

Atlas branch: `https://atlas-git-crt-joystream.vercel.app/studio/crt`
Env to choose from admin panel: `Gleev-next`
Node to choose from admin panel:  `Atlas-next`

⚠️ To be able to create account on the password step WAIT FOR 30-60 seconds, and then hit "sign up"

## Scope 

Test the implementation of the following user stories for CRTs

## Creator

Placeholder screen:
- [x] #3396

Create CRT flow:
- [x] #3401
- [x] #3385
- [x] #3394
- [x] #3402
- [x] #3386
- [x] #3387

Dashboard:
- [x] #3388
- [x] #3389
- [x] #3390

Token Page:
- [x] #3391
- [x] #3403
- [x] #3392
- [x] #3393

### Token Market
- [x] #3797
- [x] #3798
- [x] #3799
- [x] #3802
- [x] #3804
- [x] #3805

## Viewer
- [x] #3825
- [x] #3826
- [x] #3827
- [x] #3829
- [x] #3830
- [x] #3832
- [x] #3833
- [x] #3834
- [x] #3836
- [x] #3840

## Holder

- [x] #3841
- [x] #3835
- [x] #3842
- [x] #3856
- [x] #3859

## Revenue Share
- [x] #3844
- [x] #3845
- [x] #3846
- [x] #3847
- [x] #3848
- [x] #3849
- [x] #3850
- [x] #3851
- [x] #3852
- [x] #3862
- [x] #3863
- [x] #3864

**Comment by chrlschwb** [comment]
QA result
https://github.com/Joystream/atlas/issues/5483
