### ISSUE TITLE
Improve work sheet icon for hidden state

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#537]
Using the same `_` icon for controlling visibility of the work sheet both when its hidden and expanded is confusing. It would be better to have more explicit icons for up/down or hide/show.

![Screenshot 2021-04-30 at 23 25 01](https://user-images.githubusercontent.com/437292/116756182-f8c5b200-aa0b-11eb-92f5-2649e4d90395.png)

**Comment by KubaMikolajczyk** [comment]
Two icons were designed and can be seen in this flow : [Minimizing upload action sheet & edit another video](https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=7389%3A0).
