### ISSUE TITLE
[FEATURE REQUEST] My account is not logging in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5371]
**Taken at**: https://gleev.xyz/ypp?referrerId=39525
**Fields**:
- Which feature are you missing?: My account is not logging in
- What problem would that solve for you?: My account is not logging in
- Share your Email or Discord so we can get in touch: mdsiamhossen031@gmail.com
- Your Gleev channel ID or Title: GAMING WITH SIAM

**Browser**: Chrome 117 (Android 10)
**Screen size**: 360x800
**[Open #108 in Usersnap](https://app.usersnap.com/l/feedback/e8c3c6eb-e3a9-4aef-aa58-c64de57f3270?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
