### ISSUE TITLE
[FEATURE REQUEST] Account loging Problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5373]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: Account loging Problem
- What problem would that solve for you?: Sir, I have opened an account at abukawsar2714@gmail.com. But now it is not Login and Forgot is not happening. But whey ? 
- Share your Email or Discord so we can get in touch: abukawsar2714@gmail.com
- Your Gleev channel ID or Title: শান্তিসংঘ ইসলাম

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**[Open #110 in Usersnap](https://app.usersnap.com/l/feedback/4685b082-401f-4d14-a38a-540918e8a01f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
