### ISSUE TITLE
Surface Studio better

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#538]
Right now the only way for a new user discover that they can indeed also make a channel and publish videos is quite low. They would have to, for some unrelated reason, open the navigation drawer - something one actually does not have an independent reason to ever do, then observe the studio button at the very bottom, and then - without much information about what this is, click it.

I think we really want to make it easier for people to organically learn this, so lifting out and explicit call to action button visible in the top level of the UI seems advisable.

**Comment by KubaMikolajczyk** [comment]
To encourage viewers to explore studio side of the atlas we proposed two solutions: "start publishing" button in top navigation and a collapsable banner informing about the other part of experience.

Surface studio better Figma page: [Figma link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=9818%3A265474)
Banner component variants: [Component link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8480%3A23392)
