### ISSUE TITLE
[USERSNAP] Rjcripto não estou conseguindo acessar a minha conta, pois fala que não reconhece o cadastro, e eu já tenho 6 indicados nela, já tentei recuperar com a chave semente e não consigo. Podem me ajudar 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5383]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Expected Result: Rjcripto não estou conseguindo acessar a minha conta, pois fala que não reconhece o cadastro, e eu já tenho 6 indicados nela, já tentei recuperar com a chave semente e não consigo. Podem me ajudar 
- Houston, we have a problem.: Não consigo acessar a minha conta
- Your Channel and Account Details: falacompapaioficial@gmail.com 
evertonspie@gmail.com 
- Email or Discord handle for feedback: Rjcripto

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/de4c4d48-4074-46cd-a043-92bde0f48183-annotated_ed60565b-4390-4b65-8f0a-369cbb9f637a.png?etag=a54f46eab687cdbfc5f977df72b1a447)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/de4c4d48-4074-46cd-a043-92bde0f48183-annotated_ed60565b-4390-4b65-8f0a-369cbb9f637a.png?etag=a54f46eab687cdbfc5f977df72b1a447)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 412x869
**Browser size**: 428x750
**[Open #391 in Usersnap](https://app.usersnap.com/l/feedback/2f147922-230e-4d74-b4b4-eba7a191290c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
issue resolved in creator support channel: https://discord.com/channels/811216481340751934/1053294778529353788/1174725131218722848
