### ISSUE TITLE
[USERSNAP] NO ME DEJA ELEGIR UN NOMBRE?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5384]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: NO ME DEJA ELEGIR UN NOMBRE?
- Houston, we have a problem.: QUE SIGNIFICA ESTO: REFERENTE- INTRODUZCA EL TITULO DEL CANAL GLEEV QUE LE RECOMENDO EL PROGRAMA??
- Your Channel and Account Details: SE QUEDA EN ESPERA Y NO AVANZA?
- Email or Discord handle for feedback: criaderoeskairim@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #392 in Usersnap](https://app.usersnap.com/l/feedback/973545bb-d47f-4445-8c52-f59624398c01?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
https://www.youtube.com/channel/UCZrUUDHSvqZVX4Zc85w1a5w - channel opted out platform  - This account has been terminated because we received multiple third-party claims of copyright infringement regarding material the user posted.
