### ISSUE TITLE
[USERSNAP] i wanna fix this issue 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5389]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: i wanna fix this issue 
- Houston, we have a problem.: i can not log in my account
- Your Channel and Account Details: i do not know my channel ID, because i did not log into my account.

My mail adress is ozkurt.tuana61@gmail.com

Please contact me with my mail adress
- Email or Discord handle for feedback: ozkurt.tuana61@gmail.com

**Browser**: Chrome 119 (macOS Catalina)
**Screen size**: 1680x1050
**[Open #395 in Usersnap](https://app.usersnap.com/l/feedback/de840681-ad7c-4b7c-8bf9-a56207461bd1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours
