### ISSUE TITLE
[USERSNAP] No me ha dejado terminar de hacer la sincronización 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5393]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: No me ha dejado terminar de hacer la sincronización 
- Houston, we have a problem.: Buenas, pues no me deja sincroniza la cuenta de YouTube 
- Your Channel and Account Details: El coyote tv 
- Email or Discord handle for feedback: Luisjosebreezy01@gmail.com

**Browser**: ChromeiOS 119 (iOS)
**Screen size**: 414x896
**[Open #396 in Usersnap](https://app.usersnap.com/l/feedback/8652ff46-71de-4ad1-9c9a-1f6eca0aa296?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
