### ISSUE TITLE
[FEATURE REQUEST] i am not Join 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5394]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Which feature are you missing?: i am not Join 
- What problem would that solve for you?: who to problem my YouTube account 
- Share your Email or Discord so we can get in touch: ibrahim2007ff@gmail.com
- Your Gleev channel ID or Title: https://youtube.com/@ffibrahik4416?si=KFZbPsPNkL6JE--X

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/77f18745-a673-4132-a693-0facfdc0e582-annotated_baf67711-1eac-4d9a-afe7-f6cace781ce6.png?etag=19c66bdc719144c8ad7c1ea1907e43fc)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/77f18745-a673-4132-a693-0facfdc0e582-annotated_baf67711-1eac-4d9a-afe7-f6cace781ce6.png?etag=19c66bdc719144c8ad7c1ea1907e43fc)*

**Browser**: Chrome 117 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x711
**[Open #112 in Usersnap](https://app.usersnap.com/l/feedback/901eee12-7b2a-44c9-9089-e4140364b654?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
