### ISSUE TITLE
[FEATURE REQUEST] Profil onayı

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5398]
**Taken at**: https://gleev.xyz/member/mixtubex?tab=NFTs
**Fields**:
- Hangi özelliği kaçırıyorsun?: Profil onayı
- Bu sizin için hangi problemi çözer?: Neden kanalımı hala onaylamadanız? 
- Share your Email or Discord so we can get in touch: Reqs.merkezi@gmail.com
- Your Gleev channel ID or Title: j4UVwDmT7jWUtRzzysytPh5baZ9PDju8H71ycQVvKTCTXkFgZ

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e97a273d-ba8c-4441-a67b-f5234b340a0e-annotated_374ddea2-4f36-4d6b-a85d-89734c0d4785.png?etag=9b81fad327027d6407292ddbc00ec62a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e97a273d-ba8c-4441-a67b-f5234b340a0e-annotated_374ddea2-4f36-4d6b-a85d-89734c0d4785.png?etag=9b81fad327027d6407292ddbc00ec62a)*

**Browser**: ChromeiOS 119 (iOS)
**Screen size**: 414x896
**Browser size**: 414x716
**[Open #113 in Usersnap](https://app.usersnap.com/l/feedback/54d46980-38c0-47c4-a4a1-fbcabac4a790?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate.
