### ISSUE TITLE
[USERSNAP] quiero que me den una respuesta

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5399]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Expected Result: quiero que me den una respuesta
- Houston, we have a problem.: No me han verificado mi cuenta, mi cuenta tiene 20 seguidores y no aparecen y tampoco aparecen mis videos que eh subido a youtube
- Your Channel and Account Details: ismaryquine@gmail.com
- Email or Discord handle for feedback: ismaryquine@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**[Open #399 in Usersnap](https://app.usersnap.com/l/feedback/ee34b53b-e211-40a9-ab01-e8cf0fc505c0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
