### ISSUE TITLE
Carousel alternative on mobile

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#54]
### Carousel alternative on mobile

The current design uses a number of carousels to present content on the landing page. It makes sense for desktop but I don't think that's ideal for mobile.

<img width="476" alt="Screenshot 2020-09-07 at 11 49 33 AM" src="https://user-images.githubusercontent.com/12646744/92374669-56656100-f100-11ea-9242-c97433e46d22.png">

In the mobile view, most probably only one video will fit the screen at the time. This means that to browse a carousel containing 20 elements, user will need to tap the screen 19 times, to browse items one by one. This probably discourages exploration and makes the UX harder.

For this reason, I think we should find some alternative better fitting mobile view

_Originally posted by @kdembler in https://github.com/Joystream/joystream/issues/1245#issuecomment-688211916_

**Comment by bedeho** [comment]
- Here I think we really can't aspire as many as 20 in a practical carousel, that is to much from a UX perspective either way.
- I do wonder if simply allowing carousels to have smaller previews, so you can see 2 horizontally, could be reasonable compromise if each scroll gesture or click rotates out both. Lets see what the designers say.

**Comment by KubaMikolajczyk** [comment]
There was a redesign of the carousel component so it looks different now as a whole.
It's mobile version can be found for example here: https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=11810%3A414610
In mobile version of this component the video tiles take fixed amount of space and part of it is always cut by the right edge of the screen. No controls or sections are included.
