### ISSUE TITLE
[USERSNAP] Benim kanalımı neden onaylamıyorsunuz? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5403]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Benim kanalımı neden onaylamıyorsunuz? 
- Houston, we have a problem.: Kanal doğrulanması
- Your Channel and Account Details: Reqs.merkezi@gmail.com
- Email or Discord handle for feedback: Reqs.merkezi@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/339fb77e-de15-4089-883e-edfeae9cc218-annotated_dca9e3ad-efc2-4752-ba83-a1f65aa5d7a0.png?etag=3697f2d0d612fc751ffefd574537539a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/339fb77e-de15-4089-883e-edfeae9cc218-annotated_dca9e3ad-efc2-4752-ba83-a1f65aa5d7a0.png?etag=3697f2d0d612fc751ffefd574537539a)*

**Browser**: ChromeiOS 119 (iOS)
**Screen size**: 414x896
**Browser size**: 414x826
**[Open #403 in Usersnap](https://app.usersnap.com/l/feedback/2c5545d1-ae93-40f0-b61b-57571ec00930?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Reviewed the channel and it's now verified at the bronze tier. Notified the creator about the completion.
