### ISSUE TITLE
[USERSNAP] I logged in to YouTube directly with Google from the YouTube partnership page. After automatically logging out of my membership, I cannot log in again and it gives warnings like your account is connected. I opened a membership with the same e...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5404]
**Taken at**: https://gleev.xyz/channel/45476?tab=Videos
**Fields**:
- Expected Result: I logged in to YouTube directly with Google from the YouTube partnership page. After automatically logging out of my membership, I cannot log in again and it gives warnings like your account is connected. I opened a membership with the same email, but I cannot access the membership with my YouTube account.
- Houston, we have a problem.: I connected my YouTube account without being a member and I cannot log in.
- Your Channel and Account Details: Damon Black, osmanarpaci16@gmail.com 
- Email or Discord handle for feedback: osmanarpaci16@gmail.com 

**Browser**: Opera 102 (Windows 10)
**Screen size**: 1366x768
**[Open #404 in Usersnap](https://app.usersnap.com/l/feedback/2575fbf4-ad10-432b-92f4-2f300de60141?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
