### ISSUE TITLE
[FEATURE REQUEST] I cant log in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5405]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: I cant log in
- What problem would that solve for you?: I cant log in sign in why ? please work on it..
- Share your Email or Discord so we can get in touch: queenolive14@yahoo.com
- Your Gleev channel ID or Title: none , was never signed in

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1280x720
**[Open #114 in Usersnap](https://app.usersnap.com/l/feedback/c23dc316-3540-481d-a92b-9e1c83c9b23c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator to try again signing-up as there is no found in our records with their given information.
