### ISSUE TITLE
[USERSNAP] Please fix my issue . i 100% confirm not craete account  yet . i want create account freshly without any bug . i will show my problem photo . please check that photo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5406]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Please fix my issue . i 100% confirm not craete account  yet . i want create account freshly without any bug . i will show my problem photo . please check that photo
- Houston, we have a problem.: When i try create account then showing i allready create account and connected with GLEEV / TALISMAN . But never i can not create account . when i try login then show this email not have any account . 
- Your Channel and Account Details: My email : pronaba52@gmail.com ,
Username : @DailyEmotion
- Email or Discord handle for feedback: priyontibiswas86@gmail.com

**Browser**: Edge (Chromium) 119 (Windows 10)
**Screen size**: 1536x864
**[Open #405 in Usersnap](https://app.usersnap.com/l/feedback/c6599ce2-3015-49b5-83fc-a0c295aa42a0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
