### ISSUE TITLE
[USERSNAP] I didn’t finished my form yet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5410]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: I didn’t finished my form yet
- Houston, we have a problem.: It is showing something went wrong.. By mistake in process i reload this page.After that the problem started
- Your Channel and Account Details: sarkerfardin123@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 393x873
**[Open #407 in Usersnap](https://app.usersnap.com/l/feedback/412c0907-a368-4ad2-85e0-fd97b5538f34?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
