### ISSUE TITLE
[USERSNAP] Hhhhh

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5463]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Hhhhh
- Houston, we have a problem.: Hhhhh
- Your Channel and Account Details: sunnijamatmuktirpoth@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/18773da5-59b7-4401-bade-957d7ab482d2-annotated_229fc611-9bdc-4838-bcda-523ec976a6f7.png?etag=a7c69d7ab0b3b711948a1c15a88d5a2e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/18773da5-59b7-4401-bade-957d7ab482d2-annotated_229fc611-9bdc-4838-bcda-523ec976a6f7.png?etag=a7c69d7ab0b3b711948a1c15a88d5a2e)*

**Browser**: Chrome 109 (Android 9)
**Screen size**: 360x780
**Browser size**: 360x644
**[Open #435 in Usersnap](https://app.usersnap.com/l/feedback/d39e4e4d-48c6-45ba-978b-c6084a8d210e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
The creator successfully signed up but failed the verification requirement. 
Action Item: Notified the creator about the suspension reason and provided the document for reference.
