### ISSUE TITLE
[USERSNAP] realmente creo que resuelvan 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5465]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: realmente creo que resuelvan 
- Houston, we have a problem.: Hola qué tal, Ami ya se me cumplieron las 48 horas y aún no me verifican el canal 
- Your Channel and Account Details: tfw mafia yt 
- Email or Discord handle for feedback: darieladrian85@gmail.com

**Browser**: ChromeiOS 119 (iOS)
**Screen size**: 414x896
**[Open #436 in Usersnap](https://app.usersnap.com/l/feedback/2c76052a-7400-43a0-96b2-e8c1e592f197?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
