### ISSUE TITLE
[USERSNAP] I definitely did not use bots.  I didn't use fake followers.  Do you have any evidence about this?  I want to use your site and earn money.  If the suspension is not lifted I will cancel my membership. Help me please

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5466]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: I definitely did not use bots.  I didn&#39;t use fake followers.  Do you have any evidence about this?  I want to use your site and earn money.  If the suspension is not lifted I will cancel my membership. Help me please
- Houston, we have a problem.:  I definitely did not use bots.  I didn&#39;t use fake followers.  Do you have any evidence about this?  I want to use your site and earn money.  If the suspension is not lifted I will cancel my membership. Help me please
- Your Channel and Account Details: basketciemre@gmail.com
- Email or Discord handle for feedback: basketciemre@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x851
**[Open #437 in Usersnap](https://app.usersnap.com/l/feedback/90958251-69e4-4951-80b0-acad951cf2d3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason "copyright breach" and provided the document for reference.
