### ISSUE TITLE
[USERSNAP] Login automatic with channel 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5467]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Login automatic with channel 
- Houston, we have a problem.: I can&#39;t login but my channel already signup
- Your Channel and Account Details: gapunyakode2@gmail.com
- Email or Discord handle for feedback: gapunyakode2@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x873
**[Open #438 in Usersnap](https://app.usersnap.com/l/feedback/6037b92a-e795-4b87-881e-d925386d24ff?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
**Action Taken:** Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
