### ISSUE TITLE
[USERSNAP] Login with channel better than 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5468]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Login with channel better than 
- Houston, we have a problem.: I can&#39;t login but my channel already signup
- Your Channel and Account Details: gapunyakode2@gmail.com
- Email or Discord handle for feedback: gapunyakode2@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/61d9ca98-7e1a-4213-94e4-a7a33cb6a724-annotated_474a8e4a-cbc7-40c2-92d7-5794d56b75e6.png?etag=190b3c74feecbaf9201a25c1d4522308)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/61d9ca98-7e1a-4213-94e4-a7a33cb6a724-annotated_474a8e4a-cbc7-40c2-92d7-5794d56b75e6.png?etag=190b3c74feecbaf9201a25c1d4522308)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x873
**Browser size**: 393x737
**[Open #439 in Usersnap](https://app.usersnap.com/l/feedback/5ceb5fb9-ee70-459e-aee6-26a5b837d174?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
