### ISSUE TITLE
the "cancel" buuton doesn't work

### ISSUE THREAD

**Issue by polikosi** [Joystream/atlas#5479]
the "cancel" button on the "Edit token" page does not work.
I expect to be redirected to the dashboard token after clicking the "cancel" button.

https://github.com/Joystream/atlas/assets/80429191/ca9898c2-2f2b-46d8-8aeb-63520b12d0b4

**Comment by dmtrjsg** [comment]
<img width="458" alt="Screenshot 2023-11-24 at 13 43 15" src="https://github.com/Joystream/atlas/assets/93924525/92636efb-ab93-44cc-813a-2fff9cfc57f8">

**Comment by polikosi** [comment]
> <img alt="Screenshot 2023-11-24 at 13 43 15" width="458" src="https://user-images.githubusercontent.com/93924525/285418907-92636efb-ab93-44cc-813a-2fff9cfc57f8.png">

Strange, because I got the same result as in the previous case
