### ISSUE TITLE
Video draft status changes during flow

### ISSUE THREAD

**Issue by mikkio-j** [Joystream/atlas#548]
![Screen Recording 2021-05-04 at 14 25 23](https://user-images.githubusercontent.com/59691518/117003426-2305c100-ace5-11eb-9b19-b6a4cd6cabb7.gif)

As seen in the gif, `isDraft` changes during the flow causing change in dialog message (and snackbar notification). Should change after closing the dialog

**Comment by kdembler** [comment]
That's another of those issues I've had in my mind, thanks for creating an issue for that! When I first noticed this was the first time I thought that using some kind of hook for dialogs may be a good idea. Not sure how we should solve that but it's good to have an issue for it :+1:

**Comment by kdembler** [comment]
What we do here may depend on outcome of #559, let's wait till that's done
