### ISSUE TITLE
[USERSNAP] no results 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5486]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: no results 
- Houston, we have a problem.: My Account is Not Login
- Your Channel and Account Details: entertainmentt79@gmail.com
- Email or Discord handle for feedback: entertainmentt79@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**[Open #446 in Usersnap](https://app.usersnap.com/l/feedback/2a876321-2192-45a2-b4b0-39dc7a5a050a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
no need for assistance  - "This account has been terminated for a violation of YouTube's Terms of Service".
