### ISSUE TITLE
[USERSNAP] Couldn't login 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5487]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Couldn&#39;t login 
- Houston, we have a problem.: My Account is Not Login
- Your Channel and Account Details: entertainmentt79@gmail.com
- Email or Discord handle for feedback: entertainmentt79@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5d8292c8-dfbb-44d7-929d-b2dbe3bbb2a4-annotated_eda0307b-2f87-4aa4-bb59-fd11ff659e74.png?etag=0033d6e82cca973d60c59ed06d9af200)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5d8292c8-dfbb-44d7-929d-b2dbe3bbb2a4-annotated_eda0307b-2f87-4aa4-bb59-fd11ff659e74.png?etag=0033d6e82cca973d60c59ed06d9af200)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x690
**[Open #447 in Usersnap](https://app.usersnap.com/l/feedback/169702f4-fb34-4027-bb6f-d9c24df24db5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue.
