### ISSUE TITLE
[FEATURE REQUEST] Repar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5495]
**Taken at**: https://gleev.xyz/ypp?state=code%3Dqj880lnbb%26channelId%3D&code=4/0AfJohXl-2Sc61YpUr5gcgY31fBEINAc70oV_zEZvBotmovOYTV3yYw03PCqJZUuwFtYKGQ&scope=email%20https://www.googleapis.com/auth/youtube.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- Which feature are you missing?: Repar
- Share your Email or Discord so we can get in touch: gamingofficial402@gmail.com
- Your Gleev channel ID or Title: https://youtube.com/@pyrgamingofficial?si=XMZt3RnbmWATacqD

**Browser**: Chrome 104 (Android 13)
**Screen size**: 424x942
**[Open #125 in Usersnap](https://app.usersnap.com/l/feedback/e556f277-b440-4919-873a-06cbaf32c704?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate.
