### ISSUE TITLE
[FEATURE REQUEST] Upload video 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5496]
**Taken at**: https://board.usersnap.com/tZNWrBYXJAAHUiTo/feedback/125?&
**Fields**:
- Which feature are you missing?: Upload video 
- Share your Email or Discord so we can get in touch: gamingofficial402@gmail.com
- Your Gleev channel ID or Title: https://youtube.com/@pyrgamingofficial?si=XMZt3RnbmWATacqD

**Browser**: Chrome 104 (Android 13)
**Screen size**: 424x942
**[Open #126 in Usersnap](https://app.usersnap.com/l/feedback/791b2b90-9ae5-45fb-b4e1-5ec446165bda?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
