### ISSUE TITLE
[USERSNAP] already creating account problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5497]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: already creating account problem 
- Houston, we have a problem.: i did now login my gleev account 
- Your Channel and Account Details: sagor18061144@gmail.com

- Email or Discord handle for feedback: sagor18061144@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1024x768
**[Open #452 in Usersnap](https://app.usersnap.com/l/feedback/5dcc1ec4-2acf-4c4c-828f-3b0b2fbf898d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24 hours.
