### ISSUE TITLE
[USERSNAP] Help me. 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5500]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Help me. 
- Houston, we have a problem.: Askıyı kaldırın lütfen 
- Your Channel and Account Details: basketciemre@gmail.com
- Email or Discord handle for feedback: basketciemre@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x851
**[Open #455 in Usersnap](https://app.usersnap.com/l/feedback/e8455b39-dd39-4893-a934-d6293782b828?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
