### ISSUE TITLE
[USERSNAP] I am not violating any copyright

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5514]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: I am not violating any copyright
- Houston, we have a problem.:  check my videos again
- Your Channel and Account Details: jegb I am the owner of those videos on my YouTube channel

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1352x657
**[Open #460 in Usersnap](https://app.usersnap.com/l/feedback/5b6a07e2-3278-4734-ad98-da4c57e3a87c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
No email address or YouTube link has been provided. There's no reference available for checking.
