### ISSUE TITLE
[USERSNAP] my account icomica2@gmail.com can't login, please help me

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5527]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: my account icomica2@gmail.com can&#39;t login, please help me
- Houston, we have a problem.: can&#39;t log in
- Your Channel and Account Details: icomica2@gmail.com

**Browser**: Chrome 108 (Android 11)
**Screen size**: 424x918
**[Open #467 in Usersnap](https://app.usersnap.com/l/feedback/ec0bf8be-dbc8-415f-9984-7f4773eb5042?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document for reference.
