### ISSUE TITLE
[USERSNAP] Password forget, so i am not mean my channel varified yes or not?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5528]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Password forget, so i am not mean my channel varified yes or not?
- Houston, we have a problem.: I Password forget
- Your Channel and Account Details: Md Alamin Hossain
- Email or Discord handle for feedback: linkerreza@gmail.com

**Browser**: Chrome 113 (Android 10)
**Screen size**: 360x800
**[Open #468 in Usersnap](https://app.usersnap.com/l/feedback/b02e2620-2463-4197-b7ee-83efd3907df9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
