### ISSUE TITLE
[USERSNAP] I need to fix this issue to fix the touch problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5544]
**Taken at**: https://gleev.xyz/member/darkbladegaming?tab=About
**Fields**:
- Expected Result: I need to fix this issue to fix the touch problem
- Houston, we have a problem.: No touch working on website
- Your Channel and Account Details: Yasif ul-Islam agnail.com 
- Email or Discord handle for feedback: hidingboy1234@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x780
**[Open #481 in Usersnap](https://app.usersnap.com/l/feedback/5f73d82c-7880-4520-a373-d349f80d6412?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
