### ISSUE TITLE
All creator tokens table

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5554]
## Context
- https://github.com/Joystream/atlas/issues/3773

## Design
[Link to Figma>](https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=478%3A217458&mode=design&t=EuFdwDhHJyeOIBS5-1)

## Scope
- [ ] Implement all tokens table
⚠️ make sure that header of the table remains sticky as the table is scrolling down

**Comment by WRadoslaw** [comment]
Either sticky header, which will make implementation longer, or we just use paginated table

**Comment by dmtrjsg** [comment]
Paginated seems okay cc @KubaMikolajczyk
