### ISSUE TITLE
[USERSNAP] tolong di acc

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5558]
**Taken at**: https://gleev.xyz/member/darjonofficial?tab=NFTs
**Fields**:
- Expected Result: tolong di acc
- Houston, we have a problem.: kenapa akun saya di suspend. padahal semua video asli buatan sendiri. tolong acc
- Your Channel and Account Details: nama chanel: darjon official
email: jbiasa1446@gmail.com
- Email or Discord handle for feedback: jbiasa1446@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/90bc1ed5-8326-4bef-9d4f-9feb31710a86-annotated_bc9e4c9f-050e-45f7-80fe-b249cc7798a2.png?etag=b084da5511bcb2824a4cb805accb5a8a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/90bc1ed5-8326-4bef-9d4f-9feb31710a86-annotated_bc9e4c9f-050e-45f7-80fe-b249cc7798a2.png?etag=b084da5511bcb2824a4cb805accb5a8a)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x672
**[Open #482 in Usersnap](https://app.usersnap.com/l/feedback/c59c3684-2a89-4d4c-a9e0-f1a1f81f3ff7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
