### ISSUE TITLE
[USERSNAP] Now I can't enter and it said my YouTube channel its connected 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5559]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Now I can&#39;t enter and it said my YouTube channel its connected 
- Houston, we have a problem.: I registered but didi create my membership 
- Your Channel and Account Details: raymer08023@gmail.com, Youtube Channel reinonreforma
- Email or Discord handle for feedback: raymer08023@gmail.com

**Browser**: Chrome 115 (Android 10)
**Screen size**: 360x640
**[Open #483 in Usersnap](https://app.usersnap.com/l/feedback/c2642f7f-6467-4fb3-9e1f-aed8c0fb08ca?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
