### ISSUE TITLE
User shouldn't be able to click on the loading placeholder for followed channels 

### ISSUE THREAD

**Issue by eldiegod** [Joystream/atlas#556]
On the sidenav the User shouldn't be able to click on the loading placeholder for followed channels as currently it redirects to a non existent channel.. 
<img width="440" alt="Screenshot 2021-05-05 at 09 55 24" src="https://user-images.githubusercontent.com/10615263/117120556-c1e8f680-ad93-11eb-8123-d5669dba887a.png">

**Comment by eldiegod** [comment]
Could perfectly be post-sumer

**Comment by kdembler** [comment]
Yeah, not really related to sumer and we're likely rework it later

**Comment by kdembler** [comment]
You can still click it but it properly redirects you so I guess we can close
