### ISSUE TITLE
[USERSNAP] be able to upload videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5561]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: be able to upload videos
- Houston, we have a problem.: can not upload videos
- Your Channel and Account Details: zhoukenshinn@gmail.com
- Email or Discord handle for feedback: trading.view6e@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #484 in Usersnap](https://app.usersnap.com/l/feedback/11a7f3ab-76cb-4d62-ac1f-f59c995a1c00?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
@rchrdcstro there are issues with the upload of large files. We will be able to increase the size slightly, so next week hopefully there will be a release which makes it better. 

Full solution is expected next year as there will be infrastructure changes required.

**Comment by rchrdcstro** [comment]
Action Item: Request a screenshot of the error and update the creator about ongoing developments and potential technical challenges.
