### ISSUE TITLE
[USERSNAP] Funciona bien "pero espero que sea util para ayudarme con mi solicitud

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5562]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Expected Result: Funciona bien &#34;pero espero que sea util para ayudarme con mi solicitud
- Houston, we have a problem.: Hola, soy un youtuber muy conocido en mi pais y tengo un canal de youtube grande el cual vincule a gleev pero aun no me verifican mi cuenta ni me aparecen mis recompensas, ya tengo un referido y puedo meter a muchos grandes youtuber pero primero quiero tener mi cuenta activa y generar ganancias por ello, gracias por su atencion
- Your Channel and Account Details: id de canal: channel/47722?tab=Videos
correo electronico: nt24music@gmail.com
- Email or Discord handle for feedback: nt24music@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1024x820
**[Open #485 in Usersnap](https://app.usersnap.com/l/feedback/bd94cda9-5420-4847-bc4f-3ea89fa4090c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under silver tier.
