### ISSUE TITLE
[FEATURE REQUEST] VERIFICACION

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5563]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: VERIFICACION
- ¿Qué problema resolvería eso para ti?: EN PENDIENTE DE VERIFICACION DICE QUE PUEDE TARDAR HASTA 48 HS, PERO YA PASO UNA SEMANA Y SIGUE IGUAL???? LA VAN A VERIFICAR O NO???
- Share your Email or Discord so we can get in touch: kennelhimalayos@gmail.com
- Your Gleev channel ID or Title: KENNEL ADROGUE

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #131 in Usersnap](https://app.usersnap.com/l/feedback/3e7d0669-0860-41bc-a896-5bf5249f648a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
