### ISSUE TITLE
[USERSNAP] por favor solucionar este error no me permite ingresar, Algo salió mal Este canal de YouTube ya está registrado y conectado con la membresía de Joystream. Informe esto al canal de soporte para obtener ayuda.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5564]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: por favor solucionar este error no me permite ingresar, Algo salió mal
Este canal de YouTube ya está registrado y conectado con la membresía de Joystream. Informe esto al canal de soporte para obtener ayuda.
- Houston, we have a problem.: Algo salió mal Este canal de YouTube ya está registrado y conectado con la membresía de Joystream. Informe esto al canal de soporte para obtener ayuda.
- Your Channel and Account Details: correo
yoeltalleres47@gmail.com
- Email or Discord handle for feedback: juan.parrao@cun.edu.co

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**[Open #486 in Usersnap](https://app.usersnap.com/l/feedback/1b303047-0a1f-4775-b508-5e8ff9f4a68c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue resolved in Discord Support Channel.
