### ISSUE TITLE
[USERSNAP] ??

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5565]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: ??
- Houston, we have a problem.: jerry0191303@gmail.com
- Your Channel and Account Details: https://www.youtube.com/@JerryHarry13
- Email or Discord handle for feedback: jerry0191303@gmail.com

**Browser**: Chrome 105 (Android 12)
**Screen size**: 360x806
**[Open #487 in Usersnap](https://app.usersnap.com/l/feedback/142f3b70-d827-4002-9785-bc6bf6e2f309?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent an email with the creator asking what is the concern about? The creator didn't provide any brief explanations.
