### ISSUE TITLE
[USERSNAP] unlock my account so i can upload some videos bos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5566]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: unlock my account so i can upload some videos bos
- Houston, we have a problem.: why my account got suspend bos?
- Your Channel and Account Details: my gmail account : umbuadiumbu@gmail.com
- Email or Discord handle for feedback: umbuadiumbu@gmail.com

**Browser**: Chrome 119 (macOS Catalina)
**Screen size**: 1280x800
**[Open #488 in Usersnap](https://app.usersnap.com/l/feedback/a9cb3c2d-0853-426c-bf23-a3d93dc1d232?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
