### ISSUE TITLE
[USERSNAP] I am doing sign up with this channel but showing this channel is already connected with another joystream connection  YouTube channel link - https://www.youtube.com/@Animeworldnaruto605

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5567]
**Taken at**: https://gleev.xyz/ypp?state=code%3Dm57v4hmfk%26channelId%3D&code=4/0AfJohXkEgZTil-_bAMVaNOlUAXnr8THaDPnuFBj1RA_mPovG1pMm86oV2zeVL7gKoWzRwg&scope=email%20https://www.googleapis.com/auth/youtube.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=1&prompt=consent
**Fields**:
- Expected Result: I am doing sign up with this channel but showing this channel is already connected with another joystream connection 
YouTube channel link - https://www.youtube.com/@Animeworldnaruto605
- Houston, we have a problem.: YPP problem
- Your Channel and Account Details: https://www.youtube.com/@Animeworldnaruto605
- Email or Discord handle for feedback: jk18263700@gmail.com

**Browser**: Chrome 109 (Android 11)
**Screen size**: 360x800
**[Open #489 in Usersnap](https://app.usersnap.com/l/feedback/2fb56c57-2477-4258-a7bf-1f75708523ca?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the email address used for feedback matches the one used during the sign-up process, but unfortunately, the channel did not meet the verification criteria.
