### ISSUE TITLE
[USERSNAP] I almost reffer 7 people. But i Didn't received my payment. It's almsot 3 weeks.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5568]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: I almost reffer 7 people. But i Didn&#39;t received my payment. It&#39;s almsot 3 weeks.
- Houston, we have a problem.: Youtube Reffer Program
- Your Channel and Account Details: verifiedairdrops2430, mrex1600@gmail.com
- Email or Discord handle for feedback: mrex1600@gmail.com

**Browser**: Yandex.Browser 23 (Linux)
**Screen size**: 360x804
**[Open #490 in Usersnap](https://app.usersnap.com/l/feedback/9cee76e5-5435-4b12-89f9-970c0a0e7acc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
