### ISSUE TITLE
[USERSNAP] jerry0191303@gmail.com

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5573]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: jerry0191303@gmail.com

- Houston, we have a problem.: jerry0191303@gmail.com
- Your Channel and Account Details: https://youtube.com/@JerryHarry13?si=ZyLGTToDqFYoE9Z_
- Email or Discord handle for feedback: jerry0191303@gmail.com

**Browser**: Chrome 105 (Android 12)
**Screen size**: 360x806
**[Open #491 in Usersnap](https://app.usersnap.com/l/feedback/ffc5a225-558b-4f36-ae33-58c0b15bae49?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Issue not stated. Advise the creator to state the concern and join discord creator support channel.
