### ISSUE TITLE
[FEATURE REQUEST] RECOMPENSA NIVEL DE BRONCE

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5575]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: RECOMPENSA NIVEL DE BRONCE
- ¿Qué problema resolvería eso para ti?: DE QUE ME SIRVE ESTAR EN GLEEV SI A ESTE NIVEL NO ME VAN A PAGAR NADA POR CADA VIDEO QUE SUBA??
- Share your Email or Discord so we can get in touch: luffyfanny@gmail.com
- Your Gleev channel ID or Title: KENNEL ADROGUE

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #132 in Usersnap](https://app.usersnap.com/l/feedback/f7843871-3589-4f35-ac8c-5773351e7d1f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator about program details.
