### ISSUE TITLE
[USERSNAP] boa noite meu nome é Cristiano, tenho 10.500 escrito no meu canal e vocês só vão me pagar 2 dólares?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5576]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: boa noite meu nome é Cristiano, tenho 10.500 escrito no meu canal e vocês só vão me pagar 2 dólares?
- Houston, we have a problem.: tenho 10.500 escrito no meu canal e vocês só vão me pagar 2 dólares?
- Your Channel and Account Details: Cristiano CF3
@CristianoCF3
‧
10,5 mil inscritos
https://www.youtube.com/channel/UCer5W5t8_jJtP7nNj3PTUcQ
SE FOR SÓMENTE ISSO QUERO DESFAZER O ACORDO O SINK  A ESCRIÇÃO COM VOCES. AGUARDANDO RETORNO.
- Email or Discord handle for feedback: cristianoautor@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3aa0fcef-4f90-4316-a365-8e60d638d39b-annotated_5dd723c3-f3e2-4491-b5bc-862002c57e02.png?etag=b66f187309dfd6a2ff5b4a089b9c9a1f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3aa0fcef-4f90-4316-a365-8e60d638d39b-annotated_5dd723c3-f3e2-4491-b5bc-862002c57e02.png?etag=b66f187309dfd6a2ff5b4a089b9c9a1f)*

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x633
**[Open #493 in Usersnap](https://app.usersnap.com/l/feedback/9db717be-9e0d-4deb-8400-fb93f1bdb0e4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator basis of verification and forward program details.
