### ISSUE TITLE
[USERSNAP] Server Indonesia always bug in upload,login,token his gone

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5578]
**Taken at**: https://gleev.xyz/studio
**Fields**:
- Expected Result: Server Indonesia always bug in upload,login,token his gone
- Houston, we have a problem.: Bug website and token
- Your Channel and Account Details: 36339/Mikael Eprain/eprainmikael@gmail.com/mikaelsmith.
- Email or Discord handle for feedback: eprainmikael@gmail.com // mikaelsmith.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c4884662-515c-42c1-af4a-c2a6d94cb1ba-annotated_23d9663e-3afd-47c5-9d51-23ebafd877b1.png?etag=d1fbca78c003b5e1958c7fe74a006ea2)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c4884662-515c-42c1-af4a-c2a6d94cb1ba-annotated_23d9663e-3afd-47c5-9d51-23ebafd877b1.png?etag=d1fbca78c003b5e1958c7fe74a006ea2)*

**Browser**: Chrome 119 (Android 10)
**Screen size**: 400x867
**Browser size**: 400x735
**[Open #495 in Usersnap](https://app.usersnap.com/l/feedback/00846f87-5575-4b7a-a7a1-16bca7f4dfbd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
