### ISSUE TITLE
[USERSNAP] necesito que me expliquen porfavor porque el mensaje de suspendido en mi canal.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5583]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: necesito que me expliquen porfavor porque el mensaje de suspendido en mi canal.
- Houston, we have a problem.: me sale explotacion de los terminos del programa
- Your Channel and Account Details: 𝕄𝕦𝕤𝕚𝕔𝕒𝕂𝕒𝕣𝕒𝕠𝕜𝕖𝕤𝟞𝟞𝟞
tengo un problema porque me dijeron que vinculara mi cuenta de youtube y me sale un mensaje de suspendido y no se porque.
Me ayudan porfavor
- Email or Discord handle for feedback: caos.test7@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**[Open #497 in Usersnap](https://app.usersnap.com/l/feedback/c17e2a4b-a5d7-46bb-af07-9899d1dea4fe?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator that the channel was re-evaluated and verified now under bronze tier.
