### ISSUE TITLE
[USERSNAP] my channel has been suspended, I don't know why but my channel has every qualification

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5584]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: my channel has been suspended, I don&#39;t know why but my channel has every qualification
- Houston, we have a problem.: my channel suspended
- Your Channel and Account Details: hakanisik176@gmail.com
j4Uj3hRn4omPCdREEYZJyCE6CArphdDNaegYgV1AnLK79j6gC

- Email or Discord handle for feedback: hakanisik176@gmail.com

**Browser**: Safari 17 (macOS Catalina)
**Screen size**: 1440x900
**[Open #498 in Usersnap](https://app.usersnap.com/l/feedback/1cb0a0d5-2af2-4b19-bfbc-0f7243780ce1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
