### ISSUE TITLE
[USERSNAP] I expected that my channel would be accepted into the partnership program, but I do not know why my channel was suspended. Please, what is the solution to this problem?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5591]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: I expected that my channel would be accepted into the partnership program, but I do not know why my channel was suspended. Please, what is the solution to this problem?
- Houston, we have a problem.: Why was my channel suspended and what is the solution to this problem?
- Your Channel and Account Details: walidmohamedtahir@gmail.com
https://youtube.com/@dm_wr-nov?si=3Etac2OBGgsD5ewP
- Email or Discord handle for feedback: walidmohamedtahir@gmail.com

**Browser**: Chrome 103 (Android 8.0.0)
**Screen size**: 360x640
**[Open #500 in Usersnap](https://app.usersnap.com/l/feedback/62fdc093-d815-4398-adb1-82e34ba76c8b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
