### ISSUE TITLE
[FEATURE REQUEST] COMO SE COBRA EL BONO DE REGISTRO?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5592]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: COMO SE COBRA EL BONO DE REGISTRO?
- ¿Qué problema resolvería eso para ti?: EXPLIQUEN EN ESPAÑOL COMO SE COBRA EL BONO DE REGISTRO
- Share your Email or Discord so we can get in touch: kennelhimalayos@gmail.com
- Your Gleev channel ID or Title: KENNEL ADROGUE

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #134 in Usersnap](https://app.usersnap.com/l/feedback/98b98446-f918-462d-aeff-fce815c76b6b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. (In spanish) https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
