### ISSUE TITLE
[FEATURE REQUEST] Не могу зайти в акаунт

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5593]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Какая черта вам не хватает?: Не могу зайти в акаунт
- Какая проблема мы можем решить для вас?: Не могу зайти в аккаунт whitefadio@gmail.com. Я регистрировался в сентябре. Как восстановить доступ, когда хочу зарегистрироваться пишут такой канал уже есть в системе.
- Share your Email or Discord so we can get in touch: whitefadio@gmail.com
- Your Gleev channel ID or Title: https://www.youtube.com/@NaPasive

**Browser**: Yandex.Browser 23 (Windows 10)
**Screen size**: 1920x1080
**[Open #135 in Usersnap](https://app.usersnap.com/l/feedback/02f39758-6533-41d4-9dd8-64bd089a3117?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference. 
https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
