### ISSUE TITLE
[USERSNAP] Espero que tomen en consideracion mi caso y se pueda resorber 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5595]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Espero que tomen en consideracion mi caso y se pueda resorber 
- Houston, we have a problem.: Hola, buenas noches, escribo porque me registre en el mes de nobiembre y mi pago y el de mis referidos seria efectuado el dia 5 de diciembre pero aun no me han pagado ni a mis referidos tampoco y la fecha de pago nos fue actualizada para el dia 12 de diciembre razon por la cual estan empezando a dudar, por favor poner en consideracion nuestro caso. gracias por su atencion pase feliz noche
- Your Channel and Account Details: id gleev: 36939 / id youtube: UCcHTMLHIy3jNR_QmUvf3h9w / Correo de gleev: nt24music@gmail.com
- Email or Discord handle for feedback: nt24music@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1024x820
**[Open #502 in Usersnap](https://app.usersnap.com/l/feedback/c3ccd522-7059-4d72-a6cf-6b2c6a4d66eb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue.
