### ISSUE TITLE
Stake token to revenue share on the token page/member portfolio

### ISSUE THREAD

**Issue by polikosi** [Joystream/atlas#5600]
- [ ] As a holder I don't see where I can stake tokens on the token page.
![image](https://github.com/Joystream/atlas/assets/80429191/1c60faa3-5c73-4024-b4b7-0032e2f3fea2)

- [ ] As a holder I don't see where I can stake tokens on my portfolio page.
I can only claim my share, but I have not stake tokens before, as you can see in the screenshot.
![image](https://github.com/Joystream/atlas/assets/80429191/6b1e65c6-306f-45a6-b9b0-9e1b9447cca1)

**Comment by dmtrjsg** [comment]
@polikosi claiming share is in fact implies staking. Its just a diff wording. So staking for users = claim in the CTA. 

(we probably should change this)

**Comment by polikosi** [comment]
@dmtrjsg Okay, I get it.
But then the next problem is that when I click on the "claim your share" button, nothing happens.
As you can see in the video, I have tokens, revenue share is active

https://github.com/Joystream/atlas/assets/80429191/71b27b14-f328-4d54-87c2-a33730e12887
