### ISSUE TITLE
[USERSNAP] I was referring a lot of things a few days back all refer success but I didn't get bonus

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5604]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Expected Result: I was referring a lot of things a few days back all refer success but I didn&#39;t get bonus
- Houston, we have a problem.: reffer bonus not riceave
- Your Channel and Account Details: ID. 36209
handle. @s.rlittlebird9106
mail. Sheblurr@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1024x768
**[Open #503 in Usersnap](https://app.usersnap.com/l/feedback/c8705af2-e135-42f0-b9df-a11090a74d16?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address and channel id provided associate is not found. Ask creator to provide youtube channel and/or screenshot of referral dashboard.
