### ISSUE TITLE
[USERSNAP] merhaba kabak kafalar kanalımıza red gelmiş sebebini anlayamadım

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5605]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: merhaba kabak kafalar kanalımıza red gelmiş sebebini anlayamadım
- Houston, we have a problem.: kanalıma red gelmiş
- Your Channel and Account Details: kabak kafalar kanal ismi
- Email or Discord handle for feedback: omerkopuz16@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1536x864
**[Open #504 in Usersnap](https://app.usersnap.com/l/feedback/d0c1a1ed-9538-47bc-9c5a-86e0fbe4a8fd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under silver tier.
