### ISSUE TITLE
[FEATURE REQUEST] merhaba kanalım neden onaylanmadı

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5606]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Hangi özelliği kaçırıyorsun?: merhaba kanalım neden onaylanmadı
- Bu sizin için hangi problemi çözer?: bunu öğrenmek istiyorum
- Share your Email or Discord so we can get in touch: omerkopuz16@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/studio/ypp/dashboard

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1536x864
**[Open #136 in Usersnap](https://app.usersnap.com/l/feedback/cf0a98b0-2551-4f6b-b7cf-e83f360ee44e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
