### ISSUE TITLE
[USERSNAP] can log back in to your account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5608]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: can log back in to your account
- Houston, we have a problem.: can&#39;t log in to account
- Your Channel and Account Details: Fionse Music
Email: teguhnurhakim50@gmail.com
- Email or Discord handle for feedback: teguhnurhakim50@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d8086d8c-cab5-40a4-81ee-309bb85b215f-annotated_19c60886-ed44-43f9-b136-5e43d5ad60cd.png?etag=607e20abfc549fef2e31496560b2c83e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d8086d8c-cab5-40a4-81ee-309bb85b215f-annotated_19c60886-ed44-43f9-b136-5e43d5ad60cd.png?etag=607e20abfc549fef2e31496560b2c83e)*

**Browser**: Edge (Chromium) 119 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1318x654
**[Open #505 in Usersnap](https://app.usersnap.com/l/feedback/de115a11-1098-4450-9d41-ade29f91dc74?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document for reference.
