### ISSUE TITLE
[USERSNAP] me dice que ya estoy conectado al Joystream y no me deja ingresar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5611]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: me dice que ya estoy conectado al Joystream y no me deja ingresar
- Houston, we have a problem.: No me deja abrir mi cuenta
- Your Channel and Account Details: brayangt58@gmail.com
- Email or Discord handle for feedback: brayangt58@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1920x1080
**[Open #506 in Usersnap](https://app.usersnap.com/l/feedback/c37fe914-6fe0-48aa-95fc-33b2a8416c03?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
