### ISSUE TITLE
[USERSNAP] inicie sesion con mi canal y al intentar iniciar sesion me dice que no hay asociado nada

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5612]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: inicie sesion con mi canal y al intentar iniciar sesion me dice que no hay asociado nada
- Houston, we have a problem.: no me deja iniciar sesion con el email creado 
- Your Channel and Account Details: ciaotuttittt@gmail.com youtube xdu150684@gmail.com register email
- Email or Discord handle for feedback: xdu150684@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #507 in Usersnap](https://app.usersnap.com/l/feedback/b42a76b0-47f4-412e-90a8-ab1dd76eaff4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Inform the creator to use the other email address to login.
