### ISSUE TITLE
[USERSNAP] changing e-mail address

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5613]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: changing e-mail address
- Houston, we have a problem.: email change
- Your Channel and Account Details: Hello, my old e-mail address is cetintasburak46@gmail.com.
I will not use that anymore. I will use my new e-mail address, eymenawzem@gmail.com. Could you please change this e-mail address, thank you...

I also request that my wallet address be changed. My new wallet address is:  

My e-mail address: cetintasburak46@gmail.com

This is the user address of the channel: @burakprod2948
- Email or Discord handle for feedback: eymenawzem@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1536x864
**[Open #508 in Usersnap](https://app.usersnap.com/l/feedback/4dd4f563-5c5c-454e-8e2a-bcffc1ad4cb5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that email address is change to [**eymenawzem@gmail.com**].
