### ISSUE TITLE
[USERSNAP] new wallet : 12xgWH4m4SNg8qLvzLv8uKLLrtykY9obbFi9MXBnkowJZzUv

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5614]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: new wallet : 12xgWH4m4SNg8qLvzLv8uKLLrtykY9obbFi9MXBnkowJZzUv
- Houston, we have a problem.: email change
- Your Channel and Account Details: new wallet : 12xgWH4m4SNg8qLvzLv8uKLLrtykY9obbFi9MXBnkowJZzUv
- Email or Discord handle for feedback: eymenawzem@gmail.com

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1536x864
**[Open #509 in Usersnap](https://app.usersnap.com/l/feedback/003f6370-6fa3-46ed-913d-668080f274fd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
