### ISSUE TITLE
[USERSNAP] Kayıt yapmadı

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5615]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Kayıt yapmadı
- Houston, we have a problem.: Hata aldım
- Your Channel and Account Details: celebibaris040@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x851
**[Open #510 in Usersnap](https://app.usersnap.com/l/feedback/6e2c1f15-5eba-452a-802b-233e6eaf41bc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
