### ISSUE TITLE
[USERSNAP] i hope that i can sign up with my email, please cek this email (kharismacarma14@gmail.com) already signup or not? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5616]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: i hope that i can sign up with my email, please cek this email (kharismacarma14@gmail.com) already signup or not? 
- Houston, we have a problem.: i cant sign up my gmail youtube account it say that i already signup in gleev with my email, than when i try to sign in the web say cannot find the email correct  
- Your Channel and Account Details: i dont have my gleev account 
- Email or Discord handle for feedback: wdinata14@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #511 in Usersnap](https://app.usersnap.com/l/feedback/171a0a63-42d7-46a9-9997-86a286763c94?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
