### ISSUE TITLE
[USERSNAP] I have added a refer success please balance not added one

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5617]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard?tab=Referrals
**Fields**:
- Expected Result: I have added a refer success please balance not added one
- Houston, we have a problem.: reffer bonus not riceave
- Your Channel and Account Details: id 36209
handle @s.rlittlebird9106
email Sheblurr@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/70d23008-c091-410a-b3de-d15731f214b5-annotated_f92f4483-2855-4073-a869-d3c4972a63af.png?etag=13c509a62d1803e489f02cc7ae140a51)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/70d23008-c091-410a-b3de-d15731f214b5-annotated_f92f4483-2855-4073-a869-d3c4972a63af.png?etag=13c509a62d1803e489f02cc7ae140a51)*

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1024x768
**Browser size**: 1024x651
**[Open #512 in Usersnap](https://app.usersnap.com/l/feedback/ce074d1a-2cef-4603-9b21-5261ef04b3b2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue, already provided assistance.
