### ISSUE TITLE
[USERSNAP] I used google to sign up, but while signing up, an error code dropped to try again later. Now today I am trying and basically it says the account is registered, but the email I used is not working and is invalid.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5618]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: I used google to sign up, but while signing up, an error code dropped to try again later. Now today I am trying and basically it says the account is registered, but the email I used is not working and is invalid.
- Houston, we have a problem.: Signed up with a YouTube account, but can&#39;t log in
- Your Channel and Account Details: UCotiZ6qP5Mus1gRiTokzIZQ
- Email or Discord handle for feedback: hello@cryptoclicks.io

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1928x972
**[Open #513 in Usersnap](https://app.usersnap.com/l/feedback/4f1a0638-f87a-4676-8439-666c6c57c6ef?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
