### ISSUE TITLE
[USERSNAP] hesabı açın ve ödeme yapın ben gerçek bir kişiyim ve kanal bana ait haksızca askıda 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5622]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: hesabı açın ve ödeme yapın ben gerçek bir kişiyim ve kanal bana ait haksızca askıda 
- Houston, we have a problem.: hesabım neden askıda
- Your Channel and Account Details: aytactutkug@gmail.com
japon balıkları dünyası
- Email or Discord handle for feedback: aytactutkug@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1280x800
**[Open #514 in Usersnap](https://app.usersnap.com/l/feedback/a5471daf-3054-4a61-9f77-51836d6e428c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is now verified under bronze tier.
