### ISSUE TITLE
[USERSNAP] please help

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5624]
**Taken at**: https://gleev.xyz/ypp?state=code%3Daagl0v03d%26channelId%3D&code=4/0AfJohXn1QCyY9oVlnHdvuP3dUejWXpSTzSR6XrB8kO7KVlZ2mvW1L6jmTRQelRzPkBQKeg&scope=email%20https://www.googleapis.com/auth/youtube.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- Expected Result: please help
- Houston, we have a problem.: cant login my account
- Your Channel and Account Details: kamandakaraden101@gmail.com
- Email or Discord handle for feedback: kamandakaraden101@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 501x1141
**[Open #516 in Usersnap](https://app.usersnap.com/l/feedback/a5520ea2-4eb8-4e7d-b94b-b2ce2645158b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
