### ISSUE TITLE
[USERSNAP] I was join one month ago but until now i can not login to app, can help me how to process my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5625]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Expected Result: I was join one month ago but until now i can not login to app, can help me how to process my account
- Houston, we have a problem.: Join but can not login
- Your Channel and Account Details: Email : cbos991@gmail.com
Channel name : Suheri9695
- Email or Discord handle for feedback: cbos991@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 360x806
**[Open #517 in Usersnap](https://app.usersnap.com/l/feedback/5a92c314-6ab2-4b58-9839-523981cc4eab?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
