### ISSUE TITLE
[FEATURE REQUEST] Login problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5626]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: Login problem
- What problem would that solve for you?: I am opening the account for the first time and I am not able to login the second time
- Share your Email or Discord so we can get in touch: mdkawsarhossen848@gmail.com
- Your Gleev channel ID or Title: FREE INCOME BD

**Browser**: Chrome 105 (Android 12)
**Screen size**: 360x820
**[Open #137 in Usersnap](https://app.usersnap.com/l/feedback/4a7b610b-c84f-4712-a28c-26ad7f1ba7f5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
