### ISSUE TITLE
[FEATURE REQUEST] Login problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5627]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: Login problem
- What problem would that solve for you?: I opened the account the first time and was able to login the second time
- Share your Email or Discord so we can get in touch: mdkawsarhossen848@gmail.com
- Your Gleev channel ID or Title: FREE INCOME BD

**Browser**: Chrome 105 (Android 12)
**Screen size**: 360x820
**[Open #138 in Usersnap](https://app.usersnap.com/l/feedback/fa8a6c1f-c608-4d99-9391-c2c7d83873ab?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item:  Acknowledge creator concern and ask creator if problem still exist.
