### ISSUE TITLE
[USERSNAP] I want to create an account! But there's problem with creating a new account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5628]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Expected Result: I want to create an account! But there&#39;s problem with creating a new account
- Houston, we have a problem.: Cannot create new account.
- Your Channel and Account Details: yeakinsinger148@gmail.com
- Email or Discord handle for feedback: yeakinsinger148@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x873
**[Open #518 in Usersnap](https://app.usersnap.com/l/feedback/ebbecf4f-83f3-40cf-b5e1-7f7ffd3afe63?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
