### ISSUE TITLE
[USERSNAP] que la sincronizacion de los videos no tuviera ningun problema

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5629]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: que la sincronizacion de los videos no tuviera ningun problema
- Houston, we have a problem.: Mi canal a sido suspendido y no se cual es el motivo
- Your Channel and Account Details: @bonyabor bonyabre1@gmail.com
- Email or Discord handle for feedback: bonyabre1@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0925b0a7-68be-44b6-957d-d12f38620947-annotated_379df48b-12a8-4dc4-9635-8b37bcca53e5.png?etag=2b019c10d17656905476958e431ad4aa)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0925b0a7-68be-44b6-957d-d12f38620947-annotated_379df48b-12a8-4dc4-9635-8b37bcca53e5.png?etag=2b019c10d17656905476958e431ad4aa)*

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x643
**[Open #519 in Usersnap](https://app.usersnap.com/l/feedback/bfe861cc-febd-4479-a163-5677816b312b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
