### ISSUE TITLE
[USERSNAP] Y me podrán explicar 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5630]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Y me podrán explicar 
- Houston, we have a problem.: Bueno está suspendido dice a qué se debe eso si recién ase poco me registro 
- Your Channel and Account Details: No se mi id
- Email or Discord handle for feedback: alexcv2800@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f8ef2331-d728-4845-931e-9e7388e6fd70-annotated_fa8c354e-74cb-454c-b0b1-e12e2e509bb1.png?etag=f560fd3b47c0a29ece3ac5f4bba346e5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f8ef2331-d728-4845-931e-9e7388e6fd70-annotated_fa8c354e-74cb-454c-b0b1-e12e2e509bb1.png?etag=f560fd3b47c0a29ece3ac5f4bba346e5)*

**Browser**: Chrome 103 (Android 12)
**Screen size**: 360x825
**Browser size**: 360x698
**[Open #520 in Usersnap](https://app.usersnap.com/l/feedback/e29965ea-dd28-46de-b58e-5b9367a2d4c9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
