### ISSUE TITLE
[USERSNAP] Normal 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5631]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Normal 
- Houston, we have a problem.: Good evening to all GLEEV staff, I have a problem that I can&#39;t enter into my gleev account, I have how to resolve why I need to enter my account, I created my account with this email.  jorgevasquez@mail.ru
- Your Channel and Account Details: Channel ID.
https://gleev.xyz/channel/48650?tab=Information

Membership. 
https://gleev.xyz/member/jorgevasquez?tab=NFTs

Email. 
jorgevasquez@mail.ru
- Email or Discord handle for feedback: jorgevasquez@mail.ru

**Browser**: Safari 16 (iOS)
**Screen size**: 428x926
**[Open #521 in Usersnap](https://app.usersnap.com/l/feedback/bff2612f-1c08-47a5-95cb-cd9f00cd2bd3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
