### ISSUE TITLE
[USERSNAP] Normal 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5632]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Normal 
- Houston, we have a problem.: Hello to all the Gleev staff, I have a problem that I cannot access my Gleev account, the truth is I created my account with this email, jorgevasquez@mail.ru
- Your Channel and Account Details: Channel ID. 
https://gleev.xyz/channel/48650?tab=Videos

Membership. 
https://gleev.xyz/member/jorgevasquez?tab=NFTs

Email.  jorgevasquez@mail.ru
- Email or Discord handle for feedback: Discord Handle/     jorge.vasquez

**Browser**: Safari 16 (iOS)
**Screen size**: 428x926
**[Open #522 in Usersnap](https://app.usersnap.com/l/feedback/9ef4f143-e883-4795-b109-5d529fd276de?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
