### ISSUE TITLE
[USERSNAP] Mi correo es wilsonvega055@gmail.com 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5633]
**Taken at**: https://gleev.xyz/channel/47877?tab=Videos
**Fields**:
- Expected Result: Mi correo es
wilsonvega055@gmail.com 
- Houston, we have a problem.: No me abre mi cuenta ni la contraseña  nada
- Your Channel and Account Details: stock sea beauty earth author angle canoe flight inhale patch adapt early

Esa las letras de la membresía 

**Browser**: Chrome 119 (Android 10)
**Screen size**: 384x857
**[Open #523 in Usersnap](https://app.usersnap.com/l/feedback/9170b99d-a598-4433-96a7-010aee1b0c4e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
