### ISSUE TITLE
[USERSNAP] I made a withdrawal but it hasn't arrived yet 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5634]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: I made a withdrawal but it hasn&#39;t arrived yet 
- Houston, we have a problem.: I made a withdrawal but it hasn&#39;t arrived yet 
- Your Channel and Account Details: Rdfn1928@gmail.com
- Email or Discord handle for feedback: Rdfn1928@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a0ee5dfc-9c13-4c5d-9ca4-3610ae125f06-annotated_f250f601-102b-4bda-adf1-85250a7b40d1.png?etag=8a059db614a0a07f09f7f535083099ea)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a0ee5dfc-9c13-4c5d-9ca4-3610ae125f06-annotated_f250f601-102b-4bda-adf1-85250a7b40d1.png?etag=8a059db614a0a07f09f7f535083099ea)*

**Browser**: Chrome 117 (Android 10)
**Screen size**: 393x851
**Browser size**: 393x767
**[Open #524 in Usersnap](https://app.usersnap.com/l/feedback/dc38f326-e4a7-4450-a45f-6aa80d8bf3fc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator the steps on how to withdraw joy tokens and sent the document.
