### ISSUE TITLE
[USERSNAP] Una solución para poder usar mi cuenta 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5637]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Expected Result: Una solución para poder usar mi cuenta 
- Houston, we have a problem.: No puedo acceder a mi cuenta,dice que pude crear una cuenta pero cuando intento acceder me dice que no la tengo , entonces intento vincular mi canal de YouTube a otra nueva cuenta y ni me deja
- Your Channel and Account Details: El correo con el que al parecer creo la cuenta es anijoeg@gmail.com
- Email or Discord handle for feedback: anijoeg@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 393x873
**[Open #525 in Usersnap](https://app.usersnap.com/l/feedback/3b082909-99e8-4528-8ae2-9e376111d594?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
