### ISSUE TITLE
[FEATURE REQUEST] It was a warning I received when I first opened the channel. There are hundreds of videos on my channel.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5638]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Hangi özelliği kaçırıyorsun?: It was a warning I received when I first opened the channel. There are hundreds of videos on my channel.
- Bu sizin için hangi problemi çözer?: It was a warning I received when I first opened the channel. There are hundreds of videos on my channel.
- Share your Email or Discord so we can get in touch: ozguraltunn09@gmail.com
- Your Gleev channel ID or Title: BumerangTw

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #139 in Usersnap](https://app.usersnap.com/l/feedback/d160d2b6-3d8b-45de-a55e-26641bc8bcec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
