### ISSUE TITLE
[USERSNAP] I made a referral last 20th November but still I have not received the refer bonus please give me my refer bonus

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5639]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: I made a referral last 20th November but still I have not received the refer bonus please give me my refer bonus
- Houston, we have a problem.: Reffer bonus not received 
- Your Channel and Account Details: Id : 35386
Hanble : @mostakimmuhin9648
Mail : mostakimmuhinalfi@gmail.com
- Email or Discord handle for feedback: mostakimmuhinalfi@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x640
**[Open #526 in Usersnap](https://app.usersnap.com/l/feedback/96d1e933-289b-4858-bc7d-682c67b3329b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Request the creator to provide screenshots of their referral dashboard and the associated YouTube channels for verification.
