### ISSUE TITLE
[USERSNAP] Esta sicronizado pero no veo la monetizacion, mi canal esta suspendido

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5641]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Esta sicronizado pero no veo la monetizacion, mi canal esta suspendido
- Houston, we have a problem.: Mi canal ya se encuentra sincronizado, pero se encuentra suspendido y no se porque??
- Your Channel and Account Details: @bonyabor bonyabre1@gmail.com
- Email or Discord handle for feedback: bonyabre1@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9c6bc60f-c179-48bf-b590-862a0b24a8e1-annotated_6012ff34-8823-43e9-a70c-18d52fb3580e.png?etag=2a96c27787fd8a3357a59ab68aa3d4f5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9c6bc60f-c179-48bf-b590-862a0b24a8e1-annotated_6012ff34-8823-43e9-a70c-18d52fb3580e.png?etag=2a96c27787fd8a3357a59ab68aa3d4f5)*

**Browser**: Chrome 119 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x643
**[Open #527 in Usersnap](https://app.usersnap.com/l/feedback/82701c67-4878-49b9-b077-1748156185c4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
