### ISSUE TITLE
[USERSNAP] please pay unpaid referrals

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5642]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: please pay unpaid referrals
- Houston, we have a problem.: I have 4 verified referrals, but only 2 were paid
- Your Channel and Account Details: Jalan Jalan Miku 
- Email or Discord handle for feedback: mizuzakimiku@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 424x942
**[Open #528 in Usersnap](https://app.usersnap.com/l/feedback/d5944ca1-cbf0-4808-93be-678b1363dd77?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Issue resolved in discord.
