### ISSUE TITLE
[USERSNAP] my account suspend please remove my suspend notise.really sorry today actively video upload please 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5643]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: my account suspend please remove my suspend notise.really sorry today actively video upload please 
- Houston, we have a problem.: my account suspend please agin review
- Your Channel and Account Details: j4U9T6MomjXhNm9AfG9hDuynLEagGRgEscJzs4WBJnGLymE7x
- Email or Discord handle for feedback: @tushar37485

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1440x900
**[Open #529 in Usersnap](https://app.usersnap.com/l/feedback/a0315a80-2e9b-4380-803f-d15f5d05454c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Youtube channel and email address not provided for feedback to assist. *closed*
