### ISSUE TITLE
[USERSNAP] on the site its say i will get 2$ sing up rewards in 12 dec ! but why i doest not nothing just added ?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5644]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: on the site its say i will get 2$ sing up rewards in 12 dec ! but why i doest not nothing just added ?
- Houston, we have a problem.: I don&#39;t get the sing up 2$ reward
- Your Channel and Account Details: atoislive.yt@gmail.com
- Email or Discord handle for feedback: atoislive.yt@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 411x913
**[Open #530 in Usersnap](https://app.usersnap.com/l/feedback/228b9647-829e-4d46-9272-d06b3864ae0f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards.
