### ISSUE TITLE
[USERSNAP] Error 500

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5645]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Error 500
- Houston, we have a problem.: I can’t create account. Thanks
- Your Channel and Account Details: N/A
- Email or Discord handle for feedback: Emiliosalassaenz@gmail.com

**Browser**: Safari 17 (iOS)
**Screen size**: 390x844
**[Open #531 in Usersnap](https://app.usersnap.com/l/feedback/6a3f563f-0411-4987-b84d-dfa5c4bff040?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
