### ISSUE TITLE
[USERSNAP] Hola mi cuenta de gleev fue suspendida y no entiendo el porque fue suspendido y lo peor que mis referencias no se reflejan tampoco  Mi canal es Alex cortez Vasquez 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5646]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Hola mi cuenta de gleev fue suspendida y no entiendo el porque fue suspendido y lo peor que mis referencias no se reflejan tampoco 
Mi canal es Alex cortez Vasquez 
- Houston, we have a problem.: Cuenta suspendida 
- Your Channel and Account Details: alexcv2800@gmail.com
- Email or Discord handle for feedback: alexcv2800@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e566e60c-e316-4685-aefa-8b4437619ea6-annotated_835943b0-b124-4a81-8f2d-6ef1470b38b3.png?etag=f78e87826c499a041c6fceaa9881a5fe)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e566e60c-e316-4685-aefa-8b4437619ea6-annotated_835943b0-b124-4a81-8f2d-6ef1470b38b3.png?etag=f78e87826c499a041c6fceaa9881a5fe)*

**Browser**: Chrome 103 (Android 12)
**Screen size**: 360x825
**Browser size**: 360x698
**[Open #532 in Usersnap](https://app.usersnap.com/l/feedback/53eedeff-983d-43b9-bd5b-52aa46e13949?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
