### ISSUE TITLE
[FEATURE REQUEST] Solucionar cuenta suspendida 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5647]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: Solucionar cuenta suspendida 
- ¿Qué problema resolvería eso para ti?: Mi cuenta fue suspendida no entiendo el porque 
- Share your Email or Discord so we can get in touch: alexcv2800@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/studio/ypp/dashboard

**Browser**: Chrome 103 (Android 12)
**Screen size**: 360x825
**[Open #140 in Usersnap](https://app.usersnap.com/l/feedback/6d8f216b-3282-4bbd-9717-1fdaa360ac6f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
