### ISSUE TITLE
[USERSNAP] Mi cuenta  YPP está suspendido ayuda porfavor 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5648]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Mi cuenta  YPP está suspendido ayuda porfavor 
- Houston, we have a problem.: Cuenta de  YPP suspendido 
- Your Channel and Account Details: alexcv2800@gmail.com
- Email or Discord handle for feedback: alexcv2800@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1166e53a-26ac-49c9-a51d-23dd46d09280-annotated_4b18dd85-4944-4c9b-b79a-c4226225ed5a.png?etag=0c489358d4bbd1eb2c7ec58982931da5)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1166e53a-26ac-49c9-a51d-23dd46d09280-annotated_4b18dd85-4944-4c9b-b79a-c4226225ed5a.png?etag=0c489358d4bbd1eb2c7ec58982931da5)*

**Browser**: Chrome 103 (Android 12)
**Screen size**: 360x825
**Browser size**: 360x698
**[Open #533 in Usersnap](https://app.usersnap.com/l/feedback/fcf7e342-2c54-491b-818d-22bdd07c4c7b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
