### ISSUE TITLE
[USERSNAP] I was contacted by an advertising agency that told me I would earn $5 for each video synced, but for some reason I have not received any payment from them, is it a mistake or have I been scammed?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5651]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: I was contacted by an advertising agency that told me I would earn $5 for each video synced, but for some reason I have not received any payment from them, is it a mistake or have I been scammed?
- Houston, we have a problem.: Payment for synchronized videos after registration
- Your Channel and Account Details: https://gleev.xyz/channel/48702?tab=Videos
- Email or Discord handle for feedback: denis.bdkk@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #534 in Usersnap](https://app.usersnap.com/l/feedback/fab408d4-9f5a-40c8-8635-fae34d5884a7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator in regards to rewards and payout schedule.
