### ISSUE TITLE
[FEATURE REQUEST] Payment for synchronized videos after registration

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5652]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- ¿Qué característica te estás perdiendo?: Payment for synchronized videos after registration
- ¿Qué problema resolvería eso para ti?: I was contacted by an advertising agency that told me I would earn $5 for each video synced, but for some reason I have not received any payment from them, is it a mistake or have I been scammed?
- Share your Email or Discord so we can get in touch: denis.bdkk@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/channel/48702?tab=Videos

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #141 in Usersnap](https://app.usersnap.com/l/feedback/ccbf8a95-f783-4ebf-a737-6501de959507?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that channel is still in gold tier and rewards for sync is still $5. Encourage creator to join our discord channel.
