### ISSUE TITLE
[USERSNAP] What the reason for my channel are suspended now??? Why?? Im daily upload to my youtube acc,, n not problem about that,, n my video are sync to gleev,, but why my accoust has suspended now??n why im not receive payment per week?? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5654]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: What the reason for my channel are suspended now??? Why?? Im daily upload to my youtube acc,, n not problem about that,, n my video are sync to gleev,, but why my accoust has suspended now??n why im not receive payment per week?? 
- Houston, we have a problem.: Account suspended
- Your Channel and Account Details: Shanty Yulianti, the email is Shantyuliaa@gmail.com 

**Browser**: Chrome 120 (Linux)
**Screen size**: 424x753
**[Open #535 in Usersnap](https://app.usersnap.com/l/feedback/90a7c350-a8e9-4514-ab53-e03cafa71b0c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier after re-evaluation.
