### ISSUE TITLE
[USERSNAP] que el retiro sea rapido y ya paso mas de 5horas

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5655]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: que el retiro sea rapido y ya paso mas de 5horas
- Houston, we have a problem.: realice un retiro y aun no llego
- Your Channel and Account Details: unloconetfree2539
- Email or Discord handle for feedback: ripiocristian12@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1093x615
**[Open #536 in Usersnap](https://app.usersnap.com/l/feedback/cff07f5b-f9a6-4751-aad1-eee7e88766e1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Notified the creator about the withdrawal duration and forwarded documentation outlining the withdrawal procedure.
