### ISSUE TITLE
[USERSNAP] I made a withdrawal on the date 27 Okt 2023, 20:04. My withdrawal is in progress, please process it immediately

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5656]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: I made a withdrawal on the date 27 Okt 2023, 20:04. My withdrawal is in progress, please process it immediately
- Houston, we have a problem.: Withdrawal is in progress
- Your Channel and Account Details: https://gleev.xyz/channel/32319?tab=Videos

Email : abilkhoiri744@gmail.com
- Email or Discord handle for feedback: abilkhoiri744@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6442b5e0-0f57-444c-a951-eb8375e17206-annotated_afd5162a-d196-448b-a53c-3c6d11bd9899.png?etag=a928b6bc455343fd130577f08801dc0e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6442b5e0-0f57-444c-a951-eb8375e17206-annotated_afd5162a-d196-448b-a53c-3c6d11bd9899.png?etag=a928b6bc455343fd130577f08801dc0e)*

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x780
**Browser size**: 360x648
**[Open #537 in Usersnap](https://app.usersnap.com/l/feedback/3a7a322d-37b8-4ff2-9060-e9570bde973b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Notified the creator about the withdrawal duration and forwarded documentation outlining the withdrawal procedure.
