### ISSUE TITLE
[USERSNAP] Im faching login problem dated 5th dec to still now ..please gleev team fix this my problem as soon as possible...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5660]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Expected Result: Im faching login problem dated 5th dec to still now ..please gleev team fix this my problem as soon as possible...
- Houston, we have a problem.: Not Login my account 
- Your Channel and Account Details: I&#39;m Bhagirath.. my channel H3LBOY-YT...
- Email or Discord handle for feedback: bhagirathapore@gmail.com

**Browser**: Chrome 107 (Android 12)
**Screen size**: 412x892
**[Open #538 in Usersnap](https://app.usersnap.com/l/feedback/29dbda3a-c5e1-4a9d-ab71-c6ca17ce8d7c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document for reference.
