### ISSUE TITLE
[USERSNAP] I was hoping to create an account and link the channel without any problem, but it seems impossible.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5661]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: I was hoping to create an account and link the channel without any problem, but it seems impossible.
- Houston, we have a problem.: I just registered and it won&#39;t let me log in, nor will it let me recover the account or link the channel.  Everything gives me error
- Your Channel and Account Details: gabo23062017yt@gmail.com 

https://www.youtube.com/@GaboGabitoYT_02
- Email or Discord handle for feedback: gabo23062017yt@gmail.com 

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1280x720
**[Open #539 in Usersnap](https://app.usersnap.com/l/feedback/90b5f47f-e699-477e-885f-8f2be4afd873?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
