### ISSUE TITLE
[USERSNAP] nice

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5662]
**Taken at**: https://gleev.xyz/legal/tos
**Fields**:
- Expected Result: nice
- Houston, we have a problem.: can&#39;t login
- Your Channel and Account Details: sulov5683@gmail.com
- Email or Discord handle for feedback: sulov5683@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 461x1024
**[Open #540 in Usersnap](https://app.usersnap.com/l/feedback/7c33dfa4-11c8-4f95-a678-253ff92fb597?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
