### ISSUE TITLE
[USERSNAP] Accept my account for join youtube partner program please

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5663]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Accept my account for join youtube partner program please
- Houston, we have a problem.: PLEASE ACCEPT JOIN YOUTUBE PARTNER PROGRAM 
- Your Channel and Account Details: irealofficial255@gmail.com
- Email or Discord handle for feedback: irealofficial255@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4628d292-aa08-483f-ad31-c1d3c244ff1f-annotated_9111df30-49be-4398-a3e2-5f9dff5ddb19.png?etag=bb86fc7f81ee7f0ef18b84acc93f6083)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4628d292-aa08-483f-ad31-c1d3c244ff1f-annotated_9111df30-49be-4398-a3e2-5f9dff5ddb19.png?etag=bb86fc7f81ee7f0ef18b84acc93f6083)*

**Browser**: Chrome 116 (Linux)
**Screen size**: 424x942
**Browser size**: 991x1869
**[Open #541 in Usersnap](https://app.usersnap.com/l/feedback/e6f89710-2a60-4f82-a4de-7171b518ab6d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
