### ISSUE TITLE
[USERSNAP] I expect a faster log in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5665]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: I expect a faster log in
- Houston, we have a problem.: Difficult to log in
- Your Channel and Account Details: archieariap@gmail.com
- Email or Discord handle for feedback: archieariap@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 384x857
**[Open #542 in Usersnap](https://app.usersnap.com/l/feedback/afe7d76b-ce45-48fc-bca6-f40091571a02?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Ask the creator specific problem when logging in.
