### ISSUE TITLE
[FEATURE REQUEST] I forget my password 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5666]
**Taken at**: https://gleev.xyz/ypp?referrerid=36209+8801750383469
**Fields**:
- Which feature are you missing?: I forget my password 
- What problem would that solve for you?: I forget my password and wallet seed please help me 
- Share your Email or Discord so we can get in touch: atikurrahmanzone@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/001ffd87-5b4b-46fa-af8f-abb7018de692-annotated_f3176d86-8559-41bf-95d4-adc32e5046db.png?etag=833714b4be2565e0e67ad10eb361f119)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/001ffd87-5b4b-46fa-af8f-abb7018de692-annotated_f3176d86-8559-41bf-95d4-adc32e5046db.png?etag=833714b4be2565e0e67ad10eb361f119)*

**Browser**: Chrome 120 (Android 10)
**Screen size**: 424x942
**Browser size**: 471x933
**[Open #142 in Usersnap](https://app.usersnap.com/l/feedback/0b5a36d3-8888-4c4c-9749-0458c6783a05?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
