### ISSUE TITLE
Idea: Designs for Changenow integration

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#5667]
# Background

We want to minimize the friction involved for users to use Atlas NFT and Creator Token features, despite not havin gJOY already. Today, we already give them some small amount of JOY, but this will not be enough for these more heavier features where you need to pay more, for this you would need to buy JOY. Of course, you can go to an exange, but that is a lot of hassle for a user, making an account, possibly ID checks, etc. Changenow (https://changenow.io/) is an example of a simple swapping service where, if you have crypto, like ETH or BTC or something else, you can easily just send it and receive JOY back, at least when we are integrated. Changenow also allows the reverse, namely cashing out from JOY to any other digital asset. Changenow also supports this for fiat, meaning you can connect your bank account/debit card, and while we don't know whether we will suppor this right away, it's something we should support at some point.

# Proposal

Review Atlas and propose designs for where and how this integration with on-off ramps for crypto and fiat can be introduced into Atlas for the benefit of users and creators.

**Comment by msmadeline** [comment]
@bedeho Hello! I finished designig some ideas on how to introduce the changenow integration into Atlas. 

➡figma file https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=2-513&mode=design&t=zHB1aRHk4YXkKulv-4

🎥Loom walkthrough https://www.loom.com/share/83e8e00653434d1fbd3410da04551cac?sid=afd5eb65-dc48-4722-bb56-9f851c3a954a

**Comment by bedeho** [comment]
# Changenow Integration Feedback

Thank you for this excellent overview, and I really appreciate that you went through and identified all the different places where JOY is being spent, it gives a great baseline for subsequent work.

# Feedback

1. Be aware that the token is called "JOY", not "Joy", so you may want to fix this in all current and future copy.
2. You did not explicitly say, but I assume the way the changenow dialog should work is that it's a sort of overlay with an almost solid dark background, similar to other overlays we have.
3. How does Changenow work, if at all, on mobile? Are you aware of that? How is does the design work and look there?
4. Be aware that in the version of Changenow we are launchign now, we will only allow users to buy and sell JOY for some other crypto, not for fiat using a credit card or bank account. This is because this costs extra, and we wanted to just try to get started and see how it works with just crypto first. This is a good place to start, because we still expect most initial users to be crypto native. This means we want to custmoize the Changenow widget to not show the credit card featues, which I think is the "Buy/Sell Crypto", but I'm not totally sure.
5. When we want to buy or sell JOY, we will need to provide the JOY account of the member to the Changenow widget, and I'm wondering if this is something that can be done programatically, so that when the user wants to buy "JOY" for example, they don't have to go and find their address in a new window and copy and paste it into the dialogue. Many people will fail here, and even more so if this is not actually explained, but ideally we don't need to even explain it.
6. As a continuation of the prior point about addresses, I think we are missing quite a lot about how the actual flow works in Changenow once the user enters it. What happens then? Do they have to KYC? Do they need to sign up to soemthing? Is there a delay at some point, if so how long? And what happens once success happens? And what happens if the user cancels? Should we be telling the user something after the flow ends, one way or the other? I think you need to dig deeper into the Changenow experience, and then educate us on what different experiences it creates, and also what room for customization we have?
7. As a continuiation of the prio point: Whenver we are creating an action for teh user in Atlas, we already know whether the user wants to buy JOY or sell JOY, so it would be very useful if it's possible to present a verison of the Changenow widget which only can do one or the other and has everything setup correctly for only this case. But this requires more reserach from you.
8. There are a range of actions that are so cheap that we will give you JOY for free from faucet to the user, and we do not want them to have to go and spend cash to be able to do. The canonical examples are creating a membership and channel, and publishing. Please collaborate with Radek (the lead developer on Jsgenesis) to identify such actions, removed the changenow injection from these flows. Here we should insted be giving the user additional free tokens. I don't know if we are actually properly detecting such cases where the user requires additional free funds, perhaps we need to tackle this in this same effort as integrating Changenow.
9. I think the explainer window for being out of JOY can be improved in a variety of ways to help the user understand what the problem is, and what the steps are:
   - Let's change title to: "You Need Additio"
   - Lets introduce an illustration which very directly illustrates the idea that you will be able to buy JOY with a range of other crypto currencies. There are many ways of showing such an exchange. We probably also want to introduce the Changenow brand somwhere here, to increase trust 
   - Lets add some additional points of information that:
      - no signup
      - no KYC
      - less than 30 seconds
      - supports +200 cryptos
   - Lets change label of buy button to something like "Buy JOY in 30s", or whatever the number is for fast checkout.
10. I think the notion of "Trade JOY" is too opaque. It does not exactly match the objectives of any user, and its sounds more like you are going to start speculating, that is buying and selling in a marketplace. In reality, most users either want to sell their JOY, that is cash out, or get more JOY, that is top up. I think it's better that we make our actions very explicit, with such plain names, so a distinct Buy JOY and Sell JOY will be better for our users, and then depending on what they choose, we open the widget with only this option.


On point 9: if the illustration takes time, or is not within your scope of experience, we can just postpone it for now, just add some placeholder to make more progress to allow developers to start working on it, and then we can contact an illustrator for this work.

**Comment by msmadeline** [comment]
Hey @bedeho I already did the second iteration of changenow integration. 

➡figma file https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=2-513&mode=design&t=pBBMywiqyyV5rtuC-4

🎥 loom walkthrough https://www.loom.com/share/c9a2557855754fc1a6fbcc302d22237d?sid=8501b4a7-652d-4bf6-b4f5-4560cf82c777

looking forward to your feedback!

**Comment by bedeho** [comment]
Excellent work, this was quite complex indeed, and I have a lot of points. I think we should review this together on our call tomorrow, to brainstorm what to do next, and make sure we are on the same page.

- I appreciate that its a not as easy of an experience as you perhaps wanted, but the fact that hte user has to go to another window, app or even device - depending on where they hold, was to be expectd, and something most crypto users will be fine with.
- I agree illustration is not needed.
- Remember that the user not having a wallet, or wanting to put JOY into some address from a wallet that they need to take a picture off, is not a use case for how Changenow is used in Atlas. Remember, we want to allow users to buy JOY for the purpose of using specifically in Atlas, which has a built in wallet. So these two cases (having no wallet, or having some wallet where they need to take a picture)  are not possible, and we should ideally remove these possibilities from the widget to reduce chance that user mistakenly tries this. Can you investigate whether this is possible? You should also remove these flows.
- What happens if user closes the window during the 10mins while waiting? How will they see the status of their purchase gain? For example, I guess it can fail, it can succeed, etc. I think the only way we can really solve this is if we add a new section to the member profile which shows a list of such purchases and sales, with results, status, date, etc. That way the user can review in the future as well. I also think perhaps we need to add email notifications, to tell the user the event happened? Is this possible for Changenow to notify our backend about?
- How do all the later screens work on mobile?
- I think we need to have the Changenow brand more directly in this experience, to increase trust, in particular on the very first slide (you need funds) - but not only there, so people understand there is reputable third party who is faciliatting the transaction.
- In terms of video, I think this is something we can consider adding, but we have to design as if most people will not watch it, and that it should not be required.
- Is there any reason you do not show the stage indicators (1, 2, 3) from the very first screen? I think if possible, this is much better, because it gives the earliest possible indication to the user what the steps are tehy need to get through.
- I think the steps (1,2,3) need to be above or too the left of the content, that is the typical place they are placed so as to avoid people missing them.
- I don't think I understood whether all of this has to be in a new window, or if we can do it all in the same original window? I'm assuming everything is in the same window belo.
- I find it strange that we can customize this much on the first screen, for example you are even add a link (How to buy JOY) are you sure this is possible? Please help me understand this, perhaps in a meeting.
- I find it strange that the first screen can be customised so deeply, but all the other screens cannot? They all look pretty chaotic and poorly done, so this is why I'm asking.
- Are you sure it's not possible to prepopulate JOY address? because it seemed to be so customizable. If not, then I think your solution of showing it on screen is a very good idea, but I think we need to give it even more space, so its not missed.
- Is it possible to prevent he user from changing JOY as received currency in drop down? This would be better, to give user fewer options, less room for misunderstaning.
- Is it possible to skip the whole "Start new exchange" and just show our own success screen and then send usre back to normal Atlas stuff?
- I agree we cannot say 30seconds if that is not true. lets just make the taglines
  - "No signup"
  - "no KYC"
  - "Supports +200 ..."
- I also liked the approach you suggested with the extended menu, it's cleaner. Lets rename to "Transfer JOY". The menu does get a bit long, and I'm not sure waht exactly is the optimal ordering of items for a user, in terms of what actions are used most frequently, but its worth trying.

**Comment by msmadeline** [comment]
Hello @bedeho I created a "Transactions" section in Atlas so the user can see all of the transactions they have made and their status. I did this section in a portfolio page instead of doing it in the membership profile because that way it is not public for viewers and I think this section should be private. 

➡figma file: https://www.figma.com/file/VvWuJfHYpOPFQrcDVAeHkT/Portfolio?type=design&node-id=2205-11044&mode=design&t=IyQCXn7oeWbkuTBM-4

**Comment by bedeho** [comment]
- I do not think this information belongs under the portfolio, at teh very least in the same place of the informatino hierarchy as tokens and nfts, because these two are the fundamental ingredients of what a portfolio is about: what you own. I think also we should not refer to these Changenow buys and sells as "transactions", because that term already is undrstood to primarily means transactions on the blockchain, so it may confuse people as to what they are seeing here, they may expect a comprenehsive overview of all transactions on the blockchain involving this user address. I think instead we should make this entire section its own page. We link to it from the top level menu, and we call it something like "ChangeNOW Dashboard", using their logo as icon or something. 
- I don't think we need to separate pruchases and sales, the basic information we need in both cases is the same, and I don't think anyone will do so many of both that they would benefit from having them separated. I think we need the following, in this order
   1. DATE: date when changenow order was triggered
   2. STATUS: this is same as your current status field, but I think we need a case for when the failure involves a refund. I think we need to prepare an exhaustive list of status indicators here, and make sure we have covered all cases the API may tell us about.
   3. SENT: value sent to changenow, must include currency, which in the future may be dollars if we allow fiat. When it is not fiat, we should include fiat value of the value sent at the time.
   4. RECEIVED: value changenow sent back, must include currency, which in the future may be in dollars if we allow
- I belive the page needs something that explains that it is the place recording all pruchases and sales with Changenow. Like a header of some kind.
- I believe we need an empty state for the table which explains what is shown there and why its currently empty.
- Lets drop the filters for now.
- What menu are you planning to show that opens when the three dots in the right hand column are clicked.

**Comment by msmadeline** [comment]
Hello @bedeho I did another iteration of changenow integration ✅

Loom video: https://www.loom.com/share/e3986815578742f5bde9431f30b48c0b?sid=5b2d0783-f8fb-43ac-a41a-10377bebf886

Buying/Selling flows: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=182-63536&mode=design&t=uN1auSXx1bt8VkYz-4

Mobile demonstration: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=197-63110&mode=design&t=uN1auSXx1bt8VkYz-4

**Comment by bedeho** [comment]
# You need additional funds

I am here referring to

https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=8-12997&mode=design&t=Zc3RE7kFVXWzt9Ka-4

I think on this page we need to do a better job of encouraging the user to try this, right now it's overall too scary and feels like you may have hit a dead end. Something happened that you did not expect, and now there is a sign icon, call to action and lots of small text.

- I also got confirmation from Changenow that a trade takes 2-3 minutes, I think this is short enough that it's worth informing people, so lets add it as the third point in the list, with speed icon of some kind, and copy "Takes 2-3 minutes." 
- Please update title to someting like "Buy JOY". This is a more positive framing, rateher than focusing on failure. The subtext explains why you have to.
- Please update the copy here to not refer to selling. In general try to be a bit more careful to make copy as good as it can be, even though it is easy to change. 
- Let shorten copy of all cases, 
   - "No signup"
   - "No KYC"
   - "Only 2-3 minutes"
   - "200+ cryptos accepted"
- Can we make both copy and icons larger? I don't think they need to be this small

# Buy & Sell Crypto

I am here referring to 

- buying: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=87-41520&mode=design&t=Tl8aeCpDHmTNqaUn-4
- selling: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=87-41668&mode=design&t=Tl8aeCpDHmTNqaUn-4

In each case, change the title to "Buy JOY" and "Sell JOY".
Let us also make this much more similar to the "You need additional fudns", in that we should highlight how easy thsi is going to be. Let us drop the video link for now, I don't think enough people will open it, and for everyone who does not, it just adds clutter to the scene by competing with the key CTA.


# Changenow Dashboard

- Lets relocate the changenow icon to the right hand side of the screen, on the same level as the main title, right now its getting quite crowded
- Lets call this entire dashboard the "Swap Dashboard", as Changenow is something people don't understand as abrand or concept, as clearly as the idea of swapping. Lets change subtext to: "This dashboard shows the history of current and past swaps."
- Why do we need "Cancelled"? If the user closes the exchange widnow on step 1 or 2, then there is no need to keep a record of it, nothing was really done. If the user closes window on step 3, then you really cant know if they actually intended to cancel, or if the money was actually still sent using some other crypto wallet, if they are     
- Where are you getting tehse STATUS values from in general? I don't think this is what the API provides. Please let me know, and if it is not informed by what the underlying information the API provides, then you have to adapt it to that, and stay within those limits.
- Empty state looks good, just rename "transactions" to "swaps".
- Please give the  "details" page a proper top heading which is bigger than the section heading, call it "Swap". Also, is the information you are hsowing here informed by what the API from ChangeNOW actually provides?
- I think for now, drop the dollar amounts from SENT/RECEIEVEd, because for this to make sense we really need the exchange rate of each currency at the point in time of each swap, and that will be slow and just too muche hassle to cram into this release, it's not important enough for now. 

# Exchange Crypto - buy

I'm here referring to: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=195-66714&mode=design&t=W3dZR7nzIxMiBh2V-4 
   
- I had to think a long time about this stepper. I fundamentally think its very important to communicate to the user where they are in the process, and how long until its over. For a new user, this is key to reduce dropoff along the way. At the same time, I want us to to get too caught up about small tweaks now, and so since there is a lot to do, and this may need design tweaks in the future, just dropping it is OK.
- The title should reflect the user action, so "Buy JOY" is way better than "Exchanee Cryptp".
- For all screens, rename "Go back" to "Back".

## Step 1

- Do we have a design for a drop down which can show an ICON? Do we have a drop down that works well with 200 different alterantives? Please show interaction for how this will look when clicked. Remember that longest token names can be quite long.
- Is the user supposed to be able to enter a value in both "send" and "get" fields? where updating one updates the other?
- I think we also need to fetch new exhange rate pretty frequently on this page, as underlying fprice changes a lot. How should this be dealt with in the UI?
- "You send" => "Send"
- "You receive" => "Receive"
- Drop refund address: we jsut send back to their account

## Step 2

- "Exchange" => "Swap"


## Step 3


- What is "Exchange ID", whatever it is, it should not be as prominent as it is, it should be the last thing shown. If this value is so relevant as to bea dded here, then probably it should be part of the dashboard as well?
- The call to action here looks like a sort of error, and it drowns among all the other information. Most crypto native people will not be confused, because they are used to it, but in actuality I think this is not giving enough emphasis to what the person is supposed to do next.
- I assume "awaiting deposit" is something that waits for the funds of the user to be arriving. Does the changenow give any more granular status here? because it could distinguish between states like: user transaction not seen, user transaction found, doing trade, sending user funds, something like that. Because since the total process can take 2 minutes, giving some sort of updated indicator of how things are progressing during this long, nervwracking, wait, would be highly benefitial. After all, the user has sent their money out into the world and is wondering what, if anything, is coming back.

- I think this success screen is too technical, all the user really wants to see is some sort of celebration that it worked, and then go back to the app. They can later see all of this information in the dashboard anyway.


# Exchange Crypto - Sell

I'm here referring to: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=195-66717&mode=design&t=W3dZR7nzIxMiBh2V-4

Points I make above pretty much in all cases here also, in addition the below.

## Step 1

- Drop refund address: we jsut send back to their account
- We need some way to block user if they input an amount of JOY they do not have. Do we need to say what account we are sourcing JOY from?


## Step 3

- This step does not make sense? Why would the user here see this screen, please think again what is supposed to happen here.

**Comment by msmadeline** [comment]
Hey @bedeho I did another update of the changenow design with your feedback implemented. Looking forward to your feedback✅

🎥Loom video: https://www.loom.com/share/a1e9860218a04e63ba8eb4aaa3b978f6?sid=0136525f-6682-400c-b819-134e090b0e26

➡ Currency dropdown https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=273-278199&mode=design&t=t43AfBXygqZC6r6A-4

➡ Stepps loader https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=265-227981&mode=design&t=t43AfBXygqZC6r6A-4

➡ Estimated Rate design https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=281-443737&mode=design&t=t43AfBXygqZC6r6A-4

**Comment by bedeho** [comment]
# Intro

Great work, there is a lot going on here, and you are handlign it very well, takes me a long time to properly review because it is so broad.

I want to encourage you to try to make sure the copy you use, even on designs which are early stage, is as accurate as possible. When labels are just copied and clearly incorrect, it causes confusion on my end as to whether you have just made a mistake, or if something has been misunderstood or miscommunicated between us. If any mistake you have here is just a mistake, then I guess its fine, but if you just did not update them, then try to do so going forward.

# Currency Picker 

This looks great, not sure why the horizontal placement of the dropdown is different for buying and selling, I don't see an obvious reason for this.  

# Stepper

- I disagree that not showing how many steps there are in total, and how far along the user is, is not needed. We do not need to show the text description of all future steps, that is too much, and the user will anyway not read them, but indicating progress and remaining steps in an unfamiliar journey is very worth while.
- Why is the first step in the stepper "awiating deposit"? The whole point of the stepper is to give the user who is about to contemplate whether they should bother with this process or not, an indication of what it will entail and what steps are involved. This means its actually earlir in the flow that its most valubale to have this, compared to later,because when someone has already comitted to a few steps, they are probably likely to persevere. So I think the stepper really should be on the earliest possible screen the user is confronted with this decision, namely https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=8-12997&mode=design&t=q5nbWN5K79aaWLwa-4.
- Both your proposals for the stepper vs. just showing the current stage has a flaw in that you are showing a spinning circle for steps where it is not appropriate. This is because the spinning circle is reserved for cases when one wants to tell the user that they have to wait because some other process is ongoing. It is not used to tell the user that the app is waiting for the users input. So "awaiting deposit" is an example where the app is waiting for the user to send a transaction, and since the app cannot know exactly when the user has sent it - before it is detected, the app should just be standing idle. We could do slightly better by just having a button the user can click when they have sent transaction, called say "Deposit Sent", and then on the next stage we could await deposit. 
- In the stepper designs you appear to be showing the same deposit screen for all stages, even though we are past the deposit stage. This does not really make sense. The main surface area is mismatching with what the user is actually doing. This main area should change as we are progressing. I think part of the problem here is that you have turned the stepper also into a spinner. It would make more sense to just have the stepper just be a progress indicator, and then the main content area of the window can hold spinner, a deeper explanation of what is going on (e.g. on Confirming you can say we have seen your transaction ) and success indicators when transitions are made. For example the last step: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=88-41978&mode=design&t=pILqfMFzMv4iZemQ-4, that should just be a part of the normal flow, where teh stepper has all 4 steps completed, the main content area just shows the success message.

# Fee estimation

Estimated rate prototype is fine, but I think perhaps putting in some text which says "fetching new rate", so peope know what is going on, as it also may be deale


# Buying Flow

- Just so you know, Changenow supports over 900 cryptos, not 200 like I originally thought.
- Let us not have this sort of alert about only supporting crypto. There were no promises up front that specified that fiat would be possible, so no need to address it, also, most users will have crypto still, so we will just be making the UI more noisy for the majority of users for limited benefit to anyone. 
- One thing we have overlooked, in both sell and buy flow, is to make the user accept some terms of service at some stage. I think it makes most sense to have it be a checkbox in the very final screen before the trade is executed, which I believe is here: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=87-41824&mode=design&t=Qe0I2qhGgrh3fGRX-4 . It should be really obvious to the user they need to check it off. Not sure if its best to disable swap button until its checked, or have some error indication in the UI when the user clicks it and the checkbox has not been checked. We must link to the terms which can live on some external page like gleev.xyz/swap_terms, which can just be opened in a new browswer window.
- I agree that allowing user to adjust both inputs, but I think we need to deal with two issues here. First off, people often mistake whether they should input "."  or "," as decimal point, so by picking som reasonable default value, we can alreay have populated this for them, to avoid the confusion. In fact, I think it can make sense to pick some value informed by what the user is trying to do. If they just wanted to buy from dashboard, then perhaps just targeting some dollar amount like 50 USD makes sense. Also, picking ETH as default other currency is a good idea. The second problem is that we need error handling on the user inputs. For example if the user inouts an invalid value in the field, like "blabla", or a value which is too large for what changenow allows. In which case the UI message should clearly inform the user what the actual max is, so they dont have to keep guessing by putting in random numbers. Pusihng "Next" should not be possible during such conditions.
- CTA on screen to send payment is just too small, it drowns. Make is shorter and bigger, just "Send funds to address below".
- What happens if the user ends up sending less or more funds than what they selected? will the trade fail, or is it just executed with same fee? If it fails, how will we tell the user that?
- What happens if the fee in the market changes from what the user accepted, for example if there is volatility in the mraket, or if they waited for too long. Will the trade fail? if so, how do we tell the user?
- Keep in mind that the user does not need to actually go to another window when sending transactions, so I would change this in the documentation. For example, the user may be just sending from their phone or something. So its better to repalce this with just a screen that says user sends funds.
- How will transition between each step be presented? is it instant or is there some sort of animation or something, so user clearly sees one tsage is finishing and next is beginning.
- Swap completed screen should just have action "Finished" as action, no "Go back to dashboard", because we should just send user back to wherever they were when they launched the flow, whether that is on a particular video or dashboard or somehwere else.


# Selling Flow

I mean this flow: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=113-42770&mode=design&t=Qe0I2qhGgrh3fGRX-4

- Remember that when inititating the swap when selling, we are sending money from the account of the user, so that means they will need to sign something, this means you need to have a stage for that which is before the awaiting deposit waiting stage. 
- I don't understand why the stage does not have all the same stages? It should surely also require changenow to wait to see our transaction, wait for it to be confirmed, wait for it funds to be swapped on the backend, and then finally wait for funds to be sent and confirmed on our cashout chain of preference?
- Remember that all my remarks above about the use of the stepper apply equally here as well in the selling flow. The only difference I am aware of is taht perhaps the  
- I don't really understand why you introduced a special "waiting for changenow" content when selling, but this is not part of the buying for the exact same stage? At best perhaps you have not documented fully? Either way, lets try to keep what can be the same, the same.

# Changenow dashboard

- I think we do need to show more of the states actually, at least starting from "confirming", becase in this state, if the user is interrupted for any reason, they should find some representation of their swap somehwere, otherwise they have sent money out, but there is no trace of where it is or what is going on.
- Can you please add tooltips to the status indicators in the dashboard, because when the user reads something like "Verifying", they will not undrestand what this is. In fact, perhaps we should also just pick better names than this, we don't have to use the same name the API uses in our UI.
- In swap window, just drop "info" in the titel of each section. Info is also not really a proper word, and in the UI we should only use english words, so in this case it would be "information", but I don't think we need it in this case.

# Drop down menu

Here: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=177-58389&mode=design&t=q5nbWN5K79aaWLwa-4 

Just use section dividers, no titles at all, I think that is the simplest for now, as this menu will keep evolving.

**Comment by msmadeline** [comment]
Hey @bedeho I have a few matters that I wanted to clarify now after I analysed the feedback. It's about the stepper

- First I wanted to ask you If you really think that adding a stepper on a really early stage is a good idea? It is completely unnessecary in my opion and very confusing. It could be even discouraging for the user as they will see so many steps ahead of them at this point. I think in the "You need additional funds" modal the only needed information there is that they need to buy JOY in order for them to proceed with some kind of action  and information that they can do it quickly with changenow. We don't want the user to think too much about making the decision to buy JOY

- When it comes to the actual steps. Making the user click some kind of button to start the stepper to progress is in my opion an unnsessecary step that could make a lot of problems. What If the user click the button too early or forget to click the button? If they did the transaction and did not click the button the transafction is gonna process anyway  by changenow but on our end the user will be stuck in a modal that is not progressing which will be confusing. I think adding the button will just complicate things when intstead we want to simplyfy it. It better in my opinion to do it automatically in a way where the stepper is progressing by itself and changing after user does the transaction. 

- The steps are actually provided in the API so maybe we can keep them as they are but of course we can change the look of the stepper so delete the circle that is loading and maybe change the name of the step for example "Awaiting deposit" - "Waiting for transaction" etc. then it will be more clear for the user about what is going on but we wouldn't complicate too much 

- Also after thinking a little bit about the two modals "Selling JOY" "Buying JOY" ( they appear when the user click on a buy JOY button or sell JOY button anywhere in atlas) maybe we can just skip it and display the buying / selling JOY flow automatically without them? it will reduce the amount of steps. It was a sudden thought so let me know Wdyt :)

**Comment by msmadeline** [comment]
Hey @bedeho I've implemented your feedback. Let me know what you think

🎥 loom: https://www.loom.com/share/c4adb71f2536450984008743bb1d4b0a?sid=c55a7338-1720-4d62-ba50-c7a9c3be30ab

➡ figma file: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=2-513&mode=design&t=MONGf4SKHHIRYzvH-4

**Comment by bedeho** [comment]
# What should be first modal when user clicks Buy/Sell?

I understand what you mean here. My guess is that if the user is quite sure they want to buy joy, perhaps they have already used the flow before, then having the extra screen will not discourage them so what, we could even have it so that its onl shown the first time or something if we wanted, but in a sense the cost is not so big. However, if the user just trying to click the buy button for the first time, for example while exploring or learning, then this screen can be very valuable, helps them understand the benefits. Perhaps they dont even execute the trade on the first time, but they have it in the back of their mind.

I don't have a strong opinion here, so you decide, but I would actually guess its best to keep overall.

# Add Buy/Sell to main menu

Thinking about the prior point made me realise that this action of buynig and sellling is actually much more important than the space we are giving it in the app currently. Strategically its very valuable for us for people to see that they can do this, and right now you have to go to a very specific screen, open a specific tab (tokens), press a very small button and open a small menu to see the action. For example, if you are a creator with a balance, its not so obvious to you that you can cash out with changenow unless you accidentally go to the right place.

For this reason I suggest adding buy & sell as two primary actions to the drop down menu under the membership as well.

# Renaming

- Can we in all places in the app rename  "sell" to "Cash Out" and "buy" to "Top Up", this is just much simpler for people.
- Lets on the swap screen rename "Send" to "Paying" and "Receive" to "Receiving"
- "Waiting for your transaction" => "Awaiting payment"
- "Confirming" => "Confirming payment"
- "Sending to you" => "Sending funds"

# User sends funds

Here I was initially confused about the role of this screen https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=486-293189&mode=design&t=ajEpc8CCDBFz6tJ0-4, but I think we agreed on the call that it was not needed, and we can just jump to this screen directly https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=445-236799&mode=design&t=ajEpc8CCDBFz6tJ0-4.

# Add TXIDs, scrap everythign else

For all screens where changenow has detected your transaction, lets scrap the "amount sent", "amount to receive", "estimated rate" ..., all of those are no longer relevant for the user to do anything wiht. Instead, we really only need one thing that the user _may_ be interested in, this is the transaction id. This ID allows users to use a block explorere, such as joystream.subscan.io, to watch what is going on their transactino on the blockchain. This ID should be available from changenow. It is a long hexidecimal string, so you don't need to show the whole thing, and it's useful to ahve a sort of "copy" button that the user can click to copy the ID into their clipboard. It would also be useful to show the transaction ID of the transaction that changenow is sending to the user, again if changenow makes it available to us. You can check with Radek about this. If we are able to show that also, then you need to distnguish the two IDs, so perhap call them "Your Payment Transaction ID" and "Changenow Transcation ID"

# Error handling on amount on swap screen

If I understood your comment here https://www.loom.com/share/c4adb71f2536450984008743bb1d4b0a?t=591&sid=13f1fbaf-2001-4b82-a572-a3dbdefa98fd, you are asking whether we should have the red alert messageon both boxes, or just one? I think just having on the top one is sufficient. I agree we should block any value except digits and comma, also pasting in any string with invalid values should not work.

# Transitions

Looks smashing, nice job!

# User sending less funds

OK, I will ask.

# Sell JOY flow

- Remember that this screen https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=432-144662&mode=design&t=ajEpc8CCDBFz6tJ0-4, is for waiting for the transaction to be included in a block in Joystream chain, for that block to be finalized, and for Gleev indexing infrastructure to process this block. You don't need to understand exactly what these steps are, but suffice to say that these steps have nothing to do with when changenow sees the transaction or considers it confirmed. For this reason I suggest you skip this screen and just go straight to a new screen where we are waiting for Changenow to detect the transaction. Here again we should show the TXID for this, and we get it now from our internal Atlas wallet which is constructing and signing the transaction (not from Changenow like we did when buying). Then when changenow sees it, then we go to the confirming screen, as you have designed here: https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=113-44785&mode=design&t=ajEpc8CCDBFz6tJ0-4 

- When the user is to send the funds, after that we can go straight to waiting for it to be confirmed using the nroam

**Comment by msmadeline** [comment]
@bedeho Hey, I implemented your last feedback.

🎥 quick loom video https://www.loom.com/share/9297682e61bf4ce897cb4ebd36865de0?sid=49218860-2586-42c2-a2d9-789f88d57053

➡ figma file https://www.figma.com/file/SmId6AkqNYU8zo70yRU36U/Changenow-integration?type=design&node-id=2-513&mode=design&t=VhHzyRDbQIMxipYk-4

**Comment by bedeho** [comment]
- great job!
- member drop down looks really smashing!
- ok, we can change it back to buy/sell since you have thought more about it.
- Its called "Transaction ID" not "Exchange ID".
