### ISSUE TITLE
[USERSNAP] Not sign-up   my account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5668]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Not sign-up   my account 
- Houston, we have a problem.: Please  Sign-up  my channel ,,, 
- Your Channel and Account Details: mdnaeym080@gmail.com
- Email or Discord handle for feedback: mdnaeym080@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 400x889
**[Open #543 in Usersnap](https://app.usersnap.com/l/feedback/c489f836-9ea3-4dec-9332-4ed43e35f2d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
