### ISSUE TITLE
[USERSNAP] Please unlock channel suspension 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5670]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Please unlock channel suspension 
- Houston, we have a problem.: My channel is suspended
- Your Channel and Account Details: Email: enabm913@gmail.com
- Email or Discord handle for feedback: enabm913@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x851
**[Open #545 in Usersnap](https://app.usersnap.com/l/feedback/014b3d09-85ae-493e-904b-564b0f52989f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
