### ISSUE TITLE
[USERSNAP] Please unlock channel suspension 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5671]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Please unlock channel suspension 
- Houston, we have a problem.: My channel is suspended
- Your Channel and Account Details: Email: enabm913@gmail.com
- Email or Discord handle for feedback: enabm913@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/93f219b6-aeb1-4be6-a989-94bc190b4c3d-annotated_ac0e0842-c0e4-4fc5-ab8b-c1fbbecdb049.png?etag=32e3577491164f49342c3a4670a29c3e)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/93f219b6-aeb1-4be6-a989-94bc190b4c3d-annotated_ac0e0842-c0e4-4fc5-ab8b-c1fbbecdb049.png?etag=32e3577491164f49342c3a4670a29c3e)*

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x851
**Browser size**: 393x776
**[Open #546 in Usersnap](https://app.usersnap.com/l/feedback/97e81704-37a7-40b1-81d2-bb84c799b00f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
