### ISSUE TITLE
[USERSNAP] Need to gleev support to change my password 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5673]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Expected Result: Need to gleev support to change my password 
- Houston, we have a problem.: Getting error to change password
- Your Channel and Account Details: Bhagirath Pore/ bhagirathapore@gmail.com
- Email or Discord handle for feedback: bhagirathapore@gmail.com/ discord-bhagirath009

**Browser**: Chrome 107 (Android 12)
**Screen size**: 412x892
**[Open #547 in Usersnap](https://app.usersnap.com/l/feedback/f9f4bd48-e8c8-456b-b401-ca0e845c2c7b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document for reference.
