### ISSUE TITLE
[USERSNAP] espero la sincronizacion y un rango superior ya que mi contenido es original

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5675]
**Taken at**: https://gleev.xyz/channel/49024?tab=Videos
**Fields**:
- Expected Result: espero la sincronizacion y un rango superior ya que mi contenido es original
- Houston, we have a problem.: mi canal no sincronizo los videos de youtube en gleev, adicional mi contenido es totalmente original nada de derechos de autor uq epuedo hacer ?
- Your Channel and Account Details: Id elCONTERTULIO correo juanpipe2014dbz@gmail.com
- Email or Discord handle for feedback: juan.parrao@cun.edu.co

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #548 in Usersnap](https://app.usersnap.com/l/feedback/826721b9-7dc0-4b40-86c5-9201b0be92ae?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
