### ISSUE TITLE
[USERSNAP] neden askıya alındıgım ve nasıl çözüme ulaştırabilecegimi söylemeniz gerekmekte 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5676]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: neden askıya alındıgım ve nasıl çözüme ulaştırabilecegimi söylemeniz gerekmekte 
- Houston, we have a problem.: askıya alınmış
- Your Channel and Account Details: Miztape
- Email or Discord handle for feedback: 12.4unalbey@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #549 in Usersnap](https://app.usersnap.com/l/feedback/5d712675-cdd8-4f22-8176-05c5dcb66bc5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
