### ISSUE TITLE
[USERSNAP] Registré mi canal de YouTube con 200k de suscriptores y no me deja entrar. Ni con la semilla, ni cambiando de contraseña.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5678]
**Taken at**: https://gleev.xyz/channels
**Fields**:
- Expected Result: Registré mi canal de YouTube con 200k de suscriptores y no me deja entrar. Ni con la semilla, ni cambiando de contraseña.
- Houston, we have a problem.: No puedo iniciar sesión 
- Your Channel and Account Details: Mi canal de YouTube es: PlayStar, tiene 200k suscriptores.
- Email or Discord handle for feedback: edgar.vargasvazquez09@gmail.com

**Browser**: Safari 17 (iOS)
**Screen size**: 414x896
**[Open #550 in Usersnap](https://app.usersnap.com/l/feedback/7b967fe3-6bd8-4f65-af77-f1296a6e9363?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
