### ISSUE TITLE
[USERSNAP] Que me agregaran mi saldo en Token joy

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5681]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Que me agregaran mi saldo en Token joy
- Houston, we have a problem.: No me agregaron mi pago el 19/12/2023
- Your Channel and Account Details: Krfinanzas 
- Email or Discord handle for feedback: Lachelcha123@gmail.com

**Browser**: ChromeiOS 117 (iOS)
**Screen size**: 414x736
**[Open #552 in Usersnap](https://app.usersnap.com/l/feedback/9f553639-a343-495d-b4fa-2a15f7d5dfe2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards that it was settled and provide more information for bronze channel.
