### ISSUE TITLE
[USERSNAP] I have been on this platform for 3 weeks, I have the GOLD rank that should give me 5$ for each sync, the problem is that in all that I have been on the platform I have not been paid anything, not even for a single sync, I ask to fix the bug a...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5682]
**Taken at**: https://gleev.xyz/channel/48702?tab=Videos
**Fields**:
- Expected Result: I have been on this platform for 3 weeks, I have the GOLD rank that should give me 5$ for each sync, the problem is that in all that I have been on the platform I have not been paid anything, not even for a single sync, I ask to fix the bug and pay me for all the past syncs.
- Houston, we have a problem.: I was not paid a single synchronisation - DeN Contrast
- Your Channel and Account Details: https://gleev.xyz/channel/48702?tab=Videos
- Email or Discord handle for feedback: denis.bdkk@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #553 in Usersnap](https://app.usersnap.com/l/feedback/9659ea2b-1322-40ff-9a43-69ae7e5d0400?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator in regards to sync rewards and requirements and payout schedule.
