### ISSUE TITLE
[USERSNAP] No me llego mi pago

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5683]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: No me llego mi pago
- Houston, we have a problem.: Nunca me llego mi pago
- Your Channel and Account Details: jahch94@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 412x915
**[Open #554 in Usersnap](https://app.usersnap.com/l/feedback/cff2dd1b-7290-4ac7-96a3-b82e4a9ec5aa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
