### ISSUE TITLE
[USERSNAP] Hlw sir when i  want to see my channel balance its loding i can't see my channel balance and withdraw 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5688]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: Hlw sir when i  want to see my channel balance its loding i can&#39;t see my channel balance and withdraw 
- Houston, we have a problem.: Balance cheack proboem
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFBwY2125x4cxv3jAruZtS
- Email or Discord handle for feedback: tauhideahmedtarik350@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/06fd8650-4b1d-4123-89a4-769ad9179e1d-annotated_7931821c-cd50-4ddf-b1ab-b7a9d74fd9e4.png?etag=d1b142bef3017f1b67134c3fcb4c7174)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/06fd8650-4b1d-4123-89a4-769ad9179e1d-annotated_7931821c-cd50-4ddf-b1ab-b7a9d74fd9e4.png?etag=d1b142bef3017f1b67134c3fcb4c7174)*

**Browser**: Chrome 120 (Android 10)
**Screen size**: 351x782
**Browser size**: 351x688
**[Open #555 in Usersnap](https://app.usersnap.com/l/feedback/26606f27-9e42-4f04-bcaa-7418b3f41394?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
