### ISSUE TITLE
[FEATURE REQUEST] I have no videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5690]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: I have no videos
- What problem would that solve for you?: Video
- Share your Email or Discord so we can get in touch: Shikderrayhan461@gmail 
- Your Gleev channel ID or Title: Shikder rayhan

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2190f7d6-4b75-45c5-9fa1-e3faaab22259-annotated_cbc15709-771c-4ea3-81c3-0da89f0febe6.png?etag=b9a47b5422947e4764f4cae5eb88427b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2190f7d6-4b75-45c5-9fa1-e3faaab22259-annotated_cbc15709-771c-4ea3-81c3-0da89f0febe6.png?etag=b9a47b5422947e4764f4cae5eb88427b)*

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**Browser size**: 393x767
**[Open #143 in Usersnap](https://app.usersnap.com/l/feedback/71b62995-0557-44a6-b11d-b14778bc5c62?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
