### ISSUE TITLE
[USERSNAP] Logging

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5691]
**Taken at**: https://gleev.xyz/channel/28936?tab=Videos
**Fields**:
- Expected Result: Logging
- Houston, we have a problem.: Can&#39;t log in
- Your Channel and Account Details: enebongnahum2@gmail.com
- Email or Discord handle for feedback: enebongnahum2@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x800
**[Open #556 in Usersnap](https://app.usersnap.com/l/feedback/914e99a3-ab21-469d-a961-2a8e139e4814?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
