### ISSUE TITLE
[USERSNAP] ödülümün yatması

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5692]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: ödülümün yatması
- Houston, we have a problem.: kaydoldum fakat ödül yok
- Your Channel and Account Details: ozbekmehmet3871@gmail.com  @historicaldepths
- Email or Discord handle for feedback: ozbekmehmet3871@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #557 in Usersnap](https://app.usersnap.com/l/feedback/f1352b56-009e-4695-a760-ef37f359f8fd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
