### ISSUE TITLE
[USERSNAP] Esperaba una respuesta de porque esta suspendida mi aprobación si es un canal autentico y cumple con todos los requisitos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5693]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: Esperaba una respuesta de porque esta suspendida mi aprobación si es un canal autentico y cumple con todos los requisitos
- Houston, we have a problem.: Estado de aprobación suspendida.
- Your Channel and Account Details: Enzofernandux
- Email or Discord handle for feedback: inmenzofernandez8@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1280x768
**[Open #558 in Usersnap](https://app.usersnap.com/l/feedback/b400f2a9-c77d-4a8f-a26d-51f6712aa5cb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
