### ISSUE TITLE
[USERSNAP] Quisiera saber porque no me habilitaron el canal, no me dijeron ninguna razon y estoy buscando la manera para que evaluen otra vez? solo me pusieron suspendido. Tampoco puedo entrar al discord para escribirle al soporte. Tengo creadores para ...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5694]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Quisiera saber porque no me habilitaron el canal, no me dijeron ninguna razon y estoy buscando la manera para que evaluen otra vez? solo me pusieron suspendido. Tampoco puedo entrar al discord para escribirle al soporte. Tengo creadores para referir pero ni siquiera me habilitaron a mi, como voy a traer mas gente?
- Houston, we have a problem.: Suspendido
- Your Channel and Account Details: Enzofernandux
- Email or Discord handle for feedback: inmenzofernandez8@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1280x768
**[Open #559 in Usersnap](https://app.usersnap.com/l/feedback/dc9d2787-3c32-40d9-bc41-9f20478f21c5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that the channel is verified under bronze tier.
