### ISSUE TITLE
[USERSNAP] gleev hesabımı silmek istiyorum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5697]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: gleev hesabımı silmek istiyorum
- Houston, we have a problem.: hesabımı silmek istiyorum 
- Your Channel and Account Details: gleev hesabımı silmek istiyorum 
- Email or Discord handle for feedback: cesurcotkar363@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**[Open #560 in Usersnap](https://app.usersnap.com/l/feedback/ea9bfb9d-4994-45c3-a6f5-634a7e9366d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Asked the creator the reason for gleev channel deletion and provided the link of our communication channel.
