### ISSUE TITLE
[USERSNAP] Eklediğim iki kanalı silmek istiyorum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5698]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Expected Result: Eklediğim iki kanalı silmek istiyorum
- Houston, we have a problem.: Eklediğim iki kanalı silmek istiyorum
- Your Channel and Account Details: Eklediğim iki kanalı silmek istiyorum
- Email or Discord handle for feedback: cesurcotkar363@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**[Open #561 in Usersnap](https://app.usersnap.com/l/feedback/2a70f273-c960-4c35-a717-e0ef996e06c1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
