### ISSUE TITLE
[USERSNAP] I am not receiving funds for the video

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5699]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: I am not receiving funds for the video
- Houston, we have a problem.: Money doesn&#39;t come for video
- Your Channel and Account Details: ICOLine, link to channel  https://www.youtube.com/channel/UCcs5JTQEcTQnYSKeWIyXcwQ
- Email or Discord handle for feedback: kotlyar.1995@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #562 in Usersnap](https://app.usersnap.com/l/feedback/835597e1-bcc2-468b-9b99-5b855e50d580?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator in regards to sync rewards an and payout schedule.
