### ISSUE TITLE
[USERSNAP] I didn’t copy any video from another channels. But you guys suspended my channel. Why/

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5700]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: I didn’t copy any video from another channels. But you guys suspended my channel. Why/
- Houston, we have a problem.: Copyright 
- Your Channel and Account Details: musakhandhakar2121@gmail.com
- Email or Discord handle for feedback: musakhandhakar2121@gmail.com

**Browser**: Chrome 112 (Android 12)
**Screen size**: 412x869
**[Open #563 in Usersnap](https://app.usersnap.com/l/feedback/2edb57b0-d3ab-4034-be9b-d7d324099fbf?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
