### ISSUE TITLE
[USERSNAP] Telif hakkı yapılan videonun silinerek kanalın onaylanmasını talep ediyorum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5701]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Expected Result: Telif hakkı yapılan videonun silinerek kanalın onaylanmasını talep ediyorum
- Houston, we have a problem.: Neden telif hakkı ihlali yaptım
- Your Channel and Account Details: basketciemre@gmail.com
- Email or Discord handle for feedback: basketciemre@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x851
**[Open #564 in Usersnap](https://app.usersnap.com/l/feedback/93638221-83cd-4ef9-9692-5811695665bd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
