### ISSUE TITLE
[USERSNAP] Let me sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5703]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Let me sign in
- Houston, we have a problem.: I am not able to sign in
- Your Channel and Account Details: bakchodipointofficial@gmail.com
- Email or Discord handle for feedback: bakchodipointofficial@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x804
**[Open #565 in Usersnap](https://app.usersnap.com/l/feedback/75ac0333-7000-4fae-803d-e28179206d62?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
Same thing https://github.com/Joystream/atlas/issues/5711#issuecomment-1871985925

**Comment by rchrdcstro** [comment]
This is not the same issue with https://github.com/Joystream/atlas/issues/5711. The creator simply needs to reset the password and provide the seed phrase, as they are already verified on our platform at the bronze level. Let me reopen the issue and provide assistance with the creator.
