### ISSUE TITLE
[FEATURE REQUEST] Quiero salirme del sistema

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5706]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- ¿Qué característica te estás perdiendo?: Quiero salirme del sistema
- ¿Qué problema resolvería eso para ti?: No me interesa mas esto no me gusta
- Share your Email or Discord so we can get in touch: andersonsalcedolop@gmail.com

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1024x768
**[Open #144 in Usersnap](https://app.usersnap.com/l/feedback/db5c7fad-3719-48bd-a99a-1fc75dcd8915?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
I assume that request is related to YPP sync system. It can be left through settings tab in Studio > YPP

**Comment by rchrdcstro** [comment]
I'm uncertain about the creator's request, but upon review, they're currently verified as bronze on our platform. It seems the creator might be seeking an option to opt out.
