### ISSUE TITLE
[USERSNAP] cree mi cuenta y asocie mi canal de youtube pero salto un error y ahora no me deja ingresar....

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5708]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: cree mi cuenta y asocie mi canal de youtube pero salto un error y ahora no me deja ingresar....
- Houston, we have a problem.: no pude crear bien mi cuenta...
- Your Channel and Account Details: e- mail: patricioalejocruz@gmail.com
https://www.youtube.com/channel/UCYg7CxbDK_jwU1bQ-l2964A

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #566 in Usersnap](https://app.usersnap.com/l/feedback/6c549bb9-25e3-4c20-bd87-48e9fdf2f1b2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
No account was created for the provided email, the user should to able to go through the flow again. No info about the encountered error makes it impossible to say more.

**Comment by rchrdcstro** [comment]
I verified the email address provided, but it doesn't appear in our records. It's possible that the creator used a different email address or might need to attempt signing up again.
