### ISSUE TITLE
[USERSNAP] sin problema, sencillo, eficaz 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5709]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Expected Result: sin problema, sencillo, eficaz 
- Houston, we have a problem.: me dice que el correo esta mal
- Your Channel and Account Details:  @criptofull6141 y me dice que mi correo esta mal, y no es el caso
- Email or Discord handle for feedback: mulgoba2010@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1360x768
**[Open #567 in Usersnap](https://app.usersnap.com/l/feedback/2b73d673-0cd7-445c-be03-755f4806c331?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
Snackbar is misleading, will be fixed by https://github.com/Joystream/atlas/issues/5712.

There is both account and membership connected with the provided email. User should recover account with wallet seed through the Forget password flow on the login modal.
