### ISSUE TITLE
[FEATURE REQUEST] Pago por mis videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5710]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: Pago por mis videos
- ¿Qué problema resolvería eso para ti?: Necesito saber, por qué no me están pagando por los videos que he subida a YT y que están vinculados a mi cuenta en gleev
- Share your Email or Discord so we can get in touch: educar1410@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1280x720
**[Open #145 in Usersnap](https://app.usersnap.com/l/feedback/34915445-75b9-4037-9a00-b672fe63c889?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
No accounts related to the email ergo no way to verify the issue
