### ISSUE TITLE
[USERSNAP] Просто зарегестрируюсь и все, а то не грузится то заново начинаю уже зареган пишет, а войти в аккаут енмогу пишет, что не существует, а когда регусюь пишу, что существует

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5711]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Просто зарегестрируюсь и все, а то не грузится то заново начинаю уже зареган пишет, а войти в аккаут енмогу пишет, что не существует, а когда регусюь пишу, что существует
- Houston, we have a problem.: Не регестрируется аккаунт
- Your Channel and Account Details: freestylezames@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1440x900
**[Open #568 in Usersnap](https://app.usersnap.com/l/feedback/f9a7c081-1846-4c89-bd8d-e7bb043a05b3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
Both account and membership are already created for the provided email.

Only thing we can do, is to ask the user to recover the account with wallet seed obtained during registration. The flow can be found on the login modal "Forgot password".
![image](https://github.com/Joystream/atlas/assets/92513933/1d7c5484-ec2b-4593-a608-553291f7de24)

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.

**Comment by rchrdcstro** [comment]
The creator simply needs to reset the password and provide the seed phrase, as they are already verified on our platform at the bronze level. Let me reopen the issue and provide assistance with the creator.
