### ISSUE TITLE
[USERSNAP] negativa. no puedo iniciar sesion

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5716]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: negativa. no puedo iniciar sesion
- Houston, we have a problem.: no me permite iniciar sesion, al momento de iniciar me dice que no existe mi membresia
- Your Channel and Account Details: cover17 es mi canal que no me permite iniciar sesion en el canal.
- Email or Discord handle for feedback: sandrorodriguez226@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #569 in Usersnap](https://app.usersnap.com/l/feedback/2884b93c-dbd9-4205-9aec-94952c20c002?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
