### ISSUE TITLE
[USERSNAP] Que me puedan brindar información de como puedo ingresar a mi canal 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5717]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Que me puedan brindar información de como puedo ingresar a mi canal 
- Houston, we have a problem.: No me acuerdo mi semilla que me pide
- Your Channel and Account Details: oscarjosepomce1@gmail.com
- Email or Discord handle for feedback: oscarjoseponce1@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 412x915
**[Open #570 in Usersnap](https://app.usersnap.com/l/feedback/bf9e5cbd-9427-405c-9968-15fd37ad599b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
