### ISSUE TITLE
[FEATURE REQUEST] ELIMINAR MI CUENTA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5718]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- ¿Qué característica te estás perdiendo?: ELIMINAR MI CUENTA
- ¿Qué problema resolvería eso para ti?: COMO ELIMINO MI CUENTA DE ESTA PORQUERIA?
- Share your Email or Discord so we can get in touch: luffyfanny@gmail.com
- Your Gleev channel ID or Title: NO HAY PLATA

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #146 in Usersnap](https://app.usersnap.com/l/feedback/612bfb61-b477-4b4d-822d-d60446239306?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Provided the information for opting-out to the platform.
