### ISSUE TITLE
[USERSNAP] Espero 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5721]
**Taken at**: https://gleev.xyz/member/id/5456?tab=NFTs
**Fields**:
- Expected Result: Espero 
- Houston, we have a problem.: Perdí mi contraseña y semilla 
- Your Channel and Account Details: alejandrofont76@gmail.com
- Email or Discord handle for feedback: alejandrofont76@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x760
**[Open #571 in Usersnap](https://app.usersnap.com/l/feedback/ec26ad13-ee59-48d3-a49f-33c4dc91a298?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
