### ISSUE TITLE
[USERSNAP] Mais rápido 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5722]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Expected Result: Mais rápido 
- Houston, we have a problem.: Fiz o saque e não recebi 
- Your Channel and Account Details: investindocomleochina@gmail.com
- Email or Discord handle for feedback: investindocomleochina@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x760
**[Open #572 in Usersnap](https://app.usersnap.com/l/feedback/94809861-7ddd-493d-8e73-cee5337d2c47?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document.
