### ISSUE TITLE
[USERSNAP] discorda katılamıyorum hesabım sebepsiz yere askıya alındı

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5723]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: discorda katılamıyorum hesabım sebepsiz yere askıya alındı
- Houston, we have a problem.: discorda katılamıyorum hesabım sebepsiz yere askıya alındı
- Your Channel and Account Details: fahridemir6347@gmail.com
- Email or Discord handle for feedback: fahridemir6347@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #573 in Usersnap](https://app.usersnap.com/l/feedback/1c3ea243-0e95-40e5-880e-2d99d542034d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
