### ISSUE TITLE
[USERSNAP] no me pagaraon nada

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5724]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: no me pagaraon nada
- Houston, we have a problem.: not paymant
- Your Channel and Account Details: https://gleev.xyz/channel/47960?tab=Videos
- Email or Discord handle for feedback: elsapomaluco@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c3496a11-cc08-45eb-bf84-210c32ad9d86-annotated_f1be0ebc-3bb0-4108-a44d-8232af76ae07.png?etag=c3bb2ba49671ff06bdb630ceba737324)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c3496a11-cc08-45eb-bf84-210c32ad9d86-annotated_f1be0ebc-3bb0-4108-a44d-8232af76ae07.png?etag=c3bb2ba49671ff06bdb630ceba737324)*

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x641
**[Open #574 in Usersnap](https://app.usersnap.com/l/feedback/ce0da515-4948-4113-9927-b968bb30b4e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I reached out to @zeeshanakram3 and confirmed that he will check.
