### ISSUE TITLE
[FEATURE REQUEST] no me pagaron 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5725]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- ¿Qué característica te estás perdiendo?: no me pagaron 
- ¿Qué problema resolvería eso para ti?: que me paguen 
- Share your Email or Discord so we can get in touch: elsapomaluco@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/channel/47960?tab=Videos

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b5a7596a-e881-43b2-8da7-9f3c81e4a2a7-annotated_3bef9ecc-271a-4a44-bd43-efc73e1d8603.png?etag=cb55cc1a1f6a43ff372f51cb0c57ffc0)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b5a7596a-e881-43b2-8da7-9f3c81e4a2a7-annotated_3bef9ecc-271a-4a44-bd43-efc73e1d8603.png?etag=cb55cc1a1f6a43ff372f51cb0c57ffc0)*

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x641
**[Open #147 in Usersnap](https://app.usersnap.com/l/feedback/3bcab08a-30e0-47bd-8af5-74c482a6cf6a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Duplicated issue.
