### ISSUE TITLE
[USERSNAP] Até agora está sendo bom

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5726]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Expected Result: Até agora está sendo bom
- Houston, we have a problem.: Fiz o pedido de saque até agora não caiu na mexc
- Your Channel and Account Details: investindocomleochina@gmail.com
- Email or Discord handle for feedback: investindocomleochina@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x760
**[Open #575 in Usersnap](https://app.usersnap.com/l/feedback/6cf5d678-104d-47dc-b9fa-aeb8974603d3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Duplicated issue.
