### ISSUE TITLE
[USERSNAP] I’m trying to sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5727]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: I’m trying to sign in
- Houston, we have a problem.: I made an account and it won’t let me in
- Your Channel and Account Details: drip mushroom scissors chicken peasant envelope direct basic hat rather like slush
- Email or Discord handle for feedback: Overcomeurreality@gmail.com

**Browser**: Safari 17 (iOS)
**Screen size**: 430x932
**[Open #576 in Usersnap](https://app.usersnap.com/l/feedback/7262f4d6-0be9-46d4-bbc0-77794c9560d2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
