### ISSUE TITLE
[USERSNAP] Why did my channel with 5010 subscribers and 570 videos receive bronze status? Look please.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5731]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Why did my channel with 5010 subscribers and 570 videos receive bronze status? Look please.
- Houston, we have a problem.: CHANNEL YPP STATUS Verified  Bronze tier
- Your Channel and Account Details: My Channel: https://gleev.xyz/channel/50540?tab=Videos

My Channel YouTube: http://www.youtube.com/channel/UCJyemTvNj_W45pE-emye6lw

My gmail: romanekras321@gmail.com
- Email or Discord handle for feedback: dmitriyshig#6960

**Browser**: Opera 105 (Windows 10)
**Screen size**: 1920x1080
**[Open #577 in Usersnap](https://app.usersnap.com/l/feedback/97c0a2c7-800b-43f2-a08c-a56017d42fa2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Verification team made a re-assessment with the creator channel and channel got upgraded to silver. Informed the creator about the news.
