### ISSUE TITLE
[USERSNAP] সিরাজগঞ্জ সদর সিরাজগঞ্জ চরহরিপুর 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5732]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: সিরাজগঞ্জ সদর সিরাজগঞ্জ চরহরিপুর 
- Houston, we have a problem.: কবির হোসেন 
- Your Channel and Account Details: kobirhoissn999483@gmail.com
- Email or Discord handle for feedback: kobirhoissn999483@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #578 in Usersnap](https://app.usersnap.com/l/feedback/8ea965bc-7f83-4ba1-b036-5207d9e327fa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I emailed the creator to inquire about their specific concerns or issues and suggested utilizing the feedback widget once more to address and resolve their problem.
