### ISSUE TITLE
[FEATURE REQUEST] no me deja iniciar sesion

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5733]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- ¿Qué característica te estás perdiendo?: no me deja iniciar sesion
- ¿Qué problema resolvería eso para ti?: me dice que no encuentra la cuenta
- Share your Email or Discord so we can get in touch: daviadabrahampv32@gmail.com
- Your Gleev channel ID or Title: www.youtube.com/@David32YT

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1366x768
**[Open #148 in Usersnap](https://app.usersnap.com/l/feedback/4deb1b8c-a0c9-4b20-8d8d-4d31cfea7d78?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
