### ISSUE TITLE
[USERSNAP] ayuda porfavor, no me deja iniciar sesion

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5734]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Expected Result: ayuda porfavor, no me deja iniciar sesion
- Houston, we have a problem.: tengo problema al login
- Your Channel and Account Details: mi canal es David32yt, y estoy teniendo problemas al iniciar sesion, la pagina me dice esto: No podemos encontrar la membresía de Gleev asociada con este correo electrónico
- Email or Discord handle for feedback: daviadabrahampv32@gmail.com

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1366x768
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/1f4f7cc3-5507-41b0-981b-9c1b26991eaa_screen_recording_d28ce413-ca53-4558-a65a-8c8a6b754832.webm?etag=cd6710793b079b3dce71c7a1bbd7119f)**
**[Open #579 in Usersnap](https://app.usersnap.com/l/feedback/b4030b21-f520-41a5-abc0-e0904a29834d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
