### ISSUE TITLE
[USERSNAP] just need more info

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5735]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: just need more info
- Houston, we have a problem.: why my youtube account suspended 
- Your Channel and Account Details: ladda.x.music 
- Email or Discord handle for feedback: bronxbanga@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #580 in Usersnap](https://app.usersnap.com/l/feedback/6e171d09-aa5a-4970-85b7-6a1d540f2991?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
The channel already opted out.
