### ISSUE TITLE
[USERSNAP] Diamond Tier

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5736]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Diamond Tier
- Houston, we have a problem.: I have a channel of 43K and I only receive 2$
- Your Channel and Account Details: Impecables
- Email or Discord handle for feedback: javierferrerbescos@gmail.com

**Browser**: Chrome 120 (macOS Catalina)
**Screen size**: 1512x982
**[Open #581 in Usersnap](https://app.usersnap.com/l/feedback/a7144105-c6c7-492e-b907-094233a4cccd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Our verification team made a reassessment and channel should passed silver tier.
