### ISSUE TITLE
[FEATURE REQUEST] Consulta 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5738]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- ¿Qué característica te estás perdiendo?: Consulta 
- ¿Qué problema resolvería eso para ti?: Necesito asesoramiento, ya que la cuenta está en bronce y no estoy obteniendo ganancias. ¿Es posible crecer una vez que estamos en bronce?
Tengo un canal con 200k sub y estoy probando con este... 
- Share your Email or Discord so we can get in touch: miusicc34@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/channel/50796?tab=Videos

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1371x639
**[Open #149 in Usersnap](https://app.usersnap.com/l/feedback/112a2b92-22dd-40ef-99ac-cc165c720be7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
No action needed. Checked and creator opted out.
