### ISSUE TITLE
[USERSNAP] Geçen Hafta Ödül hesabıma yatmadı.Bu haftada Hesabıma ödül yansimadı Yardımcı olursaniz sevinirim.İyi Çalışmlar dilerim.🙏

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5739]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Geçen Hafta Ödül hesabıma yatmadı.Bu haftada Hesabıma ödül yansimadı Yardımcı olursaniz sevinirim.İyi Çalışmlar dilerim.🙏
- Houston, we have a problem.: Para Hesabıma Yansımıyor.
- Your Channel and Account Details: darknightmaree1@gmail.com

VX Dark Nightmare 
- Email or Discord handle for feedback: darknightmaree1@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**[Open #582 in Usersnap](https://app.usersnap.com/l/feedback/91c7300f-ba83-44c0-b383-8c676115b499?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards was settled 12/27/23 and sent the instruction to check the payment.
