### ISSUE TITLE
[USERSNAP] Я обычно вводил свой mail и заходил в аккаунт, сейчас пишет, что его не существует.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5740]
**Taken at**: https://gleev.xyz/signin
**Fields**:
- Expected Result: Я обычно вводил свой mail и заходил в аккаунт, сейчас пишет, что его не существует.
- Houston, we have a problem.: Не заходит в аккаунт по email, 
- Your Channel and Account Details: fidelityclique@mail.ru
- Email or Discord handle for feedback: fidelityclique@mail.ru

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1440x900
**[Open #583 in Usersnap](https://app.usersnap.com/l/feedback/aedf1cc5-eacb-43bd-a2f6-e32fce7d2168?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
