### ISSUE TITLE
[USERSNAP] Just an hour ago I logged into my account, everything was ok. Right now I come in and it says it doesn’t exist, there are messages in the mail from gleev that I own the account and there is a seed phrase. What to do?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5741]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: Just an hour ago I logged into my account, everything was ok. Right now I come in and it says it doesn’t exist, there are messages in the mail from gleev that I own the account and there is a seed phrase. What to do?
- Houston, we have a problem.:  Can&#39;t log into account
- Your Channel and Account Details: fidelityclique@mail.ru
password eS2zTIoKm!
- Email or Discord handle for feedback: fidelityclique@mail.ru xneveroriginal@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1440x900
**[Open #584 in Usersnap](https://app.usersnap.com/l/feedback/b0b87d76-e476-4e4d-8135-1a71af0ccee1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
