### ISSUE TITLE
[USERSNAP] We can't find Gleev membership associated with this email Make sure that you are using the same email that you used to create your membership on Gleev.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5742]
**Taken at**: https://gleev.xyz/
**Fields**:
- Expected Result: We can&#39;t find Gleev membership associated with this email
Make sure that you are using the same email that you used to create your membership on Gleev.
- Houston, we have a problem.: Incorrect email or password.
- Your Channel and Account Details: marcelopabtas@gmail.com
- Email or Discord handle for feedback: marcelopabtas@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #585 in Usersnap](https://app.usersnap.com/l/feedback/a7a2a94b-3654-4483-8824-ad6f8805bfcc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
