### ISSUE TITLE
[USERSNAP] There has been no copyright violation on my channel to date. You made the wrong decision. I expect you to correct your mistake immediately.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5743]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: There has been no copyright violation on my channel to date. You made the wrong decision. I expect you to correct your mistake immediately.
- Houston, we have a problem.: Your incorrect copyright notice!
- Your Channel and Account Details: Cahannel : DeliDolu --- Delidolu1i---- kocae5098@gmail.com
- Email or Discord handle for feedback: kocae5098@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/c142d74a-7539-42a7-a899-892f82537796_screen_recording_5e194953-fa9e-43c1-8697-3dd7e5b35f21.webm?etag=edb97c4ddfb0bed475f5f2ce472ebe59-2)**
**[Open #586 in Usersnap](https://app.usersnap.com/l/feedback/b778973f-0b4a-4d25-9565-ea2e22f9e393?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator the reason of suspension and sent the document for his reference.
