### ISSUE TITLE
[USERSNAP] Approval of my channel.Being included in the rewards program and receiving my rewards I deserve.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5744]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Approval of my channel.Being included in the rewards program and receiving my rewards I deserve.
- Houston, we have a problem.: False and unfair Copyright infringement notification
- Your Channel and Account Details: Deli Dolu----delidolu1i-----kocae5098@gmail.com
- Email or Discord handle for feedback: kocae5098@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/236f50de-0629-49ab-893e-114b13ed2701_screen_recording_691e4415-6cb5-4385-8b61-daa79415ec45.webm?etag=cd9d58d966899ab7024493c402e91a42)**
**[Open #587 in Usersnap](https://app.usersnap.com/l/feedback/4abb366e-d787-4266-9990-104d69ee25c0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator about the suspension reason and provided the document for reference.
