### ISSUE TITLE
[USERSNAP] hesabım askıda gözüküyor

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5745]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: hesabım askıda gözüküyor
- Houston, we have a problem.: kanal senkrenizasyon
- Your Channel and Account Details: cobracan06@gmail ile hesap açtım 8900 aboneli youtube kanalım var ama hesabım askıda gözüküyor yardımcı olurmusunuz.
- Email or Discord handle for feedback: cobracan06@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #588 in Usersnap](https://app.usersnap.com/l/feedback/74df4c66-6886-4d41-8df1-86d9162345da?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
