### ISSUE TITLE
[USERSNAP] askıya alınmış hesap diyor yanıltıcı içerik diyor

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5746]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: askıya alınmış hesap diyor yanıltıcı içerik diyor
- Houston, we have a problem.: kanal senkrenizasyon
- Your Channel and Account Details: benim 8900 aboneli youtube kanalım var yıllardır içerik üretirim hesabı düzelte bilirmisiniz
- Email or Discord handle for feedback: cobracan06@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c65444d4-2d6c-4a6e-bf99-939d31569243-annotated_249cb187-8a6b-41fe-af13-bfb854465708.png?etag=425be6fa6a959a34098a74077c84826c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c65444d4-2d6c-4a6e-bf99-939d31569243-annotated_249cb187-8a6b-41fe-af13-bfb854465708.png?etag=425be6fa6a959a34098a74077c84826c)*

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x953
**[Open #589 in Usersnap](https://app.usersnap.com/l/feedback/68d420be-3c86-4879-8223-ce85ece6f280?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Instruct to sign-up and provide the document for creator reference.
