### ISSUE TITLE
[USERSNAP] There Is Sign In Issue.When I Sign In It Showing Your Account Was Not Created Yet Please Solve My Issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5747]
**Taken at**: https://gleev.xyz/channel/27783?tab=Videos
**Fields**:
- Expected Result: There Is Sign In Issue.When I Sign In It Showing Your Account Was Not Created Yet Please Solve My Issue
- Houston, we have a problem.: Hello There Is An Issue When I Creating My Account.
- Your Channel and Account Details: My Register Email Address :- waseem68418@gmail.com
- Email or Discord handle for feedback: toptricks786@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 412x915
**[Open #590 in Usersnap](https://app.usersnap.com/l/feedback/3774c424-e041-4a56-99ca-a673f155650d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
