### ISSUE TITLE
[USERSNAP] Sincronizar mis videos 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5750]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: Sincronizar mis videos 
- Houston, we have a problem.: Por favor eliminar mi cuenta ya que no sincronizaron mis videos 
- Your Channel and Account Details: elcontertulio correo juanpipe2014dbz@gmail.com
- Email or Discord handle for feedback: juan.parrao@cun.edu.co

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**[Open #591 in Usersnap](https://app.usersnap.com/l/feedback/1c615952-986f-4382-8c2a-1df9c682176e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Already assisting this concern in discord channel. Discussion link here: https://discord.com/channels/811216481340751934/1053294778529353788/1195106654199492679
