### ISSUE TITLE
[USERSNAP] YPP BAĞLANTISI KURAMIYORUM GLEEV DEKİ TÜM HESAPLARIMI NASIL SIFIRLAYIP YENİDEN YOUTUBE KANALI BAĞLAYA BİLİRİM DİSCORTTAN ULAŞAMIYORUM SİZE ACİL CEVAP BEKLİYORUM TÜM GLEEV HESAPLARIMI SİLMEK İÇİN NE YAPMAM LAZIM

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5751]
**Taken at**: https://gleev.xyz/channel/50927?tab=Videos
**Fields**:
- Expected Result: YPP BAĞLANTISI KURAMIYORUM GLEEV DEKİ TÜM HESAPLARIMI NASIL SIFIRLAYIP YENİDEN YOUTUBE KANALI BAĞLAYA BİLİRİM DİSCORTTAN ULAŞAMIYORUM SİZE ACİL CEVAP BEKLİYORUM TÜM GLEEV HESAPLARIMI SİLMEK İÇİN NE YAPMAM LAZIM
- Houston, we have a problem.: YPP BAĞLANTISI KURAMIYORUM
- Your Channel and Account Details: KRİPTO_AVCİSİ
- Email or Discord handle for feedback: pc.teknolog.omer@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #592 in Usersnap](https://app.usersnap.com/l/feedback/350d47a3-c293-49f3-a93f-c9a476a96336?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
