### ISSUE TITLE
[USERSNAP] I withdraw 266 joystream coin but it didn`t come to mexc

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5752]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: I withdraw 266 joystream coin but it didn`t come to mexc
- Houston, we have a problem.: withdraw
- Your Channel and Account Details: Membership handle : kriptoqazanc
- Email or Discord handle for feedback: abdulla.qeribli96@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #593 in Usersnap](https://app.usersnap.com/l/feedback/4129a99b-c3f5-410c-8d99-b4aa6e09d49a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator to check their transfer status through subscan.
