### ISSUE TITLE
[USERSNAP] Yo no sabía Qué era esta plataforma y yo lo eqore

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5753]
**Taken at**: https://gleev.xyz/ypp?state=code%3Dezxmw4ha2%26channelId%3D&code=4/0AfJohXnwv0A-swnXZicrcONbkK6fI71sMOI2UnYJOu5VwWcg5ZCPAaPWONUUI6q3OHn-gw&scope=email%20https://www.googleapis.com/auth/youtube.readonly%20openid%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- Expected Result: Yo no sabía Qué era esta plataforma y yo lo eqore
- Houston, we have a problem.: Mis suscriptores no ve mis vídeos y me unia
- Your Channel and Account Details: Hola me llamo MR THE 🗿 solo subo videos de #humor 
- Email or Discord handle for feedback: eliexercastro118@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #594 in Usersnap](https://app.usersnap.com/l/feedback/a11c0c90-c269-415a-ae35-2faa26bfb407?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Task: Notified the creator that the membership has been established, but the YouTube channel is not linked yet. Provided guidelines on how to connect the YouTube channel.
