### ISSUE TITLE
[USERSNAP] When i login its showing - Incorrect email or password

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5760]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Expected Result: When i login its showing - Incorrect email or password
- Houston, we have a problem.: I have submited with my youtube but unable to login again
- Your Channel and Account Details: cwebdesignmedia@gmail.com
Channel Name : Opentarges
- Email or Discord handle for feedback: cwebdesignmedia@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #596 in Usersnap](https://app.usersnap.com/l/feedback/ec5cac41-7580-4fc7-9de2-4ee50e87b7bd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration. Instruct to sign-up and provide the document for creator reference.
