### ISSUE TITLE
[USERSNAP] Hi i register my channel, but there is no trace that it is associated with my page, for example the tier reward has not been activated in others this is my channel https://www.youtube.com/@FlexVega

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5761]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Hi i register my channel, but there is no trace that it is associated with my page, for example the tier reward has not been activated in others
this is my channel https://www.youtube.com/@FlexVega
- Houston, we have a problem.: Problem Youtube +7 M
- Your Channel and Account Details: carlosaugustovega4@gmail.com
- Email or Discord handle for feedback: squirtlevega@gmail.com

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #597 in Usersnap](https://app.usersnap.com/l/feedback/66e9afc8-575c-4e01-9e74-c13104cc5eda?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator that their channel is still undergoing verification. Requested the creator to exercise patience and await further updates within the next 24-48 hours.
