### ISSUE TITLE
[USERSNAP] None

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5762]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Expected Result: None
- Houston, we have a problem.: Why my referal channel can&#39;t be accepted
- Your Channel and Account Details: Not yet proved
- Email or Discord handle for feedback: donapk256@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #598 in Usersnap](https://app.usersnap.com/l/feedback/e0f77fcc-3ca2-41c1-9df0-49b4b28257b1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Emailed the creator to obtain the YouTube channel link of their referral and conduct a check.
