### ISSUE TITLE
[USERSNAP] Hello, why is my channel not being accepted for the program?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5763]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Expected Result: Hello, why is my channel not being accepted for the program?
- Houston, we have a problem.: Channle YPP Suspended
- Your Channel and Account Details: chainfogroup@gmail.com
- Email or Discord handle for feedback: chainfogroup@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8bbb2388-1ecd-4f07-a0bf-5e48e4136f92-annotated_3805bcbd-fe6c-4619-99e4-12c047ca294d.png?etag=bc4c47cd1100cdcc480c29a3c48d5c2a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8bbb2388-1ecd-4f07-a0bf-5e48e4136f92-annotated_3805bcbd-fe6c-4619-99e4-12c047ca294d.png?etag=bc4c47cd1100cdcc480c29a3c48d5c2a)*

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1912x800
**Browser size**: 1731x659
**[Open #599 in Usersnap](https://app.usersnap.com/l/feedback/0e37df0d-2322-4179-8ee3-87bfcc9d304d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
