### ISSUE TITLE
[FEATURE REQUEST] Доброго времени суток

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5764]
**Taken at**: https://gleev.xyz/channel/26913?tab=Videos
**Fields**:
- Какая черта вам не хватает?: Доброго времени суток
- Какая проблема мы можем решить для вас?: Ребят у меня будет начисление монет или как?
вы начислите что то?
- Share your Email or Discord so we can get in touch: djsuhov88@gmail.com
- Your Gleev channel ID or Title: victorolga88

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1280x1024
**[Open #150 in Usersnap](https://app.usersnap.com/l/feedback/67b6f027-cd92-4131-b413-b62f76cb8a15?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Duplicated issue.
