### ISSUE TITLE
[USERSNAP] quiero tener la oportunidad de ser aceptado en esta gran plataforma y red socila ya que soy creador de contenido original gracias 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5765]
**Taken at**: https://gleev.xyz/member/makingflowbeat6434?tab=NFTs
**Fields**:
- Expected Result: quiero tener la oportunidad de ser aceptado en esta gran plataforma y red socila ya que soy creador de contenido original gracias 
- Houston, we have a problem.: mi canal salio no lo aprovaron dice engañoso 
- Your Channel and Account Details: j4SLFwUSAe8qTmPxPqdZpXdhzp1rqKBQ34114AcGPS8DSbMwY   

mackingflowbeat@gamilcom

hago instrumentales y beat soy productor son mis ediciones y sonidos originalestengo los proyectos por patententes y notas en el pentagrama 
- Email or Discord handle for feedback: animedis99@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #600 in Usersnap](https://app.usersnap.com/l/feedback/b70c7d7c-0972-4922-b6d9-c2e9c6b83955?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
