### ISSUE TITLE
[USERSNAP] I cannot access to my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5768]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I cannot access to my account
- Expected Result: Error with recover my password and my seed int recognized
- Your Channel and Account Details: nickolaskremep@gmail.com
TESOROS DE LA PALABRA DE DIOS
- Email or Discord handle for feedback: nickolaskremep@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #601 in Usersnap](https://app.usersnap.com/l/feedback/76ddbba7-577d-4fdb-99ab-277c362460e8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
