### ISSUE TITLE
[USERSNAP] I don't receive my payments 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5769]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: I don&#39;t receive my payments 
- Expected Result: Hello, I have not received two payments, I receive the Gmail explaining that the payments were made but I log into my account and there is nothing
- Your Channel and Account Details: eliasortiz311202@gmail.com
- Email or Discord handle for feedback: eliasortiz311202@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x720
**[Open #602 in Usersnap](https://app.usersnap.com/l/feedback/d5a874a6-e2df-4537-8eb3-dd8fc8521ea0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards were settled 12/27/2023 and sent the instruction to check the payment.
