### ISSUE TITLE
[USERSNAP] I can't restore password

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5770]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I can&#39;t restore password
- Expected Result: I has a seed phrase, but when i restore password window &#34;Something went wrong&#34;. Plz delet my accaun and i will created new one
- Your Channel and Account Details: igormatukhin@gmail.com
youtube channel @cryptarnya
- Email or Discord handle for feedback: igormatukhin@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1536x761
**[Open #603 in Usersnap](https://app.usersnap.com/l/feedback/aee5fc8e-d1f9-4621-b116-1ae6135362ad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that without the seed phrase account can't be recovered.
