### ISSUE TITLE
[USERSNAP] Problemi di accesso ed iscrizione.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5772]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Problemi di accesso ed iscrizione.
- Expected Result: Non sono mai riuscito ad accedere al mio profilo... e ho avuto difficoltà ad effettuare l iscrizione.
- Your Channel and Account Details: Valentino.chia@hotmail.com
- Email or Discord handle for feedback: Valentino.chia@hotmail.com 

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #604 in Usersnap](https://app.usersnap.com/l/feedback/63b7ac17-d98e-4e56-9e75-99b5a5c5a038?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found.Ask the creator to check if they use the same email address for registration.Instruct to sign-up and provide the document for creator reference.
