### ISSUE TITLE
[USERSNAP] Salir del sistema 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5774]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: Salir del sistema 
- Expected Result: No hay forma  de salir de este sietema, quiero salir, quiero sacar mi canal de aqui...
- Your Channel and Account Details: j4T1YtgZutNKmTws7ZWAnQkePSgDCBxjrGRffcGoTRVRSatM4
- Email or Discord handle for feedback: miusicc34@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #605 in Usersnap](https://app.usersnap.com/l/feedback/210b7194-6eac-4009-81fc-f1c2168fa572?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator about ranking channel guidelines and give recommendations.
