### ISSUE TITLE
[USERSNAP] payment problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5775]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: payment problem
- Expected Result: I tried to withdraw a payment, there was an error on the page, the balance was collected but it never reached the wallet
- Your Channel and Account Details: carlosaugustovega4@gmail.com
- Email or Discord handle for feedback: squirtlevega@gmail.com

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #606 in Usersnap](https://app.usersnap.com/l/feedback/04e32f56-caf5-44b7-a450-ca61c16dc65d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration
