### ISSUE TITLE
[USERSNAP] Salir del sistema 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5779]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Salir del sistema 
- Expected Result: quiero salir del sistema y me dice: No node connection
Wait for connection to restore
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFB6efxR97Rkb6kxPgRAwD
- Email or Discord handle for feedback: miusicc34@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #607 in Usersnap](https://app.usersnap.com/l/feedback/f009fe7a-96c0-4dbb-b33a-c2ee3acfe6cd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Ask the creator to share the error message by screen recording or snapshot so we can further assist.
