### ISSUE TITLE
[USERSNAP] Sir my channle reawds not receive 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5784]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: Sir my channle reawds not receive 
- Expected Result: My joy strim reawds not ricive 
- Your Channel and Account Details: ffkamrul909@gmail.com
- Email or Discord handle for feedback: ffkamrul909@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 424x942
**[Open #608 in Usersnap](https://app.usersnap.com/l/feedback/a38c266f-6f70-4f91-94c3-d59f4132ebf5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that there are no rewards for suspended channels.
