### ISSUE TITLE
[FEATURE REQUEST] ads

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5785]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Which feature are you missing?: ads
- What problem would that solve for you?: whats the source of income that gives you to give money for these creators ? thats little suspious for me beacuse i can&#39;t even see any ads here..
- Share your Email or Discord so we can get in touch: propottanabhishek@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBQfQSdWt79fUQkmW1Usz

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #155 in Usersnap](https://app.usersnap.com/l/feedback/1fc365d3-920e-46e9-bb7a-6111d77a53b9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Information provided from Content Lead.
