### ISSUE TITLE
[FEATURE REQUEST] code invetation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5786]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Which feature are you missing?: code invetation
- What problem would that solve for you?: hi dear should you obligate new user to add invetation or refferal code when they create there new account to encourage old user get some rewards 
- Share your Email or Discord so we can get in touch: a.beghdadi@yahoo.fr

**Browser**: Edge (Chromium) 120 (Windows 10)
**Screen size**: 1600x900
**[Open #156 in Usersnap](https://app.usersnap.com/l/feedback/337355f0-1f06-4f88-8911-0c8eb08e8a98?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that all Gleev channels regardless of the tier can participate in the referrals scheme.
