### ISSUE TITLE
[FEATURE REQUEST] مشاهدات

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5787]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Which feature are you missing?: مشاهدات
- What problem would that solve for you?: لم يتقبل 
- Share your Email or Discord so we can get in touch: anwradlalfwdya@gmail.com‬‏
- Your Gleev channel ID or Title: آيـﮯسـو¿

**Browser**: Chrome 120 (Android 10)
**Screen size**: 412x883
**[Open #157 in Usersnap](https://app.usersnap.com/l/feedback/f41e0fde-1d53-402a-9496-d4466e89ee68?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
