### ISSUE TITLE
[USERSNAP] I try to register with my YouTube channel and it tells me that it is already in use

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5788]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I try to register with my YouTube channel and it tells me that it is already in use
- Expected Result: I tried to register with my YouTube channel doubleprecords2023@gmail.com, but it tells me that it is already in use and that it will contact support
- Your Channel and Account Details: Doubleprecords2023@gmail.com
- Email or Discord handle for feedback: Heylicho123@gmail.com

**Browser**: Safari 17 (iOS)
**Screen size**: 414x896
**[Open #609 in Usersnap](https://app.usersnap.com/l/feedback/825af463-65e8-4e63-99d1-7cde08c2a654?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
