### ISSUE TITLE
[USERSNAP] Forget password  not working 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5789]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Forget password  not working 
- Expected Result: Must work 
- Your Channel and Account Details: ffg317957@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 412x915
**[Open #610 in Usersnap](https://app.usersnap.com/l/feedback/48506a2b-360b-4453-9f60-abf9081773e4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
