### ISSUE TITLE
[FEATURE REQUEST] .

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5791]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Какой функциональности вам не хватает?: .
- Какую проблему мы можем решить для вас?: Дали бронзу после синхронизации, при том условии, что у меня оригинальный контент и большая база подписчиков. Хоть и канал заново набирает обороты
- Share your Email or Discord so we can get in touch: nikitacryptoyt@gmail.com
- Your Gleev channel ID or Title: Saving_Klaster

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #158 in Usersnap](https://app.usersnap.com/l/feedback/3ba6f428-55d0-4830-89c6-df1972ac440b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator to advance to a higher tier, we recommend creating high-quality content and actively engaging inthe platform. In this, we can consider advancing to a higher tier in the future.
