### ISSUE TITLE
[FEATURE REQUEST] I didn't get anything, check it out

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5792]
**Taken at**: https://gleev.xyz/channel/26913?tab=Videos
**Fields**:
- Какой функциональности вам не хватает?: I didn&#39;t get anything, check it out
- Какую проблему мы можем решить для вас?: I didn&#39;t get anything, check it out
- Share your Email or Discord so we can get in touch: djsuhov88@gmail.com
- Your Gleev channel ID or Title: victorolga88

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1280x1024
**[Open #159 in Usersnap](https://app.usersnap.com/l/feedback/473ed8c1-eec1-4a7d-acd2-a1c0be2bca5d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards were settled long time ago and sent the instruction to check the payment.
