### ISSUE TITLE
[FEATURE REQUEST] ؟ 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5793]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Quelle fonctionnalité vous manque?: ؟ 
- Quel problème cela résoudrait-il pour vous?: جلبت احالة ولم تحتسب لي
- Share your Email or Discord so we can get in touch: Attarhocin10@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBGaUFKsNRsF8UuJ94Q4h

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ef17b3e1-0729-40f7-94ef-5d454029c3fa-annotated_6078a589-0aed-4b8f-8323-68ba5e6976b6.png?etag=b2ea0693332ba1336917ed980bacbed2)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ef17b3e1-0729-40f7-94ef-5d454029c3fa-annotated_6078a589-0aed-4b8f-8323-68ba5e6976b6.png?etag=b2ea0693332ba1336917ed980bacbed2)*

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x760
**Browser size**: 360x637
**[Open #160 in Usersnap](https://app.usersnap.com/l/feedback/365c139f-1146-4bde-beb5-49b5a701e30a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that if referral is suspended no referral rewards will be issued,
