### ISSUE TITLE
[FEATURE REQUEST] I can Not Login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5794]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: I can Not Login
- What problem would that solve for you?: I can not login
- Share your Email or Discord so we can get in touch: Irgikasep47@gmail.com
- Your Gleev channel ID or Title: Irgimana12

**Browser**: Chrome 113 (Android 10)
**Screen size**: 393x873
**[Open #161 in Usersnap](https://app.usersnap.com/l/feedback/1796450a-6aed-4221-861a-a51c530bffd0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
