### ISSUE TITLE
[USERSNAP] не могу восстановить пароль у меня нет специальных букв

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5795]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: не могу восстановить пароль у меня нет специальных букв
- Expected Result: Да ожидала
- Your Channel and Account Details: jakuma1993@gmail.com 
- Email or Discord handle for feedback: jakuma1993@gmail.com 

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x720
**[Open #611 in Usersnap](https://app.usersnap.com/l/feedback/d7d59fba-8122-499b-8aca-9f1f2d93f0fe?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
