### ISSUE TITLE
[USERSNAP] Mi risultano 0 follower nel mol canale youtube 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5796]
**Taken at**: https://gleev.xyz/channel/51859?tab=Information
**Fields**:
- Houston, we have a problem.: Mi risultano 0 follower nel mol canale youtube 
- Expected Result: Mi aspettavo 2000 follower 
- Your Channel and Account Details: Ho molte visualizzazioni e iscritti ma mi spunta 0 su tutto
- Email or Discord handle for feedback: burgiop48@gmail.com

**Browser**: Safari 604 (iOS)
**Screen size**: 375x812
**[Open #612 in Usersnap](https://app.usersnap.com/l/feedback/82a7929d-d660-4bbc-959e-6fe0e05faa0d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that only videos from youtube is sync not the followers from youtube to gleev.
