### ISSUE TITLE
[USERSNAP] hesabımı bagladım ama giris yapamıyorum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5797]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: hesabımı bagladım ama giris yapamıyorum
- Expected Result: hesabi bagladım ama giris yapamıyorum birşeler ters gitti diyor
- Your Channel and Account Details: batakdizi@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #613 in Usersnap](https://app.usersnap.com/l/feedback/cbcf79b6-4f1b-4923-94e9-23217bae75ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator for a snapshot and asked the creator to join discord if this issue still need assistance.
