### ISSUE TITLE
[USERSNAP] Я потерял сид фразу что делать

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5800]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: Я потерял сид фразу что делать
- Expected Result: В начале не скопировал !
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFBCYFeFtzSGpCMTL6FqkH
- Email or Discord handle for feedback: ulugbekrazbekova@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 450x1000
**[Open #614 in Usersnap](https://app.usersnap.com/l/feedback/dd1d972b-8d74-482d-862e-6ed97ef8e435?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
