### ISSUE TITLE
[USERSNAP] Здравствуйте, я подал заявку на партнёрства прошло 48 часов и мне отказали по причине Эксплуатация условий программы

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5801]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Здравствуйте, я подал заявку на партнёрства прошло 48 часов и мне отказали по причине Эксплуатация условий программы
- Expected Result: Думал что одобрят на серебро
- Your Channel and Account Details: Адрес suhaylisuhrob1@gmail.com
Ютуб канал @suhayli
- Email or Discord handle for feedback: suhaylisuhrob1@gmail.com

**Browser**: Chrome 114 (Android 10)
**Screen size**: 384x832
**[Open #615 in Usersnap](https://app.usersnap.com/l/feedback/24918a52-2476-40be-9769-8de8357ff71a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
