### ISSUE TITLE
[FEATURE REQUEST] Никакой

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5802]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Какой функциональности вам не хватает?: Никакой
- Какую проблему мы можем решить для вас?: Никакой
- Share your Email or Discord so we can get in touch: burievodil213@gmsil.com
- Your Gleev channel ID or Title: MM see IT

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**[Open #162 in Usersnap](https://app.usersnap.com/l/feedback/25508781-9d5d-4491-9ebe-d784a430fe64?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
