### ISSUE TITLE
[USERSNAP] здраствуйте я привязал ютуб канал к этому сайту и канал на проверке уже 3 дня можете помочь с этим 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5803]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Houston, we have a problem.: здраствуйте я привязал ютуб канал к этому сайту и канал на проверке уже 3 дня можете помочь с этим 
- Expected Result: все хорошо будет
- Your Channel and Account Details: j4TQtyhCDDD8rv9EcbCV3UsCqs2yi3VNH9B5FL2CMFNjdKAC3
vvakkazov@gmail.com
- Email or Discord handle for feedback: vvakkazov@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1600x900
**[Open #616 in Usersnap](https://app.usersnap.com/l/feedback/b61c627f-3a6d-4e60-97be-bc01678e4c8a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
