### ISSUE TITLE
[FEATURE REQUEST] Здравствуйте помогите пожалуйста 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5804]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Какой функциональности вам не хватает?: Здравствуйте помогите пожалуйста 
- Какую проблему мы можем решить для вас?: У меня такая проблема напишу свой канал в поисках не найдёт что мне надо делать?
- Share your Email or Discord so we can get in touch: basarininizind@gmail.com
- Your Gleev channel ID or Title: başarının izinde 

**Browser**: Chrome 120 (Android 10)
**Screen size**: 412x915
**[Open #163 in Usersnap](https://app.usersnap.com/l/feedback/8b58791e-59a9-4f76-a9d9-2cc599a8773b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
