### ISSUE TITLE
[USERSNAP] зрасивуйте я ждал 2 дня но не платили

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5805]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: зрасивуйте я ждал 2 дня но не платили
- Expected Result: я думал за 2 дня оплата приходт но я жу уже 3 день
- Your Channel and Account Details: pubgmobileg295@gmail.com
- Email or Discord handle for feedback: standoff3363@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x720
**[Open #617 in Usersnap](https://app.usersnap.com/l/feedback/f5d2065c-1680-4f25-9d2b-ef7344033b32?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
I emailed the creator instructions on how to verify their channel and sent them a document explaining how to check their payment status.
