### ISSUE TITLE
[USERSNAP] It's been more than 48 hours of verification and they haven't checked

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5806]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: It&#39;s been more than 48 hours of verification and they haven&#39;t checked
- Expected Result: I thought they would check in 48 hours 
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFApUtQ18YgsLpr5NW5YgM
- Email or Discord handle for feedback: doriktutik@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 393x873
**[Open #618 in Usersnap](https://app.usersnap.com/l/feedback/6cf0c3d1-54d0-4512-9613-d5f0b9325a33?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
