### ISSUE TITLE
[USERSNAP] Unable to sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5807]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Unable to sign in
- Expected Result: More comfortable
- Your Channel and Account Details: moyoadeabdulbasit4@gmail.com
- Email or Discord handle for feedback: bmoyoade@gmail.com

**Browser**: Chrome 107 (Android 13)
**Screen size**: 412x915
**[Open #619 in Usersnap](https://app.usersnap.com/l/feedback/cd721ac4-3e0e-4f3e-81a1-bd0b2a477b10?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
