### ISSUE TITLE
[FEATURE REQUEST] Youtube Partner Program

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5809]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Melyik funkció hiányzik?: Youtube Partner Program
- Milyen probléma lenne megoldani az Ön számára?: Dear Gleeve! My question is that I applied for the Youtube Partner Program on January 28, 2024, and on the website it says with the verification that it may take 48 hours for them to decide which tier I will be in. In principle, the 48 hours will expire on January 30, 2024 at 7:50 a.m. And my question in this regard would be that on January 30, 2024, at 7:50 a.m., it will be revealed which tier I will be in? Thank you in advance for your answer. Best regards, Máté Chrén!
- Share your Email or Discord so we can get in touch: matechren@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBrQaiHjH7uCdT9Wq89bV

**Browser**: Chrome 120 (Android 10)
**Screen size**: 385x854
**[Open #164 in Usersnap](https://app.usersnap.com/l/feedback/0d25a77a-149b-44cc-8597-231cf9906869?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
closed this issue as channel is already verified under bronze tier.
