### ISSUE TITLE
[USERSNAP] I was not assigned channel status

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5810]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I was not assigned channel status
- Expected Result: I was not assigned channel status
- Your Channel and Account Details: dikribak@gmail.com
Crypto Corner

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1193x671
**[Open #620 in Usersnap](https://app.usersnap.com/l/feedback/c772dd5c-caeb-412c-814e-b626da1e0d5b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
closed issue - channel opted out
