### ISSUE TITLE
[FEATURE REQUEST] Marcelinho 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5811]
**Taken at**: https://gleev.xyz/studio/video-workspace
**Fields**:
- Que dispõem que está faltando?: Marcelinho 
- O problema teria que resolver para você?: Sim
- Share your Email or Discord so we can get in touch: marceloinvest01@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x760
**[Open #165 in Usersnap](https://app.usersnap.com/l/feedback/374bde1d-3971-432f-8cb3-84f34f49d7de?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
