### ISSUE TITLE
[USERSNAP] login problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5812]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: login problem
- Expected Result: Dear team
 I have registered gleev through referral link. After login I didn&#39;t get any mail from your side same way unable to login 
i want to reset my password 
kindly do favor 
thankyou 
- Your Channel and Account Details: selfcare tamil
- Email or Discord handle for feedback: selfcaretamil@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #621 in Usersnap](https://app.usersnap.com/l/feedback/52008291-bd3e-48d2-b939-6c893cd01952?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Instruct creator to follow the steps on the document for their issue. 
https://joystream.notion.site/Troubleshooting-Sign-Up-Sign-in-8b127a6da0a44650866e6828715b0009c
