### ISSUE TITLE
[USERSNAP] Login issue 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5813]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Login issue 
- Expected Result: Immediately take me to my dashboard 
- Your Channel and Account Details: kdramaclipsedit, yummy30341@gmail.com
- Email or Discord handle for feedback: yummy30341@gmail.com

**Browser**: Chrome 120 (Linux)
**Screen size**: 385x854
**[Open #622 in Usersnap](https://app.usersnap.com/l/feedback/338229ae-d87c-4c1e-b695-ba65af6496c6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
