### ISSUE TITLE
[USERSNAP] Verification process is still pending

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5814]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Verification process is still pending
- Expected Result: Its has been 48 hours but verification process does not complete
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFAxCqCHGRL8F8ZiCkG2AT

**Browser**: Chrome 110 (Android 10)
**Screen size**: 360x820
**[Open #623 in Usersnap](https://app.usersnap.com/l/feedback/00994182-9981-498a-8442-8a4649f96ce2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
