### ISSUE TITLE
[FEATURE REQUEST] Востановить фразу для привязки кошелька

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5815]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Какой функциональности вам не хватает?: Востановить фразу для привязки кошелька
- Какую проблему мы можем решить для вас?: как востановить фразу для привязки кошелька
- Share your Email or Discord so we can get in touch: litvinovallexx@gmail.com
- Your Gleev channel ID or Title:  Новости цифровых активов DEGEN

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**[Open #166 in Usersnap](https://app.usersnap.com/l/feedback/012b1c3c-7363-4b33-8168-e526afdec5a8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
