### ISSUE TITLE
[USERSNAP] withdrew but failed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5816]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: withdrew but failed
- Expected Result: withdrew but failed and cutt from account but not receive in my wallet
- Your Channel and Account Details: https://gleev.xyz/member/20xreviewer84

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1600x900
**[Open #624 in Usersnap](https://app.usersnap.com/l/feedback/d40813c0-3c51-4f17-aa6a-e5cbe5e100a1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
