### ISSUE TITLE
[USERSNAP] Writes copyright usage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5817]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Writes copyright usage
- Expected Result: my expected result was that the rank was given
- Your Channel and Account Details: aklonshow2008@gmail.com 
- Email or Discord handle for feedback: aklon#1514

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ebe644c0-2509-4618-a88b-404ba7600f6d-annotated_bcfdf153-a8fe-4b0c-b4b4-f502fd918267.png?etag=145de69ba37485e21c6b218520a8ce33)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ebe644c0-2509-4618-a88b-404ba7600f6d-annotated_bcfdf153-a8fe-4b0c-b4b4-f502fd918267.png?etag=145de69ba37485e21c6b218520a8ce33)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x869
**Browser size**: 412x722
**[Open #625 in Usersnap](https://app.usersnap.com/l/feedback/067602e8-fb7e-41fa-a0d9-2ac1c09e4b89?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension reason and provided the document for reference.
