### ISSUE TITLE
[USERSNAP] I CANT SIGN UP

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5818]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I CANT SIGN UP
- Expected Result: I WANT TO SIGN UP WITH MY EMAIL ADDRESS 
- Your Channel and Account Details: general gospel south credit toilet fine aerobic track connect alert verb welcome ikeolisaogochukwu@gmail.com
- Email or Discord handle for feedback: ikeolisaogochukwu@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1366x768
**[Open #626 in Usersnap](https://app.usersnap.com/l/feedback/32e5303c-be6d-4b6a-9a60-15fda5277773?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
