### ISSUE TITLE
[FEATURE REQUEST] None

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5819]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: None
- What problem would that solve for you?: I waited for 48hours but still didnt received account tier and how do I recover my joystream wallet address
- Share your Email or Discord so we can get in touch: tstarspha107@gmail.com
- Your Gleev channel ID or Title: Jesus Christ 

**Browser**: Chrome 120 (Android 10)
**Screen size**: 412x892
**[Open #167 in Usersnap](https://app.usersnap.com/l/feedback/c9f442b7-a7de-414f-a54f-06e117dd68ab?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
