### ISSUE TITLE
[USERSNAP] не начисляет баланс

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5820]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: не начисляет баланс
- Expected Result: Мне должны были начислить баланс сегодня, прошло 48 часов с момента подключения канала к платформе, скажите пожалуйста что делать или как ме написать в дискорд, перехожу по ссылке, открывается дискорд без вашего оператора, просто пустая заставка дискорда
- Your Channel and Account Details: kazakovalex13012009@gmail.com, канал: Internet_Profit
- Email or Discord handle for feedback: kazakovalex13012009@gmail.com

**Browser**: Yandex.Browser 23 (Windows 10)
**Screen size**: 1366x768
**[Open #627 in Usersnap](https://app.usersnap.com/l/feedback/e130174a-c418-4bc8-844a-370ba90cb286?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that channel didn't meet the verification requirement are no rewards for suspended channels.
