### ISSUE TITLE
[USERSNAP] I can not registre muy Youtube channel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5822]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Houston, we have a problem.: I can not registre muy Youtube channel
- Expected Result: Please help
- Your Channel and Account Details: lindacarpio21@gmail.com
- Email or Discord handle for feedback: lindacarpio21@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #629 in Usersnap](https://app.usersnap.com/l/feedback/3ba2be60-3181-4f72-a679-e8f321a8c20f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
