### ISSUE TITLE
[USERSNAP] i cannot login my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5823]
**Taken at**: https://gleev.xyz/channel/52931?tab=Information
**Fields**:
- Houston, we have a problem.: i cannot login my account
- Expected Result: i expect to make a login again soon enough
- Your Channel and Account Details: One23-dklegaspi21@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x800
**[Open #630 in Usersnap](https://app.usersnap.com/l/feedback/8895d731-5d6d-4189-8777-33e138683a20?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
