### ISSUE TITLE
[USERSNAP] My channel has not yet been verified. Its been more than 48 hours 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5824]
**Taken at**: https://gleev.xyz/channel/52676?tab=Videos
**Fields**:
- Houston, we have a problem.: My channel has not yet been verified. Its been more than 48 hours 
- Expected Result: It should get verified in 48 hours.
- Your Channel and Account Details: cairoefx6287
- Email or Discord handle for feedback: infinityboy40@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x800
**[Open #631 in Usersnap](https://app.usersnap.com/l/feedback/6f182107-e69e-4d50-8e58-a2a6d8d80891?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
