### ISSUE TITLE
[USERSNAP] My channel verification is pending but 48 hours already completed 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5825]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: My channel verification is pending but 48 hours already completed 
- Expected Result: When my verification will complete and I request gleev team to give me silver tier requesting to gleev team 
- Your Channel and Account Details: shivambhagat8764@gmail.com
- Email or Discord handle for feedback: movielalo02@gmail.com

**Browser**: Chrome 112 (Android 10)
**Screen size**: 360x800
**[Open #632 in Usersnap](https://app.usersnap.com/l/feedback/ffb35c69-4585-4937-8806-63400c999f03?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
