### ISSUE TITLE
[USERSNAP] I get a unexpected error everytime I upload avatar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5826]
**Taken at**: https://gleev.xyz/studio/uploads
**Fields**:
- Houston, we have a problem.: I get a unexpected error everytime I upload avatar
- Expected Result: That it would draw the fee, take the image, put it as my avatar
- Your Channel and Account Details: RemarkableMe
Emanuel.lyrsten@hotmail.com
- Email or Discord handle for feedback: emanuel.lyrsten@hotmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x915
**[Open #633 in Usersnap](https://app.usersnap.com/l/feedback/8f179313-7930-42ff-b341-53c3d9c52c19?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Hi @zeeshanakram3. Can you look into this?

**Comment by rchrdcstro** [comment]
issue resolved in discord.
