### ISSUE TITLE
[USERSNAP] I couldn't delete the video

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5827]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: I couldn&#39;t delete the video
- Expected Result: the video has been extended
- Your Channel and Account Details: aklonshow2008@gmail.com 
- Email or Discord handle for feedback: gmail: aklonshow2008@gmail.com Discord: aklon#1514

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a5088bd5-6149-499b-80f0-4a09d8ae7eb5-annotated_6c3e7f12-d661-43f4-bb9f-bc44a82cad9d.png?etag=dcad91bca2b02813575482180ddf0372)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a5088bd5-6149-499b-80f0-4a09d8ae7eb5-annotated_6c3e7f12-d661-43f4-bb9f-bc44a82cad9d.png?etag=dcad91bca2b02813575482180ddf0372)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x869
**Browser size**: 412x722
**[Open #634 in Usersnap](https://app.usersnap.com/l/feedback/578c7e9c-05f0-471a-a90f-097dedfaab2c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
