### ISSUE TITLE
[USERSNAP] Request login issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5828]
**Taken at**: https://gleev.xyz/ypp?state=code%3Dzqg7ejmj9%26channelId%3D&code=4/0AfJohXlIf-uAyQgRaepkcn7MxL27OaqOW5IAruhrJo-KGgEEgvqdHUysQQ0Ha5GKKs-OLw&scope=email%20openid%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/userinfo.email&authuser=1&prompt=consent
**Fields**:
- Houston, we have a problem.: Request login issue
- Expected Result: I forgot my password of login 
I want to reset my password
- Your Channel and Account Details: Selfcare Tamil , selfcaretamil@gmail.com
- Email or Discord handle for feedback: selfcaretamil@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 407x904
**[Open #635 in Usersnap](https://app.usersnap.com/l/feedback/a5b939bc-2227-4290-8df5-3bc6a4938269?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
