### ISSUE TITLE
[USERSNAP] forgot password login issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5829]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: forgot password login issue
- Expected Result: I forgot my gleev password
i want to reset it
kindly help me do favour
- Your Channel and Account Details: selfcare Tamil
selfcaretamil@gmail.com
- Email or Discord handle for feedback: selfcaretamil@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c41e8d0a-f1ed-4264-ab6f-01c9e4a07011-annotated_1e35645e-535e-45d2-855d-28e5e17217a7.png?etag=a8c9f75435a08f7f164e0d60f5855309)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c41e8d0a-f1ed-4264-ab6f-01c9e4a07011-annotated_1e35645e-535e-45d2-855d-28e5e17217a7.png?etag=a8c9f75435a08f7f164e0d60f5855309)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1024x768
**Browser size**: 1024x657
**[Open #636 in Usersnap](https://app.usersnap.com/l/feedback/0791b3d4-8501-4e75-95cc-1766072f8476?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
