### ISSUE TITLE
[USERSNAP] Hello, what should I do if I did not save the code for tolisman's wallet, help me delete it

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5830]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Hello, what should I do if I did not save the code for tolisman&#39;s wallet, help me delete it
- Expected Result: Hello, what should I do if I did not save the code for tolisman&#39;s wallet, help me delete it
- Your Channel and Account Details: Hello, what should I do if I did not save the code for tolisman&#39;s wallet, help me delete it
- Email or Discord handle for feedback: andrey.gorchakov.08@mail.ru

**Browser**: Yandex.Browser 24 (Windows 10)
**Screen size**: 1920x1080
**[Open #637 in Usersnap](https://app.usersnap.com/l/feedback/502e0ba1-efad-4c2a-89e0-e47a186ba472?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
