### ISSUE TITLE
[USERSNAP] Unable to sign in 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5831]
**Taken at**: https://gleev.xyz/channel/52753?tab=NFTs
**Fields**:
- Houston, we have a problem.: Unable to sign in 
- Expected Result: To be more easier
- Your Channel and Account Details: moyoadeabdulbasit4@gmail.com
- Email or Discord handle for feedback: bmoyoade@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b96d9ef6-291c-4079-a236-571fa33172af-annotated_e3aff2be-ff73-4ab0-a212-010d22125dd4.png?etag=4be9e56d7282c6cad217dd58cc77a9af)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b96d9ef6-291c-4079-a236-571fa33172af-annotated_e3aff2be-ff73-4ab0-a212-010d22125dd4.png?etag=4be9e56d7282c6cad217dd58cc77a9af)*

**Browser**: Chrome 107 (Android 13)
**Screen size**: 412x915
**Browser size**: 412x785
**[Open #638 in Usersnap](https://app.usersnap.com/l/feedback/60a7fa27-b110-4f29-a236-a5a35a46b78b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
