### ISSUE TITLE
[USERSNAP] why is my account suspended?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5832]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Houston, we have a problem.: why is my account suspended?
- Expected Result: How to proceed
- Your Channel and Account Details: Davide46_Gamer
- Email or Discord handle for feedback: davidedilo46@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1920x1080
**[Open #639 in Usersnap](https://app.usersnap.com/l/feedback/90ca4039-74fc-401e-9959-bc8bdd2c2f98?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
