### ISSUE TITLE
[USERSNAP] вход 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5833]
**Taken at**: https://gleev.xyz/signin
**Fields**:
- Houston, we have a problem.: вход 
- Expected Result: не могу войти в аккаунт
- Your Channel and Account Details: horosaamarina02@gmail.com
- Email or Discord handle for feedback: horosaamarina02@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1366x768
**[Open #640 in Usersnap](https://app.usersnap.com/l/feedback/83ca2b78-44e5-466b-824b-51e04b8a2ba2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
