### ISSUE TITLE
[USERSNAP] My channel has not been verified yet and it's pass three days why what's the issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5835]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: My channel has not been verified yet and it&#39;s pass three days why what&#39;s the issue
- Expected Result: My channel to be verified as soon as possible please 
- Your Channel and Account Details: Blockchainbios
- Email or Discord handle for feedback: thegoatplayer27@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x820
**[Open #641 in Usersnap](https://app.usersnap.com/l/feedback/8eca5d21-0849-44d2-86ce-330b5334cdbb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as verification of channels is already up to date. Just reached out to the creator to join the Discord channel if they need assistance.
