### ISSUE TITLE
[USERSNAP] The account did not violate copyright в меня он есть 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5836]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: The account did not violate copyright в меня он есть 
- Expected Result: You have an error, the account did not violate copyright 
- Your Channel and Account Details: sanuyanu0@gmail.com
www.youtube.com/ilmeaarlim
- Email or Discord handle for feedback: ddfsima@gmail.com

**Browser**: Chrome 119 (Linux)
**Screen size**: 393x873
**[Open #642 in Usersnap](https://app.usersnap.com/l/feedback/e045e61c-bad8-498a-8515-7ca1aaaeb298?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
