### ISSUE TITLE
[USERSNAP] YouTube mistakenly blocked my channel, he apologized and unblocked 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5837]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: YouTube mistakenly blocked my channel, he apologized and unblocked 
- Expected Result: YouTube mistakenly blocked my channel, he apologized and unblocked it
YouTube blocked it by mistake, he unblocked it
- Your Channel and Account Details: ilme aallim
https://www.youtube.com/channel/UCjGxr8SNpmgtA2762cdWHpw
- Email or Discord handle for feedback: sanuyanu0@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1600x900
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/7252d5df-edb0-460a-9b2f-c7492d4e5ff9_screen_recording_f6268ff8-7ab7-4644-8916-9eba5724e389.webm?etag=44cabe3bd46f524041e6bd3a5eb4cd95)**
**[Open #643 in Usersnap](https://app.usersnap.com/l/feedback/c825fcc0-b712-4c9d-ad11-5bfc93a6bb0d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue .
