### ISSUE TITLE
[USERSNAP]  the account was blocked by mistake on the part of YouTube, I did not violate any copyrights

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5838]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.:  the account was blocked by mistake on the part of YouTube, I did not violate any copyrights
- Expected Result: 
the account was blocked by mistake on the part of YouTube, I did not violate any copyrights
- Your Channel and Account Details: jGxr8SNpmgtA2762cdWHpw
UCjGxr8SNpmgtA2762cdWHpw
https://www.youtube.com/channel/UCjGxr8SNpmgtA2762cdWHpw
- Email or Discord handle for feedback: sanuyanu0@gmail.com

**Browser**: Chrome 120 (Windows 10)
**Screen size**: 1600x900
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/2139ea45-dabb-4ec7-ab8f-20458f807330_screen_recording_08aa0cec-ee93-4b8f-8f24-591cc9227c86.webm?etag=73c057794e763d72cc7635abbeeef89f)**
**[Open #644 in Usersnap](https://app.usersnap.com/l/feedback/874c62ef-c01c-4e5e-98fe-07c4e5a32e68?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
