### ISSUE TITLE
[USERSNAP] No puedo registrarme 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5839]
**Taken at**: https://gleev.xyz/channel/52649?tab=Videos
**Fields**:
- Houston, we have a problem.: No puedo registrarme 
- Expected Result: Es la cuarta vez que intento registrarme con mi smartphone y no accede.
- Your Channel and Account Details: josualogan@proton.me
- Email or Discord handle for feedback: josualogan@proton.me

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x771
**[Open #645 in Usersnap](https://app.usersnap.com/l/feedback/e0932cd2-0ac1-44ff-bda7-c1511476c208?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
