### ISSUE TITLE
[USERSNAP] Не в чем нет проблем

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5840]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Не в чем нет проблем
- Expected Result: Да
- Your Channel and Account Details: Какашка
- Email or Discord handle for feedback: Romatop2024@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x825
**[Open #646 in Usersnap](https://app.usersnap.com/l/feedback/0e775db9-b348-4b4e-9cbc-a0e124b48758?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
closed this issue as creator told that there's no problem.
