### ISSUE TITLE
[USERSNAP] It says that the channel is linked and i know the password but i cant login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5841]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: It says that the channel is linked and i know the password but i cant login
- Expected Result: to login,maybe get my passphrase or correct password?
- Your Channel and Account Details: https://www.youtube.com/channel/UCOnxxdU_jdAUibYqn2H9dgg  , email is idetylerbrown@gmail.com 
- Email or Discord handle for feedback: idetylerbrown@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**[Open #647 in Usersnap](https://app.usersnap.com/l/feedback/0d64d3c8-6a8b-47fc-809b-613d9a9af7d4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced
