### ISSUE TITLE
[USERSNAP] Cannot login to my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5842]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Cannot login to my account
- Expected Result: Cannot login
- Your Channel and Account Details: Fayhaskitchen
- Email or Discord handle for feedback: shajigdr7@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x915
**[Open #648 in Usersnap](https://app.usersnap.com/l/feedback/1144a2b8-c57a-48ec-bef7-22f7ce6514b3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator and ask the error message.
