### ISSUE TITLE
[USERSNAP] Not working

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5843]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Houston, we have a problem.: Not working
- Expected Result: Hjjkkkhgfgg
- Your Channel and Account Details: Fghjjk
- Email or Discord handle for feedback: barcynbekovanurzat41@gmil.com

**Browser**: Safari 17 (iOS)
**Screen size**: 414x896
**[Open #649 in Usersnap](https://app.usersnap.com/l/feedback/93d446db-5d6a-401d-9a13-2b20eaa09b21?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Reach out to the creator via email to inquire about their specific issues and offer assistance.
