### ISSUE TITLE
[USERSNAP] Can't able to create a membership, showing error:500

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5844]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Can&#39;t able to create a membership, showing error:500
- Expected Result: It should be fast and smooth
- Your Channel and Account Details: preetiagrawaldl18@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9977164f-3894-487e-a371-e47049bd5883-annotated_9f99461c-9553-4654-86d0-30ae9a11093e.png?etag=5bad3d81a59de81115a57af791466495)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9977164f-3894-487e-a371-e47049bd5883-annotated_9f99461c-9553-4654-86d0-30ae9a11093e.png?etag=5bad3d81a59de81115a57af791466495)*

**Browser**: Chrome 87 (Android 11)
**Screen size**: 360x780
**Browser size**: 360x609
**[Open #650 in Usersnap](https://app.usersnap.com/l/feedback/a8dc7a27-df3f-497d-8d63-9b53e7080d2d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
