### ISSUE TITLE
[USERSNAP] Incorrect email or password

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5845]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Incorrect email or password
- Expected Result: i create a account here. but ti have a login problem 
- Your Channel and Account Details: kawsaraliearn@gmail.com
- Email or Discord handle for feedback: kawsaraliearn@gmail.com

**Browser**: Opera 106 (Windows 10)
**Screen size**: 1920x1080
**[Open #651 in Usersnap](https://app.usersnap.com/l/feedback/84591704-6f6f-4929-8c5d-f61deb91e082?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
