### ISSUE TITLE
[USERSNAP] sheikharifwork@gmail.com

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5846]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: sheikharifwork@gmail.com
- Expected Result: Something went wrong
There was a problem with creating your account. Please try again later. Error code: 500
- Your Channel and Account Details: kawsaraliearn@gmail.com
- Email or Discord handle for feedback: sheikharifwork@gmail.com

**Browser**: Opera 106 (Windows 10)
**Screen size**: 1920x1080
**[Open #652 in Usersnap](https://app.usersnap.com/l/feedback/2eaf1e74-9ab6-460a-b8a1-60ee46f0c9e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Instruct creator to follow the steps on the document for their issue. 
https://joystream.notion.site/Troubleshooting-Sign-Up-Sign-in-8b127a6da0a44650866e6828715b0009c
