### ISSUE TITLE
[USERSNAP] I cannot connect the YouTube channel. It tells me: There was a problem creating your account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5847]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I cannot connect the YouTube channel. It tells me: There was a problem creating your account
- Expected Result: T dont know
- Your Channel and Account Details: Osamaalshbl110@gmail.com
- Email or Discord handle for feedback: Osamaalshbl110@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x720
**[Open #653 in Usersnap](https://app.usersnap.com/l/feedback/dd24b7ac-0feb-4e2d-8b5c-d4a83d2d5a3e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Instruct creator to follow the steps on the document for their issue. 
https://joystream.notion.site/Troubleshooting-Sign-Up-Sign-in-8b127a6da0a44650866e6828715b0009
