### ISSUE TITLE
[USERSNAP] I can't sign up here. Everytime I sign up during membership sign in time it say error 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5849]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Houston, we have a problem.: I can&#39;t sign up here. Everytime I sign up during membership sign in time it say error 
- Expected Result: I want to sign up and earn money. Please solve it fast.
- Your Channel and Account Details: Email: sahinsheikh020@gmail.com
- Email or Discord handle for feedback: sahinsheikh020@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x869
**[Open #655 in Usersnap](https://app.usersnap.com/l/feedback/744208c8-4e2d-4080-b62a-4798daad6381?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated plug issue.
