### ISSUE TITLE
[USERSNAP] I can't signup. When I go to signup it says this channel has already been registered and when I go to log in it says there no account with this email?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5850]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I can&#39;t signup. When I go to signup it says this channel has already been registered and when I go to log in it says there no account with this email?
- Expected Result: I want to signup and the issue should be solved
- Your Channel and Account Details: ahsenammar6@gmail.com
- Email or Discord handle for feedback: ahsenammar6@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x800
**[Open #656 in Usersnap](https://app.usersnap.com/l/feedback/ed6626fc-01a5-4619-bbf9-d57f0100e991?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
