### ISSUE TITLE
[USERSNAP] Error 500

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5851]
**Taken at**: https://gleev.xyz/channel/52649?tab=Videos
**Fields**:
- Houston, we have a problem.: Error 500
- Expected Result: My membership handle is arckolrour
- Your Channel and Account Details: It is stuck in Creating membership...
- Email or Discord handle for feedback: kollingmarc@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1286x571
**[Open #657 in Usersnap](https://app.usersnap.com/l/feedback/b195bd45-9e4d-426a-a559-0688c3e68ac0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Instruct creator to follow the steps on the document for their issue. 
https://joystream.notion.site/Troubleshooting-Sign-Up-Sign-in-8b127a6da0a44650866e6828715b0009
