### ISSUE TITLE
[USERSNAP] No me deja entrar ami cuenta de Gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5852]
**Taken at**: https://gleev.xyz/ypp?referrerId=51557
**Fields**:
- Houston, we have a problem.: No me deja entrar ami cuenta de Gleev
- Expected Result: Que iba ah aceder rapido a mi cuenta de Gleev
- Your Channel and Account Details: Yadielmercedes65@gmail.com
- Email or Discord handle for feedback: yadielmercedes65@gmail.com 

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x846
**[Open #658 in Usersnap](https://app.usersnap.com/l/feedback/0dc08dd5-0401-4e5f-8144-0a5a4576904c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration.Instruct to sign-up and provide the document for creator reference.
