### ISSUE TITLE
[USERSNAP] Faucet Exhausted - Can not create an account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5853]
**Taken at**: https://gleev.xyz/video/920495
**Fields**:
- Houston, we have a problem.: Faucet Exhausted - Can not create an account
- Expected Result: Account Created
- Your Channel and Account Details: 68marc
- Email or Discord handle for feedback: kollingrouram@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1286x571
**[Open #659 in Usersnap](https://app.usersnap.com/l/feedback/ada61b05-9384-4875-9e88-3114746aaa26?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
