### ISSUE TITLE
[USERSNAP] Can't connect my channel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5854]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Can&#39;t connect my channel
- Expected Result: Connect issue
- Your Channel and Account Details: Hiiiuniverse

**Browser**: Chrome 119 (Android 10)
**Screen size**: 437x970
**[Open #660 in Usersnap](https://app.usersnap.com/l/feedback/00f49083-6c50-4217-b402-d34557880a21?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found.Ask the creator to check if they use the same email address for registration. Instruct to sign-up and provide the document for creator reference.
https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb
