### ISSUE TITLE
[USERSNAP] Membership failed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5855]
**Taken at**: https://gleev.xyz/channel/52649?tab=Videos
**Fields**:
- Houston, we have a problem.: Membership failed
- Expected Result: I´m triying to create an account for the fourth time but the faucet does not work at all. Thank you.
- Your Channel and Account Details: manahague@gmail.com
- Email or Discord handle for feedback: manahague@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1932x956
**[Open #661 in Usersnap](https://app.usersnap.com/l/feedback/f0fee85c-29c0-4482-b108-d1984970d233?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
