### ISSUE TITLE
[USERSNAP] started linking the YouTube channel, but it says copyright infringement. Content not copied, made by me.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5856]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: started linking the YouTube channel, but it says copyright infringement. Content not copied, made by me.
- Expected Result: my account will be assigned a rank
- Your Channel and Account Details: aklonshow@gmail.com 
- Email or Discord handle for feedback: Gmail aklonshow@gmail.com 

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6720ff4a-fb42-49c2-8407-a05afc96266d-annotated_630b13cf-d592-4654-b854-c853b217d4a2.png?etag=4727151c3b1d8fd59d77587f5e7018e1)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6720ff4a-fb42-49c2-8407-a05afc96266d-annotated_630b13cf-d592-4654-b854-c853b217d4a2.png?etag=4727151c3b1d8fd59d77587f5e7018e1)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x869
**Browser size**: 412x722
**[Open #662 in Usersnap](https://app.usersnap.com/l/feedback/ec51dda9-ee5d-4c4f-a36d-51291cda560e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
