### ISSUE TITLE
[FEATURE REQUEST] Que no sean 20subcribtores y en vez 1 suscriptor

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5857]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- ¿Qué característica te estás perdiendo?: Que no sean 20subcribtores y en vez 1 suscriptor
- Share your Email or Discord so we can get in touch: Sina.gomez@yahoo.com
- Your Gleev channel ID or Title: Youtube.com/tom

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x780
**[Open #169 in Usersnap](https://app.usersnap.com/l/feedback/3d74b8a2-ae52-4aad-bdd2-ac49153745f7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator about the set subscribers limit. Sent the project outline: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#6d0146586e4d4399837c2247cb8bf1d1
