### ISSUE TITLE
[USERSNAP] No me diga entrar 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5858]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: No me diga entrar 
- Expected Result: NoNo me diga entrar 
- Your Channel and Account Details: No me diga entrar 

**Browser**: Chrome 121 (Android 10)
**Screen size**: 393x873
**[Open #663 in Usersnap](https://app.usersnap.com/l/feedback/99f45df1-c65f-4b9e-b48b-4446c8a02d61?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
closed the issue - no contact information and issue not  provided
