### ISSUE TITLE
[USERSNAP] No me deja iniciar sesión 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5859]
**Taken at**: https://gleev.xyz/ypp?state=code%3Duw3quf1gy%26channelId%3D&code=4/0AfJohXmYglegAia8g6Bzy6IwTmJYnnZo_l9pR5V9uQV7gLvSR8BJFjrah8IHeBIInCeyaQ&scope=email%20openid%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- Houston, we have a problem.: No me deja iniciar sesión 
- Expected Result: Malo
- Your Channel and Account Details: Goku4376
- Email or Discord handle for feedback: omargabrielp10@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x806
**[Open #664 in Usersnap](https://app.usersnap.com/l/feedback/46596329-93bf-408f-9aaa-f63c66a6e920?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Also let know that channel didn't pass verifications.
