### ISSUE TITLE
[USERSNAP] Money doesn't come for video

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5861]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: Money doesn&#39;t come for video
- Expected Result: Payments for the week did not arrive
- Your Channel and Account Details: I haven&#39;t received payments for the videos I shot last week.
- Email or Discord handle for feedback: kotlyar.1995@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**[Open #665 in Usersnap](https://app.usersnap.com/l/feedback/628e072d-7810-4cf6-9a2a-632fe64170a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that payment is made every Tuesday and check that the rewards for the last synced video have been settled.
