### ISSUE TITLE
[USERSNAP] I just forget the password and seed 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5862]
**Taken at**: https://gleev.xyz/referrals?utm_medium=email&_hsmi=82520502&_hsenc=p2ANqtz-8J-RsaEZMAxCa_DT2ikI5YGx7ElcAW_yOL2jW3hwxmBRmCv7nPfQR7_wKRXOwbXMNmP_j1q2KlW4Go2BAlch33ATxTxA&utm_content=82520502&utm_source=hs_email
**Fields**:
- Houston, we have a problem.: I just forget the password and seed 
- Expected Result: Plz allow me reset the password or login with google
- Your Channel and Account Details: YT Channel:https://youtube.com/@jinshatechandgaming?si=_rkavvXjyCYZsfsb
Handle: Jinshatechandgaming
Email: abuarakkal36@gmail.com
- Email or Discord handle for feedback: abuarakkal36@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1967d352-0ea8-4a0e-b191-1a3725874ec0-annotated_833dc4de-2e18-4e51-86de-220f3ba8da22.png?etag=de481cf5fa15a3fa92917b756e2c5123)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1967d352-0ea8-4a0e-b191-1a3725874ec0-annotated_833dc4de-2e18-4e51-86de-220f3ba8da22.png?etag=de481cf5fa15a3fa92917b756e2c5123)*

**Browser**: Chrome 92 (Android 11)
**Screen size**: 360x800
**Browser size**: 360x672
**[Open #666 in Usersnap](https://app.usersnap.com/l/feedback/0b5c7105-4a5c-4bd2-b2b8-252d6e8a6a90?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference. 
https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
