### ISSUE TITLE
[FEATURE REQUEST] Why was it suspended? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5864]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Hangi özelliği kaçırıyorsun?: Why was it suspended? 
- Bu sizin için hangi problemi çözer?: Why is my account suspended? 
- Share your Email or Discord so we can get in touch: Heavenly Future 
- Your Gleev channel ID or Title: Heavenly Future 

**Browser**: Chrome 121 (Android 10)
**Screen size**: 393x873
**[Open #170 in Usersnap](https://app.usersnap.com/l/feedback/d2ed9ff7-de5f-433f-9cf9-c71e441b4209?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference.
(https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b)
