### ISSUE TITLE
[USERSNAP] my channel have more than 20 suscribers and 2 videos,

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5866]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: my channel have more than 20 suscribers and 2 videos,
- Expected Result: I dont think
- Your Channel and Account Details: my channel is PunxetMusic
- Email or Discord handle for feedback: punet134@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d0bc4515-206b-4cfe-b6da-b588876a4b79-annotated_9faaef18-45c9-4adc-b031-079015c03871.png?etag=a61891495678ee923078215ff54c03d7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d0bc4515-206b-4cfe-b6da-b588876a4b79-annotated_9faaef18-45c9-4adc-b031-079015c03871.png?etag=a61891495678ee923078215ff54c03d7)*

**Browser**: Firefox 122 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x643
**[Open #668 in Usersnap](https://app.usersnap.com/l/feedback/46e0577a-7b8c-4885-b565-5df7d7d73474?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference.
https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
