### ISSUE TITLE
[USERSNAP] Kayıt olurken bana verilen anahtarı kayebtim

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5868]
**Taken at**: https://gleev.xyz/signin
**Fields**:
- Houston, we have a problem.: Kayıt olurken bana verilen anahtarı kayebtim
- Expected Result: Bunu lütfen en kısa surede düzeltin şifremi unuttum ve değiştiremiyorum.
- Your Channel and Account Details: 63hanifix@gmail.com
- Email or Discord handle for feedback: 63hanifix@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 393x873
**[Open #669 in Usersnap](https://app.usersnap.com/l/feedback/3f3c9936-9dfc-411e-b881-5b276b2abcdb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
