### ISSUE TITLE
[FEATURE REQUEST] I forgot my phrase, sir, please, sir

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5870]
**Taken at**: https://gleev.xyz/referrals?utm_medium=email&_hsmi=82145380&_hsenc=p2ANqtz--SoL4OKpKKJ0ZPO7mUSvlFe2nDkHfFWLtIqUwymJBa0WUu5xIUS9ODe39IvKsiJt1e1TsMbFmlrID6hAmsADOM9Gw_xA&utm_content=82145380&utm_source=hs_email
**Fields**:
- Which feature are you missing?: I forgot my phrase, sir, please, sir
- What problem would that solve for you?: I forgot my phrase, sir, please, sir
- Share your Email or Discord so we can get in touch: redmicrp32@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x851
**[Open #172 in Usersnap](https://app.usersnap.com/l/feedback/e30ad77d-b8f1-4114-80f6-fb3197ba9bfb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
