### ISSUE TITLE
[USERSNAP] Не могу войти в аккаунт пишет что нету членства

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5871]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Не могу войти в аккаунт пишет что нету членства
- Expected Result: Думал что будет все намного легче 
- Your Channel and Account Details: https://youtube.com/@Kriptomasters?si=jGYppTGYKkuOA4TW
- Email or Discord handle for feedback: lasenkoviktor915@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x820
**[Open #670 in Usersnap](https://app.usersnap.com/l/feedback/1368deee-e25f-4214-98bb-99345c5bb03e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator that they successfully signed up but didn't pass the verifications. Let know about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
