### ISSUE TITLE
[USERSNAP] It está leni

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5872]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: It está leni
- Expected Result: 

Eee
- Your Channel and Account Details: Err
- Email or Discord handle for feedback: willianyerguzman@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x806
**[Open #671 in Usersnap](https://app.usersnap.com/l/feedback/6ec98fb3-4df0-44ad-8da2-eb5858af0107?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference.
https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
