### ISSUE TITLE
[USERSNAP] Пишет ошибка кода или почты но я всё ввел правильно

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5875]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Houston, we have a problem.: Пишет ошибка кода или почты но я всё ввел правильно
- Expected Result: Помогите 
- Your Channel and Account Details: mrsellos2012@gmail.com. Sh13791379!

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x800
**[Open #672 in Usersnap](https://app.usersnap.com/l/feedback/f571b55d-e5eb-4a5f-a09c-4393f69f30d9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason of suspension of his and provided the document for reference.
