### ISSUE TITLE
[USERSNAP] E posta şifre hatasi

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5876]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: E posta şifre hatasi
- Expected Result: Posta hatası veriyor sifre hatası veriyor cep telefonun girince bu hatayi veriyor
- Your Channel and Account Details: balkir.coregili@gmail.com
- Email or Discord handle for feedback: balkir.coregili@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e4f32107-29a2-4245-b904-c69bb384fd33-annotated_3dc5e4f4-15e3-4e65-bc91-558cf71c2e2e.png?etag=26625c6ddb67dfb7d40943ca0c1ed628)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e4f32107-29a2-4245-b904-c69bb384fd33-annotated_3dc5e4f4-15e3-4e65-bc91-558cf71c2e2e.png?etag=26625c6ddb67dfb7d40943ca0c1ed628)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x640
**Browser size**: 476x740
**[Open #673 in Usersnap](https://app.usersnap.com/l/feedback/ebecd8ed-8b09-44e2-8f69-4cbebb3ca9be?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
