### ISSUE TITLE
[USERSNAP] My info is correct but i can't seem to login my account.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5877]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Houston, we have a problem.: My info is correct but i can&#39;t seem to login my account.
- Expected Result: Why it&#39;s my account letting me log in.
- Your Channel and Account Details: wolfgm09 
dhkprojects1@gmail.com
DANte@2005det
- Email or Discord handle for feedback: dhkprojects1@gmail.com

**Browser**: Edge (Chromium) 121 (Windows 10)
**Screen size**: 1366x768
**[Open #674 in Usersnap](https://app.usersnap.com/l/feedback/75059b26-e31d-4b58-b87b-732d1415ae83?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
