### ISSUE TITLE
[USERSNAP] Проблема с регистрацией

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5878]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Houston, we have a problem.: Проблема с регистрацией
- Expected Result: Мне хотелось как можно скорее зарегистрироваться и начать работать на вашей платформе 
- Your Channel and Account Details: ekmgh0@gmail.com
- Email or Discord handle for feedback: ekmgh0@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 393x873
**[Open #675 in Usersnap](https://app.usersnap.com/l/feedback/a88edee1-1cd4-4238-ab7f-ee2b36a02f7b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
