### ISSUE TITLE
[USERSNAP] Здравствуйте почему нет у меня реф.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5879]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard?tab=Referrals
**Fields**:
- Houston, we have a problem.: Здравствуйте почему нет у меня реф.
- Expected Result: Я думал что если кто регист. По моей ссылке то мой реф. А нет ни кого.
- Your Channel and Account Details: alexsandrgovorov143@gmail.com
- Email or Discord handle for feedback: alexsandrgovorov143@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x806
**[Open #676 in Usersnap](https://app.usersnap.com/l/feedback/3fc278fd-b275-4499-ac2f-615d0eb3a147?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated submitted issue.
