### ISSUE TITLE
[USERSNAP] Здравствуйте почему нет у меня реф.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5880]
**Taken at**: https://gleev.xyz/member/p33333?tab=Activity
**Fields**:
- Houston, we have a problem.: Здравствуйте почему нет у меня реф.
- Expected Result: Думал все будет хорошо работать.
- Your Channel and Account Details: j4VTJ3RfVdMLkrPcCcrbDPtCWENqXD9RC4gmPAkMRxaeF5HfH
- Email or Discord handle for feedback: alexsandrgovorov143@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/28c01f03-9e0d-47cd-9947-055f4d2fa540-annotated_51ac37ab-a1bd-41fb-ad77-fab85f21d8a1.png?etag=3d7d500fc35642df5a22147d932bd558)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/28c01f03-9e0d-47cd-9947-055f4d2fa540-annotated_51ac37ab-a1bd-41fb-ad77-fab85f21d8a1.png?etag=3d7d500fc35642df5a22147d932bd558)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x806
**Browser size**: 360x666
**[Open #677 in Usersnap](https://app.usersnap.com/l/feedback/bd7c16b5-81af-4c45-a76d-204b32d2a9af?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated submitted issue.
