### ISSUE TITLE
[FEATURE REQUEST] проверте

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5881]
**Taken at**: https://gleev.xyz/channel/26913?tab=Videos
**Fields**:
- Какой функциональности вам не хватает?: проверте
- Какую проблему мы можем решить для вас?: ребят нет начислений в джей наак - проверте - у меня ютуб на 5к с плюсом - должны быть начисления - пофиксите
- Share your Email or Discord so we can get in touch: djsuhov88@gmail.com
- Your Gleev channel ID or Title: victorolga88

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1280x1024
**[Open #173 in Usersnap](https://app.usersnap.com/l/feedback/1471b731-79f2-4baa-9906-6a0629375330?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue about payments (Old ticket)
