### ISSUE TITLE
[USERSNAP] Account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5882]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Account 
- Expected Result: Delete the channel that I created on gleev and my account 
- Your Channel and Account Details: Channel is unlisted I&#39;d is - j4VMdZrkcU6wbAQvnk7Ng5mRcJGDXCT6EQf2vyPda5KV9bc7b

Membership handle : bross

Email : rajatprakash4646@gmail.com
- Email or Discord handle for feedback: rajatprakash4646@gmail.com

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x800
**[Open #678 in Usersnap](https://app.usersnap.com/l/feedback/0892ab95-9f1d-4da8-b99f-657548579356?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that no option to delete the registration but told an option to opt out.
