### ISSUE TITLE
[USERSNAP] I just forget the password and seed 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5883]
**Taken at**: https://gleev.xyz/referrals?utm_medium=email&_hsmi=82520502&_hsenc=p2ANqtz-_CwR0CmghpKCYTkeJzH05ldyQkcjVqD9UKDDT6Q8cwTHFRYAf7fiCuD3guwEZyCffvIp3mrqOP56kxa2OiUOXn5ks57Q&utm_content=82520502&utm_source=hs_email
**Fields**:
- Houston, we have a problem.: I just forget the password and seed 
- Expected Result: Password reset option needed without the seed
- Your Channel and Account Details: Jinshatechandgaming
email: abuarakkal36@gmail.com
Youtube Channel: Jinsha tech and gaming

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/98ab8f5d-465d-4083-984f-5c3180f15185-annotated_9294fa41-699f-4e14-81b1-d59d8cb80efa.png?etag=4baeb5e05a5909f3a96a9ed03a16ce22)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/98ab8f5d-465d-4083-984f-5c3180f15185-annotated_9294fa41-699f-4e14-81b1-d59d8cb80efa.png?etag=4baeb5e05a5909f3a96a9ed03a16ce22)*

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x672
**[Open #679 in Usersnap](https://app.usersnap.com/l/feedback/c97ad8c6-a580-4217-8a73-9733378e1212?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
