### ISSUE TITLE
[FEATURE REQUEST] PARTNERSHIP PROPOSAL

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5884]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Que dispõem que está faltando?: PARTNERSHIP PROPOSAL
- O problema teria que resolver para você?: Hello,

My name is Welson and I own the Jovens Prósperos channel. My channel has 60K subscribers and is in the online money making niche. Here it is: https://www.youtube.com/@JovensProsperos 

I found your app and I believe my audience would love to know about it. Would you be interested in partnership?

Best Regards,
Welson
- Share your Email or Discord so we can get in touch: welsonnegociosonline@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1536x864
**[Open #174 in Usersnap](https://app.usersnap.com/l/feedback/c9587d78-f35e-4282-b401-7cac475b3170?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator to join our discord link and contact marketing for partnership proposal.
