### ISSUE TITLE
[FEATURE REQUEST] Estratega 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5885]
**Taken at**: https://gleev.xyz/channel/54638?tab=NFTs
**Fields**:
- ¿Qué característica te estás perdiendo?: Estratega 
- Share your Email or Discord so we can get in touch: Bazmatias37@gmail.com 
- Your Gleev channel ID or Title: https://youtube.com/@ESTRATEGA-cf7ox?si=9Oea8Qb4PVbfGy6o

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x760
**[Open #175 in Usersnap](https://app.usersnap.com/l/feedback/93a683e9-f0b8-48d7-8943-b4bb5e033a61?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
