### ISSUE TITLE
[USERSNAP] Stop doing this fraud business 😠

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5886]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Stop doing this fraud business 😠
- Expected Result: If you&#39;re system have any problem cheak now.😠😠.I don&#39;t need your your program and money also. I have lot of growth in youtube🤬🤬🤬. You says me it&#39;s copyright breach and you suspended my channel. Now I challenge you find the copyright problem. Please second verify before saying .... You need more research and more experience.By the way I think this is a fraud website, So I gonna report this website,and make a video about this.So be ready for this. I will upload my second channel.
- Your Channel and Account Details: Channel name - Quick Bites, email- personalsabarna2001@gmail.com
- Email or Discord handle for feedback: personalsabarna2001@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/86a6eebd-5dd3-46d8-890f-2f7271feb766-annotated_6d3a44c8-cf3a-4106-8a97-578a8f25d003.png?etag=28e234fba14fff0752e8b86a8f925e96)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/86a6eebd-5dd3-46d8-890f-2f7271feb766-annotated_6d3a44c8-cf3a-4106-8a97-578a8f25d003.png?etag=28e234fba14fff0752e8b86a8f925e96)*

**Browser**: Chrome 121 (Linux)
**Screen size**: 1152x720
**Browser size**: 1152x584
**[Open #680 in Usersnap](https://app.usersnap.com/l/feedback/fd83d77c-0133-41bf-b239-00623c2ca74a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by igrexac** [comment]
A letter was sent by mail with an explanation.

**Comment by rchrdcstro** [comment]
closed this issue due to its duplicated.
