### ISSUE TITLE
[USERSNAP] Stop doing this fraud business 😠

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5887]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Stop doing this fraud business 😠
- Expected Result: Ready for this I gonna report this your fraud website and make a video regarding your website 🤬🤬.I have linked my second channel to this website to verify that.But you have suspended my channel to saying that it is copyright 😠🤬.You have no Idea.you don&#39;t have any idea that what can I do. Ready for the video 
- Your Channel and Account Details: Channel name - Quick Bites.
Email - personalsabarna2001@gmail.com
- Email or Discord handle for feedback: personalsabarna2001@gmail.com

**Browser**: Chrome 121 (Linux)
**Screen size**: 1152x720
**[Open #681 in Usersnap](https://app.usersnap.com/l/feedback/4cba53e9-95a5-483b-aae6-4b962b59c033?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by igrexac** [comment]
A letter was sent by mail with an explanation.
