### ISSUE TITLE
[USERSNAP] Проблема со регистрацией своего канала вашей площадки

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5888]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Проблема со регистрацией своего канала вашей площадки
- Expected Result: Не знаю
- Your Channel and Account Details: Название канала:
Tagoinazar Abdurahmonov,
 Псевдоним:@TNazar23,
Адрес канала:
https://www.youtube.com/@THazar23

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x820
**[Open #682 in Usersnap](https://app.usersnap.com/l/feedback/15c0a451-bd12-42f3-98e6-5c8efb291d6b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by igrexac** [comment]
Description of the problem is not enough. There are no contacts for communication, there are no contacts in the youtube channel.

**Comment by rchrdcstro** [comment]
Hi @igrexac. You can use the YouTube channel link search in Dynamo B to find the email address.

**Comment by rchrdcstro** [comment]
Closed ticket as no contacts for communication.
