### ISSUE TITLE
[USERSNAP] Site tells me I will get paid but then I don't

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5889]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Site tells me I will get paid but then I don&#39;t
- Expected Result: The page displays &#34;you will receive your sign-up bonus on (Tuesday) 13 Feb 2024&#34; but the day comes and I don&#39;t get paid. If I wasn&#39;t going to be paid it shouldn&#39;t say that I will
- Your Channel and Account Details: arturo.calanche@gmail.com
- Email or Discord handle for feedback: arturo.calanche@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x915
**[Open #683 in Usersnap](https://app.usersnap.com/l/feedback/da235e86-edd6-41c4-bb76-94e2f4af583c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document.
