### ISSUE TITLE
[USERSNAP] I can't login to my gleeve account, when try logging it shows unknown accont

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5890]
**Taken at**: https://gleev.xyz/signin
**Fields**:
- Houston, we have a problem.: I can&#39;t login to my gleeve account, when try logging it shows unknown accont
- Expected Result: To be Good
- Your Channel and Account Details: robertidara217@gmail.com
- Email or Discord handle for feedback: robertidara217@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6cc40c52-6473-4ded-a1b3-214b0210293b-annotated_cf010ca4-3c59-4272-94e8-793d9ca399ea.png?etag=2255909771ed61134753bdaf5ec6bf6c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6cc40c52-6473-4ded-a1b3-214b0210293b-annotated_cf010ca4-3c59-4272-94e8-793d9ca399ea.png?etag=2255909771ed61134753bdaf5ec6bf6c)*

**Browser**: Chrome 95 (Android 7.1)
**Screen size**: 360x640
**Browser size**: 360x560
**[Open #684 in Usersnap](https://app.usersnap.com/l/feedback/308c1a91-b4d7-4b93-9737-89d6c0d83198?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
