### ISSUE TITLE
[FEATURE REQUEST] vMario@@nauticmc

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5891]
**Taken at**: https://gleev.xyz/ypp?referrerId=47429
**Fields**:
- ¿Qué característica te estás perdiendo?: vMario@@nauticmc
- ¿Qué problema resolvería eso para ti?: Donovanjadx
- Share your Email or Discord so we can get in touch: Donovanjaftp123
- Your Gleev channel ID or Title: https://www.youtube.com/@vMario_nauticmc

**Browser**: Chrome 102 (Android 12)
**Screen size**: 360x800
**[Open #176 in Usersnap](https://app.usersnap.com/l/feedback/fbca7177-d252-4dff-8574-4999434a7578?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
closed ticket, unpecified concern.
