### ISSUE TITLE
[FEATURE REQUEST] проверте

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5892]
**Taken at**: https://gleev.xyz/channel/26913?tab=Videos
**Fields**:
- Какой функциональности вам не хватает?: проверте
- Какую проблему мы можем решить для вас?: нету оплаты в джеях
- Share your Email or Discord so we can get in touch: djsuhov88@gmail.com
- Your Gleev channel ID or Title: victorolga88

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1280x1024
**[Open #177 in Usersnap](https://app.usersnap.com/l/feedback/73c771cb-184f-475d-b9a3-b1525b543b3f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as creator creates duplicated issues.
