### ISSUE TITLE
[USERSNAP] i can not sign up thought i do not  create a account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5894]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: i can not sign up thought i do not  create a account 
- Expected Result: This YouTube channel is already signed up and connected with Joystream membership. Report this to Support channel for help.
- Your Channel and Account Details: Asadashaduzzaman4@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1536x864
**[Open #686 in Usersnap](https://app.usersnap.com/l/feedback/3fef58de-a09b-4eaf-938e-a057d24ec42a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
