### ISSUE TITLE
[USERSNAP] Hola que tal, el 4 de febrero de 2024 cree una cuenta, y nunca me dieron semilla de billetera, ahora se me olvido la contraseña en que formatee mi pc, y no puedo iniciar sesión por que no me acuerdo de la contraseña ni mucho menos me dieron u...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5895]
**Taken at**: https://gleev.xyz/channel/53643?tab=Information
**Fields**:
- Houston, we have a problem.: Hola que tal, el 4 de febrero de 2024 cree una cuenta, y nunca me dieron semilla de billetera, ahora se me olvido la contraseña en que formatee mi pc, y no puedo iniciar sesión por que no me acuerdo de la contraseña ni mucho menos me dieron una semilla de billetera
- Expected Result: Me esperaba que me enviarian un correo para restablecer la contraseña de mi cuenta gleev por que no puedo iniciar sesión y mientras ya perdí mis ingresos
- Your Channel and Account Details: https://youtube.com/@Lealito?si=JysKM1szDab3JZvQ 
rodrigito9@gmail.com
- Email or Discord handle for feedback: rodrigito9@gmail.com

**Browser**: ChromeiOS 121 (iOS)
**Screen size**: 414x896
**[Open #687 in Usersnap](https://app.usersnap.com/l/feedback/a5e937d3-f55e-40ee-9f16-aefa3cb8e23c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Inform the creator to reset password and send instruction to recover seed phrase if misplaced.
