### ISSUE TITLE
[FEATURE REQUEST] O recurso avançar/retornar 10 segundos, ao dar 2 toques rápidos na tela.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5896]
**Taken at**: https://gleev.xyz/video/891532
**Fields**:
- Que dispõem que está faltando?: O recurso avançar/retornar 10 segundos, ao dar 2 toques rápidos na tela.
- O problema teria que resolver para você?: Não apenas para mim, mas também para todos os demais usuários da plataforna GLEEV.
- Share your Email or Discord so we can get in touch: marioclovismail@gmail.com 
- Your Gleev channel ID or Title: https://gleev.xyz/video/963428

**Browser**: Chrome 121 (Android 10)
**Screen size**: 412x869
**[Open #178 in Usersnap](https://app.usersnap.com/l/feedback/af3ba2f5-381b-4910-a066-0e45b8b2dcce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and ask what feature he is referring. Will re-open the ticket once I received a response.
