### ISSUE TITLE
[USERSNAP] Reason: Taking advantage of the program conditions

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5897]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: Reason: Taking advantage of the program conditions
- Expected Result: suspended

Reason: Taking advantage of the program conditions

Look at the channel once again, it should definitely not be suspended because there is nothing wrong, if you are going to continue to suspend it, please delete my account, good luck.
- Your Channel and Account Details: suspended

Reason: Taking advantage of the program conditions

Look at the channel once again, it should definitely not be suspended because there is nothing wrong, if you are going to continue to suspend it, please delete my account, good luck.
- Email or Discord handle for feedback: tasbilal954@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**[Open #688 in Usersnap](https://app.usersnap.com/l/feedback/ae61c763-45ed-409e-9180-2950a0f09a0e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Already assisted. Duplicate issue.
