### ISSUE TITLE
[USERSNAP] Cuando le doy en verificar me dice la contraseña debe cumplir con los requisitos que y yo lo puse todo bien

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5898]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Cuando le doy en verificar me dice la contraseña debe cumplir con los requisitos que y yo lo puse todo bien
- Expected Result: Que me dejara crear mi cuenta
- Your Channel and Account Details: @emojiamarillo
- Email or Discord handle for feedback: Ciclistas.ron@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 385x854
**[Open #689 in Usersnap](https://app.usersnap.com/l/feedback/c8b76626-528f-4670-92e2-9ce68639cecb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator and let them know that they didn't meet the minimum requirements of the platform. Advise them to try again once the requirements are met.
