### ISSUE TITLE
[USERSNAP] No puedo ganar dinero con los videos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5902]
**Taken at**: https://gleev.xyz/channel/26231?tab=Videos
**Fields**:
- Houston, we have a problem.: No puedo ganar dinero con los videos
- Expected Result: Quiero ganar dinero con los videos
- Your Channel and Account Details: Soy un argentino con 20 suscrictores
- Email or Discord handle for feedback: Matteoalessandrolobos@gmail.com 

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x800
**[Open #690 in Usersnap](https://app.usersnap.com/l/feedback/40da6c18-bca6-428e-bc60-6447e03056b8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
