### ISSUE TITLE
[USERSNAP] My videos do not appear on my channel on this page.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5905]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: My videos do not appear on my channel on this page.
- Expected Result: Very good my videos are not reflected in my panel of the web, I am already a verified player of bronze rank, and I have many videos but in the profile I get 0
- Your Channel and Account Details: ID UCHZhs7xyllvw4tFq1cEQhMQ
Mail gamesderiris@gmail.com
Membresia Nivel bronce
- Email or Discord handle for feedback: deirispantini@gmail.com

**Browser**: Opera 106 (Windows 10)
**Screen size**: 2560x1440
**[Open #691 in Usersnap](https://app.usersnap.com/l/feedback/1f42e639-f60a-4632-ad58-6c87de215c60?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Advise the creator that the issue is already addressed and the team is already working on it.
