### ISSUE TITLE
[FEATURE REQUEST] 15$

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5906]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Quelle fonctionnalité vous manque?: 15$
- Quel problème cela résoudrait-il pour vous?: لايتم دفع لي وايضا احالات التي جلبتها راجعو حسابي 
- Share your Email or Discord so we can get in touch: Attarhocin10@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBGaUFKsNRsF8UuJ94Q4h

**Browser**: Chrome 118 (Android 10)
**Screen size**: 360x760
**[Open #179 in Usersnap](https://app.usersnap.com/l/feedback/11a3f6c0-e1bd-4c92-951b-d37f8bfa8b6e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item Informed the creator about rewards updates.
