### ISSUE TITLE
[FEATURE REQUEST] no

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5914]
**Taken at**: https://gleev.xyz/
**Fields**:
- Какой функциональности вам не хватает?: no
- Какую проблему мы можем решить для вас?: no
- Share your Email or Discord so we can get in touch: no
- Your Gleev channel ID or Title: noo

**Browser**: Safari 16 (iOS)
**Screen size**: 375x812
**[Open #180 in Usersnap](https://app.usersnap.com/l/feedback/bd458454-da2b-49fd-83ef-bf8eb58103b8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
no details provided, therefore no assistance can be provided.
