### ISSUE TITLE
[USERSNAP] 3luismontiel@gmail.com

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5915]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: 3luismontiel@gmail.com
- Expected Result: Que me ayude a hacer un youtuber de verdad y a ganar dinero
- Your Channel and Account Details: Cel un youtuber de verdad

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x806
**[Open #694 in Usersnap](https://app.usersnap.com/l/feedback/2405a8c7-3d28-4406-a6c9-3f580363e28b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
