### ISSUE TITLE
[USERSNAP] Look at my balance, I have a zero balance - when will there be rewards and accruals?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5916]
**Taken at**: https://gleev.xyz/channel/26913?tab=Videos
**Fields**:
- Houston, we have a problem.: Look at my balance, I have a zero balance - when will there be rewards and accruals?
- Expected Result: Look at my balance, I have a zero balance - when will there be rewards and accruals?
- Your Channel and Account Details: Look at my balance, I have a zero balance - when will there be rewards and accruals?
- Email or Discord handle for feedback: djsuhov88@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1280x1024
**[Open #695 in Usersnap](https://app.usersnap.com/l/feedback/89705024-aa2e-4b23-8b86-73867dd89cc1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
still checking

**Comment by rchrdcstro** [comment]
Action Item: Check records and creator signed-up last year of August. Inform the creator that payout period has already been passed for a long time.
