### ISSUE TITLE
[USERSNAP] My Account from DIAMOND Tier becomes GOLD, why this is happen?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5920]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: My Account from DIAMOND Tier becomes GOLD, why this is happen?
- Expected Result: what happen, you guys changed my tier without notification First, what happen ith this platform? my video payment from $16 to $5
- Your Channel and Account Details: 3way Asiska 

j4SeiVkLidnZnKPM6GKwKGb2DP8Bf1Ykf466UzUWwE8LSZ86b
- Email or Discord handle for feedback: Fianakbar51@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0c588b6d-2607-4816-b075-96cf86b768ec-annotated_1702a1a2-70da-4695-b137-51ed0afc1dfd.png?etag=8df67502eef03cd94f1c80fba0d4c7ac)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/0c588b6d-2607-4816-b075-96cf86b768ec-annotated_1702a1a2-70da-4695-b137-51ed0afc1dfd.png?etag=8df67502eef03cd94f1c80fba0d4c7ac)*

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x945
**[Open #696 in Usersnap](https://app.usersnap.com/l/feedback/21d47402-5578-4a71-80d8-4f1e5b4b982e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Notify the creator that the team has conducted a comprehensive reevaluation across all channels and adjusted their status to align with current quality standards and requirements.
