### ISSUE TITLE
[USERSNAP] Hesapa giremiyorum

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5921]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Hesapa giremiyorum
- Expected Result: Hesapa gircek
- Your Channel and Account Details: fatihr25duman@gmail.com
- Email or Discord handle for feedback: fatihr25duman@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 393x873
**[Open #697 in Usersnap](https://app.usersnap.com/l/feedback/1d415a01-3daa-4183-8945-90f04f0397cd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
