### ISSUE TITLE
[USERSNAP] Приостановили синхронизацию с Ютуба 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5922]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Приостановили синхронизацию с Ютуба 
- Expected Result: Подключить 
- Your Channel and Account Details: mrsellos2012@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x800
**[Open #698 in Usersnap](https://app.usersnap.com/l/feedback/3f848ee2-a4f6-45ee-bf0c-e2049db70ac8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
