### ISSUE TITLE
[USERSNAP] My Account from DIAMOND Tier turned into GOLD, why this is happen

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5923]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: My Account from DIAMOND Tier turned into GOLD, why this is happen
- Expected Result: Please help!
- Your Channel and Account Details: 3way Asiska
- Email or Discord handle for feedback: Fianakbar51@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/72a54f73-6d97-4e39-ac44-ab26331f0eb4-annotated_37d10b41-0178-4c80-b807-e3e5c8e4d32c.png?etag=8a8d99b45b3b88464dd6475427a5e6e1)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/72a54f73-6d97-4e39-ac44-ab26331f0eb4-annotated_37d10b41-0178-4c80-b807-e3e5c8e4d32c.png?etag=8a8d99b45b3b88464dd6475427a5e6e1)*

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x945
**[Open #699 in Usersnap](https://app.usersnap.com/l/feedback/0164c0cc-c5c4-4d6e-b403-7a5a98368593?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the team has conducted a comprehensive reevaluation across all channels and adjusted their status to align with current quality standards and requirements
