### ISSUE TITLE
[USERSNAP] что значит првепка приостановлена

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5924]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: что значит првепка приостановлена
- Expected Result: приостановлена проверка причина нарушение авторских прав это что мой канал не пройде проверку больше?
- Your Channel and Account Details: utliptrfkj@gmail.com

**Browser**: Yandex.Browser 24 (Windows 10)
**Screen size**: 1366x768
**[Open #700 in Usersnap](https://app.usersnap.com/l/feedback/8a0cc3e9-839a-4902-8cc3-d90146c624a7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
