### ISSUE TITLE
[USERSNAP] Although there are 2 videos on my Yotube Channel and over 50 subscribers, and although it has been over 1 month for a long time, the conditions were not accepted. Please accept I want to produce content here.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5925]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Although there are 2 videos on my Yotube Channel and over 50 subscribers, and although it has been over 1 month for a long time, the conditions were not accepted. Please accept I want to produce content here.
- Expected Result: I request verification of my channel.
- Your Channel and Account Details: narhanimneysen@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/581b84d2-6152-43a3-8a98-0b5f8bf9d7a2-annotated_581aad5c-4a89-4355-b6a7-e0080d762d9c.png?etag=737932acb25c5dcc09190c0967fdff22)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/581b84d2-6152-43a3-8a98-0b5f8bf9d7a2-annotated_581aad5c-4a89-4355-b6a7-e0080d762d9c.png?etag=737932acb25c5dcc09190c0967fdff22)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1600x773
**[Open #701 in Usersnap](https://app.usersnap.com/l/feedback/f3428568-210b-4c4e-8c46-add0ba7663bb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
