### ISSUE TITLE
[USERSNAP] I have over 50 subscribers. Why can’t I partner?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5926]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I have over 50 subscribers. Why can’t I partner?
- Expected Result: A fantastic partnership with gleev
- Your Channel and Account Details: Luxurious Hair NY / @LuxuriousHairNY
- Email or Discord handle for feedback: luxurioushair@msn.com

**Browser**: Safari 17 (iOS)
**Screen size**: 428x926
**[Open #702 in Usersnap](https://app.usersnap.com/l/feedback/77feb347-caa0-4b85-bb97-e5d1b86628aa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
