### ISSUE TITLE
[USERSNAP] When I want to link my YouTube channel, it always gives the error Authentication failed. Yesterday I created an account with this same email, but today, even having the recovery words, it says that it does not exist, I had to create a new one...

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5927]
**Taken at**: https://gleev.xyz/legal/tos
**Fields**:
- Houston, we have a problem.: When I want to link my YouTube channel, it always gives the error Authentication failed. Yesterday I created an account with this same email, but today, even having the recovery words, it says that it does not exist, I had to create a new one and now it won&#39;t let me link my channel.
- Expected Result: Link my youtube channel
- Your Channel and Account Details: EBALIA, ebaliass, lucasapelichi@gmail.com
- Email or Discord handle for feedback: lucasapelichi@gmail.com

**Browser**: Opera 107 (Windows 10)
**Screen size**: 1280x1024
**[Open #703 in Usersnap](https://app.usersnap.com/l/feedback/c3e12bdd-44ab-4e87-b812-d75a789dac57?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that membership is associate in Orion. Instruct to sign-in direct to gleev platform in the same credentials.
