### ISSUE TITLE
[USERSNAP] No recuerdo mi contraseña ni mi código de billetera

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5929]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: No recuerdo mi contraseña ni mi código de billetera
- Expected Result: Al darle olvide mi contraseña esperaba las preguntas clásicas de siempre de la confirmación del correo electronico
- Your Channel and Account Details: Suvajech arts
- Email or Discord handle for feedback: Pjeshua26@gmail.com 

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x780
**[Open #704 in Usersnap](https://app.usersnap.com/l/feedback/41007aff-5611-4a34-9e99-039ed2bc37e1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
