### ISSUE TITLE
[USERSNAP] Hello, I have a question

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5930]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: Hello, I have a question
- Expected Result: I want to upgrade my account to Silver. 

Can you tell me one by one what the Silver Conditions are for this, I want to grow my account accordingly. I want to be in the Silver Rank. 
Thank you.
- Your Channel and Account Details: ycanbolat020@gmail.com
- Email or Discord handle for feedback: ycanbolat020@gmail.com

**Browser**: Chrome 121 (Windows 10)
**Screen size**: 1536x864
**[Open #705 in Usersnap](https://app.usersnap.com/l/feedback/8b9bd911-828c-4caf-aa1f-ab44a3baac4c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator on how to upgrade tier.
