### ISSUE TITLE
[USERSNAP] Не даёт выйти из программы

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5933]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Не даёт выйти из программы
- Expected Result: Не даёт выйти из программф
- Your Channel and Account Details: senkovecvlad@gmail.com

**Browser**: Chrome 121 (Linux)
**Screen size**: 412x869
**[Open #706 in Usersnap](https://app.usersnap.com/l/feedback/1021dddd-bc5c-4768-8f6a-3dcefe41ef64?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
