### ISSUE TITLE
Powered by Joystream

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#5936]
We are getting more and more people who are discovering Gleev through some content, but they may never learn about Joystream. To help with that reverse discovery, can we augment the logo here to have a sort of less visible "powered by joystream" style subtitle, where it is a clickable link? I mean here: 

![308645819-a6c59366-9e47-4bf9-bb85-b608ee825289](https://github.com/Joystream/atlas/assets/437292/25ea31f2-62db-495d-89b5-daec1736eced)

This probaboly means we need more horizontal space for the logo, so if Atlas requires the instance logo to be of a fixed aspect ratio, that should probably be abandoned as a requirement.

**Comment by msmadeline** [comment]
@bedeho Hey, I added the subtitle to the logo and I did 2 versions. Let me know what you think 

➡ https://www.figma.com/file/tBjZ75yZaifK1JwfUTFqFn/Small-issues?type=design&node-id=927-2536&mode=design&t=c5KEyZ10yYQTkrb5-4

**Comment by bedeho** [comment]
A is best I think, do we need a mobile version?

**Comment by msmadeline** [comment]
@bedeho Hey I did RWD for the top navigation with a new logo. I was able to display subtitle form the XS breakpoint. If you approve then I will need to update the original component. 

➡ RWD: https://www.figma.com/file/tBjZ75yZaifK1JwfUTFqFn/Small-issues?type=design&node-id=948-151026&mode=design&t=jyBR29K5Rpw0wT17-4
