### ISSUE TITLE
[FEATURE REQUEST] Video review

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5939]
**Taken at**: https://gleev.xyz/member/martinmax333?tab=NFTs
**Fields**:
- Какой функциональности вам не хватает?: Video review
- Какую проблему мы можем решить для вас?: Hello!
I want to make a video about your service, but for this I need to create another account to initially show the user what’s here and how, tell me, can I create a second account, if not, how can I make a video review so that I don’t get blocked?
- Share your Email or Discord so we can get in touch: martinmax472@gmail.com
- Your Gleev channel ID or Title: j4ScL2R9LbwrxFjLV3fER8YeSr2mgiL64T4epgmrv1H54DuaY

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1600x900
**[Open #181 in Usersnap](https://app.usersnap.com/l/feedback/1cbe448e-79b3-4cb7-9074-60501b2ff709?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
