### ISSUE TITLE
[USERSNAP] ошибка авторских прав

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5940]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: ошибка авторских прав
- Expected Result: Найдено нарушение авторских прав,но это ошибка,можете еще раз проверить,пожалуйста.
- Your Channel and Account Details: valeryk72@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1536x864
**[Open #707 in Usersnap](https://app.usersnap.com/l/feedback/2d3d66fa-2ca6-4370-a501-9ed9bcb559bf?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
