### ISSUE TITLE
[USERSNAP] The system detected a copyright violation

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5941]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: The system detected a copyright violation
- Expected Result: The system detected a copyright violation, but this is an error, please check again.
- Your Channel and Account Details: valeryk72@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/279ff3e6-abab-43c2-a199-f78c85055114-annotated_8b74c107-a856-4fa2-8bef-2409afaa543d.png?etag=c979c7e6781766068fc245a0e37fe8b6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/279ff3e6-abab-43c2-a199-f78c85055114-annotated_8b74c107-a856-4fa2-8bef-2409afaa543d.png?etag=c979c7e6781766068fc245a0e37fe8b6)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x703
**[Open #708 in Usersnap](https://app.usersnap.com/l/feedback/7091a9b2-38b9-4ebb-82b5-c202fb38dcfb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
