### ISSUE TITLE
[USERSNAP] Не могут проверить канал

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5942]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Не могут проверить канал
- Expected Result: Чтобы проверили и длпустили к эксплатации
- Your Channel and Account Details: https://youtube.com/@Lenok_13?si=RElAL38g1YT8w_gf
- Email or Discord handle for feedback: borovkova.len4ok@mail.ru

**Browser**: Chrome 122 (Android 10)
**Screen size**: 385x854
**[Open #709 in Usersnap](https://app.usersnap.com/l/feedback/ce31182b-70b1-4044-bdbd-35eeeb9c9095?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
