### ISSUE TITLE
[USERSNAP] Comida receitas 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5943]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Comida receitas 
- Expected Result: Como vcs decidirem o melhor 
- Your Channel and Account Details: Vitoria 
- Email or Discord handle for feedback: vitoriaschorn3@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x760
**[Open #710 in Usersnap](https://app.usersnap.com/l/feedback/ca4b8d42-46c8-4daa-b379-491b1a57380d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
