### ISSUE TITLE
[FEATURE REQUEST] Estou com problemas na palavra passe nao me lembro

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5944]
**Taken at**: https://gleev.xyz/
**Fields**:
- Que dispõem que está faltando?: Estou com problemas na palavra passe nao me lembro
- O problema teria que resolver para você?: Sim
- Share your Email or Discord so we can get in touch: Cleriasantos67C@gmail.com 
- Your Gleev channel ID or Title: biblia@123

**Browser**: Chrome 117 (Android 10)
**Screen size**: 412x915
**[Open #182 in Usersnap](https://app.usersnap.com/l/feedback/40d65099-e0a2-44b9-93d3-936cb46a65ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
