### ISSUE TITLE
[FEATURE REQUEST] Algumas melhorias nos links de divulgação 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5945]
**Taken at**: https://gleev.xyz/channel/56344?tab=Videos
**Fields**:
- Que dispõem que está faltando?: Algumas melhorias nos links de divulgação 
- O problema teria que resolver para você?: Melhorar os links de divulgação que senpre está dando erro quando vou divulgar em outras plataformas 
- Share your Email or Discord so we can get in touch: Adelsonsodre64@gmail.com
- Your Gleev channel ID or Title: Ester e Dara 

**Browser**: Chrome 122 (Android 10)
**Screen size**: 385x854
**[Open #183 in Usersnap](https://app.usersnap.com/l/feedback/f10dc06f-fbe5-4a24-b551-5f89756b571c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Communicated with CWG Lead and this feature will not worked.
