### ISSUE TITLE
[USERSNAP] Olá, o que faço para não ficar suspenso?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5949]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Olá, o que faço para não ficar suspenso?
- Expected Result: Eu não sabia que poderia ser suspenso, o que faço?
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFB1uPhSGW8cedcAJPEEph
- Email or Discord handle for feedback: edglaysonsilva@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/48bdc37d-5265-4c52-9969-e87d96f3639b-annotated_d991177f-1bad-42bb-9da2-5ebeef52d878.png?etag=b8aa3669391cc34573f2def0c1956eb7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/48bdc37d-5265-4c52-9969-e87d96f3639b-annotated_d991177f-1bad-42bb-9da2-5ebeef52d878.png?etag=b8aa3669391cc34573f2def0c1956eb7)*

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x722
**[Open #711 in Usersnap](https://app.usersnap.com/l/feedback/60d7b4b1-0dae-4338-a62e-6a139bc3058d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
