### ISSUE TITLE
General responsive tweaks

### ISSUE THREAD

**Issue by mikkio-j** [Joystream/atlas#595]
During testing of responsiveness we've found some things that need to be improved, here is the list:

- ~~Signin~~
  - ~~Coins on small screen should not be visible (found in:  `join?step=0`)~~
  ~~(it should follow RWD from design:~~ (covered in: #626 )
[https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7677%3A2556](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=7677%3A2556))
<img src="https://user-images.githubusercontent.com/59691518/117788462-b68c4400-b247-11eb-8963-7028bd0612d9.png" width="200" />

  - ~~Dialog's content not scrollable - covered in other issue (#477) (found in: `join?step=2`)~~
  - ~~Joystream logo not aligned on smaller screens~~ (covered in: #626 )
 <img src="https://user-images.githubusercontent.com/59691518/117788600-d1f74f00-b247-11eb-86a2-ed2e095ccae1.png" width="200" />

- New channel
  - Select for language and privacy for smaller screens (some languages are not visible as well as second item in privacy)
  <img src="https://user-images.githubusercontent.com/59691518/117788644-dc194d80-b247-11eb-9f0d-b8d5ad78f502.png" width="200" />

- ~~My videos~~
  - ~~no videos svg illustration overflow (horizontal scroll)~~
- ~~Video sheet~~
  - ~~"Add new video" should not be visible on smaller screens~~ (covered in: #633  )
- Uploads view
  - Needs some general tweaks in upload bars and dropdown (not covered in designs). We've discussed that during one of the meetings and came to conclusion that it's not in the scope of sumer release

**Comment by drillprop** [comment]
`Topbar` should be scrollable. If I have a lot of channels I can't click logout on smaller screens.
![image](https://user-images.githubusercontent.com/51168865/117816874-48f01000-b267-11eb-8b71-e54411f07a2c.png)
