### ISSUE TITLE
[USERSNAP] Dorlamayeri kendikedine açlp kapanıyor

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5951]
**Taken at**: https://gleev.xyz/ypp?state=code%3Dcizi42gar%26channelId%3D&code=4/0AeaYSHDTtw6F_lewYqW-BX3sgZXez9piBjDgAE4ypdm2SBFE55tbWOWeW7cHVszBsWUW4A&scope=email%20openid%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- Houston, we have a problem.: Dorlamayeri kendikedine açlp kapanıyor
- Expected Result: Hesaplarken şire dorlamayeri kendikedine açlp kapnıyor
- Your Channel and Account Details: Yildirimtakimi183@gmail.com
- Email or Discord handle for feedback: Yildirimtakimi183@gmail.com

**Browser**: Chrome 120 (Android 10)
**Screen size**: 360x720
**[Open #712 in Usersnap](https://app.usersnap.com/l/feedback/88dcde59-d5b9-4d74-ab67-5361b4fa01b7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
