### ISSUE TITLE
[USERSNAP] No puedo subir un video

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5953]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: No puedo subir un video
- Expected Result: Se enviará al reducir los gráficos del video 
- Your Channel and Account Details: Depredador215

**Browser**: Chrome 122 (Android 10)
**Screen size**: 384x854
**[Open #713 in Usersnap](https://app.usersnap.com/l/feedback/bb1ffaef-e702-4fc2-bdc7-b0e0e64f834b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Details incomplete, can't find the youtube channel and details to check.
