### ISSUE TITLE
Idea: Follow @JoystreamDAO X profile within YPP sign-up flow

### ISSUE THREAD

**Issue by leetjoy** [Joystream/atlas#5955]
**Is your feature request related to a problem? Please describe.**

Issues to address:

- Lack of connection between creators and the Joystream ecosystem.
- Low engagement and participation of creators with X.

**Describe the solution you'd like**

I propose incorporating a button within the YPP sign-up flow labeled `Follow Joystream X`, which will redirect users to https://twitter.com/joystreamdao.

**Additional context**

Currently, we are experiencing an average of 100 sign-ups daily. I believe this could contribute to social media growth, engagement with X, and overall add significant value to Joystream.
**optional:** We could even consider rewarding creators for such actions by implementing an automated tracking tool (similar to those on Gleam, Zealy, etc.) which will check whether creators followed the profile and reward creators with some JOY. (for example if their tier bronze and above).
This will also increase the efficiency of creator growth campaigns, as it will contribute slightly to the growth of Joystream X.

**Comment by dmtrjsg** [comment]
Added to dashboard of tasks, seems to be working okay.. I am not sure if we need to drive users away from the app right after sign up.. 
<img width="484" alt="Screenshot 2024-05-27 at 19 39 14" src="https://github.com/Joystream/atlas/assets/93924525/58c1d4d8-dcdf-43ca-93d3-c54ef2fcd8be">
