### ISSUE TITLE
[USERSNAP] My channel was suspended 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5958]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: My channel was suspended 
- Expected Result: Good Afternoon, my channel is suspended I don&#39;t understand why it says copyright but there is no problem on my YouTube channel! I even deleted everything and I made new videos and it&#39;s still suspended! I wanted to know if it is possible to do something? Is there a solution for this or will it never change?
- Your Channel and Account Details: kobockovdmitrij@gmail.com
- Email or Discord handle for feedback: kobockovdmitrij@gmail.com

**Browser**: Safari 16 (iOS)
**Screen size**: 428x926
**[Open #714 in Usersnap](https://app.usersnap.com/l/feedback/0cdf36cd-8684-47e5-bccb-a73e6ba55c99?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
