### ISSUE TITLE
[USERSNAP] Channel suspended 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5959]
**Taken at**: https://gleev.xyz/channel/56297?tab=Videos
**Fields**:
- Houston, we have a problem.: Channel suspended 
- Expected Result: I have my channel YouTube suspended because of copyright violation I deleted all videos with copyright violations on my YouTube channel I want to register as a new please 
- Your Channel and Account Details: @InstaMood-NH kobockovdmitrij@gmail.com
- Email or Discord handle for feedback: kobockovdmitrij@gmail.com

**Browser**: ChromeiOS 122 (iOS)
**Screen size**: 375x667
**[Open #715 in Usersnap](https://app.usersnap.com/l/feedback/8d469e2e-d7fc-4a55-b2a2-ddf9f055c93c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
