### ISSUE TITLE
[FEATURE REQUEST] YPPA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5961]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: YPPA
- What problem would that solve for you?: why is my channel suddenly bronze, originally my channel was Silver, my channel has been around for a long time
- Share your Email or Discord so we can get in touch: Adesumantry88@gmail.com
- Your Gleev channel ID or Title: Sultan Rebahan

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/504459e5-bdda-4cae-8e26-cbbb5fe61ac3-annotated_f8480c3c-c390-4dc8-91d3-bcec2b116db6.png?etag=e9ca77e32eb3932547087a85dfa39be1)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/504459e5-bdda-4cae-8e26-cbbb5fe61ac3-annotated_f8480c3c-c390-4dc8-91d3-bcec2b116db6.png?etag=e9ca77e32eb3932547087a85dfa39be1)*

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x825
**Browser size**: 360x698
**[Open #185 in Usersnap](https://app.usersnap.com/l/feedback/c723debc-9612-4b6b-baa3-82cccc836be9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the team has conducted a comprehensive reevaluation across all channels and adjusted their status to align with current quality standards and requirements.
