### ISSUE TITLE
[FEATURE REQUEST] YPPA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5962]
**Taken at**: https://board.usersnap.com/tZNWrBYXJAAHUiTo#/
**Fields**:
- Which feature are you missing?: YPPA
- What problem would that solve for you?: why is my channel suddenly bronze, originally my channel was Silver, my channel has been around for a long time
- Share your Email or Discord so we can get in touch: Adesumantry88@gmail.com
- Your Gleev channel ID or Title: Sultan Rebahan

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x825
**[Open #186 in Usersnap](https://app.usersnap.com/l/feedback/4f8383c9-3a70-4def-80d2-d6f1cc7a50a2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Closed this ticket as issue is duplicated.
