### ISSUE TITLE
[USERSNAP] YPPA Tier

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5963]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: YPPA Tier
- Expected Result: why is my channel suddenly bronze, originally my channel was Silver, my channel has been around for a long time
- Your Channel and Account Details: Sultan Rebahan,  j4To6jgKfy8MgiMRDXzc15ggN8AnFBWUKbaP4fSfT4z1SZmFj
- Email or Discord handle for feedback: Sultanrebahan88@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a6ebcca0-50e5-4e2c-9be6-d206bf8bfed0-annotated_fbad11c9-3a78-4fce-8f21-2f5cb4fedf40.png?etag=8bba14b9424ffc3839b2a0958724a259)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/a6ebcca0-50e5-4e2c-9be6-d206bf8bfed0-annotated_fbad11c9-3a78-4fce-8f21-2f5cb4fedf40.png?etag=8bba14b9424ffc3839b2a0958724a259)*

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x825
**Browser size**: 360x754
**[Open #716 in Usersnap](https://app.usersnap.com/l/feedback/851fe9b3-a1fe-4862-88b7-1ad63d6484db?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the team has conducted a comprehensive reevaluation across all channels and adjusted their status to align with current quality standards and requirements.
