### ISSUE TITLE
[USERSNAP] desejo cancelar a assinatura 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5964]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: desejo cancelar a assinatura 
- Expected Result: cancelar assinatura 
- Your Channel and Account Details: zoodesenhosinfantil@gmail.com
- Email or Discord handle for feedback: marianaramon.vitoria@yahoo.com.br

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1536x864
**[Open #717 in Usersnap](https://app.usersnap.com/l/feedback/7af1fb35-1db3-4e94-ad63-49e9800b43c0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
