### ISSUE TITLE
[USERSNAP] no se sincronizan mis videos viejos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5965]
**Taken at**: https://gleev.xyz/channel/57581?tab=Videos
**Fields**:
- Houston, we have a problem.: no se sincronizan mis videos viejos
- Expected Result: se trendian que subir todos mis videos de youtube a gleev
- Your Channel and Account Details: j4T4LtCREECSp2UwjQEEjVLESgeiFsoNXHMFogrABhzatpBNo
- Email or Discord handle for feedback: agustincho13255@gmail.com

**Browser**: Firefox 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #718 in Usersnap](https://app.usersnap.com/l/feedback/8b123401-d503-4492-bc3b-e27cc667a081?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the channel is still pending verification. Advise the creator to wait for up to 48 hours, and once approved, syncing of the videos will commence.
