### ISSUE TITLE
[USERSNAP] Lowered the level

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5966]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Lowered the level
- Expected Result: Lowered the level to &#34;bronze&#34; Why did this happen?
- Your Channel and Account Details: @icoline8293  https://www.youtube.com/channel/UCcs5JTQEcTQnYSKeWIyXcwQ
- Email or Discord handle for feedback: kotlyar.1995@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #719 in Usersnap](https://app.usersnap.com/l/feedback/72da2248-ae79-495d-9a94-bbe5690172fc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the team has conducted a comprehensive reevaluation across all channels and adjusted their status to align with current quality standards and requirements.
