### ISSUE TITLE
[USERSNAP] quiero eliminar mi cuenta y no me deja

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5967]
**Taken at**: https://gleev.xyz/channel/55000?tab=Videos
**Fields**:
- Houston, we have a problem.: quiero eliminar mi cuenta y no me deja
- Expected Result: no encuentro la opción
- Your Channel and Account Details: https://gleev.xyz/channel/55000?tab=Videos

no e cobrado nada y quiero eliminar mi cuenta
- Email or Discord handle for feedback: okaeritalleres@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #720 in Usersnap](https://app.usersnap.com/l/feedback/680ea840-989e-4922-a0d0-09fd5f262305?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Checked the channel and already opted out. No further actions required.
