### ISSUE TITLE
[USERSNAP] I want to delete my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5968]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: I want to delete my account
- Expected Result: I can&#39;t find the option to delete my account
- Your Channel and Account Details: 
I have not collected any of the money obtained, I want to delete my account and have it no longer synchronized with my YouTube channel, I deactivated it a while ago but it reactivated itself
- Email or Discord handle for feedback: okaeritalleres@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #721 in Usersnap](https://app.usersnap.com/l/feedback/9851c264-4235-47c2-9670-134376ff5d40?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Duplicated issue.
