### ISSUE TITLE
[FEATURE REQUEST] Muito bom

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5969]
**Taken at**: https://gleev.xyz/
**Fields**:
- Que dispõem que está faltando?: Muito bom
- O problema teria que resolver para você?: Não tem
- Share your Email or Discord so we can get in touch: janainamartinsdeoliveira120@gmail.com
- Your Gleev channel ID or Title: https://youtube.com/@janainamartinsdeoliveira5090?si=f9zvZKilZSz5cvJw

**Browser**: Chrome 122 (Android 10)
**Screen size**: 347x733
**[Open #187 in Usersnap](https://app.usersnap.com/l/feedback/316dd32b-37b9-4dac-9f8f-8e1c37bce197?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator via email and ask how I can offer help as there is open ticket. Closed this ticket issue due to issue unspecified,
