### ISSUE TITLE
[USERSNAP] Login error

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5970]
**Taken at**: https://gleev.xyz/channel/55123?tab=Videos
**Fields**:
- Houston, we have a problem.: Login error
- Expected Result: Que me deje entrar a mi cuenta o que me deje cambiar la contraseña
- Your Channel and Account Details: JuanRodGames 
D4e8cFQCrwQyANm
Juanrodgames0407@gmail.com
No me deja iniciar sesión ni cambiar contraseña.
- Email or Discord handle for feedback: Juanrodgames0407@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 384x832
**[Open #722 in Usersnap](https://app.usersnap.com/l/feedback/8aa1467d-2023-4c1c-bb55-8ec0a371c457?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
