### ISSUE TITLE
Notifications: user received duplicate/multiple notifications for content being featured

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#5971]
SSIA
![image](https://github.com/Joystream/atlas/assets/50830161/13ce8c72-ef73-41fd-9b90-7a3b26ed65c3)

```Hi, I received 5 notifications "You NFT was featured in the marketplace section..." for the same NFT
First on Feb 29, then March 5, March 6, and 2 notifications on March 8th
Both Gleev notifications and email. Just saying```

**Comment by kdembler** [comment]
Same here

![CleanShot 2024-03-11 at 12 26 48@2x](https://github.com/Joystream/atlas/assets/12646744/b8a7664f-bc3a-4924-9926-adcbd57868c1)
