### ISSUE TITLE
[USERSNAP] Copyright breach

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5976]
**Taken at**: https://gleev.xyz/studio/channel?tab=General
**Fields**:
- Houston, we have a problem.: Copyright breach
- Expected Result: Why my channel is suspended because all My own Record content I posted. 
- Your Channel and Account Details: sraikynohay@gmail.com
- Email or Discord handle for feedback: sraikynohay@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x800
**[Open #723 in Usersnap](https://app.usersnap.com/l/feedback/d3f1112e-064a-4166-9b0b-6772fe5a1cbd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
