### ISSUE TITLE
[FEATURE REQUEST] Ganhos

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5979]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Que dispõem que está faltando?: Ganhos
- O problema teria que resolver para você?: When do earnings from synchronization, referrals and posts on YouTube enter my account???
- Share your Email or Discord so we can get in touch: kdulee25@gmail.com
- Your Gleev channel ID or Title: 57033

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #188 in Usersnap](https://app.usersnap.com/l/feedback/980f3e24-8922-4fc8-b301-786487de0753?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their rewards. The rewards were settled 03/13/24 and sent the instruction to check the payment.
