### ISSUE TITLE
[USERSNAP] Suspended  Reason: Misleading content

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5980]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Suspended  Reason: Misleading content
- Expected Result: Suspended

Reason: Misleading contentnao concordo tenho meu youtube a anos, e vc diz que e falso vc esta errado 
- Your Channel and Account Details: Suspended

Reason: Misleading contentnao concordo tenho meu youtube a anos, e vc diz que e falso vc esta errado , espero que verifique novamente, espero que sem demora tb
- Email or Discord handle for feedback: https://gleev.xyz/studio/ypp/dashboard

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #724 in Usersnap](https://app.usersnap.com/l/feedback/97332e76-2eff-4d93-bbee-1cc21be8d027?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: This ticket has been closed since there is no way to check or contact the creator. No YouTube link or email address was provided.
