### ISSUE TITLE
[FEATURE REQUEST] Payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5981]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: Payment
- What problem would that solve for you?: why is there no referral bonus payment?
- Share your Email or Discord so we can get in touch: wekibow@gmail.com

**Browser**: Chrome 106 (Android 6.0.1)
**Screen size**: 360x640
**[Open #189 in Usersnap](https://app.usersnap.com/l/feedback/a7d2c4df-613f-4620-a449-ba4d5fa31ae2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator to share referral dashboard through dm. Will leave the ticket pending for 48 hours more to wait for creator to get back,
