### ISSUE TITLE
"time to like/comment" should be reduced

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#5982]
When liking a video it generally takes ~30 seconds to finish this action. There are obviously architecture reasons for this but it seems like an extremely long amount of time and I think for someone not familiar with our project they would assume that it hasn't worked.

* Perhaps the UI could be changed to better reflect that this will take some time and the user doesn't need to be concerned?
* Is there any way to get finalization sooner?
* The user can navigate away while this is still waiting and it will apparently work just fine, why don't we just show users it has succeeded a lot quicker?
* It seems the likelihood of failure for this once the TX has been successfully submitted is going to be like <1% so shouldn't the UX be based around 99% success rate instead of making a user wait ~30 seconds just to see that it succeeded?

**Comment by ikprk** [comment]
Duplicate
