### ISSUE TITLE
[USERSNAP] My 2$ signup bonus was issued on 12 march but unfortunately it's not issued please recheck and issued my reward 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5983]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: My 2$ signup bonus was issued on 12 march but unfortunately it&#39;s not issued please recheck and issued my reward 
- Expected Result: Excellent
- Your Channel and Account Details: barikhatri500@gmail.com

**Browser**: Chrome 117 (Android 10)
**Screen size**: 360x800
**[Open #725 in Usersnap](https://app.usersnap.com/l/feedback/5810a143-2c8b-4823-ac21-06d87d2f519f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards were settled 03/13/24 and sent the instruction to check the payment.
