### ISSUE TITLE
[USERSNAP] Can't login 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5984]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Can&#39;t login 
- Expected Result: I thought i created an account, I connected my YouTube channel, I&#39;ve had an email from you, but when I try to login it won&#39;t let me! 
- Your Channel and Account Details: JohnVDenley?
- Email or Discord handle for feedback: JohnVDenley@googlemail.com 

**Browser**: Chrome 122 (Android 10)
**Screen size**: 384x854
**[Open #726 in Usersnap](https://app.usersnap.com/l/feedback/6e37a38f-9abc-49cd-bc4a-92c9710e68f8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
