### ISSUE TITLE
[USERSNAP] Ignore my last message, seems like maybe the account hadn't been created when I last tried to login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5985]
**Taken at**: https://gleev.xyz/member/id/5456?tab=NFTs
**Fields**:
- Houston, we have a problem.: Ignore my last message, seems like maybe the account hadn&#39;t been created when I last tried to login
- Expected Result: It&#39;s OK now
- Your Channel and Account Details: John V Denley
- Email or Discord handle for feedback: JohnVDenley@googlemail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 384x854
**[Open #727 in Usersnap](https://app.usersnap.com/l/feedback/e1e52df1-855f-4774-ac52-b7850ec406f4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action: Closed ticket as issue is already resolved.
