### ISSUE TITLE
[USERSNAP] I didn't receive my payment!

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5990]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: I didn&#39;t receive my payment!
- Expected Result: I have done all the withdrawal steps but I couldn&#39;t receive the payment yet.. also received your email for withdrawal. 

This is the my Gate.io deposit address: j4UWPJ9MD2szRExtiYPEoTqaLQJzv3W42TuFUMUMzbUmzktuZ 

But still waiting for a withdrawal..

I was creating the video about your website but I&#39;m very disappointed from your side. 
- Your Channel and Account Details: Mr Kjee Secrets Vlogs, mrkjeesecrets@gmail.com 
- Email or Discord handle for feedback: mrkjeesecrets@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a1086cb-c2f2-4254-b688-c4df27698967-annotated_e3aa5dba-aa06-49fb-9c9d-7e69bd38681c.png?etag=9ef70e19093bc4d36a29499281bc59f1)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a1086cb-c2f2-4254-b688-c4df27698967-annotated_e3aa5dba-aa06-49fb-9c9d-7e69bd38681c.png?etag=9ef70e19093bc4d36a29499281bc59f1)*

**Browser**: Chrome 117 (Android 10)
**Screen size**: 412x846
**Browser size**: 412x774
**[Open #728 in Usersnap](https://app.usersnap.com/l/feedback/eea28b5d-da38-4533-8770-628e065f4c3b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item : Informed the creator to contact exchange support.
