### ISSUE TITLE
[USERSNAP] me inscrevi nesse programa para entrar com outro canal meu 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5991]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: me inscrevi nesse programa para entrar com outro canal meu 
- Expected Result: um canal que esta feito tudo certinho esse https://www.youtube.com/channel/UC5GLwqzwHXUYpzc7sGaQyPw e acabou entrando com o meu 1 canal esse https://www.youtube.com/channel/UCc-tFhOhSSyur0kPMbtdPBQ, como ele estava cheio de videos sem nexo vcs nao aceitaram meu canal esta suspenso mas eu ja arrumei ele coloquei so renda extra e home office so que aqui no GREEV nao atualiza, o que faço p ser aceita
- Your Channel and Account Details: https://www.youtube.com/channel/UCc-tFhOhSSyur0kPMbtdPBQ
goncalvesluciane@gmail.com
espero que me ajudem 
- Email or Discord handle for feedback: https://gleev.xyz/studio/ypp/dashboard

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #729 in Usersnap](https://app.usersnap.com/l/feedback/86c4a89f-22ad-4adf-ae44-abcf13f35f77?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
