### ISSUE TITLE
[USERSNAP] My withdraw dont come!

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5992]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: My withdraw dont come!
- Expected Result: My last withdraw dont come to MEXC
- Your Channel and Account Details: viituh.rivas@gmail.com
- Email or Discord handle for feedback: victordvrivas@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #730 in Usersnap](https://app.usersnap.com/l/feedback/0666c7ef-c77f-4405-8993-477b9e6c8072?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and informed that it was successful on our end. Checked if he still experience the issue and recomment to contact their exchange support.
