### ISSUE TITLE
[USERSNAP] Tengo error al ingresar la contraseña del correo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#5993]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Tengo error al ingresar la contraseña del correo
- Expected Result: Continuar con el proceso 
- Your Channel and Account Details: ESKETIT
robertnarvaez322@gmail.com
- Email or Discord handle for feedback: robertnarvaez322@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 424x945
**[Open #731 in Usersnap](https://app.usersnap.com/l/feedback/7f1aeb42-4d21-4e35-b5cb-ac12ddc5b5d9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
