### ISSUE TITLE
Better Affilient link preview

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#5994]
Creator requests improving this preview presentation, this is how it looks on Twitter on desktop

<img width="802" alt="Screenshot 2024-03-14 at 10 24 16" src="https://github.com/Joystream/atlas/assets/437292/bf703ea2-1856-44c1-a3ca-0667d37e173b">

**Comment by dmtrjsg** [comment]
Was implemented with showing Gleev logo. Assuming showing thumbnail is not an option? @ikprk

**Comment by ikprk** [comment]
> Was implemented with showing Gleev logo. Assuming showing thumbnail is not an option? @ikprk

It should be possible, it just wasn't in the scope.
