### ISSUE TITLE
[USERSNAP] i have many more channels and i want to join gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6000]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: i have many more channels and i want to join gleev
- Expected Result: i have many more channels and i want to join gleev, can i create more accounts? and can i create accounts through my this refferal link ?
- Your Channel and Account Details: https://gleev.xyz/channel/56693
- Email or Discord handle for feedback: hatech539@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**[Open #732 in Usersnap](https://app.usersnap.com/l/feedback/8ed43ce0-fe4d-4cfa-bb90-8ed1c47d4e3f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that they can add more channel in one membership. Show a screenshot for reference.
