### ISSUE TITLE
[USERSNAP] My withdraw dont come!

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6002]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: My withdraw dont come!
- Expected Result: I got an error when requesting the withdrawal and my balance disappeared and did not arrive in my mexc account
- Your Channel and Account Details: rivasnft
- Email or Discord handle for feedback: viituh.rivas@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/42e3ed3f-1935-46b9-801f-f7ee7d859ca9-annotated_58202006-c394-45ed-8bd4-f0e20e5f9bab.png?etag=0f2c5f35f1d7ea65c2ff077480e0f17b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/42e3ed3f-1935-46b9-801f-f7ee7d859ca9-annotated_58202006-c394-45ed-8bd4-f0e20e5f9bab.png?etag=0f2c5f35f1d7ea65c2ff077480e0f17b)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x945
**[Open #733 in Usersnap](https://app.usersnap.com/l/feedback/3109c5bc-744d-4a4c-a74a-ba1146081896?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I reached out to the creator to inquire if they have received the reward, as delays can occur due to upgrades. I will re-open the ticket if issue still persist.
