### ISSUE TITLE
[USERSNAP] payment reward not recived in gate io exchange

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6003]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: payment reward not recived in gate io exchange
- Expected Result: respected i thanks to happy join gleev

yesterday i make withdaw my all 3 channel but not recive in wallet gate,io still i check wallet right and then withdraw but not recived in exchange these toekn joysteam wallet help me 3 channel same problem tahanks 

hope give me response 

my email 

madihafamilyvlog@gmail.com

all channel in this email

- Your Channel and Account Details: respected i thanks to happy join gleev

yesterday i make withdaw my all 3 channel but not recive in wallet gate,io still i check wallet right and then withdraw but not recived in exchange these toekn joysteam wallet help me 3 channel same problem tahanks 

hope give me response 

my email 

madihafamilyvlog@gmail.com

all channel in this email

- Email or Discord handle for feedback: madihafamilyvlog@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**[Open #734 in Usersnap](https://app.usersnap.com/l/feedback/4878832b-8d10-484a-ad3f-a5a26a6f5ef2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and recommends to contact exchange support. Will re-open the ticket if issue still persist.
