### ISSUE TITLE
[USERSNAP] No puedo ingresar a mi cuenta

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6004]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: No puedo ingresar a mi cuenta
- Expected Result: Solo lo quiero recuperar
- Your Channel and Account Details: don.juego.r@gmail.com
- Email or Discord handle for feedback: don.juego.r@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 412x892
**[Open #735 in Usersnap](https://app.usersnap.com/l/feedback/be3f6b9c-5721-4162-8ae4-932cbe599b70?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
