### ISSUE TITLE
[FEATURE REQUEST] Recuperar la cuenta mediante un codigo al correo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6007]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- ¿Qué característica te estás perdiendo?: Recuperar la cuenta mediante un codigo al correo
- ¿Qué problema resolvería eso para ti?: Facilidad en recuperar mi cuenta
- Share your Email or Discord so we can get in touch: don.juegor@gmail.com
- Your Gleev channel ID or Title: PepitoE.3

**Browser**: Chrome 122 (Android 10)
**Screen size**: 412x915
**[Open #190 in Usersnap](https://app.usersnap.com/l/feedback/aef22237-4a64-41a6-815c-2a67aebaa296?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue.
