### ISSUE TITLE
[USERSNAP] joy coin payment did not arrive

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6008]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: joy coin payment did not arrive
- Expected Result: I made the withdrawal, but the balance has not been transferred to my account for 2 days.

j4WmaxynwD8pRZcTvR1fQsAJXzVEsrQ4yqksy98nFUKAjKmBk
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFBN7K2ixzFQjRhfN4ohrS
- Email or Discord handle for feedback: mustafayla32@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1536x864
**[Open #736 in Usersnap](https://app.usersnap.com/l/feedback/33160eb9-f679-4ebe-88ea-2ef5a086d130?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that transfer was successful on our end. Recommend to contact his exchange support.
