### ISSUE TITLE
[USERSNAP] not paymant

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6009]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: not paymant
- Expected Result: hola hice ayer un retiro y nunca me llego 
- Your Channel and Account Details: https://gleev.xyz/channel/45398?tab=Videos
- Email or Discord handle for feedback: elsapomaluco@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9fd76f8d-af53-4285-a6e6-84ae87c7f57b-annotated_f27b53e2-acc5-4b91-b968-6751e10af181.png?etag=499ab079f6e9d8e317991daf0cbbfd75)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/9fd76f8d-af53-4285-a6e6-84ae87c7f57b-annotated_f27b53e2-acc5-4b91-b968-6751e10af181.png?etag=499ab079f6e9d8e317991daf0cbbfd75)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x641
**[Open #737 in Usersnap](https://app.usersnap.com/l/feedback/6f30b103-b563-4378-903d-02d55aa0610f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator about the status of withdrawal and recommended to contact their exchange support.
