### ISSUE TITLE
[USERSNAP] No puedo registrarme 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6010]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: No puedo registrarme 
- Expected Result: Pues que coloque mi correo electrónico y me dejara registrarme no se que más decir 
- Your Channel and Account Details: torch mixed truck also wait nothing local hammer memory unique permit bleak
- Email or Discord handle for feedback: alcides314565@gmail.com 

**Browser**: Chrome 122 (Android 10)
**Screen size**: 688x1490
**[Open #738 in Usersnap](https://app.usersnap.com/l/feedback/4e6880c7-7cb5-4a1b-8a32-d596d22d6486?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
