### ISSUE TITLE
[USERSNAP] i can't login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6011]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: i can&#39;t login
- Expected Result: why i can&#39;t login to my account? please i need help
- Your Channel and Account Details: my account email is jokerdece666@gmail.com
- Email or Discord handle for feedback: jokerdece666@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #739 in Usersnap](https://app.usersnap.com/l/feedback/103a104e-d7b6-4a26-899c-6cb40f190297?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
