### ISSUE TITLE
[FEATURE REQUEST] Informação

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6012]
**Taken at**: https://gleev.xyz/
**Fields**:
- Que dispõem que está faltando?: Informação
- O problema teria que resolver para você?: Por favor, quanto tempo os cookies do meu link de afiliado permanecem no dispositivo do usuário?
- Share your Email or Discord so we can get in touch: marcio.marxx68@gmail.com
- Your Gleev channel ID or Title: Period Songs

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**[Open #191 in Usersnap](https://app.usersnap.com/l/feedback/a8d48591-d09f-42e5-b9dc-6461d61deff0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
