### ISSUE TITLE
[USERSNAP] channel suspened issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6013]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: channel suspened issue
- Expected Result: please approved my channel .please
- Your Channel and Account Details: channel link
j4To6jgKfy8MgiMRDXzc15ggN8AnFBsunhyqjFdQtAF5WyyHf
- Email or Discord handle for feedback: kazim306284@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1280x720
**[Open #740 in Usersnap](https://app.usersnap.com/l/feedback/ed39fae0-2afc-4608-aebd-10249360150f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
