### ISSUE TITLE
[USERSNAP] channel suspened issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6014]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: channel suspened issue
- Expected Result: please recheck my channel
- Your Channel and Account Details: channel link
j4To6jgKfy8MgiMRDXzc15ggN8AnFBsunhyqjFdQtAF5WyyHf
- Email or Discord handle for feedback: kazim306284@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ba291f18-45df-444d-a9b7-cc38f940b8c6-annotated_d7d8e2cf-c2d2-4981-8cec-a3e0207b10d3.png?etag=5cdf6797e94e0fdfcc5f032f1836b44d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ba291f18-45df-444d-a9b7-cc38f940b8c6-annotated_d7d8e2cf-c2d2-4981-8cec-a3e0207b10d3.png?etag=5cdf6797e94e0fdfcc5f032f1836b44d)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1280x720
**Browser size**: 1280x593
**[Open #741 in Usersnap](https://app.usersnap.com/l/feedback/9638c449-dd06-44cf-8eec-cba362976fed?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue.
