### ISSUE TITLE
ChangeNOW intregration QA

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#6017]
### Known issues:

- Missing loading state after "Next" is clicked on the summary step
- Close button and go to the dashboard doesn't close the modal at success (just use `X` in top-right corner for now)
- There is no validation against user joy balance for sell joy scenario

**Comment by kdembler** [comment]
- Too many digits
![CleanShot_2024-03-18_at_18 34 232x](https://github.com/Joystream/atlas/assets/12646744/6a019fcf-e099-42b4-adbc-e2c30d16ed44)

- Estimated arrival seems to always be "N/A"?
