### ISSUE TITLE
[USERSNAP] clico em inscreverse mesmo tendo conta nao fica logado

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6018]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: clico em inscreverse mesmo tendo conta nao fica logado
- Expected Result: não fica logado quando clica inscrevase no google nao aparese as outras coisa studio  se posivel me enfia algum contato com voces 
- Your Channel and Account Details: gmail andersonebertz999@gmail.com
- Email or Discord handle for feedback: andersonebertz999@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b8af2be6-b70c-4bc5-83ee-4b6f99587b78-annotated_d09027b7-6391-4607-a53b-43a1fceea32c.png?etag=a4dab2675c0c9e30e3495c06ecb6de31)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b8af2be6-b70c-4bc5-83ee-4b6f99587b78-annotated_d09027b7-6391-4607-a53b-43a1fceea32c.png?etag=a4dab2675c0c9e30e3495c06ecb6de31)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x953
**[Open #742 in Usersnap](https://app.usersnap.com/l/feedback/20f9981d-6efb-4a3a-af6f-518432981164?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration.Instruct to sign-up and provide the document for creator reference.
