### ISSUE TITLE
[USERSNAP] Please Fix This Bug Please 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6019]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Please Fix This Bug Please 
- Expected Result: When i referral someone showing and error 
&#34;&#34;No channel with this title found &#34;&#34; please fix this bug i reffral 2 account but no reward i get.
Showing this error channel not found when i make account with someone one reffral same error with me then i make my account without reffral please help 
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFAzp1MPKHx88TFNmK8LbN,
Channel name How To
- Email or Discord handle for feedback: worldinfo288@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 424x942
**[Open #743 in Usersnap](https://app.usersnap.com/l/feedback/3c4d1d05-02af-47a3-83e1-801dbd45c1fa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator to share email address and youtube channel along with the screenshot of the error message upon referral. Will re-open the ticket once creator get back via email.
