### ISSUE TITLE
[FEATURE REQUEST] One biggest feature is missing 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6020]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Which feature are you missing?: One biggest feature is missing 
- What problem would that solve for you?: Please Give 1$ on sync video bronze Level.
This feature is missing if you add this feature in gleev then 5k to 10k subscribes channel make good level earning with this. You can also set an up limit so that subscribers below 5000 can&#39;t get one dollar per video۔
Now they have only one reffral option
But Biggest Bug in your reffral link
When someone signup with link gleev showing this error
&#34;&#34;No channel with this title found&#34;&#34; and please fix this bug 😞
- Share your Email or Discord so we can get in touch: worldinfo288@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFAzp1MPKHx88TFNmK8LbN

**Browser**: Chrome 122 (Android 10)
**Screen size**: 424x942
**[Open #192 in Usersnap](https://app.usersnap.com/l/feedback/bd06188b-d35f-4c9d-82c3-df8e2382db8a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Shared the creator request with the team, and will inform the creator that it is in discussion. Referral bug issue addressed on a separate ticket.
