### ISSUE TITLE
[FEATURE REQUEST] Channel suspended

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6021]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: Channel suspended
- What problem would that solve for you?: hello gleev team,
   my youtube channel not linked and got suspended.
But my channel fullfil all the requirements. I upload original videos more than 2 and my subscribers are above 50 and my channel more than 1 month old.
please review my channel and tell me the main reason of suspention so i&#39;ll be carefull in future.
Thanks
- Share your Email or Discord so we can get in touch: letsuncoverrespect202@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBM2kzcrNDk9No94SJ3Wr

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fe420389-5587-4dcf-bf28-7ced703d9d86-annotated_be122463-bee1-44b7-8fea-94db6151e517.png?etag=66237d3fa9cee8f3952c7c30cd0425d1)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/fe420389-5587-4dcf-bf28-7ced703d9d86-annotated_be122463-bee1-44b7-8fea-94db6151e517.png?etag=66237d3fa9cee8f3952c7c30cd0425d1)*

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x641
**[Open #193 in Usersnap](https://app.usersnap.com/l/feedback/f4555dab-6da5-4645-a771-dc58364c604a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
