### ISSUE TITLE
[USERSNAP] forget my ass

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6022]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: forget my ass
- Expected Result: i want to reset my pass
- Your Channel and Account Details: channel name BD street food
email: bdstreetfood674@gmail.com
- Email or Discord handle for feedback: bdstreetfood674@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**[Open #744 in Usersnap](https://app.usersnap.com/l/feedback/23d8aa76-7981-4c34-a162-77282a478237?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
