### ISSUE TITLE
[FEATURE REQUEST] Pement 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6024]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: Pement 
- What problem would that solve for you?: 19/3/24
Next pement not paid, what reason? Sir 
- Share your Email or Discord so we can get in touch: alltips276@gmail.com
- Your Gleev channel ID or Title: j4Sb4xRD4W1zh1wfUau6Trsp5J1uwPGz5Q1HHoqT41pEdKwKE

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x780
**[Open #194 in Usersnap](https://app.usersnap.com/l/feedback/638d102b-79bf-48b3-82e3-8769a3c32e05?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards were settled 03/19/24 and sent the instruction to check the payment.
