### ISSUE TITLE
[FEATURE REQUEST] PARECE QUE YA ME SUSCRIBI A ESTA PLATAFORMA

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6026]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- ¿Qué característica te estás perdiendo?: PARECE QUE YA ME SUSCRIBI A ESTA PLATAFORMA
- ¿Qué problema resolvería eso para ti?: SI NO ENTENDI ALG EXPLIQUENMELO LUEGO
- Share your Email or Discord so we can get in touch: fmarmonia102.1@gmail.com
- Your Gleev channel ID or Title: ArnolVideos

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #195 in Usersnap](https://app.usersnap.com/l/feedback/a40edf03-6dea-4e31-bd2b-06c6284bc546?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
