### ISSUE TITLE
[FEATURE REQUEST] I Don't know

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6027]
**Taken at**: https://gleev.xyz/studio/uploads
**Fields**:
- Which feature are you missing?: I Don&#39;t know
- What problem would that solve for you?: Can&#39;t Uplode
- Share your Email or Discord so we can get in touch: mdamirahosann@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x720
**[Open #196 in Usersnap](https://app.usersnap.com/l/feedback/1b364777-1940-4236-89bb-a547fb4a1c33?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and ask for the error message along with the screenshot for reference. Closed ticket for now. Will re-open ticket once creator reach us back.
