### ISSUE TITLE
[FEATURE REQUEST] Hasan

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6028]
**Taken at**: https://gleev.xyz/ypp?referrerId=31767
**Fields**:
- Which feature are you missing?: Hasan
- What problem would that solve for you?: Raj
- Share your Email or Discord so we can get in touch: hasanindo295@gmail.com

**Browser**: Chrome 122 (Android 11)
**Screen size**: 360x820
**[Open #197 in Usersnap](https://app.usersnap.com/l/feedback/65a0763d-7b1c-4580-a749-261093de6d23?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Ticket closed as issue was not specified. Still email the creator to ask what issue/problem they experience.
