### ISSUE TITLE
New Cookie banner for Atlas

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6030]
# Background

https://github.com/Joystream/atlas/issues/6023#issuecomment-2009205593

# Proposal

Make it way way less invasive, drop text to absolute minimum, just the accept all decline all buttons are needed, but check regulatory requirements for this choice. Its particularly important that this is not invasive on mobile, where screen real estate is tiny.

**Comment by dmtrjsg** [comment]
Let's consider adding this to the scope:
- https://github.com/Joystream/atlas/issues/4098
