### ISSUE TITLE
[USERSNAP] ERROR WITHDRAWAL, I made a withdraw on March 19th and a popout with "error" appeared after a few seconds but the web says that it was succesfully withdrawed. It didnt came through and I dont know how to solve it

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6032]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: ERROR WITHDRAWAL, I made a withdraw on March 19th and a popout with &#34;error&#34; appeared after a few seconds but the web says that it was succesfully withdrawed. It didnt came through and I dont know how to solve it
- Expected Result: I expect that the withdraw come through
- Your Channel and Account Details: Virgo Resumenes, Silver Membership
tweety.agustin@hotmail.com
- Email or Discord handle for feedback: tweety.agustin@hotmail.com

**Browser**: Firefox 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #746 in Usersnap](https://app.usersnap.com/l/feedback/d9068d5b-c6ca-4388-ab86-07ccee31e7f7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
