### ISSUE TITLE
[USERSNAP] sicronização

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6033]
**Taken at**: https://gleev.xyz/channel/59053?tab=Videos
**Fields**:
- Houston, we have a problem.: sicronização
- Expected Result: meu youtube não foi sicronizado
- Your Channel and Account Details: josevestina@gmail.com
- Email or Discord handle for feedback: josevestina@gmail.com

**Browser**: Edge (Chromium) 122 (Windows 10)
**Screen size**: 1920x1080
**[Open #747 in Usersnap](https://app.usersnap.com/l/feedback/41e3a312-5325-4d8c-945c-96b5d8dd6317?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator the reason why videos are not sync is channel suspended.
