### ISSUE TITLE
[USERSNAP] Please Fix This Bug Please 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6034]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Please Fix This Bug Please 
- Expected Result: I refer 3 people but i not get 3$ amount
2 days ago please
Please help thanks you
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFAzp1MPKHx88TFNmK8LbN
- Email or Discord handle for feedback: worldinfo288@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 424x942
**[Open #748 in Usersnap](https://app.usersnap.com/l/feedback/c63ef878-879e-4d12-a541-35916eede303?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Email address provided not found. Request for channel info (Ticket pending)

**Comment by rchrdcstro** [comment]
Action Item: In contact with the content creator, and share his referral dashboard. His referrals made it in the platform 03/19. Inform that payout will happen next Tuesday 03/26.
