### ISSUE TITLE
[USERSNAP] La semilla billetera se me olvidó 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6035]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: La semilla billetera se me olvidó 
- Expected Result: No entendí claramente 
- Your Channel and Account Details: abiertopodcast4@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 393x851
**[Open #749 in Usersnap](https://app.usersnap.com/l/feedback/b22d2c9f-683d-4758-b7d8-30fe8b47d99a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference.
