### ISSUE TITLE
[USERSNAP] i upload my own content but shows copyright breach on my ypp status

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6036]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: i upload my own content but shows copyright breach on my ypp status
- Expected Result: i have proof for my own content videos raw footages 
- Your Channel and Account Details:  https://www.youtube.com/@joja_pp
- Email or Discord handle for feedback: janarthanagaja@gmail.com // joja_pp

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f4bce41c-b2ad-452e-8cb4-bf37c0fd3cbc-annotated_2443d0d2-c912-4a5b-b364-23efe8a232d9.png?etag=e1d2ead2bebe471b3db97d1602ff1a27)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/f4bce41c-b2ad-452e-8cb4-bf37c0fd3cbc-annotated_2443d0d2-c912-4a5b-b364-23efe8a232d9.png?etag=e1d2ead2bebe471b3db97d1602ff1a27)*

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x953
**[Open #750 in Usersnap](https://app.usersnap.com/l/feedback/b1312dcf-2d7d-4ecc-a0b3-57189e5398eb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Already in communication in discord and support is already being provided.
