### ISSUE TITLE
[FEATURE REQUEST] Reffer Bonus Not Add

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6037]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: Reffer Bonus Not Add
- What problem would that solve for you?: hello,
    i received the reffer bonus 1$, it shows in reffer section, but from a lot of time it doesn&#39;t add in my wallet, please solve my problem ASAP.
Thanks,
- Share your Email or Discord so we can get in touch: kong125521@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFBnPwtv9cpH3YHQ67wN7e

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1366x768
**[Open #198 in Usersnap](https://app.usersnap.com/l/feedback/f767a593-7756-4049-9a3d-7e68ce1ca72e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator referral is suspended and with that no referral rewards will be issued.
