### ISSUE TITLE
[USERSNAP] Please check Channel again 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6039]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Please check Channel again 
- Expected Result: Not good 
- Your Channel and Account Details: socialnext1755@gmail.com
- Email or Discord handle for feedback: socialnext1755@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x820
**[Open #751 in Usersnap](https://app.usersnap.com/l/feedback/df981571-3b7b-4c4f-a8a9-edc883b4b000?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
