### ISSUE TITLE
[FEATURE REQUEST] Начисления  Video synchronization charges

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6042]
**Taken at**: https://gleev.xyz/channel/25731
**Fields**:
- Какой функциональности вам не хватает?: Начисления  Video synchronization charges
- Какую проблему мы можем решить для вас?: 
no accruals from September 2023
- Share your Email or Discord so we can get in touch: poelenvik5555@gmail.com
- Your Gleev channel ID or Title: https://gleev.xyz/channel/25731?tab=Videos

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1280x1024
**[Open #199 in Usersnap](https://app.usersnap.com/l/feedback/aaae0ea2-cd0f-4c32-8ae8-5b3781737602?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I checked the creator tier and it is under bronze tier. Inform the creator that sync rewards is only available silver tier and above.
