### ISSUE TITLE
[USERSNAP] полное фуфло,хотя вы хрен поймете,гандоны

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6044]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: полное фуфло,хотя вы хрен поймете,гандоны
- Expected Result: херня
- Your Channel and Account Details: херня

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1536x864
**[Open #753 in Usersnap](https://app.usersnap.com/l/feedback/77eaad49-1e82-4757-b1f9-acae48912d3e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed ticket as it contains profanity. Issue is not provided.
