### ISSUE TITLE
[USERSNAP] can't login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6045]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: can&#39;t login
- Expected Result: cant login, I have created with email kamal@ajku.edu.pk,  when i try to login it says email doesn&#39;t exists, i reset the password, but still not working
- Your Channel and Account Details: N/A
- Email or Discord handle for feedback: kamal@ajku.edu.pk

**Browser**: Firefox 124 (Windows 10)
**Screen size**: 1536x864
**[Open #754 in Usersnap](https://app.usersnap.com/l/feedback/6aad1198-a5fb-414f-b107-cba6a4da7907?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
