### ISSUE TITLE
[USERSNAP] My channel page shown $2.08 but payment page have not any balance .

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6047]
**Taken at**: https://gleev.xyz/member/billahpress6101?tab=NFTs
**Fields**:
- Houston, we have a problem.: My channel page shown $2.08 but payment page have not any balance .
- Expected Result: My channel page shown $2.08 but payment page have not any balance . . Please solve this issue asap. 
- Your Channel and Account Details: account id : j4SKZmWSk2UP8rKTEErpZZvR3789qZWyF3bLRHefuZP1sZo1Z      gmail: bdjobs264@gmail.com   channel name : billahpress6101
- Email or Discord handle for feedback: bdjobs264@gmail.com

**Browser**: Chrome 122 (Windows 10)
**Screen size**: 1368x768
**[Open #755 in Usersnap](https://app.usersnap.com/l/feedback/9dc24385-34c2-4837-a67f-347aa3ce15ef?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
