### ISSUE TITLE
[FEATURE REQUEST] No la puedo usar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6048]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- ¿Qué característica te estás perdiendo?: No la puedo usar
- ¿Qué problema resolvería eso para ti?: No entiendo nada
- Share your Email or Discord so we can get in touch: Tengo solo 10 años
- Your Gleev channel ID or Title: Hd Slenderman 

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x760
**[Open #200 in Usersnap](https://app.usersnap.com/l/feedback/d9f27b53-f7be-45e1-9fe2-af4b4fa9aba3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
No contact email to get back to the creator. Closed the ticket.
