### ISSUE TITLE
[USERSNAP] Why copyright 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6049]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Why copyright 
- Expected Result: Not good 
- Your Channel and Account Details: Kamran Tariq 
- Email or Discord handle for feedback: kamrantariq17555@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x820
**[Open #756 in Usersnap](https://app.usersnap.com/l/feedback/5e9242b9-bc9f-4175-813f-a43735575c5b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
