### ISSUE TITLE
[USERSNAP] I don't see my category in these channel 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6050]
**Taken at**: https://gleev.xyz/studio/channel?tab=Notifications
**Fields**:
- Houston, we have a problem.: I don&#39;t see my category in these channel 
- Expected Result: Reply me 
- Your Channel and Account Details: vuningomanaurice@gmail.com
Vuna117
- Email or Discord handle for feedback: vuningomanaurice@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 463x1002
**[Open #757 in Usersnap](https://app.usersnap.com/l/feedback/f9fbd730-2d4a-4a74-bd4b-c626ff6ee237?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator to clarify their concern.
