### ISSUE TITLE
[USERSNAP] Channel rejected 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6051]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Channel rejected 
- Expected Result: Accept my channel the videos I used are common creative I have permission to reuse
- Your Channel and Account Details: crypto.money.ways@gmail.com
- Email or Discord handle for feedback: terwasesamson123@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 424x753
**[Open #758 in Usersnap](https://app.usersnap.com/l/feedback/9a85de25-4299-410c-81dd-080226835eeb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
