### ISSUE TITLE
[USERSNAP] I want to withdraw

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6052]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I want to withdraw
- Expected Result: qebetb
- Your Channel and Account Details: btwebtvw4bwb
- Email or Discord handle for feedback: no

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #759 in Usersnap](https://app.usersnap.com/l/feedback/321d1cc3-aaa9-422c-aa9e-c2358fabc8c8?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reviewed, and no email or Discord handle was provided for feedback.
