### ISSUE TITLE
[USERSNAP] Login ERROR

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6054]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Login ERROR
- Expected Result: For some reason the page doesnt let me login with my account
- Your Channel and Account Details: Juanrodgames0407@gmail.com
JuanRodGames

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #761 in Usersnap](https://app.usersnap.com/l/feedback/a01cea57-b383-4091-900f-b46dc247226e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
