### ISSUE TITLE
[USERSNAP] If I get  thousand views on gleev platform not on YouTube so you can pay 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6055]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: If I get  thousand views on gleev platform not on YouTube so you can pay 
- Expected Result: Good 
- Your Channel and Account Details: mybusiness7214@gmail.com
- Email or Discord handle for feedback: mybusiness7214@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x820
**[Open #762 in Usersnap](https://app.usersnap.com/l/feedback/57cbdbe3-503b-4773-a4a5-63b229815669?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration for issue checking purposes.
