### ISSUE TITLE
[USERSNAP] Suspended issue.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6056]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Suspended issue.
- Expected Result: Fix my account.
- Your Channel and Account Details: Whitehat ID
- Email or Discord handle for feedback: honestyan0708@gmail.com

**Browser**: Chrome 123 (macOS Catalina)
**Screen size**: 1920x1080
**[Open #763 in Usersnap](https://app.usersnap.com/l/feedback/04d67d9d-cd69-40fc-ad93-975bb0618444?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
