### ISSUE TITLE
[FEATURE REQUEST] طلب مهم

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6057]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: طلب مهم
- What problem would that solve for you?: ارجوا الافاده كيفيت السحب الي محفظتي الخاصه لبلدي
- Share your Email or Discord so we can get in touch: y5766775@gmail.com
- Your Gleev channel ID or Title: @Ro763

**Browser**: Chrome 122 (Android 10)
**Screen size**: 393x873
**[Open #201 in Usersnap](https://app.usersnap.com/l/feedback/73a377ce-8f05-4ee7-abb3-0bbe19d795a7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
