### ISSUE TITLE
[USERSNAP] Gleev pay if we reach thousands of views on gleev platform not on YouTube important question ❓

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6058]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Gleev pay if we reach thousands of views on gleev platform not on YouTube important question ❓
- Expected Result: Good 
- Your Channel and Account Details: kamrantariq17555@gmail.com
- Email or Discord handle for feedback: kamrantariq17555@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x820
**[Open #764 in Usersnap](https://app.usersnap.com/l/feedback/ef146db5-33f8-426a-8791-0e7b2ebcf6bc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment/rewards of our program is (sign-up rewards, videos sync (silver and above tier) and referral.
