### ISSUE TITLE
[USERSNAP] Bouns Reward not added 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6059]
**Taken at**: https://gleev.xyz/channel/59437?tab=Information
**Fields**:
- Houston, we have a problem.: Bouns Reward not added 
- Expected Result: Bouns Reward not added 
into my account after the given date. now it&#39;s showing me the new date even old date passed but Reward not added in my account. can you please tell me what is the problem?
- Your Channel and Account Details: infoworld1432
- Email or Discord handle for feedback: anasramzanaltaf786@gmail.com

**Browser**: Chrome 115 (Android 11)
**Screen size**: 412x915
**[Open #765 in Usersnap](https://app.usersnap.com/l/feedback/06170285-8b94-4952-ad0e-1a13d3f5c72e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their sign-up rewards. The rewards were settled 03/19/24 and sent the instruction to check the payment.
