### ISSUE TITLE
[USERSNAP] I am creat 3 video and uplod a week but reward not receive 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6060]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Houston, we have a problem.: I am creat 3 video and uplod a week but reward not receive 
- Expected Result: Reward not receive
- Your Channel and Account Details: Mahakal gaming
- Email or Discord handle for feedback: sujalpatidar435@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x825
**[Open #766 in Usersnap](https://app.usersnap.com/l/feedback/a898deb4-5d06-4330-8197-4fdb68533698?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I checked the channel and the channel is bronze. Informed the creator that videos sync rewards is available only from silver and above tier. Encourage the creator to utilize referral.
