### ISSUE TITLE
[FEATURE REQUEST] Dear sir please solve my problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6061]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: Dear sir please solve my problem 
- What problem would that solve for you?: Sir my singup bonus not received please send my reward 
- Share your Email or Discord so we can get in touch: nawaz.1228@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFAXF8cqzaE6fPeTWW96Vv

**Browser**: Chrome 120 (Android 10)
**Screen size**: 393x873
**[Open #202 in Usersnap](https://app.usersnap.com/l/feedback/b4655ee9-eedc-48e5-991a-f040559ee98a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
