### ISSUE TITLE
[USERSNAP] Payment not received 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6062]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Payment not received 
- Expected Result: I Referral 2 Channels And Gleev Confirmed My 2 Dollers But I didn&#39;t Got The Payment On Due Date
- Your Channel and Account Details: A.i Nerd Nomi
- Email or Discord handle for feedback: nomitrap060@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x800
**[Open #767 in Usersnap](https://app.usersnap.com/l/feedback/d16ea45c-4442-4da4-ac9e-50c5ff992fec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Request the creator to provide screenshots of their referral dashboard and the associated YouTube channels for verification.
