### ISSUE TITLE
[FEATURE REQUEST] suspend issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6063]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Which feature are you missing?: suspend issue
- What problem would that solve for you?: dear gleev team, i cannot upload any copyright content . please check again ... i always upload my own content
- Share your Email or Discord so we can get in touch: abloon727@gmail.com
- Your Gleev channel ID or Title: https://www.youtube.com/channel/UCJ6qX6S0VgwcKPClwAQuYCA

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1366x768
**[Open #203 in Usersnap](https://app.usersnap.com/l/feedback/fbb161fe-8e7f-48a6-aa39-86b804242185?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
