### ISSUE TITLE
[USERSNAP] Bouns Reward not added into my account after the given date. now it's showing me the new date even old date passed but Reward not added in my account. can you please tell me what is the problem?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6064]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: Bouns Reward not added into my account after the given date. now it&#39;s showing me the new date even old date passed but Reward not added in my account. can you please tell me what is the problem?
- Expected Result: Please add my bouns 
- Your Channel and Account Details: Browserstack3@mail.com
- Email or Discord handle for feedback: Browserstack3@mail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 412x915
**[Open #768 in Usersnap](https://app.usersnap.com/l/feedback/99b703fa-4667-4afa-9fe8-c4f69bd16736?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
**Action Item:** Informed the creator that this week payout (March 26, 2024) will be slightly delayed. Assured creator that payout will be settled as soon as possible.
