### ISSUE TITLE
[FEATURE REQUEST] Payments problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6065]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: Payments problem
- What problem would that solve for you?: Payments problem
- Share your Email or Discord so we can get in touch: mfnazmulhoda24@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFAbHS47FQqNgjijQ6Vgf1

**Browser**: Chrome 122 (Android 10)
**Screen size**: 501x1002
**[Open #204 in Usersnap](https://app.usersnap.com/l/feedback/abade760-ad55-4e13-a7fa-3181a129b19a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Checked, and the channel was not found for checking purposes. I reached out to the creator to provide channel details.
