### ISSUE TITLE
[FEATURE REQUEST] Payments problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6066]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: Payments problem
- What problem would that solve for you?: Sir my singup bonus not received please send my reward
- Share your Email or Discord so we can get in touch: mfnazmulhoda24@gmail.com
- Your Gleev channel ID or Title: j4To6jgKfy8MgiMRDXzc15ggN8AnFAbHS47FQqNgjijQ6Vgf1

**Browser**: Chrome 122 (Android 10)
**Screen size**: 501x1002
**[Open #205 in Usersnap](https://app.usersnap.com/l/feedback/0fa691dd-9ebe-4e2f-828c-b12c05fd18cb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
