### ISSUE TITLE
[USERSNAP] Payment Not recived

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6067]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Payment Not recived
- Expected Result: I Was Spouse To Get My Signup 2$ On 26 Of March But I Didnt Recived Anything I Dont Understand Whats The Problem My Channel Has Been Verified So Why I Didnt Recive My Bonus
- Your Channel and Account Details: sasukenj786@gmail.com
- Email or Discord handle for feedback: sasukenj786@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #769 in Usersnap](https://app.usersnap.com/l/feedback/3c3175df-a3cc-4e6d-bf3d-04854faafbbb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that this week payout (March 26, 2024) will be slightly delayed. Assured creator that payout will be settled as soon as possible.
