### ISSUE TITLE
[FEATURE REQUEST] My payment not receive 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6069]
**Taken at**: https://board.usersnap.com/tZNWrBYXJAAHUiTo#/
**Fields**:
- Which feature are you missing?: My payment not receive 
- What problem would that solve for you?: My payment not receive 
- Share your Email or Discord so we can get in touch: alaminhossainmd934@gmail.com
- Your Gleev channel ID or Title: Md.Alamin Hossain 

**Browser**: Chrome 122 (Android 10)
**Screen size**: 400x889
**[Open #207 in Usersnap](https://app.usersnap.com/l/feedback/238d6783-4027-410c-9129-03c3d7c49304?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Checked the channel and it was suspended. Reached out to the creator if what kind of rewards he is looking for.
