### ISSUE TITLE
[USERSNAP] I can't link my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6071]
**Taken at**: https://gleev.xyz/search?query=gleev+error
**Fields**:
- Houston, we have a problem.: I can&#39;t link my account
- Expected Result: I hoped that if there was an error or lost email, I could recover it by sending a code to the email as verification.
- Your Channel and Account Details: I cannot link my YouTube account, I had previously registered the account email but I cannot access it to delete it because it does not have the phrase, when I try to link the YouTube account I get that the account is already registered, please help me
- Email or Discord handle for feedback: araneamike4608@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1366x768
**[Open #770 in Usersnap](https://app.usersnap.com/l/feedback/e30c4e7c-f16b-4f46-b3bb-d29326597371?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration.Instruct to sign-up and provide the document for creator reference.
