### ISSUE TITLE
[USERSNAP] Payment not add in account 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6075]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Payment not add in account 
- Expected Result: Please help me i reffer 3 approve channel but i not get Reward on 26 march please help me 
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFAzp1MPKHx88TFNmK8LbN
- Email or Discord handle for feedback: worldinfo288@gmail.com

**Browser**: Chrome 122 (Linux)
**Screen size**: 424x942
**[Open #771 in Usersnap](https://app.usersnap.com/l/feedback/9dc016d8-b0ac-4eae-bf13-3a1c428906b9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that this week payout (March 26, 2024) will be slightly delayed. Assured creator that payout will be settled as soon as possible.
