### ISSUE TITLE
[FEATURE REQUEST] Bappy 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6076]
**Taken at**: https://gleev.xyz/ypp?referrerId=58463
**Fields**:
- Which feature are you missing?: Bappy 
- What problem would that solve for you?: Dakota 
- Share your Email or Discord so we can get in touch: bappyvai787@gmail.com

**Browser**: Opera 79 (Android 13)
**Screen size**: 424x949
**[Open #208 in Usersnap](https://app.usersnap.com/l/feedback/5648f818-817f-4c15-b097-4eb2802d0965?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
