### ISSUE TITLE
[USERSNAP] YPP Status Problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6077]
**Taken at**: https://gleev.xyz/member/settings?tab=Public+profile
**Fields**:
- Houston, we have a problem.: YPP Status Problem
- Expected Result: I have working regular on my channel but i stuck in broze status and i am real content creator working on youtube so please again recongnize my YPP status
- Your Channel and Account Details: mangarix, salmanshaikh002k@gmail.com

**Browser**: Chrome 121 (Android 10)
**Screen size**: 360x720
**[Open #772 in Usersnap](https://app.usersnap.com/l/feedback/38153f20-7208-45b0-8514-9bd1b3d463d9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Email address not found in our records, reach out to the creator and ask for more further information for checking purposes.
