### ISSUE TITLE
[USERSNAP] why my YPP show suspened

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6078]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: why my YPP show suspened
- Expected Result: i already remove the copy right video
- Your Channel and Account Details: https://www.youtube.com/channel/UC6OkDryxjfKpHAxmkaw3HZg
- Email or Discord handle for feedback: please remove my suspended ypp 

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1539x707
**[Open #773 in Usersnap](https://app.usersnap.com/l/feedback/abda55db-bb8f-4435-a866-dde82b028316?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Closed ticket - No contact provided to get back with the creator
