### ISSUE TITLE
[USERSNAP] Why bronze only

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6079]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Why bronze only
- Expected Result: i deserve more check again
- Your Channel and Account Details: queenvideozone@gmail.com
my yt: https://www.youtube.com/channel/UCmg24XsCOtRj6TJf9bZ0rKw
- Email or Discord handle for feedback: queenvideozone@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #774 in Usersnap](https://app.usersnap.com/l/feedback/26966f6b-eb7b-4857-b2aa-290e87bef2be?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notify the creator that the team has conducted a comprehensive reevaluation and channel is really a bronze.
