### ISSUE TITLE
[USERSNAP] Give me gold level

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6080]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Give me gold level
- Expected Result: no results
- Your Channel and Account Details: rotigembul@gmail.com
- Email or Discord handle for feedback: rotigembul@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #775 in Usersnap](https://app.usersnap.com/l/feedback/4d02808c-bbd9-4532-8ffa-86f33263f597?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: The channel was recently evaluated and it is bronze.
