### ISSUE TITLE
[USERSNAP] Everyone has been paid already but I received nothing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6081]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Everyone has been paid already but I received nothing
- Expected Result: no payment received
- Your Channel and Account Details: Account Gleev romanekras321@gmail.com
Channel http://www.youtube.com/channel/UCJyemTvNj_W45pE-emye6lw
- Email or Discord handle for feedback: romanekras321@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #776 in Usersnap](https://app.usersnap.com/l/feedback/6d025e69-1796-4ab9-b0b3-ce2d792eda4e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I checked the channel and sync rewards was not distributed. Follow-up with zeeshan.
