### ISSUE TITLE
[USERSNAP] sign up bonus not received 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6082]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: sign up bonus not received 
- Expected Result: sign up bonus not received 
- Your Channel and Account Details: sign up bonus not received 

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1440x900
**[Open #777 in Usersnap](https://app.usersnap.com/l/feedback/10745f0e-979b-4987-98cb-cb564e0512c9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Closed ticket. No email provided to get back to the creator.
