### ISSUE TITLE
[USERSNAP] didn't get payment of last week

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6083]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: didn&#39;t get payment of last week
- Expected Result: get payment correctly
- Your Channel and Account Details: channel name : PRO POTTAN, Its a Gaming Channel
- Email or Discord handle for feedback: propottanabhishek@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #778 in Usersnap](https://app.usersnap.com/l/feedback/6e8fa13a-e4ec-4331-af50-5c0728a7076d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that this week payment was delayed. Rest assured that creator payment will be credited next week.
