### ISSUE TITLE
[USERSNAP] No payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6084]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: No payment
- Expected Result: I&#39;m still waiting for the payment on 03/26 my Youtube channel is www.youtube.com/@somibeercast and my e-mail is armandorosal@gmail.com
- Your Channel and Account Details: armandorosal@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #779 in Usersnap](https://app.usersnap.com/l/feedback/93bd689e-5848-49ce-92f8-2c5c210afb3d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I checked the channel and he is eligible of sync video rewards, assured creator that it will be credited next payout.
