### ISSUE TITLE
[USERSNAP] ot received weekly payment yet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6085]
**Taken at**: https://gleev.xyz/channel/49824?tab=Videos
**Fields**:
- Houston, we have a problem.: ot received weekly payment yet
- Expected Result: I’m also not received weekly payment yet
- Your Channel and Account Details: https://gleev.xyz/video/1268783
- Email or Discord handle for feedback: https://gleev.xyz/video/1268783

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #780 in Usersnap](https://app.usersnap.com/l/feedback/85ee1d61-1805-481d-85c8-d195ea184e56?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: I checked the channel and it is under gold tier. Let know the creator that payment will be distributed next week.
