### ISSUE TITLE
Branded snippet

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6088]
## Context

We want to try and entice creators to post their videos to Gleev first (before YT) and reward them for original content. There is a hypothesis that a subset will be interested in Joystream branding (pre-roll snippet before their videos. 

## Scope
- [ ] Design branded video snippets for 
- pre-roll - we can start with something simple to the same effect as in [this video>](https://gleev.xyz/video/1103611). "Gleev logo and sound. Gleev logo can have a small text Powered by Joystream." With sound 🔉 
- post-roll - tiktok style. The text has to be "Watch more on Gleev.xyz. Powered by Joystream"
- mid-roll  overlay - subtle overlay with Gleev branding. "Watch more on Gleev.xyz. Powered by Joystream"

We need some sound to be applied as part of branding.

**Comment by KubaMikolajczyk** [comment]
Hey @dmtrjsg I finished designing the prerolls, midroll and postrolls - which are now ready to review ✅ I prepared a video overview where we can watch all of them together but I also encourage you to preview the files yourself by downloading them from the github/atlas-resources and playing them by yourself 👌 Let me know what do you think 🙇

🎥 Branded Snippets Design: Exploring Pre-Rolls, Mid-Rolls, and Post-Rolls (5:49min): https://www.loom.com/share/178b00a9659048fbbf2018cb2b74c4bb?sid=f5dd2c93-e3b5-4497-bb4b-19294110bfec

📁 Video files on github joystream/atlas-resources: https://github.com/Joystream/atlas-resources/tree/main/Gleev%20Branded%20Snippet

**Comment by dmtrjsg** [comment]
@KubaMikolajczyk excellent work there ⭐, I mean really impressive  🙌 

Pre-roll: first one with lower sound is perfect imo
Mid-roll: I'd probaby want to see it sliding from the bottom in the center and sliding back down. Cornered position in my impression does not capture the attention enough. I would also suggest to keep it for a little longer like slide out - wait for 2 seconds- slide back in. 
Post-roll: the first one without the music worked best with me, and making a lamp click is a brilliant idea 💡 !!

**Comment by KubaMikolajczyk** [comment]
Hey @dmtrjsg 🖐️ I lowered the sound on pre-roll and made changes to mid-roll + prepared the final video assets in both landscape (16:9) and vertical (9:16) aspect ratios. It's ready to be reviewed and if everything is fine - ready to be used ✅ 

🎥 Final branded snippets walkthrough: https://www.loom.com/share/3d0a5e053ce645a9ae7dfe749ff012aa?sid=24c95402-ada0-4377-a21a-1d82b9d00d44

📁 Final video files on github joystream/atlas-resources: https://github.com/Joystream/atlas-resources/tree/main/Gleev%20Branded%20Snippet
