### ISSUE TITLE
Design: Updates for YPP Dash

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6092]
## Context
- https://github.com/Joystream/atlas/issues/6038

# Scope
1. Rename YPP side panel to "Earn". 
2. Change icon to "$"
3. Change H1 from YouTube Partner Program to `Creator Rewards`
4. Add more tasks

**Youtubers** 
- Connect Channel
- Sync New Videos
- Refer YT creator

**Original Creators** 
⚠️ Offer is valid for Silver+ tiers
- Gleev Original Content
Small text: Earn more by publishing content to Gleev at least 24 hours ahead of Youtube. Add hashtag # JoystreamOriginal and # watchOnGleev  and links to #video[id] #channel[id] pointing to Gleev to get counted.
Reward: `x2 per video`
CTA: Sign up > links to Typeform (url to be provided)

- Gleev Branding
Small text: Add Joystream branding to your video and multiply your rewards for original uploads to Gleev.
Reward: `x2 per original video`
CTA: Sign up > links to Typeform (url to be provided)

__
**Community builders**

- Discord Community
Small text: Connect with other creators on Discord and participate in building the platform with us. Each week 5 new active participants selected by community are rewarded with 20 USD. 
Reward: 20 USD
CTA: Join Discord  (links to https://discord.gg/jEzC5bjD)

- Post on X
Tweet the sample and follow [Joystream DAO](link to twitter) on X.
Each week 5 new random channels get paid and featured in our New Joiners post. 
Reward: 20 USD
CTA: Post on X (redirect to X and have a pre-generated post  has already link to channel ID and utm params, example url = `https://gleev.xyz/channel/29895&utm_source=x&utm_campaign=channel_id&utm_).  

- Roundtable events
Small text: Participate in Creator Roundtable events on Discord and win cash and other prizes. 3 best questions receive a prize.
Reward: 25 USD 
CTA: Learn more (links to Discord channel with new roundtable vents announced)

**Social Promoters**
⚠️ Offer is valid for Silver+ tiers
- Share NFT
Small text: Drop your shared NFT link to our discord NFT shares channel and get voted by other for the weekly prize by our community. 
Reward: Up to 100 USD
CTA: Share NFT (links to NFTs tab on channel)

- Share Token 
Small text: Drop your shared token link to our discord Token shares channel and get voted for the weekly prize by our community. 
Reward: Up to 100 USD
CTA: Share token ((links to CRTs tab on channel)

- Ambassador Program
Small text: Become Joystream ambassador and work with our marketing and product team on growing the platform.
Reward: Up to 1k USD pm
CTA: Apply > (blogpost)

### Out of scope ⛔ 
cc @msmadeline 

- Link to Gleev channel 
⚠️ Offer is valid for Silver+ tiers
Add a link to video description on YT pointing back to your Gleev channel and add # `watchOnGleev` hashtag to increase your sync rewards per video. 
Reward: +10%
CTA: Generate link
When clicked, copies their channel id URL with UTM links to clipboard
example: `https://gleev.xyz/channel/1219927?utm_source=yt&utm_campaign=yppbacklink`

**Comment by spatsochi** [comment]
I would add yet
Original Creators
⚠️ Offer is valid for Silver+ tiers

Gleev Original Content
 Earn more by publishing  original content WEB3 exclusively  to Gleev ,the video should not be repeated anywhere

**Comment by dmtrjsg** [comment]
@spatsochi we have to rely on existing Payouts Infrastructure that is still based on YT videos published. Over time we will try and build smth that can support Gleev exclusive. Also since YT channels still get most of the viewers attention it is beneficial to "advertise" there and refer the traffic from there to Gleev.

**Comment by msmadeline** [comment]
@dmtrjsg Adding a link to the finalized dashboard 

➡ figma link: https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=6162-87114&mode=design&t=GcdDtMBfveyBoUSr-4

**Comment by msmadeline** [comment]
@dmtrjsg Hey I did the RWD for the dashboard

➡https://www.figma.com/file/oQqFqdAiPu16eeE2aA5AD5/YouTube-Partner-Program?type=design&node-id=6427-84638&mode=design&t=OEW3U0AiHDXekHjd-4
