### ISSUE TITLE
[USERSNAP] simonzralok@gmail.com

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6093]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: simonzralok@gmail.com
- Expected Result: I would like to level up my tier
- Your Channel and Account Details: simonzralok@gmail.com
- Email or Discord handle for feedback: simonzralok@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #781 in Usersnap](https://app.usersnap.com/l/feedback/23114fd4-aa3f-41b4-9fa3-eac254b511a2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator the current status is accurate and recommends to level up contents.
