### ISSUE TITLE
[FEATURE REQUEST] More payments

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6094]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: More payments
- What problem would that solve for you?: you create more to earn from us
- Share your Email or Discord so we can get in touch: invest32@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #209 in Usersnap](https://app.usersnap.com/l/feedback/5d70ce81-8b01-442f-97bc-c5dedd42edd9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator about the platform and educate creator things to take advantage for rewards purposes.
