### ISSUE TITLE
[USERSNAP] No payment again? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6096]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: No payment again? 
- Expected Result: no payment now and last week
- Your Channel and Account Details: jagoran.lal2004@gmail.com
- Email or Discord handle for feedback: jagoran.lal2004@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #782 in Usersnap](https://app.usersnap.com/l/feedback/c8457919-c757-4064-807f-2b1ba566e9d6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed that creator that payment will be made within this week including the last payout. Let know the creator that he will be receiving an email when payment was executed.
