### ISSUE TITLE
[USERSNAP] you SCAM us

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6097]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: you SCAM us
- Expected Result: Please provide clear and definitive information regarding the payment schedule for March 26. When can we expect it to be processed and paid?
- Your Channel and Account Details: no
- Email or Discord handle for feedback: no

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #783 in Usersnap](https://app.usersnap.com/l/feedback/7a92b540-918c-4b07-92b4-05c48d52eacb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this ticket as there is no way to get back to the creator (email or discord handle not provided)
