### ISSUE TITLE
[USERSNAP] WHAT Happen?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6098]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: WHAT Happen?
- Expected Result: I am registered in Gleev since 3 months ago... I know I can receive rewards... what I want to know is what happened with the payment of March 26th and today?
- Your Channel and Account Details: my Youtube channel is www.youtube.com/@somibeercast and my e-mail is armandorosal@gmail.com
- Email or Discord handle for feedback: armandorosal@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #784 in Usersnap](https://app.usersnap.com/l/feedback/9120a24a-94df-4866-b529-dffb5073264d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent an email to the creator about the issue encountered and explained that will be doing one time payment from last pay out and this payout.
