### ISSUE TITLE
[USERSNAP] no payment received

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6099]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: no payment received
- Expected Result: no payment received
- Your Channel and Account Details: romanekras321@gmail.com
- Email or Discord handle for feedback: romanekras321@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #785 in Usersnap](https://app.usersnap.com/l/feedback/47294df0-2c91-4e57-82cf-7f876949b49c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed that creator that payment will be made within this week including the last payout. Let know the creator that he will be receiving an email when payment was executed.
