### ISSUE TITLE
[USERSNAP] I have no youtube channel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6100]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I have no youtube channel
- Expected Result: can i earn you guys if no yotuube?
- Your Channel and Account Details: no channel
- Email or Discord handle for feedback: gerytjfr@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #786 in Usersnap](https://app.usersnap.com/l/feedback/f1c581e9-0bfe-4104-b44f-3a38da1fb1b2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent program details to the inquirer to learn more.
