### ISSUE TITLE
[USERSNAP] Bye

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6101]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Bye
- Expected Result: Want to delete my account
- Your Channel and Account Details: jahidjk471@gmail.com
https://www.youtube.com/channel/UCiTIfQ_UiR-9fzEYZKcVuZQ
- Email or Discord handle for feedback: jahidjk471@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #787 in Usersnap](https://app.usersnap.com/l/feedback/0ce8af1c-2296-46e2-93f2-0e809ea56454?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that we don't offer for deletion but they can opt-out. Sent the steps through dm.
