### ISSUE TITLE
[USERSNAP] ¿Dónde está mi pago?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6102]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: ¿Dónde está mi pago?
- Expected Result: Ya no creo en ustedes, no hubo pago nuevamente la semana pasada y esta semana son increíbles.
- Your Channel and Account Details: my youtube https://www.youtube.com/channel/UC1w6D2LeuAP_jOxhwB6epnA
- Email or Discord handle for feedback: fernandopersonal147@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #788 in Usersnap](https://app.usersnap.com/l/feedback/05c3e757-119e-469d-928f-254329bdb891?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed that creator that payment will be made within this week including the last payout. Let know the creator that he will be receiving an email when payment was executed.
