### ISSUE TITLE
[USERSNAP] Already april 4 today not yet recieve 😅

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6103]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Already april 4 today not yet recieve 😅
- Expected Result: nothing again 
- Your Channel and Account Details: kenshin

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #789 in Usersnap](https://app.usersnap.com/l/feedback/d8a042c9-9450-454b-b974-5d7e766ed33c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed that creator that payment will be made within this week including the last payout. Let know the creator that he will be receiving an email when payment was executed.
