### ISSUE TITLE
[FEATURE REQUEST] i want to apply

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6104]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: i want to apply
- What problem would that solve for you?: hi my name is vega and experienced designer.lets connect
- Share your Email or Discord so we can get in touch: vegatomex@outlook.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #210 in Usersnap](https://app.usersnap.com/l/feedback/e991ca16-5067-4a13-8032-bd1506811800?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Let know the inquiry to join discord and sent the link for invite to see job/work opportunities.
