### ISSUE TITLE
[USERSNAP] Я в замешательстве, вы нам заплатите или нет?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6107]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Я в замешательстве, вы нам заплатите или нет?
- Expected Result: Я ждал платежа с прошлой недели, вот и все.
- Your Channel and Account Details: HELP
- Email or Discord handle for feedback: vegaflex9@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #790 in Usersnap](https://app.usersnap.com/l/feedback/ec3c4dcc-c0db-484a-8317-44fe22397a82?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment will be processed today or tomorrow.
