### ISSUE TITLE
[USERSNAP] only bronze

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6108]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: only bronze
- Expected Result: how can upgrade bronze to silver 
- Your Channel and Account Details: https://gleev.xyz/channel/57916?tab=Videos
- Email or Discord handle for feedback: technokalingraj@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #791 in Usersnap](https://app.usersnap.com/l/feedback/57f3f23e-66d3-4a8e-9761-5417ec0ce1d4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator to advance to a higher tier, I recommend creating high-quality content and actively engaging with the platform.
