### ISSUE TITLE
[USERSNAP] No rewards

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6109]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: No rewards
- Expected Result: Two weeks without payments channel 
- Your Channel and Account Details: My channel is &#34;huertinga&#34;
- Email or Discord handle for feedback: huertinga

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #792 in Usersnap](https://app.usersnap.com/l/feedback/5eb490d0-0b3e-464c-baae-5db15882f291?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment would be slightly delay and will be processed by today or tomorrow.
