### ISSUE TITLE
[FEATURE REQUEST] Take note of this!

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6110]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: Take note of this!
- What problem would that solve for you?: I suggest that your platform should make a concise payment date for us! Not waiting and waiting for nothing.
- Share your Email or Discord so we can get in touch: web3easy@gmail.com
- Your Gleev channel ID or Title: exhausting

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #211 in Usersnap](https://app.usersnap.com/l/feedback/26551ee9-dea8-4b11-babb-5115d53ae196?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Send an email to the creator informing that we are alrealdy working on payment structure.
