### ISSUE TITLE
[USERSNAP] Payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6111]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Payment
- Expected Result: You Said Payment Will Be Settled Next Week But Even This Week Me And My Partner Channels Didn&#39;t Get Any Payment, We Have A Whole YouTube Community Who always Exploring New Ways To Grow And Make Money Alongside, In That Regard We Tested Your Site Which Had Some Hype But After This Terrible Experience I&#39;d Make Sure To Let everyone Know What Gleev Is Actually 👎 
- Your Channel and Account Details: nomitrap060@gmail.com
- Email or Discord handle for feedback: nomitrap060@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #793 in Usersnap](https://app.usersnap.com/l/feedback/12387101-b673-4313-af48-a77dae433ff6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment from last week and this week will slightly be delayed. Let know the creator that it might be process today or tomorrow.
