### ISSUE TITLE
[USERSNAP] My channels is always suspended

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6112]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: My channels is always suspended
- Expected Result: I have been trying to join in your platform but always suspending my joining.
- Your Channel and Account Details: No channel
- Email or Discord handle for feedback: rotigemre@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #794 in Usersnap](https://app.usersnap.com/l/feedback/18d1af67-1df9-41d1-9397-076e4a9a1425?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
