### ISSUE TITLE
[USERSNAP] no recuerdo mi semilla de billetera  podrian enviarmela a mi coarreo electronico? hay alguna manera

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6113]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: no recuerdo mi semilla de billetera  podrian enviarmela a mi coarreo electronico? hay alguna manera
- Expected Result: no recuerdo mi semilla de billetera 
podrian enviarmela a mi coarreo electronico?
hay alguna manera
- Your Channel and Account Details: no recuerdo mi semilla de billetera 
podrian enviarmela a mi coarreo electronico?
hay alguna manera
- Email or Discord handle for feedback: no recuerdo mi semilla de billetera  podrian enviarmela a mi coarreo electronico? hay alguna manera

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #795 in Usersnap](https://app.usersnap.com/l/feedback/464945c6-86ab-489f-bbcb-b8a72ee865dc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed ticket as no email to get back with the creator.
