### ISSUE TITLE
[USERSNAP] Payment Issue

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6114]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Payment Issue
- Expected Result: Hi, I haven&#39;t been paid the last 2 payments for the YPP. Can someone clarify it is an ongoing issue and we will be paid the missing payments soon?
- Your Channel and Account Details: https://gleev.xyz/channel/45180?tab=Videos
- Email or Discord handle for feedback: cryptoready1@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #796 in Usersnap](https://app.usersnap.com/l/feedback/7524dcb0-b4a0-435d-a965-9d7446f4b16f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Already being assisted in discord platform.
