### ISSUE TITLE
[USERSNAP] where is my total 3$ sir ?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6115]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: where is my total 3$ sir ?
- Expected Result: my 5 invitees and 2$ signup bonus  make me a total of 7$ but I received 4$..whats problem where is my   total 3$ sir ?check my channel properly.. 
- Your Channel and Account Details: channel mail is muhammadrafiullah269@gmail.com 
- Email or Discord handle for feedback: muhammadrafiullah269@gmail.com 

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #797 in Usersnap](https://app.usersnap.com/l/feedback/fa27bd15-9797-40ac-91f3-d4f172d578ab?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that remaining payments will be credited soon.
