### ISSUE TITLE
[USERSNAP] error al proceder a retirar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6116]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: error al proceder a retirar
- Expected Result: hice un retiro y me dio error y me fue descontado mas no pagado
- Your Channel and Account Details: mi canal es kreutercash
- Email or Discord handle for feedback: kreutertovar696@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1971x975
**[Open #798 in Usersnap](https://app.usersnap.com/l/feedback/6324b57d-c7f4-449b-9c2e-17e1c0c6303b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
