### ISSUE TITLE
[USERSNAP] one reward only?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6117]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: one reward only?
- Expected Result: i want to know..can i get payment for weekly video sycn
- Your Channel and Account Details: Crypto Asia
- Email or Discord handle for feedback: oran.lal2004@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #799 in Usersnap](https://app.usersnap.com/l/feedback/e7c54b81-c17d-49ad-b873-91ba82239b09?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator about the information about the ypp program.
