### ISSUE TITLE
[USERSNAP] payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6119]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: payment
- Expected Result: Hello I have an issue with payment withdraw, My payment not received in my account. this is block id 6 930 041 block
- Your Channel and Account Details: Shivam vlogs
- Email or Discord handle for feedback: pippopnick@gmail.com

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x800
**[Open #800 in Usersnap](https://app.usersnap.com/l/feedback/26607594-d327-4c19-840a-2f9b6e24f544?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
