### ISSUE TITLE
[USERSNAP] I can't connect the channel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6120]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Houston, we have a problem.: I can&#39;t connect the channel
- Expected Result: When registering I got an error and after that I can’t log in and can’t do a new registration
- Your Channel and Account Details: https://www.youtube.com/channel/UCVdVYbLQFKbNzQQqt4CF62w
alexmirr046@gmail.com
- Email or Discord handle for feedback: alexmirr046@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #801 in Usersnap](https://app.usersnap.com/l/feedback/92886236-ddbd-4827-b9ff-d41a839963fb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 48 hours.
