### ISSUE TITLE
[USERSNAP] No inicia sesión en mi cuenta

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6121]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: No inicia sesión en mi cuenta
- Expected Result: Que si inicie, ya que tengo guardado la contraseña y el correo 
- Your Channel and Account Details: Mi canal es TereRecharged, ya habia asociado a la pagina anteriormente y se subieron mis videos. 
- Email or Discord handle for feedback: Brubenjaquino@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x780
**[Open #802 in Usersnap](https://app.usersnap.com/l/feedback/5cf6c956-c3e2-45ba-87b0-b92058773bf6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
