### ISSUE TITLE
[USERSNAP] I made a withdrawal, the money never arrived in my account and I deducted it (above there was a problem but the money never arrived in my account)

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6122]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: I made a withdrawal, the money never arrived in my account and I deducted it (above there was a problem but the money never arrived in my account)
- Expected Result: let them fix it
- Your Channel and Account Details: SebasDrake , j4U8vu9dESsnKzhnLtnttYjFyvWGQxQehBgFdUfX5rvqFus7o
- Email or Discord handle for feedback: sebasdrakegamer@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d65fb3f0-fce8-44fa-8cc1-7fde5f5fe26f-annotated_20ffa93f-fbe5-4668-8237-dc84ffcd80b2.png?etag=b944f3e5040162f60272ec76edf4514b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/d65fb3f0-fce8-44fa-8cc1-7fde5f5fe26f-annotated_20ffa93f-fbe5-4668-8237-dc84ffcd80b2.png?etag=b944f3e5040162f60272ec76edf4514b)*

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 2266x1275
**Browser size**: 2266x1119
**[Open #803 in Usersnap](https://app.usersnap.com/l/feedback/813baba5-756b-4699-83e9-97224584c7be?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
