### ISSUE TITLE
[USERSNAP] I can't get in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6129]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I can&#39;t get in
- Expected Result: I wanted to connect my channel, but it gave an error and as a result I can&#39;t go into the office and register again, writes such an email is already in the database. Can I delete it so that I can register again? 
- Your Channel and Account Details: alexmirr046@gmail.com
https://www.youtube.com/channel/UCVdVYbLQFKbNzQQqt4CF62w
- Email or Discord handle for feedback: alexmirr046@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #805 in Usersnap](https://app.usersnap.com/l/feedback/f079cc10-858d-4a32-8307-f689f7e88830?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
