### ISSUE TITLE
[USERSNAP] Rank

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6130]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Rank
- Expected Result: Good evening,

I wanted to inquire if you could upgrade me to silver rank. I was told that to reach this rank, I needed to be more consistent with my YouTube channel to meet the requirements, and that&#39;s what I did.
Here I attach some screenshots of my channel and my rank on Gleev.

Thank you, regards.
- Your Channel and Account Details: https://www.youtube.com/channel/UCTHyM5lbIgWM0C_DETj6PhA
- Email or Discord handle for feedback: ianchulo333@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #806 in Usersnap](https://app.usersnap.com/l/feedback/038b6e67-200d-4c85-9827-47bedef08410?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Informed the creator that verification team will have a re-evaluation for the channel and we will keep him posted with the results.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that channel reevaluation is done and upgraded from bronze to silver tier.
