### ISSUE TITLE
[USERSNAP] How to update tier

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6132]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: How to update tier
- Expected Result: support how to update silver tier or Which requirement need to updated Silver tier ? 
- Your Channel and Account Details: question only
- Email or Discord handle for feedback: ahadsaker1@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #808 in Usersnap](https://app.usersnap.com/l/feedback/83dda5bb-505c-4003-8d14-eeb5ffec721c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent an email to the creator that to advance to a higher tier, we recommend creating high-quality content and actively engaging with the platform. In this, we can consider their advancing to a higher tier in the future.
