### ISSUE TITLE
[USERSNAP] dejar el programa

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6133]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: dejar el programa
- Expected Result: por favor me ayudas a dejar el programa correo
- Your Channel and Account Details: juanpipe2014dbz@gmail.com
- Email or Discord handle for feedback: juanpipe2014dbz@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #809 in Usersnap](https://app.usersnap.com/l/feedback/3f5e830c-cb91-4753-b15b-60415025b53e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent an email to the creator that we don't offer delete option but sent instructions about opt-out.
