### ISSUE TITLE
[USERSNAP] I can't log in to my account, membership not associated

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6134]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I can&#39;t log in to my account, membership not associated
- Expected Result: Hello, today I want to log into my Gleev account and it appears that my account does not have an associated membership.
Can you please help me? I am a YouTuber content creator with more than 182,000 subscribers. 100% original and excellent quality content. I also have no copyright claims.
I even upload videos talking about gleev studio to invite people.
- Your Channel and Account Details: https://youtube.com/@LautaroBergmann?si=s2oc4WkZEPJTRYKg
- Email or Discord handle for feedback: lautibergmann@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #810 in Usersnap](https://app.usersnap.com/l/feedback/20d51eae-00d2-4bff-9cb2-070d48720036?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that channel is already in and it is under silver tier. Recommend to the creator reset the password and send the document on how to retrieve wallet seed for creators reference. 
https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
