### ISSUE TITLE
[USERSNAP] Lvl up

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6135]
**Taken at**: https://gleev.xyz/channel/59089?tab=Videos
**Fields**:
- Houston, we have a problem.: Lvl up
- Expected Result: How to lvl up bronge to silver?
- Your Channel and Account Details: 59089
MunNa
- Email or Discord handle for feedback: message me

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #811 in Usersnap](https://app.usersnap.com/l/feedback/7fb5378e-c612-4864-b3ec-4aadf14e786f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that current channel is accurate and sent recommendations on how to reconsider to level up tier in the future.
