### ISSUE TITLE
[USERSNAP] SUPPORT

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6136]
**Taken at**: https://gleev.xyz/channel/59089?tab=Videos
**Fields**:
- Houston, we have a problem.: SUPPORT
- Expected Result: Even though I have many categories and subscribers, my category is bronze. This is not a correct analysis. 2. Even though I invited many references
- Your Channel and Account Details: My channel. E posta - snntakip@gmail.com 
https://www.youtube.com/@1paramatik
- Email or Discord handle for feedback: snntakip@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #812 in Usersnap](https://app.usersnap.com/l/feedback/0383bce6-022f-4c8f-83b4-1dae93d9b552?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that current tier is correct and sent instruction on how to possibly upgrade tier in the future.
