### ISSUE TITLE
[USERSNAP] no payment again?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6137]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: no payment again?
- Expected Result: no payment again and again
- Your Channel and Account Details: BTDcrypto
- Email or Discord handle for feedback: btdcrypto8@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #813 in Usersnap](https://app.usersnap.com/l/feedback/6626f4b3-2749-4f6d-a92f-fa698ff1440a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that we will make an announcement once payment was process.
