### ISSUE TITLE
[USERSNAP] Where is my payment?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6141]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Where is my payment?
- Expected Result: I am silver ranked and my video rewards was still not been rewarded. It was delay last week and delay again?
- Your Channel and Account Details: cleansingwaters.wc@gmail.com
- Email or Discord handle for feedback: cleansingwaters.wc@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #814 in Usersnap](https://app.usersnap.com/l/feedback/8952810d-e2f9-4960-9ff8-9d96c3ab6db1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment was a bit delay but will make an announcement and loop in once it is rewarded.
