### ISSUE TITLE
[FEATURE REQUEST] Need a fix schedule for payments

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6142]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Which feature are you missing?: Need a fix schedule for payments
- What problem would that solve for you?: We have been raising this issue multiple times about payment delay.
- Share your Email or Discord so we can get in touch: cleansingwaters.wc@gmail.com
- Your Gleev channel ID or Title: Cleansing Waters

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #212 in Usersnap](https://app.usersnap.com/l/feedback/f8e65396-9fc0-4e6b-bc78-887a32bda2ad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator and let know that this is being worked out.
