### ISSUE TITLE
[USERSNAP] Signup Bonus Not Received 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6143]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Signup Bonus Not Received 
- Expected Result: I Were Suppose To Get 2 Dollar Worth Of Joy Coins Yesterday But I didn&#39;t Received Anything 
- Your Channel and Account Details: Nomi Bro ML
- Email or Discord handle for feedback: Nomitrap017@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x800
**[Open #815 in Usersnap](https://app.usersnap.com/l/feedback/6a9bb23f-9389-4bfa-ab85-f3046b2050ae?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
