### ISSUE TITLE
[USERSNAP] ¿Dónde está el pago?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6145]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: ¿Dónde está el pago?
- Expected Result: No hay pago nuevamente para esta semana, al igual que en las últimas semanas.
- Your Channel and Account Details: Genera ingresos Por Internet
- Email or Discord handle for feedback: Genera ingresos Por Internet

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #816 in Usersnap](https://app.usersnap.com/l/feedback/6756acde-5abe-43fa-996e-3657d9a8d6f6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
