### ISSUE TITLE
[USERSNAP] I don't know why I join

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6146]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I don&#39;t know why I join
- Expected Result: It has been really a struggle joining your platform. No rewards at all. 
- Your Channel and Account Details: No
- Email or Discord handle for feedback: I dont need

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #817 in Usersnap](https://app.usersnap.com/l/feedback/93d86d39-c13b-4958-96ef-b2fc756651c2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Closed ticket as no way to get back to the creator.
