### ISSUE TITLE
[USERSNAP] Сколько я смогу заработать, если мой канал только запускается?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6147]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Сколько я смогу заработать, если мой канал только запускается?
- Expected Result: Я планирую создать канал на YouTube, вы меня примете?
- Your Channel and Account Details: dinara1@gmail.com
- Email or Discord handle for feedback: dinara1@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #818 in Usersnap](https://app.usersnap.com/l/feedback/9d148a76-d9a7-4d8c-b154-66c51004a28d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent an email to the creator the program outline for more information. https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb
