### ISSUE TITLE
[USERSNAP] How can I withdraw my balance? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6148]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: How can I withdraw my balance? 
- Expected Result: Hello folks! I still have a little joy but I don&#39;t know how to get it. 
- Your Channel and Account Details: cryptowonderland23@gmail.com
- Email or Discord handle for feedback: cryptowonderland23@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #819 in Usersnap](https://app.usersnap.com/l/feedback/5c9eb850-5c7c-4772-8aba-46de253e11ac?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
