### ISSUE TITLE
[USERSNAP] Payment is missing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6149]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Payment is missing
- Expected Result: Hi there! The payment for my channel is missing. I&#39;ve been waiting for 2 days now. Any updates please? 
- Your Channel and Account Details: UJ Crypto
- Email or Discord handle for feedback: unionjagcrypto@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #820 in Usersnap](https://app.usersnap.com/l/feedback/f16740fa-7daf-4986-b661-b234413c4bfd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
