### ISSUE TITLE
[USERSNAP] Why my channel is suspended? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6150]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Why my channel is suspended? 
- Expected Result: I have a good content and I was suspended? What is happening?
- Your Channel and Account Details: https://www.youtube.com/@PepeRoni777/videos
- Email or Discord handle for feedback: simonzralok@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #821 in Usersnap](https://app.usersnap.com/l/feedback/55c63ca5-5d5f-4ab2-911f-87c3919ef9a2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
