### ISSUE TITLE
[USERSNAP] I dont have phrase

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6151]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I dont have phrase
- Expected Result: Please reset phrase and enable to change password
- Your Channel and Account Details: Abdul.hananah08@gmail.com
- Email or Discord handle for feedback: Abdul.hananah08@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x760
**[Open #822 in Usersnap](https://app.usersnap.com/l/feedback/c47faa38-4f9a-4cff-bfc9-abb5770a3f2e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference. 
https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
