### ISSUE TITLE
[USERSNAP] I dont have login gleev account && No phrase to forget password

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6152]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I dont have login gleev account &amp;&amp; No phrase to forget password
- Expected Result: Please reset phrase to login my account with only email.
- Your Channel and Account Details: Abdul.hananah08@gmail.com
- Email or Discord handle for feedback: Abdul.hananah08@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x760
**[Open #823 in Usersnap](https://app.usersnap.com/l/feedback/b032fa0a-6241-47c4-b170-ea41be4cb2d3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
