### ISSUE TITLE
[USERSNAP] I dont have login password gleev.xyz account && No phrase to forget password

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6153]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I dont have login password gleev.xyz account &amp;&amp; No phrase to forget password
- Expected Result: 
Please reset phrase to login my account with only email.
- Your Channel and Account Details: abdul.hananah08@gmail.com
- Email or Discord handle for feedback: abdul.hananah08@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x760
**[Open #824 in Usersnap](https://app.usersnap.com/l/feedback/a661dcad-0850-4f5a-9fe5-9fdf663a57c4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this ticket as it is duplicated.
