### ISSUE TITLE
[FEATURE REQUEST] nada mas quiero cumplir mi sueño  de crear el mejor juego y ayudar a mi familia 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6154]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- ¿Qué característica te estás perdiendo?: nada mas quiero cumplir mi sueño  de crear el mejor juego y ayudar a mi familia 
- ¿Qué problema resolvería eso para ti?: yo resolveria que la personas que si nescita
- Share your Email or Discord so we can get in touch: saggiomohector@gmail.com
- Your Gleev channel ID or Title: dark nighit

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1024x600
**[Open #213 in Usersnap](https://app.usersnap.com/l/feedback/39bd2e63-2bcb-4be5-a4fa-fab6872f3f85?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified/not clear. Acknowledge creator concern and ask how we can assist.
