### ISSUE TITLE
[USERSNAP] Really? I am suspended?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6155]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Really? I am suspended?
- Expected Result: I just joined and suspended immediately? 
- Your Channel and Account Details: Here is my youtube channel: https://www.youtube.com/channel/UC2wu_YDwuNluTQSaOYsxLZg
- Email or Discord handle for feedback: fernandobraz529@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #825 in Usersnap](https://app.usersnap.com/l/feedback/b7699c34-03ab-4a7f-a989-561e9ba83d45?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Checked the channel and it didn't meet the requirements to be verified. Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
