### ISSUE TITLE
[USERSNAP] ¿No hay pago para esta semana?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6156]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: ¿No hay pago para esta semana?
- Expected Result: ¡Hola, equipo! Ya es viernes y ya son 3 días y todavía no recibimos los pagos. ¿Lo que está sucediendo?
- Your Channel and Account Details: https://www.youtube.com/@CineTop/videos
lucassilvalopesramos@gmail.com
- Email or Discord handle for feedback: lucassilvalopesramos@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #826 in Usersnap](https://app.usersnap.com/l/feedback/cfa3c2e0-83a1-43ac-8c1b-e4321182ae56?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
