### ISSUE TITLE
[USERSNAP] Hi! Any updates with the payment for this week?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6157]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Hi! Any updates with the payment for this week?
- Expected Result: Payment error, I guess? Any updates?
- Your Channel and Account Details: cleansingwaters.wc@gmail.com
- Email or Discord handle for feedback: cleansingwaters.wc@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #827 in Usersnap](https://app.usersnap.com/l/feedback/3818294d-44f7-4c02-812d-3827dc5992f3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
