### ISSUE TITLE
[FEATURE REQUEST] Hire ME

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6158]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Which feature are you missing?: Hire ME
- What problem would that solve for you?: Hi, how are you doing today?
I am a lead frontend and web3 developer looking for new opportunity.
I have over 12 years of experience with building websites &amp; web apps and over 5 years of experience with blockchain technology.
I have strong experience with building frontend ui based on responsive features, translating UX/UI designs into interactive interfaces, collaborating with the backend for API &amp; web3 integrations.
And I&#39;m highly experienced with building Defi/Dao/Dex, NFT marketplace(mint, buy, sell, staking, auction and etc ), p2e/crypto games, so I have been working in blockchain field for recent 5 years.

My comprehensive knowledge and experience span across:
● JavaScript (including TypeScript, React.js, Next.js, Angular, Vue.js, Node.js, and Express.js)
● Frontend development (HTML5, CSS3/SCSS, Bootstrap, Tailwind and Material UI)
● Databases (MySQL, Postgres, Amazon DynamoDB and MongoDB)
● Web3 technologies (Web3.js, Ethers.js, Truffle/Hardhat/Remix, wagmi)
● Cloud services (AWS, Firebase, Heroku, and Azure)
● Blockchain Network: EVM (ethereum, polygon, bsc, avax and etc), Solana, IOTA, phantasma and etc.

I am currently looking for full-time or part-time opportunities as web and blockchain developer. I am available to start immediately.
Please let me know if you have any works or opening positions.
- Share your Email or Discord so we can get in touch: nagelsmann3@gmail.com
- Your Gleev channel ID or Title: nagelsmann3@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #214 in Usersnap](https://app.usersnap.com/l/feedback/e13b6308-cb74-4f62-af85-7da863ce6832?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Send an email to the user to join discord and check opportunities for any available position.
