### ISSUE TITLE
[USERSNAP] It's 4 days now and yet there is no payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6165]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: It&#39;s 4 days now and yet there is no payment
- Expected Result: No payment for this week and another payment for next week no again?
- Your Channel and Account Details: Crypto Chris
- Email or Discord handle for feedback: juanpipebz@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #830 in Usersnap](https://app.usersnap.com/l/feedback/02c2ac32-a758-4a8a-bbe0-96c9bdf9c411?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
