### ISSUE TITLE
[USERSNAP] Estoy interesado en ganar más. ¿Cómo puedo referirme?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6166]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Estoy interesado en ganar más. ¿Cómo puedo referirme?
- Expected Result: No tengo youtube pero tengo muchas amigas que lo hacen.
- Your Channel and Account Details: Aún no tengo un canal de YouTube, pero lo crearé pronto.
- Email or Discord handle for feedback: elcoraldejasper@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #831 in Usersnap](https://app.usersnap.com/l/feedback/400b7d32-f019-40d2-9b66-f4d8f667cb48?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Send an email to the creator in regards to referral program. How to and how much to earn in referring.
