### ISSUE TITLE
[FEATURE REQUEST] My channel payment

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6167]
**Taken at**: https://gleev.xyz/
**Fields**:
- Which feature are you missing?: My channel payment
- What problem would that solve for you?: It&#39;s been a week now and yet I didn&#39;t receive my payment. What will happen now?
- Share your Email or Discord so we can get in touch: cleasingwaters.wc@gmail.com
- Your Gleev channel ID or Title: cleasingwaters.wc@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #215 in Usersnap](https://app.usersnap.com/l/feedback/69f5b6b8-733b-4643-b530-f93243a109d0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for this week was delayed. Will sent a reminder to the creator once payment got processed.
