### ISSUE TITLE
[USERSNAP] How long does verification takes?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6168]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: How long does verification takes?
- Expected Result: I just joined and it shows pending. How long should I wait?
- Your Channel and Account Details: https://www.youtube.com/@PopMusic1811
- Email or Discord handle for feedback: popmusic1811@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1536x960
**[Open #832 in Usersnap](https://app.usersnap.com/l/feedback/96761ce0-99a6-450d-ba8a-4772c49aa2bf?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that verification usually takes 24-48 hours.
