### ISSUE TITLE
[USERSNAP] No channel with this title found error 😕

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6170]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: No channel with this title found error 😕
- Expected Result: Hi team I report this issue soo many time please fix this bug when i referral someone and gleev automatically pick my channel name showing error &#34; no channel with this title has been found&#34; this error i attached this error screenshot please fix this error and can you please hire for some works i have experience to test many type of web and apps and some errors sulotion can you please hire me. Thanks you i am waiting for reply
- Your Channel and Account Details: j4To6jgKfy8MgiMRDXzc15ggN8AnFAzp1MPKHx88TFNmK8LbN
- Email or Discord handle for feedback: worldinfo288@gmail.com

**Browser**: Chrome 123 (Linux)
**Screen size**: 424x942
**[Open #834 in Usersnap](https://app.usersnap.com/l/feedback/4ebb7460-369b-4963-b37b-c628dcf3b62a?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Recommend to the creator to generate his referral link and share it directly to his referrals instead of manual channel input upon referral sign-up process.
