### ISSUE TITLE
[USERSNAP] Not move after verification need of robot

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6171]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Not move after verification need of robot
- Expected Result: Maybe in better way
- Your Channel and Account Details: Niazshah
- Email or Discord handle for feedback: niazshah@gmail.com

**Browser**: Safari 15 (iOS)
**Screen size**: 375x667
**[Open #835 in Usersnap](https://app.usersnap.com/l/feedback/319bfe64-344b-468d-9257-6fd6c0b67f74?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified/unclear. Acknowledge creator concern and ask how we can assist.
