### ISSUE TITLE
[USERSNAP] How can I verify that I am not robot 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6172]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: How can I verify that I am not robot 
- Expected Result: Problem in sign up
- Your Channel and Account Details: Problem in sign up
- Email or Discord handle for feedback: niazshah99@gmail.com

**Browser**: Safari 15 (iOS)
**Screen size**: 375x667
**[Open #836 in Usersnap](https://app.usersnap.com/l/feedback/0d1b55a0-c58b-4eaf-b4bd-12e39bfec08f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicate issue * closed ticket
