### ISSUE TITLE
[USERSNAP] What happen to our payments?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6173]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: What happen to our payments?
- Expected Result: It has been a week now since the last payment. The new payment will come up tomorrow . Can you tell us what happen? 
- Your Channel and Account Details: BTD Crypto
- Email or Discord handle for feedback: cryptobtd7@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #837 in Usersnap](https://app.usersnap.com/l/feedback/92b3691b-8640-44d7-bd40-1876cb80bd47?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that payment for last week was delayed. Let know the creator that payment most likely will be settled today or tomorrow.
