### ISSUE TITLE
[USERSNAP] What kind of content will makes me gold?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6174]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: What kind of content will makes me gold?
- Expected Result: I want to level up
- Your Channel and Account Details: Kripto Jasper
- Email or Discord handle for feedback: kriptojasperdev5@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #838 in Usersnap](https://app.usersnap.com/l/feedback/10454637-0129-4600-a2ee-0ee804249cd0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Advised the creator to maintain their current content while providing comprehensive guidelines on crafting high-quality material.
