### ISSUE TITLE
All CRTs table - default sorting

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#6175]
Currently, we can only sort by creation date, it would be good if user could order by total revenue and market cap as well.

![image](https://github.com/Joystream/atlas/assets/92513933/41ba1ea8-27f0-4862-81aa-3442692cf3ee)

1. Market cap - we cannot order by market cap, because market cap isn't a creator token field, we calc it on the client side as `lastPrice * totalSupply`
2. Total revenue - this field is present in Orion, but it belongs to a channel, so there is no way to sort by it as well

Market cap could be added CRT entity and updated by the mappings. 

Total revenue is harder to maintain as each time we modify this field for a channel we would need to adjust it for a creator token as well. (or maybe there is some kind of abstraction that would handle it more gracefully, but I do not know such thing)

**Comment by zeeshanakram3** [comment]
> Market cap could be added CRT entity and updated by the mappings.

Sure, having derived `marketCap` property seems like good idea, it would avoid hassle of doing client side calculations

> Total revenue is harder to maintain as each time we modify this field for a channel we would need to adjust it for a creator token as well. (or maybe there is some kind of abstraction that would handle it more gracefully, but I do not know such thing)

You could achieve this using Postgres views, i.e. first move `creator_token` to admin schema, then create public `creator_token` views by joining `creator_token` and `channel` tables, and including all fields of `creator_token` table + `channel`.`cumulative_revenue`

Also, it might be a bit tricky to properly manage all migrations, since `creator_token` table already exist on production, so let me know if you want me to handle it?

**Comment by WRadoslaw** [comment]
> > Market cap could be added CRT entity and updated by the mappings.
> 
> Sure, having derived `marketCap` property seems like good idea, it would avoid hassle of doing client side calculations
> 
> > Total revenue is harder to maintain as each time we modify this field for a channel we would need to adjust it for a creator token as well. (or maybe there is some kind of abstraction that would handle it more gracefully, but I do not know such thing)
> 
> You could achieve this using Postgres views, i.e. first move `creator_token` to admin schema, then create public `creator_token` views by joining `creator_token` and `channel` tables, and including all fields of `creator_token` table + `channel`.`cumulative_revenue`
> 
> Also, it might be a bit tricky to properly manage all migrations, since `creator_token` table already exist on production, so let me know if you want me to handle it?
> 

Your call @dmtrjsg

**Comment by dmtrjsg** [comment]
No need for the release. But great that we looked into it so once the volume of tokens picks up we can come back and implement the table header sorting. For now let's focus on launching the first version, recommendations and mobile experience. @zeeshanakram3 @WRadoslaw cc @bedeho

**Comment by dmtrjsg** [comment]
Needs to be done together with: 
- https://github.com/Joystream/atlas/issues/6354
