### ISSUE TITLE
[USERSNAP] i have many more channels and i want to join gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6178]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: i have many more channels and i want to join gleev
- Expected Result: i have many more channels and i want to join gleev
- Your Channel and Account Details: i have many more channels and i want to join gleev , can i create more gleev accounts to join yt chanel ? on my other mails 
- Email or Discord handle for feedback: hatech539@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1366x768
**[Open #839 in Usersnap](https://app.usersnap.com/l/feedback/b1520fef-a437-44be-bc04-f583159336ea?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that we allow connecting multiple YT channels in a single membership. Sent steps via email.
