### ISSUE TITLE
[USERSNAP] I can’t open my account. I’m connecting YouTube also

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6179]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I can’t open my account. I’m connecting YouTube also
- Expected Result: My error is show me that older than 1 
(Authorization failed
An unexpected error occurred.
Please try again.)
I can’t open my email and I can’t forget password. Please fix my issue.
- Your Channel and Account Details: Salahshaz989@gmail.com
- Email or Discord handle for feedback: Salahshaz989@gmail.com

**Browser**: Safari 17 (iOS)
**Screen size**: 414x896
**[Open #840 in Usersnap](https://app.usersnap.com/l/feedback/5fc0c6c6-3b0b-43c5-9b79-f69f819d1615?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset the password and send the document on how to retrieve wallet seed for creators reference. https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76 
Also informed the creator that channel is suspended.
