### ISSUE TITLE
[USERSNAP] Today morning 125 joy was credited to my account but it has vaniahed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6180]
**Taken at**: https://gleev.xyz/member/sdmcl?tab=Activity
**Fields**:
- Houston, we have a problem.: Today morning 125 joy was credited to my account but it has vaniahed
- Expected Result: Nothing
- Your Channel and Account Details: harekrishna.sandip@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/288f4a30-76c9-431b-8fea-0b86c34d33ef-annotated_484434d9-c907-4395-a9f1-a22ec74a10b3.png?etag=8104670d016996cf45e8bf1d0a2fe8ba)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/288f4a30-76c9-431b-8fea-0b86c34d33ef-annotated_484434d9-c907-4395-a9f1-a22ec74a10b3.png?etag=8104670d016996cf45e8bf1d0a2fe8ba)*

**Browser**: Chrome 122 (Android 10)
**Screen size**: 360x760
**Browser size**: 360x630
**[Open #841 in Usersnap](https://app.usersnap.com/l/feedback/6fc495a9-1b87-4ac4-898e-6b1f97ba0ace?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
