### ISSUE TITLE
[USERSNAP] I forget my password & I didn't have wallet seed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6182]
**Taken at**: https://gleev.xyz/marketplace
**Fields**:
- Houston, we have a problem.: I forget my password &amp; I didn&#39;t have wallet seed
- Expected Result: Pls help me
- Your Channel and Account Details: teamwolfgamingyt78@gmail.com
- Email or Discord handle for feedback: gamingworld4055@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x800
**[Open #842 in Usersnap](https://app.usersnap.com/l/feedback/5dd3b375-b8c4-49f9-be10-eac80a71787b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
