### ISSUE TITLE
[USERSNAP] How can I withdraw my balance? 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6185]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: How can I withdraw my balance? 
- Expected Result: I received an email that I was rewarded, can you tell me how can I get it?
- Your Channel and Account Details: cryptowonderland23@gmail.com
- Email or Discord handle for feedback: cryptowonderland23@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #843 in Usersnap](https://app.usersnap.com/l/feedback/f7e82ae6-4bae-4557-b555-5dc7a33f49a1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
