### ISSUE TITLE
[USERSNAP] Application for Community Moderator

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6186]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Application for Community Moderator
- Expected Result: Hi My Name is Christina Alford. I am writing to express my interest in the HR Community Moderator position at Joystream as advertised. With extensive experience in human resources and a strong commitment to creating inclusive workplace communities, I am eager to contribute to your team. I look forward to the possibility of discussing how I can contribute to your team. Thank you for considering my application.
- Your Channel and Account Details: I have no channel but I want to work with you 
- Email or Discord handle for feedback: christinaalford9@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1920x1080
**[Open #844 in Usersnap](https://app.usersnap.com/l/feedback/97edfcca-4dc0-4229-a948-36983b497338?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this issue as this is not a creator concern. No further actions needed.
