### ISSUE TITLE
[FEATURE REQUEST] Djfjfjfj

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6188]
**Taken at**: https://gleev.xyz/ypp?state=code%3D83rdy5vsr%26channelId%3D&code=4/0AeaYSHDwdZ8UTGxC0PkaFpBkJmWjTeP1hGHYMuMMaBn-_nDCPGWll4dbajFMFEG3n7ZNzQ&scope=email%20openid%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
**Fields**:
- ¿Qué característica te estás perdiendo?: Djfjfjfj
- ¿Qué problema resolvería eso para ti?: Nddbfnf
- Share your Email or Discord so we can get in touch: thorangel715@gmail.com
- Your Gleev channel ID or Title: Jdkkjhhkdkfjfjf

**Browser**: Chrome 123 (Android 10)
**Screen size**: 320x640
**[Open #216 in Usersnap](https://app.usersnap.com/l/feedback/5fc39553-ea85-43fc-b197-916d12378d7e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not specified. Acknowledge creator concern and ask how we can assist.
