### ISSUE TITLE
[USERSNAP] Hi, why you need creators to sign up what is your goal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6189]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Hi, why you need creators to sign up what is your goal
- Expected Result: Good
- Your Channel and Account Details: socialnext1755@gmail.com
- Email or Discord handle for feedback: socialnext1755@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x820
**[Open #845 in Usersnap](https://app.usersnap.com/l/feedback/c3dc7441-35d9-4380-b7c2-4ecc9f5a2661?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator in regards to the youtube partnership program. Closed ticket as this is not a creator concern.
