### ISSUE TITLE
[USERSNAP] I lose my secret phrase 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6190]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I lose my secret phrase 
- Expected Result: Send the secret phrase in my email dropadi947@gmail.com
- Your Channel and Account Details: Satisfyingbrooooo

**Browser**: Chrome 111 (Android 10)
**Screen size**: 393x895
**[Open #846 in Usersnap](https://app.usersnap.com/l/feedback/af8aba32-9d26-4edc-bfd0-6c8df681ab01?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
