### ISSUE TITLE
[USERSNAP] Not copy my refferl link

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6195]
**Taken at**: https://gleev.xyz/referrals
**Fields**:
- Houston, we have a problem.: Not copy my refferl link
- Expected Result: Not copy my refferl link
- Your Channel and Account Details: khanewalcreative@gmail.com
- Email or Discord handle for feedback: huzaimamaster69@gmail.com

**Browser**: Chrome 119 (Android 10)
**Screen size**: 360x800
**[Open #847 in Usersnap](https://app.usersnap.com/l/feedback/853dac33-524b-4609-b13a-02ad76d1db0b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and ask specific question about referral link, also send steps.
