### ISSUE TITLE
[USERSNAP] I can’t open my account because my account is connecting YouTube. I want to connect my account coming error and I also I can’t forget password. I don’t know why because I am connect direct my YouTube. I don’t get password.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6196]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: I can’t open my account because my account is connecting YouTube. I want to connect my account coming error and I also I can’t forget password. I don’t know why because I am connect direct my YouTube. I don’t get password.
- Expected Result: Please fix my issue. I can’t open my account. I can’t forget my password so please check what problem showing me Authorization failed
An unexpected error occurred.
Please try again.
나
- Your Channel and Account Details: balochiofficials9638
- Email or Discord handle for feedback: Salahshaz989@gmail.com // balochiofficials9638

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e5acd7a8-df87-4a3c-b51c-1eb7e59fe254-annotated_efeea3a8-6a4f-4d7c-b92f-f047909d0f0f.png?etag=5cc1bb742ddf7839ef9e8093a3d75871)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e5acd7a8-df87-4a3c-b51c-1eb7e59fe254-annotated_efeea3a8-6a4f-4d7c-b92f-f047909d0f0f.png?etag=5cc1bb742ddf7839ef9e8093a3d75871)*

**Browser**: Safari 17 (macOS Catalina)
**Screen size**: 414x896
**Browser size**: 360x674
**[Open #848 in Usersnap](https://app.usersnap.com/l/feedback/4e7ee12d-afb7-40d1-b43a-893a944ad879?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent creator email Password Reset Instructions and informed along that channel didn't make it in the platform.
