### ISSUE TITLE
[USERSNAP] The problem is that I was connected in direct YouTube, I don't know, it also gives direct violet code, so I didn't save it when I was connecting, if I was doing password on 12seed Wallet. Need direct code of

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6197]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: The problem is that I was connected in direct YouTube, I don&#39;t know, it also gives direct violet code, so I didn&#39;t save it when I was connecting, if I was doing password on 12seed Wallet. Need direct code of
- Expected Result: Actually I have the account directly connected to my YouTube and I don&#39;t get this 12 code seed wallet save it maybe or I didn&#39;t see attention I didn&#39;t save because then automatic I connect it in YouTube After automatic I shut down then tried to log in again I can&#39;t connect I press the forget password section I just need seed phrase 12 digit wallet code which I didn&#39;t save If you guys delete this account completely then Again I will connect I will also save this code because I am connecting now it says ready this account is connected if you can give 12 code ok no problem if you can&#39;t then delete this account full thank you 
- Your Channel and Account Details: balochiofficials9638 salahshaz989@gmail.com
- Email or Discord handle for feedback: Salahshaz989@gmail.com// balochiofficials9638

**Browser**: Safari 17 (macOS Catalina)
**Screen size**: 414x896
**[Open #849 in Usersnap](https://app.usersnap.com/l/feedback/431b6714-d392-4201-97b0-5a66303329d2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Sent creator email Password Reset Instructions and informed along that channel didn't make it in the platform.
