### ISSUE TITLE
[USERSNAP] i have been trying to link my youtube channel 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6198]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: i have been trying to link my youtube channel 
- Expected Result: its been 3days i have been trying to link my account to sync youtube videos its dosent get uploaded or linked, have tried with multiple accounts there is no error or update
- Your Channel and Account Details: anjuyande@gmail.com - Gmail
@anjaliyande4383 - youtube handel
- Email or Discord handle for feedback: yashyande@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1280x720
**[Open #850 in Usersnap](https://app.usersnap.com/l/feedback/d8b1ec34-21eb-4e68-8bfb-3dd990145f5e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
