### ISSUE TITLE
Progress indicator in carousel

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#62]
Currently, there is no visual feedback to the user how many times they will have to click before they have exhausted the carousel, they will just notice content repeating at some unpredictable time. This is lack of predictability discouraged exploration.

**Comment by KubaMikolajczyk** [comment]
The carousel component was reiterated and visual progress indicator was added ☝️
Carousel component: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=8426%3A593
Should we close this @kdembler ?

**Comment by kdembler** [comment]
Yep
