### ISSUE TITLE
[FEATURE REQUEST] cancelar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6200]
**Taken at**: https://gleev.xyz/member/settings?tab=Notifications
**Fields**:
- Que dispõem que está faltando?: cancelar
- O problema teria que resolver para você?: Quero cancelar minha conta
- Share your Email or Discord so we can get in touch: somoscorinthianseternamente@gmail.com

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1366x768
**[Open #217 in Usersnap](https://app.usersnap.com/l/feedback/2d6848c0-55a0-42e3-8a9d-da15dbd52d1e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed creator opt out option and terms and conditions.
