### ISSUE TITLE
[USERSNAP] No puedo ingresar a mi cuenta

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6204]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: No puedo ingresar a mi cuenta
- Expected Result: El restaurarla
- Your Channel and Account Details: don.juego.r@gmail.com
- Email or Discord handle for feedback: don.juego.r@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 412x915
**[Open #851 in Usersnap](https://app.usersnap.com/l/feedback/7a378bc1-0617-4d08-ba75-5f2619b4bfc5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action  Item: Informed the creator to send the error message why they can't login.
