### ISSUE TITLE
CRT post release fixes

### ISSUE THREAD

**Issue by WRadoslaw** [Joystream/atlas#6205]
- Integrate runtime constants into the app (min revenue share duration, min amm slope param, min amm outstanding tokens, etc.)
- Inflation on channel page is hidden, when 0% is picked
- Change number formatting to short on holder table on channel token view

**Comment by kdembler** [comment]
### Broken token view on mobile safari
![CleanShot 2024-04-23 at 11 22 28@2x](https://github.com/Joystream/atlas/assets/12646744/5b68b76f-3486-4f3c-bf2c-47f7f9f22b9b)

### Holders dialog issues
1. When I move through pages, the token amounts get updated with a bit of lag.
2. Same user (`songoku`) can be seen on the first and second page
3. When I get to the last page, the dialog height changes which is a bit disruptive, I would suggest to keep it at a fixed height


https://github.com/Joystream/atlas/assets/12646744/b7b5691c-0f46-4cf9-b1ff-57cc7fbde503
