### ISSUE TITLE
CRT: Inform creators that during active revenue split Market Transactions are paused.

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6206]
## context
Creators do not anticipate that active Revenue splits will result in transactions on open market been put on pause (unavailable). 

## scope
Find a place in the UX which informs creators about it.

**Comment by msmadeline** [comment]
@dmtrjsg Hey, I added little warning copy on the bottom of the modal that is telling user about the transaction pause. Let me know wdyt

➡figma link: https://www.figma.com/file/OuywwClsegx2eotkii4ea4/My-token?type=design&node-id=3679-23218&mode=design&t=ULuUGQwtgU3jozxo-4
