### ISSUE TITLE
[USERSNAP] oh my god the payments get lower and lower

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6214]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: oh my god the payments get lower and lower
- Expected Result: referral only half and video whats happening?
- Your Channel and Account Details: na
- Email or Discord handle for feedback: oran.lal2004@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1920x1080
**[Open #852 in Usersnap](https://app.usersnap.com/l/feedback/351ac2ca-0827-49bd-8034-c38955a7aa47?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that there is an update in regards to the creator ypp  rewards. Sent document for the upcoming creator rewards for more earning opportunities. https://joystream.notion.site/WIP-Creator-Rewards-2-0-934f2e7348d8468598e4304b36f2c82b
