### ISSUE TITLE
[USERSNAP] Video Sync Rewards is too low now

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6215]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Video Sync Rewards is too low now
- Expected Result: What happen to the updates? Not that good.
- Your Channel and Account Details: cleansing waters
- Email or Discord handle for feedback: cleansingwaters.wc@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1920x1080
**[Open #853 in Usersnap](https://app.usersnap.com/l/feedback/749f691a-8bf8-42f3-bb11-19335a54bc12?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that there is an update in regards to the creator ypp  rewards. Sent document for the upcoming creator rewards for more earning opportunities. https://joystream.notion.site/WIP-Creator-Rewards-2-0-934f2e7348d8468598e4304b36f2c82b
