### ISSUE TITLE
[USERSNAP] Payment 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6216]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: Payment 
- Expected Result: Payment option not show my account
- Your Channel and Account Details: muhammadasifmajeed08@gmail.com
- Email or Discord handle for feedback: muhammadasifmajeed08@gmail.com

**Browser**: Chrome 123 (Android 10)
**Screen size**: 360x800
**[Open #854 in Usersnap](https://app.usersnap.com/l/feedback/5fa1b91a-cb45-4176-a54a-bc7fefb5d856?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
