### ISSUE TITLE
[USERSNAP] i dont recive my withdraw money but my joy token cut now plese chake

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6217]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: i dont recive my withdraw money but my joy token cut now plese chake
- Expected Result: solve my problem
- Your Channel and Account Details: ruokbhai007

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1536x864
**[Open #855 in Usersnap](https://app.usersnap.com/l/feedback/470954d9-b529-4d34-9f64-e06dc21f1b8c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed ticket as channel not found and no email address to get back to the creator.
