### ISSUE TITLE
Bug: Follower relationships display

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#622]
When I open the drawer I see this

![Screenshot 2021-05-15 at 14 33 23](https://user-images.githubusercontent.com/437292/118361266-e78fb000-b58a-11eb-9ac8-c1c2782e26b8.png)

and when I click `Show 6 More` I see

![Screenshot 2021-05-15 at 14 33 30](https://user-images.githubusercontent.com/437292/118361286-fa09e980-b58a-11eb-9176-37002cd00ed5.png)

**Comment by kdembler** [comment]
Fixed on Sumer
