### ISSUE TITLE
Opening portfolio from snackbar after amm buy fails

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6222]
I just bought a token using amm, then when the snack bar opens I try to click the link to the portfolio, and it it shows me this

<img width="1691" alt="Screenshot 2024-04-26 at 00 47 19" src="https://github.com/Joystream/atlas/assets/437292/c2210c82-22c1-44be-a7c2-18f4364edbce">

**Comment by WRadoslaw** [comment]
I cannot reproduce it. If it happens again, please add a console screenshot with an error.
