### ISSUE TITLE
[USERSNAP] Куда выводить?

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6223]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Куда выводить?
- Expected Result: Я не понимаю куда и как выводить JOY. Единственное я нашел кошелёк Talisman и в нем токен JOY в сети poligon. Это он? Тогда как туда выводить?
- Your Channel and Account Details: Это вопрос, канал я ещё не подключил
- Email or Discord handle for feedback: cimoko.play@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1920x1080
**[Open #858 in Usersnap](https://app.usersnap.com/l/feedback/eda48d90-2583-4020-a085-ae5a426d13b5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator and ask to elaborate their issue.
