### ISSUE TITLE
[USERSNAP] Login Problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6235]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Login Problem 
- Expected Result: Login Problem 
- Your Channel and Account Details: Rejoan Tv
- Email or Discord handle for feedback: iammuslim815@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 360x800
**[Open #861 in Usersnap](https://app.usersnap.com/l/feedback/26536e82-8584-444b-a65f-c63a24723e30?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reach out to the creator to elaborate on their login issues and ask for the error they are getting.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
