### ISSUE TITLE
[USERSNAP] Unstaking tokens from ended revenue share is not available from portfolio page

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6237]
**Taken at**: https://gleev.xyz/channel/7698?tab=Token
**Fields**:
- Houston, we have a problem.: Unstaking tokens from ended revenue share is not available from portfolio page
- Expected Result: It should be accessible from portfolio page
Now creators can do it only from their studio panel
- Your Channel and Account Details: https://gleev.xyz/channel/7698
- Email or Discord handle for feedback: joystream

**Browser**: Firefox 125 (macOS Catalina)
**Screen size**: 1881x1218
**[Open #862 in Usersnap](https://app.usersnap.com/l/feedback/3593a3a6-45db-447f-88d5-050aee2958b1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by WRadoslaw** [comment]
As the owner I was able to unlock tokens through portfolio
