### ISSUE TITLE
Bad loading state transition on feature carousel

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6238]
When going to market place, there is a nasty artefact when loading the carousel. It is visible between the grey loading state and when the content is actually rendered, and it looks like a sort of highlight border around the cards, gives a bad feeling like an error or something broke, tried to take screenshot, not sure I really captured. I'm on firefox.

<img width="1189" alt="Screenshot 2024-04-30 at 16 59 14" src="https://github.com/Joystream/atlas/assets/437292/dd4b2aa5-a2c8-4b72-ba1c-d41cb9613baf">

**Comment by WRadoslaw** [comment]
Let's set a time box for debugging this. I tried to fix it for 30-60 mins before this issue was raised, not sure how much more we are willing to sacrifice

**Comment by bedeho** [comment]
Were you able to reproduce it?

**Comment by WRadoslaw** [comment]
> Were you able to reproduce it?

Reproduce - yes, fix - not ;C

I assume you are talking about the black screen with a white border when loading skeleton disappears and the video is not yet shown.

**Comment by bedeho** [comment]
yep. I don't think this is a bug though, at least that is not obvious, it may just be that this state does not look so good.

**Comment by WRadoslaw** [comment]
I will give it an hour max
