### ISSUE TITLE
No hover indicator for cursor

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6239]
There is no click pointer shown when you hover over these tabs, so its really confusing if you can actually click them or not. 

<img width="702" alt="Screenshot 2024-04-30 at 17 11 02" src="https://github.com/Joystream/atlas/assets/437292/3cfaa492-a0c5-46c8-950c-73f023d94d8a">

**Comment by WRadoslaw** [comment]
There is a bottom border when you hover over other tabs, for me both on Windows and Mac the cursor switches to pointer.

![image](https://github.com/Joystream/atlas/assets/92513933/daef52e2-ca85-4c48-b0c8-806b92051879)

![image](https://github.com/Joystream/atlas/assets/92513933/b56b5607-764b-49e6-b807-9527f5d13d4a)

**Comment by bedeho** [comment]
Which browser? I use FF 
![Screenshot 2024-05-07 at 11 15 11](https://github.com/Joystream/atlas/assets/437292/5acb8f95-b0d7-49b6-973e-57f176633ecb)

**Comment by WRadoslaw** [comment]
> Which browser? I use FF

I tested both Chrome and FF
