### ISSUE TITLE
[USERSNAP] Channel Verification Problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6242]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Channel Verification Problem 
- Expected Result: I Have Completed My Subscribes To The Required Amount My Channel Should Be Verified Now
- Your Channel and Account Details: Nomitrap053@gmail.com
- Email or Discord handle for feedback: noumanmustata786@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x800
**[Open #863 in Usersnap](https://app.usersnap.com/l/feedback/2db914d5-67b1-4d46-b438-8779eda43f34?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Duplicated issue.
