### ISSUE TITLE
[USERSNAP] Account Suspended Mistakenly 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6243]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Account Suspended Mistakenly 
- Expected Result: My Subs Decreased When I joined Gleev &amp; My Account Got suspended But now I have Regained My Subs &amp; I request A Review 
- Your Channel and Account Details: Nomitrap005@gmail.com
- Email or Discord handle for feedback: noumanmustata786@gmail.com

**Browser**: Chrome 116 (Android 10)
**Screen size**: 360x800
**[Open #864 in Usersnap](https://app.usersnap.com/l/feedback/ec9f96f7-1d32-4b02-8d16-74bd24fcb655?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Duplicated ticket.
