### ISSUE TITLE
[FEATURE REQUEST] تحفيز المبتدئين للربح من تنزيل الفيديوهات 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6244]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Which feature are you missing?: تحفيز المبتدئين للربح من تنزيل الفيديوهات 
- What problem would that solve for you?: الربح ولو جزء بسيط من عمله الفرح
- Share your Email or Discord so we can get in touch: mahmoud9276091@gmail.com
- Your Gleev channel ID or Title: j4SKVgJjNwChtwwJBtEZr7iLXrSuB8b9SyLXWUAJ3GztG5fZA

**Browser**: Chrome 124 (Android 10)
**Screen size**: 393x895
**[Open #218 in Usersnap](https://app.usersnap.com/l/feedback/64bc0f39-54bd-417d-a852-5985f4db2b29?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator and ask for more information for this request.
