### ISSUE TITLE
[USERSNAP] problem 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6245]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: problem 
- Expected Result: very good 
- Your Channel and Account Details: content 
- Email or Discord handle for feedback: nahidaus77@email.con

**Browser**: Chrome 123 (Android 10)
**Screen size**: 393x851
**[Open #865 in Usersnap](https://app.usersnap.com/l/feedback/ab3fc1c1-c179-49f2-92f3-76b9adcebe7c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that the email address associate is not found. Ask the creator to check if they use the same email address for registration Instruct to sign-up and provide the document for creator reference.
