### ISSUE TITLE
Reminder to turn off revenue share

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6246]
Seems on has to actively turn off revenue share once completed for trading to be possible again, this is really easy for peopel to forget as creators, I have seen many cases. So lets help creators by sending regular email notificaitons if their token is stuck in this mode of having the rev share completed but not finalized. These notifications should be sent perpetually, not just once.

The email itself could have like a little gif embed or something showing what they should do.

**Comment by WRadoslaw** [comment]
I'm pretty sure that the creator will get an email that the revenue has ended as he is a holder.

**Comment by WRadoslaw** [comment]
I just checked and it is possible to make amm trade after revenue share ended, but wasn't yet finalized by the creator. 

It should resolve UX issue for both holders and creators.

**Comment by dmtrjsg** [comment]
I guess closing on the basis of latest comment from Radek. @bedeho shout if you disagree.
