### ISSUE TITLE
[USERSNAP] I can't sign up

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6250]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: I can&#39;t sign up
- Expected Result: My email and password is right, it should log in.
- Your Channel and Account Details: m.nehal.javaid@gmail.com
- Email or Discord handle for feedback: bilalkhan2323545@gmail.com

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1366x768
**[Open #866 in Usersnap](https://app.usersnap.com/l/feedback/3f31adb5-7d62-4dcd-8b66-f3a660eeb433?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
