### ISSUE TITLE
[USERSNAP] Why rewards decrease 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6254]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Why rewards decrease 
- Expected Result: Not good
- Your Channel and Account Details: Rewards of channel why decrease 
- Email or Discord handle for feedback: socialnext1755@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 360x820
**[Open #868 in Usersnap](https://app.usersnap.com/l/feedback/f96d0e79-481d-470f-a9fc-9be81c983626?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator in regards to revision of creator reward but let know about the exciting improvements coming soon.
