### ISSUE TITLE
[USERSNAP] please announced date you increases creators rewards

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6255]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: please announced date you increases creators rewards
- Expected Result: good
- Your Channel and Account Details: please increases rewards 
- Email or Discord handle for feedback: socialnext1755@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1366x768
**[Open #869 in Usersnap](https://app.usersnap.com/l/feedback/578987d4-c8c4-4f90-bdad-f6f9903ee4ee?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that creator rewards will be announce soon.
