### ISSUE TITLE
[USERSNAP] I can't sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6256]
**Taken at**: https://gleev.xyz/signin
**Fields**:
- Houston, we have a problem.: I can&#39;t sign in
- Expected Result: I expected to be able to sign in after creating membership account 
- Your Channel and Account Details: Amor, amor_088. estylo088@gmail.com
- Email or Discord handle for feedback: estylo088@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 360x820
**[Open #870 in Usersnap](https://app.usersnap.com/l/feedback/a916955c-3355-43d3-94f2-273767882a2f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
