### ISSUE TITLE
Idea: Add search bar to search CRTs

### ISSUE THREAD

**Issue by jen4ph** [Joystream/atlas#6258]
Navigating the marketplace to find a specific creator token can be a cumbersome and inefficient process, especially if the token is not featured or listed among the top-earning channels. The current design requires users to browse through numerous pages, which is not only time-consuming but also hinders discoverability.
In the absence of a direct link to the desired creator token, users face a significant challenge in locating it within the vast and growing marketplace for CRTs.

**Suggestion**:
To enhance the user experience and discoverability of creator tokens within the marketplace, I propose to add `Search Bar` as UI/UX improvements. 
<img width="1436" alt="Screenshot 2024-05-06 at 11 31 28 PM" src="https://github.com/Joystream/atlas/assets/96877192/4474e708-1e56-4cc9-b357-6cce331e8fdb">

Another that came to my mind is the `Sort Functionality` will enable users to sort the list of creator tokens based on various criteria such as **_trading volume_**, **_alphabetical order_**, **_market capitalization_**, **_date created_** etc

**Comment by dmtrjsg** [comment]
Search input should also work with channel title and member handle, not just token ticker.
