### ISSUE TITLE
[USERSNAP] cannot receive my money

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6260]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: cannot receive my money
- Expected Result: Please help me i cannotreceive my money 
- Your Channel and Account Details: Email: gamesforlife998@gmail.com
Channel: Arqade Plays
- Email or Discord handle for feedback: gamesforlife998@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1366x768
**[Open #871 in Usersnap](https://app.usersnap.com/l/feedback/b78cfa1e-2df4-4b89-9c1f-a58c513430f6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Issue not well specified. Acknowledge creator concern and ask further information.
