### ISSUE TITLE
[USERSNAP] when I want to signup, YPP ask me you are already Sign in but when I want to sign in, a notification showed that you are not a member of YPP. 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6262]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: when I want to signup, YPP ask me you are already Sign in but when I want to sign in, a notification showed that you are not a member of YPP. 
- Expected Result: I do not know
- Your Channel and Account Details: NasirGamer-lm9gv, neutral myth toward panda ride mesh camp decrease federal clown fossil year, n86754849@gmail.com
- Email or Discord handle for feedback: n86754849@gmail.com

**Browser**: Edge (Chromium) 122 (Windows 10)
**Screen size**: 1366x768
**[Open #872 in Usersnap](https://app.usersnap.com/l/feedback/67b7a4d3-d56e-4a87-882b-dc8e8bb9bc5f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
