### ISSUE TITLE
[USERSNAP] Can't create additional channel

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6264]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Can&#39;t create additional channel
- Expected Result: Should create additional channel
- Your Channel and Account Details: jaysonmott@gmail.com
- Email or Discord handle for feedback: jaysonmott@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 412x892
**[Open #874 in Usersnap](https://app.usersnap.com/l/feedback/bfb1ec60-55f7-47d4-806e-11a48721ba98?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Reached out to the creator to send a screenshot and more details error message they are getting.
