### ISSUE TITLE
[USERSNAP] I didn't get my reward 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6265]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: I didn&#39;t get my reward 
- Expected Result: To get it in 2024 /7May 
- Your Channel and Account Details: @an_idea2008
qawsedrftghh65@gmail.com
- Email or Discord handle for feedback: qawsedrftghh65@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 360x816
**[Open #875 in Usersnap](https://app.usersnap.com/l/feedback/1f9bfae2-054e-4947-b136-9c42b2ae6185?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator update on their rewards. The rewards were settled 05/08/24 and sent the instruction to check the payment.
