### ISSUE TITLE
[USERSNAP] Se Pone La Pantalla Completamente Blanca Cuando Subo Algo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6266]
**Taken at**: https://gleev.xyz/studio/video-workspace
**Fields**:
- Houston, we have a problem.: Se Pone La Pantalla Completamente Blanca Cuando Subo Algo
- Expected Result: Que Funcione Y Que Carge El Video Bien
- Your Channel and Account Details: j4TdXLWSDxDfeDST9if6AyTDGypoKW5VpuY1vQRubF1Cf7CwA
- Email or Discord handle for feedback: emitotonepiece@gmail.com

**Browser**: Chrome 123 (ChromeOS)
**Screen size**: 1536x864
**[Open #876 in Usersnap](https://app.usersnap.com/l/feedback/c565e50c-834d-4811-b9d1-ee4e7adedf56?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Hi @kdembler @dmtrjsg Is there any reason why some having a trouble uploading videos now?

**Comment by kdembler** [comment]
@rchrdcstro from what I know this should be resolved already
