### ISSUE TITLE
[USERSNAP] No cargar la membresía

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6267]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: No cargar la membresía
- Expected Result: Ggggg
- Your Channel and Account Details: :(

**Browser**: Chrome 124 (Android 10)
**Screen size**: 412x915
**[Open #877 in Usersnap](https://app.usersnap.com/l/feedback/9fc5292d-0835-4fad-9855-e4fac67a72c2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed the ticked as no details to get back to the creator/inquirer.
