### ISSUE TITLE
[USERSNAP] Suspended

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6273]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Suspended
- Expected Result: Hello, I added my YouTube channel and after checking it was suspended and the reason was stated as taking advantage of the program conditions, my purpose is to add videos and of course to make money after adding videos, people who already join your platform are already joining for these reasons. Can you please unsuspend and approve my account?
- Your Channel and Account Details: debuateam@gmail.com
- Email or Discord handle for feedback: debuateam@gmail.com

**Browser**: Safari 15 (iOS)
**Screen size**: 375x667
**[Open #879 in Usersnap](https://app.usersnap.com/l/feedback/a35d9cf8-cf45-4150-84e6-b6a3bbadecd7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
