### ISSUE TITLE
[USERSNAP] Suspenso

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6274]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Suspenso
- Expected Result: Meu trabalho é original,mas foi suspenso. O que houve?
- Your Channel and Account Details: Shanoa

**Browser**: Chrome 124 (Android 10)
**Screen size**: 320x712
**[Open #880 in Usersnap](https://app.usersnap.com/l/feedback/9eb59314-65b5-4625-8f0a-6b46ea4d1a87?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Found the channel and here is the channel id: 62257 -  Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
