### ISSUE TITLE
[USERSNAP] hello I can't create my account

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6275]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: hello I can&#39;t create my account
- Expected Result: hello I can&#39;t create my account
- Your Channel and Account Details: https://www.youtube.com/channel/UC3IePTSLHf0uMcccuRaPMqg

EMAIL : yuricriptogamer@gmail.com
- Email or Discord handle for feedback: yuricriptogamer@gmail.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1366x768
**[Open #881 in Usersnap](https://app.usersnap.com/l/feedback/ef698ea4-f3ff-4c1b-82c9-27fc3d54a629?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
