### ISSUE TITLE
[USERSNAP] Trying to sign up but it says I already have an account. When I try to log in, it says I do not have an account. 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6277]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Trying to sign up but it says I already have an account. When I try to log in, it says I do not have an account. 
- Expected Result: I expected to log in.
- Your Channel and Account Details: https://www.youtube.com/channel/UCrF2_2N_B8NWf-I5bIXcSiQ
Contact@jamaleads.com
- Email or Discord handle for feedback: contact@jamaleads.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1536x864
**[Open #882 in Usersnap](https://app.usersnap.com/l/feedback/255a6caa-928e-43e9-8aac-e86e52b34a53?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
