### ISSUE TITLE
[USERSNAP] Llevo 10 minutos y no carga 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6278]
**Taken at**: https://gleev.xyz/ypp?referrerId=61889
**Fields**:
- Houston, we have a problem.: Llevo 10 minutos y no carga 
- Expected Result: No carga
- Your Channel and Account Details: No carga 
- Email or Discord handle for feedback: bussidb90@gmail.com

**Browser**: Chrome 115 (Android 13)
**Screen size**: 385x854
**[Open #884 in Usersnap](https://app.usersnap.com/l/feedback/8d0f045d-be74-4378-aaf8-162b88132e71?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
