### ISSUE TITLE
[USERSNAP] Cannot sign up or sign in

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6279]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: Cannot sign up or sign in
- Expected Result: To create and account and log in
- Your Channel and Account Details: https://www.youtube.com/channel/UCrF2_2N_B8NWf-I5bIXcSiQ 
- Email or Discord handle for feedback: contact@jamaleads.com

**Browser**: Chrome 124 (Windows 10)
**Screen size**: 1536x864
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/d5cbb26a-1aef-493d-b0d5-f5dbe2e63993_screen_recording_5c28b909-a614-459a-a960-b3b4864d8a6b.webm?etag=67445af58c6b537d4143a59038f81a21)**
**[Open #883 in Usersnap](https://app.usersnap.com/l/feedback/4c8c146d-2674-420d-96ca-67a5f0b99472?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Taken: Inform the creator that we will remove their email from our records and suggest trying again after 24-48 hours.
