### ISSUE TITLE
CRTs: "Your Share" from revenue share shows 0 when it shouldn't be

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6281]
# Problem
![image](https://github.com/Joystream/atlas/assets/50830161/0be0ee84-3e1f-4e02-bcb6-13aca26ae614)

* I own CRTs and the "Your share" column for each of them shows 0, but when I click "stake your tokens" it turns out that there is actually some reward available from the revenue share. 
* The column appears to update _after_ the revenue share has been claimed by the user

# Solution
* "Your share" should show the amount available in $JOY from the revenue split _or_
* There should be a separate column showing the available revenue share in $JOY

**Comment by ikprk** [comment]
To be included in next release https://github.com/Joystream/atlas/pull/6331
