### ISSUE TITLE
[USERSNAP] Не могу востановить пароль, потерял слово которые востановить пароль

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6290]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Не могу востановить пароль, потерял слово которые востановить пароль
- Expected Result: Пока не знаю
- Your Channel and Account Details: jakuma1993@gmail.com
- Email or Discord handle for feedback: jakuma1993@gmail.com

**Browser**: Chrome 124 (Android 10)
**Screen size**: 393x873
**[Open #885 in Usersnap](https://app.usersnap.com/l/feedback/aa79fe03-83f1-470e-970c-de82e7db8b6e?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
