### ISSUE TITLE
CRTs: Disallow revenue shares beyond 30 days

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6297]
# Problem
https://gleev.xyz/channel/26072?tab=Token 
This channel has done a revenue share of a year

# Solution
Either disallow revenue shares this long, or place some sort of extreme warning.

EDIT: come to think of it, I can think of no practical use for a revenue share that is a year long. It did cross my mind that maybe the creator wants to "exit" the platform (or more likely wants to retire from making videos) and as a courtesy opens one final revenue share, but then the holders can't sell their CRT holdings so it is kind of pointless... Maybe for a giant channel will tens of thousands of holders this would be a "fair" way to close out a channel with a huge amount of pending revenue, but that seems like an edge case and doesn't really exist right now--even in a case like that 90 days seems more than fair for "closing down" a CRT in a fair way.

**Comment by bedeho** [comment]
Brutal. I think we should just cap at  7 days or something for now too be honest..

**Comment by ikprk** [comment]
> Brutal. I think we should just cap at 7 days or something for now too be honest..

Maximum duration of 14 days was introduced
