### ISSUE TITLE
Idea: Add video counter and NFT counter to channel page

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6298]
# Problem
I am a keen CRT investor, and I am constantly looking through CRTs. I see some with zero revenue and click their profile to find out more and get this:
![image](https://github.com/Joystream/atlas/assets/50830161/c08427eb-249b-479b-b38f-7a154ed1ae18)

The problem is that at face value it appears the channel has no content--as the channel only joined today it is unlikely it would have received any rewards so far, so it -could- have an interesting value proposition for an early investor.

In reality the channel already has 6 videos and 0 NFTs but this information isn't surfaced in Atlas without clicking multiple tabs.

# Solution
Change the highlighted box in the screenshot to read something like:
`Videos (83)` / `NFTs (16)` / `Token (name_of_crt)` / `Information`

* `name_of_crt` I think is a great thing to add because it immediately tells a user whether the channel has a CRT or not

**Comment by bedeho** [comment]
Very good idea

**Comment by ikprk** [comment]
> * `name_of_crt` I think is a great thing to add because it immediately tells a user whether the channel has a CRT or not

Token tab won't be shown if a channel hasn't minted CRT

**Comment by msmadeline** [comment]
Hey, I've updated the design in figma
➡ https://www.figma.com/design/POw4j95jszfIP5bGfas2IC/Channel?node-id=1901-79747&t=2rewP8OlFE15XOuk-4

**Comment by mochet** [comment]
> > * `name_of_crt` I think is a great thing to add because it immediately tells a user whether the channel has a CRT or not
> 
> Token tab won't be shown if a channel hasn't minted CRT

I still suggest to show the CRT name because CRTs are a new/novel feature that are not standard on video platforms so seeing `$FLAVR` will make it stand out to users.
