### ISSUE TITLE
[USERSNAP] Не получается

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6301]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Не получается
- Expected Result: Проблема
- Your Channel and Account Details: Проблема

**Browser**: Chrome 125 (Android 10)
**Screen size**: 412x892
**[Open #886 in Usersnap](https://app.usersnap.com/l/feedback/4e5b814b-3052-4603-95aa-f9da8e4fb00b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this ticket as there is no way to get back with the creator.
