### ISSUE TITLE
[USERSNAP] delete my account Matthezz MTZ

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6304]
**Taken at**: https://gleev.xyz/channel/62389?tab=Videos
**Fields**:
- Houston, we have a problem.: delete my account Matthezz MTZ
- Expected Result: delete my account Matthezz MTZ
- Your Channel and Account Details: https://gleev.xyz/channel/62389?tab=Videos

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1360x768
**[Open #887 in Usersnap](https://app.usersnap.com/l/feedback/c1ed3da3-e9e5-4ec8-813b-3502134c4334?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed creator in regards to program opt-out option.
