### ISSUE TITLE
[USERSNAP] мне не начислят деньги за мои видео 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6305]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: мне не начислят деньги за мои видео 
- Expected Result: мне уже 6 месяцев нечего не платят почему ?
- Your Channel and Account Details: sasha1937286458@gmail.com
https://www.youtube.com/channel/UCgulwyHieRpATZWlE82Palg
https://www.youtube.com/channel/UCRcXYaCH-qe629N9Bsq9faA

два моих канала к Вам подключил
- Email or Discord handle for feedback: sasha1937286458@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/13dce7f4-65ec-4200-9034-897c6c607fbd-annotated_8fbd8e7e-cadf-414e-8a6c-8db0bff0a914.png?etag=c5ad251890b52ccc0ecff39797bd037f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/13dce7f4-65ec-4200-9034-897c6c607fbd-annotated_8fbd8e7e-cadf-414e-8a6c-8db0bff0a914.png?etag=c5ad251890b52ccc0ecff39797bd037f)*

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1280x800
**Browser size**: 1600x798
**[Open #888 in Usersnap](https://app.usersnap.com/l/feedback/49b1d91d-5832-4c8a-925f-107e55341f5c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that channel tier is bronze and sync video is solely available to silver and above.
