### ISSUE TITLE
[USERSNAP] мне не начислят деньги за мои видео 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6306]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: мне не начислят деньги за мои видео 
- Expected Result: Почему мне не начисляют деньги за видео ?
- Your Channel and Account Details: https://www.youtube.com/channel/UCRcXYaCH-qe629N9Bsq9faA
billylwells1@gmail.com
- Email or Discord handle for feedback: billylwells1@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/07f4473d-0c8d-44b0-a81b-2b7326050196-annotated_53a54e26-f090-4edf-8a38-7aa4818c1c47.png?etag=6defcae7af3b95fbef640faebcc0c400)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/07f4473d-0c8d-44b0-a81b-2b7326050196-annotated_53a54e26-f090-4edf-8a38-7aa4818c1c47.png?etag=6defcae7af3b95fbef640faebcc0c400)*

**Browser**: Chrome 123 (Windows 10)
**Screen size**: 1280x800
**Browser size**: 1600x798
**[Open #889 in Usersnap](https://app.usersnap.com/l/feedback/8390d1fa-c359-4f83-b346-dd6618508648?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that channel tier is bronze and sync video is solely available to silver and above.
