### ISSUE TITLE
Emails notifs: not recieving notification emails / can't change email address

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6313]
# Problem
I signed up to gleev via a wallet and put in an email address that didn't exist (just to get through the signup flow). Presumably this meant the emails bounced and emails stopped getting sent.
There is no way to change the email address currently.

# Solution
I guess being able to change the email address would be a "nice to have" but may cost a lot of resources to do this. Otherwise just need some help to reset my email account.

(can be contacted on discord `tomato_js` for more info)

**Comment by dmtrjsg** [comment]
@mochet sadly there's no way to update it rn. We will introduce changing email at some point but its costly so was left out of scope for a reason :/
