### ISSUE TITLE
Idea: Split NFTs an CRTs

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#6336]
I think having these under one tab is getting quite annoying, they look so similar, I often have to go up to tabs to check which one Im actually on. Lets split them up and put each one in left hand menu with titles "Tokens" and "NFTs", and use these icons from the tab:

![Screenshot 2024-05-26 at 19 22 09](https://github.com/Joystream/atlas/assets/437292/6945014a-b1eb-4225-bdf6-74004ea79dff)

![Screenshot 2024-05-26 at 19 22 18](https://github.com/Joystream/atlas/assets/437292/09b5b481-849e-4d4d-9ab1-c3995d24914f)

On mobile, if there is not enough space, lets hide "referrals".

**Comment by dmtrjsg** [comment]
Yes! Was also thinking about it recently 👍 Prioritising up to be shipped with UX improvements for CRTs

**Comment by msmadeline** [comment]
@bedeho Just to be sure - does that also mean that I have to delete the "Marketplace" side nav item? and delete the tabs?(the ones on the marketplace page)

 If that is the case then the user will go directly to the tokens page after clicking on the "tokens" side nav, and same with the NFTs. Please let me know If my assumptions are right cause this will require some updates in designs

**Comment by bedeho** [comment]
> Just to be sure - does that also mean that I have to delete the "Marketplace" side nav item? and delete the tabs?(the ones on the marketplace page)

Correct :)

**Comment by msmadeline** [comment]
Hey @bedeho I updated the navigation component, then updated the designs of the pages and added 2 user stories as well. 

➡ Updated designs: 
https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=401-42773&t=7TrEzMXSRKmBK3vP-4

➡ New user stories: 
https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1367-99787&t=7TrEzMXSRKmBK3vP-4
https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1367-124036&t=7TrEzMXSRKmBK3vP-4

**Comment by bedeho** [comment]
Great, but ordering should be

1. home
2. Tokens
3. NFTs
4. Earn
5. Referrals
