### ISSUE TITLE
[USERSNAP] Cannot Sign In

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6341]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Cannot Sign In
- Expected Result: Waiting for extension ... (remains forever)
Nothing happens during attempt to log in, tried 2 wallets (polkadot js and talisman) and Tried 2 devices (OSX &amp; WIN11)
- Your Channel and Account Details: leet_joy
- Email or Discord handle for feedback: joystream

**Browser**: Firefox 126 (macOS Catalina)
**Screen size**: 1881x1218
**[Open #891 in Usersnap](https://app.usersnap.com/l/feedback/415dbee8-691b-47ca-b6c7-7b9450217c19?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment]
I tried on my own devices and wasn't able to replicate this issue.
