### ISSUE TITLE
Surface CRT activity

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6344]
Inspiration: [dextools.io](https://www.dextools.io/)

1. Thinking of like a trades ribbon without timestamps: Only Token + Trade + Member handle who purchased  (last 30)

[Like this](https://www.dextools.io/app/en/ether/pair-explorer/0x0c3fdf9c70835f9be9db9585ecb6a1ee3f20a6c7?t=1716967197051)
<img width="1250" alt="Screenshot 2024-05-29 at 11 20 01" src="https://github.com/Joystream/atlas/assets/93924525/9947015e-f89b-43c4-b682-7c28376d5fbf">

2. Hot tokens (based on page hits)
<img width="435" alt="Screenshot 2024-05-29 at 11 21 17" src="https://github.com/Joystream/atlas/assets/93924525/4198adc9-ccb0-4f52-a45a-6f88d25b2644">

**Comment by msmadeline** [comment]
@dmtrjsg Hey, Just finished designing the trades ribbon and hot tokens section. I did desktop and mobile view. Also I modyfied the top selling channels section on the mobile so that it's a better UX. 

➡ figma page: https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1385-69557&t=hRUZWI5c7pkd300r-4

**Comment by dmtrjsg** [comment]
Nice work!  Here's what I think we would want from the second iteration in terms of page and widgets structure. 

1	Ribbon with trades on top: Token name; tokens purchased / sold; member handle who purchased 
2	Hot pairs: #rank, icon, token name, price, % increase in price last 24 hrs. Can be up or down. Maximum vertical is 5 tokens, Scrollable horisontaly to total of 10.
3	Weekly Gainers / Weekly Loosers
#rank, icon, token name, price, % increase in price last 7 days. Maximum vertical is 5 tokens, Scrollable horisontaly to total of 10.
4	Featured tokens
5	Top selling channels
6	All tokens

**Comment by msmadeline** [comment]
@dmtrjsg Hey! I implemented the feedback and did the desktop view. Let me know what you think.

📱Mobile design: https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1396-154157&t=Hsn11CMPLzQFAxRe-4

💻Desktop design: https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1391-138536&t=Hsn11CMPLzQFAxRe-4

CC. @bedeho

**Comment by bedeho** [comment]
@dmtrjsg Some opinions

1. I think price is useless, it has no information, just a unit bias. Price makes sense if you are tracking the same asset over time, like if you already know where it has been, but for a _discovery_ scneario, where you are meeting new tokens, it holds 0 information.
2. Why is liquidity no included, or liquidity dynamics, like up x% in liquidty, that is a real metric which people care about.
3. Similar with volume, more susceptible to being gamed, but still. 
4. "Top earning" are basically not useful imho, its just a static cast that never ever changes, I have tuned it out on the current other pages long ago, that's my experience.

**Comment by dmtrjsg** [comment]
@bedeho thank you for your feedback, super valuable!

1. On liquidity: 
- I believe we want to display the metric which is more volatile based on the humble sales / tx volume. Imo this will be the price, hence the rationale. 
- Liquidity will be added to the All tokens table and users can sort/ filter based on that parameter
2. On Volume and Top Earning channels
- Agreed, @msmadeline let's replace Top Selling Channels widget with Top Traded Tokens by Volume

**Comment by bedeho** [comment]
> I believe we want to display the metric which is more volatile 

- Whether liquidity or price is more volatile depends on slope of curve, in my mind I dont know which is more volatile, did you actually check?
- This is not an argument for showing price _levels_, and that is what you are showing in each row now. If you want to show price changes, have an explicit volumn for that, with a proper label, and then replace price _level_ column which is doing nothing. Liquidity _levels_ or change are both better than this.

**Comment by dmtrjsg** [comment]
@msmadeline let's prepare the version without explicit price levels, only price change in % and liquidity change in % for daily gainers and losers.

**Comment by dmtrjsg** [comment]
@bedeho spoke with Ignazio, we concluded that Price is better optics compared to JOY liquidity change for the small volume of transactions we are having now.

**Comment by msmadeline** [comment]
@dmtrjsg I did RWD for the new tokens page. let me know wdyt

➡ https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1498-239456&t=zwSFeJq4U0SqYqpp-4

**Comment by msmadeline** [comment]
@dmtrjsg I updated the user stories foe the new layout of the tokens page 

➡https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1518-281941&t=zwSFeJq4U0SqYqpp-4
➡https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1519-286848&t=zwSFeJq4U0SqYqpp-4
➡https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1519-292117&t=zwSFeJq4U0SqYqpp-4
➡https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=1519-297045&t=zwSFeJq4U0SqYqpp-4
