### ISSUE TITLE
[USERSNAP] senha

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6348]
**Taken at**: https://gleev.xyz/ypp
**Fields**:
- Houston, we have a problem.: senha
- Expected Result: não estou conseguindo criar uma senha
- Your Channel and Account Details: não estou conseguindo criar uma senha 

**Browser**: Chrome 125 (Android 10)
**Screen size**: 320x712
**[Open #892 in Usersnap](https://app.usersnap.com/l/feedback/fbc2be07-5ceb-4a81-a33f-7ea84bf2325d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Closed this ticket as there is no option to get back.
