### ISSUE TITLE
Remove Large Preview of CRT trailer 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6350]
This carousel needs to go from CRT marketplace:
<img width="1110" alt="Screenshot 2024-05-29 at 11 21 51" src="https://github.com/Joystream/atlas/assets/93924525/2f7427ae-5748-4f1a-a9e3-04041e0d1dd3">

**Comment by mochet** [comment]
I made some suggestions for the NFT page that might be worthwhile to look at for the CRT page also, but there may already be issues for some of those: https://github.com/Joystream/atlas/issues/6377

**Comment by msmadeline** [comment]
@dmtrjsg Hey, that's done ✅
https://www.figma.com/design/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?node-id=401-19210&t=hRUZWI5c7pkd300r-4
