### ISSUE TITLE
[USERSNAP] problemas con retiro

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6352]
**Taken at**: https://gleev.xyz/studio/payments
**Fields**:
- Houston, we have a problem.: problemas con retiro
- Expected Result: hice un retiro de 247.72 joy y no fueron enviados a la billetera registrado en el bloque 7593730 y aun no se han devuelto los fondos al apartado principal
- Your Channel and Account Details: kreutertovar696@gmail.com
- Email or Discord handle for feedback: kreutertovar696@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/76a5a34d-56da-4ab5-980a-b3ce55cfc69f-annotated_8ac2e7c2-8cc1-4765-afdb-5129307ad3ed.png?etag=650c7f6468f0539778e4274224e99cb3)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/76a5a34d-56da-4ab5-980a-b3ce55cfc69f-annotated_8ac2e7c2-8cc1-4765-afdb-5129307ad3ed.png?etag=650c7f6468f0539778e4274224e99cb3)*

**Browser**: Opera 110 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1866x919
**[Open #893 in Usersnap](https://app.usersnap.com/l/feedback/e4a51504-d340-49f8-8886-c2bbe729afdc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that all transactions is successful upon checking and recommend to contact its exchange support.
