### ISSUE TITLE
Update CRT table columns

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6354]
Add columns:
-- % change in price to tokens table over 7 days
- % of liquidity change over 7 days
- Change date created to X days / months/ years ago)

So we would need space for it so
 - remove the status name from the column - only keep icon. 
- remove the "Holders" from the holders column - only keep the number. 

Order of columns: 
Token name
Date Created
24 % change in price
Price
7d % change in liquidity
Liquidity
7d Trading Volume
Status
Market Cap
Channel Revenue
Holders Count

**Comment by msmadeline** [comment]
@dmtrjsg What about the total rev. and status column? Where am I supposed to put them in terms of the order? Do we even keep the total rev. one?

**Comment by dmtrjsg** [comment]
Hi @msmadeline, thank you for your question. I have now updated the columns composition and order.
