### ISSUE TITLE
[USERSNAP] Unable to login

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6356]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Unable to login
- Expected Result: I´m trying to login . I´ve put the correct password and email but it dont login
- Your Channel and Account Details: @veronicareginasol
- Email or Discord handle for feedback: veron.cuadros@gmail.com

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1360x768
**[Open #894 in Usersnap](https://app.usersnap.com/l/feedback/e1f57d07-a844-4929-b697-4149bbbda863?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator that their membership has not been established and provide them with a link to access the document for finalizing the sign-up procedure.
Document link: https://joystream.notion.site/YouTube-Partner-Program-Outline-d492c2eb88ff4ace955b5f2902ec21fb#2fc79ce6c2d24b7b95138b67d093028f
