### ISSUE TITLE
[USERSNAP] Meus vídeos não estão sincronizando

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6381]
**Taken at**: https://gleev.xyz/studio/videos
**Fields**:
- Houston, we have a problem.: Meus vídeos não estão sincronizando
- Expected Result: estou esperando a sincronia do youtube, já tem dois vídeos que postei lá que ainda não está aqui
- Your Channel and Account Details: Zombies In The Lawn
https://gleev.xyz/channel/62462?tab=Videos
- Email or Discord handle for feedback: rameslamonie@gmail.com

**Browser**: Edge (Chromium) 125 (Windows 10)
**Screen size**: 1536x864
**[Open #895 in Usersnap](https://app.usersnap.com/l/feedback/b5f00c90-7a75-475c-87bb-da203aea8d63?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that syncing the video might take a while and that he is under the bronze channel. Additionally, informed him that regardless of the syncing process, only silver and above are eligible for the reward.
