### ISSUE TITLE
[USERSNAP] Remove my old channel on gleev

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6382]
**Taken at**: https://gleev.xyz/channel/62389?tab=Videos
**Fields**:
- Houston, we have a problem.: Remove my old channel on gleev
- Expected Result: I literally lost access to this channel and I wanted it deleted on gleev for privacy reasons
- Your Channel and Account Details: https://gleev.xyz/channel/62389?tab=Videos
- Email or Discord handle for feedback: matheusdesouza2046@gmail.com

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1360x768
**[Open #896 in Usersnap](https://app.usersnap.com/l/feedback/5c9ce4e5-26db-4f4b-99b1-57a7d7fb9133?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that we don't offer delete option but we have opt-out. Sent instructions via email.
