### ISSUE TITLE
[USERSNAP] no sync from youtube

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6383]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: no sync from youtube
- Expected Result: I would like that my youtube videos syncronize with gleev
- Your Channel and Account Details: Zombies In The Lawn
https://gleev.xyz/channel/62462?tab=Videos
- Email or Discord handle for feedback: rameslamonie@gmail.com

**Browser**: Edge (Chromium) 125 (Windows 10)
**Screen size**: 1536x864
**[Open #897 in Usersnap](https://app.usersnap.com/l/feedback/88e8cc9c-6918-44b3-a7ab-5627ea386983?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Informed the creator that sync process synchronizing videos can be a time-consuming process. Ask for patience.
