### ISSUE TITLE
[USERSNAP] estou com problema para acessar meu canal -futebol sem igual

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6385]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: estou com problema para acessar meu canal -futebol sem igual
- Expected Result: eu espero que eu digite a minha senha e email e consiga logar minha conta
- Your Channel and Account Details: desculpe não me lembro o id, mais o nome do canal é futebol sem igual-o email é dasilvakiki357@gmail.com, obrigada

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1600x900
**[Open #898 in Usersnap](https://app.usersnap.com/l/feedback/976087e2-9bdd-444b-9b99-c0f75aad5e80?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
