### ISSUE TITLE
[USERSNAP] No me deja entrar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6386]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: No me deja entrar
- Expected Result: Me deje entrar
- Your Channel and Account Details: L.gamer
- Email or Discord handle for feedback: Lukytas.gamer2007@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4a8ca59e-5bfd-485a-b1e7-dd4cf2feb83a-annotated_88e8a5f6-6df9-416d-91e3-45d3e842d05a.png?etag=5be1c8da21c524f1c04386191f3c4751)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4a8ca59e-5bfd-485a-b1e7-dd4cf2feb83a-annotated_88e8a5f6-6df9-416d-91e3-45d3e842d05a.png?etag=5be1c8da21c524f1c04386191f3c4751)*

**Browser**: Chrome 102 (Android 7.0)
**Screen size**: 360x640
**Browser size**: 386x618
**[Open #899 in Usersnap](https://app.usersnap.com/l/feedback/416d714e-efc5-4381-9126-028be1bc932c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Duplicated ticket.
