### ISSUE TITLE
[USERSNAP] mistake passw

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6390]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: mistake passw
- Expected Result: i can&#39;t login because passw is mistake..i don&#39;t know why??
- Your Channel and Account Details: my channel is Tronci Anastasia (anyboutique)
- Email or Discord handle for feedback: any.tronci84@gmail.com

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1924x931
**[Open #900 in Usersnap](https://app.usersnap.com/l/feedback/c5423378-e82b-42aa-a0cb-c7b632487edb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
