### ISSUE TITLE
[USERSNAP] estou com problema para acessar meu canal -futebol sem igual

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6391]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: estou com problema para acessar meu canal -futebol sem igual
- Expected Result: porfavor eu gostaria de digitar a minha senha e consiguisse acessar minha conta
- Your Channel and Account Details: dasilvakikiu357@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/43fcb7c4-40ed-4002-adb5-44081c93d84c-annotated_73b07d05-2cd1-4fa3-984c-85c33ae4b255.png?etag=9f139a723956f2269979f515aa354046)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/43fcb7c4-40ed-4002-adb5-44081c93d84c-annotated_73b07d05-2cd1-4fa3-984c-85c33ae4b255.png?etag=9f139a723956f2269979f515aa354046)*

**Browser**: Chrome 125 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1455x703
**[Open #901 in Usersnap](https://app.usersnap.com/l/feedback/a796ae35-f1c0-455d-aa60-5a2ca639ddb2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
