### ISSUE TITLE
[USERSNAP] При попытке восстановления пишет мы столкнулись с проблемой 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6395]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: При попытке восстановления пишет мы столкнулись с проблемой 
- Expected Result: Что я смогу восстановить аккаунт 
- Your Channel and Account Details: andrewegorov@gmail.com это почта пороль не помню семя Your welcome Your welcome Your welcome Your welcome 
- Email or Discord handle for feedback: andrewegorov@gmail.com

**Browser**: Chrome 126 (Android 10)
**Screen size**: 385x860
**[Open #903 in Usersnap](https://app.usersnap.com/l/feedback/eaf2dc82-d360-4421-9c42-18990a64cf0b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated ticket.
