### ISSUE TITLE
Add Category Filters to Homepage

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6404]
## Context

Aiding discovery of non-crypto content and reducing bounce of non-crypto audience. 

## Scope

1. Add categories as bubbles to the top of homepage. 
2. List: 
- All
- Crypto
- Gaming
- Music
- Entertainment
- Other
3. Display All by default
4. When selected categories, modify Homepage query to only display relevant categories. 
5. Content ranking rules should persist. 
6. Manual curation of videos can stay only on All or Migrate to other categories where relevant if not too difficult. 
7. 🆕 Add analytics events on clicking to bubbles
title = Feed Category Selected
name = Feed Category Selected
Parameter: {categoryName, All}

**Comment by mochet** [comment]
@dmtrjsg I think adding a category/area just for "Gleev exclusive" content should be one of the categories: https://github.com/Joystream/joystream/issues/1824

Though I'm not sure how much this increases the difficulty of your initial issue.

**Comment by dmtrjsg** [comment]
@mochet We don't have enough stock just yet, but as an idea I like it a lot 👍

**Comment by msmadeline** [comment]
@dmtrjsg Hey! I've added categories to the homepage ✅: https://www.figma.com/design/FU2k3hoyr9rnuf5wrWAtiJ/Homepage?node-id=1248-4682&t=9IbAK1E7LO7b3T6X-4

**Comment by dmtrjsg** [comment]
Further actions required before release:
- Remove All and randomise the order of categories shown to users so we can have a conclusive test which ones are more popular.
- Add curation (pinned videos) for all categories that we add.
- Add more categories - up to 8 ( I will come back with the actual list asap).

**Comment by dmtrjsg** [comment]
List of categories to extend for checking the feed 
ℹ️ All other categories would be showing under :other: 
<img width="616" alt="Screenshot 2024-07-10 at 14 51 26" src="https://github.com/Joystream/atlas/assets/93924525/5efa99bd-7137-4b9f-9f91-98e758b11c1e">

⚠️ We may discard a few based on the quality after the QA

**Comment by dmtrjsg** [comment]
@ikprk 

let's remove: 
- education
- business
- lifestyle


as the content in such categories is all over the place and more often than not fits to other categories

tested here: https://atlas-g4b5hety7-joystream.vercel.app/?category=10
using production environment data set

cc @bedeho
