### ISSUE TITLE
[USERSNAP] Olvide mi contraseña y no tengo la semilla

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6407]
**Taken at**: https://gleev.xyz/studio/signin
**Fields**:
- Houston, we have a problem.: Olvide mi contraseña y no tengo la semilla
- Expected Result: Que me ayudaran a iniciar sesion
- Your Channel and Account Details: SomosAmerica   edgarmanolo461@gmail.com
- Email or Discord handle for feedback: edgarmanolo461@gmail.com

**Browser**: Chrome 126 (Android 10)
**Screen size**: 384x832
**[Open #910 in Usersnap](https://app.usersnap.com/l/feedback/3dc4f8a0-52ab-4da6-bcd1-205c66d33a14?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Inform the creator to reset password and send instruction to recover seed phrase if misplaced. Reference: https://joystream.notion.site/How-to-retrieve-your-Seed-Phrase-94df8e1a95d049d38e4214264bc2db76
