### ISSUE TITLE
Viewer channel details design tweaks

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#641]
Capturing some feedback from @bwhm :

1. Channel description not visible anywhere in the channel view
2. Channels without videos should be put at the bottom of the list by default, or just not visible. (Including channels where all vids are hidden or censored)
3. Show creation date (somewhere)

**Comment by KubaMikolajczyk** [comment]
Viewer channel got a redesign : https://www.figma.com/file/TGUpBXgXf9ceMvHbRB5BIx/Joystream-Atlas?node-id=10589%3A297734
