### ISSUE TITLE
[USERSNAP] withdraw error

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6422]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: withdraw error
- Expected Result: i can&#39;t withdraw my funds to my wallet
- Your Channel and Account Details: https://gleev.xyz/channel/62461?tab=Videos
- Email or Discord handle for feedback: rameslamonie@gmail.com

**Browser**: Edge (Chromium) 126 (Windows 10)
**Screen size**: 1536x864
**[Open #911 in Usersnap](https://app.usersnap.com/l/feedback/83e21fcf-c694-4880-ad22-70d8d60c90c6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
