### ISSUE TITLE
[USERSNAP] Passou 48 hours e não fui aceito

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6426]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Passou 48 hours e não fui aceito
- Expected Result: Como podem resolver isso? Resolvam pois já se passaram 48 horas, porfavor resolvam 
- Your Channel and Account Details: A verificação de 48 horas está demorando 
- Email or Discord handle for feedback: josielcb60@gmail.com

**Browser**: Opera 112 (Linux)
**Screen size**: 384x857
**[Open #912 in Usersnap](https://app.usersnap.com/l/feedback/36258444-e276-4aaa-92a8-77dc6fb1ab50?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
