### ISSUE TITLE
Bug: % of price increase on CRT for nintendo

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6429]
I see that the one that went up 14k % has circa 2.6% of tokens purchased by non holders
while the one that went up 590% has circa 13% of purchases. 

Tokens: 
https://gleev.xyz/channel/62461?tab=Token
https://gleev.xyz/channel/62730?tab=Token

<img width="1336" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUVFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a95880a1742f3686709bfa8d3210f732cc965e10/Screenshot%202024-07-24%20at%2013.39.50.png" alt="Screenshot 2024-07-24 at 13.39.50.png" />

<img width="726" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1FQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--586d84d7b600f86a04306b71489501b596b16eaa/Screenshot%202024-07-24%20at%2013.39.39.png" alt="Screenshot 2024-07-24 at 13.39.39.png" />

**Comment by 0x2bc** [comment]
liquidiy drop by 100% must be bug as well
![image](https://github.com/user-attachments/assets/46c3fff8-8365-4fbb-9696-efa529374b11)

**Comment by ikprk** [comment]
## NMG

There seems to be no problem with a query (at least I don't see one). At the time of query execution `current block - 30 days = 8086564` let's call it block `X`, this is important to understand which transaction is being picked. 

1. Oldest transaction - first transaction right before block `X` is the one with id `7c` with price `1184026286 JOY`
2. Current price - here is where the magic happens, here for the simplicity query takes current price from  `lastPrice` field, normally this would be `pricePerUnit` from the newest transaction, in this case `fc` with value `12946377152`, but creator of the token closed the AMM right after this transaction and opened a new one, that resulted in recalculation in `lastPrice` based on new AMM params.
3. Calculations `(current price - oldest price in period) / oldest price in period * 100`

Without new amm `(12946377152-1184026286)/1184026286*100` equals `993%`.

With new amm `(562906230000-1184026286)/1184026286*100` equals `47441%`.

4. Liquidity - before block `X` liquidity was 14 tokens (10+4), now after all transactions it equals 0, so `0-14/14*100` is `-100%`

### Data 
```json
{
        "id": "181",
        "symbol": "NMG",
        "lastPrice": "562906230000",
        "ammCurves": [
          {
            "finalized": true,
            "transactions": [
              {
                "id": "00000074",
                "quantity": "10",
                "createdIn": 7542652,
                "pricePerUnit": "493344286",
                "transactionType": "BUY"
              },
              {
                "id": "0000007c",
                "quantity": "4",
                "createdIn": 7550671,
                "pricePerUnit": "1184026286",
                "transactionType": "BUY"
              },
              {
                "id": "000000cz",
                "quantity": "250",
                "createdIn": 8293969,
                "pricePerUnit": "13714971151",
                "transactionType": "BUY"
              },
              {
                "id": "000000fc",
                "quantity": "264",
                "createdIn": 8413877,
                "pricePerUnit": "12946377152",
                "transactionType": "SELL"
              }
            ]
          },
          {
            "finalized": true,
            "transactions": []
          },
          {
            "finalized": true,
            "transactions": []
          }
        ]
      }
```

**Comment by ikprk** [comment]
Closing for now
