### ISSUE TITLE
Arrow direction on tokens sold in the moving bar

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6430]
Needs to point down on sale:
<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVlFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf6467f50fdda2cf2a21b4913bc7353fe2f34479/Screenshot%202024-07-24%20at%2013.51.39.png" alt="Screenshot 2024-07-24 at 13.51.39.png" />

**Comment by ikprk** [comment]
Done
