### ISSUE TITLE
[USERSNAP] Account create password same but show incurrect password fix the problem

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6436]
**Taken at**: https://gleev.xyz/video/1306722
**Fields**:
- Houston, we have a problem.: Account create password same but show incurrect password fix the problem
- Expected Result: Password inccert problem
- Your Channel and Account Details: Iam new user
- Email or Discord handle for feedback: Jonym6408@gmail.com

**Browser**: Chrome 126 (Android 10)
**Screen size**: 360x820
**[Open #913 in Usersnap](https://app.usersnap.com/l/feedback/63343812-f64a-443a-ba6c-b9b20fb09602?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue
