### ISSUE TITLE
CRTs: Astronomical marketcaps with 0 transactions

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6437]
# Problem
1. Someone launches a new CRT, there are zero transactions and it gets an astronomical market cap from nothing. If no one has purchased any of the CRT it should _logically_ have a marketcap of zero.
2. Someone actually purchases the CRT on the market and the marketcap goes down by like 90% to something way more reasonable

The consequence of this problem is that the CRT marketplace gets many CRTs that have very high marketcaps despite having only `1 holder` (as can be seen in the below screenshot)
![image](https://github.com/user-attachments/assets/c8837169-ea76-4e1a-bc11-07ceb2786f81)

It appears that maybe starting a revenue share gives the token a price even if there are 0 TXs, but I am uncertain.

# Solution
Any CRT with zero sales/TXs should show a marketcap of zero

**Comment by Lezek123** [comment]
Fixed by https://github.com/Joystream/orion/pull/349
