### ISSUE TITLE
[USERSNAP] why my YPP show suspened

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6440]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: why my YPP show suspened
- Expected Result: how to slove the suspended account 
- Your Channel and Account Details: please help 
- Email or Discord handle for feedback: eeehanjit@gmail.com

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1544x707
**[Open #914 in Usersnap](https://app.usersnap.com/l/feedback/a7f9a608-d43e-4fd1-adde-8c020fb824ca?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
