### ISSUE TITLE
[USERSNAP] problem transfer 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6441]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: problem transfer 
- Expected Result: error al retirar 
- Your Channel and Account Details: j4Sv5eviJfUAqpXukzZstJiap2XieFJSG2G4T4xW7R94NJhVf
lucianofinanzas
- Email or Discord handle for feedback: elsapomaluco@gmail.com

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1366x768
**[Open #915 in Usersnap](https://app.usersnap.com/l/feedback/d22cc376-c6ca-4bb2-87e7-feef92d86908?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator and provided instructions for the withdrawal process, including a guide document. https://joystream.notion.site/How-to-withdraw-JOY-tokens-193dd774e3a74818a9494921636ead9c
