### ISSUE TITLE
[USERSNAP] youtube videos is not synchronizing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6442]
**Taken at**: https://gleev.xyz/channel/64992?tab=Videos
**Fields**:
- Houston, we have a problem.: youtube videos is not synchronizing
- Expected Result: i hope that works
- Your Channel and Account Details: https://gleev.xyz/channel/64992?tab=Videos
- Email or Discord handle for feedback: rameslamonie@gmail.com

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1536x864
**[Open #916 in Usersnap](https://app.usersnap.com/l/feedback/c8c708ef-7f79-445b-9ba9-37d6d62eafb3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Responded through discord support.
