### ISSUE TITLE
[USERSNAP] Why suspended 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6449]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Why suspended 
- Expected Result: Please why suspended 
- Your Channel and Account Details: K-Drama Recaps 
- Email or Discord handle for feedback: mehwishfatimaa1997@gmail.com

**Browser**: Chrome 127 (Android 10)
**Screen size**: 360x800
**[Open #923 in Usersnap](https://app.usersnap.com/l/feedback/492361cc-32d3-449d-b809-afc12bc478f6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
