### ISSUE TITLE
[USERSNAP] Why suspended 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6450]
**Taken at**: https://gleev.xyz/studio/ypp/dashboard
**Fields**:
- Houston, we have a problem.: Why suspended 
- Expected Result: What is the reason of suspended me
- Your Channel and Account Details: K-Drama Recaps 
- Email or Discord handle for feedback: mehwishfatimaa1997@gmail.com

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/de374eff-9b2c-4b3e-8ca7-721096068219-annotated_3c00aba9-88d1-4d5b-95c2-2c63fdcb3ff3.png?etag=9010d311446c41dbd39ac5da953ddb6c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/de374eff-9b2c-4b3e-8ca7-721096068219-annotated_3c00aba9-88d1-4d5b-95c2-2c63fdcb3ff3.png?etag=9010d311446c41dbd39ac5da953ddb6c)*

**Browser**: Chrome 127 (Android 10)
**Screen size**: 360x800
**Browser size**: 360x664
**[Open #924 in Usersnap](https://app.usersnap.com/l/feedback/f71c840e-1e3e-42ac-ba63-3be8e3af3d44?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
duplicated issue.
