### ISSUE TITLE
[USERSNAP] Esqueci minha senha e a semente de carteira 

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6452]
**Taken at**: https://gleev.xyz/
**Fields**:
- Houston, we have a problem.: Esqueci minha senha e a semente de carteira 
- Expected Result: Me enviar um código de verificação para cadastrar nova senha
- Your Channel and Account Details: Canal no YouTube / Mineirin RSB Gamer
E-mail: ricardobernabe06@gmail.com
- Email or Discord handle for feedback: ricardobernabe06@gmail.com

**Browser**: Chrome 128 (Android 10)
**Screen size**: 360x800
**[Open #926 in Usersnap](https://app.usersnap.com/l/feedback/f3b480a6-2386-4edc-b993-8185c49edc2b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Action Item: Notified the creator about the suspension and the reason for suspension of his and provided the document for reference. https://joystream.notion.site/My-channel-is-suspended-what-to-do-86a3df16c55c434ab2184d61dfcfc41b
