### ISSUE TITLE
[USERSNAP] My support ticket

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#6455]
**Taken at**: https://gleev.xyz/search?query=matthezz+mtz
**Fields**:
- Houston, we have a problem.: My support ticket
- Expected Result: Hello support, I want you to take my channel off the air for end-use privacy reasons 
and unfortunately I was also unable to create 
an internet channel and I don&#39;t want my 
data spread out there!
- Your Channel and Account Details: https://gleev.xyz/channel/62389
- Email or Discord handle for feedback: mathzeirabrz2383@yopmail.com

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1360x768
**[Open #929 in Usersnap](https://app.usersnap.com/l/feedback/d42a8b2b-6f8d-437c-af4e-022999c7d4a5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by rchrdcstro** [comment]
Inform the creator that we don't offer channel deletion option and sent instrcution instead on how to opt out in the program
