### ISSUE TITLE
Sometimes created videos are not displayed in uploads and they're not deleted from drafts

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#647]
This will need some investigation. Don't know how to reproduce this, but I experienced this bug several times.

Sometimes when I creating the video after a transaction is done and the sheet is minimized, the video is not added to the uploads and it's not removed from drafts. When Im trying to close the tab I also see a warning about data lost. 
When I refresh the site, I see snackbar: `Asset waiting to resume upload.` but don't see `AssetLine` in UploadsView with this video(If I remember it correctly)
Not 100% sure, but I think it's not happening when you upload only one video.  It happens when you upload the second video in the row.

**Comment by kdembler** [comment]
I think we managed to resolve that more or less. If the behaviour returns, let's open a new issue with updated details
