### ISSUE TITLE
Allow changing target environment on the fly

### ISSUE THREAD

**Issue by mikkio-j** [Joystream/atlas#658]
Dev mode needs some work (currently we are changing env variables manually, we want to go for dynamic mocking, staging etc.)

**Comment by kdembler** [comment]
Allow changing target environment on the fly (without app rebuild).

This will require some changes to how we access all the environment variables. Currently those will get pre-processed by the Netlify plugin (`./netlify-plugins/contextual-env`) and the app will only receive vars for the current environment. For example, in Netlify we will pass the following: `PRODUCTION_QUERY_NODE_URL`, `STAGING_QUERY_NODE_URL`, etc. Then the Netlify plugin will pick the correct environment based on which branch the build is targeting. So for production, plugin will take value from `PRODUCTION_QUERY_NODE_URL` and export it as `REACT_APP_QUERY_NODE_URL`.

I think we may need to just get rid of the plugin and allow the app access to all of those directly (all will need `REACT_APP_` prefix). For production we should default to just `REACT_APP_QUERY_NODE_URL`, without any env. For development, we should do the same but allow to change that. I envision some kind of `/admin` route that would allow you to save some kind of localStorage entry that tells the app which env to choose.

I'm not sure if that makes enough sense to start implementation. Please contact me for more details, we can get on a call to talk about this as well.
