### ISSUE TITLE
When the user is going through sign-in steps in studio there is no way to get back to regular joystream

### ISSUE THREAD

**Issue by drillprop** [Joystream/atlas#674]
I think it's self-explanatory. 
Right now when the user is on `signin/join` the side navigation is hidden and there is no link or button which will lead him to the regular viewer joystream. I think we should add  "go back to joystream" button somewhere

**Comment by KubaMikolajczyk** [comment]
This issue was already addressed by tech team but the pattern will have to be revisited by the design team to make it more UX aligned.

**Comment by KubaMikolajczyk** [comment]
This may be no longer relevant as we open joystream studio in a separate tab.
