### ISSUE TITLE
Remove unknown watched videos/followed channels

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#686]
I see this now

![Screenshot 2021-05-27 at 23 02 04](https://user-images.githubusercontent.com/437292/119896743-be363300-bf3f-11eb-86f7-d5e109fd9115.png)

**Comment by kdembler** [comment]
Yeah this is tricky because this are videos you watched on the previous chain, stored in your local storage. They just don't exist anymore but your local state doesn't know that. But you're right, this should be handled some way
