### ISSUE TITLE
Question: slow image loading

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#692]
I am consistently seeing almost all images load very slowly. I assume they are all getting scaled down in the publishing experience, so this should not be a lot of data. Is it the server that needs to have better specs?

![Screenshot 2021-05-29 at 07 14 56](https://user-images.githubusercontent.com/437292/120063700-c8078580-c068-11eb-8b8a-2b16d1144c05.png)

**Comment by kdembler** [comment]
Yep, the images should be scaled down and taking a look at what's one the front page, almost all of them are <400kb so shouldn't be an issue. It seems some of the storage providers are just very slow to respond. I wouldn't expect the specs to be an issue tbh, probably the network connection. It seems one of the storage providers is very slow, 674kb taking 20s to load. 

<img width="694" alt="Screenshot 2021-05-29 at 12 50 46" src="https://user-images.githubusercontent.com/12646744/120067536-808af480-c07c-11eb-858c-635a3e7f6f86.png">

**Comment by kdembler** [comment]
This is relating to slow storage providers, I don't think there's anything concrete to improve on Atlas side, closing for now
