### ISSUE TITLE
Idea: Add featured videos to front page

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#693]
On `sumer` the content curators can now more easily add featured videos, plus we are getting a lot more uploads (the average since release has been about 1 video/hour which is great).

The problem is that featured videos only show on the `videos` page: https://play.joystream.org/videos and do not show on the front page: https://play.joystream.org/

New users should be able to see some featured videos, and to further motivate usage of the featured videos there is discussion about potentially creating a reward program for users who have their videos featured: https://testnet.joystream.org/#/forum/threads/421

**Comment by kdembler** [comment]
@bedeho What do you think? We had featured videos on the front page previously but they got moved into `Videos` in one of the design iterations

**Comment by kdembler** [comment]
We're currently working on redesign of viewer experience, this should be a part of that
