### ISSUE TITLE
Idea: Add a "what is Joystream" link to Atlas

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#702]
Currently Atlas makes no mention of what Joystream actually is, it also doesn't mention that the product is in a testnet phase. For new users who have just joined the project, they may still have no understanding of how Atlas actually works (as in, there is no CDN hosting content and everything is hosted by on-chain workers)

There could be a basic information page, explaining the following:

* Joystream is a DAO
* This product is in a beta/testnet phase, you may encounter problems with loading content and bugs (link to Atlas GitHub repo)
* All the content is hosted by workers on the platform's Storage Working Group (link to WG)
* Content is curated by the Curator Working Group (link to WG)
* You should keep backups of all content you upload as during the testnet phase there is the possibility of storage failure (or other issues). In the event the storage directory needs to be reset, this will be announced ahead of time on the blog (link to blog)
* This page could basically act as a link to Pioneer. On Pioneer we have a page that links to Atlas (https://testnet.joystream.org/#/media) but we do not have a similar page on Atlas that links to Pioneer.

This basic information will help new users understand why there may be issues with downloads/uploads on the platform.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201958687417145/1202540208571960) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment]
This issue can be repurposed to broader Joystream and done together with #2032 label:onboarding is created

**Comment by dmtrjsg** [comment]
Proposed Solution"Powered by Joystream" as part of new name for Atlas. But let's consider the proposal added to description to show some basic info in a tooltip of some sort?

**Comment by toiletgranny** [comment]
@dmtrjsg As discussed on Slack, I added "Powered by [Joystream logo]" footnote at the bottom of the Side navigation component. I mentioned this change in this [component's changelog entry](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9151%3A168502) as I was working on this issue [Update Atlas Branding #3021](https://github.com/Joystream/atlas/issues/3021).


![image](https://user-images.githubusercontent.com/35307309/182620270-43af474d-980b-4a06-b96e-5952de76c81f.png)

**Comment by kdembler** [comment]
What if we added icon-link to github in there as well (just an icon would work)? This could encourage people to contribute to the codebase
![CleanShot 2022-08-03 at 15 35 41@2x](https://user-images.githubusercontent.com/12646744/182621759-4821dcb7-dd87-47b1-b873-1ea54bf6695c.png)

WDYT @toiletgranny @dmtrjsg

**Comment by dmtrjsg** [comment]
I like the idea! But perhaps an explicit copy >  Below Joystream, " We are an open source company, check our Github" maybe better? Is it it getting too crowded this way?

Also when we are implementing this, would be nice to make it easily configurable from the same place where logo is managed for other GW operators 😇

**Comment by kdembler** [comment]
I think adding a copy may make it too crowded, and it's a fairly common pattern to use just a github icon as a link.

**Comment by dmtrjsg** [comment]
Sure, not insisting. But it isnt obvious that we are open source and mentioning it may inspire more people to click on it. not a biggie

**Comment by toiletgranny** [comment]
@dmtrjsg @kdembler Ooff, that's quite a lot of information we want to squeeze into this space, I'm afraid. If emphasising the fact it's an open source project, specifically in this place, is strategically important to us, then I would suggest revisiting the text-only version I've been showing both of you yesterday on Slack. 

Here, have a look and see it in context. The version on the left is what we agreed upon yesterday, the two in the middle are your suggestions, and the one on the right is my recommendation.


![image](https://user-images.githubusercontent.com/35307309/182820101-067ed8b4-b6f7-4f30-bc2d-ea87752958b8.png)

**Comment by kdembler** [comment]
Let's discuss on the call today 👍 Just for clarity, my suggestion was just the github icon, without the "Check out"

**Comment by toiletgranny** [comment]
Ok, then two more options.
 
![image](https://user-images.githubusercontent.com/35307309/182821205-d536ced4-6298-4b7a-9715-174e59b223f9.png)

**Comment by toiletgranny** [comment]
Ok, having talked this through during tech <> design sync call, we agreed we want to proceed with the below version, where:
1. The "Powered by [Joystream logo]" part, as a whole, links to joystream.org,
2. The GitHub icon logo links to the Atlas GitHub repository — https://github.com/Joystream/atlas (@kdembler please correct me if I'm wrong).

![image](https://user-images.githubusercontent.com/35307309/182847165-cdd2dbbc-dbfd-4b92-acdf-73c2482ae859.png)

cc @bedeho

**Comment by kdembler** [comment]
Yes, I would go with atlas repo link as well, it should be easy to get to org from there, harder the other way around

**Comment by bedeho** [comment]
Looks good ;)

**Comment by kdembler** [comment]
@toiletgranny Do we have a Figma link?

**Comment by toiletgranny** [comment]
@kdembler I mentioned this change in this [component's changelog entry](https://www.figma.com/file/Pf31tuYpozYmpq163U2ho8/Web-components?node-id=9151%3A168502) as I was working on this issue https://github.com/Joystream/atlas/issues/3021.
