### ISSUE TITLE
Hide cancel button from transaction bar when creating new channel

### ISSUE THREAD

**Issue by freakstatic** [Joystream/atlas#703]
The cancel button on the bottom right doesn't do anything in the Creating Channel page
(https://play.joystream.org/studio/channel/new)

![image](https://user-images.githubusercontent.com/7486476/120450658-948a6b00-c388-11eb-8b86-9d73343ce7bd.png)

**Comment by kdembler** [comment]
Good catch, we'll get rid of it!
