### ISSUE TITLE
Bad cover sheet & Transaction bar interaction

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#711]
This happens if the cover sheet is open, and then I chose to do any sort of transaction. I should not be forced to close the bar.

![Screenshot 2021-06-04 at 13 48 27](https://user-images.githubusercontent.com/437292/120797288-1d95d380-c53c-11eb-92f5-e5cdf1f964cb.png)

**Comment by kdembler** [comment]
This should have been fixed, although we did a couple of iterations on the code and must have broken along the way. My guess is this was in channel edit view?

**Comment by bedeho** [comment]
Very possible.
