### ISSUE TITLE
Better indicate required fields in forms

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#715]
I seem to recall we had a graceful way to indicate to the user that they were ready to publish some changes, for example a video. Right now, its almost inevitable for a user to try to publish, only to be told that lots of non-optional fields are blank after the fact. Didn't we have a thing for this, almost a progress indicator? Right now its not a good experience, as you presume lots of options are optional and the button is available to click.
![Screenshot 2021-06-04 at 14 33 15](https://user-images.githubusercontent.com/437292/120804118-939e3880-c544-11eb-948c-f897028f53b6.png)

**Comment by kdembler** [comment]
We had a progress indicator only for channel edit. I agree, we should somehow indicate which fields are required and which are optional

**Comment by bedeho** [comment]
I agree.

**Comment by KubaMikolajczyk** [comment]
During the discussion we agreed that marking optional fields would be a better approach than marking required. This will be tackled along other input realted work.

**Comment by kdembler** [comment]
This has been tackled as part of updated video workspace design. Example here: https://www.figma.com/file/xm6vBdSnQDroc57rGfGtPM/%5BPage%5D-Video-workspace?node-id=419%3A7992
