### ISSUE TITLE
Second non-functional scroller

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#716]
This in the publishing sheet for a video and on Firefox 88.0.1 (64-bit). The second scroller has no impact on anything.

![Screenshot 2021-06-04 at 21 07 51](https://user-images.githubusercontent.com/437292/120854661-c31d6700-c57d-11eb-8a5c-5c4d1e717db3.png)

**Comment by kdembler** [comment]
@bedeho Is this reproducible for you? I've tested on Firefox both on Mac and Windows and can't see that second scrollbar
