### ISSUE TITLE
Tedious manual closing of success dialogs

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#717]
There are a few places where some transaction is executed, and after it is completed, you get a dialog like this that you have to close to proceed. 

![Screenshot 2021-06-04 at 20 45 04](https://user-images.githubusercontent.com/437292/120854719-d7f9fa80-c57d-11eb-8510-51e52090588c.png)

![Screenshot 2021-06-04 at 15 22 13](https://user-images.githubusercontent.com/437292/120854721-d7f9fa80-c57d-11eb-85c1-61515d7fca18.png)

This gets really tedious. What we want is to make sure the user registers the transaction went through fine, when it did, but then to move on. Perhaps it would be better to only show this sort of thing with a very short circular timer thing which winds down in 1-2s, and then the dialog slides away. Also perhaps its better to not have this result dialog as distinct from the actual progress 3 step progress dialog, it could just be the final step.

**Comment by kdembler** [comment]
Ideally, those wouldn't even be blocking. The operation could very well be minimized and happen in the background. That would require some work on how to represent those pending operations and assets they target

**Comment by bedeho** [comment]
That would be even better!
