### ISSUE TITLE
User input validation

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#72]
Currently, publishers can input malicious text that will be directly injected into the users browser, such as in video and channel titles, descriptions, and probably tons of other places. There is no input validation any place in our pipeline to prevent this. This is both a big security and a usability concern. 

We have to
- Identfify all such places, make issues for each-
- Compile a list of possible remedies: Here there is both the conceptual question of who does it (Atlas or Query node, I lean very strongly towards the former), and how it will work in further detail.
- Pick one.
- Plan to have it done and deployed.

**Comment by bedeho** [comment]
Additional notes

- Handling this is in the query node is unlikely sufficient, because a malicous query node could still possible cause problems for end users. It would seem that it would need to be complemented with some sort of Atlas side double checking of all fields 
- In terms of what to do in Atlas, a very simple approach would just be to display all such text fields raw, so if there is an malicous content, it would just make the video/channel look bad. Alternatively some more visually graceful placeholder content could be used instead, but then one would need to actively detect things.

**Comment by kdembler** [comment]
After the internal discussion it seems this is a non-issue at the moment, as React and browser combined automatically stop all (that we came up with) possible attack vectors. Closing for now
