### ISSUE TITLE
Recent searches hanging

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#729]
I see this perpetually, notice that I have not even entered any search phrase

![Screenshot 2021-06-07 at 20 10 26](https://user-images.githubusercontent.com/437292/121068990-408ae680-c7cd-11eb-9f4f-5425214da29e.png)

**Comment by kdembler** [comment]
Is it possible that these are from the previous testnet?

**Comment by bedeho** [comment]
Yep, that was the reason. I guess we should think more about this next network upgrade, closing!
