### ISSUE TITLE
Atlas UI Review III for Babylon

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#73]
- The no selected state for the top menu items (Home, Browse) does not have same color for text and icon. It should be dimmed for both, as text is.

![Screenshot 2020-11-28 at 12 08 25](https://user-images.githubusercontent.com/437292/100514148-84dc6080-3172-11eb-9af7-fccc42d018b4.png)

- This artifact is still here - let's raise the vertical cover video gradient a little bit so that the artifact isn't as visible

![Screenshot 2020-11-28 at 12 27 47](https://user-images.githubusercontent.com/437292/100514450-25338480-3175-11eb-8679-0eebf812ea2f.png)

- Make the icon in the play/pause button positioned in a fixed horizontal position, right now it moves due to changes in label width. Make button wider 

- Browsing section is missing its branding pattern

![Screenshot 2020-11-28 at 12 37 06](https://user-images.githubusercontent.com/437292/100514603-798b3400-3176-11eb-9d17-a910483ed430.png)

- When going from one category tag to another on the Browse screen, you should scroll to the top, you don't want to skip all the way down in the new category.

- The space between the category tags and the left edge of the view port does not collapse to be smaller at a certain break point the way it does for everything else in the layout.

![Screenshot 2020-11-28 at 12 38 36](https://user-images.githubusercontent.com/437292/100514631-c242ed00-3176-11eb-97fc-a9cbfcb96403.png)

- When loading on a channel page, I see a stretched out version of the pattern which looks totally wrong, before the cover loads. Is that correct?

- Can we add proper fade-in on the channel cover also, like the video previews, it appears to just snap in instantly now. Also for the channel avatars

- Lets' have the audio on by default, much more impactful, yes possibly also annoying, but hey, the intro audio track here is excellent.

- I still see the line breaking on the subtext for the cover photo change multiple times. Lets keep this static at all sizes, and only accommodate using font-size. Moreover, let us prevent the subtext from extending any further outside the main title text than something like this

![Screenshot 2020-11-28 at 12 58 59](https://user-images.githubusercontent.com/437292/100515022-8a897480-3179-11eb-9177-a45b73194ee4.png)

e.g. this is not great, with text covering Mr. Jone's chest :P

![Screenshot 2020-11-28 at 13 00 16](https://user-images.githubusercontent.com/437292/100515053-b4db3200-3179-11eb-8ea1-e32d4055833d.png)

- When I go to launch a video, the scroller will remain in the position it was on the launching screen, which means I have to scroll up to the video player in many cases. 

- At this point I have lost the last discussion point on this, but when going from loading to playback, the area video player portion of the layout collapses and comes back, which means the entire page snaps up and down.

- When scrolling on the video playback page, the video player floats over the top menu :D 

![Screenshot 2020-11-28 at 13 15 51](https://user-images.githubusercontent.com/437292/100515361-dd642b80-317b-11eb-94f4-a0b90232fdd6.png)

- There should be a greyish line separating the top menu from the bottom which is missing. 

- When on the Browse screen, this greyish line should also be at the bottom of the category section itself.

![Screenshot 2020-11-28 at 13 36 00](https://user-images.githubusercontent.com/437292/100515763-b5c29280-317e-11eb-8c62-7a7af57e697a.png)

- We have discussed this before as well, but I think it's still not great how we are managing the channel cover sizing. If we look at how YouTube manages channel covers, that seems like an improvement on what we have. The two differences appear to be that (a) manages visible part of the cover as if it was much flatter than we do, we appear to be trying to display 16:19 aspect ratio, and this ens up eating up a lot of vertical space very quickly. (b) we seem to be doing lots of adjustments to how much of. Is it not possible to just pick one very flat implied aspect ratio and not do any these adjustments underway? If the image is much taller than that, then too bad, it gets covered up, if its much shorter than that, then too bad, it doesn't cover the full height. The publishing flow helps them do this properly if they wish to.

**Comment by bedeho** [comment]
I missed this one, sorry!

- The right end of the search bar must align with the right end of the video player so long as the video player is full screen. It seems there are two different margins applied to the player and the top menu depending on the size of the viewport, but in both cases there is not perfect alignment

![Screenshot 2020-11-30 at 12 17 27](https://user-images.githubusercontent.com/437292/100604162-71fa9500-3306-11eb-8753-7c5edbfec9d5.png)


![Screenshot 2020-11-30 at 12 17 37](https://user-images.githubusercontent.com/437292/100604180-78890c80-3306-11eb-8f2a-520a2b57ced8.png)

**Comment by kdembler** [comment]
Issues:
- https://github.com/Joystream/atlas/issues/79
- https://github.com/Joystream/atlas/issues/80
- #81 
- #82 
- https://github.com/Joystream/atlas/issues/46
- #83
- #84

**Comment by kdembler** [comment]
All fixed, closing

**Comment by bedeho** [comment]
This still seems to be an issue @kdembler :

> (b) we seem to be doing lots of adjustments to how much of. Is it not possible to just pick one very flat implied aspect ratio and not do any these adjustments underway? If the image is much taller than that, then too bad, it gets covered up, if its much shorter than that, then too bad, it doesn't cover the full height. The publishing flow helps them do this properly if they wish to.

**Comment by bedeho** [comment]
I also thought we agreed on the same approach on the main landing page.

**Comment by kdembler** [comment]
We discussed that on the call, I thought we had an understanding on the fact that some adjustments will be needed. I also don't think we'll be able to use the same policy for channel cover and the cover video on the landing page. That was brought up on Rocket Chat, let's continue that there

**Comment by kdembler** [comment]
Discussed, we're shelving that for now - created an issue - https://github.com/Joystream/atlas/issues/169 and closing this one
