### ISSUE TITLE
Filter videos pending upload from search results

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#733]
I am seeing videos eppear in Atlas before the primary asset has been uploaded, this is akward, as playback will not work, and the thumbnail will possibly not be visible as well. I thought we had used the expressive query node API to pick up on this and filter this out. I saw such videos both in search results and on the channel page, but a bit less sure about the latter.

**Comment by kdembler** [comment]
Yep, we already do that for videos but we missed that in the search results. Shouldn't happen for videos in the channel page though, we do proper filtering there
