### ISSUE TITLE
Graceful handling of invalid asset ids

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#738]
If a video or channel is deleted, the current client side state is not dealing well with this, for example in the "continue watching" or the "recent search" section. They just appear as perpetually loading entries. This should probably be dealt with a bit better, but its not clear how exactly. Just raising the issue for later.

**Comment by kdembler** [comment]
So this has been fixed now for both "continue watching" and "followed channels". If the query node reports video/channel as missing we remove them from their respective list. I think it's just recent searches that need this same behaviour
