### ISSUE TITLE
Sharing Videos doesn't generate a preview.

### ISSUE THREAD

**Issue by fcescob** [Joystream/atlas#75]
Currently, sharing a video on social media doesn't generate any type of preview. 
Fix this by adding Open Graph Meta Tags: https://ogp.me/

**Comment by kdembler** [comment]
Not sure if this will be easy to do since we load the video asynchronously. Will the social media crawler run our JS to fetch the data and wait for tags to be populated? I guess not :(

**Comment by kdembler** [comment]
Closing in favour of #416, contains more details
