### ISSUE TITLE
Page refresh in studio shows connection closed alert

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#761]
The alert slides down when someone refreshes, which it should not if the user is actively refreshing.

**Comment by kdembler** [comment]
I think we may not be able to actually detect a refresh, but what we could do is delay showing the alert by something like 1 sec, that should do the trick

**Comment by kdembler** [comment]
(This was happening on Firefox)

**Comment by drillprop** [comment]
I cannot reproduce this. Is this still happening?

**Comment by kdembler** [comment]
Have you tried on Firefox?

**Comment by drillprop** [comment]
Yeah, I tried but for some reason I couldn't reproduce this at first. I see it now.
