### ISSUE TITLE
Create simple e2e tests setup

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#772]
please DM me to agree on requirements

**Comment by rafalpawlow** [comment]
@kdembler Here is draft of testing scenarios. I'd love to get your feedback, also feel free to expand if something comes to your mind.

# Atlas test cases

## Studio
* open how it works on sign up
* go to studio page from player page
* open upload page from main screen
* sidebar navigation
  * open sidebar
  * go to videos
  * go to channel
  * go to uploads
  * open upload video page
  * open terms and conditions
  * open copyright policy
* open
* topbar
  * open upload video page  
  * open channels dropdown
  * log out

**Comment by kdembler** [comment]
Looks good, although given that we will be doing quite a big overhaul of the viewer experience starting next week, maybe we do just the `Studio` part for now? There will be a lot of changes to viewer so not sure how valuable that scenario will be to have
