### ISSUE TITLE
Atlas Product Management

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#777]
# Document Purpose

This is a draft document describing how the Atlas team and product should be managed, and it should be understood as a starting point for generating discussion and feedback.

# Background

The Atlas product state, product roadmap and team has grown considerably. There has also been some drift in our processes from the [last time we attempted to define them](https://github.com/Joystream/atlas/issues/188), as such, now is a good time to re-establish a clear process.

## Team Members 🧑‍💻

The team is quite dynamic, but the current cast includes

| Name  | Role  | Association  |
|---|---|---|
| Kuba Mikołajczyk   | Design Lead (DL)  | Netguru  |
| Milosz Klimek | Design Mentor & Manager  | Netguru  |
| Adam Ruthendorf-Przewoski  | UI Design  | Netguru  |
| Klaudiusz Dembler  | Front-End Tech Lead (TL) | Jsgenesis  |
| Diego Cardenas  | Front-End Engineer | Jsgenesis  |
| Rafal Pawlow  | Senior Engineer | Elpassion  |
| Bartosz Dryl  | Front-End Engineer | Elpassion  |
| Mikołaj Jędrzejewski  | Front-End Engineer | Elpassion  |
| Bedeho Mender  | Product Owner (PO) | Jsgenesis  |

Note: In many cases below the PO is excluded from the notion of _the team_. Also, when referring to teams below, it is in reference to the design and tech teams.

## Release Targets :bow_and_arrow:

Experience from recent work, and where we are going, clearly shows that we will be working against three distinct release target types simultanously. Doing this effectively, which importantly also involves dynamic repriotitizations and rescoping, is the most important goal of our process.

| Name  | Description | Release ETA from start  |
|---|---|---|
| Long-term | Not yet scheduled for release  | 3>= months |
| Testnet | Scheduled for release in the next team wide release | <=2 months |
| Urgent | scheduled for production within a very short period of time | <=1-2 weeks |

## Goals :dart:

The product management process should achieve the following goals:

1. An up to date view of what every team member is working on currently and in the immediate future.
3. Capture and triage feedback and bug reports coming from users of the production application.
4. Keeping designers in synch with changes or fixes the tech team ships which may not be in the current designs.
5. Generate artefacts, logs and information that lowers the bar for outsiders and future contributors to get involved.
6. Regular meetings to priorities and rescope current areas of work.
7. A clear division of responsibility which makes it possible to determine who needs to be in what meeting.
8. A low friction means of everyone staying in synch and discussing issues synchronously.

# Proposal

## A canonical messaging channel :love_letter:

Everyone in the team should be available and responsive in `atlas` in the RocketChat when working during normal hours.

## Daily Public Todo :speech_balloon:

Everyone in the team should write an entry in `atlas-standup` in the RocketChat in the format already present.

## Sprints :running:

All work associated with long-term or testnet work should be organised into _sprints_. Each sprint should have a short name which is easy to type and pronounce, like `channel-view` or `signup-flow`, etc. These are focused working periods, no longer than 21 days, during which PO or any other stakeholder is not required to review the output. Importantly, a sprint should be as short as possible, while balancing the likely value of early feedback and the overhead of checkins.

The purpose of sprints is having a way of generating constraints for work which has looser time constraints by virtue of being further away from production.

### Sprint Master & Milestone

Sprints could be across team boundries or not, depending on the need, and a single person could be involed in more than one sprint simultanously, but this should be rare. A designated _sprint master_ is tasked with the overal responsibility over the sprint, typically either the TL, DL or PO. Each sprint must also have a _sprint issue_, written and maintained by the master. It should initiall describe the overall objective of the sprint, who is involved - and for what purpose, and then any important sprint meetings should be appended as replies, including summaries of what was concluded.

### Estimation

A sprint should be broken down into a set of tasks which, called _sprint tasks_, which are small enough that they only cover the work of a single person, and can be reliably estimated in terms of hours of effective work. Any sprint task which has so much uncertainity associated with it that estimation is not feasible, should just be given some large number.

## Issues :scroll:

- All work being done across all teams should be organised exclusivley in the Github issues for the `Atlas` repo.
- The relevant team (tech, design) is responsible for maintaining the assignment and labels for a given issue.
- All work being done by anyone at all times should be mappable to a single specific issue in this tracker. The daily public todo entries should mostly reference such specific issues.

All issues should eventually be fully labelled using the following suite of labels

- `design`: Requires attention from a designer to be processed or implemented.
- `bug`: A malfunction in the behaviour in some deployment of the application. The core issue may not be in Atlas itself, however the behaviour was observed through Atlas.
- `idea`: An idea for a new feature in the product.
- `urgent`: Should be processed and ideally executed upon very quickly.
- `estimate-<x>`: It is currently estimated that this will require `x` working hours for a single person to complete as a sprint task.
- `<testnet-name>`: It is part of the effort of releasing a testnet with name `testnet-name`
- `pending-triage`: Requires attention from team lead or PO to be properly labelled and catalogued. Should be applied to new `bugs` or `ideas`, and be removed only when DL or TL has reviewed. Anyone finding an issue from the community which has not been reviwed, i.e. has not other meaningful labels, should apply this label.

# Releases Deployment

TL has unilateral deployment prividlige into production on a rolling basis.

# Meetings :handshake:

## Weekly Goals and Weekly Summaries

Every working week starts of with reasonably well specified goals for each team, describing what progress is expected on the ongoing sprints and urgent work. Every final working day of the week, each team lead should submit a report, taking no more than 20 minutes to perpare, to the `atlas` channel describing

1. What was achieved this week.
2. What departures from the weekly sprint plan occured, such as blockers or unexpected problems.
3. Github issues, if any, or any other agenda items for the next team lead meeting (see below).
4. For any sprint where author is the sprint master: Total hours across all estimated issues that are not done. (no partial progress counting), and equivalent estimated completion day based on team size working on it.

## Start of Week Team Lead Meeting

First working day of the week, unless something else has been agreed upon, where at least PO, TL and DL meet to

1. discuss overall progress of ongoing sprints and adjust any scope or priorities based on this.
2. set weekly goals for each team.
3. deal with any issues or matter raised in the weekly summaries in the prior week.

PO will invite with full agenda at least 24 hours in advance, if possible, and whomever is required outside of TL and DL should join on a per need basis.

## Sprint Planning Meetings

These are regular meetings where, PM and the relevant team lead(s), try to plan an upcoming sprint.

**Comment by kdembler** [comment]
Looks all good. I wanted to give some feedback for the labels we're gonna be using:
- Maybe let's have a separate label for meta issues. This issue has `idea` label but I would expect that to be related strictly to ideas inside the product. How about `meta` or `process`?
- Maybe we could expand on priorities a bit? You've  added `urgent`, we already used `p1` `p2` `p3` to prioritize inside a project. How about something like `priority:low` `priority:medium` `priority:high` `priority:critical` or (`priority:urgent`)? Those could be applied to external issues, as well as to issues inside a sprint

**Comment by kdembler** [comment]
I'm also wondering:
1. what's the difference between `enhancement` and `idea`?
2. when exactly should we apply `pending-triage`?

**Comment by bedeho** [comment]
> what's the difference between enhancement and idea?

I think I use ideas for bigger things, perhaps speculative or needing lots of investment - to make sure people to not think everything is going to get implemented , enhancement for smaller things, but we can actually just drop idea and just use enhancement. To simplify!

Notice @KubaMikolajczyk .

> when exactly should we apply pending-triage?

Its basically something which needs review from more than the creator in order to get scheduled for a sprint, or just put permanently on the backlog, eitehr one would result in `pending-triage` getting removed. I thouhgt of it as an easy way to find things that should be processed for weekly meetings. Do you think this distinction is not worth it?
