### ISSUE TITLE
Confusing failed uploads due to hitting storage space limit

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#782]
Some users want to start synching a lot of content right away, and they are running into the issue that the are running out of space, however, the error they see makes this hard to understand.

https://prnt.sc/15hmal8

While we will need to do a more deeper review of storage management in the future when the v2 of or storage system is rolled out, but in the interim it could be helpful to

a) prevent users from starting publishing flows when they have run out of space.
b) prevent users from completing publishing actions for tabs they already have open if space has run out.

**Comment by kdembler** [comment]
If we want to prevent user from even starting the flows, I think we should make that data available in the query node, otherwise that would be first state we need to read from blockchain directly

**Comment by MishaSER1** [comment]
Hello @tomato, you can increase the limit by another 10 GB) https://play.joystream.org/channel/150
