### ISSUE TITLE
Atlas Player: Design Ideas Backlog

### ISSUE THREAD

**Issue by toiletgranny** [Joystream/atlas#785]
# Document Purpose
This document aims to gather all ideas for improvements and new functionalities around Atlas' video player. Design-wise, ideally, all the things below are tackled during one go. 

Implementation-wise, the below items can be taken apart from the list and implemented at different points in time, as I see no mutual dependence in the below functionalities atm. It does not apply to functionalities marked as critical. 

Regarding the order of implementation, following the order in which ideas are presented below would be preferable.

### #821 Player's UI revamp/overhaul (🚨  Critical) 

- To make the currently available controls visually aligned with the JS design system (through the use of components from the JS component library or through introducing new components, based on previously established style guide).
- To ensure a working mobile experience for each functionality mentioned below.

### #821 Adjustments to the logic behind showing/hiding player's UI 

- To hide the player's UI immediately after the cursor leaves the player area.
- To hide the player's UI after **3 seconds** (? to be confirmed through research and testing) after the playing has been resumed.

### #822 Adjust states of the player

- To introduce an error state for (#40): 
	- Failed to load the whole video page,
	- Failed to load the media file,
- To introduce states for video completion (#52):
	- When the standalone video finished playing,
	- When the playlist video finished playing.

### #823 Introduce keyboard shortcuts

Key(s) | Action | Visual Feedback
------------ | ------------- | -------------
`Spacebar` , `k` | Play/pause | Yes
`←` and `→` | Seek backward/forwards by 5 seconds | Yes
`J` and `L` | Seek backward/forwards by 10 second
`↑` and `↓`  | Increase/decrease volume by 10% | Yes
`M`  | Toggle mute | Yes
`F` and `Escape`  | Toggle full-screen mode 

### #824 Video preview when scrubbing

To allow the user to preview the video at the selected point on the timeline.

### #825 Quality controls

To allow the user to change the quality of the playback (eg. 360p, 480p, 720p, 1080p, etc.), providing an “Auto” option at the same time.

### #825 Playback speed controls

To allow the user to change the speed of the playback (eg. 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2).

### #825 CC/Subtitles

To allow the user to enable/disable CC or subtitles included with the video during upload.

### #826 Casting

To allow the user to cast the video to a TV.

### #827 Prev/next controls

To allow the user to jump into previous (in case of playlists) and/or next (in case of playlists, otherwise: suggested) videos.

### #828 In-player social features

To allow the user to share a video from the player:

- Copy/generate a link,
	- Include a timestamp,
- Share on social media platforms (the list of platforms to be finalized through a research),

### Adjust the video page

- To introduce suggested videos section (as opposed to only having other videos from the same author),
- To introduce a default player mode (size, as opposed to the current “cinema-mode”),
- To introduce a platform-wide PIP mode (to allow the user to navigate into different screens/pages in the app, while watching the video),

**Comment by bedeho** [comment]
This mentions `Video preview when scrubbing`, but be aware that we don't even have baseline scrubbing at the moment in the design, let alone the preview.

**Comment by toiletgranny** [comment]
@bedeho Sorry for the confusion! 

As discussed yesterday, by "scrubbing" I meant the act of hovering your cursor over the timeline and seeing the preview of the video at a selected point in time, not necessarily clicking and holding the timeline. As such, this functionality is already available within the currently implemented version of the player component.
