### ISSUE TITLE
Long time failed upload persisting

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#790]
Its really confusing to come back to `MyUploads` to see failure asset uploads without a clear association to what they belong to. This could be because the videos were deleted? but I am not sure.

![Screenshot 2021-06-16 at 17 43 33](https://user-images.githubusercontent.com/437292/122251314-add40100-ceca-11eb-8720-9b49f160f934.png)

Should be revised when the `MyUploads` area is revised as a whole.

**Comment by kdembler** [comment]
We're currently working on an improvement that will only list assets that are pending and known by the query node so hopefully we get rid of situations like this

**Comment by bedeho** [comment]
We have other primary issues
- #887 
- #868
