### ISSUE TITLE
Unexplained failure during upload

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#794]
Everything works fine, the asset is a `.mov` file, not sure if that matters, but when I click publish I see this

![Screenshot 2021-06-16 at 22 41 12](https://user-images.githubusercontent.com/437292/122290553-28fddd00-cef4-11eb-8466-d567b1585d05.png)

The dev console prints

 ```
 Media resource blob:https://play.joystream.org/acb3621c-11fa-7e4e-b13c-5ba90a7191fa could not be decoded. edit-video
Media resource blob:https://play.joystream.org/acb3621c-11fa-7e4e-b13c-5ba90a7191fa could not be decoded, error: Error Code: NS_ERROR_OUT_OF_MEMORY (0x8007000e)
Details: virtual RefPtr<MP4Demuxer::InitPromise> mozilla::MP4Demuxer::Init(): Parse MP4 metadata failed
```

Seems related to the media somehow. 

Anyway, the UX needs to be improved here. Should not be possible to issue transaction at all if this does not work, probably a better failure message should be provided when specifying the media from the get go.

**Comment by bedeho** [comment]
Weirdly, when I clicked the `Add video file`, I now see this

![Screenshot 2021-06-16 at 23 04 05](https://user-images.githubusercontent.com/437292/122293408-42ecef00cef7-11eb-98bb-39f1b3ee2b4c.png)

So it seems there actually was an error message, but the colors hid it, however the message was not actually that meaningful in the end.

**Comment by bedeho** [comment]
![Screenshot 2021-06-16 at 23 04 05](https://user-images.githubusercontent.com/437292/122293834-b55dcf00-cef7-11eb-96e8-9ec501db4c0d.png)

**Comment by kdembler** [comment]
Could you describe the steps you've taken to encounter that? (regarding the interaction with the file picker)

**Comment by KubaMikolajczyk** [comment]
- [x] Improve the interaction with video/thumbnail stepper
