### ISSUE TITLE
Idea: Manually Updatable Hero section

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#803]
We want to be able to feature  more of the new UGC coming online now, however, currently this seems to be hardcoded into Atlas itself. Its not clear whether this sort of featuring should be controller by the curators, or if the gateway (i.e. Atlas operator) should him/herself control this. As a way to at least honor our top creators, we would love to be able to have the content lead periodically decide what creators to feature, and then have the Atlas team update this on their end with minimal effort.

- What would this require in Atlas, and what additional assets would the content lead need to provide?
- What technical changes would this require in Atlas to make it convenient to change this without downtime?

**Comment by kdembler** [comment]
We actually already have support for fetching that data inside of Atlas. So if it would be provided by the query node, changes in Atlas would be minimal.

Regarding the required assets, we currently use this additional data not found in the regular videos:
- Separate asset for hero video "cut" - we don't want to play the full video so we currently use a separate file containing cut video. We potentially could instead use the original video file and just define the start and end of the desired cut. That would require more changes in the logic behind displaying that though. I think separate asset also gives more flexibility, maybe you want to play some kind of "trailer" or "teaser" that would be slightly different than the original video in how it's structured
- Separate description - we currently show short description of the playing video that is separate from the full description the videos has. However, I think the new designs got rid of that text, cannot find it in Figma atm though

**Comment by bedeho** [comment]
Can you describe what you would need from the query node exactly?

**Comment by kdembler** [comment]
Currently in Atlas we use this:
```graphql
type CoverVideo {
  id: ID!
  video: Video!
  coverDescription: String!
  coverCutMediaMetadata: VideoMediaMetadata!
  coverCutMediaDataObject: DataObject
  coverCutMediaAvailability: AssetAvailability!
  coverCutMediaUrls: [String!]!
}

type Query {
  coverVideo: CoverVideo!
}
```

**Comment by kdembler** [comment]
That's done now
