### ISSUE TITLE
Bug: playback stops/breaks with certain uploads

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#841]
Example files:
* https://play.joystream.org/video/634
* https://play.joystream.org/video/773
* https://play.joystream.org/video/632

Problem: These videos will play for a few seconds and then stop working, at this point they revert back to the video thumbnail. I can download the full file directly from the same `storage provider` and playback the entire file completely fine. For some reason on Atlas it just quits playing the fille almost immediately or a few seconds after playback has started. You can click on the thumbnail again to try and playback but it will switch to a different provider and the same behaviour happens.

The curator lead (igrex on Joystream) has provided a full list of files that have similar issues, I am not sure if they all have the exact same issue and have only briefly looked through a few of them: https://discord.com/channels/811216481340751934/815192060276506664/857171355916566528

They also tried this from multiple devices, browsers and locations

**Comment by igrex** [comment]
Not sure why I am mentioned here, but I am neither the curator lead nor am I involved in this project at all. Please remove me from the description @mochet

**Comment by mochet** [comment]
> Not sure why I am mentioned here, but I am neither the curator lead nor am I involved in this project at all. Please remove me from the description @mochet

apologies, we have a user with the same name (although apparently not on Github). Have removed you.

**Comment by kdembler** [comment]
This has been fixed since
