### ISSUE TITLE
Remove joystream studio logo from sign in page inner content 

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#856]
This will have to be addressed in design and implementation - we will remove the logo from the inner content and leave it in top navigation.

**Comment by dmtrjsg** [comment]
![Uploading Joystream_remove_stuidio_logo.png…]()

**Comment by dmtrjsg** [comment]
<img width="920" alt="Joystream_remove_stuidio_logo" src="https://user-images.githubusercontent.com/93924525/143253070-091dc1bd-bade-4f47-94af-ab139b77f8c3.png">

**Comment by kdembler** [comment]
Will be done as part of #1653
