### ISSUE TITLE
Video tiles alignment (implementation - design)

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#865]
All tiles (for viewer and publisher) are specified in variants in Figma.
In implementation there is inproper spacing & text sizing which needs alignment.

Video tiles variants: [Figma link](https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=4806%3A98753)

**Comment by kdembler** [comment]
Implementation should be up to date now
