### ISSUE TITLE
Sometimes it's not possible to accept ToS

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#875]
When creating a membership, the last step of multistepper is accepting ToS. The button won't unlock unless you scroll to the bottom. However, it seems sometimes the button won't unlock even then. I experienced this once myself on a Windows machine and community member has also reported it happening on Windows 10 with the latest Chrome. Not sure how to reproduce it but we could try looking into what the problem may be and find some more solid solution

**Comment by dmtrjsg** [comment]
Hard to reproduce. Closing now and waiting for user-reported bug OR centry-events.
