### ISSUE TITLE
In-App feedback 

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#879]
Could it be a good idea to introduce a really low bar way of allowing anyone to provide feedback while we are in the development stage? There are plenty of off the shelf solutions for this, like (Mopinion)[https://mopinion.com/], so it should very low cost to integrate maintain.

**Comment by dmtrjsg** [comment]
usersnap is a contender; while mopinion can be added to the discovery mix on MIro board. Ask @dmtrjsg
