### ISSUE TITLE
No limit for image size

### ISSUE THREAD

**Issue by blrhc** [Joystream/atlas#88]
There doesn't seem to be an issue for this yet, and since Pioneer no longer supports media playback, this seems the best place to put it.

Since thumbnail/preview images (as well as channel profile and cover images) are taken from user-provided URLs, it seems probable that if an attacker were to create a video preview/thumbnail with an unreasonably large file size then associate this with a given video, it would break the previews on the rest of the page where this thumbnail is displayed (including on the landing page and search results pages etc.) 

It might also stop the page from loading or cause the browser to freeze.

A long-term solution is allowing the thumbnails to be uploaded to the storage providers to be validated internally, but for now it seems that the solution should be to simply validate that the thumbnails provided from external sources are not above a certain size.

**Comment by kdembler** [comment]
Do you mean this validation as part of the publishing flow? A malicious actor could still do the thing you've described using CLI or manually constructing a transaction, right?

**Comment by blrhc** [comment]
I think even a CLI validation would not work since an attacker could create a video with `example.com/bad.jpg` as a thumbnail which originally represents a 10KB JPEG then replace it with an 100MB one with the same name `example.com/bad.jpg` on their server once the CLI validation has passed.

So a good solution would almost be to take the image URL from the CLI input, make a copy of the image on our own CDN to ensure it is the same file within the constraints (i.e. importing the file rather than just the URL, which can be made to represent anything) and then just use this image.

Clearly that would be a temporary solution in advance of images being supported by Storage Providers.

**Comment by kdembler** [comment]
Yeah, I guess to pin this down we will need something more sophisticated than just validation, like you've mentioned. However, it can be a good first step to validate in publishing experience

**Comment by blrhc** [comment]
Definitely agree - at this stage there is a very low incentive for this kind of attack anyway, just useful to be aware.
