### ISSUE TITLE
Easy video preview

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#883]
Currently in implementation there is a solution for that - a button in more dropdown on video tile - to see the video in the viewer side of the product. However this might be not the ideal solution for this experience - might need a more prominent pattern.

**Comment by KubaMikolajczyk** [comment]
If we can develop a solution for one click opening of the video this would be worth exploring.

**Comment by bedeho** [comment]
# Feedback

Not sure if I was supposed to give feedback here in this issue, but didn't find anywhere else.

- I agree with your basic point that launching the video should be the primary action.
- I did not understand why the edit button required a black framing box, while the other "launch workspace" button did not? I certainly think having a clear hover state is great, and that helps with this, however not sure why they should be treated differently.
- What is the difference between the edit and open in workspace buttons? Do we really need both?
- I assume that the playback is launched if you click anywhere, except the two other buttons? That is how the video tiles work everywhere else.

**Comment by KubaMikolajczyk** [comment]
- Great so I will set primary action to launching a video
- This black background is there for contrast better icon visibility and easier function discoverability 
- Yes, you're right - I didn't see that - both buttons on top are doing the same thing - I would remove the open in workspace button located in the top left corner for now and leave just edit video icon button - but in the future, we might want to think about using the space in the top left corner for the checkbox for bulk actions for video tiles (just a mental note though). 
- Yes the playback would be launched by clicking on the video title, or video tile anywhere - only not on edit button or context menu button

**Comment by KubaMikolajczyk** [comment]
https://www.loom.com/share/e748fd67207f4f5fb7ca8005a4d32f69

**Comment by kdembler** [comment]
This has been designed and implemented - closing
