### ISSUE TITLE
Membership card hover state

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#891]
Currently in implementation the membership card has a lighten hover effect which is different from the other card hovers we use consistently on the platform - this could be aligned with the designs here: https://www.figma.com/file/rBjfm2tJ2Pr9M0UNTduU9v/Joystream-Atlas?node-id=6745%3A148

**Comment by kdembler** [comment]
Closing this since we are removing membership cards altogether as part of #1653
