### ISSUE TITLE
Playlist RWD

### ISSUE THREAD

**Issue by KubaMikolajczyk** [Joystream/atlas#895]
RWD for playlist page is needed.

**Comment by dmtrjsg** [comment]
Addressed as acceptance criteria in the respective issues. Designs for reference: https://www.figma.com/file/XfKZ5ZSavt88rVfiKf0tBv/Playlist%3A-Channel-owner?node-id=902%3A29109
https://www.figma.com/file/f6pcaMR7bryFmszfrzTqJM/Playlist-details-page?node-id=203%3A202
