### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by phaitonican** [Joystream/atlas#903]
I have a question does the blockchain include tags? Sorry

**Comment by kdembler** [comment]
Could you explain a bit more on what you're referring to as "tags" here? Each video has a category, it currently doesn't have tags like you would see on Twitter

**Comment by phaitonican** [comment]
i dont know much technical stuff about blockchain, but i thought a string array where u include tags or have inline tags in the description like on twitter, but that would be a frontend thing then...

**Comment by kdembler** [comment]
We currently don't include anything like that in video metadata, it may be added in the future

**Comment by kdembler** [comment]
Since this doesn't look like a feature request, I'm gonna close this. If you'd like to see a feature like that added, please open a new issue with some more details of what you'd like to see and we can take it from there
