### ISSUE TITLE
Wrong video player sizing for non-wide aspect ratios

### ISSUE THREAD

**Issue by blrhc** [Joystream/atlas#91]
![player_example1](https://user-images.githubusercontent.com/4144334/100857027-0fc79e80-3484-11eb-8b8b-75c2a979362f.jpeg)
![player_example2](https://user-images.githubusercontent.com/4144334/100857034-12c28f00-3484-11eb-84d6-519f2b8eee09.jpeg)

On my screen I need to scroll down to view the controls of 480p videos (usually the older content e.g. videos on the Classic Documentaries or Classic Cartoons channels).

It seems that the height of this element should be reduced to allow easy access to the video controls.

![video](https://user-images.githubusercontent.com/4144334/100858053-608bc700-3485-11eb-830d-ca8c58c06f94.gif)

I was using Google Chrome and my screen size is 1680x1050.

**Comment by kdembler** [comment]
Fixed by #206
