### ISSUE TITLE
Figma Reorganisation

### ISSUE THREAD

**Issue by milosz-klimek** [Joystream/atlas#920]
The goal of our Figma reorganisation is to set up a scalable & future-proof file structure. 

Aim:
- [ ] Atomic / Shared Component Library approach 
- [ ] New structure that avoids Figma's RAM storage limits 
- [ ] Framework development which will express the status of particular flows _Done/In progress/On hold_ 
- [ ] Transfer to new set-up
- [ ] TBA

**Comment by kdembler** [comment]
We have been iteratively working on this for some time now, I don't think we really need this issue so closing
