### ISSUE TITLE
Broken error handling on loading

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#94]
I still get this error handler, what causes it? We need something more graceful designed

![Screenshot 2020-12-02 at 11 39 11](https://user-images.githubusercontent.com/437292/100862559-9b94f700-3493-11eb-86ad-cc22abcd8853.png)

**Comment by fcescob** [comment]
This is working as intended, the `Featured videos` query we do is not implemented in the query node (this will be fixed soon, likely after  is merged) therefore the gallery gets an errors and catches it correctly. The design could use some help, I agree.
