### ISSUE TITLE
Videos Uploaded via Atlas are not Playing.

### ISSUE THREAD

**Issue by elif42** [Joystream/atlas#985]
The vast majority of the videos I have uploaded via Atlas have not been playing. I have used different OSs (Mac, Windows, Ubuntu) and browsers (Brave, Chrome, Firefox). I have created new accounts and new channels, all to no avail. I have used different ISPs, worked with and without VPNs, with the same result. Of the last 30 or so videos I uploaded, only 4 or so are playing, and I have been forced to delete the rest.

**Comment by elif42** [comment]
Fixed.

**Comment by elif42** [comment]
Fixed

**Comment by bedeho** [comment]
Hi, very sorry to hear that you had a bad experience, we want to correct this and also give you some credit. Would you mind sharing a bit more about what have tried, and what the fix was?

**Comment by elif42** [comment]
@bedeho Thank you. It's been fixed. It seems that the videos sometimes don't propagate quickly. They all eventually play, so I have learned to stop deleting and re-upping them. 😁

**Comment by bedeho** [comment]
But I think still this is not a good enough solution, we need to improve the product to avoid whatever initially confused you. Can you describe step by step what you did, what you expected, and what happened, before you learned how it works? This means a ton to us to get right 🙏
