### ISSUE TITLE
Bug: video upload issues

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#995]
A user on discord (ZAZIK) has uploaded the following video showing problems with uploading another video: 
https://play.joystream.org/video/3182

I have checked their storage quota and there should be no issue uploading the video they're having issues uploading (it is 234 MB and they have approximately 2.5 GB of quota available). We do currently have one storage provider down (out of 10) so maybe this is causing complications.

In this case the transaction is broadcast successfully, the video uploads to 100% but then ends up with a broken asset link error.

This may just be a specific browser/video issue or it could relate to the storage network having issues, in any case the video will hopefully be helpful in showing first hand the user experience in a situation like this.

**Comment by kdembler** [comment]
The recent upload flow improvements should take care of the vast majority of problems like this so closing the issue. In case this persist, we can investigate further
